### ISSUE TITLE
可不可以出一版python版的runtime代码？

### ISSUE THREAD

**Issue by YY007H** [wenet-e2e/wenet#1005]
c++代码不熟悉，很多地方都看不懂，想用python来实现runtime，但又无从下手

**Comment by SWHL** [comment]
这个可以参考我们整理的 [RapidASR](https://github.com/RapidAI/RapidASR/tree/main/python)

**Comment by YY007H** [comment]
> 这个可以参考我们整理的 [RapidASR](https://github.com/RapidAI/RapidASR/tree/main/python)

大佬，已经阅读了你们的代码，但是未发现实时识别python端的处理代码，想直接在python中启用websocket来搭建服务

**Comment by SWHL** [comment]
- 实时识别的处理代码没有整理
- 基于RapidASR python部分，可以自行改写

**Comment by jiay7** [comment]
以前写过一个极其简陋的代码。https://github.com/jiay7/wenet_onlinedecode.git

**Comment by libo87** [comment]
you can try wenet.transformer.asr_model.ASRModel.attention_rescoring

**Comment by qiuyuzhao** [comment]
> 这个可以参考我们整理的 [RapidASR](https://github.com/RapidAI/RapidASR/tree/main/python)
在运行RapidASR回提示ValueError: negative dimensions are not allowed，定位问题是feature.py里
def sliding_window(x, window_size, window_shift):
    shape = x.shape[:-1] + (x.shape[-1] - window_size + 1, window_size)
    strides = x.strides + (x.strides[-1],)
    return np.lib.stride_tricks.as_strided(x, shape=shape, strides=strides)[::window_shift]
只要x.shape[-1] - window_size + 1 小于0 就会报错请问大佬是为什么？

**Comment by qiuyuzhao** [comment]
> 以前写过一个极其简陋的代码。https://github.com/jiay7/wenet_onlinedecode.git

您这份代码加载那个模型的文件？
