### ISSUE TITLE
C++ memory leak

### ISSUE THREAD

**Issue by BarryKCL** [wenet-e2e/wenet#1017]
代码环境：目前最新的runtime代码改成GPU推理
libtorch版本：libtorch-cxx11-abi-shared-with-deps-1.9.0%2Bcu102.zip
测试代码：decoder_main.cc，单线程
现象：1.处理单个音频时，显存会涨到一个固定值，推理结束后不会下降；2.处理多个音频时，长音频比短音频显存增长快，增长是叠加式的，推理结束后显存不会下降。
![image](https://user-images.githubusercontent.com/48039828/162166546-2519f78c-cb05-4a5c-bd4c-f15f65300506.png)

**Comment by hacjac** [comment]
可能是内存碎片化导致的。我也遇到了同样的问题。我们分析是我们业务中会使用多线程，且计算过程的张量大小变化大，导致了内存碎片化。然后我用jemalloc替换了c++默认的内存分配器，就解决了。
