### ISSUE TITLE
Can export onnx model that support streaming?

### ISSUE THREAD

**Issue by murphypei** [wenet-e2e/wenet#1021]
I get an onnx model by using export_onnx.py，but it doesn't seem to support streaming decoder. I wonder if there is any way to do this?

**Comment by Slyne** [comment]
Yes, the previous export_onnx.py (now export_onnx_gpu.py) can only export models for offline inference, which is targeted for the x86_gpu.   I think there will be one export_onnx.py that can export the streaming models to be deployed in decoder_main soon.

As for gpu streaming onnx/tensorrt implementation, we only have an internal solution. If you are interested, I can share with you the project.

**Comment by murphypei** [comment]
> Yes, the previous export_onnx.py (now export_onnx_gpu.py) can only export models for offline inference, which is targeted for the x86_gpu. I think there will be one export_onnx.py that can export the streaming models to be deployed in decoder_main soon.
> 
> As for gpu streaming onnx/tensorrt implementation, we only have an internal solution. If you are interested, I can share with you the project.

Thanks, looking forward to your sharing

**Comment by Slyne** [comment]
@murphypei  You should now be able to access [here](https://github.com/nvidia-china-sae/CISI/tree/main/asr/wenet_online)
BTW, I can see there's one pr related to this : https://github.com/wenet-e2e/wenet/pull/921

**Comment by murphypei** [comment]
> @murphypei You should now be able to access [here](https://github.com/nvidia-china-sae/CISI/tree/main/asr/wenet_online) BTW, I can see there's one pr related to this : #921

Thanks

**Comment by Slyne** [comment]
@chiendb97  done. 

@murphypei   @chiendb97    Notice since wenet recently just releases a new streaming API, we'll follow up this new streaming API and update a new version soon.    Please also keep an eye on this pr: https://github.com/wenet-e2e/wenet/pull/1023

**Comment by murphypei** [comment]
> @chiendb97 done.
> 
> @murphypei @chiendb97 Notice since wenet recently just released a new streaming API, we'll follow up this new streaming API and update a new version soon. Please also keep an eye on this pr: #1023

Thanks
