### ISSUE TITLE
Empty context file leads to Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Adam-fei** [wenet-e2e/wenet#1022]
**Describe the bug**
Using compiled runtime x86 server **websocket_server_main**. When passing argument --context_path $context_path, if this context file is empty, then calling server leads to Segmentation fault (core dumped)

**To Reproduce**
running following command
```
./build/websocket_server_main --port $port --chunk_size $chunk_size --model_path $model_path --context_path $context_path --context_score $context_score --dict_path $dict_path
```
**_keep file $context_path empty._**

Then calling the server using:
```
./build/websocket_client_main --host $host --port $port --wav_path $wave_path
```
following error will pop out:

```
3093774 Segmentation fault      (core dumped)
```
**Additional context**
Pay attention to line23, empty context file has been considered, but would lead to core dump somewhere else
https://github.com/wenet-e2e/wenet/blob/1e6f751e1783c6835be5e4a0cb5e45424dcfc07e/runtime/core/decoder/context_graph.cc#L16-L26

**Comment by xiangxyq** [comment]
Hi, coredump reason is that, ContextGraph initialize [runtime/core/decoder/params.h](https://github.com/wenet-e2e/wenet/blob/main/runtime/core/decoder/params.h)  line 130~142, FLAGS_context_path file content is empty, so query_contexts is empty, when ContextGraph constructor, graph_ pointer is still nullptr, after BuildContextGraph function finished, graph_ pointer is not nullptr

I think can be fixed as below:
` void ContextGraph::BuildContextGraph( 
     const std::vector<std::string>& query_contexts, 
     const std::shared_ptr<fst::SymbolTable>& symbol_table) { 
   CHECK(symbol_table != nullptr) << "Symbols table should not be nullptr!"; 
   start_tag_id_ = symbol_table->AddSymbol("<context>"); 
   end_tag_id_ = symbol_table->AddSymbol("</context>"); 
   symbol_table_ = symbol_table; 
   if (query_contexts.empty() && !graph_) { 
     graph_.reset(); 
     return; 
   } `

Thanks
