### ISSUE TITLE
想问下如何进行热词添加？

### ISSUE THREAD

**Issue by tcexeexe** [wenet-e2e/wenet#1035]
是否有相关教程和文档？

**Comment by xiangxyq** [comment]
hi,
maybe this doc can help you:  https://wenet.org.cn/wenet/context.html

**Comment by xiaobobo-bilibili** [comment]
请问wenet中基于context graph的热词方案和基于前缀树的热词方案有什么区别？

**Comment by tcexeexe** [comment]
> hi, maybe this doc can help you: https://wenet.org.cn/wenet/context.html

非常感谢！还想请教一下，如果需要在字典里面添加新的字，然后在预训练模型的基础上做微调，这样是否可行？

**Comment by pengzhendong** [comment]
> 请问wenet中基于context graph的热词方案和基于前缀树的热词方案有什么区别？

@xiaobobo-bilibili 参考这篇文章：https://zhuanlan.zhihu.com/p/434421921

**Comment by pengzhendong** [comment]
> > hi, maybe this doc can help you: [wenet.org.cn/wenet/context.html](https://wenet.org.cn/wenet/context.html)
> 
> 非常感谢！还想请教一下，如果需要在字典里面添加新的字，然后在预训练模型的基础上做微调，这样是否可行？

可行，不过最后一个全连接层需要重新训

**Comment by xiaobobo-bilibili** [comment]
> 

多谢您的回复，这篇文章我之前有看过。我想了解的是context graph的方案相比prefix tree的方案有些什么优势。我理解这两种方案在实际使用中都是提供context graph/prefix tree的指针/状态给到正常解码的路径上，只是判断是否出词，context graph是回到原始节点，prefix tree是走到叶子节点。

**Comment by pengzhendong** [comment]
没有做过详细的比较，因为先有了语言模型，引入了 OpenFST，于是就直接用 fst 来做。

> > 
> 
> 多谢您的回复，这篇文章我之前有看过。我想了解的是context graph的方案相比prefix tree的方案有些什么优势。我理解这两种方案在实际使用中都是提供context graph/prefix tree的指针/状态给到正常解码的路径上，只是判断是否出词，context graph是回到原始节点，prefix tree是走到叶子节点。
