### ISSUE TITLE
rtf and chunk do not match

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#1038]
Hi，When I test, the accuracy will be better as the chunk increases. But the rtf will increase as the chunk decreases. Is this normal? Shouldn't the smaller the chunk's RTF be?

model：u2++_conformer
use_dynamic_chunk: true
use_dynamic_left_chunk: false
ctc_weight: 0.3

**Comment by robin1001** [comment]
It's normal, please refer our paper for more details. https://arxiv.org/pdf/2102.01547.pdf
