### ISSUE TITLE
why deletion errors increase when decoding with LM model ?

### ISSUE THREAD

**Issue by unkwner** [wenet-e2e/wenet#1039]
When decoding without language model , the deletion error is 4% ，than with language model , the deletion error is 11%. Has anyone met ？ why does this happen ?

My language model is trained by aishell1 script in wenet  and the words.txt size is 46791 created by language model training script.

I also used --deletion_penalty option ，but it not work.

such as :
ref: wifi 是 什么
the decoding result is : 是 什么 ， “wifi” always fails to decode.

**Comment by robin1001** [comment]
it's reasonable, LM always results in more deletion error. please adust the acoustic scale to balance the LM/AM.
