### ISSUE TITLE
延时怎么计算的

### ISSUE THREAD

**Issue by joinhe** [wenet-e2e/wenet#1040]
在论文中延时计算 ：
                        And the total model latency of our model is (chunk/2∗4+ 6)∗10 (ms), where 4 is the subsampling rate,6 is the lookahead introduced by the first two CNN layers in the encoder and 10 is the frame shift.  
在代码中：
                 if (opts_.chunk_size > 0) {
    if (!start_) {                      // First batch
      int context = right_context + 1;  // Add current frame
      num_requried_frames = (opts_.chunk_size - 1) * subsampling_rate + context;   //需要的解码帧
    } else {
      num_requried_frames = opts_.chunk_size * subsampling_rate;
    }
  } else {
    num_requried_frames = std::numeric_limits<int>::max();
  }

 (chunk/2∗4+ 6)∗10 ms   与  num_requried_frames = (opts_.chunk_size - 1) * subsampling_rate + context  区别在哪？

**Comment by robin1001** [comment]
`(chunk/2∗4+ 6)∗10 ms` computes the average latency.
