### ISSUE TITLE
Why waveform * (1 << 15) in tools/compute_cmvn_stats.py

### ISSUE THREAD

**Issue by panxin801** [wenet-e2e/wenet#1042]
Hello,
When reading the source code of `tools/compute_cmvn_stats.py` in line about 49, I find `waveform=waveform *(1<<15)`.
I know `1<<15=32768` but why times the waveform then ,I am a little bit confused about this operation. Can you help me  and thanks in advance

**Comment by robin1001** [comment]
torchaudio normalizes the sample point to -1.0 and 1.0 automatically. Here we convert it to 16 bits representation by `waveform=waveform *(1<<15)`

**Comment by panxin801** [comment]
Understood, thanks robin

**Comment by panxin801** [comment]
Oh sorry for the question again, I wonder if set the flag `normalize=False ` in `torchaudio.backend.sox_io_backend.load`,  the result will be the same with the current waveform ?

**Comment by robin1001** [comment]
Yes,  1waveform=waveform *(1<<15)` does the same works as `normalize=False`

**Comment by panxin801** [comment]
got it thanks a lot
