### ISSUE TITLE
support input wav resampling

### ISSUE THREAD

**Issue by ftdzh1994** [wenet-e2e/wenet#1060]
An error occurs when I try to recognize a 24K rate audio.
```
Check failed: wav_reader.sample_rate() == FLAGS_sample_rate (24000 vs. 16000)
```
I checked the source code, it seems that the audio rate resample is only done in the processing of training but not in predicting. Giving supports to this use scenario will be an every convenient and powerful feature for deployment.

Also I'm trying to implement this feature by my own. But I'm not familiar with c++ and dunno how runtime stuff works. where should I add this **resampling input wav file feature** into? in the python file `recognize.py`, or in the `decoder_main.cc`?

**Comment by xiangxyq** [comment]
when use decoder_main.cc to predict 24k wav, maybe you should set --sample_rate=24000
such as:
./build/decoder_main \
   --sample_rate=24000 \
    --chunk_size -1 \
    --wav_path $wav_path \
    --model_path $model_dir/final.zip \
    --dict_path $model_dir/lang_char_symbol.txt | tee log.txt
