### ISSUE TITLE
decoder_main 如何在x64计算机上编译呢？

### ISSUE THREAD

**Issue by 529261027** [wenet-e2e/wenet#1061]
在runtime/server中只看到了x86，如何在x64上如何编译呢？
按照x86方法，编译出错了

**Comment by 529261027** [comment]
Linux
![image](https://user-images.githubusercontent.com/37971318/165681062-385bb05e-a713-4354-a49e-b05f9fbe564c.png)

**Comment by xiangxyq** [comment]
请问下你用的是Ubuntu多少版本的，gcc版本是什么？

这个好像和x86 x64没有关系，试一试使用这个命令看看: 
`cmake -DINTTYPES_FORMAT:STRING=C99 ..
make
`

**Comment by espider** [comment]
我也遇到了同样的问题，“cmake -DINTTYPES_FORMAT:STRING=C99” 也是一样的

**Comment by pengzhendong** [comment]
The x86 we said is x86_64. Please update your system and then install the develop tools by:
* ubuntu: `apt-get update && apt-get install -y git cmake wget build-essential`
* centos: `yum install git cmake && yum groupinstall 'Development Tools'`
