### ISSUE TITLE
how to set num_decoding_left_chunks for export_onnx_cpu.py

### ISSUE THREAD

**Issue by meixitu17** [wenet-e2e/wenet#1062]
Hi,
    Thanks for your awesome work.

    I have a question for the export_onnx_cpu.py, there is a parameter named num_decoding_left_chunks, I don't know how to set it reasonable, I want to get a balance accuracy and inference time.

    I checked your pre-trained model, num_decoding_left_chunks = -1, use_dynamic_left_chunk = false, it means all of the left chunks are used. if I set a small value for inference, will it hurt the accuracy?

    and at export_onnx_cpu.py, line 95, att_mask[:, :, :required_cache_size] = 0, does it means you don't use left chunk for attention?  I am confused, I should make some mistake. could you kindly explain it?

Thanks

meixitu

**Comment by robin1001** [comment]
@xingchensong

**Comment by xingchensong** [comment]
yes, use -1 during training but other ‘left _chunks’ (let’s say 4) during inference will definitely hurt the accuracy
