### ISSUE TITLE
[Question]What's the difference between WenetSpeech's pretained model to others?

### ISSUE THREAD

**Issue by tcexeexe** [wenet-e2e/wenet#1073]
Hello~
In the WenetSpeech's pretained model, there are only four files:
```
20211025_conformer_exp/global_cmvn
20211025_conformer_exp/words.txt
20211025_conformer_exp/final.pt
20211025_conformer_exp/train.yaml
```
but in other pretrained model, there are several files in 'final.zip'. What's the difference between them? And how to convert it?

**Comment by pengzhendong** [comment]
Documents are all you need. https://github.com/wenet-e2e/wenet/blob/main/docs/pretrained_models.md

**Comment by tcexeexe** [comment]
> Documents are all you need. https://github.com/wenet-e2e/wenet/blob/main/docs/pretrained_models.md

Thanks!
