### ISSUE TITLE
docker image with cuda support

### ISSUE THREAD

**Issue by Rikka93** [wenet-e2e/wenet#1074]
**Is your feature request related to a problem? Please describe.**
the official docker image comes without CUDA installed.

it can not utilize GPU for inference

**Describe the solution you'd like**
Make a docker image based on, for example,`pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime`

**Comment by robin1001** [comment]
There is no plan to support GPU docker. And please see https://github.com/wenet-e2e/wenet/tree/main/runtime/server/x86_gpu for how to  build your own GPU docker over tritonserver.
