### ISSUE TITLE
The WenetSpeech's Runtime Model works incorrectly

### ISSUE THREAD

**Issue by tcexeexe** [wenet-e2e/wenet#1077]
Hello~
l use the following command form the wenet/examples/wenetspeech/s0/run.sh to convert Checkpoint Model to Runtime Model. 
```
. ./path.sh || exit 1;

# Use this to control how many gpu you use, It's 1-gpu training if you specify
# just 1gpu, otherwise it's is multiple gpu training based on DDP in pytorch
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
export CUDA_VISIBLE_DEVICES="0"
stage=0
stop_stage=6

# The num of nodes
num_nodes=1
# The rank of current node
node_rank=0
if [ ${stage} -le 6 ] && [ ${stop_stage} -ge 6 ]; then
  echo "Export the best model you want"
  python wenet/bin/export_jit.py \
    --config /home/tcexeexe/dataDisk2/asr/WeNet/weights/20211025_conformer_exp/train.yaml \
    --checkpoint /home/tcexeexe/dataDisk2/asr/WeNet/weights/20211025_conformer_exp/final.pt \
    --output_file ./final.zip
fi
```
And add cmvn filepath to the train.yaml
![1651511680(1)](https://user-images.githubusercontent.com/28287196/166293523-aed637e9-dc9c-4b49-b611-16da094e6b1a.png)
 But after the train.zip generated and when l use docker form `https://github.com/wenet-e2e/wenet/tree/main/runtime/server/x86` to test the result, it seems that the model dosen't work. The sample wav file comes from the train set of WenetSpeech
![1651511983(1)](https://user-images.githubusercontent.com/28287196/166294241-447c5345-f2b1-4d43-8715-8dfee733deaa.png)
Can you give some advice about it? Thanks a lot!

**Comment by pengzhendong** [comment]
The pretrained model is a non streaming model. Please set the chunk_size to -1.

**Comment by tcexeexe** [comment]
> The pretrained model is a non streaming model. Please set the chunk_size to -1.

@pengzhendong l use the order as follow to test the local file, but it still work incorrectly. Is there anything else wrong with my steps?
```
wav_path=/home/wenet/runtime/server/x86/docker_resource/S00017.wav
model_dir=docker_resource/model/20211025_conformer_exp
 /home/wenet/runtime/server/x86# ./build/decoder_main     --chunk_size -1     --wav_path $wav_path     --model_path $model_dir/final.zip     --dict_path $model_dir/words.txt 2>&1 | tee log.txt
```
![b259eaaedcf49208c72f7cde6eecb02](https://user-images.githubusercontent.com/28287196/166403561-6f98984f-eb67-42ce-acc1-647cdc45dfbe.png)
