### ISSUE TITLE
Errors occurred when execute binary decoder_main when compiled the whole source code

### ISSUE THREAD

**Issue by shone666** [wenet-e2e/wenet#1084]
**Describe the bug**
base on: commit: 050f04172b7f3d9dae104ed871dd404b24ed15b6
When finished compile the whole source code, then execute binary decoder_main, Errors occurred as below:
./decoder_main --chunk_size -1 --model_path wenet_wenetspeech/assets/final.zip --dict_path wenet_wenetspeech/assets/words.txt --wav_path data/tiaoguoyure.wav
terminate called after throwing an instance of 'c10::Error'
  what():  forward_encoder_chunk() Expected a value of type 'Optional[List[Tensor]]' for argument 'elayers_output_cache' but instead found type 'Tensor'.
Position: 5
Declaration: forward_encoder_chunk(__torch__.wenet.transformer.asr_model.ASRModel self, Tensor xs, int offset, int required_cache_size, Tensor? subsampling_cache=None, Tensor[]? elayers_output_cache=None, Tensor[]? conformer_cnn_cache=None) -> ((Tensor, Tensor, Tensor[], Tensor[]))
Exception raised from checkArg at ../aten/src/ATen/core/function_schema_inl.h:184 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f618a92a75b in /home/victor/shone/work/project/WeNet/wenet/wenet_0505/wenet-main/runtime/server/x86/fc_base/libtorch-src/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xce (0x7f618a92638e in /home/victor/shone/work/project/WeNet/wenet/wenet_0505/wenet-main/runtime/server/x86/fc_base/libtorch-src/lib/libc10.so)
frame #2: <unknown function> + 0x125ec22 (0x7f617584fc22 in /home/victor/shone/work/project/WeNet/wenet/wenet_0505/wenet-main/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x1262fa1 (0x7f6175853fa1 in /home/victor/shone/work/project/WeNet/wenet/wenet_0505/wenet-main/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #4: torch::jit::GraphFunction::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) + 0x2d (0x7f617813b39d in /home/victor/shone/work/project/WeNet/wenet/wenet_0505/wenet-main/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #5: torch::jit::Method::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) const + 0x175 (0x7f617814aab5 in /home/victor/shone/work/project/WeNet/wenet/wenet_0505/wenet-main/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #6: ./decoder_main() [0x5d0c39]
frame #7: ./decoder_main() [0x499538]
frame #8: ./decoder_main() [0x4940be]
frame #9: ./decoder_main() [0x493c82]
frame #10: ./decoder_main() [0x47ba38]
frame #11: __libc_start_main + 0xe7 (0x7f6172e78bf7 in /lib/x86_64-linux-gnu/libc.so.6)
frame #12: ./decoder_main() [0x47a26a]

Aborted (core dumped)

**To Reproduce**
1. Go to 'wenet/runtime/server/x86'
2. mkdir build
3. cd build
4. cmake ..
5. cmake build .
6. ./decoder_main --chunk_size -1 --model_path wenet_wenetspeech/assets/final.zip --dict_path wenet_wenetspeech/assets/words.txt --wav_path data/tiaoguoyure.wav

**Smartphone (please complete the following information):**
 - Device: [x86 PC]
 - OS: [ubuntu 18.04]
 - Version [wenet source code commit: 050f04172b7f3d9dae104ed871dd404b24ed15b6]

**Comment by pengzhendong** [comment]
Please see https://github.com/wenet-e2e/wenet/issues/1065
