### ISSUE TITLE
tlg runtime decode question

### ISSUE THREAD

**Issue by Yymax-max** [wenet-e2e/wenet#1087]
for (int i = 0; i < nbest; i++) {
      kaldi::LatticeWeight weight;
      std::vector<int> alignment;
      fst::GetLinearSymbolSequence(nbest_lats[i], &alignment, &outputs_[i],
                                   &weight);
      ConvertToInputs(alignment, &inputs_[i], &times_[i]);
      RemoveContinuousTags(&outputs_[i]);
      likelihood_[i] = -weight.Value2();
    }

in ctc_wfst_beam_search.cc why likelihood_[i] = -weight.Value2() is not likelihood_[i] = -(weight.Value1()+weight.Value2())?

**Comment by robin1001** [comment]
It should be likelihood_[i] = -(weight.Value1()+weight.Value2()) if we want the sum of acoustic score and lm score.

**Comment by Yymax-max** [comment]
> It should be likelihood_[i] = -(weight.Value1()+weight.Value2()) if we want the sum of acoustic score and lm score.

thank you for your answer ,i approve your answer, but why ctc_wfst_beam_search.cc is likelihood_[i] = -weight.Value2(),-weight.Value2() is likely acoustic score , only add it ,what the mean of the tlg

**Comment by robin1001** [comment]
https://github.com/wenet-e2e/wenet/pull/1116

Please see the PR, we use both acoustic and graph cost now.
