### ISSUE TITLE
Added key: store_based_barrier_key:1 to store for rank: 0

### ISSUE THREAD

**Issue by kejom-ou** [wenet-e2e/wenet#1097]
**Describe the bug**
单机多卡分布式训练时出现
Added key: store_based_barrier_key:1 to store for rank: 0
2022-05-09 22:30:27,597 INFO Waiting in store based barrier to initialize process group for rank: 0, key: store_based_barrier_key:1 (world_size=6, worker_count=287, timeout=0:30:00)
猜测是每张卡的进程无法通讯，能否解决一下
![image](https://user-images.githubusercontent.com/54171620/167546102-7829ca4e-19a1-4563-9a83-32c3c9e1df8c.png)

**Comment by robin1001** [comment]
delete the `ddp_init` file and try again.

**Comment by kejom-ou** [comment]
it works,thanks

**Comment by sumorday** [comment]
您好 怎么解决的呢？ 是删掉文件重新来？我没有看到自己的ddp_init文件呢，虽然确实是ddp训练

**Comment by kejom-ou** [comment]
好像在保存checkpoint目录下，每次训练前先删掉

**Comment by zhangze1** [comment]
I also had the same problem, did you solve it？

**Comment by sumorday** [comment]
看上去你的5个gpu不是运行起来了吗？
内存不足吗？后面的error信息没有看到。
如果是cuda out of memory，那么
这里有一个方法限制内存大小，但是对于我来讲无用
os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "max_split_size_mb:<enter-size-here>"

https://stackoverflow.com/questions/73747731/runtimeerror-cuda-out-of-memory-how-setting-max-split-size-mb

如果你用的ddp，我自己是把batch size改小
比如原来是如下：
--batch_size_D=64 
--batch_size_G=128
--accumulation=1

我改成
--batch_size_D=32 
--batch_size_G=64
--accumulation=2

注意， accumulation乘以新的batch size和原来的大小一致那就可以了。
--batch_size_D=16
--batch_size_G=32
--accumulation=4
其实这样也可以。但不建议改太小。

目前自己的解决方法只有这个
