### ISSUE TITLE
Please offer me the lexicon.txt and units.txt of multi_cn recipe

### ISSUE THREAD

**Issue by shushanxingzhe** [wenet-e2e/wenet#1100]
@whiteshirt0429 @fanlu  Would you please send me the lexicon.txt and units.txt of multi_cn recipe. Since I cannot get all corpus for multi_cn recipe, so I cannot rebuild this files by myself. But I want to build TLG lm to enhance multi_cn model. Thanks you in advance.

**Comment by robin1001** [comment]
You should apply the data from the offcial site of each dataset in multi_cn.
