### ISSUE TITLE
word align timestamp error in some audios

### ISSUE THREAD

**Issue by xiangxyq** [wenet-e2e/wenet#1106]
**Describe the bug**

If an audio has the following three cases:
1. starts with a piece of noise or sil
2. ends with a piece of noise or sil
3. has a piece of noise or sil between two speech in an audio

such as below audio decode result(case 1, 2)
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/18209169/168411470-cdeabeba-c90b-4ca3-8684-0e88d42f6c70.png">

**Expected behavior**
a word should more accurate

Test audio:
[test.zip](https://github.com/wenet-e2e/wenet/files/8692306/test.zip)

**Comment by xiangxyq** [comment]
I submit a pr #1107 , but I think it is not a good solution, details description as pr comment.

**Comment by pengzhendong** [comment]
PR https://github.com/wenet-e2e/wenet/pull/1107 merged.
