### ISSUE TITLE
runtime decoding bug 

### ISSUE THREAD

**Issue by agreatbush** [wenet-e2e/wenet#1114]
while decoding , i got the error. I have finished building  TLG. There seems some error in decoder_main

> perl: warning: Setting locale failed.
> perl: warning: Please check that your locale settings:
>         LANGUAGE = (unset),
>         LC_ALL = (unset),
>         LANG = "en_US.UTF-8"
>     are supported and installed on your system.
> perl: warning: Falling back to the standard locale ("C").
> ./tools/decode.sh: line 61: 28410 Aborted                 (core dumped) decoder_main --rescoring_weight $rescoring_weight --ctc_weight $ctc_weight --reverse_weight $reverse_weight --chunk_size $chunk_size --wav_scp ${dir}/split${nj}/wav.${n}.scp --model_path $model_file --dict_path $dict_file $wfst_decode_opts --result ${dir}/split${nj}/${n}.text &> ${dir}/split${nj}/${n}.log

Thanks in advance.

**Comment by agreatbush** [comment]
by the way, I'm training on Gigaspeech recently. I have tried training on 30h of it for 200 epochs with 1e-5 lr ,but I got wer around 60%, is this normal?

**Comment by wwfcnu** [comment]
我也遇到了这个问题，请问怎么解决的
