### ISSUE TITLE
python binding local build failed

### ISSUE THREAD

**Issue by ftdzh1994** [wenet-e2e/wenet#1130]
**Describe the bug**
the WeNet python binding fails to built locally after the latest update. 
`error: [Errno 2] No such file or directory: '/home/wenet/runtime/binding/python/fc_base/openfst-subbuild/openfst-populate-prefix/lib/libfstscript.so'
`

**Tried in following OS (please complete the following information):**
 - MacOS 11.2.2
 - Ubuntu 20.04.3 LTS

**Additional context**
[install_log.txt](https://github.com/wenet-e2e/wenet/files/8714253/install_log.txt)

**Comment by pengzhendong** [comment]
Try again.
