### ISSUE TITLE
不带CTC训练性能会非常差

### ISSUE THREAD

**Issue by chenwuchen** [wenet-e2e/wenet#1145]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chenwuchen** [comment]
设置  ctc_weight: 0.0 训练结果非常差。

**Comment by robin1001** [comment]
Joint CTC/Attention always shows better result.
