### ISSUE TITLE
Complementary Language Models

### ISSUE THREAD

**Issue by AdolfVonKleist** [wenet-e2e/wenet#115]
Do you support complementary language models, do you plan to?  I didn’t notice any examples or related code in the repo.

**Comment by robin1001** [comment]
Yes, there is no language support now. It's in our plan, However it may takes long time since WeNet is designed production first and production ready, so we have to verify it works for production, easy to implement, and provide runtime support for LM.

**Comment by AdolfVonKleist** [comment]
Out of curiosity, have you found that the LM is largely unnecessary in your tasks? In most of the espnet egs it looks like it yields 1-3% absolute improvement in-domain.

**Comment by robin1001** [comment]
We haven't done the LM fusion experiment yet. Yes,  it seems LM helps from espnet for some dataset.
