### ISSUE TITLE
DLL load failed while importing _wenet: 找不到指定的模块。

### ISSUE THREAD

**Issue by billqu01** [wenet-e2e/wenet#1180]
我安装了wenet, pip install wenet.
安装提示成功了。
我用例子程序做识别。
程序如下：
import sys
import wenet

def get_text_from_wav(dir, wav):
    model_dir = dir
    wav_file = wav
    decoder = wenet.Decoder(model_dir)
    ans = decoder.decode_wav(wav_file)
    print(ans)

if __name__ == '__main__':
    dir = "./models"
    wav = "./1.wav"
    get_text_from_wav(dir,wav)

但是运行报错如下：
Traceback (most recent call last):
  File "D:\codes\speech2word\main.py", line 2, in <module>
    import wenet
  File "D:\codes\speech2word\venv\lib\site-packages\wenet\__init__.py", line 1, in <module>
    from .decoder import Decoder  # noqa
  File "D:\codes\speech2word\venv\lib\site-packages\wenet\decoder.py", line 17, in <module>
    import _wenet
ImportError: DLL load failed while importing _wenet: 找不到指定的模块。

请问如何解决？

**Comment by lfgogogo** [comment]
同问，是这个模块还在开发的意思吗

**Comment by robin1001** [comment]
@Mddct do you have time to figure out the problem?

**Comment by Mddct** [comment]
> 我安装了wenet, pip install wenet.
> 安装提示成功了。
> 我用例子程序做识别。
> 程序如下：
> import sys
> import wenet
> 
> def get_text_from_wav(dir, wav):
>     model_dir = dir
>     wav_file = wav
>     decoder = wenet.Decoder(model_dir)
>     ans = decoder.decode_wav(wav_file)
>     print(ans)
> 
> if __name__ == '__main__':
>     dir = "./models"
>     wav = "./1.wav"
>     get_text_from_wav(dir,wav)
> 
> 但是运行报错如下：
> Traceback (most recent call last):
>   File "D:\codes\speech2word\main.py", line 2, in <module>
>     import wenet
>   File "D:\codes\speech2word\venv\lib\site-packages\wenet\__init__.py", line 1, in <module>
>     from .decoder import Decoder  # noqa
>   File "D:\codes\speech2word\venv\lib\site-packages\wenet\decoder.py", line 17, in <module>
>     import _wenet
> ImportError: DLL load failed while importing _wenet: 找不到指定的模块。
> 
> 请问如何解决？
> 

Which python version and window are you using?

**Comment by lfgogogo** [comment]
Mine is python38 and win10.

**Comment by Mddct** [comment]
Could you use python3.6 using virtualenv to see if it has the same problem？ I'll reproduce when my env is done

**Comment by lfgogogo** [comment]
Using python 36 is ok.

**Comment by billqu01** [comment]
我安装了python 3.6，还是报一样的错误。

**Comment by Mddct** [comment]
can you find this so in wheel？

**Comment by Mddct** [comment]
can you put this so to your wheel folder to see if it can work

**Comment by Mddct** [comment]
Can you download libtorch and put this so (in libtorch/lib/libiomp5md.dll) to your wheel folder to see if it can work

https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.10.0%2Bcpu.zip

**Comment by xiongyihui** [comment]
putting `libiomp5md.dll` to the folder of `_wenet.cp38-win_amd64.pyd` works.
Thanks

**Comment by Mddct** [comment]
> putting `libiomp5md.dll` to the folder of `_wenet.cp38-win_amd64.pyd` works.
> Thanks

@pengzhendong will helpfix tomorrow

**Comment by Silent1user** [comment]
it show **cannot import name 'init_asr_model' from 'wenet.transformer.asr_model**.but I discover the **init_asr_model** has existed in it

**Comment by Silent1user** [comment]
> 它显示**无法从“wenet.transformer.asr_model”导入名称“init_asr_model**”，但我发现其中存在**init_asr_model**

how can I resovle the problem
