### ISSUE TITLE
为什么用GPU推理的时候会有这种错误

### ISSUE THREAD

**Issue by YanZiBuGuiCHunShiWan** [wenet-e2e/wenet#1196]
![BUG1](https://user-images.githubusercontent.com/58776907/171981526-a9523438-ad13-41bf-b861-f7d98ae01cf1.png)

**Comment by robin1001** [comment]
这里提示了，操作的两个 tensor 不在一个设备上，一个在 cpu 上，一个在 cuda 上。可以根据这个信息追一下。
