### ISSUE TITLE
编译binding/python时出现/usr/local/bin/ld: cannot find -lwenet_api

### ISSUE THREAD

**Issue by joewale** [wenet-e2e/wenet#1206]
Hi，我在编译binding/python，运行python setup.py install，出现以下错误，请问是什么原因？

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/9114449/172612370-d73d3b60-702d-493b-8476-1cde9b8beb80.png">

**Comment by joewale** [comment]
I build with onnx config as follow.
<img width="971" alt="image" src="https://user-images.githubusercontent.com/9114449/172618340-5f4fbbb2-8b0b-4ddb-a0bb-0a9138b5faa3.png">

And get the error below
[Uploading build.log…]()

**Comment by Mddct** [comment]
> I build with onnx config as follow.
> <img width="971" alt="image" src="https://user-images.githubusercontent.com/9114449/172618340-5f4fbbb2-8b0b-4ddb-a0bb-0a9138b5faa3.png">
> 
> And get the error below
> [Uploading build.log…]()
> 

Currently python bind does not support onnx, but you can  see ： https://github.com/wenet-e2e/wenet/pull/1178

**Comment by joewale** [comment]
I build successfully following https://github.com/wenet-e2e/wenet/pull/1178  Thanks
