### ISSUE TITLE
./decoder_main: undefined symbol: _ZN3fLS26FLAGS_fst_weight_separatorE

### ISSUE THREAD

**Issue by veelion** [wenet-e2e/wenet#1208]
**To Reproduce**
1. mkdir `build-torch` and `cd && camke ..`, run `decoder_main` successfully.
2. mkdir `build-onnx` and `cd && camke -DONNX=ON -DTORCH=OFF ..` , run `decoder_main` successfully.
3. go back to `build-torch/bin`, run `decoder_main` again, you'll get the error.

I've found that, after each building, the size of `libfst.so.8.0.0` are different.

**Comment by robin1001** [comment]
we have no idea on that, may be it is related to build options. You can just build with `-DONNX=ON` and `-DTORCH=ON` to enable them.

**Comment by veelion** [comment]
The reason was found. It's because of `TORCH_CXX_FLAGS` in openfst.cmake:
https://github.com/wenet-e2e/wenet/blob/46ae3eae79d89e86270bf58cd8f6b3a55153f81d/runtime/core/cmake/openfst.cmake#L29
this line uses `TORCH_CXX_FLAGS`, which comes from libtorch-src/share/cmake/Torch/TrochConfig.cmake : 
```
# When we build libtorch with the old GCC ABI, dependent libraries must too.
if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")                                                                                                                                                                                        
  set(TORCH_CXX_FLAGS "-D_GLIBCXX_USE_CXX11_ABI=0")
endif()
```
if `-DTORCH=OFF`, ther is no `TORCH_CXX_FLAGS `. So, my `build-torch` did not use CXX11, but `build-onnx` used CXX11, and finally got different size of libfst.so.

if  we want to build with libtorch with CXX11,  just `-DCXX11_ABI=ON`, which defined here : 
https://github.com/wenet-e2e/wenet/blob/46ae3eae79d89e86270bf58cd8f6b3a55153f81d/runtime/server/x86/CMakeLists.txt#L5
