### ISSUE TITLE
Optimization for inaccurate word timestamp

### ISSUE THREAD

**Issue by roney123** [wenet-e2e/wenet#1223]
**Is your feature request related to a problem? Please describe.**
In long speech recognition, due to silence data and lack of VaD, the timestamp of words is inaccurate, especially in the first and last words

**Describe the solution you'd like**
I use a method similar to CTC endpoint to detect the front and back silence position of each sentence to judge the real position of the active audio

Core code
```cpp
void CtcSilence::detect(const std::vector<std::vector<float>>& ctc_log_probs,
                        bool decoded_something) {
  if (is_foregoing) {
    if (!decoded_something) {
      num_frames_foregoing_blank_ += ctc_log_probs.size();
    } else {
      for (int t = 0; t < ctc_log_probs.size(); ++t) {
        float blank_prob = expf(ctc_log_probs[t][config_.blank]);
        if (blank_prob > config_.blank_threshold) {
          num_frames_foregoing_blank_++;
        } else {
          break;
        }
      }
      is_foregoing = false;
    }
  } else {
    for (int t = 0; t < ctc_log_probs.size(); ++t) {
      float blank_prob = expf(ctc_log_probs[t][config_.blank]);
      if (blank_prob > config_.blank_threshold) {
        num_frames_trailing_blank_++;
      } else {
        num_frames_trailing_blank_ = 0;
      }
    }
  }
}
``` 

Can I submit PR?

**Comment by robin1001** [comment]
https://github.com/wenet-e2e/wenet/pull/1107/

please see the PR, I think the PR is a better solution.

**Comment by roney123** [comment]
yes, #1107  looks simpler, but `time_ stamp_ gap_= 100` is like an experience value. I will track the effect in the actual project.
I look forward to a better way to solve CTC word alignment timestamp.
thanks.

**Comment by robin1001** [comment]
Great! If it works, it's a big deal.
Please look at our roadmap https://github.com/wenet-e2e/wenet/blob/main/ROADMAP.md and python binding https://github.com/wenet-e2e/wenet/blob/main/runtime/binding/python/README.md if you are interested.

**Comment by duj12** [comment]
> yes, #1107 looks simpler, but `time_stamp_gap_= 100` is like an experience value. I will track the effect in the actual project. I look forward to a better way to solve CTC word alignment timestamp. thanks.

@roney123 hi, I also found that the time stamp is not accurate(the error range is over 250ms for some tokens), which is result from CTC's bad alignment performence. Do you have any better solution now?
Here is my opinion, only using CTC to learn alignment is not enough for accurate time stamp, maybe we can give some audios with frame-level labels, to learn a better alignment as an auxiliaury task.

**Comment by roney123** [comment]
> @roney123 hi, I also found that the time stamp is not accurate(the error range is over 250ms for some tokens), which is result from CTC's bad alignment performence. Do you have any better solution now? Here is my opinion, only using CTC to learn alignment is not enough for accurate time stamp, maybe we can give some audios with frame-level labels, to learn a better alignment as an auxiliaury task.


@duj12 hi,CTC training has this problem. It should be impossible to avoid it. Now some experts have put forward some methods, such as TrimTail（https://mp.weixin.qq.com/s/rHE0ckKGBlc1zjh5BMXAUQ）. You can try it.
