### ISSUE TITLE
如何获得model

### ISSUE THREAD

**Issue by billqu01** [wenet-e2e/wenet#1227]
我通过aliyun用pip按照了wenet
 python -m pip install wenet -i https://mirrors.aliyun.com/pypi/simple/
我的程序如下，想试一试识别，但是没有下载到model，请问如何下载到model?
import sys
import wenet

def get_text_from_wav(dir, wav):
    model_dir = dir
    wav_file = wav
    decoder = wenet.Decoder(model_dir)
    ans = decoder.decode_wav(wav_file)
    print(ans)

# Press the green button in the gutter to run the script.
if __name__ == '__main__':
    print('test')

# See PyCharm help at https://www.jetbrains.com/help/pycharm/

**Comment by robin1001** [comment]
@Mddct seems it is a strong requirement, when can we finish it?

**Comment by Mddct** [comment]
> @Mddct seems it is a strong requirement, when can we finish it?

I‘m doing now ， maybe pr tomorrow

**Comment by Mddct** [comment]
> 我通过aliyun用pip按照了wenet
>  python -m pip install wenet -i https://mirrors.aliyun.com/pypi/simple/
> 我的程序如下，想试一试识别，但是没有下载到model，请问如何下载到model?
> import sys
> import wenet
> 
> def get_text_from_wav(dir, wav):
>     model_dir = dir
>     wav_file = wav
>     decoder = wenet.Decoder(model_dir)
>     ans = decoder.decode_wav(wav_file)
>     print(ans)
> 
> # Press the green button in the gutter to run the script.
> if __name__ == '__main__':
>     print('test')
> 
> # See PyCharm help at https://www.jetbrains.com/help/pycharm/
> 

you can manually download mode from https://github.com/wenet-e2e/wenet/blob/main/docs/pretrained_models.md

future code will automatic download by language type
