### ISSUE TITLE
 报错forward_encoder_chunk() Expected a value of type 'Optional[List[Tensor]]' for argument 'elayers_output_cache' but instead found type 'Tensor'.

### ISSUE THREAD

**Issue by ljwmusclenlper** [wenet-e2e/wenet#1231]
I0617 01:39:51.221403     7 websocket_server_main.cc:31] Listening at port 10086
I0617 01:40:32.026695    16 websocket_server.cc:217] {"signal":"start","nbest":1,"continuous_decoding":true}
I0617 01:40:32.026813    16 websocket_server.cc:43] Received speech start signal, start reading speech
I0617 01:40:34.267653    16 websocket_server.cc:96] Received 6848 samples
I0617 01:40:34.605115    16 websocket_server.cc:96] Received 5483 samples
I0617 01:40:34.605576    17 asr_decoder.cc:88] Required 67 get 67
E0617 01:40:34.629177    17 websocket_server.cc:157] forward_encoder_chunk() Expected a value of type 'Optional[List[Tensor]]' for argument 'elayers_output_cache' but instead found type 'Tensor'.
Position: 5
Declaration: forward_encoder_chunk(__torch__.wenet.transformer.asr_model.ASRModel self, Tensor xs, int offset, int required_cache_size, Tensor? subsampling_cache=None, Tensor[]? elayers_output_cache=None, Tensor[]? conformer_cnn_cache=None) -> ((Tensor, Tensor, Tensor[], Tensor[]))
Exception raised from checkArg at ../aten/src/ATen/core/function_schema_inl.h:184 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6b (0x7f66d76a775b in /home/wenet/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xce (0x7f66d76a338e in /home/wenet/lib/libc10.so)
frame #2: <unknown function> + 0x125ec22 (0x7f66d894ac22 in /home/wenet/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x1262fa1 (0x7f66d894efa1 in /home/wenet/lib/libtorch_cpu.so)
frame #4: torch::jit::GraphFunction::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) + 0x2d (0x7f66db23639d in /home/wenet/lib/libtorch_cpu.so)
frame #5: torch::jit::Method::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) const + 0x175 (0x7f66db245ab5 in /home/wenet/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x168d25 (0x55fc48eaad25 in /home/wenet/websocket_server_main)
frame #7: <unknown function> + 0xa5035 (0x55fc48de7035 in /home/wenet/websocket_server_main)
frame #8: <unknown function> + 0xa1e70 (0x55fc48de3e70 in /home/wenet/websocket_server_main)
frame #9: <unknown function> + 0x55865 (0x55fc48d97865 in /home/wenet/websocket_server_main)
frame #10: <unknown function> + 0xd6de4 (0x7f66d6e98de4 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #11: <unknown function> + 0x8609 (0x7f66d7652609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #12: clone + 0x43 (0x7f66d6b85163 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by robin1001** [comment]
Please update both the model and code to the latest version.
