### ISSUE TITLE
use two language models at the same time ?

### ISSUE THREAD

**Issue by hk0901** [wenet-e2e/wenet#1232]
I hava trained a lm model (lm1) with a large corpus.  Now hava a new batch of corpus, I can train a small lm(lm2),  Is there a way to use both models at the same time

**Comment by Mddct** [comment]
> I hava trained a lm model (lm1) with a large corpus.  Now hava a new batch of corpus, I can train a small lm(lm2),  Is there a way to use both models at the same time

if you have two ngram，you can use language model Interpolation algorithms。Both srilm and  kenlm can do this。
