### ISSUE TITLE
results of recognize.py and decoder_main.cc are different

### ISSUE THREAD

**Issue by ForestLee** [wenet-e2e/wenet#1239]
**Describe the bug**

I checked the recognize.py result in exp/conformer/test_attention_rescoring/cer, for a certain sentence, i decoder with "decoder_main.cc", the results are different, a lot of errors decoded by decoder_main.cc.

I train with default configuration. And run decoder_main like:
/opt/wenet/runtime/server/x86/build/decoder_main \
	--model_path /opt/wenet/examples/aishell/s0/exp/conformer/final.zip \
	--dict_path /opt/wenet/examples/aishell/s0/data/local/dict/units.txt \
	--wav_path /asr/dataset/aishell_format_aidatatang_private/data_aishell/wav/test/G9171/T0055G9171S0400.wav

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ForestLee** [comment]
训练的最后会使用recognize.py对测试集识别，结果存放在exp/conformer/test_attention_rescoring/cer中；
我用decoder_main.cc生成的decoder_main来解码测试集中的音频， 发现结果比较差，很多音频错误， CER很大。

Overall -> 38.13 % N=93577 C=59757 S=16877 D=16943 I=1864
Mandarin -> 36.94 % N=89579 C=58299 S=15296 D=15984 I=1814
Number -> 64.86 % N=3680 C=1316 S=1493 D=871 I=23
English -> 63.26 % N=313 C=142 S=84 D=87 I=27
Other -> 100.00 % N=5 C=0 S=4 D=1 I=0

比如：
utt: T0055G9171S0398
WER: 8.33 % N=12 C=11 S=0 D=1 I=0
lab: 查 一 下 徐 家 汇 的 路 况 怎 么 样
rec: 查 一 下 徐 家 汇    路 况 怎 么 样

utt: T0055G9171S0400
WER: 28.57 % N=14 C=10 S=0 D=4 I=0
lab: 请 给 我 把 这 首 音 乐 加 入 到 收 藏 夹
rec:    给 我 把    首    乐    入 到 收 藏 夹

配置都是默认的conformer+CTC+attention， decoder_main是：
/opt/wenet/runtime/server/x86/build/decoder_main
--model_path /opt/wenet/examples/aishell/s0/exp/conformer/final.zip
--dict_path /opt/wenet/examples/aishell/s0/data/local/dict/units.txt
--wav_path /asr/dataset/aishell_format_aidatatang_private/data_aishell/wav/test/G9171/T0055G9171S0400.wav

**Comment by ForestLee** [comment]
我用的是这个版本
commit 30ba2007b367fd3d1f0689d673d99effb173efc1 (HEAD)
Merge: f7ebd24 6a16474
Author: Mddct <hamddct@gmail.com>
Date:   Mon May 30 12:02:11 2022 +0800

**Comment by robin1001** [comment]
提问题应该像你最后这个问题一样，别人才可能帮助到你。你检查一下你的模型是不是用动态 chunk 训练的，也就是训练中的

https://github.com/wenet-e2e/wenet/blob/main/examples/aishell/s0/conf/train_unified_conformer.yaml#L20

这个参数要为 true。

**Comment by ForestLee** [comment]
多谢多谢，我训练用的是默认配置，确实没有设置use_dynamic_chunk: true，再次感谢！
