### ISSUE TITLE
请问如何给文本添加标点？

### ISSUE THREAD

**Issue by billqu01** [wenet-e2e/wenet#1242]
我用下面代码已经获取到了文本。
    decoder = wenet.Decoder(model_dir)
    ans = decoder.decode_wav(wav_file)
请问如何给文本断句，如何添加标点？

**Comment by robin1001** [comment]
There is no punctuation in WeNet.

**Comment by chernzheng** [comment]
Use the punctuation restoration model, e.g.  https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/iwslt2012/punc0
