### ISSUE TITLE
different execution efficiency on arm64 platform

### ISSUE THREAD

**Issue by dmcEric** [wenet-e2e/wenet#1245]
Hello.
Thank you for the great work.
I tested the RTF on Android device(arm64) by following [https://github.com/wenet-e2e/wenet/blob/main/runtime/device/android/wenet/README.md](url). the RTF was less than 1 and the CPU utilization was nearly 100% with the Multi-CN model, that was perfect. Then i compiled the program on Ubuntu(arm64, share the same hardware with Android), run  `./build/bin/decoder_main`with the same wav file and model file Android did, but the RTF was larger than 1 and the  CPU utilization was nearly 500%. The difference performances on the same hardware with difference OS confused me. 
I know `/runtime/server/x86/bin/decoder_main.cc` is for x86, but it can be compiled on arm64 too. 

I wonder if there are any settings that affect `./decoder_main` performance on x86 and Android.

**Comment by robin1001** [comment]
We do not have the arm64 ubuntu, and I have no idea about it. What runtime did you use? ONNX or LibTorch?

**Comment by dmcEric** [comment]
LibTorch. 
Are there any settings that can control `./decoder_main` performance on x86 and Android?

**Comment by robin1001** [comment]
https://github.com/wenet-e2e/wenet/blob/main/runtime/core/bin/decoder_main.cc#L33 controls how many threads we use for decoding for `decoder_main`,  seems you have used more than 1 threads, so the CPU utilization is over 100%.
