### ISSUE TITLE
stuck reading model

### ISSUE THREAD

**Issue by rgwt123** [wenet-e2e/wenet#1247]
I'm new to using wenet and I use the official wenet docker image from wenetorg/wenet and pretrained model "20210728_u2pp_conformer_libtorch".
However, when I use websocket_server_main or decoder_main, the programs all hang after printing one line as follows:
```
root@e90cd95a48d1:/home/wenet/runtime/server/x86/build/bin# ./websocket_server_main --port 8888 --chunk_size 16 --model_path ../../docker_resource/20210728_u2pp_conformer_libtorch/final.zip --unit_path ../../docker_resource/20210728_u2pp_conformer_libtorch/units.txt
I0622 18:18:52.687235    60 params.h:135] Reading torch model ../../docker_resource/20210728_u2pp_conformer_libtorch/final.zip
```
So the websocket client return errors like:
```
terminate called after throwing an instance of 'boost::wrapexcept<boost::system::system_error>'
  what():  connect: Connection refused
```
I have also tried the pre-built demo and websocket cannot connect to the server too.
Has anyone encountered this problem, thanks!

**Comment by pengzhendong** [comment]
Confirm whether the container can access the model path.

**Comment by pengzhendong** [comment]
Update the version of docker desktop can fix this problem.
