### ISSUE TITLE
Can not import torch while import wenet

### ISSUE THREAD

**Issue by lfgogogo** [wenet-e2e/wenet#1253]
I am using wenet to do asr job,while i also use another torch model to do vad job.I want to combine the two results to do something like speaker diarization.But it raise errors:
1、import torch then import wenet:
raise error "ImportError: DLL load failed" while import _wenet
2、import wenet then import torch:
raise error "OSError: [WinError 127]  Error loading "D:\Anaconda3\envs\asr36\lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies" while import torch
I am wondering there is a conflict between them.Maybe wenet should rely on torch installed locally ?
ps:
python version:3.6
install wenet using pip install wenet
torch version:torch-1.8.0+cu111-cp36-cp36m-win_amd64.whl

**Comment by pengzhendong** [comment]
Plz use different python env.

**Comment by lfgogogo** [comment]
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0627 11:24:01.351308  5600 wenet_api.cc:47] Check failed: wenet::FileExists(unit_path) 
*** Check failure stack trace: ***

Process finished with exit code -1073740791 (0xC0000409)

Ok,i get that.But i have a new error here,it means out of GPU memory?And i do nothing,it works fine last week.

**Comment by Mddct** [comment]
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> F0627 11:24:01.351308  5600 wenet_api.cc:47] Check failed: wenet::FileExists(unit_path) 
> *** Check failure stack trace: ***
> 
> Process finished with exit code -1073740791 (0xC0000409)
> 
> Ok,i get that.But i have a new error here,it means out of GPU memory?And i do nothing,it works fine last week.

plz rename word.txt to unit.txt due to latest chabges for e2e model unit

**Comment by lfgogogo** [comment]
thanks for help!
