### ISSUE TITLE
[transducer] decoding strategy

### ISSUE THREAD

**Issue by Mddct** [wenet-e2e/wenet#1269]
Open this to track different decoding strategies of the transducer model. I will update some materials and code snippets here
 Suggestions welcome and hope to collaborate

**Comment by Mddct** [comment]
https://github.com/espnet/espnet/blob/d837c97c88f13ffe655a30bcff93d814f212b225/espnet/nets/beam_search_transducer.py#L713
https://arxiv.org/pdf/1211.3711.pdf
https://ieeexplore.ieee.org/document/9053040
https://arxiv.org/pdf/2002.03577.pdf
https://ieeexplore.ieee.org/document/9250505

**Comment by b-flo** [comment]
Hi @Mddct ,

For alignment-length synchronous (ALSD), time-synchronous decodng (TSD) and modified Adaptive Expansion Search (mAES) in ESPnet, please refer to [this](https://github.com/espnet/espnet/blob/a672fe65030a7d9424465b2027019c906ae35fe1/espnet2/asr_transducer/beam_search_transducer.py). The version you linked is missing some fixes and optimizations!

Btw, you can drop 1-step/N-step constrained beam search from your list as it was superseded by AES/mAES!

**Comment by Mddct** [comment]
> Hi @Mddct ,
> 
> For alignment-length synchronous (ALSD), time-synchronous decodng (TSD) and modified Adaptive Expansion Search (mAES) in ESPnet, please refer to [this](https://github.com/espnet/espnet/blob/a672fe65030a7d9424465b2027019c906ae35fe1/espnet2/asr_transducer/beam_search_transducer.py). The version you linked is missing some fixes and optimizations!
> 
> Btw, you can drop 1-step/N-step constrained beam search from your list as it was superseded by AES/mAES!

Thank you very much for your reply， I'll do some experiments later

**Comment by Mddct** [comment]
If we want to use one-step decoding in the inference stage, can we try the implementation of this rnhnt loss later?
 [paper](https://arxiv.org/abs/1909.12415) 
[implement](https://github.com/csukuangfj/optimized_transducer)
