### ISSUE TITLE
Can I get timestamp info by GPU inference?

### ISSUE THREAD

**Issue by JaheimLee** [wenet-e2e/wenet#1282]
I found timestamp info from [here](https://wenet.org.cn/wenet/python_binding.html?highlight=timestamp) . But it's only for cpu. Is it possible to get timestamp from GPU inference? For example by using your [docker server](https://github.com/wenet-e2e/wenet/tree/main/runtime/GPU)

**Comment by robin1001** [comment]
@yuekaizhang is it possible?

**Comment by yuekaizhang** [comment]
> @yuekaizhang is it possible?

Yes, it's possible to add timestamp. Currently gpu inference using this [ctc_decoder](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/third_party/ctc_decoders), which needs to modify to add timestamps. Or we could replace it with https://pytorch.org/audio/main/models.decoder.html, which has already supported timestamps. 

I could implement it next week.

@Mddct would wenet python bindings give an python API for ctc_prefix_beam_search?

**Comment by Mddct** [comment]
> > @yuekaizhang is it possible?
> 
> Yes, it's possible to add timestamp. Currently gpu inference using this [ctc_decoder](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/third_party/ctc_decoders), which needs to modify to add timestamps. Or we could replace it with https://pytorch.org/audio/main/models.decoder.html, which has already supported timestamps. 
> 
> I could implement it next week.
> 
> @Mddct would wenet python bindings give an python API for ctc_prefix_beam_search?  

python bindung  is for the convenience of using wenet。If we can binding wenet ctc prefix search in other repo to replace ctcdecoder？I've implemented a statedledd binding before which maybe helpful
https://github.com/Mddct/losses/blob/main/src/ctc_decoder.h

**Comment by pengzhendong** [comment]
@yuekaizhang Plz note this issue: https://github.com/parlance/ctcdecode/issues/148

**Comment by xingchensong** [comment]
seems solved， close this issue
