### ISSUE TITLE
识别准确率只有70%多

### ISSUE THREAD

**Issue by billqu01** [wenet-e2e/wenet#1285]
我用wenet speech 模型进行识别。
decoder = wenet.Decoder(model_dir)
ans = decoder.decode_wav(wav_file)
识别准确率只有70%多。
请问如何提高识别的准确率？

**Comment by robin1001** [comment]
WenetSpeech is for general speech recognition. The performance degrades when you apply it to your specific domain. You can use your domain data to fine tune the model.
