### ISSUE TITLE
convert the onnx model to tensorflow pb model

### ISSUE THREAD

**Issue by zhaiyuan0217** [wenet-e2e/wenet#1288]
I want to know when i use the onnx-tf convert to encoder.onnx model to pb model, why it happens"ValueError: Cannot take the length of shape with unknown rank"
and convert the encoder_fp16.onnx to pb model, why it happens"Nodes in a graph must be topologically sorted, however input 'TopK_2457_input_cast_0' of node". what should i do?

**Comment by robin1001** [comment]
Sorry, we have no experience on it.
