### ISSUE TITLE
U2++ lost word problem

### ISSUE THREAD

**Issue by 601222543** [wenet-e2e/wenet#1291]
Why U2++ lose words at the end of sentences compared to non-streaming conformer?

non-streaming conformer
```
Overall -> 15.21 % N=263 C=223 S=40 D=0 I=0
```
U2++
```
Overall -> 29.66 % N=263 C=185 S=33 D=45 I=0
```

**Comment by robin1001** [comment]
It's unnormal. The WER should be close.
