### ISSUE TITLE
Android Project：mode forward chunks error 

### ISSUE THREAD

**Issue by swpucl** [wenet-e2e/wenet#1300]
**Describe the bug**
when I run the android project get some error about mode forward chunks, like this:

E/libc++abi: terminating with uncaught exception of type std::runtime_error: The following operation failed in the TorchScript interpreter.
    Traceback of TorchScript, serialized code (most recent call last):
      File "code/__torch__/wenet/transformer/asr_model/___torch_mangle_28.py", line 129, in forward_encoder_chunk
        conformer_cnn_cache: Optional[List[Tensor]]=None) -> Tuple[Tensor, Tensor, List[Tensor], List[Tensor]]:
        encoder = self.encoder
        _24 = (encoder).forward_chunk(xs, offset, required_cache_size, subsampling_cache, elayers_output_cache, conformer_cnn_cache, )
               ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return _24
      def is_bidirectional_decoder(self: __torch__.wenet.transformer.asr_model.___torch_mangle_28.ASRModel) -> bool:
      File "code/__torch__/wenet/transformer/encoder/___torch_mangle_21.py", line 123, in forward_chunk
          conformer_cnn_cache1 = unchecked_cast(List[Tensor], conformer_cnn_cache)
          cnn_cache, conformer_cnn_cache0 = conformer_cnn_cache1[0], conformer_cnn_cache1
        _25 = (_0).f
A/libc: Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 6447 (Thread-3), pid 6338 (xample.atomtest)

Don't know the reasons. Could you check it?

**Comment by robin1001** [comment]
It's because you use different model and code version. Please update both the model and the code to the latest version.

**Comment by swpucl** [comment]
> It's because you use different model and code version. Please update both the model and the code to the latest version.

Thanks a lot , I'll try.
