### ISSUE TITLE
[runtime] Difference of cmake command

### ISSUE THREAD

**Issue by yuekaizhang** [wenet-e2e/wenet#1307]
**Describe the bug**

Under runtime/LibTorch, build using below command would let decoder_main abort. 
```
cmake .. -DCMAKE_BUILD_TYPE=Release && cmake --build . --config Release
```
However, it works if build with
```
cmake ..  && cmake --build .
```
Does anyone know the reason?

**To Reproduce**
I tested it with single wav, however, the program has not been properly exited. I can't see the log from https://github.com/wenet-e2e/wenet/blob/main/runtime/core/bin/decoder_main.cc#L160-L162. 
[log.txt](https://github.com/wenet-e2e/wenet/files/9117669/log.txt)

```bash
./build/bin/decoder_main \
 --chunk_size -1 \
 --wav_path $wav_path \
 --model_path $model_dir/final.zip \
 --unit_path $model_dir/units.txt 2>&1 | tee log.txt
```

**Comment by pengzhendong** [comment]
What's your platform? Windows or Linux?

**Comment by yuekaizhang** [comment]
> What's your platform? Windows or Linux?

It's Ubuntu 20.04.

**Comment by pengzhendong** [comment]
Fixed. https://github.com/wenet-e2e/wenet/pull/1312
