### ISSUE TITLE
Transducer 解码时报错，缺少参数“last”

### ISSUE THREAD

**Issue by gangkou2020** [wenet-e2e/wenet#1308]
wenet/transducer/search/prefix_beam_search.py 第96行漏掉了参数“last”
89行-91行的代码如下
        `# 2. init beam using Sequence to save beam unit`
        `h_0, c_0 = self.predictor.init_state(1, method="zero")`
        `beam_init.append(`
        `    Sequence(`
        `        hyp=[self.blank],`
        `        score=0.0,`
        `        h_0=h_0,`
        `        c_0=c_0,`
        `    )`
        `)
`

**Comment by xingchensong** [comment]
RNNT decoding is under frequent development, some parts or features are removed compared to the previous version. As u can find in PR https://github.com/wenet-e2e/wenet/pull/1302, `last` is not a required item.

**Comment by gangkou2020** [comment]
> RNNT decoding is under frequent development, some parts or features are removed compared to the previous version. As u can find in PR #1302, `last` is not a required item.

明白了，谢谢
