### ISSUE TITLE
running onnx format model , met this rebuild error

### ISSUE THREAD

**Issue by tianmala** [wenet-e2e/wenet#1313]
I tried to use onnx format model according to README.md in directory Onnxruntime. And  I have been finished step 1 ,export model to onnx and step 2 ,build. But when I tried to test step 3 ,testing, I met this error.

F0718 17:00:21.503589 355018 params.h:131] Please rebuild with cmake options 'DONNX=ON'.
*** Check failure stack trace: ***
@ 0x14ed739dc6ec google::LogMessage::Fail()
@ 0x14ed739dc634 google::LogMessage::SendToLog()
@ 0x14ed739dbf75 google::LogMessage::Flush()
@ 0x14ed739df794 google::LogMessageFatal::~LogMessageFatal()
@ 0x55f6110d5908 wenet::InitDecodeResourceFromFlags()
@ 0x55f6110d6594 main
@ 0x14ed725c9bf7 __libc_start_main
@ 0x55f6110d534a _start 
@                   (nil)   (unknown)

I finished to rebuild step, but still met this error ,please help~thanks

**Comment by pengzhendong** [comment]
Turn this option on: https://github.com/wenet-e2e/wenet/blob/67c89d4173be9148aca130f1b6031e454de64a58/runtime/LibTorch/CMakeLists.txt#L13
