### ISSUE TITLE
x86 compilation issues

### ISSUE THREAD

**Issue by tuocheng0824** [wenet-e2e/wenet#1315]
I pulled the latest wenet compilation and used x86 to perform a single voice test, but there was no result output, as follows
![old](https://user-images.githubusercontent.com/28757602/179669121-9bf630d6-315b-4edb-9de8-4e8a462f2b3a.png)
![new](https://user-images.githubusercontent.com/28757602/179669146-b9ac2a1c-b288-42ca-8ab8-1697341c3315.png)

I0719 12:30:06.883505 3235498 params.h:135] Reading torch model model_0714_english_aws/final.zip
I0719 12:30:06.919427 3235498 torch_asr_model.cc:36] Num intra-op threads: 1
I0719 12:30:06.919452 3235498 torch_asr_model.cc:37] Num inter-op threads: 1
I0719 12:30:07.481051 3235498 torch_asr_model.cc:71] Torch Model Info:
I0719 12:30:07.481078 3235498 torch_asr_model.cc:72]    subsampling_rate 6
I0719 12:30:07.481081 3235498 torch_asr_model.cc:73]    right context 10
I0719 12:30:07.481083 3235498 torch_asr_model.cc:74]    sos 4998
I0719 12:30:07.481086 3235498 torch_asr_model.cc:75]    eos 4998
I0719 12:30:07.481087 3235498 torch_asr_model.cc:76]    is bidirectional decoder 1
I0719 12:30:07.481094 3235498 params.h:145] Reading unit table model_0714_english_aws/units.txt

**Comment by robin1001** [comment]
@lzhin please follow the problem, it is related to thread pool

**Comment by lzhin** [comment]
> 

Is it convenient to send your audio？

**Comment by tuocheng0824** [comment]
[音频.zip](https://github.com/wenet-e2e/wenet/files/9138681/default.zip)
It should not be a problem with the audio, because the audio is recognized by the environment compiled before

**Comment by lzhin** [comment]
![image](https://user-images.githubusercontent.com/17926066/179695547-52963f23-224f-4695-9f9a-d54d6cab1f2a.png)
I test and it is normal.

**Comment by tuocheng0824** [comment]
This model needs to be converted to libtorch, right?
I am using the original final.zip directly 
I will try again

**Comment by lzhin** [comment]
final.zip has bean converted to libtorch.

**Comment by tuocheng0824** [comment]
![server](https://user-images.githubusercontent.com/28757602/179702298-bb37a89b-8a46-48b2-8602-4de8359000c1.png)
This is tested with websocket,
I compiled it on the server according to mkdir build && cd build && cmake .. && cmake --build . and no errors were reported

**Comment by lzhin** [comment]
The final.zip might not fit to the newest runtime code.

**Comment by tuocheng0824** [comment]
![11111](https://user-images.githubusercontent.com/28757602/179707455-0ecedfb9-70db-4c99-a732-7d7b912b86fe.png)
I solved it. I re-exported final.zip using latest wenet/bin/export_jit.py, thanks a lot!

**Comment by lzhin** [comment]
ok
