### ISSUE TITLE
用单机多GPU卡训练，却只用到一张卡

### ISSUE THREAD

**Issue by dlkht** [wenet-e2e/wenet#1326]
设置了export CUDA_VISIBLE_DEVICES="0,1,2"，dist_backend="gloo"

训练开始发现三个 rank都分配在GPU0，另外两个GPU没有使用到，

应该怎么设置？

谢谢！

**Comment by wenzhengchang** [comment]
你解决了吗

**Comment by diveknown** [comment]
就是这样设置, 建议在run.sh中在获得num_gpus后, 打印echo $num_gpus, 检查是不是环境问题

**Comment by wntg** [comment]
想问下解决了吗

**Comment by apoca909** [comment]
你是不是把os.environ['CUDA_VISIBLE_DEVICES'] = str(args.gpu)这行代码注释了？

**Comment by wenzhengchang** [comment]
你好，有人解决了吗，我一直这样

**Comment by wenzhengchang** [comment]
> 想问下解决了吗

你好，你解决了吗

**Comment by Meeny2018** [comment]
我也出现类似情况了，可以更换一下torch版本

**Comment by dahu1** [comment]
> 我也出现类似情况了，可以更换一下 torch 版本

请问换的是哪一版本？

**Comment by xingchensong** [comment]
试一下最新代码（torchrun启动）可不可以呢
