### ISSUE TITLE
aishell compute_cmvn_stats error

### ISSUE THREAD

**Issue by wpchenit** [wenet-e2e/wenet#1329]
**Describe the bug**
aishell-1 run.sh error。

**To Reproduce**
./run.sh --stage 0 --stop_stage 1

**Expected behavior**
success

**Screenshots**
![image](https://user-images.githubusercontent.com/64248379/180708149-05206ce3-7ef3-4ef8-ac7c-7eab7a6f09a0.png)

**Desktop (please complete the following information):**
CentOS Linux release 7.9.2009
gcc 5.1.0
memory 512G

try set num_workers 1、0  and rebuild environment  not work

**Comment by robin1001** [comment]
Sorry, I have no idea from the log. You can try to debug compute_cmvn_stats.py step by step.

**Comment by rookie0607** [comment]
I encountered the same problem. Has the problem been solved？

**Comment by wpchenit** [comment]
已收到您的邮件。

**Comment by wpchenit** [comment]
Conflict with other programs, just stop another program. The cause of the conflict is unknown。

**Comment by wpchenit** [comment]
已收到您的邮件。
