### ISSUE TITLE
Why is the 'cnn_module_kernel' set to 15 for the U2 recipe but 8 for the U2++?

### ISSUE THREAD

**Issue by wangfangyuan** [wenet-e2e/wenet#1331]
I am trying to reproduce the results of U2++. However, I'm confused about the cnn_module_kernel's default setting for U2++.

U2++:
![image](https://user-images.githubusercontent.com/20180997/181143170-80044bc7-c73c-4467-b88f-27a05b080857.png)

U2:
![image](https://user-images.githubusercontent.com/20180997/181143375-22137790-83d5-4170-b7b2-673f6566a5a7.png)

The default setting is 8, while 15 for U2. 
It will be appreciated if your could explain a little bit about your consideration in U2++.
Is that because U2++ finds small kernel size is beneficial to the performance or for any other reason? 

Thanks a lot.

**Comment by robin1001** [comment]
U2++ uses causal convolution, it only takes left context and current frame, so it's 7+1 = 8 in U2++.

**Comment by wangfangyuan** [comment]
Thanks for your timely response.

U2 also uses causal convolution as a streaming and non-streaming unified solution,  see the figure beblow.

![image](https://user-images.githubusercontent.com/20180997/181188415-208f4171-1e1c-4bf5-bcbc-373d5b0dbb85.png)

Is there any problem for U2 with the setting of 15?

**Comment by robin1001** [comment]
Sorry for that, maybe just because 8 get better result.
