### ISSUE TITLE
[Runtime] Cmake build files did not compile perfecly to the right path ```$ wenet\runtime\server\x86``` on my local machine

### ISSUE THREAD

**Issue by xiao11lam** [wenet-e2e/wenet#1334]
Hi! Here are the issues I met when I just want to build the runtime system, I ran the ```cmake  --B build ``` very perfectly at the directory ```$ wenet\runtime\server\x86```, here was the screenshot.
![微信截图_20220727180124](https://user-images.githubusercontent.com/58770171/181229147-0b437db9-7ad0-45e7-b521-ca8268e3a4a8.png)
![微信截图_20220727180150](https://user-images.githubusercontent.com/58770171/181229216-43e65d29-5645-4bf1-a118-e4539336163b.png)
However, when I want to make a final compling ```cmake --build build```, the log looks fine but I just cannot find the generated ```Debug``` directory from my final outputs, is there anything wrong there ？
![微信截图_20220727183111](https://user-images.githubusercontent.com/58770171/181230324-8a6339ee-34cb-4e48-9695-75614dcad748.png)

![微信截图_20220727183245](https://user-images.githubusercontent.com/58770171/181230232-99c1a9ad-28fc-4140-bf26-d89e473c9cb7.png)

**Comment by pengzhendong** [comment]
Only MSVC in Windows will generate the `CMAKE_BUILD_TYPE` folder. All bianries you built are in `bin` folder.

**Comment by xiao11lam** [comment]
> Only MSVC in Windows will generate the `CMAKE_BUILD_TYPE` folder. All bianries you built are in `bin` folder.

Thank you for your advice. Here was my `bin` folder. 
![微信截图_20220727192212](https://user-images.githubusercontent.com/58770171/181235367-bf26b15b-0eff-4e2b-b3f7-f008fa57a098.png)
![微信截图_20220727192518](https://user-images.githubusercontent.com/58770171/181235609-5d6d9404-e9df-41d9-b087-b4f13ab5d938.png)

**Comment by pengzhendong** [comment]
Files end with main are all you need.
