### ISSUE TITLE
Libtorch GPU 版本报nvrtc  error

### ISSUE THREAD

**Issue by ziyu123** [wenet-e2e/wenet#1335]
利用GPU=ON进行libtorch在gpu上进行编译，跑TLG解码，跑多条音频，第一条正常返回结果，第二条就报如下error，  
terminate called after throwing an instance of 'std::runtime_error'
  what():  nvrtc: error: failed to open libnvrtc-builtins.so.11.3.
  Make sure that libnvrtc-builtins.so.11.3 is installed correctly.
nvrtc compilation failed:

#define NAN __int_as_float(0x7fffffff)
#define POS_INFINITY __int_as_float(0x7f800000)
#define NEG_INFINITY __int_as_float(0xff800000)

template<typename T>
__device__ T maximum(T a, T b) {
  return isnan(a) ? a : (a > b ? a : b);
}

template<typename T>
__device__ T minimum(T a, T b) {
  return isnan(a) ? a : (a < b ? a : b);
}

extern "C" __global__
void fused_mul_add(float* tv_, float* tv__, double vff_scale_2, float* aten_add) {
{
  float v = __ldg(tv_ + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
  float v_1 = __ldg(tv__ + (long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x));
  aten_add[(long long)(threadIdx.x) + 512ll * (long long)(blockIdx.x)] = v + v_1 * (float)(vff_scale_2);
}
}

这个应该是cuda版本的问题，问题是为什么第一条音频可以跑出来结果呢，后面的却报nvrtc  error呢？
我现在环境是cuda 11.4版本，GPU A30

**Comment by yuekaizhang** [comment]
@veelion Do you have any ideas?

**Comment by ziyu123** [comment]
问题解决了， 进入 /home/wenet_test/runtime/server/x86/fc_base/libtorch-src/lib， 执行软连接即可，
ln -s libnvrtc-builtins-4730a239.so.11.3  libnvrtc-builtins.so.11.3

**Comment by ziyu123** [comment]
问题解决了， 进入 /home/wenet/runtime/server/x86/fc_base/libtorch-src/lib， 执行软连接即可，
ln -s libnvrtc-builtins-4730a239.so.11.3 libnvrtc-builtins.so.11.3

**Comment by zhaoyinjiang9825** [comment]
Hello, I have no problem compiling with the official pretrained models, but the call is unsuccessful, how did you do it, can you give me some guidance, thank you?
@ziyu123

**Comment by ziyu123** [comment]
you can remove some codes about thread pool in decoder_main.cc and then compile it again.    or  set GLOG_v=3, print more logs information.  
you can also make in Debug type, try to debug the c++ code line by line.

**Comment by zhaoyinjiang9825** [comment]
Do you re-export the official Checkpoint Model to the runtime model?@ziyu123

**Comment by ziyu123** [comment]
i use the original checkpoint file
