### ISSUE TITLE
使用runtime自行编译运行时程序出现的错误

### ISSUE THREAD

**Issue by xzwworkplace** [wenet-e2e/wenet#1344]
**Describe the bug**
我使用的是ubantu20.04系统,我按照wenet的安装指南,创建了wenet虚拟环境,虚拟环境中安装了CUDA,但是在本机的基础环境中没有安装CUDA工具,在运行
mkdir build && cd build && cmake -DGPU=ON .. && cmake --build .
后出现了以下错误

**Describe the bug**
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
CMake Warning at fc_base/libtorch-src/share/cmake/Caffe2/public/cuda.cmake:31 (message):
  Caffe2: CUDA cannot be found.  Depending on whether you are building Caffe2
  or a Caffe2 dependent library, the next warning / error will give you more
  info.
Call Stack (most recent call first):
  fc_base/libtorch-src/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  fc_base/libtorch-src/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  cmake/libtorch.cmake:52 (find_package)
  CMakeLists.txt:35 (include)

CMake Error at fc_base/libtorch-src/share/cmake/Caffe2/Caffe2Config.cmake:90 (message):
  Your installed Caffe2 version uses CUDA but I cannot find the CUDA
  libraries.  Please set the proper CUDA prefixes and / or install CUDA.
Call Stack (most recent call first):
  fc_base/libtorch-src/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  cmake/libtorch.cmake:52 (find_package)
  CMakeLists.txt:35 (include)

**Comment by zhaoyinjiang9825** [comment]
This error is obvious, the local host also needs to install cuda！@xzwworkplace

**Comment by yuekaizhang** [comment]
Please turn off GPU options. mkdir build && cd build && cmake -DGPU=OFF .. && cmake --build .

**Comment by xzwworkplace** [comment]
thank your reply！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月01日 11:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wenet-e2e/wenet] 使用runtime自行编译运行时程序出现的错误 (Issue #1344) |

This error is obvious, the local host also needs to install ***@***.***

**Comment by xzwworkplace** [comment]
it works.Thank your reply!



---- 回复的原邮件 ----
| 发件人 | Yuekai ***@***.***> |
| 日期 | 2022年08月01日 15:26 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [wenet-e2e/wenet] 使用runtime自行编译运行时程序出现的错误 (Issue #1344) |

Please turn off GPU options. mkdir build && cd build && cmake -DGPU=OFF .. && cmake --build .
