### ISSUE TITLE
When I compile the runtime, there is an error

### ISSUE THREAD

**Issue by rookie0607** [wenet-e2e/wenet#1345]
(base) root@dd2323d5f3ed:/home/wenet/runtime/server/x86/build# cmake ..
-- Populating libtorch
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wenet/runtime/LibTorch/fc_base/libtorch-subbuild
[100%] Built target libtorch-populate
-- Populating gflags
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wenet/runtime/LibTorch/fc_base/gflags-subbuild
[100%] Built target gflags-populate
-- Populating glog
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wenet/runtime/LibTorch/fc_base/glog-subbuild
[100%] Built target glog-populate
CMake Error at /usr/local/lib/cmake/gflags/gflags-targets.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: gflags_nothreads_static

  Targets not yet defined: gflags_static

Call Stack (most recent call first):
  /usr/local/lib/cmake/gflags/gflags-config.cmake:10 (include)
  fc_base/glog-src/CMakeLists.txt:51 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/wenet/runtime/server/x86/build/CMakeFiles/CMakeOutput.log".
See also "/home/wenet/runtime/server/x86/build/CMakeFiles/CMakeError.log".

**Comment by Mddct** [comment]
you system have gflags ， remove it  and try again

**Comment by rookie0607** [comment]
> gflags



> you system have gflags ， remove it and try again

(base) root@dd2323d5f3ed:/home/wenet/runtime/server/x86/build# cmake ..
-- Populating libtorch
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wenet/runtime/LibTorch/fc_base/libtorch-subbuild
[100%] Built target libtorch-populate
-- Populating gflags
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wenet/runtime/LibTorch/fc_base/gflags-subbuild
[100%] Built target gflags-populate
-- Populating glog
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wenet/runtime/LibTorch/fc_base/glog-subbuild
[100%] Built target glog-populate
CMake Warning at fc_base/glog-src/CMakeLists.txt:51 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" (requested
  version 2.2.0) with any of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Populating boost
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wenet/runtime/LibTorch/fc_base/boost-subbuild
[100%] Built target boost-populate
-- Populating googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wenet/runtime/LibTorch/fc_base/googletest-subbuild
[100%] Built target googletest-populate
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wenet/runtime/server/x86/build

**Comment by rookie0607** [comment]
> you system have gflags ， remove it and try again

I deleted gflags, and with the following erro, what should I do? thank you

**Comment by Mddct** [comment]
this is a warning ， then you can build it
