### ISSUE TITLE
按照教程使用runtime本地wav文件识别，使用--wav_scp遇到的一个问题

### ISSUE THREAD

**Issue by xzwworkplace** [wenet-e2e/wenet#1347]
**Describe the bug**
command：./build/bin/decoder_main \
    --chunk_size -1 \
    --wav_scp /media/shiyanshi/E/espnet/egs/aishell/asr1/data/dev/1.scp \
    --model_path /media/shiyanshi/E/wenet/examples/aishell/s1/exp/conformer/final.zip \
    --unit_path /media/shiyanshi/E/wenet/examples/aishell/s1/exp/conformer/units.txt 2>&1 | tee log.txt

**Describe the bug**
I0802 14:12:26.160938 64401 params.h:135] Reading torch model /media/shiyanshi/E/wenet/examples/aishell/s1/exp/conformer/final.zip
I0802 14:12:26.205207 64401 torch_asr_model.cc:36] Num intra-op threads: 1
I0802 14:12:26.205233 64401 torch_asr_model.cc:37] Num inter-op threads: 1
I0802 14:12:26.550078 64401 torch_asr_model.cc:71] Torch Model Info:
I0802 14:12:26.550105 64401 torch_asr_model.cc:72] 	subsampling_rate 4
I0802 14:12:26.550107 64401 torch_asr_model.cc:73] 	right context 6
I0802 14:12:26.550109 64401 torch_asr_model.cc:74] 	sos 889
I0802 14:12:26.550112 64401 torch_asr_model.cc:75] 	eos 889
I0802 14:12:26.550113 64401 torch_asr_model.cc:76] 	is bidirectional decoder 0
I0802 14:12:26.550119 64401 params.h:145] Reading unit table /media/shiyanshi/E/wenet/examples/aishell/s1/exp/conformer/units.txt
W0802 14:12:26.552407 64466 wav.h:55] Error in read /media/shiyanshi/E/2020_XZW/ATC/S0001/S0001-UTT00016.wav
F0802 14:12:26.552464 64466 decoder_main.cc:47] Check failed: wav_reader.sample_rate() == FLAGS_sample_rate (0 vs. 16000) 
*** Check failure stack trace: ***
    @     0x7fc98cb90efc  google::LogMessage::Fail()
    @     0x7fc98cb90e37  google::LogMessage::SendToLog()
    @     0x7fc98cb90768  google::LogMessage::Flush()
    @     0x7fc98cb9414e  google::LogMessageFatal::~LogMessageFatal()
    @     0x559fc462736f  decode()
    @     0x559fc464c221  std::__invoke_impl<>()
    @     0x559fc464bf80  std::__invoke<>()
    @     0x559fc464bc15  _ZNSt5_BindIFPFvSt4pairISsSsEES1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @     0x559fc464b663  std::_Bind<>::operator()<>()
    @     0x559fc464aec9  std::__invoke_impl<>()
    @     0x559fc464a9a5  std::__invoke<>()
    @     0x559fc4649737  _ZZNSt13__future_base11_Task_stateISt5_BindIFPFvSt4pairISsSsEES3_EESaIiEFvvEE6_M_runEvENKUlvE_clEv
    @     0x559fc464b732  _ZNKSt13__future_base12_Task_setterISt10unique_ptrINS_7_ResultIvEENS_12_Result_base8_DeleterEEZNS_11_Task_stateISt5_BindIFPFvSt4pairISsSsEESA_EESaIiEFvvEE6_M_runEvEUlvE_vEclEv
    @     0x559fc464af8a  _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_EZNS1_11_Task_stateISt5_BindIFPFvSt4pairISsSsEESD_EESaIiEFvvEE6_M_runEvEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @     0x559fc46325ec  std::function<>::operator()()
    @     0x559fc462e3bc  std::__future_base::_State_baseV2::_M_do_set()
    @     0x559fc463be19  std::__invoke_impl<>()
    @     0x559fc4637c36  std::__invoke<>()
    @     0x559fc4632186  _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENKUlvE_clEv
    @     0x559fc46321bd  _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv
    @     0x559fc46321d2  _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv
    @     0x7fc976b654df  __pthread_once_slow
    @     0x559fc46296eb  __gthread_once()
    @     0x559fc4632293  std::call_once<>()
    @     0x559fc462dea0  std::__future_base::_State_baseV2::_M_set_result()
    @     0x559fc46497a9  std::__future_base::_Task_state<>::_M_run()
    @     0x559fc4639889  std::packaged_task<>::operator()()
    @     0x559fc46339ff  _ZZN10ThreadPool7enqueueIRFvSt4pairISsSsEEJRS2_EEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOS8_DpOS9_ENKUlvE_clEv
    @     0x559fc464629f  _ZNSt17_Function_handlerIFvvEZN10ThreadPool7enqueueIRFvSt4pairISsSsEEJRS4_EEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOSA_DpOSB_EUlvE_E9_M_invokeERKSt9_Any_data
    @     0x559fc463124a  std::function<>::operator()()
    @     0x559fc462e70d  _ZZN10ThreadPoolC4EmENKUlvE_clEv
    @     0x559fc464beef  _ZSt13__invoke_implIvZN10ThreadPoolC4EmEUlvE_JEET_St14__invoke_otherOT0_DpOT1_

**Comment by pengzhendong** [comment]
请检查音频的采样率
