### ISSUE TITLE
macOS M1 support?

### ISSUE THREAD

**Issue by jinfagang** [wenet-e2e/wenet#1350]
[ 96%] Linking CXX shared library libwenet_api.dylib
ld: warning: ignoring file ../../../fc_base/libtorch-src/lib/libtorch.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

**Comment by pengzhendong** [comment]
We do not have macOS M1 device. You can pull request that.

**Comment by jinfagang** [comment]
why runtime suffix is zip?? netron can not even visualize the model

**Comment by pengzhendong** [comment]
Plz see: https://github.com/wenet-e2e/wenet/blob/main/docs/pretrained_models.md

**Comment by jinfagang** [comment]
@pengzhendong Hi, am aware of this, but how can i convert the zip to torhcscript? I wanna visualize it in netron. It was load error with zip file. (not pytorch checkpoint)

**Comment by pengzhendong** [comment]
So Why not just use the trained pytorch checkpoint model?

**Comment by jinfagang** [comment]
@pengzhendong Hi, frankly speaking, am very very newbie in asr. I just wanna make a tiny application to recognise voice to text. I didn't find a way to infer it on macOS M1 with raw python pytorch (it seems need to build c++ and got error above).

So I wanna take a look at the model archecture than I can convert it to pnnx.

BTW, is there a way can I infer it in pytorch checkpoint without c++?

**Comment by pengzhendong** [comment]
https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/recognize.py

**Comment by jinfagang** [comment]
@pengzhendong How to recognize on a single wav file? I don't want download all the dataset.

**Comment by jinfagang** [comment]
got it.

**Comment by pengzhendong** [comment]
Prepare the single wav `data.list`. Runtime does not support M1.

**Comment by jinfagang** [comment]
@pengzhendong HI, I prepare a `data.list` like this:

```
kenan.wav
```

it says need json, what json I need?
