### ISSUE TITLE
torch::jit::ErrorReport error

### ISSUE THREAD

**Issue by zhaoyinjiang9825** [wenet-e2e/wenet#1352]
Hello, I re-exported the checkpoint model to the runtime model through wenet/bin/export_jit.py, it generated final.zip and final_quant.zip, and then I put train.yaml, utils.txt and final.zip into a directory As the model_dir directory, and then compile and execute the decoder_main file, it calls the GPU and reports the following error:
*********************************************************************************************************************************************
(wenet) [ZYJ@localhost LibTorch]$ model_dir=/home/ZYJ/WeNet/wenet_gpu/wenet/runtime/OnnxRuntime/model/20210815_unified_conformer_runtime
(wenet) [ZYJ@localhost LibTorch]$ ./build/bin/decoder_main     --chunk_size -1     --wav_path $wav_path     --model_path $model_dir/final.zip --unit_path $model_dir/units.txt 2>&1 | tee log.txt

I0802 17:35:13.902567 36283 params.h:135] Reading torch model /home/ZYJ/WeNet/wenet_gpu/wenet/runtime/OnnxRuntime/model/20210815_unified_conformer_runtime/final.zip
I0802 17:35:13.919255 36283 torch_asr_model.cc:36] Num intra-op threads: 1
I0802 17:35:13.919296 36283 torch_asr_model.cc:37] Num inter-op threads: 1
I0802 17:35:14.181143 36283 torch_asr_model.cc:47] CUDA available! Running on GPU
terminate called after throwing an instance of 'torch::jit::ErrorReport'
terminate called recursively
****************************************************************************************************************
May I ask which part is the problem?

**Comment by pengzhendong** [comment]
Plz build it without GPU.

**Comment by zhaoyinjiang9825** [comment]
I want to use GPU now. I see LibTorch's README.txt description that it is possible to build with GPU:
"""
For building with GPU, you should turn on GPU:
mkdir build && cd build && cmake -DGPU=ON .. && cmake --build .
"""
How can this be called successfully?

**Comment by zhaoyinjiang9825** [comment]
@pengzhendong

**Comment by zhaoyinjiang9825** [comment]
I succeeded by converting the model, thanks, I'll close it!

**Comment by AlexanderXuan** [comment]
@zhaoyinjiang9825 I met the same problem, can you give me some suggestions about how to convert model?

**Comment by Macsim2** [comment]
I face the same problem. Is there anyone who can tell me if it's still not working or if it's works, how to convert the model?

**Comment by wgfi110** [comment]
The problem maybe is caused by you exporting the model in a higher torch environment than the libtorch, you can export_jit.py the model in torch 1.10.

**Comment by wgfi110** [comment]
I think the wenet should update the libtorch.cmake to use a higher libtorch version.
