### ISSUE TITLE
为什么通过pretrained models 里面的train.yaml 和final.pt加载的权重和模型不一致？

### ISSUE THREAD

**Issue by qiuyuzhao** [wenet-e2e/wenet#1354]
我下载了wenetspeech，和aishell通过里面yaml文件运行的\wenet\bin\recognize.py文件，在加载模型权重时候报错：
RuntimeError: Error(s) in loading state_dict for ASRModel:
	Unexpected key(s) in state_dict: "encoder.encoders.0.concat_linear.weight", "encoder.encoders.0.concat_linear.bias", "encoder.encoders.1.concat_linear.weight", "encoder.encoders.1.concat_linear.bias", "encoder.encoders.2.concat_linear.weight", "encoder.encoders.2.concat_linear.bias", "encoder.encoders.3.concat_linear.weight", "encoder.encoders.3.concat_linear.bias", "encoder.encoders.4.concat_linear.weight", "encoder.encoders.4.concat_linear.bias", "encoder.encoders.5.concat_linear.weight", "encoder.encoders.5.concat_linear.bias", "encoder.encoders.6.concat_linear.weight", "encoder.encoders.6.concat_linear.bias", "encoder.encoders.7.concat_linear.weight", "encoder.encoders.7.concat_linear.bias", "encoder.encoders.8.concat_linear.weight", "encoder.encoders.8.concat_linear.bias", "encoder.encoders.9.concat_linear.weight", "encoder.encoders.9.concat_linear.bias", "encoder.encoders.10.concat_linear.weight", "encoder.encoders.10.concat_linear.bias", "encoder.encoders.11.concat_linear.weight", "encoder.encoders.11.concat_linear.bias", "decoder.left_decoder.decoders.0.concat_linear1.weight", "decoder.left_decoder.decoders.0.concat_linear1.bias", "decoder.left_decoder.decoders.0.concat_linear2.weight", "decoder.left_decoder.decoders.0.concat_linear2.bias", "decoder.left_decoder.decoders.1.concat_linear1.weight", "decoder.left_decoder.decoders.1.concat_linear1.bias", "decoder.left_decoder.decoders.1.concat_linear2.weight", "decoder.left_decoder.decoders.1.concat_linear2.bias", "decoder.left_decoder.decoders.2.concat_linear1.weight", "decoder.left_decoder.decoders.2.concat_linear1.bias", "decoder.left_decoder.decoders.2.concat_linear2.weight", "decoder.left_decoder.decoders.2.concat_linear2.bias", "decoder.right_decoder.decoders.0.concat_linear1.weight", "decoder.right_decoder.decoders.0.concat_linear1.bias", "decoder.right_decoder.decoders.0.concat_linear2.weight", "decoder.right_decoder.decoders.0.concat_linear2.bias", "decoder.right_decoder.decoders.1.concat_linear1.weight", "decoder.right_decoder.decoders.1.concat_linear1.bias", "decoder.right_decoder.decoders.1.concat_linear2.weight", "decoder.right_decoder.decoders.1.concat_linear2.bias", "decoder.right_decoder.decoders.2.concat_linear1.weight", "decoder.right_decoder.decoders.2.concat_linear1.bias", "decoder.right_decoder.decoders.2.concat_linear2.weight", "decoder.right_decoder.decoders.2.concat_linear2.bias". 
请问为什么初始化的模型会少这些结构呢？我没有修改train.yaml里面的参数

**Comment by robin1001** [comment]
下载了 wenetspeech, 就用 wenetspeech 的 train.yaml

**Comment by qiuyuzhao** [comment]
> 下载了 wenetspeech, 就用 wenetspeech 的 train.yaml

我表述的可能有问题，我下载了这两个模型的文件，分别用里面的yaml和对应的.pt，在加载模型的时候会报这种错误

RuntimeError: Error(s) in loading state_dict for ASRModel:
	Unexpected key(s) in state_dict: "encoder.encoders.0.concat_linear.weight", "encoder.encoders.0.concat_linear.bias", "encoder.encoders.1.concat_linear.weight", "encoder.encoders.1.concat_linear.bias", "encoder.encoders.2.concat_linear.weight", "encoder.encoders.2.concat_linear.bias", "encoder.encoders.3.concat_linear.weight", "encoder.encoders.3.concat_linear.bias", "encoder.encoders.4.concat_linear.weight", "encoder.encoders.4.concat_linear.bias", "encoder.encoders.5.concat_linear.weight", "encoder.encoders.5.concat_linear.bias", "encoder.encoders.6.concat_linear.weight", "encoder.encoders.6.concat_linear.bias", "encoder.encoders.7.concat_linear.weight", "encoder.encoders.7.concat_linear.bias", "encoder.encoders.8.concat_linear.weight", "encoder.encoders.8.concat_linear.bias", "encoder.encoders.9.concat_linear.weight", "encoder.encoders.9.concat_linear.bias", "encoder.encoders.10.concat_linear.weight", "encoder.encoders.10.concat_linear.bias", "encoder.encoders.11.concat_linear.weight", "encoder.encoders.11.concat_linear.bias", "decoder.left_decoder.decoders.0.concat_linear1.weight", "decoder.left_decoder.decoders.0.concat_linear1.bias", "decoder.left_decoder.decoders.0.concat_linear2.weight", "decoder.left_decoder.decoders.0.concat_linear2.bias", "decoder.left_decoder.decoders.1.concat_linear1.weight", "decoder.left_decoder.decoders.1.concat_linear1.bias", "decoder.left_decoder.decoders.1.concat_linear2.weight", "decoder.left_decoder.decoders.1.concat_linear2.bias", "decoder.left_decoder.decoders.2.concat_linear1.weight", "decoder.left_decoder.decoders.2.concat_linear1.bias", "decoder.left_decoder.decoders.2.concat_linear2.weight", "decoder.left_decoder.decoders.2.concat_linear2.bias", "decoder.right_decoder.decoders.0.concat_linear1.weight", "decoder.right_decoder.decoders.0.concat_linear1.bias", "decoder.right_decoder.decoders.0.concat_linear2.weight", "decoder.right_decoder.decoders.0.concat_linear2.bias", "decoder.right_decoder.decoders.1.concat_linear1.weight", "decoder.right_decoder.decoders.1.concat_linear1.bias", "decoder.right_decoder.decoders.1.concat_linear2.weight", "decoder.right_decoder.decoders.1.concat_linear2.bias", "decoder.right_decoder.decoders.2.concat_linear1.weight", "decoder.right_decoder.decoders.2.concat_linear1.bias", "decoder.right_decoder.decoders.2.concat_linear2.weight", "decoder.right_decoder.decoders.2.concat_linear2.bias".

**Comment by Mddct** [comment]
用最新代码

**Comment by zjc6666** [comment]
如果使用wenetspeech的与训练模型，在老代码中使用--enc_init参数，也是没法进行初始化的，可以告诉一下这个原因嘛？

**Comment by Mddct** [comment]
这个参数不是用来初始化模型的 是用来初始化encoder的

**Comment by donstang** [comment]
wenet代码做了更新，layer里面加了concat的操作，导致之前训练的模型没有这一部分的参数
<img width="685" alt="image" src="https://user-images.githubusercontent.com/15995403/205254868-4354e070-9729-4de0-911b-002b248208b7.png">
