### ISSUE TITLE
Does trinton_gpu version support Context Biasing?

### ISSUE THREAD

**Issue by zhaoyinjiang9825** [wenet-e2e/wenet#1355]
Hello, may I ask, does triton_GPU support the function of Context Biasing to correct proper nouns?

**Comment by robin1001** [comment]
@yuekaizhang

**Comment by yuekaizhang** [comment]
> Hello, may I ask, does triton_GPU support the function of Context Biasing to correct proper nouns?

Sorry, currently triton GPU solution can't do it. It would be possible if someone could first develop a pybind api. e.g. decoder = wenet.WFSTDecoder(ctc_log_probs) --> nbest_hyps

**Comment by zhaoyinjiang9825** [comment]
OK, thanks for the guidance!

**Comment by zhaoyinjiang9825** [comment]
OK, thanks for the guidance!
