### ISSUE TITLE
Onnx recognize inputs wrong

### ISSUE THREAD

**Issue by jinfagang** [wenet-e2e/wenet#1357]
I exported the onnx have 4 inputs:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/21303438/182770229-0189f12e-63fe-48be-b348-9d7caa76ce93.png">

but the demo shows:

<img width="497" alt="image" src="https://user-images.githubusercontent.com/21303438/182770182-f6a7b0e0-b04f-40d8-ae4f-4b1b2cbb6661.png">

How to make it infer? I exported the cpu version.

**Comment by robin1001** [comment]
Please see https://github.com/wenet-e2e/wenet/tree/main/runtime/OnnxRuntime
