### ISSUE TITLE
label_checker_main

### ISSUE THREAD

**Issue by zjc6666** [wenet-e2e/wenet#1364]
当我编译完wenet后，想要运行下label_checker_main，可否提供调用参数示例？

当我不提供参数时，报以下异常，是否是我编译的有问题导致？

**Comment by zjc6666** [comment]
terminate called after throwing an instance of 'c10::Error'
  what():  open file failed because of errno 2 on fopen: , file path: 
Exception raised from RAIIFile at ../caffe2/serialize/file_adapter.cc:27 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f6fdaabc4b2 in /home/jcz52/wenet-main/runtime/LibTorch/fc_base/libtorch-src/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f6fdaab8dbb in /home/jcz52/wenet-main/runtime/LibTorch/fc_base/libtorch-src/lib/libc10.so)
frame #2: caffe2::serialize::FileAdapter::RAIIFile::RAIIFile(std::string const&) + 0xde (0x7f6fc6cede9e in /home/jcz52/wenet-main/runtime/LibTorch/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #3: caffe2::serialize::FileAdapter::FileAdapter(std::string const&) + 0x31 (0x7f6fc6cee421 in /home/jcz52/wenet-main/runtime/LibTorch/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #4: torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x30 (0x7f6fc81b5ed0 in /home/jcz52/wenet-main/runtime/LibTorch/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #5: torch::jit::load(std::string const&, c10::optional<c10::Device>) + 0x54 (0x7f6fc81b6024 in /home/jcz52/wenet-main/runtime/LibTorch/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #6: ./label_checker_main() [0x5e1244]
frame #7: ./label_checker_main() [0x46d337]
frame #8: ./label_checker_main() [0x46efb4]
frame #9: __libc_start_main + 0xf5 (0x7f6fc394e495 in /lib64/libc.so.6)
frame #10: ./label_checker_main() [0x46cc79]

**Comment by woqiang0515** [comment]
I tried with my own code to run the label_checker_main exe.
Here is the template:
label_checker_main \
     --rescoring_weight $rescoring_weight \
     --ctc_weight $ctc_weight \
     --reverse_weight $reverse_weight \
     --chunk_size $chunk_size \
     --wav_scp data/*/wav.scp \
     --model_path exp/*/final.zip \
     --text data/*/text \
     --unit_path $unit_path \
     --timestamp timestamp \
     --result result  &>  run.log
After running, the timestamp will be stored within file timestamp.
