### ISSUE TITLE
export_jit with different version of wenet lead to different decode result?

### ISSUE THREAD

**Issue by kli017** [wenet-e2e/wenet#1367]
Hello, I found that export_jit with different version of wenet lead to different decode result.
I was training the wenet model with a previous version without lm and after training I use wenet with lm to export the pt model.
And I found that the decode result very different from each other?

**Comment by robin1001** [comment]
What's the different? higher version shows better WER?  please first remove `lm` to do fair comparison.

**Comment by kli017** [comment]
We are using a very old version without lm implementation training the model. The pytorch vesion is 1.6.0. And recently need to add lm. So I export the previous trained unified conformer model with jit in a newer version(commit 172df757cd38c8c566808509e888e9e98411fdb4 pytorch 1.10.0). After get the final.zip I tested with some utts(without lm) and found that the exported model get a wrose WER(example: "我在这个这个张店区" became  "广寨镇张店区").

**Comment by Mddct** [comment]
plz note：
1 runtime has more changes in latest code，plz using latest runitme code

2 words.txt rename to unit.txt that is e2e model unit

**Comment by kli017** [comment]
@Mddct Thanks for remind, words.txt already renamed to unit.txt. For some reason my colleague still using the old version to train the model. I just found this issue while I implement model with different version of wenet. using the same version wenet to export does not have this problem.

**Comment by robin1001** [comment]
Great!
