### ISSUE TITLE
runtime decode的效果比较差，wenet/bin/recognize.py的效果比较好，为啥？

### ISSUE THREAD

**Issue by nocoolsandwich** [wenet-e2e/wenet#1369]
使用runtime decode，即使录音有一点噪音也会导致decode不出来。而使用python脚本即wenet/bin/recognize.py出来的结果会比较好？是什么原因导致的？

**Comment by robin1001** [comment]
I have no idea, try to show more information.

**Comment by nocoolsandwich** [comment]
[1.zip](https://github.com/wenet-e2e/wenet/files/9457890/1.zip)
Thanks for your reply.My issue describe as below.
I got a audio(see the zip file).  

The result of `wenet\wenet\bin\recognize.py` looks like thie:
```
您好过号妈三很高兴为您服务尊钱会员陈先生来电话讲定个谷关节凌是吧
```

using `wenet/runtime/server/x86/build/bin/decoder_main` result:
```
好好先生来电
```

then i try to remove the noise from the audio and feed it for `wenet/runtime/server/x86/build/bin/decoder_main`,the result:
```
好好先生电话订购关节
```
 
I beleive that the noise is the key of this problem because there is no problem when decode aishell data's audio.
Is that some voice detect function in decoder_main.cc?

I am appreciate for your replay at your convince!

**Comment by nocoolsandwich** [comment]
我猜测是因为我使用了lm，而lm的音素词典不含有我的场景的词条，我去验证一下

**Comment by nocoolsandwich** [comment]
发现原因了，是因为音素词典没有我的场景的词条导致的。
