### ISSUE TITLE
流式识别教程

### ISSUE THREAD

**Issue by kejom-ou** [wenet-e2e/wenet#1372]
能否提供流式识别的教程

**Comment by robin1001** [comment]
please see https://github.com/wenet-e2e/wenet/tree/main/runtime/libtorch

**Comment by kejom-ou** [comment]
Have a python version for streaming recognize?

**Comment by kejom-ou** [comment]
Is there a python version of streaming recognition？

**Comment by robin1001** [comment]
please see https://github.com/wenet-e2e/wenet/blob/main/runtime/binding/python/README.md.

![image](https://user-images.githubusercontent.com/6036624/184565032-449b657f-c213-423e-815d-4bb0dcc431df.png)

**Comment by kejom-ou** [comment]
thanks

**Comment by kejom-ou** [comment]
Can I see wenet'source code of python version ? I can not debug for research deploying.
