### ISSUE TITLE
how to compile decoder_main

### ISSUE THREAD

**Issue by xiaochunxin** [wenet-e2e/wenet#1374]
![84c881513fa0f782a0ef87ea1878881](https://user-images.githubusercontent.com/45034922/184355803-547f023d-cdfe-4c8a-9937-cf9d7f817d20.png)
Do I need to enable libtorch to compile decoder main now? I tried both Server /x86 and libtorch compilations and encountered the above problem. The last err shown is:
![a49a1540e61a626838555dda05e76a6](https://user-images.githubusercontent.com/45034922/184355933-a361b900-a724-4bae-98d8-e8b861af27c9.png)
indside the libtorch/build/CMakeFiles/CMakeError.log is:
Source file was:

__declspec(selectany) int a;
int main(void) { return 0; }

Performing C++ SOURCE FILE Test STL_NO_NAMESPACE failed with the following output:
Change Dir: /dataset/chunxinxiao/wenet/runtime/libtorch/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_eb4ff/fast && /usr/bin/make  -f CMakeFiles/cmTC_eb4ff.dir/build.make CMakeFiles/cmTC_eb4ff.dir/build
make[1]: Entering directory '/dataset/chunxinxiao/wenet/runtime/libtorch/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_eb4ff.dir/src.cxx.o
/usr/bin/c++ -DSTL_NO_NAMESPACE  -std=c++14 -pthread -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -DC10_USE_GLOG  -o CMakeFiles/cmTC_eb4ff.dir/src.cxx.o -c /dataset/chunxinxiao/wenet/runtime/libtorch/build/CMakeFiles/CMakeTmp/src.cxx
/dataset/chunxinxiao/wenet/runtime/libtorch/build/CMakeFiles/CMakeTmp/src.cxx:3:1: error: ‘vector’ does not name a type
    3 | vector<int> t; int main() { }
      | ^~~~~~
make[1]: *** [CMakeFiles/cmTC_eb4ff.dir/build.make:78: CMakeFiles/cmTC_eb4ff.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/dataset/chunxinxiao/wenet/runtime/libtorch/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_eb4ff/fast] Error 2

Source file was:

#include <vector>
vector<int> t; int main() { }

Performing C++ SOURCE FILE Test HAVE_MSVC_TLS failed with the following output:
Change Dir: /dataset/chunxinxiao/wenet/runtime/libtorch/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make -f Makefile cmTC_9e42e/fast && /usr/bin/make  -f CMakeFiles/cmTC_9e42e.dir/build.make CMakeFiles/cmTC_9e42e.dir/build
make[1]: Entering directory '/dataset/chunxinxiao/wenet/runtime/libtorch/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_9e42e.dir/src.cxx.o
/usr/bin/c++ -DHAVE_MSVC_TLS  -std=c++14 -pthread -fPIC -D_GLIBCXX_USE_CXX11_ABI=0 -DC10_USE_GLOG  -o CMakeFiles/cmTC_9e42e.dir/src.cxx.o -c /dataset/chunxinxiao/wenet/runtime/libtorch/build/CMakeFiles/CMakeTmp/src.cxx
/dataset/chunxinxiao/wenet/runtime/libtorch/build/CMakeFiles/CMakeTmp/src.cxx:2:11: error: expected constructor, destructor, or type conversion before ‘(’ token
    2 | __declspec(thread) int tls;
      |           ^
make[1]: *** [CMakeFiles/cmTC_9e42e.dir/build.make:78: CMakeFiles/cmTC_9e42e.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/dataset/chunxinxiao/wenet/runtime/libtorch/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:127: cmTC_9e42e/fast] Error 2

It seems related to the env, my friends computer worked!

**Comment by robin1001** [comment]
Just follow https://github.com/wenet-e2e/wenet/tree/main/runtime/libtorch#run-with-local-build to build. It seems it works on your friend's computer, so please check your env. I have no idea from the log, I think you can align the env with your friend's
