### ISSUE TITLE
The decoding result lacks the splice character "__"

### ISSUE THREAD

**Issue by rookie0607** [wenet-e2e/wenet#1378]
When running librispeech, I use subword LM, but I find that the decoding result lacks the splice character "__", How can I solve it? thank you.

**Comment by Mddct** [comment]
postprocess replace __

**Comment by robin1001** [comment]
It is replaced at https://github.com/wenet-e2e/wenet/blob/main/examples/librispeech/s0/run.sh#L208.

**Comment by rookie0607** [comment]
> postprocess replace __

I found that "__" is missing when running to runtime, There seems to be no replacement code found here.

**Comment by rookie0607** [comment]
> It is replaced at https://github.com/wenet-e2e/wenet/blob/main/examples/librispeech/s0/run.sh#L208.

I found that "__" is missing when running to runtime, There seems to be no replacement code found here.

**Comment by Mddct** [comment]
plz see:

https://github.com/wenet-e2e/wenet/blob/2e7838d0fee36b4f7e7932f1be605d3ec64e7d52/runtime/core/post_processor/post_processor.h#L37

**Comment by rookie0607** [comment]
> plz see:
> 
> https://github.com/wenet-e2e/wenet/blob/2e7838d0fee36b4f7e7932f1be605d3ec64e7d52/runtime/core/post_processor/post_processor.h#L37
> 
> https://github.com/wenet-e2e/wenet/blob/main/runtime/core/post_processor/post_processor.cc

Thanks for your guidance, my problem has been solved. Thank you very much
