### ISSUE TITLE
Undefined reference when compile decode_main with GPU support

### ISSUE THREAD

**Issue by robin1001** [wenet-e2e/wenet#1379]
Here is the log.

![23eb880aaf1d5045a819eefee6f9c12](https://user-images.githubusercontent.com/6036624/184564610-74c29251-128d-423a-aa29-857fa5bb052c.png)

**Comment by robin1001** [comment]
@yuekaizhang @veelion please follow the problem.

**Comment by veelion** [comment]
Maybe the cuda version build with libtorch_cuda_cpp.so, does not match the cuda version installed on the system.

**Comment by bmfire1** [comment]
same problem when rebuild with GPU

**Comment by robin1001** [comment]
Maybe there is version conflict in libtorch cuda and your system cuda, please check.

**Comment by xpanp** [comment]
I have the same problem. Wenet require install cudatoolkit with 11.1, but in `runtime/core/cmake/libtorch.cmake`, `set(CUDA_NAME "cu113")`.  When i change the version to 11.1 in `libtorch.cmake`, it worked.

**Comment by xingchensong** [comment]
Will hold this PR for anyone else who has encountered and interested in the same question.
