### ISSUE TITLE
automatically decoding sequence in silence after building the apk and installing on android phone

### ISSUE THREAD

**Issue by wl1221** [wenet-e2e/wenet#1380]
hi dongge，I use my own datas to train a new model which only modified parameters of the model but not change the structure of the model。Then I build the apk following the tutorial that you published in CSDN，after I install the apk，it automatically decoded sequence in silence，please what is the problem？thanks！

**Comment by wl1221** [comment]
When I use recognize.py the rate is good，but the result is automatically decoding in silence when I test with the apk。Do my model have some issues？

**Comment by pengzhendong** [comment]
With LM or without LM?

**Comment by wl1221** [comment]
without LM

**Comment by pengzhendong** [comment]
May be you should try it with websocket.

**Comment by wl1221** [comment]
thanks, dongge, I solved it, it's my model problems
