### ISSUE TITLE
Support RNNT in runtime mode

### ISSUE THREAD

**Issue by PPGGG** [wenet-e2e/wenet#1385]
Does wenet support RNNT in runtime mode, which shows great potential in streaming asr ?

**Comment by Mddct** [comment]
> Does wenet support RNNT in runtime mode, which shows great potential in streaming asr ?

@robin1001 
Yes, but from my point of view, our priority is to try to adjust the rnnt result to the best effect. For the runtime, it is relatively easy to integrate into the current code.

**Comment by robin1001** [comment]
RNN-T is under experimental evaluation. If RNN-T shows superior performance over the current U2++ system and the conlusion is very solid, we will support RNN-T in the runtime.

**Comment by PPGGG** [comment]
Good to know that. Really appreciated.
