### ISSUE TITLE
python: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.

### ISSUE THREAD

**Issue by DemonDamon** [wenet-e2e/wenet#1395]
when i ran my cli:
`python wenet/bin/train.py --gpu 1 --config ./wenetspeech_train_conformer_bidecoder.yaml --data_type raw --symbol_table ./med_unit.txt --train_data ./data.list --cv_data ./data.list --model_dir ./model_saved --cmvn ./global_cmvn --num_workers 8`

and i got issues:
```
python: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Aborted (core dumped)
```

my cuda version is cuda11.3, torch version is 1.12.1

here is my cli history,
firstly, i ran in 1 3080ti:
```
python wenet/bin/train_wenetspeech.py \
--gpu 1 \
--config ./wenetspeech_train_conformer_bidecoder.yaml \
--data_type raw \
--symbol_table ./med_unit.txt \
--train_data ./data.list \
--cv_data ./data.list \
--model_dir ./model_saved \
--cmvn ./global_cmvn \
--num_workers 8 
it can calculate loss, but OOM immediately
```

then i want to use 2 3080ti with cli below, and i had no idea what is ddp.init_method, so i just copied "file:///export/nfs/ddp_init " here:
```
python wenet/bin/train_wenetspeech.py \
--gpu 1 \
--config ./wenetspeech_train_conformer_bidecoder.yaml \
--data_type raw \
--symbol_table ./med_unit.txt \
--train_data ./data.list \
--cv_data ./data.list \
--model_dir ./model_saved \
--cmvn ./global_cmvn \
--num_workers 8 \
--checkpoint ./pretrained_model_list/wenetspeech-cn-conformer-checkpoint/20220506/final.pt \
--ddp.init_method file:///export/nfs/ddp_init \
--ddp.world_size 2 \
--ddp.rank 0 \
--ddp.dist_backend nccl
```

then i found it took too long, so i forced to stop it, and ran again, no matter what parameters are set,
```
python: ../nptl/pthread_mutex_lock.c:81: __pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Aborted (core dumped)
```
still raised

what s that, any help?

**Comment by by2101** [comment]
I encountered the same problem with K2. Maybe it is an environment problem.

**Comment by xingchensong** [comment]
> I encountered the same problem with K2. Maybe it is an environment problem.

thanks for reply.
