### ISSUE TITLE
 'wenet' has no attribute 'Decoder'

### ISSUE THREAD

**Issue by bboyxu5928** [wenet-e2e/wenet#1408]
when I try this demo to test the wenet ,but follow error shows,who can help me fix it.thanks 

demo:

import sys
import wenet

wav_file = '/home/workspace/wenet/11.wav'
decoder = wenet.Decoder(lang='chs',
                        nbest=5,
                        enable_timestamp=True,
                        context=['不忘初心', '牢记使命'],
                        context_score=3.0)
ans = decoder.decode_wav(wav_file)
print(ans)

error:

Traceback (most recent call last):
  File "wenet.py", line 2, in <module>
    import wenet
  File "/home/workspace/wenet/wenet.py", line 5, in <module>
    decoder = wenet.Decoder(lang='chs',
AttributeError: partially initialized module 'wenet' has no attribute 'Decoder' (most likely due to a circular import)

**Comment by Mddct** [comment]
plz rename your  wenet.py to other name

**Comment by bboyxu5928** [comment]
> plz rename your wenet.py to other name

it doesn't work,the error is the same

AttributeError: module 'wenet' has no attribute 'Decoder'

**Comment by robin1001** [comment]
Please do not run it at the root directory of wenet.
