### ISSUE TITLE
call decoder.decode_wav multiple times in sequence

### ISSUE THREAD

**Issue by affanmehmood** [wenet-e2e/wenet#1414]
I am trying to process a long wav file. As it is not possible to process the file at once, I am first splitting the files into chunks and then trying to process them one by one. The problem is that the decoder.decode_wav(chunk_name) processes the 1st chunk successfully but then crashes when called again inside the loop.

Error:
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0830 10:51:27.304338 11900 feature_pipeline.cc:57] Check failed: !input_finished_ 
*** Check failure stack trace: ***

Code to recreate the error:

from pydub import AudioSegment
from pydub.utils import make_chunks

sound = AudioSegment.from_wav("./examples/mandarin.wav")
chunks = make_chunks(sound, 60000)  # Make chunks of one min

decoder = wenet.Decoder(lang='chs',
                        nbest=1,
                        enable_timestamp=True,
                        context_score=3.0)

for i, chunk in enumerate(chunks):
    # save the chunks
    chunk_name = "./examples/chunk{0}.wav".format(i)
    chunk.export(chunk_name, format="wav")
    print('line number {}'.format(i))
    
    # decode the chunks
    ans = decoder.decode_wav(chunk_name)
    print(ans)

**Comment by robin1001** [comment]
please call decoder.reset() after calling decode_wav to reset decoding status.

**Comment by affanmehmood** [comment]
Thanks! Also is there a way to process a long wav file without needing to split it up?

**Comment by robin1001** [comment]
Add `continuous_decoding=True` when initializing the `Decoder`, please see https://github.com/wenet-e2e/wenet/blob/main/runtime/binding/python/README.md.

**Comment by affanmehmood** [comment]
I will check it out! Thanks again!
