### ISSUE TITLE
Triton wenet_client error

### ISSUE THREAD

**Issue by NathanJHLee** [wenet-e2e/wenet#1420]
Hi, My name is Nathan.
I tried to check performance based on triton server.
In my case, I works at closed network env.
So avoiding this issue, I Built server(and client) docker at open network env and move images to closed env.
Finally I started server on one gpu.

[asr@k-atc12 ~]$ docker ps
CONTAINER ID   IMAGE                 COMMAND                  CREATED        STATUS          PORTS                                                           NAMES
ae14c456f950   wenet_server:latest   "/opt/nvidia/nvidia_…"   15 hours ago   Up 15 hours     0.0.0.0:8000-8002->8000-8002/tcp, :::8000-8002->8000-8002/tcp   tender_murdock

[asr@k-atc12 ~]$ nvidia-smi
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    259800      C   tritonserver                     1389MiB |
+-----------------------------------------------------------------------------+

After checking triton-server works properly, I  started client and tried to run as follows
$ python3 client.py --audio_file=/ws/test_data/41_0511_760_0_09479_01.wav --model_name=streaming_wenet --streaming

root@k-atc12:/ws/client# file /ws/test_data/41_0511_760_0_09479_01.wav
/ws/test_data/41_0511_760_0_09479_01.wav: RIFF (little-endian) data, WAVE audio, Microsoft PCM, 16 bit, mono 8000 Hz

**But I got errors as follows**

root@k-atc12:/ws/client# python3 client.py --audio_file=/ws/test_data/41_0511_760_0_09479_01.wav --url=localhost:8001 --model_name=streaming_wenet --streaming
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 576, in _handle_results
    task = get()
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 1 required positional argument: 'msg'

Please check this issue. 
Thank you

**Comment by robin1001** [comment]
@yuekaizhang please follow the PR.

**Comment by yuekaizhang** [comment]
Did you set the sampling rate here https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/model_repo_stateful/feature_extractor/config_template.pbtxt#L30? Looks like you are using 8k audios for test. Also, could you try test it with perf_analyzer (see https://github.com/wenet-e2e/wenet/tree/main/runtime/gpu perf test part)?

**Comment by NathanJHLee** [comment]
Oh i see. I made mistake that i didn't change sampling rate information on 'train.yaml' even though i trained 8k model.
Thank you so much for your help.

It works fine. Thank you!
