### ISSUE TITLE
How to limit the Triton server GPU memory ?

### ISSUE THREAD

**Issue by ziyu123** [wenet-e2e/wenet#1422]
目前用Triton server的默认配置，当发送请求教多的时候，GPU显存会不断增加，最后会达到显卡最大显存。
尝试在config文件中设置 gpu_mem_limit 或 max_workspace_size_bytes ， 都没有起作用。
而且，在把max_batch_size 设置为32， 各个模型的instance_group都设置为1后，显存还是会占满。
请问，怎么设置这里的GPU显存？

**Comment by yuekaizhang** [comment]
你的情况说明跑 batch size 32的话会爆显存，并发大了的话推理的 batch size就越来越接近 max_batch_size。 可以再调小 max_batch_size, 比如换成 16 试试

**Comment by ziyu123** [comment]
> 

嗯嗯，我现在设置为4或8了，主要是输入的音频比较长，有几十秒，现在显存下来了，不过响应时间变长了
