### ISSUE TITLE
Instructions for abbreviation and special symbols

### ISSUE THREAD

**Issue by dipeshhoncho07** [wenet-e2e/wenet#1424]
Can someone please guide on how to use abbreviation in text (Specifically, can we write "AIDS" as "A_I_D_S" in text file). Also, can we use special characters such as ' _ - " in text file and LM ?

**Comment by xingchensong** [comment]
we use "▁" instead of "_" for blanks among english words, so it's okay to use '_-'

refer to https://github.com/wenet-e2e/wenet/blob/main/tools/text2token.py for text processing
