### ISSUE TITLE
Resuming from runtime model

### ISSUE THREAD

**Issue by affanmehmood** [wenet-e2e/wenet#1435]
Is it possible to resume training from a runtime model that contains final.zip, units.txt, train.yaml file?

Also, what is the purpose of -cv_data and -train_data arguments in train.py?

**Comment by robin1001** [comment]
It is not recommended to train from the runtime model. cv_data is used for validation, train_data is used for training.

**Comment by affanmehmood** [comment]
Is it possible to resume training from Checkpoint Model and then save it as a Runtime Model? If yes then how? The thing is that I want a Runtime Model for inference.

Also is there a dataset that has -cv_data, -train_data, and -symbol_table files?

**Comment by robin1001** [comment]
Yes, please see the standard training pipeline such as librispeech.

All the datasets in WeNet have cv_data, train_data, and symbol_table.

**Comment by affanmehmood** [comment]
Thanks! Can you please share the link to one of those datasets?
