### ISSUE TITLE
Pretrained GigaSpeech sentencepiece model

### ISSUE THREAD

**Issue by FredSRichardson** [wenet-e2e/wenet#1438]
**Is your feature request related to a problem? Please describe.**
I am investigating language model training with a pre-trained model.  I think I need a sentencepiece model to map my lexicon to the output token list of the model.

**Describe the solution you'd like**
Please include the sentencepiece model in the downloadable pre-trained model archives.

**Describe alternatives you've considered**
Is there a way to create a functioning spm_encoder from just the token list?  I would consider that, but I don't think it is easy to do.

**Additional context**
No additional context for this.

**Comment by robin1001** [comment]
Please download it from https://wenet-1256283475.cos.ap-shanghai.myqcloud.com/models/gigaspeech/20210728_u2pp_conformer_exp.tar.gz. The BPE model is named as `train_xl_unigram5000.model`.

**Comment by FredSRichardson** [comment]
That is perfect, thank you so much!!!

**Comment by yunigma** [comment]
Hello @robin1001 ! I have the same question but it looks like the link does not work anymore. Please, could you share it again? Thanks! Yulia

**Comment by yunigma** [comment]
It has possibly happened because of the commit: ```https://github.com/wenet-e2e/wenet/commit/999f6ef4f21987324776f5c8be86c2b18377b66f```... Do you still have the conformer pretrained on Gigaspeech and with the BPE model? :pray:

**Comment by robin1001** [comment]
> It has possibly happened because of the commit: `https://github.com/wenet-e2e/wenet/commit/999f6ef4f21987324776f5c8be86c2b18377b66f`... Do you still have the conformer pretrained on Gigaspeech and with the BPE model? 🙏

Fixed, please see https://github.com/wenet-e2e/wenet/pull/1660. There is a BPE model in the checkpoint model.

**Comment by yunigma** [comment]
Great! Thank you a lot!
