### ISSUE TITLE
Quetion of training time of the provided checkpoints

### ISSUE THREAD

**Issue by hanggun** [wenet-e2e/wenet#1442]
Thanks for your amazing project.
I am curious about the training time of the provided checkpoints. Does it train from the 10000+ hour wenet speech?  How many devices do you use?  How long did you train the model. How many epochs do you use and how about the final loss

**Comment by robin1001** [comment]
WenetSpeech checkpoint is trained from 10000+ hours data. We use 24 V100 gpus with 25 epochs, and it takes about 3 days. The final loss is around 8~10%.

**Comment by hanggun** [comment]
Thanks for your reply!
