### ISSUE TITLE
any possibilities for pyPI package for manylinux2014_aarch64 ?

### ISSUE THREAD

**Issue by hannanma** [wenet-e2e/wenet#1443]
I am running python3 on an ARM-android platform for evaluation purpose of this great end to end python version of kaldi XD

pip3 install wenetruntime failed on my environment.
Seems on pyPI there is no wheels for aarch64.

pip3 install opencv-python actuall installed below pkg:
opencv_python-4.6.0.66-cp36-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl 

However, I am able to compile locally and use it all fine (so far so good).

Is there anyway to extract my local built version as a wenetruntime.manylinux2014_aarch64.whl ?
Or should we request the wenetruntime package on pyPI to include aarch64 version?

Thanks

**Comment by pengzhendong** [comment]
Plz make a pull request to this file: https://github.com/wenet-e2e/wenet/blob/main/.github/workflows/wheels.yml

**Comment by pengzhendong** [comment]
May be you need this action: [Arm runner](https://github.com/marketplace/actions/arm-runner).

**Comment by Gmgge** [comment]
@hannanma

**Comment by Gmgge** [comment]
@hannanma  hi
do you have any suggestions for wenetruntime running on aarch64 ? I compiled

**Comment by StuartIanNaylor** [comment]
https://github.com/KumaTea/pytorch-aarch64/releases/tag/v1.10.0
I guess you could install via pip then compile?

**Comment by xingchensong** [comment]
Hi, PR is welcome
