### ISSUE TITLE
react-native-wenet

### ISSUE THREAD

**Issue by Hannes1** [wenet-e2e/wenet#1449]
**Is your feature request related to a problem? Please describe.**
Thank you @pengzhendong for closing [this](https://github.com/pengzhendong/wenet-openfst-android/issues/1#issue-1319535677). I started working on [react-native-wenet](https://github.com/Hannes1/react-native-wenet) and it's working on android. I was wondering if some of the python features can be added to android/java

**Describe the solution you'd like**
     1. enable_timestamp
     2. context: context words
     3. context_score: bonus score when the context is matched
     4. will PyTorch-android-lite work?

**Describe alternatives you've considered**
I've tried looking at the current python implementation but haven't had much success

**Additional context**
If there's any other place I should rather post this please let me know

**Comment by robin1001** [comment]
Great job!

For 1-3, the answer is `yes`, sall the python featurea are based on core C++ code.
For 4, we havn't tried it. However, wenet is based on `Transformer`, which is not a light weight model.
