### ISSUE TITLE
Conv2dSampling6-right-context  error?

### ISSUE THREAD

**Issue by Guodong0712** [wenet-e2e/wenet#1451]
https://github.com/wenet-e2e/wenet/blob/ee43964afd8fe1c984f030124075b9d1e463b444/wenet/transformer/subsampling.py#L150

Hi all,
        The right context of Conv2dSampling6 (right_context = 14) seems error, maybe, it should equal to 10?

Thanks.

**Comment by robin1001** [comment]
Good catch, it should be 10, could you help to make a PR?

**Comment by xingchensong** [comment]
Thans, Fixed
