### ISSUE TITLE
Train true case model

### ISSUE THREAD

**Issue by dipeshhoncho07** [wenet-e2e/wenet#1454]
Hi, can we train a true case model using wenet? If yes, then how? I gave the true case / mixed case text (i.e., text contains uppercase as well as lowercase text) while training and getting only capital labels while decoding. The issue is that the model is not recognizing any of the lowercase tokens and recognizing tokens corresponding to uppercase text.

Note: I'm using librispeech recipe and in the data.list there are mix of lower case and uppercase in text.

**Comment by xingchensong** [comment]
librispeech doesn't have lowercase text

**Comment by dipeshhoncho07** [comment]
Sorry for creating the confusion but I only used librispeech recipe from stage 1 over my own data. So, frankly I have not used any librispeech audio or text data.

**Comment by xingchensong** [comment]
If u want to train mixcase model, just add both lowercase token and uppercase token to your dict. However, this is not recommended, simply apply a post-processing method to translate uppercase asr result to any mixcase u want might be a better solution.

**Comment by dipeshhoncho07** [comment]
@xingchensong I kept both in the dict. My BPE model trained on mixcase and has units.txt file that contains both the tokens. However, I suspect inside train.py somewhere all the words are getting capitalized and as result of that my AM got only trained on token ids that are mapped to uppercase in unit.txt file. I have following two questions:
1.) Have you ever trained a mixcase AM using wenet recipe.
2.) As you recommended to simply apply a post-processing method to translate uppercase asr to mixcase. Can you please state some of the findings or observations you have for recommending such case. Why should one avoid mixcase training?

**Comment by dipeshhoncho07** [comment]
@xingchensong I kept both in the dict. My BPE model trained on mixcase and has units.txt file that contains both the tokens. However, I suspect inside train.py somewhere all the words are getting capitalized and as result of that my AM got only trained on token ids that are mapped to uppercase in unit.txt file. I have following two questions:
1.) Have you ever trained a mixcase AM using wenet recipe.
2.) As you recommended to simply apply a post-processing method to translate uppercase asr to mixcase. Can you please state some of the findings or observations you have for recommending such case. Why should one avoid mixcase training?

**Comment by dipeshhoncho07** [comment]
@xingchensong I kept both in the dict. My BPE model trained on mixcase and has units.txt file that contains both the tokens. However, I suspect inside train.py somewhere all the words are getting capitalized and as result of that my AM got only trained on token ids that are mapped to uppercase in unit.txt file. I have following two questions:
1.) Have you ever trained a mixcase AM using wenet recipe.
2.) As you recommended to simply apply a post-processing method to translate uppercase asr to mixcase. Can you please state some of the findings or observations you have for recommending such case. Why should one avoid mixcase training?

Samples of units.txt file:
▁patel 3350
▁patella 3351
▁patellar 3352
▁patellofemoral 3353
▁patent 3354
▁paternal 3355
path 3356
▁pathological 3357
▁pathology 3358
▁pathway 3359
pati 3360
▁patient 3361
patosplenomegaly 3362
▁patricia 3363
▁pattern 3364
▁paul 3365
▁PCI 3366
▁PCO 3367
▁PCR 3368
▁PD 3369
pe 3370
▁PE 3371
▁peak 3372
▁peanut 3373
pectoral 3374
▁PEG 3375
▁pelvic 3376
▁pelvicalyceal 3377
▁pelvis 3378
pen 3379
▁pen 3380

**Comment by xingchensong** [comment]
1) no, we force to do uppercase here: https://github.com/wenet-e2e/wenet/blob/main/wenet/dataset/processor.py#L330
2) most of the time, `_PCR` and `_pcr` have equal meanings, it's better to merge them to get a smaller unit dict.

**Comment by xingchensong** [comment]
Feel free to reopen this issue if u have any problems.
