### ISSUE TITLE
build runtime error

### ISSUE THREAD

**Issue by apoca909** [wenet-e2e/wenet#1457]
build from wenet/runtime/libtorch/docker/Dockerfile

log:
<img width="838" alt="image" src="https://user-images.githubusercontent.com/4969897/191199823-8ba75ddb-a269-41da-9db8-ca03f930e17a.png">

**Comment by xingchensong** [comment]
cc @pengzhendong

**Comment by xingchensong** [comment]
your libtorch version dose not match system arch (x86/aarch64/... etc)

**Comment by apoca909** [comment]
root@docker-desktop:~/wenet/runtime/libtorch/build# arch
aarch64

which libtorch should i use?

**Comment by apoca909** [comment]
> your libtorch version dose not match system arch (x86/aarch64/... etc)


system archis aarch64, which libtorch should i use?
