### ISSUE TITLE
about memory leaks in runtime decoder 

### ISSUE THREAD

**Issue by mirajane0520** [wenet-e2e/wenet#1461]
**Describe the bug**
During debugging runtime version of decoder and checking memory leak using valgrind, a lot of memory leaks are founded.
==24650==    definitely lost: 22,168 bytes in 131 blocks
==24650==    indirectly lost: 738,712 bytes in 9,394 blocks
==24650==      possibly lost: 33,750,192 bytes in 103 blocks
==24650==    still reachable: 1,022,665 bytes in 14,729 blocks
==24650==                       of which reachable via heuristic:
==24650==                         multipleinheritance: 4,880 bytes in 63 blocks
==24650==         suppressed: 0 bytes in 0 blocks
Almost all of them are caused by libtorch_cpu.so
First leak is found when doing encoder chunk forward, after ‘forward_encoder_chunk’ is invoked.
auto outputs = model_->torch_model()
                   ->get_method("forward_encoder_chunk")(inputs)
                   .toTuple()
                   ->elements();
when doing batch test, there is also continuous growth of memory. E.g.
In the begining,  memory occupation is 74428kb. It increases to 609944kb after model is loaded, the amount of increase is approximately equal to the model size. Then decoding a list of audios, memory is continuously increasing, from initial 1717696kb to 2896672kb, and it still increased when decoding subsequent data. 
When I searching solutions, someone said libtorch produces memory leaks during forward process if batch size of data used to compute is changed , it seems that libtorch using the method ‘forward_encoder_chunk’, which in practice using forward_chunk, I am not whether forward_chunk also has similiar probelms.
besides, I am not sure, does export_jit python script pack the model class including the forward_encoder_chunk, litorch just help c++ invoke python method? So to fix this solution, it needs to check forward method in python scripts, or is there any good solution for memory leaks problem?

**Comment by Mddct** [comment]
据我了解 这不是内存泄漏，如果从model里拿到的tensor不主动release的话 libtorch的内存管理会delay清理l这些内存

如果可以的话 你找台内存大一些机器 比如16g 即使并发后 内存会稳定到一定范围

**Comment by WangGewu** [comment]
@mirajane0520 请问你解决这个问题了吗？
我也遇到了同样的问题，客户端连续调用两天，服务端的内存会一直缓慢增长

**Comment by KakayaLin** [comment]
Got the same problem here, is there any update about this issue?

**Comment by hacjac** [comment]
it might be memory fragmentation. i got the same problem. our analysis indicated that our application, which uses multithreading and has varying tensor sizes during computation, resulted in memory fragmentation. then i replaced the default C++ memory allocator with jemalloc, which solved the problem.
