### ISSUE TITLE
Why does the downloaded ".pt" not match with the train.yaml in openasr2021?

### ISSUE THREAD

**Issue by fangfuping** [wenet-e2e/wenet#1465]
RuntimeError: unexpected key in state_dict: "encoder.encoders.0.concat_linear.weight","encoder.encoders.0.concat_linear.bias",...

**Comment by fangfuping** [comment]
when we adapted the pretrained encoders to finetune our asr？

**Comment by xingchensong** [comment]
u can set strict=Flase, https://github.com/wenet-e2e/wenet/blob/main/wenet/utils/checkpoint.py#L31
