### ISSUE TITLE
segmentation fault when export_onnx_gpu

### ISSUE THREAD

**Issue by 1215thebqtic** [wenet-e2e/wenet#1469]
Are there any solutions to the following situation? thanks!

Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Traceback (most recent call last):
  File "wenet/bin/export_onnx_gpu.py", line 574, in <module>
run_decode_onnx_gpu.sh: line 32: 542480 Segmentation fault      (core dumped) python3 wenet/bin/export_onnx_gpu.py --config=$model_dir/train.yaml --checkpoint=$model_dir/avg_10.pt --cmvn_file=$model_dir/global_cmvn --ctc_weight=0.5 --output_onnx_dir=$onnx_model_dir --fp16

**Comment by 1215thebqtic** [comment]
The segmentation fault is solved by setting the session options intra_op_num_threads to 1 according to https://github.com/microsoft/onnxruntime/blob/main/docs/FAQ.md

And I have another question, since deploying tritonserver on our server is difficult, are there any repositories supporting onnx gpu batch inferencing without using triton? Thanks!

**Comment by Slyne** [comment]
If this is only offline asr model, you can refer to https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/recognize_onnx.py and replace the feature extractor with kaldifeat, which you can refer [here](https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/model_repo/feature_extractor/1/model.py) or [here](https://github.com/csukuangfj/kaldifeat).

**Comment by 1215thebqtic** [comment]
> If this is only offline asr model, you can refer to https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/recognize_onnx.py and replace the feature extractor with kaldifeat, which you can refer [here](https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/model_repo/feature_extractor/1/model.py) or [here](https://github.com/csukuangfj/kaldifeat).

Thanks!
