### ISSUE TITLE
pass config options through api

### ISSUE THREAD

**Issue by FredSRichardson** [wenet-e2e/wenet#1470]
I'm currently trying to find a way to change parameters like "acoustic_scale" or "length_penalty" when using the Python wenetruntime module but I don't see a way to do it.  Please let me know if there already is some way of doing this!

I think it would be great to be able to drop a config file in the model directory that sets parameters.  Maybe there is a way to do this with gflags?

I considered also adding more parameters to the Python decode object constructor which might be a better way but may also require more work.

Once the parameters have been tuned for a particular use case, then of course it would be great to pass those parameters to the runtime API.

**Comment by robin1001** [comment]
Currently, there is no such setting in wenet runtime. And it's in our plan to support a config file, which is the same as your proposal.

**Comment by Mddct** [comment]
> @Mddct , I think it's the time to add a config file. Do you have the bandwidth to do it?

I will take the time to implement an initial version during the recent National Day holiday

**Comment by xingchensong** [comment]
Ongoing, see https://github.com/wenet-e2e/wenet/issues/1697
