### ISSUE TITLE
use compute-wer.py is wrong

### ISSUE THREAD

**Issue by RyanGuo98** [wenet-e2e/wenet#1473]
hello,when i use compute-wer.py is wrong.
my label info is below(just one):
5f2b074881760 қазір болған аумаққа қаладағы коммуналдық қызмет толық жұмылдырылды
my recognize is below(just one):
5f2b074881760  қазірыры болған алмақа қаладағы ком мынанадық қыз толықжымныңын тұрылды
but when use  compute-wer.py to computer WER the info is below : (it can't output right label and use chara to compute WER)
utt: 5f2b074881760
WER: 30.00 % N=60 C=50 S=5 D=5 I=8
lab: Қ А З І Р          Б О Л Ғ А Н А У М А Қ Қ А Қ А Л А Д А Ғ Ы К О М М У Н А Л    Д Ы Қ Қ Ы З М Е Т Т О Л Ы Қ Ж Ұ  М    Ы Л Д Ы         Р Ы Л Д Ы 
rec: Қ А З І Р Ы Р Ы Б О Л Ғ А Н А Л М А Қ   А Қ А Л А Д А Ғ Ы К О М М Ы Н А Н А Д Ы Қ Қ Ы З       Т    О Л Ы Қ Ж Ы М Н Ы Ң     Ы Н Т Ұ Р Ы Л Д Ы 
the config of mine is below:
python tools/compute-wer.py --char=1 --v=1 \
          $wave_data/$test/text $test_dir/text > $test_dir/wer
can you guys give some advice

**Comment by xingchensong** [comment]
set --char=0

**Comment by RyanGuo98** [comment]
thaks a lot,my problem was solved
