### ISSUE TITLE
how to use  pretrained conformer encoders?

### ISSUE THREAD

**Issue by TinaChen95** [wenet-e2e/wenet#1474]
Thanks for public the ch-w2v-conformer model.

I'm currently trying to use this model to initial encoder by using "--enc_init" and "--enc_init_mods" following this script:
https://github.com/wenet-e2e/wenet/blob/main/examples/openasr2021/s0/run.sh

but I come across some model inconsistent problem very much similar to this issue:
https://github.com/wenet-e2e/wenet/issues/1354

RuntimeError: Error(s) in loading state_dict for ASRModel:
Unexpected key(s) in state_dict: "encoder.encoders.0.concat_linear.weight", "encoder.encoders.0.concat_linear.bias", "encoder.encoders.1.concat_linear.weight", "encoder.encoders.1.concat_linear.bias", "encoder.encoders.2.concat_linear.weight", "encoder.encoders.2.concat_linear.bias", "encoder.encoders.3.concat_linear.weight", "encoder.encoders.3.concat_linear.bias", "encoder.encoders.4.concat_linear.weight", "encoder.encoders.4.concat_linear.bias", "encoder.encoders.5.concat_linear.weight", "encoder.encoders.5.concat_linear.bias", "encoder.encoders.6.concat_linear.weight", "encoder.encoders.6.concat_linear.bias", "encoder.encoders.7.concat_linear.weight", "encoder.encoders.7.concat_linear.bias", "encoder.encoders.8.concat_linear.weight", "encoder.encoders.8.concat_linear.bias", "encoder.encoders.9.concat_linear.weight", "encoder.encoders.9.concat_linear.bias", "encoder.encoders.10.concat_linear.weight", "encoder.encoders.10.concat_linear.bias", "encoder.encoders.11.concat_linear.weight", "encoder.encoders.11.concat_linear.bias",...

Hyper-parameter mismatch maybe the reason. Could you kindly share the config file of training the ch-w2v-conformer model?

**Comment by xingchensong** [comment]
PLZ see https://github.com/wenet-e2e/wenet/issues/1465#issuecomment-1257929504

**Comment by TinaChen95** [comment]
I've changed this line https://github.com/wenet-e2e/wenet/blob/3383dfb6178fbe159b9b1b02e9741c77da7b33ff/wenet/utils/checkpoint.py#L104 

to this line https://github.com/wenet-e2e/wenet/blob/3383dfb6178fbe159b9b1b02e9741c77da7b33ff/wenet/utils/checkpoint.py#L33

and modified this script  a little bit :https://github.com/wenet-e2e/wenet/blob/3383dfb6178fbe159b9b1b02e9741c77da7b33ff/examples/aishell/s0/run.sh#L152

by using this config file https://github.com/wenet-e2e/wenet/blob/main/examples/openasr2021/s0/conf/train_conformer_large_10h.yaml

removing this line to not using global_cmvn https://github.com/wenet-e2e/wenet/blob/3383dfb6178fbe159b9b1b02e9741c77da7b33ff/examples/aishell/s0/run.sh#L152

also adding this two parameters  --enc_init --enc_init_mods

model can be successfully initialized, but got this WARNING:
   WARNING NaNor Inf found in input tensor

**Comment by xingchensong** [comment]
why remove global_cmvn?

**Comment by TinaChen95** [comment]
Cause I don't have this file.
The default feature is fbank and it's 80 dim.
But this config  using mfcc as feature, and it's 40 dim.
https://github.com/wenet-e2e/wenet/blob/main/examples/openasr2021/s0/conf/train_conformer_large_10h.yaml

**Comment by robin1001** [comment]
@Emiyassstar would you please follow the issue

**Comment by TinaChen95** [comment]
Thanks for reply.
I think my modifications here https://github.com/wenet-e2e/wenet/issues/1474#issuecomment-1265253266 is consistent with suggession 1 and 2.
I'm using aishell dataset, and all output is NAN.

Can I get more specific instructions? Thanks.

**Comment by coreeey** [comment]
Does discarding some parameter in state_dict  have no effect on the model?
