### ISSUE TITLE
Add "segment" file input option to decoder_main.cc

### ISSUE THREAD

**Issue by FredSRichardson** [wenet-e2e/wenet#1482]
**Is your feature request related to a problem? Please describe.**
This is only a problem if you are decoding data with a pre-defined segmentation and you don't want to write data to disk.

**Describe the solution you'd like**
Unfortunately I can't contribute code directly to WeNet, but I did hack this into my code.  Basically I modified the "decode()" function in decode_main.cc so that it takes a string and a vector.  I loaded the user specified Kaldi format segment file as a map from the waveform file basename to a vector of tuples of each utterance-label, start-time and end-time.  Then each waveform file is loaded into memory and the map is used to populate a vector of pairs of the utterance-label and a float vector of PCM data.  Sorry that sounds so complicated!

**Describe alternatives you've considered**
I think this could be implemented in a number of different ways.  The approach I took uses more memory than is necessary since it loads all the PCM data before decoding.  It might be better to decode a waveform file on a thread and have the "decode()" function walk through all the segments of a given waveform.

**Additional context**
This is useful for decoding some standard corpora which come with pre-defined segmentations (like the hub5e evaluation data)

**Comment by robin1001** [comment]
It is not in the plan of WeNet. `segments` takes time to understand, and we can get the same results by:
1) splits wavs by segments with your own code
2) recongize the segments one by one
3) splices the results.
Users are responsible for the 1st and 3rd stages.

**Comment by FredSRichardson** [comment]
@robin1001 - that is a reasonable position.  I actually found it very easy to deal with "segments" issue using the WeNet Python module.  I only switched to using the WeNet CLI version because I needed access to more configuration options for decoding (WFST decoding in particular).  I think when configuration options are exposed for the Python module this won't matter as much.

**Comment by robin1001** [comment]
Yes, segments is supported in python module. `configuration options` for `wenetruntime` are in our plan.

**Comment by robin1001** [comment]
@Mddct any progress about the configuration options in `wenetruntime`?

**Comment by xingchensong** [comment]
move this request to https://github.com/wenet-e2e/wenet/issues/1697, closed
