### ISSUE TITLE
[Runtime] runtime/server/x86. cmake error

### ISSUE THREAD

**Issue by dospeech** [wenet-e2e/wenet#1488]
[root@asr-gpu-08 x86]$ cmake -B build
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Populating libtorch
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/wenet/runtime/LibTorch/fc_base/libtorch-subbuild
[100%] Built target libtorch-populate
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Torch: /mnt/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch.so  
-- Populating gflags
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/wenet/runtime/LibTorch/fc_base/gflags-subbuild
[100%] Built target gflags-populate
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - not found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - not found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - not found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - not found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - not found
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - not found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - not found
-- Check size of uint32_t
-- Check size of uint32_t - failed
-- Check size of u_int32_t
-- Check size of u_int32_t - failed
CMake Error at fc_base/gflags-src/CMakeLists.txt:286 (message):
  Do not know how to define a 32-bit integer quantity on your system! Neither
  uint32_t, u_int32_t, nor __int32 seem to be available.  Set
  [GFLAGS_]INTTYPES_FORMAT to either C99, BSD, or VC7 and try again.

-- Configuring incomplete, errors occurred!
See also "/mnt/wenet/runtime/server/x86/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/wenet/runtime/server/x86/build/CMakeFiles/CMakeError.log".

What should I do?Thanks

**Comment by pengzhendong** [comment]
https://github.com/wenet-e2e/wenet/issues/1061

**Comment by dospeech** [comment]
> #1061

my system is centos，so i run commands as follows：
yum install git cmake && yum groupinstall 'Development Tools'

but the error is the same：

[100%] Built target gflags-populate
-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - not found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - not found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - not found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - not found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - not found
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - not found
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - not found
-- Check size of uint32_t
-- Check size of uint32_t - failed
-- Check size of u_int32_t
-- Check size of u_int32_t - failed
CMake Error at fc_base/gflags-src/CMakeLists.txt:286 (message):
  Do not know how to define a 32-bit integer quantity on your system! Neither
  uint32_t, u_int32_t, nor __int32 seem to be available.  Set
  [GFLAGS_]INTTYPES_FORMAT to either C99, BSD, or VC7 and try again.


-- Configuring incomplete, errors occurred!
See also "/mnt/wenet/runtime/libtorch/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/wenet/runtime/libtorch/build/CMakeFiles/CMakeError.log".

**Comment by dospeech** [comment]
> Delete the build folder. And try this command:
> 
> ```shell
> mkdir build && cd build
> cmake -DINTTYPES_FORMAT:STRING=C99 ..
> ```

Thanks ! The problem was solved
