### ISSUE TITLE
.build activate bug

### ISSUE THREAD

**Issue by 903859154** [wenet-e2e/wenet#1489]
I have change some code in aishell, and i export the model successfully. When i run in local build ,and then ,the bug show. 

**Expected behavior**

**Screenshots**
![b746722911f3a14281e28116265e834](https://user-images.githubusercontent.com/57293471/194846504-29ee039b-9cba-4c80-bfb6-d8cc62afee11.jpg)

**Comment by pengzhendong** [comment]
What did you changed?

**Comment by 903859154** [comment]
> What did you changed?

I copy attention.py and  rename it to self_atte.py . And then encoder.py call this self_atte,  decoder.py 's left call self_atte, right block call the old attention.py . And i add a math formula in function forward of self_atte . This is what i changed

**Comment by 903859154** [comment]
Somebody can help?

**Comment by pengzhendong** [comment]
Try the pretrained model wenet released.

**Comment by 903859154** [comment]
> Try the pretrained model wenet released.

It is normal when using pretrained model

**Comment by 903859154** [comment]
![image](https://user-images.githubusercontent.com/57293471/195552815-e2e59e7b-b76b-43a8-8932-d4063f7dec39.png)


> > Try the pretrained model wenet released.
> 
> It is normal when using pretrained model
