### ISSUE TITLE
How to recognize one only wav file but don't use runtime style? 

### ISSUE THREAD

**Issue by newuserforstudy** [wenet-e2e/wenet#1497]
I just want to recognize one wav file . I try to  use recognize_deprecated.py (now deleted) but it can't work (some params miss). And I don't want to use runtime style because I use my finetune checkpoint model in offline env .What should I do?  3ks!

**Comment by robin1001** [comment]
Please just follow the recipes of standard datasets. such as aishell/librispeech, and pay attention to the testing stage. Then you could figure out what are required and what's the format.

However, it is not recommended to test single wav file in recognize.py

**Comment by newuserforstudy** [comment]
> Please just follow the recipes of standard datasets. such as aishell/librispeech, and pay attention to the testing stage. Then you could figure out what are required and what's the format.
> 
> However, it is not recommended to test single wav file in recognize.py

Thanks for your reply。I am interesting in your wenet source code not the stages written by shell and  I have modified the recognize.py file to fulfill my tasks。3ks again!
