### ISSUE TITLE
TorchScript Error while decoding rnnt model

### ISSUE THREAD

**Issue by dipeshhoncho07** [wenet-e2e/wenet#1498]
Hi, I am getting the below error while decoding through rnnt model.
I1017 12:31:10.279107 16174 torch_asr_model.cc:36] Num intra-op threads: 1
I1017 12:31:10.279170 16174 torch_asr_model.cc:37] Num inter-op threads: 1
terminate called after throwing an instance of 'torch::jit::ErrorReport'
  what():  
Unknown builtin op: torchaudio::rnnt_loss.
Could not find any similar ops to torchaudio::rnnt_loss. This op may not exist or may not be currently supported in TorchScript.

Can someone suggest something on this?

**Comment by Mddct** [comment]
runtime don‘t support rnnt for noe
