### ISSUE TITLE
Getting error while building runtime: FSTSCRIPT ERROR

### ISSUE THREAD

**Issue by dipeshhoncho07** [wenet-e2e/wenet#1499]
Hi, getting the below error while doing cmake --build .

[ 20%] Linking CXX executable fstarcsort
/usr/bin/ld: cannot find -lfstscript
collect2: error: ld returned 1 exit status

I think due to some recent feature merge or fix, this bug got generated. Please help.

**Comment by csetanmayjain** [comment]
I'm also facing the same issue, and can't able find any solution yet :(

**Comment by robin1001** [comment]
Fixed, please see https://github.com/wenet-e2e/wenet/pull/1496.

**Comment by csetanmayjain** [comment]
hi, 
I'm also facing the same issue, and the above commit didn't work for me

**Comment by pengzhendong** [comment]
> hi, I'm also facing the same issue, and the above commit didn't work for me

Pull the latest code, delete `fc_base/openfst-*` and `build` folder, re-config with `-DGRAPH_TOOLS=ON`

**Comment by csetanmayjain** [comment]
I pull the latest code only, still have same issue :(

**Comment by pengzhendong** [comment]
> delete `fc_base/openfst-*` and `build` folder

Plz check this step.
