### ISSUE TITLE
在windows下cmake --build的时候报错

### ISSUE THREAD

**Issue by newbeeCSharp** [wenet-e2e/wenet#1505]
[log.txt](https://github.com/wenet-e2e/wenet/files/9817366/log.txt)
decoder.lib(torch_asr_model.obj) : error LNK2019: 无法解析的外部符号 "__declspec(dllimport) public: class std::vector<struct c10
::IValue,class std::allocator<struct c10::IValue> > & __cdecl c10::ivalue::Tuple::elements(void)& " (__imp_?elements@Tu
ple@ivalue@c10@@QEGAAAEAV?$vector@UIValue@c10@@V?$allocator@UIValue@c10@@@std@@@std@@XZ)，函数 "public: virtual void __cde
cl wenet::TorchAsrModel::AttentionRescoring(class std::vector<class std::vector<int,class std::allocator<int> >,class s
td::allocator<class std::vector<int,class std::allocator<int> > > > const &,float,class std::vector<float,class std::al
locator<float> > *)" (?AttentionRescoring@TorchAsrModel@wenet@@UEAAXAEBV?$vector@V?$vector@HV?$allocator@H@std@@@std@@V
?$allocator@V?$vector@HV?$allocator@H@std@@@std@@@2@@std@@MPEAV?$vector@MV?$allocator@M@std@@@4@@Z) 中引用了该符号 [E:\wangzw\
huizhou\wenet-e2e\wenet-main\runtime\libtorch\build\api\wenet_api.vcxproj]
E:\wangzw\huizhou\wenet-e2e\wenet-main\runtime\libtorch\build\api\Debug\wenet_api.dll : fatal error LNK1120: 2 个无法解 析的外部
命令 [E:\wangzw\huizhou\wenet-e2e\wenet-main\runtime\libtorch\build\api\wenet_api.vcxproj]

请问该如何解决

**Comment by pengzhendong** [comment]
没能复现问题，请参考这俩命令试试：https://github.com/wenet-e2e/wenet/blob/7e6bb0f8b06b594311fb4747a6c23a8ca345da72/.github/workflows/windows.yml#L20-L21
