### ISSUE TITLE
单机多卡训练出现卡死，不报错也没日志输出

### ISSUE THREAD

**Issue by zmqwer** [wenet-e2e/wenet#1507]
初步看来是卡在了dist.init_process_group之后，对于大的数据集有什么好的解决方法吗

**Comment by robin1001** [comment]
We have no idea.

**Comment by duj12** [comment]
> 初步看来是卡在了dist.init_process_group之后，对于大的数据集有什么好的解决方法吗

可能的原因有：
1.在你的机器上ddp的backend不支持nccl, 可以切换为gloo试一下。
2.不是初次启动任务，wenet现在接续训练需要手动删掉之前模型保存路径下的ddp_init文件，再重新接续训练。

不太可能是数据量的原因。
