### ISSUE TITLE
Temperature scaling for ctc activations

### ISSUE THREAD

**Issue by lubacien** [wenet-e2e/wenet#1508]
Hello,

It looks like temperature scaling is quite useful to calibrate overconfident networks http://proceedings.mlr.press/v70/guo17a.html . In the case of wenet this could be applied to the ctc activations and should, in my opinion, both improve the overall wenet performance by improving the ctc score, and also make the score more interpretable as a confidence measure. Do you think this would be a useful addition?

thanks

**Comment by robin1001** [comment]
Maybe it helps. You can do experiments to prove that.

**Comment by lubacien** [comment]
@robin1001

**Comment by xingchensong** [comment]
Thanks for your exp, I think we can just keep it as a reference.
