### ISSUE TITLE
wenetruntime python调用预测只能使用单线程吗？

### ISSUE THREAD

**Issue by kingmpw2015** [wenet-e2e/wenet#1510]
如题，请问wenetruntime python调用预测只能使用单线程吗？观察了一下cpu一直都是只占用一个核。4秒的音频推理耗时1s左右，这个耗时正常吗？
另外怎么离线预测怎么使用gpu？ 不走docker

**Comment by robin1001** [comment]
对，可以使用多进程预测。刚开始比较慢，后续会快一些。

使用 GPU 可以用 triton 或者 runtime/libtorch 编译 GPU 版。
