### ISSUE TITLE
你好，请问为什么加个语言模型，效果更差了呢？丢了很多字

### ISSUE THREAD

**Issue by hk0901** [wenet-e2e/wenet#1511]
有些字句相比不加语言模型会有丢字现象，请问有这种问题吗

**Comment by robin1001** [comment]
语言模型的引入天然就会增大 deletion，可以把 acoustic_scale 调大试试看看能不能缓解。

**Comment by wwfcnu** [comment]
@hk0901 你调之后有改善吗
