### ISSUE TITLE
save wav file something error

### ISSUE THREAD

**Issue by swpucl** [wenet-e2e/wenet#1512]
I used the "wav.h" to save audio file , but the saved wav file sound shrill noise

**Comment by swpucl** [comment]
int num_sample = waves.size();
int num_channel = 1;
int sample_rate = 16000;
int bits_per_sample = 32;

WavWriter wav_writer(waves.data(), num_sample, num_channel, sample_rate,bits_per_sample);

**Comment by robin1001** [comment]
bits_per_sample should be 16.
