### ISSUE TITLE
Conv2dSubsampling4mask 操作导致单句和batch执行结果不一致问题？

### ISSUE THREAD

**Issue by LitLeo** [wenet-e2e/wenet#1513]
**Describe the bug**
```
subsampling.py  class Conv2dSubsampling4
code: x_mask[:, :, :-2:2][:, :, :-2:2]
mask (#batch, 1, time') bool 类型。

翻译一下：
逻辑为F = ceil((x - 2) / 2), 
F(F(time))
```

这行代码会导致单句和batch执行后，输出mask不一致。原因是去除pad是从尾部去除的，而batch执行时，长度较短的后面是补False，无法从尾部去除pad。
假设两句话不等长，A 100帧和B 50帧。
单句分别执行时，输入：input_mask_A[1, 1, 100], input_mask_B[1, 1, 50]。输出：output_mask_A[1, 1, 24], output_mask_B[1, 1, 11]

batch执行是，将input_mask_A 和 input_mask_B 拼接在一起，input_mask_B 后面补False。
计算后拆开，output_mask_A 的结果是对的，output_mask_B的维度为[1, 1, 13]

**解决方案**
改成从前面去除pad，结果就能对齐了

**Comment by robin1001** [comment]
具体如何修改，有想法吗？

**Comment by LitLeo** [comment]
> 具体如何修改，有想法吗？

改成从前面去除 pad 应该就可以了。
```
x_mask[:, :, 2::2][:, :, 2::2]
```

**Comment by day9011** [comment]
> 具体如何修改，有想法吗？

哈哈，彬彬大佬，看看我当年提的issue，如果batch sort后一个batch里长度差不多的情况下影响不大，以前是全局sort所以感受不大，不过目前的pipeline是局部sort，有问题的概率变大了 #211

**Comment by Mddct** [comment]
batch推理的时候 降采样 pad的部分受影响了 训练的时候需要重新算下mask。

这也是为什么在一些短句上加零可以出东西的一部分原因了

**Comment by robin1001** [comment]
赞！

> > 具体如何修改，有想法吗？
> 
> 哈哈，彬彬大佬，看看我当年提的issue，如果batch sort后一个batch里长度差不多的情况下影响不大，以前是全局sort所以感受不大，不过目前的pipeline是局部sort，有问题的概率变大了 #221 我的解决方案是根据卷积公式计算长度后，重新生成mask

**Comment by robin1001** [comment]
> > 具体如何修改，有想法吗？
> 
> 改成从前面去除 pad 应该就可以了。
> 
> ```
> x_mask[:, :, 2::2][:, :, 2::2]
> ```

Great solution, could you help to do an experiment on aishell to evaluate the impact of the change?

**Comment by LitLeo** [comment]
> > > 具体如何修改，有想法吗？
> > 
> > 
> > 改成从前面去除 pad 应该就可以了。
> > ```
> > x_mask[:, :, 2::2][:, :, 2::2]
> > ```
> 
> Great solution, could you help to do an experiment on aishell to evaluate the impact of the change?

我主要是做推理的。在部分业务测试集上，这两种方式wer差距不大。

**Comment by robin1001** [comment]
okay

**Comment by day9011** [comment]
AISHELL数据集下测试：
采用mask：x_mask[:, :, 2::2][:, :, 2::2]
Feature info: using fbank feature, dither, cmvn, online speed perturb
Training info: lr 0.002, batch size 16, 8 gpu, acc_grad 4, 240 epochs, dither 0.1
Decoding info: ctc_weight 0.5, average_num 20
attention_rescoring: 4.56
attention: 4.82
ctc_greedy_search: 4.85
ctc_prefix_beam_search: 4.85

原来的mask：x_mask[:, :, :-2:2][:, :, :-2:2]
attention_rescoring: 4.59
attention: 4.87
ctc_greedy_search: 4.88

**Comment by xingchensong** [comment]
Will hold this PR for anyone else who has encountered and interested in the same question.
