### ISSUE TITLE
中英混合识别，英文部分识别丢失字母

### ISSUE THREAD

**Issue by ziyu123** [wenet-e2e/wenet#1514]
目前，我想训练一个中文asr，同时支持少许英文识别的场景，数据方面英文语料占总训练语料千分之一，建模单元用char建模(中文用汉字，英文用字母表)，现在遇到的情况是对于英文的音频，识别会缺少字母，  
比如: 
句子标注为：sometimes you just want to stand in the corner and stare out of the window
        识别为：some times you jus want to stan in the coner and star out of the inow  
用ctc_greedy_search解码，不涉及LM等，
我的理解应该是英文的训练语料比较少，训练不充分导致的，不过还没有验证，
请问，这种情况应该怎么解决呢？

**Comment by robin1001** [comment]
可以增加点英文数据再试试。
