### ISSUE TITLE
ONNX streaming decoding problem.

### ISSUE THREAD

**Issue by kobenaxie** [wenet-e2e/wenet#1516]
when `left_chunk=4, chunk_size=16`, will get `required_cache_size=left_chunk*chunk_size=64`，`key` and `value` will be padded with cache of length `required_cache_size=64`, so now `query`, `key`, `value` have lengths `16, 80, 80`, but `att_mask` here will only attention on current  chunk but not cache ?
https://github.com/wenet-e2e/wenet/blob/960728e07e06c8225c5c80c02554a405636dcfdb/wenet/bin/export_onnx_cpu.py#L112

@xingchensong @robin1001

**Comment by xingchensong** [comment]
Yes， and it is designed for the **first** chunk. For the subsequent chunks, att_mask will be updated: 
https://github.com/wenet-e2e/wenet/blob/960728e07e06c8225c5c80c02554a405636dcfdb/wenet/bin/export_onnx_cpu.py#L195-L196

**Comment by xingchensong** [comment]
The reason for feeding real mask & real cache (instead of fake mask & fake cache, i.e., mask with zeroed shapes):

https://github.com/wenet-e2e/wenet/blob/960728e07e06c8225c5c80c02554a405636dcfdb/wenet/bin/export_onnx_cpu.py#L83-L94

**Comment by xingchensong** [comment]
In other words: our code not only support dynamic shapes (i.e. libtorch) but also support systems that only take fixed-shape tensors as input (mcnn/mnn etc).

**Comment by xingchensong** [comment]
ALL-IN-ONE onnx exporter : )

**Comment by xingchensong** [comment]
and plz see : https://mp.weixin.qq.com/s/KYzprMACYmxzr3hCpF-zOQ

**Comment by kobenaxie** [comment]
ok, thanks~
