### ISSUE TITLE
I want to know how to freeze the decoder layer during fine-tuning stage. 

### ISSUE THREAD

**Issue by 1633347510** [wenet-e2e/wenet#1517]
hello! I want to fine-tune the pretrained model on self-defined dataset, but I didn't know how to freeze the decoder layers. I want to update the parameters of encoder layers. Is there a tutorial to refer to? I didn't know how to change  
 codes.

**Comment by robin1001** [comment]
I think it should be like
``` python
for param in decoder.parameters():
    param.requires_grad = False
```

**Comment by 1633347510** [comment]
> 
thank you very much for your kind reply!
