### ISSUE TITLE
How to handle long speech？

### ISSUE THREAD

**Issue by newuserforstudy** [wenet-e2e/wenet#1518]
When I test my fitun-tune wenet model on a 4min long wav file ,the following error occurred:
"""
   
    assert offset + x.size(1) < self.max_len
AssertionError
"""
then I find the max_length: 1200 (1200ms,20s) in train.yaml。Now I want to ask for your advice to how to process long speech or I just modify the parameter max_length bigger is ok，how about the performance？3ks!

**Comment by robin1001** [comment]
Just add `--continuous_decoding` in c++ binary or `continous_decoding=True` in `wenetruntime`.
