### ISSUE TITLE
forward_encoder_chunk cost too much time

### ISSUE THREAD

**Issue by jangjun21** [wenet-e2e/wenet#1520]
env:
gpu and Torch mode
websocket_client_main and websocket_server_main applications
all of  test files are less than 10s
somes the forward_encoder_chunk cost less than 1s ,but sometimes cost more than 6s.

I1026 17:30:34.817113  3262 websocket_client_main.cc:56] Send 8000 samples
I1026 17:30:34.857689  3264 websocket_client.cc:67] {"status":"ok","type":"partial_result","nbest":"[{\"sentence\":\"正在为您接通人工服务请稍后\"}]"}
I1026 17:30:35.317690  3262 websocket_client_main.cc:56] Send 8000 samples
I1026 17:30:35.359649  3264 websocket_client.cc:67] {"status":"ok","type":"partial_result","nbest":"[{\"sentence\":\"正在为您接通人工服务请稍后为保证服\"}]"}
I1026 17:30:35.818387  3262 websocket_client_main.cc:56] Send 8000 samples
I1026 17:30:36.318984  3262 websocket_client_main.cc:56] Send 8000 samples
I1026 17:30:36.368188  3264 websocket_client.cc:67] {"status":"ok","type":"partial_result","nbest":"[{\"sentence\":\"正在为您接通人工服务请稍后为保证服务质量\"}]"}
I1026 17:30:36.819519  3262 websocket_client_main.cc:56] Send 8000 samples
I1026 17:30:36.868976  3264 websocket_client.cc:67] {"status":"ok","type":"partial_result","nbest":"[{\"sentence\":\"正在为您接通人工服务请稍后为保证服务质量您的通话\"}]"}
I1026 17:30:37.320132  3262 websocket_client_main.cc:56] Send 8000 samples
I1026 17:30:37.368381  3264 websocket_client.cc:67] {"status":"ok","type":"partial_result","nbest":"[{\"sentence\":\"正在为您接通人工服务请稍后为保证服务质量您的通话可能会被\"}]"}
I1026 17:30:37.820641  3262 websocket_client_main.cc:56] Send 1280 samples
I1026 17:30:46.257741  3264 websocket_client.cc:67] {"status":"ok","type":"final_result","nbest":"[{\"sentence\":\"正在为您接通人工服务请稍后为保证服务质量您的通话可能会被录音\",\"word_pieces\":[{\"word\":\"正\",\"start\":140,\"end\":240},{\"word\":\"在\",\"start\":300,\"end\":400},{\"word\":\"为\",\"start\":460,\"end\":560},{\"word\":\"您\",\"start\":620,\"end\":720},{\"word\":\"接\",\"start\":780,\"end\":880},{\"word\":\"通\",\"start\":940,\"end\":1040},{\"word\":\"人\",\"start\":1180,\"end\":1280},{\"word\":\"工\",\"start\":1300,\"end\":1400},{\"word\":\"服\",\"start\":1460,\"end\":1560},{\"word\":\"务\",\"start\":1620,\"end\":1720},{\"word\":\"请\",\"start\":2180,\"end\":2280},{\"word\":\"稍\",\"start\":2460,\"end\":2560},{\"word\":\"后\",\"start\":2580,\"end\":2680},{\"word\":\"为\",\"start\":3100,\"end\":3200},{\"word\":\"保\",\"start\":3260,\"end\":3360},{\"word\":\"证\",\"start\":3420,\"end\":3520},{\"word\":\"服\",\"start\":3620,\"end\":3720},{\"word\":\"务\",\"start\":3740,\"end\":3840},{\"word\":\"质\",\"start\":3900,\"end\":4000},{\"word\":\"量\",\"start\":4060,\"end\":4160},{\"word\":\"您\",\"start\":4420,\"end\":4520},{\"word\":\"的\",\"start\":4540,\"end\":4640},{\"word\":\"通\",\"start\":4700,\"end\":4800},{\"word\":\"话\",\"start\":4900,\"end\":5000},{\"word\":\"可\",\"start\":5060,\"end\":5160},{\"word\":\"能\",\"start\":5180,\"end\":5280},{\"word\":\"会\",\"start\":5380,\"end\":5480},{\"word\":\"被\",\"start\":5500,\"end\":5600},{\"word\":\"录\",\"start\":5700,\"end\":5800},{\"word\":\"音\",\"start\":5820,\"end\":5920}]}]"}
I1026 17:30:46.257865  3264 websocket_client.cc:67] {"status":"ok","type":"speech_end"}
I1026 17:30:46.258005  3262 websocket_client_main.cc:63] Total latency: 7937ms.

**Comment by jangjun21** [comment]
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3899      C   ./websocket_server_main          2773MiB |
+-----------------------------------------------------------------------------+
Wed Oct 26 19:32:15 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:03:00.0 Off |                  N/A |
| 38%   44C    P8    44W / 350W |   2775MiB / 24268MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3899      C   ./websocket_server_main          2773MiB |
+-----------------------------------------------------------------------------+

**Comment by jangjun21** [comment]
the same as cpu mode

**Comment by xingchensong** [comment]
This is a warmup issue, see https://github.com/wenet-e2e/wenet/issues/1669
