### ISSUE TITLE
在windows环境如何使用wenet？

### ISSUE THREAD

**Issue by billqu01** [wenet-e2e/wenet#1523]
在windows环境如何使用wenet?
下面方法无法通过编译：
git clone git@github.com:wenet-e2e/wenet.git
cd wenet/runtime/binding/python
python setup.py install
编译报错如下：
Exception:
Build wenet failed. Please check the error message.
You can ask for help by creating an issue on GitHub.

**Comment by robin1001** [comment]
pip install wenentruntime, please see https://wenet.org.cn/wenet/python_binding.html.

**Comment by zhhl9101** [comment]
我按照这个步骤去操作，却没有任何输出
pip3 install wenetruntime

import sys
import torch
import wenetruntime as wenet

wav_file = sys.argv[1]
decoder = wenet.Decoder(lang='chs')
ans = decoder.decode_wav(wav_file)
print(ans)

也没有报错，也没有输出，好像什么都没发生，这是怎么回事呢？
