### ISSUE TITLE
can we make the k2 to be an optional rather than necessary

### ISSUE THREAD

**Issue by tongjinle123** [wenet-e2e/wenet#1530]
in the latest commit, the k2 is added for HLG decoding and it is forced to be imported in asr_model.py 

I think it is better to skip import if K2 not installed

And there aren't any install script for k2 in requirements or readme

by pip install k2, it will install torch 1.7 (K2 seems not fully compeleted, the doc and install script not well-built)

**Comment by csukuangfj** [comment]
> by pip install k2, it will install torch 1.7

It will install torch 1.12.1, which is clearly documented at https://k2-fsa.github.io/k2/installation/pip_pypi.html

---

> K2 seems not fully compeleted, the doc and install script not well-built

We have detailed installation documentation at
https://k2-fsa.github.io/k2/installation/pip_pypi.html

Would you mind pointing out which part is not clear? We can improve it. Thanks!

**Comment by tongjinle123** [comment]
> > by pip install k2, it will install torch 1.7
> 
> It will install torch 1.12.1, which is clearly documented at https://k2-fsa.github.io/k2/installation/pip_pypi.html
> 
> If you don't want this behavior. You can either install k2 using `conda` or compiling it from source.
> 
> > K2 seems not fully compeleted, the doc and install script not well-built
> 
> We have detailed installation documentation at https://k2-fsa.github.io/k2/installation/pip_pypi.html
> 
> Would you mind pointing out which part is not clear? We can improve it. Thanks!

K2 is not my point, I just took a look on this page https://github.com/k2-fsa/k2 and didn't find an install guide, so I tried pip install k2 and it installed a torch 1.7 (may be because I am using py 3.6?)

**Comment by tongjinle123** [comment]
my bad: 
```
except ImportError:
    print('Failed to import k2 and icefall. \
        Notice that they are necessary for hlg_onebest and hlg_rescore')
```
I misread this as 
```
except:
     raise ImportError
```
this line will not break the process, just a warning message. this issue should be closed.
