### ISSUE TITLE
websocket server latency

### ISSUE THREAD

**Issue by jangjun21** [wenet-e2e/wenet#1535]
I use 20210618_u2pp_conformer_libtorch pre model to test.
Using the same file to test third times,usually,the first  time and the third  time cost 1s,but the second time cost 6s,
why the second time is very slower than the first time?

**Comment by robin1001** [comment]
Please do more test to see if it is a special case.

**Comment by jangjun21** [comment]
I do more test ,it is not a special case .Using the difference files to test by turn, the issue look the same.
[t.log](https://github.com/wenet-e2e/wenet/files/9934390/t.log)
i attach the log file

**Comment by xingchensong** [comment]
It is a warmup issue, see https://github.com/wenet-e2e/wenet/issues/1669
