### ISSUE TITLE
How to augment noise into wavefiles in training?

### ISSUE THREAD

**Issue by Tirushamandava** [wenet-e2e/wenet#1543]
I want to augment music noise to my data. Can you please tell me what I should do?
Thanks in advance.

**Comment by pengzhendong** [comment]
1. write a function to augment the noise to your data, such as: https://github.com/wenet-e2e/wenet/blob/1d9b0bf066aae3170c8c084ead6260f1f76b4fe5/wenet/dataset/processor.py#L153-L199
2. call the function you wrote in this function: https://github.com/wenet-e2e/wenet/blob/1d9b0bf066aae3170c8c084ead6260f1f76b4fe5/wenet/dataset/dataset.py#L119

**Comment by robin1001** [comment]
You can refer https://github.com/wenet-e2e/wespeaker/blob/master/wespeaker/dataset/processor.py#L322.

**Comment by Tirushamandava** [comment]
> You can refer https://github.com/wenet-e2e/wespeaker/blob/master/wespeaker/dataset/processor.py#L322.

Thanks for your reply. Can you please tell me what I should pass in the reverb source? reverb audio files path?
def add_reverb_noise(data,
                     reverb_source,
                     noise_source,
                     resample_rate=16000,
                     aug_prob=0.6):

**Comment by Tirushamandava** [comment]
> 1. write a function to augment the noise to your data, such as: https://github.com/wenet-e2e/wenet/blob/1d9b0bf066aae3170c8c084ead6260f1f76b4fe5/wenet/dataset/processor.py#L153-L199
> 2. call the function you wrote in this function: https://github.com/wenet-e2e/wenet/blob/1d9b0bf066aae3170c8c084ead6260f1f76b4fe5/wenet/dataset/dataset.py#L119

Thanks for reply

**Comment by pengzhendong** [comment]
> > You can refer https://github.com/wenet-e2e/wespeaker/blob/master/wespeaker/dataset/processor.py#L322.
> 
> Thanks for your reply. Can you please tell me what I should pass in the reverb source? reverb audio files path? def add_reverb_noise(data, reverb_source, noise_source, resample_rate=16000, aug_prob=0.6):

Plz refer https://github.com/wenet-e2e/wespeaker/blob/296449adb6f3083d5eba2b1b115af4d08f24232b/wespeaker/dataset/lmdb_data.py#L34

**Comment by xingchensong** [comment]
Will hold this PR for anyone else who has encountered and is interested in the same question.
