### ISSUE TITLE
Getting empty results after adding TLG.fst to android demo

### ISSUE THREAD

**Issue by anjul1008** [wenet-e2e/wenet#1545]
Hi,
i have made some changes in wenet.cc to facilitate TLG.fst, some code snippets are below:
```
  auto fst = std::shared_ptr<fst::Fst<fst::StdArc>>(
          fst::Fst<fst::StdArc>::Read(tlgPath));
  CHECK(fst != nullptr);
  resource->fst = fst;
  LOG(INFO) << "TLG path: " << tlgPath;
  ```

App is working as expected with LM.
But after adding TLG.fst I'm not getting anything as output.
blank_score was high for all frames. (checked from ctc_wfst_beam_search.cc line 81)

Please let me know, if i haven't integrated LM in the wrong way or if we have some other to use LM.
Thanks in advance.

**Comment by pengzhendong** [comment]
How did you check `ctc_wfst_beam_search.cc line 81`?

**Comment by anjul1008** [comment]
By logging it's value of it.
Anyway, it seems working now. I should have changed the symbol table to words.txt.

But results are very poor, the results are below:
Attention: 14.35% WER
LM + attention: 42.02% WER

Any help would be appreciated.
Thanks in advance.

**Comment by pengzhendong** [comment]
Did you use `decoder_main` to get those results? Plz provide more information.

**Comment by anjul1008** [comment]
yes, these results are from decoder_main with TLG.

I have trained two LMs:
1. spm encoded ngram model, where I have encoded the entire text corpus to encode tokens and train LM and lexicons have only units from spm(TOKEN - TOKEN). with fst + attention rescoring I got 42.02% WER.
 2. Word LM, where i have trained trigram model and lexicons are `WORD - spm encoded tokens. with fst + attention rescoring I got 28.84% WER.
 
 Word lm has better accuracy than token LM but worse then without LM.

**Comment by anjul1008** [comment]
Hi @pengzhendong, any suggestions?

**Comment by pengzhendong** [comment]
Could you provide more information about the wer and some decode results?

**Comment by anjul1008** [comment]
sure.
```
Attention rescoring results: (WER 14.35%)
uttr1 how much is ten multiplied by two
utt2 who is narendra modi
uttr3 who is narendra modi
uttr4 good morning
uttr5 add four plus five add four plus five

TLG + attention: (WER 28.84%)
uttr1 how much
uttr2 what is narendra modi
uttr3 who is narendra modi
utt4
uttr5 add four five five
```
I have tested it on a laptop, not on the android app.
I'm getting most of the time empty results on the android app.

**Comment by pengzhendong** [comment]
Larger deletion error. Try to turn up the `acoustic_scale`: https://github.com/wenet-e2e/wenet/blob/1d9b0bf066aae3170c8c084ead6260f1f76b4fe5/runtime/core/decoder/params.h#L71

**Comment by anjul1008** [comment]
i have used `--acoustic_scale 1.2`. 
Should i try higher values and can be these values?

**Comment by xingchensong** [comment]
> i have used `--acoustic_scale 1.2`. Should i try higher values and what can be these values?

yes, please try higher acoustic_scale
