### ISSUE TITLE
The WebSocket handshake Connection field is missing the upgrade token

### ISSUE THREAD

**Issue by wsywsywsywsywsy979** [wenet-e2e/wenet#1548]
**Describe the bug**
testing  demo :  I can't visit web after I start demo docker. 
 
**To Reproduce**
just according to the demo guidance .

**Expected behavior**
I want to know what's wrong and how to correctly make demo run in my environment.(windows10+wsl2)

**Screenshots**
![image](https://user-images.githubusercontent.com/75532068/200510022-a11d3a0a-f0d9-451c-b938-cc2ed34d9a21.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows10 
 - Browser [e.g. chrome, safari]  edge

**Comment by pengzhendong** [comment]
Could you use `websocket_client_main` to test it?

**Comment by wsywsywsywsywsy979** [comment]
> 

could you tell me the concrete steps? I'm not familar with "websocke_client_main", and I try to search how to do but I'm not find the method.

**Comment by XiaoPenPen** [comment]
I1119 15:22:35.533484    30 websocket_server.cc:234] The WebSocket handshake Connection field is missing the upgrade token

我也遇到了此问题， centos7.6

**Comment by xingchensong** [comment]
please try local build
