### ISSUE TITLE
模型首字符识别效果差的问题

### ISSUE THREAD

**Issue by wenyaweiwie** [wenet-e2e/wenet#1551]
在对模型部署后，使用pyaudio实时的传入语音，但是模型对传入的语音首字符识别效果较差，容易对传入的首字或前几位的字符识别不出，请问一下作者这个问题的原因和提供一些解决思路。

**Comment by robin1001** [comment]
先检查一下是不是信号传入的部分有问题，刚开始少传了一部分。

**Comment by wenyaweiwie** [comment]
> 先检查一下是不是信号传入的部分有问题，刚开始少传了一部分。

thanks，请问对于针对训练自己数据集的语音数据，但是持续性输入语音的情况下，中途的一些废话或者杂音也会输出结果，请问对于这种情况，有什么好的想法可以得到改善吗？

**Comment by xingchensong** [comment]
可以做一下文字过滤，加一个后处理模块把‘’啊‘’什么的去掉，参考 https://github.com/wenet-e2e/WeTextProcessing/tree/master/itn
