### ISSUE TITLE
Seems that path.sh doesn't contain bin under `libtorch/fc_base/openfst-build`

### ISSUE THREAD

**Issue by Randool** [wenet-e2e/wenet#1553]
**Cannot find binary files like `fstcompile` after calling `. ./path.sh`**

I want to build the WFST in stage 7 in aishell/s0 script by calling `./run.sh --stage 7 --stop-stage 7` (previous steps have been completed). But the command reported an error:
```bash
tools/fst/compile_lexicon_token_fst.sh:行59: fstcompile：未找到命令
tools/fst/compile_lexicon_token_fst.sh:行60: fstarcsort：未找到命令
```

However I have followed the `Installation(Training and Developing)` to build required binary files about fst.

It's seems that the `path.sh` only contains:
```bash
export OPENFST_PREFIX_DIR=${BUILD_DIR}/../fc_base/openfst-subbuild/openfst-populate-prefix
```

**To Reproduce**
0. Follow the `Installation(Training and Developing)` to build required binary files.
1. Go to 'wenet/examples/aishell/s0'.
2. Call `. ./path.sh`.
3. Type `fstcompile`.

**Expected behavior**
`fstcompile` cannot be found.

**Solution**
Edit the path.sh to be:
```bash
export WENET_DIR=$PWD/../../..
export BUILD_DIR=${WENET_DIR}/runtime/libtorch/build
export OPENFST_PREFIX_DIR=${BUILD_DIR}/../fc_base/openfst-subbuild/openfst-populate-prefix
export OPENFST_BIN=${BUILD_DIR}/../fc_base/openfst-build/src
export PATH=$PWD:${BUILD_DIR}/bin:${BUILD_DIR}/kaldi:${OPENFST_PREFIX_DIR}/bin:${OPENFST_BIN}/bin:$PATH

# NOTE(kan-bayashi): Use UTF-8 in Python to avoid UnicodeDecodeError when LC_ALL=C
export PYTHONIOENCODING=UTF-8
export PYTHONPATH=../../../:$PYTHONPATH
```

**Comment by Innocence-0712** [comment]
Maybe, you need modify the cmake param. I follwed the ReadME of this repo to make the runtime, the fstcompile also doesn's exists.

**Comment by Randool** [comment]
> Build the runtime with `-DGRAPH_TOOLS=ON` before you use it.

I have finish the following the commands, while the problem remain.

```bash
# runtime build requires cmake 3.14 or above
cd runtime/libtorch
mkdir build && cd build && cmake -DGRAPH_TOOLS=ON .. && cmake --build .
```

So I manually add `${BUILD_DIR}/../fc_base/openfst-build/src` to the PATH.
