### ISSUE TITLE
wenetruntime python调用GPU 怎么可以用 triton 或者 runtime/libtorch 编译 GPU 版

### ISSUE THREAD

**Issue by tuocheng0824** [wenet-e2e/wenet#1555]
如题，wenetruntime python 版本代码有GPU版本的吗，用 triton 或者 runtime/libtorch 编译 GPU 版有相关链接吗？

**Comment by robin1001** [comment]
可以自己编译，官方提供的 pip 包仅支持 CPU。libtorch runtime GPU 编译打开 GPU 选项即可 https://github.com/wenet-e2e/wenet/blob/main/runtime/libtorch/CMakeLists.txt#L15
