### ISSUE TITLE
Docker deployment problem

### ISSUE THREAD

**Issue by tuocheng0824** [wenet-e2e/wenet#1557]
hello,I have a problem when I perform the following step
docker build . -f Dockerfile/Dockerfile.server -t wenet_server:latest --network host
---------------------------------------------------------------------------------------------------------------
Step 6/11 : RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113
 ---> Running in 4e6729b116b7
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113
Collecting torch
  Downloading torch-1.13.0-cp38-cp38-manylinux1_x86_64.whl (890.2 MB)

It can't be downloaded all the time. I can't find the corresponding location，or what needs to be done？

**Comment by tuocheng0824** [comment]
NO，centos 7

**Comment by XiaoPenPen** [comment]
此问题+1  使用docker执行docker run --rm -it -p 10086:10086 -v $model_dir:/home/wenet/model wenetorg/wenet-mini:latest bash /home/run.sh时 会卡住 没法正常下载

**Comment by duj12** [comment]
> ## hello,I have a problem when I perform the following step
> docker build . -f Dockerfile/Dockerfile.server -t wenet_server:latest --network host
> Step 6/11 : RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 ---> Running in 4e6729b116b7 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113 Collecting torch Downloading torch-1.13.0-cp38-cp38-manylinux1_x86_64.whl (890.2 MB)
> 
> It can't be downloaded all the time. I can't find the corresponding location，or what needs to be done？

You can modify the dockerfile, using other pip sources can fix this problem. 
Such as
```
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple torch==1.11.0+cu113 \
    torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
```
Here I use the specific version of torch. You can add `-i https://pypi.tuna.tsinghua.edu.cn/simple` only.

**Comment by xingchensong** [comment]
> > ## hello,I have a problem when I perform the following step
> > docker build . -f Dockerfile/Dockerfile.server -t wenet_server:latest --network host
> > Step 6/11 : RUN pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 ---> Running in 4e6729b116b7 Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113 Collecting torch Downloading torch-1.13.0-cp38-cp38-manylinux1_x86_64.whl (890.2 MB)
> > It can't be downloaded all the time. I can't find the corresponding location，or what needs to be done？
> 
> You can modify the dockerfile, using other pip sources can fix this problem. Such as
> 
> ```
> RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple torch==1.11.0+cu113 \
>     torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113
> ```
> 
> Here I use the specific version of torch. You can add `-i https://pypi.tuna.tsinghua.edu.cn/simple` only.

Thx for your reply, I will keep this issue open for anyone else who also encountered this problem
