### ISSUE TITLE
how to modify Dockerfile to deploy Runtime/GPU on Jeston NX?

### ISSUE THREAD

**Issue by wienerjier** [wenet-e2e/wenet#1558]
since it download x86_64 version of the cuda in Dockerfile.server and Dockerfile.client , it may cause cannot find GPU error in Jeston NX

**Comment by yuekaizhang** [comment]
https://github.com/triton-inference-server/server/blob/main/docs/user_guide/jetson.md You could install triton from a tar file on jetson.
