### ISSUE TITLE
The return of ctc_prefix_beam_search is ill-structured?

### ISSUE THREAD

**Issue by naxingyu** [wenet-e2e/wenet#1560]
This [line](https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/asr_model.py#L449) is supposed to return a list of integers representing the top hyp of one utterance
```
) -> List[int]:
...
return hyps[0]
```
However, each entry of hyps is a tuple in the format of (hyp, score). So should this line be
```
return hyps[0][0]
```
?

**Comment by robin1001** [comment]
score is denoted with `_` in line
https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/asr_model.py#L445

**Comment by naxingyu** [comment]
@robin1001 L445 takes the two outputs from here https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/asr_model.py#L417
I was referring to the score in the tuple constructed in this line https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/asr_model.py#L416
where score was calculated using
```
log_add([y[1][0], y[1][1]])
```

**Comment by robin1001** [comment]
I see,  it should be. Could you help to fix it? I think we can just drop the score, since it is never used.

**Comment by naxingyu** [comment]
@robin1001 `hyps` in [L445](https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/asr_model.py#L445) is a `List(Tuple(Tuple, Tensor))` so `hyps[0]` is `Tuple(Tuple, Tensor)`. Thus to return List[int]
```
return list(hyps[0][0])
```

**Comment by robin1001** [comment]
Good catch! Type annotations of some decoding method are also wrong. we will fix it.

**Comment by xingchensong** [comment]
We should also modify [recognize.py::L346-L351](https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/recognize.py#L346-L351) if we return `list(int)`

before (return `tuple(tuple(), tensor)`):
```py
            for i, key in enumerate(keys):
                content = []
                for w in hyps[i]:
                    if w == eos:
                        break
                    content.append(char_dict[w])
```

after (return `List(int)`):
```py
            for i, key in enumerate(keys):
                content = []
                for w in hyps:
                    if w == eos:
                        break
                    content.append(char_dict[w])
```

**Comment by naxingyu** [comment]
@xingchensong IMO, that seems unnecessary. The logic in `bin/recognize.py` was written with assumption that `hyps[i]` is `List(int)` (I is always 0 since `hyps = [hyp]` for ctc_prefix_beam_search). So  there is runtime error of type `KeyError` if decoding mode is `ctc_prefix_beam_search` which can be resolved after this fix.

**Comment by naxingyu** [comment]
The reason for opening this issue is that I saw this `KeyError` in [L351](https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/recognize.py#L351). E.g.
```
KeyError: (1, 2, 3, 4)
```
meaning `w` is tuple. So I think the problem I presented was the root cause, fyi.

**Comment by robin1001** [comment]
The code is very ugly after we expand so many decoding ways. We will refactor it in the future.
