### ISSUE TITLE
Fail to load quantized onnx model

### ISSUE THREAD

**Issue by PPGGG** [wenet-e2e/wenet#1564]
When i tried to load quantized onnx model, it came out the following error:

`error when load onnx model: Load model from /onnx/encoder.quant.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:47 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 3 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain ai.onnx.ml is till opset 2.`

**Comment by xingchensong** [comment]
Whats the version of onnx / torch / onnxruntime

**Comment by PPGGG** [comment]
@xingchensong  

torch version: 1.11.0
onnx version: 1.11.0
onnxruntime version: 1.11.0

**Comment by xingchensong** [comment]
https://github.com/microsoft/onnxruntime/issues/11898#issuecomment-1160765270 maybe u can try downgrade onnx to 1.10.0
