### ISSUE TITLE
基于SqueezeFormer的训练模型、进行ONNX转换时，遭遇MatMul_2995问题

### ISSUE THREAD

**Issue by lvchigo** [wenet-e2e/wenet#1569]
# 一、问题描述
- 基于SqueezeFormer的训练模型ONNX转换时，遭遇MatMul_2995问题：“2022-11-21 14:51:01.052900711 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running MatMul node. Name:'MatMul_2995' Status Message: matmul_helper.h:59 Compute MatMul dimension mismatch”、具体请查看下图、详细错误可查看[log.txt](https://github.com/wenet-e2e/wenet/files/10054492/log.txt)：  
![image](https://user-images.githubusercontent.com/8186051/202988962-8a8420ff-6209-449b-9d0d-2bea4bcda733.png)  
- 此时，已生成encoder.onnx与encoder.quant.onnx：  
![image](https://user-images.githubusercontent.com/8186051/202989468-557f6ba1-bb82-457f-9496-c1aef65a7749.png)  
- 基于相同环境，已成功将相同SqueezeFormer训练模型转换为libtorch cpu model、并推理验证成功：  
![image](https://user-images.githubusercontent.com/8186051/202995989-05925e62-2c40-46bd-8cc9-db688f98bda4.png)  
- 基于相同环境，已成功将aishell2的Conformer Checkpoint Model 转换为ONNX model：  
![image](https://user-images.githubusercontent.com/8186051/202990429-491c6f25-88ba-4611-823f-74db70e911a7.png)  

# 二、执行命令
- 如需SqueezeFormer的训练模型：请联系176032216@qq.com
- 参考wenet/runtime/onnxruntime/README.md：
“
exp=exp  # Change it to your experiment dir
onnx_dir=onnx
python -m wenet.bin.export_onnx_cpu \
  --config $exp/train.yaml \
  --checkpoint $exp/final.pt \
  --chunk_size 16 \
  --output_dir $onnx_dir \
  --num_decoding_left_chunks -1
“

# 三、安装环境
- wenet版本：20221116拉取的主分支
- 系统 centos7
- python 3.8.13
- gcc 10.3.0
- torch 1.10.0+cu113
- torchaudio 0.10.0+cu113
- torchvision 0.11.0+cu113
- onnx 1.12.0
- onnxconverter-common 1.13.0
- onnxmltools 1.11.1
- onnxruntime 1.13.1
- skl2onnx 1.13

**Comment by robin1001** [comment]
@yygle, 跟进一下这个问题

**Comment by yygle** [comment]
我这边近期会排查一下问题，兼容onnx

**Comment by yygle** [comment]
https://github.com/wenet-e2e/wenet/pull/1593

torch.repeat_interleave算子不兼容，换了种写法
