### ISSUE TITLE
Effect of audio compression format on ASR model 

### ISSUE THREAD

**Issue by ziyu123** [wenet-e2e/wenet#1570]
I train the model with 16k 16bit wave audio, then i test it with 24k bits/s mp3,  the file size Compression approx 10:1,  
But the cer decrease 2% absolute,  Now, Do i need to convert wav to mp3 and then convert to wav back and train the model?

**Comment by xingchensong** [comment]
测试时24k降到了16k吗

**Comment by ziyu123** [comment]
> 测试时24k降到了16k吗

训练是256 bits/s 的wave， 测试是24k bits/s的mp3，2%的绝对值是在测试集由噪音背景音乐的情况下，干净语音测试要小于这个值，我已经转码训练了，谢谢🙏
