### ISSUE TITLE
libtorch 编译完后预测问题

### ISSUE THREAD

**Issue by deepsmallsea033** [wenet-e2e/wenet#1575]
您好：
      我这边download code 后本地编译通过，websocker_server_main 启动后，通过websocker_client_main 交互，
websocker_server_main 会卡住，
<img width="1037" alt="截屏2022-11-23 上午11 54 27" src="https://user-images.githubusercontent.com/23547939/203466664-0604ce62-6b10-424e-9386-f3cb51f163a1.png">

websocker_client_main 端
<img width="529" alt="截屏2022-11-23 上午11 54 45" src="https://user-images.githubusercontent.com/23547939/203466709-0d237998-1eea-472a-a9f3-6c2db94a03e5.png">
能帮忙看一下是什么问题吗

**Comment by robin1001** [comment]
检查一下 websocket_server_main 启动时 --chunk_size 设置的多少。

**Comment by deepsmallsea033** [comment]
<img width="529" alt="截屏2022-11-23 上午11 54 45" src="https://user-images.githubusercontent.com/23547939/203697337-06cb5f5b-76f0-4563-be04-c98cb67a7df0.png">

**Comment by deepsmallsea033** [comment]
<img width="1364" alt="截屏2022-11-24 下午12 54 11" src="https://user-images.githubusercontent.com/23547939/203697407-33890267-3416-43ea-bf7e-34252afbf1f0.png">

**Comment by deepsmallsea033** [comment]
![image](https://user-images.githubusercontent.com/23547939/203724120-19d00986-ac9b-44bc-ba71-e523a804f8bb.png)

**Comment by xingchensong** [comment]
用最新代码重新导出zip模型。
