### ISSUE TITLE
iOS runtime problem

### ISSUE THREAD

**Issue by AlexanderXuan** [wenet-e2e/wenet#1579]
I try to build ios runtime, and i built is successfully as readme. I also built the ios app in Xcode successfully. But when I run the app in iphone device, there is a problem in model init. Here is screen shot:
<img width="995" alt="image" src="https://user-images.githubusercontent.com/44723003/203561393-2d6c37d4-e791-4486-856d-bf47a92ad3d3.png">
I run it step by step, it is break in this line:
<img width="985" alt="image" src="https://user-images.githubusercontent.com/44723003/203561933-44effb9b-85d0-459e-b953-2360e9bc324b.png">

When in run `pod install`, there are some prompt:
<img width="918" alt="image" src="https://user-images.githubusercontent.com/44723003/203563593-b8e4b6e4-838f-4872-ae82-69e49e15fde5.png">
I add the workspace in PodFile, last line is still printed.

My macos is 13.0.1, Xcode version is 14.1, ios version is 16.1. I tried multi_cn, aishell, librispeech model, same error happened.

I'm not familiar with ios app, is there any suggestion?

**Comment by robin1001** [comment]
@Ma-Dan please follow the issue

**Comment by Ma-Dan** [comment]
Could you please show me how the model files are located under the WenetDemo/model folder?

**Comment by AlexanderXuan** [comment]
> Could you please show me how the model files are located under the WenetDemo/model folder?
this is path where i put final.zip and units.txt:
`wenet/runtime/ios/WenetDemo/WenetDemo/model`
And this is path in app runing processing:
<img width="983" alt="image" src="https://user-images.githubusercontent.com/44723003/203781652-422dcad0-0825-477d-b4fc-fac4389371b2.png">

**Comment by Ma-Dan** [comment]
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/38337958/203791009-efaddcf9-a765-4afd-9012-54284d9609f1.png">
Looks like your model file location is all right, I tried with 20210815_unified_conformer_libtorch and 20220506_u2pp_conformer_libtorch, both work fine on my device.
This might be related with ios version, but I only have a 14.7 iPad.
Can you provide links which you download your model files from? I will try the same files on my device first.

**Comment by Ma-Dan** [comment]
<img width="335" alt="image" src="https://user-images.githubusercontent.com/38337958/203804908-59951781-d125-4353-9534-6c12ecbdbc55.png">


<img width="324" alt="image" src="https://user-images.githubusercontent.com/38337958/203804980-363d0870-649d-40ec-9fcf-3d235c95681e.png">


I downloaded pretrained file from the same link again, and files are different from previous downloaded files, and I met the same error. The model files were updated on Oct. 26.

Please try old model files I uploaded, and I will work on the new model files.

https://dan-1256867781.cos.ap-shanghai.myqcloud.com/20210815_unified_conformer_libtorch.tar.gz

https://dan-1256867781.cos.ap-shanghai.myqcloud.com/20220506_u2pp_conformer_libtorch.tar.gz

**Comment by AlexanderXuan** [comment]
wow, many thanks! I tried this model in iphone and ipad, all wroks well. Thanks for you great job!!!

**Comment by Ma-Dan** [comment]
To use newer model files, please modify this line https://github.com/wenet-e2e/wenet/blob/main/runtime/ios/build/Podfile#L2 to Use LibTorch 1.11.0 (I tried LibTorch 1.13.1 will have link errors).

```
platform :ios, '14.3'
pod 'LibTorch', '~>1.11.0'
```


I will submit a PR to fix this later!
