### ISSUE TITLE
Failed to process the request(s) for model instance 'feature_extractor_0_0', message: Stub process is not healthy

### ISSUE THREAD

**Issue by cocoakeith** [wenet-e2e/wenet#1581]
### Description
I am trying to deploy wenet online model on GPUS and follow the guide [https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/README.md](https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/README.md)，and do not make any changes.

However, when I start server and run the python client with the cmd "python3 client.py --audio_file=/ws/test_data/test1.wav --streaming --model_name=streaming_wenet", I get the error message as below:
```
Traceback (most recent call last):
  File "client.py", line 164, in <module>
    single_job((idx, cur_files))
  File "client.py", line 149, in single_job
    result = speech_client.recognize(li, idx)
  File "/ws/client/speech_client.py", line 126, in recognize
    response = self.triton_client.infer(
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 1431, in infer
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] in ensemble 'streaming_wenet', Failed to process the request(s) for model instance 'feature_extractor_0_0', message: Stub process is not healthy.
```
### Triton server log
Here is the triton server log. 
[triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)

### Hardware
![image](https://user-images.githubusercontent.com/12630218/203748179-d5576835-a037-4f38-bb37-26f909115a40.png)

### Note
I have tried to print the feature extraction results and found that is can be successfully output, as below:

![image](https://user-images.githubusercontent.com/12630218/203747296-6f5b6f29-40b8-4b54-80b0-7eba70de6085.png)

### Looking forward to your reply, thanks.

**Comment by robin1001** [comment]
@yuekaizhang please follow the issue.

**Comment by yuekaizhang** [comment]
> ### Description
> I am trying to deploy wenet online model on GPUS and follow the guide https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/README.md，and do not make any changes.
> 
> However, when I start server and run the python client with the cmd "python3 client.py --audio_file=/ws/test_data/test1.wav --streaming --model_name=streaming_wenet", I get the error message as below:
> 
> ```
> Traceback (most recent call last):
>   File "client.py", line 164, in <module>
>     single_job((idx, cur_files))
>   File "client.py", line 149, in single_job
>     result = speech_client.recognize(li, idx)
>   File "/ws/client/speech_client.py", line 126, in recognize
>     response = self.triton_client.infer(
>   File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 1431, in infer
>     raise_error_grpc(rpc_error)
>   File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
>     raise get_error_grpc(rpc_error) from None
> tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] in ensemble 'streaming_wenet', Failed to process the request(s) for model instance 'feature_extractor_0_0', message: Stub process is not healthy.
> ```
> 
> ### Triton server log
> Here is the triton server log. [triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)
> 
> ### Hardware
> ![image](https://user-images.githubusercontent.com/12630218/203748179-d5576835-a037-4f38-bb37-26f909115a40.png)
> 
> ### Note
> I have tried to print the feature extraction results and found that is can be successfully output, as below:
> 
> ![image](https://user-images.githubusercontent.com/12630218/203747296-6f5b6f29-40b8-4b54-80b0-7eba70de6085.png)
> 
> ### Looking forward to your reply, thanks.

Hi, would you mind attaching your "tree model_repo_stateful/*" info here? Also, it seems that you're using vgpu. Could you first try to test it with normal GPU? I am not sure if this issue related to vGPU.

**Comment by cocoakeith** [comment]
> > ### Description
> > I am trying to deploy wenet online model on GPUS and follow the guide [https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/README.md，and](https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/README.md%EF%BC%8Cand) do not make any changes.
> > However, when I start server and run the python client with the cmd "python3 client.py --audio_file=/ws/test_data/test1.wav --streaming --model_name=streaming_wenet", I get the error message as below:
> > ```
> > Traceback (most recent call last):
> >   File "client.py", line 164, in <module>
> >     single_job((idx, cur_files))
> >   File "client.py", line 149, in single_job
> >     result = speech_client.recognize(li, idx)
> >   File "/ws/client/speech_client.py", line 126, in recognize
> >     response = self.triton_client.infer(
> >   File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 1431, in infer
> >     raise_error_grpc(rpc_error)
> >   File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
> >     raise get_error_grpc(rpc_error) from None
> > tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] in ensemble 'streaming_wenet', Failed to process the request(s) for model instance 'feature_extractor_0_0', message: Stub process is not healthy.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### Triton server log
> > Here is the triton server log. [triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)
> > ### Hardware
> > ![image](https://user-images.githubusercontent.com/12630218/203748179-d5576835-a037-4f38-bb37-26f909115a40.png)
> > ### Note
> > I have tried to print the feature extraction results and found that is can be successfully output, as below:
> > ![image](https://user-images.githubusercontent.com/12630218/203747296-6f5b6f29-40b8-4b54-80b0-7eba70de6085.png)
> > ### Looking forward to your reply, thanks.
> 
> Hi, would you mind attaching your "tree model_repo_stateful/*" info here? Also, it seems that you're using vgpu. Could you first try to test it with normal GPU? I am not sure if this issue related to vGPU.

### model_repo_stateful
Thanks for u reply. Here is the infos of model_repo_stateful, the details of model_repo_stateful were generated by the script [convert_start_server.sh](https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/scripts/convert_start_server.sh)
![image](https://user-images.githubusercontent.com/12630218/203887367-b242927f-88ea-4b5d-b8d5-9b4c0b519196.png)

### vGPU
I just have half of T4 in my develop environment. I have tried trinton-inference-server [example](https://github.com/triton-inference-server/server) with vGPU, follow the below guide, and reproduced the result.
![image](https://user-images.githubusercontent.com/12630218/203890175-c6b341de-f454-4084-b122-6abd69308109.png)

**Comment by yuekaizhang** [comment]
@cocoakeith  Could you also make sure you are using fp16 inference? Maybe you could upload this model_repo_stateful through huggingface. Then I could have a try on my side using your settings.

**Comment by cocoakeith** [comment]
> 



> @cocoakeith Could you also make sure you are using fp16 inference? Maybe you could upload this model_repo_stateful through huggingface. Then I could have a try on my side using your settings.

@yuekaizhang I have upload the [model_repo_stateful](https://huggingface.co/JayKe700/wenet-triton-demo) through huggingface, u can try on ur side. The encoder and decoder model have beed converted to fp16 onnx model.

I have test only the feature extractor, and get the same error message. "Failed to process the request(s) for model instance 'feature_extractor_0_0', message: Stub process is not healthy."

**Comment by yuekaizhang** [comment]
Thanks, let me try it.

**Comment by yuekaizhang** [comment]
@cocoakeith  Sorry, I can't reproduce any issue with your model_repo on myside. https://huggingface.co/JayKe700/wenet-triton-demo/blob/main/model_repo_stateful/feature_extractor/config.pbtxt#L96 Could you change this line to "kind: KIND_CPU" and try it again?

**Comment by cocoakeith** [comment]
> @cocoakeith Sorry, I can't reproduce any issue with your model_repo on myside. https://huggingface.co/JayKe700/wenet-triton-demo/blob/main/model_repo_stateful/feature_extractor/config.pbtxt#L96 Could you change this line to "kind: KIND_CPU" and try it again?

I have modified the feature extractor config with “kind:KIND_GPU” to "KIND_CPU" and reload feature extractor model, but with same problem.  :(

**Comment by yuekaizhang** [comment]
@cocoakeith  Actually the attached tritonserver_log "Here is the triton server log. [triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)" is quite werid.   This is the expected output for your reference [output.txt](https://github.com/wenet-e2e/wenet/files/10088539/output.txt).

**Comment by cocoakeith** [comment]
> 



> @cocoakeith Actually the attached tritonserver_log "Here is the triton server log. [triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)" is quite werid. This is the expected output for your reference [output.txt](https://github.com/wenet-e2e/wenet/files/10088539/output.txt).

Have u tried this script "python3 client.py --audio_file=/ws/test_data/test1.wav --streaming --model_name=streaming_wenet"

**Comment by yuekaizhang** [comment]
> > 
> 
> > @cocoakeith Actually the attached tritonserver_log "Here is the triton server log. [triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)" is quite werid. This is the expected output for your reference [output.txt](https://github.com/wenet-e2e/wenet/files/10088539/output.txt).
> 
> Have u tried this script "python3 client.py --audio_file=/ws/test_data/test1.wav --streaming --model_name=streaming_wenet"

Yes. I could get decoding outputs with your model_repo.

**Comment by cocoakeith** [comment]
> > > 
> > 
> > 
> > > @cocoakeith Actually the attached tritonserver_log "Here is the triton server log. [triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)" is quite werid. This is the expected output for your reference [output.txt](https://github.com/wenet-e2e/wenet/files/10088539/output.txt).
> > 
> > 
> > Have u tried this script "python3 client.py --audio_file=/ws/test_data/test1.wav --streaming --model_name=streaming_wenet"
> 
> Yes. I could get decoding outputs with your model_repo.

Maybe this is a vGPU issue. I'll try with normal GPU. Thanks for u reply.

**Comment by cocoakeith** [comment]
> > > > 
> > > 
> > > 
> > > > @cocoakeith Actually the attached tritonserver_log "Here is the triton server log. [triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)" is quite werid. This is the expected output for your reference [output.txt](https://github.com/wenet-e2e/wenet/files/10088539/output.txt).
> > > 
> > > 
> > > Have u tried this script "python3 client.py --audio_file=/ws/test_data/test1.wav --streaming --model_name=streaming_wenet"
> > 
> > 
> > Yes. I could get decoding outputs with your model_repo.
> 
> Maybe this is a vGPU issue. I'll try with normal GPU. Thanks for u reply.

@yuekaizhang Hello yuekai，I tried again on the normal GPU and found the same problem. Would u mind share ur wenet server docker image， I would like to try it on my side.
![image](https://user-images.githubusercontent.com/12630218/204210227-6c2233f5-9d29-44dc-9e5d-98e534923a62.png)

**Comment by yuekaizhang** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > @cocoakeith Actually the attached tritonserver_log "Here is the triton server log. [triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)" is quite werid. This is the expected output for your reference [output.txt](https://github.com/wenet-e2e/wenet/files/10088539/output.txt).
> > > > 
> > > > 
> > > > Have u tried this script "python3 client.py --audio_file=/ws/test_data/test1.wav --streaming --model_name=streaming_wenet"
> > > 
> > > 
> > > Yes. I could get decoding outputs with your model_repo.
> > 
> > 
> > Maybe this is a vGPU issue. I'll try with normal GPU. Thanks for u reply.
> 
> @yuekaizhang Hello yuekai，I tried again on the normal GPU and found the same problem. Would u mind share ur wenet server docker image， I would like to try it on my side. ![image](https://user-images.githubusercontent.com/12630218/204210227-6c2233f5-9d29-44dc-9e5d-98e534923a62.png)

Sorry to hear that. I always use a new docker image `FROM nvcr.io/nvidia/tritonserver:22.09-py3`, other parts are same with dockerfile in runtime/gpu. I think it's fine to use tritonserver:22.03.

Would you mind trying model_repo for offline ASR to check if it works on your side?

**Comment by cocoakeith** [comment]
Hi @yuekaizhang , it works for offline ASR. I have tried docker image tritonserver:22.[03-05]-py3, but with same problem, emo......

**Comment by yuekaizhang** [comment]
@Slyne  Do you have some ideas about the issue?

**Comment by riverliuc** [comment]
Hi @cocoakeith , it seems the python backend process corrupts because of some exception. could you please try to put some print() in feature_extractor/1/model.py:execute() function, and try to figure out which codes cause the python backend corruption?

**Comment by riverliuc** [comment]
> > 
> 
> > @cocoakeith Actually the attached tritonserver_log "Here is the triton server log. [triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)" is quite werid. This is the expected output for your reference [output.txt](https://github.com/wenet-e2e/wenet/files/10088539/output.txt).
> 
> Have u tried this script "python3 client.py --audio_file=/ws/test_data/test1.wav --streaming --model_name=streaming_wenet"

And do you mean just inferring one audio will cause the error?

**Comment by cocoakeith** [comment]
> Hi @cocoakeith , it seems the python backend process corrupts because of some exception. could you please try to put some print() in feature_extractor/1/model.py:execute() function, and try to figure out which codes cause the python backend corruption?
Hi @riverliuc , I tried to print the extracted fbank feature, the code and print result as below:
![image](https://user-images.githubusercontent.com/12630218/204523487-3f1c131a-48bd-491b-9b0b-8d63698364ba.png)

![image](https://user-images.githubusercontent.com/12630218/204523407-4482f3b6-9e91-44ee-929c-34997a721bc2.png)

**Comment by cocoakeith** [comment]
> > > 
> > 
> > 
> > > @cocoakeith Actually the attached tritonserver_log "Here is the triton server log. [triton_server.log](https://github.com/wenet-e2e/wenet/files/10082985/triton_server.log)" is quite werid. This is the expected output for your reference [output.txt](https://github.com/wenet-e2e/wenet/files/10088539/output.txt).
> > 
> > 
> > Have u tried this script "python3 client.py --audio_file=/ws/test_data/test1.wav --streaming --model_name=streaming_wenet"
> 
> And do you mean just inferring one audio will cause the error?

Inferring with audio dir casuse the same error.

**Comment by riverliuc** [comment]
Do you observe same issue in  tritonserver:22.[06-10]-py3?

**Comment by riverliuc** [comment]
And could you please check the size of your shared memory by runing `df -h | grep shm` inside the docker container, and running ` docker inspect <conatiner id>| grep -i shm` outside the container?
Since Triton python backend requires shared memory to transfer data, I wnat to make sure there is enough shared memory for your container.

**Comment by cocoakeith** [comment]
> docker inspect <conatiner id>| grep -i shm

Here is the info of shm.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/12630218/204540410-9914811e-999f-4c4c-8228-f520fd764cb6.png">

**Comment by riverliuc** [comment]
> > docker inspect | grep -i shm
> 
> Here is the info of shm.
> 
> <img alt="image" width="1097" src="https://user-images.githubusercontent.com/12630218/204540410-9914811e-999f-4c4c-8228-f520fd764cb6.png">

Looks fine... really weird. Will try to figure out tomorrow.

**Comment by cocoakeith** [comment]
> Do you observe same issue in tritonserver:22.[06-10]-py3?

I'm trying to use tritonserver:22.10-py3, there is some issue when build docker image, i will fix the issue and then try feature extractor model tomorrow.

**Comment by cocoakeith** [comment]
> 

It seems not the issue of feature extractor model, Is the nvidia-driver version too low?
<img width="957" alt="image" src="https://user-images.githubusercontent.com/12630218/204541855-c98cfe97-9d61-40de-975d-b98a8e00c22d.png">

**Comment by riverliuc** [comment]
Emmm, 450 is indeed too low. Can you try to upgrade the driver?

**Comment by cocoakeith** [comment]
> Emmm, 450 is indeed too low. Can you try to upgrade the driver?

The nvidia-driver is limited by the host machine and cannot be upgraded.

**Comment by cocoakeith** [comment]
> Emmm, 450 is indeed too low. Can you try to upgrade the driver?

@riverliuc However, it works for wenet offline ASR model.

**Comment by cocoakeith** [comment]
> Could you change https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/Dockerfile/Dockerfile.server#L7 to `pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113` and then rebuild a new docker image? (Or you could do it directly in current container and rebuild the kaldifeat.) It seems kaldifeat can't work with torch 0.13 for streaming feature extraction. @cocoakeith

@yuekaizhang @riverliuc @robin1001 I works for straming feature extraction when i change torch version from `torch==1.13.0+cu117` to `torch==1.11.0+cu113`.

The streaming feature extraction is a stateful triton model, and fbank features have been extracted, kaldifeat should work, so maybe my nvidia-driver version is too low and when use high torch version will casue stateful triton model not work.  How do u think?
-----------------------------------
Thanks for ur help.

**Comment by Slyne** [comment]
@cocoakeith 
It might be related to this issue: https://github.com/triton-inference-server/server/issues/4026#issuecomment-1346829451
