### ISSUE TITLE
generate TLG.fst issue

### ISSUE THREAD

**Issue by Fred-cell** [wenet-e2e/wenet#1583]
after build runtime/libtorch, then execute "bash run.sh --stage 7 --stop-stage 7", error is as below, in runtime/libtorch/fc_base/kaldi folder, lack some bin files.
Ignoring words 玮甯, which contains oov unit
Ignoring words 熙娣, which contains oov unit
Ignoring words 燮林, which contains oov unit
Ignoring words ｔ恤, which contains oov unit
Ignoring words 一ii, which contains oov unit
file data/local/lm/heldout: 10000 sentences, 89496 words, 0 OOVs
0 zeroprobs, logprob= -272791.2 ppl= 551.7352 ppl1= 1117.077
tools/fst/compile_lexicon_token_fst.sh: line 61: fstcompile: command not found
tools/fst/compile_lexicon_token_fst.sh: line 62: fstarcsort: command not found
Traceback (most recent call last):
  File "tools/fst/ctc_token_fst_compact.py", line 19, in <module>
    print('{} {} {} {}'.format(node, 0, '<eps>', '<eps>'))
BrokenPipeError: [Errno 32] Broken pipe
tools/fst/make_tlg.sh: line 23: arpa2fst: command not found
tools/fst/make_tlg.sh: line 23: fstprint: command not found
tools/fst/make_tlg.sh: line 24: fstcompile: command not found
tools/fst/make_tlg.sh: line 26: fstrmepsilon: command not found
tools/fst/make_tlg.sh: line 26: fstarcsort: command not found
Checking how stochastic G is (the first of these numbers should be small):
tools/fst/make_tlg.sh: line 30: fstisstochastic: command not found
tools/fst/make_tlg.sh: line 33: fsttablecompose: command not found
tools/fst/make_tlg.sh: line 33: fstdeterminizestar: command not found
tools/fst/make_tlg.sh: line 34: fstminimizeencoded: command not found
tools/fst/make_tlg.sh: line 34: fstarcsort: command not found

**Comment by robin1001** [comment]
please make sure you turn GRAPH_TOOS on when building, see

# runtime build requires cmake 3.14 or above
cd runtime/libtorch
mkdir build && cd build && cmake -DGRAPH_TOOLS=ON .. && cmake --build .
