### ISSUE TITLE
CTM info from decoder

### ISSUE THREAD

**Issue by jayakrishnanmm** [wenet-e2e/wenet#1588]
Hi,
I have  tried  the Gigaspeech trained English pre-trained model, and can decode successfully. Is there a way to get the CTM info from the  decoder ? ( I am not using LM )
Regards
JK

**Comment by robin1001** [comment]
what is CTM?

**Comment by MaGuodong0712** [comment]
https://github.com/wenet-e2e/wenet/blob/ff7b356f7aa993b74d8a68f9288828a5f373391e/runtime/core/decoder/asr_decoder.h#L66

**Comment by MaGuodong0712** [comment]
https://github.com/wenet-e2e/wenet/blob/ff7b356f7aa993b74d8a68f9288828a5f373391e/runtime/core/decoder/asr_decoder.h#L63

**Comment by MaGuodong0712** [comment]
TimeStamp? I remember the CTM file appear to kaldi. If I am right, see this code mybe help. https://github.com/wenet-e2e/wenet/blob/ff7b356f7aa993b74d8a68f9288828a5f373391e/runtime/core/decoder/asr_decoder.h#L63 here, wordpiece struct record the start and end time of the output unit.

**Comment by MaGuodong0712** [comment]
From https://github.com/wenet-e2e/wenet/blob/ff7b356f7aa993b74d8a68f9288828a5f373391e/runtime/core/decoder/asr_decoder.cc#L158 to https://github.com/wenet-e2e/wenet/blob/ff7b356f7aa993b74d8a68f9288828a5f373391e/runtime/core/decoder/asr_decoder.cc#L183, time infomation have been assigned to the wordpiece struct, you can use it for your interest.

**Comment by jayakrishnanmm** [comment]
Is there  any confidence score per word ?

**Comment by MaGuodong0712** [comment]
I am sorry, it seems not implement. Maybe, you need modify the prefix beam search code to support it. And maybe the creators of WeNet has solutions for it ? I also look forward to their answers.   Best regards.

**Comment by MaGuodong0712** [comment]
I have thought about it for a moment. Maybe you can record the CTC peak score for every modeling unit in prefix beam search ( because the timestamp also is get using CTC peak score information), but you need to make some changes to the process of prefix beam search.     Best regrards.

**Comment by jayakrishnanmm** [comment]
thanks  for your help.

**Comment by ospeech** [comment]
I get timestamp for every word according to https://github.com/wenet-e2e/wenet/issues/604
but get something strange as follows:
这 140 240 里 260 360 面 380 480 是 500 600 有 740 840 很 940 1040 多 1060 1160 中 1220 1320 间 1340 1440 环 1500 1600 节 1660 1760 的 1780 1880 
other utterances have similar result.  every wordpiece has a span of 100 and first start is almost inaccurate.
is it a normal result or i got wrong configuraion for decoding?

**Comment by robin1001** [comment]
Yes, it's a normal result. We use CTC in our framework to generate timestamp, and CTC doesn't give an accurate timestamp, and we limit the time span of each `char` in 100 ms in our implementation.

please see https://github.com/wenet-e2e/wenet/blob/main/runtime/core/decoder/asr_decoder.cc#L170.
