### ISSUE TITLE
基于SqueezeFormer的ONNX模型转换后，结果不一致问题

### ISSUE THREAD

**Issue by lvchigo** [wenet-e2e/wenet#1598]
# 一、问题描述
- 感谢修复https://github.com/wenet-e2e/wenet/issues/1569#issue-1457497469；
- 但、基于SqueezeFormer的ONNX模型转换后，结果存在不一致问题，具体如下：
- 模型转换前、wer评估的抽样结果：  
![image](https://user-images.githubusercontent.com/8186051/205544706-1f9024c0-1ad6-4e1d-b9e3-2de3dee7c437.png)    
- 模型转换后、wer评估的抽样结果：  
![image](https://user-images.githubusercontent.com/8186051/205544753-2b3aabd8-8dfe-4017-9120-9f0bf84b0c62.png)
- SqueezeFormer模型进行onnx的模型转换后，结果存在极大差异；
- 在本人4万条10秒音频测试集上，存在20%WER的差异；

# 二、执行命令
- 如需SqueezeFormer的训练模型：请联系176032216@qq.com
## 2.1、模型转换前--效果评估
```
decoding_chunk_size=16
ctc_weight=0.5
reverse_weight=0.0
python ${WENET_DIR}/wenet/bin/recognize.py --gpu -1 \
  --mode $mode \
  --config ${train_config} \
  --data_type $data_type \
  --test_data data/$testset/data.list \
  --checkpoint $decode_checkpoint \
  --beam_size 10 \
  --batch_size 1 \
  --penalty 0.0 \
  --dict $dict \
  --ctc_weight $ctc_weight \
  --reverse_weight $reverse_weight \
  --result_file $result_dir/text \
  ${decoding_chunk_size:+--decoding_chunk_size $decoding_chunk_size}
python ${WENET_DIR}/tools/compute-wer.py --char=1 --v=1 \
  data/$testset/text $result_dir/text > $result_dir/wer
```
## 2.2、模型转换--执行命令
```
if [ ${stage} -le -1 ] && [ ${stop_stage} -ge -1 ]; then
  #
  echo "stage -1: [onnx] Export the best model you want"
  python3 ${WENET_DIR}/wenet/bin/export_onnx_cpu.py \
    --config ${config_file} \
    --checkpoint ${checkpoint_file} \
    --chunk_size 16 \
    --output_dir ${onnx_path} \
    --num_decoding_left_chunks -1 \
    --reverse_weight 0.5
fi
```
- 转换后模型：  
![image](https://user-images.githubusercontent.com/8186051/205545444-ae4ba8d9-ade3-4c20-ab3d-c8a14394a36e.png)  
## 2.3、模型转换后--效果评估
```
  echo "[stage:0] decoder_main start ..."
  ../onnxruntime/build-cpu/bin/decoder_main \
      --chunk_size 16 \
      --wav_scp ${wav_scp} \
      --onnx_dir ${onnx_uint_path} \
      --unit_path ${unit_file} 2>&1 | tee log.txt
  echo "[stage:0] decoder_main end ..."

  mkdir -p "${text_DIR}/test_wer/"
  echo "[stage:1] compute-wer start ..."
  python3 compute-wer.py --char=1 --v=1 ${text_gt} ${text_predict} > ${text_wer}
  echo "[stage:1] compute-wer end !!!"
```
# 三、安装环境
- wenet版本：20221202拉取的主分支（该版本已支持SqueezeFormer的ONNX模型转换）
- 系统 centos7
- python 3.8.13
- gcc 10.3.0
- torch 1.10.0+cu113
- torchaudio 0.10.0+cu113
- torchvision 0.11.0+cu113
- onnx 1.12.0
- onnxconverter-common 1.13.0
- onnxmltools 1.11.1
- onnxruntime 1.13.1
- skl2onnx 1.13

**Comment by yygle** [comment]
有simulate streaming的结果吗？

**Comment by yygle** [comment]
结果差异是由于time reduction layer 的padding引入的，如果你希望训练兼容流式的模型，请把 time reduction layer type设置为“stream”。感谢提问，这个注释会在后续被添加。

**Comment by lvchigo** [comment]
感谢。。膜拜大佬。。
