### ISSUE TITLE
ONNX infereneing using onnxruntime-gpu fails on jetson

### ISSUE THREAD

**Issue by neso613** [wenet-e2e/wenet#1601]
I have converted onnx model on CPU and GPU as well.

To run onnx inference on CPU, the [step 3](https://github.com/wenet-e2e/wenet/tree/main/runtime/onnxruntime) worked after following step 2.
To run onnx inference on GPU, this [recognize_onnx_gpu](https://github.com/wenet-e2e/wenet/tree/main/runtime/onnxruntime) worked.

But onnx inferencing on GPU fails on jetson boards. 
Also, it uses kaldi based format as in input like "--dict-file". How can this be removed?

`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/wenet/wenet/bin/recognize_onnx_gpu.py", line 278, in <module>
    main()
  File "/data/wenet/wenet/bin/recognize_onnx_gpu.py", line 178, in main
    ort_outs = encoder_ort_session.run(None, ort_inputs)
  File "/usr/local/lib/python3.8/dist-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 196, in run
    raise ValueError("Model requires {} inputs. Input Feed contains {}".format(num_required_inputs, num_inputs))
ValueError: Model requires 4 inputs. Input Feed contains 2
`

@xingchensong

**Comment by xingchensong** [comment]
I guess your model is the steaming (online) version, however, recognize_onnx_gpu only support non-streaming (offline) version. See https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/recognize_onnx_gpu.py#L29-L35
