### ISSUE TITLE
流式模型训练不收敛的问题

### ISSUE THREAD

**Issue by haoyunlf** [wenet-e2e/wenet#1606]
使用train_unified_conformer.yaml或train_u2++_conformer.yamal训练流式模型都不收敛；同样的数据（aishell）训练非流式train_conformer.yaml可以收敛

不收敛的loss一直在30-40以上，而且测试时不输出识别的字：
![image](https://user-images.githubusercontent.com/68471413/206620764-9bf38bad-4a22-4ec0-898b-923343919eb2.png)

**Comment by xingchensong** [comment]
训了多少轮，有没有改过什么代码，代码是不是最新的发自我的 iPhone在 2022年12月9日，12:03，haoyunlf ***@***.***> 写道：﻿
使用train_unified_conformer.yaml或train_u2++_conformer.yamal训练流式模型都不收敛；同样的数据（aishell）训练非流式train_conformer.yaml可以收敛
不收敛的loss一直在30-40以上，而且测试时不输出识别的字：

**Comment by haoyunlf** [comment]
> 训了多少轮，有没有改过什么代码，代码是不是最新的发自我的 iPhone在 2022年12月9日，12:03，haoyunlf ***@***.***> 写道：﻿ 使用train_unified_conformer.yaml或train_u2++_conformer.yamal训练流式模型都不收敛；同样的数据（aishell）训练非流式train_conformer.yaml可以收敛 不收敛的loss一直在30-40以上，而且测试时不输出识别的字： —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

代码是最新的,没有改过，训了148个epoch还是这样(aishell s0)
![image](https://user-images.githubusercontent.com/68471413/206629459-548820e0-9c37-4f09-8fb4-c0e214fc7c55.png)

**Comment by xingchensong** [comment]
你这个是单卡，要八卡训，没有八卡就增加batchsize，目的一样，因为单卡batchsize16太小了发自我的 iPhone在 2022年12月9日，13:20，haoyunlf ***@***.***> 写道：﻿

训了多少轮，有没有改过什么代码，代码是不是最新的发自我的 iPhone在 2022年12月9日，12:03，haoyunlf @.> 写道：﻿ 使用train_unified_conformer.yaml或train_u2++_conformer.yamal训练流式模型都不收敛；同样的数据（aishell）训练非流式train_conformer.yaml可以收敛 不收敛的loss一直在30-40以上，而且测试时不输出识别的字： —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.>

代码是最新的,没有改过，训了148个epoch还是这样(aishell s0)

**Comment by haoyunlf** [comment]
> 你这个是单卡，要八卡训，没有八卡就增加batchsize，目的一样，因为单卡batchsize16太小了发自我的 iPhone在 2022年12月9日，13:20，haoyunlf ***@***.***> 写道：﻿ 训了多少轮，有没有改过什么代码，代码是不是最新的发自我的 iPhone在 2022年12月9日，12:03，haoyunlf @.> 写道：﻿ 使用train_unified_conformer.yaml或train_u2++_conformer.yamal训练流式模型都不收敛；同样的数据（aishell）训练非流式train_conformer.yaml可以收敛 不收敛的loss一直在30-40以上，而且测试时不输出识别的字： —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.> 代码是最新的,没有改过，训了148个epoch还是这样(aishell s0) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

好的我试一下，谢谢

**Comment by Songs12345** [comment]
我也遇到相同的问题，请问您解决了吗，是单卡吗，只调整batchsize吗，调成多大了

**Comment by wwfcnu** [comment]
> > 我也遇到相同的问题，请问您解决了吗，是单卡吗，只调整batchsize吗，调成多大了
> 
> 是单卡。改成双卡、调大batch size或者gradient accumulation都可以解决，具体多少不太记得了。

正常训练的话，训练损失和cv损失能达到多少

**Comment by wwfcnu** [comment]
我两张卡，batch_size=16，训了127个epoch，cv loss还是70
