### ISSUE TITLE
Getting stuck while decoding with runtime using TLG.fst

### ISSUE THREAD

**Issue by lucgeo** [wenet-e2e/wenet#1607]
Hi,

I'm trying to run the librispeech/s0 recipe. Everything went fine until I reached the 7.4 step called "Decoding with runtime" which is using the TLG.fst language model. It runs for as many days as possible and it doesn't seem to end or write anything in the output folder "exp/sp_spec_aug/lm_with_runtime_test_clean". In other words, the decoding process seems to be stuck. Any idea what the problem is?

Thanks!

**Comment by xingchensong** [comment]
see https://github.com/wenet-e2e/wenet/issues/563#issuecomment-911130086
