### ISSUE TITLE
Why rel_shift is useless in speech recognition?

### ISSUE THREAD

**Issue by cindycindyhi** [wenet-e2e/wenet#1612]
**Describe the bug**
The attention implemetion in squeezeformer remove the rel_shift.
<pre> 
        # compute matrix b and matrix d
        # (batch, head, time1, time2)
        matrix_bd = torch.matmul(q_with_bias_v, p.transpose(-2, -1))
        # Remove rel_shift since it is useless in speech recognition,
        # and it requires special attention for streaming.
        if self.do_rel_shift:
            matrix_bd = self.rel_shift(matrix_bd)
</pre> 

So why rel_shift is useless in speech recognition?
@yygle

**Comment by robin1001** [comment]
Yes, we do did some experiments on aishell-1, which showed there is no regresssion if rel_shift is not applied.

**Comment by cindycindyhi** [comment]
> Yes, we do did some experiments on aishell-1, which showed there is no regresssion if rel_shift is not applied.

The rel_shift will be usefull in stantard relpos encoding since the relpos shape is [batch, 2*seq_length] but the abspos shape is [batch, seq_length].
Rel_shift need to convert relpos shape [batch, 2*seq_length] to [batch, seq_length].

**Comment by robin1001** [comment]
@yygle have you done some experiment on streaming model using relative position encoding?

**Comment by yygle** [comment]
@robin1001 On going, it will be added if it has improvements.
