### ISSUE TITLE
path.sh sets wrong OPENFST_PREFIX_DIR path

### ISSUE THREAD

**Issue by fclearner** [wenet-e2e/wenet#1613]
commands:
'''
cd runtime/libtorch
mkdir build && cd build && cmake -DGRAPH_TOOLS=ON .. && cmake --build .
'''
will not generate ${BUILD_DIR}/../fc_base/openfst-subbuild/openfst-populate-prefix/bin,
right path is ${BUILD_DIR}/../fc_base/openfst-build/src/bin

is seems most of the path.sh in examples set the wrong path

**Comment by pengzhendong** [comment]
aishell is correct.
please pull request for others.
