### ISSUE TITLE
Bug in Squeezeformer embedding implementation.

### ISSUE THREAD

**Issue by cindycindyhi** [wenet-e2e/wenet#1616]
https://github.com/wenet-e2e/wenet/blob/2821629e49caa6b094d6f83b9216b05ef7fa2917/wenet/squeezeformer/subsampling.py#L89-L90

The function `pos_enc` will do `x = x + pos`, but the shape of x is `[batch, length, 2916]`, the pos shape is `[1, length, 324]`
Maybe should change the execution order of the code, do `input_proj` first and then do `pos_enc`.
By the way, this step `x = x + pos` is not required in other implementations. RelMHA just need clear input `x` and `pos`.

Besides, the `pos_enc` have `dropout(x)`, which is duplicate with `dropout` in `input_proj`.

@yygle

**Comment by yygle** [comment]
If you want to use the basic pos emb, the order should be changed. Here, i use rel pos func, there's no x + pos operation. So the output should be the same.
As for the dropout, it is redundant and will be removed later.
