### ISSUE TITLE
SqueezeFormer单路解码和batch结果不一致

### ISSUE THREAD

**Issue by hungker** [wenet-e2e/wenet#1617]
SqueezeFormer单路解码和batch结果不一致, 更改mask后未能解决问题。

**Comment by yygle** [comment]
训练的时候用的是bn还是ln呢？

**Comment by hungker** [comment]
@yygle 
用的是layernorm

**Comment by yygle** [comment]
测试集上WER差距大吗？有具体的实验结果吗？

**Comment by hungker** [comment]
内部的一个测试集：
bsz=1, Corr=79.46, Acc=76.15
bsz=8, Corr=79.52, Acc=76.21
bsz=16, Corr=79.35, Acc=76.04
bsz=32, Corr=79.12, Acc=75.81

**Comment by yygle** [comment]
测试用的是libtorch还是onnx呢？reduce部分用了mask，recover部分确实没用过，可能引入差异。

**Comment by hungker** [comment]
用原型测试的，解码模式ctc_greedy_search和attention模式都存在不一致的情况。

**Comment by yygle** [comment]
晚点我再提个PR，把recover部分mask加一下，你有空可以再测试一下试试，或者你解决了的话也提个PR合并一下。

**Comment by hungker** [comment]
好的

**Comment by yygle** [comment]
https://github.com/wenet-e2e/wenet/pull/1618
Hi，有空的时候可以测试一下，是不是这个原因造成的。

**Comment by hungker** [comment]
测试了一下，按照上面要求修改后，还是存在多路解码不一致的问题。

**Comment by yygle** [comment]
应该是还有其他地方需要规避，你方便把测试的代码传上来吗？我这边调试不太方便。

**Comment by hungker** [comment]
不好意思，这个不太方便，放在公司内网，代码不能导出。

**Comment by yygle** [comment]
ok，那晚点我后面自己写个测一下

**Comment by cindycindyhi** [comment]
我觉得应该这么改吧
 <pre>
xs = recover_tensor + xs[:, :recoverd_t, :].contiguous()   
chunk_masks = torch.repeat_interleave(chunk_masks, repeats=2, dim=-1)[:, :, :recoverd_t].contiguous()   
mask_pad = torch.repeat_interleave(mask_pad, repeats=2, dim=-1)[:, :, :recoverd_t].contiguous()   
 </pre>
把mask进行一个缩放操作，匹配xs的缩放

**Comment by yygle** [comment]
@hungker 有空可以试一下上面的解决方案。

**Comment by yygle** [comment]
@cindycindyhi 如果有效的话，麻烦提个PR修正这个BUG。

**Comment by hungker** [comment]
试了一下，还是不行。

**Comment by xingchensong** [comment]
any updates?

**Comment by yygle** [comment]
Sorry for that, i'm afraid i don't have time to fix this in the near future.
