### ISSUE TITLE
Import error at wenet version 1.13.0 with container

### ISSUE THREAD

**Issue by cool9203** [wenet-e2e/wenet#1621]
**Describe the bug**
Wenet version 1.13.0 will get ImportError, not import `_wenet`. In python3.7

**To Reproduce**
1. Build this Dockerfile
```dockerfile
FROM python:3.7
WORKDIR app
RUN pip install wenetruntime==1.13.0
CMD ["/bin/sh"]
```
2. Run this image
3. Enter to python with command `python`
4. Import wenet with `import wenetruntime`
5. Get error

**Expected behavior**
Step 5 will get following error message
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/wenetruntime/__init__.py", line 1, in <module>
    from .decoder import Decoder  # noqa
  File "/usr/local/lib/python3.7/site-packages/wenetruntime/decoder.py", line 17, in <module>
    import _wenet
ImportError: libtorch.so: cannot open shared object file: No such file or directory
```

**Screenshots**
ImpoerError screenshots:
> ![image](https://user-images.githubusercontent.com/29609607/208338623-adc6811a-a9dc-45ad-b9b4-a113d274ac35.png)

**Desktop (please complete the following information):**
 - OS: Windows10(64 bits)
 - ContainerRuntime: Podman==4.3.1
 - WSL version description: 
    > WSL version： 1.0.3.0
    > Core version： 5.15.79.1
    > WSLg version： 1.0.47
    > MSRDC version： 1.2.3575
    > Direct3D version： 1.606.4
    > DXCore version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
    > Windows version： 10.0.19045.2364

**Additional context**
I try to use version `wenetruntime==1.0.8`, will not get error. Following screenshot
> ![image](https://user-images.githubusercontent.com/29609607/208338361-cac715cd-21f2-472c-ac4a-48c5a1ed1ac2.png)

Use following Dockerfile:
```dockerfile
FROM python:3.7
WORKDIR app
RUN pip install wenetruntime==1.0.8
CMD ["/bin/sh"]
```

Maybe is version 1.13.0 error?

And i have compare local install 1.0.8 version, found 1.13.0 not have `wenet_api.so` (in linux), but maybe just is OS difference. (1.13.0 in WSL container, 1.0.8 in windows10)

**Comment by cool9203** [comment]
Update:
Sorry, i not read [this](https://github.com/wenet-e2e/wenet/blob/main/runtime/binding/python/README.md)
Need more import `torch`.

**Comment by dong-8080** [comment]
So the solution is first import torch and then import wenetruntime, as bellow:
```
import torch
import wenetruntime
```
or just import wenetruntime will cause error:
```
import wenetruntime

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xx/tools/miniconda3/envs/torch1130/lib/python3.8/site-packages/wenetruntime/__init__.py", line 1, in <module>
    from .decoder import Decoder  # noqa
  File "/home/xx/tools/miniconda3/envs/torch1130/lib/python3.8/site-packages/wenetruntime/decoder.py", line 17, in <module>
    import _wenet
ImportError: libtorch.so: cannot open shared object file: No such file or directory
```
