### ISSUE TITLE
Encoder层+ctc.lo+argmax返回全0

### ISSUE THREAD

**Issue by Plutoisme** [wenet-e2e/wenet#1623]
我在做一项音频比对的研究，打算用Wenet的Encoder层+CTC的全连接层 提取音频特征。当我使用基于https://github.com/wenet-e2e/wenet/tree/main/examples/aishell/s0 ,的预训练模型时发现比对效果不理想。

于是我打印了encoder+ctc.lo+argmax的输出查看，**按照我的理解这一部分应该是流式推理出的结果，数字即标签对应的是某个字符**，但当我打印出来发现输出是全0，想请问下这种是什么原因呢？

我的数据处理过程如下：
.wav 经过kaldi.fbank 生成Fbank特征； Fbank特征经过encoder层提取特征A，特征A经过ctc.ctc.lo得到特征B。其中我的kaldi.fbank完全按照训练时的yaml文件设置参数，并且也有注意到global_cmvn的设置。

经过多次输入不同的.wav音频也是如此，如：
<img width="385" alt="image" src="https://user-images.githubusercontent.com/48951434/208397867-85c295f5-f152-4c06-af1e-012305971f92.png">
<img width="297" alt="image" src="https://user-images.githubusercontent.com/48951434/208397990-a742d1dc-f7e6-4a2e-a966-61f04677ced8.png">

**Comment by robin1001** [comment]
先试试用标准的流程，看看能不能正常工作，然后再逐步对比自己的流程。
