### ISSUE TITLE
attention decode解码方式cache使用问题

### ISSUE THREAD

**Issue by hicliff** [wenet-e2e/wenet#1625]
https://github.com/wenet-e2e/wenet/blob/f673284990886a0f94a6ca865c1382b6fb8ec7be/wenet/transformer/asr_model.py#L246

attention decode解码方式在forward_one_step函数使用了cache，我理解是cache之前hyps在每一个decoder_layer的输出。这里有一个问题，假设B=1, N=3，词典大小为3，字符为A, B, C。

i = 1时，hyps为（sos, sos, sos），forward_one_step后的cache为(sos, sos, sos) 这个batch作为输入所有decoder_layer的输出。
i = 2时，hyps为（sosA, sosB, sosC），forward_one_step后的cache为（sosA, sosB, sosC）这个batch对应所有decoder_layer的输出。假设每个hyp用A, B, C扩展并取N=3best后，新的hyps是（sosAA, sosAB, sosBA）
i = 3时，hyps为（sosAA, sosAB, sosBA），在解码时，需要的cache应该是（sosA, sosA, sosB）这个batch对应的decoder_layer输出的缓存，但实际的缓存是（sosA, sosB, sosC）对应的decoder_layer的输出，这里是不是有问题呢？

**Comment by robin1001** [comment]
是的，这个是个潜在的 bug，你可以试试按你的想法修改一下，看看影响。

**Comment by hicliff** [comment]
> 是的，这个是个潜在的 bug，你可以试试按你的想法修改一下，看看影响。

ok, I will try

**Comment by xingchensong** [comment]
可以尝试用index_select，根据hyps的best index抽出来对应的cache

**Comment by xingchensong** [comment]
可以试一下：

![image](https://user-images.githubusercontent.com/13466943/208855145-e4fda193-e69c-49f3-9388-2f010b11f530.png)

**Comment by hicliff** [comment]
> 可以试一下：
> 
> ![image](https://user-images.githubusercontent.com/13466943/208855145-e4fda193-e69c-49f3-9388-2f010b11f530.png)
”可以尝试用index_select，根据hyps的best index抽出来对应的cache“，思路是这样的。
我看了下这个实现，有些疑问。第255行的cache_index元素肯定是不重复的，这样还是没法选出新的hyp是由原来某个hyp通过多个字符扩展而来的情况，cache_index里的元素应该是有重复可能的。
![image](https://user-images.githubusercontent.com/9379006/209338884-fe6e6e07-62d3-4fe6-8c82-082e619bc2aa.png)

**Comment by xingchensong** [comment]
cache也做了相应的repeat扩展，所以不重复的index对应的cache可能是一样的发自我的 iPhone在 2022年12月23日，20:49，Yi Peng ***@***.***> 写道：﻿

可以试一下：

”可以尝试用index_select，根据hyps的best index抽出来对应的cache“，思路是这样的。
我看了下这个实现，有些疑问。第255行的cache_index元素肯定是不重复的，这样还是没法选出新的hyp是由原来某个hyp通过多个字符扩展而来的情况，cache_index里的元素应该是有重复可能的。

**Comment by xingchensong** [comment]
可以直接提个pr发自我的 iPhone在 2022年12月23日，20:49，Yi Peng ***@***.***> 写道：﻿

可以试一下：

”可以尝试用index_select，根据hyps的best index抽出来对应的cache“，思路是这样的。
我看了下这个实现，有些疑问。第255行的cache_index元素肯定是不重复的，这样还是没法选出新的hyp是由原来某个hyp通过多个字符扩展而来的情况，cache_index里的元素应该是有重复可能的。

**Comment by hicliff** [comment]
Done. #1635
