### ISSUE TITLE
Export ONNX fail  with export_onnx_gpu.py

### ISSUE THREAD

**Issue by rickychanhoyin** [wenet-e2e/wenet#1630]
[error.log](https://github.com/wenet-e2e/wenet/files/10277214/error.log)
Attached error.log is showed with verbose.

i tried with different onnxruntime versions, still gave the same errors.  Simple log is as follow: 

python3 wenet/bin/export_onnx_gpu.py --config=/home/ricky/heqing/8w-hours/squeezeformer-8whr-avg2/train.yaml --checkpoint=/home/ricky/heqing/8w-hours/squeezeformer-8whr-avg2/avg_10_156000_13_196000.pt --cmvn_file=/home/ricky/heqing/8w-hours/squeezeformer-8whr-avg2/global_cmvn  --ctc_weight=0.5 --output_onnx_dir=/tmp
Failed to import k2 and icefall.         Notice that they are necessary for hlg_onebest and hlg_rescore
Update ctc weight to  0.5
/home/ricky/wenet_train_res/wenet_tools_git/wenet/utils/mask.py:213: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  max_len = max_len if max_len > 0 else lengths.max().item()
/home/ricky/wenet_train_res/wenet_tools_git/wenet/transformer/embedding.py:96: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert offset + size < self.max_len
/home/ricky/wenet_train_res/wenet_tools_git/wenet/squeezeformer/attention.py:187: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if cache.size(0) > 0:
/home/ricky/wenet_train_res/wenet_tools_git/wenet/squeezeformer/attention.py:119: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if mask.size(2) > 0:  # time2 > 0
/home/ricky/wenet_train_res/wenet_tools_git/wenet/squeezeformer/convolution.py:140: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if mask_pad.size(2) > 0:  # time > 0
/home/ricky/wenet_train_res/wenet_tools_git/wenet/squeezeformer/convolution.py:171: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if mask_pad.size(2) > 0:  # time > 0
/home/ricky/wenet_train_res/wenet_tools_git/wenet/squeezeformer/subsampling.py:159: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if L - T < 0:
[0, 0, 0] [-1, -1, -1]
2022-12-21 19:30:33.720608405 [W:onnxruntime:, constant_folding.cc:150 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_2506'
2022-12-21 19:30:33.768034651 [W:onnxruntime:, constant_folding.cc:150 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_2506'
2022-12-21 19:30:33.812875437 [W:onnxruntime:, constant_folding.cc:150 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_2506'
2022-12-21 19:30:35.151413519 [E:onnxruntime:, sequential_executor.cc:333 Execute] Non-zero status code returned while running MatMul node. Name:'MatMul_2528' Status Message: Not satisfied: K_ == right_shape[right_num_dims - 2] || transb && K_ == right_shape[right_num_dims - 1]
matmul_helper.h:42 ComputeMatMul dimension mismatch
Traceback (most recent call last):
  File "wenet/bin/export_onnx_gpu.py", line 574, in <module>
    onnx_config = export_enc_func(model, configs, args, logger, encoder_onnx_path)
  File "wenet/bin/export_onnx_gpu.py", line 331, in export_offline_encoder
    ort_outs = ort_session.run(None, ort_inputs)
  File "/home/ricky/anaconda3/envs/wenet/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 124, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running MatMul node. Name:'MatMul_2528' Status Message: Not satisfied: K_ == right_shape[right_num_dims - 2] || transb && K_ == right_shape[right_num_dims - 1]
matmul_helper.h:42 ComputeMatMul dimension mismatch

**Comment by robin1001** [comment]
why there is log of k2

> Failed to import k2 and icefall. Notice that they are necessary for hlg_onebest and hlg_rescore
Update ctc weight to 0.5

**Comment by xingchensong** [comment]
export_onnx_gpu does not support SqueezeFormer

**Comment by xingchensong** [comment]
> why there is log of k2
> 
> > Failed to import k2 and icefall. Notice that they are necessary for hlg_onebest and hlg_rescore
> > Update ctc weight to 0.5

I think it is normal behaviour: https://github.com/wenet-e2e/wenet/pull/1521#discussion_r1006467991

**Comment by robin1001** [comment]
@yygle @yuekaizhang do you have time to fix the problem?

**Comment by yygle** [comment]
I'll check it this week.

**Comment by rickychanhoyin** [comment]
The failure came after the export of encoder.onnx . I have a program which test the valid of the onnx structure.

./onnx-test /tmp/encoder.onnx
2022-12-24 14:55:54.454720687 [W:onnxruntime:, constant_folding.cc:157 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_2506'
2022-12-24 14:55:54.496876808 [W:onnxruntime:, constant_folding.cc:157 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_2506'
2022-12-24 14:55:54.518339949 [W:onnxruntime:, constant_folding.cc:157 ApplyImpl] Unsupported output type of N11onnxruntime22SequenceTensorTypeBaseE. Can't constant fold SequenceEmpty node 'SequenceEmpty_2506'
terminate called after throwing an instance of 'Ort::Exception'
  what():  Got invalid dimensions for input: speech for the following indices
 index: 2 Got: 1 Expected: 80
 Please fix either the inputs or the model.

**Comment by yygle** [comment]
This is because of the torch.repeat_interleave operator,
if you are urgent to use it in offline, change `xs = torch.repeat_interleave(xs, repeats=2, dim=1)` to `xs = xs.unsqueeze(2).repeat(1, 1, 2, 1).flatten(1, 2)` in the forward function.

As for the streaming mode, it should be rewrited.
I'll fix it later, please wait for a while if you are not that urgent.
Thanks!

**Comment by rickychanhoyin** [comment]
thanks, it works for offline conversion

**Comment by yygle** [comment]
https://github.com/wenet-e2e/wenet/pull/1634
Please try this if you are free. Note that the `time_reduction_layer_type` should be `stream` if you want to export model in streaming mode.
