### ISSUE TITLE
how to enable attention decoding in websoket server code

### ISSUE THREAD

**Issue by anjul1008** [wenet-e2e/wenet#1637]
Hi all,
I have tested a trained model with my own dataset and seems working good with attention decoding.
But WER increased by 10% with attention_rescoing decoding.

I want to how much the latency will get increased by enabling attention decoding instead of attention rescoring.
I wanna test latency and results with attention decoding.
I have tried to make changes in the code of wescoket_server.cc to enable it, the logs show it's enabled but i got exactly the same results as attention rescoring. 

Code change:
added `decoder_->Rescoring();` just after line 123 in websocke _server.cc file.
https://github.com/wenet-e2e/wenet/blob/main/runtime/core/websocket/websocket_server.cc#L123

i tried after adding  `decoder_->Rescoring();` after line 145 as well, but got same result as attention rescoring again.
https://github.com/wenet-e2e/wenet/blob/main/runtime/core/websocket/websocket_server.cc#L145

thanks in advance.

**Comment by robin1001** [comment]
`attention`(Autoregressive decoding) is not supported in the runtime, we only do it in python testing.
