### ISSUE TITLE
windows识别没有输出，也没有错报

### ISSUE THREAD

**Issue by zhhl9101** [wenet-e2e/wenet#1640]
python version = 3.8.5

先是安装了runtime
pip install wenetruntime

然后脚本如下：
import sys
import torch
import wenetruntime as wenet

wav_file = sys.argv[1]
decoder = wenet.Decoder(lang='chs')
ans = decoder.decode_wav(wav_file)
print(ans)

执行脚本给定一个audio.wav音频，没有任何输出，也没有报错信息，脚本就结束了
有人知道是为啥吗？我还缺了哪些环境配置吗？

**Comment by robin1001** [comment]
换个机器试试呢

**Comment by zhhl9101** [comment]
你好，我换了3个机器都不行，但是换到linux上就没有问题，所以，是在windows上不支持吗？还是我的环境缺少啥？

**Comment by zhhl9101** [comment]
求教怎么设置？

**Comment by zhhl9101** [comment]
![image](https://user-images.githubusercontent.com/29541186/210496674-1aaf4372-b6b6-401b-b839-fb9545b41ae2.png)

**Comment by zhhl9101** [comment]
音频6s
[wav.zip](https://github.com/wenet-e2e/wenet/files/10348717/wav.zip)

**Comment by zhhl9101** [comment]
@pengzhendong 能有时间给看下问题吗，是我音频有问题，还是我的环境不太对？

**Comment by zhhl9101** [comment]
![image](https://user-images.githubusercontent.com/29541186/211509205-56eea351-5e8c-4215-8519-0de55a4ff5ba.png)
版本和你一致了，但还是不行，想来还是我这边环境有问题，所以除了torch和wenetruntime，还需要啥呢，比如Microsoft Visual C++ 2015-2019 ?

**Comment by zhhl9101** [comment]
没有跑完，直接跳出python环境了，自动退出python环境了不能打印ans
日志和我上次贴出来的是一样的
