### ISSUE TITLE
Quantized model under checkpoint mode performs quite different from the one under jit mode

### ISSUE THREAD

**Issue by PPGGG** [wenet-e2e/wenet#1642]
I have trained an original asr model and i convert it into quantized model in both jit mode` (named asr_quant.zip)` and checkpoint mode `(named asr_quant_checkpoint.pt)`. But the results from the jit mode and the checkpoint mode are quite different.

Quantized model in jit mode:
`test Final result: 甚至出现交易几乎停滞的情况`

Quantized model in checkpoint mode:
`INFO BAC009S0764W0121 ▁LAWS骑钰阐易ISH燕▁CRITIC▁QUANTITY▁GOING骑燕▁MORE鲨ANSISH致▁GOING燕▁GOING燕▁GOING▁DESIRED▁GOING▁BREATH▁CRITIC俏尺骑▁GOING骑▁PERFECTION燕▁GOING燕▁SH燕▁SH谊▁PERFECTION敷唬诊▁SH定▁OVEN▁ORDERS尹O▁IGNORISH▁PRESIDENTO锣OKA▁PERFECTIONISH燕▁EIGHTEEN笛燕何▁PERFECTION▁INFORMEDLAND何骑▁PRETTY燕湿O▁PERFECTION尺O燕汐辆女何燕翼鲨O▁PERFECTION▁FIRST架燕绘翼盘锣▁THIS▁PRETTY▁SONG▁PERFECTION唬▁INFORMED障渲▁EIGHTEEN锣燕咏劈赌盘涉燕轧▁ABSORB汐O▁PERFECTION锣▁EIGHTEEN燕▁SH燕▁SH敷▁PRESIDENT书敷诊唬治唬唯轧辆▁IGNOR▁DOESN▁PERFECTION▁IGNOR洒翼O▁SAVE▁FIRST▁KISS▁PERFECTION锣▁PERFECTION备惭骑企洒▁PERFECTION洒慌▁SH▁CANDLE▁CHIN▁CANDLE企▁CHIN▁LIBERTY锣▁WEATHER▁FIRST▁COUNTRY敷▁CLERK`

**Comment by robin1001** [comment]
We have no idea. Quantized model is for runtime, so it should be in jit mode, why you save it with checkpoint?

**Comment by PPGGG** [comment]
I would like to load the quantized checkpoint to speed up the python inference.

**Comment by xingchensong** [comment]
quantized checkpoint should be used in QAT mode, see https://pytorch.org/docs/stable/quantization.html
