### ISSUE TITLE
More details about RNN-T results.

### ISSUE THREAD

**Issue by lomizandtyd** [wenet-e2e/wenet#1649]
Hi wenet team,

I want to know more details about the [RNN-T result](https://github.com/wenet-e2e/wenet/blob/main/examples/aishell/rnnt/README.md).

Just list the last table here:

| rnnt | ctc | att | greedy | beam | rescoring | fusion |
|------|-----|-----|--------|------|-----------|--------|
| ✔    | ✔   | ✔   |   4.88 | 4.67 |      4.45 |   4.49 |
| ✔    | ✔   |     |   5.56 | 5.46 |       /   |   5.40 |
| ✔    |     | ✔   |   5.03 | 4.94 |      4.87 |    /   |
| ✔    |     |     |   5.64 | 5.59 |       /   |    /   |
|      | ✔   | ✔   |   4.94 | 4.94 |      4.61 |    /   |

My question is:
1. What is ctc beam search used in here? I noticed there's a ctc header inside transducer module. Are you using T's encoder only and CTC header for decoding?
2. Compare with [CTC only result](https://github.com/wenet-e2e/wenet/tree/main/examples/aishell/s0) on Conformer, CTC is better with attenstion rescoring, right?
3. Is "Fusion" decoding with LM? Is that LM a TLG graph or just BPE level LM?

**Comment by Mddct** [comment]
1 there are three losses in wenet-rnnt training style。 So you can also ues ctc + rescoring 

2 

3 fuison here means ctc probs fusion with transducer when decoding ， not with lm

**Comment by ruomingp** [comment]
Do you have Conformer-RNNT results on Librispeech? Do they match the numbers from the Conformer paper? Thanks.

**Comment by robin1001** [comment]
please see https://github.com/wenet-e2e/wenet/tree/main/examples/librispeech/rnnt, the result is far behind the conformer paper. Maybe @yuekaizhang could show more details.

**Comment by yuekaizhang** [comment]
> please see https://github.com/wenet-e2e/wenet/tree/main/examples/librispeech/rnnt, the result is far behind the conformer paper. Maybe @yuekaizhang could show more details.

@ruomingp  This link's model size is about 34Mb. For mid size model in conformer paper, they got 2.3%, 5.0% on librispeech testsets. I have no idea why we can't reach the paper numbers. Maybe they train more epochs or use other techniques. I was wondering if you have some suggestions.

**Comment by ruomingp** [comment]
Thanks for the info! Have you tried Conformer-L?

**Comment by yuekaizhang** [comment]
> Thanks for the info! Have you tried Conformer-L?

Not yet. FYI, https://github.com/k2-fsa/icefall/blob/master/egs/librispeech/ASR/RESULTS.md#large this one has similar size with Conformer-L.

**Comment by lomizandtyd** [comment]
Thank your guys for the information.
