### ISSUE TITLE
公开模型20220506_u2pp_conformer_exp的模型输出中没有字母，全部为中文

### ISSUE THREAD

**Issue by bigcash** [wenet-e2e/wenet#1650]
**Describe the bug**
使用20220506_u2pp_conformer_exp发布的模型进行推理，发现所有的推理结果全部是中文的。看units.txt文件中是有A-Z的字典的，但是如果使用模型推理训练集中的音频时，发现所有结果全部为中文，是做过什么处理吗？因为翻看训练集的label中是有大写字母的token的，但是使用预训练模型推理后确全部为中文了。
示例如下（音频是从训练集中找的）：
utt: Y0000000541_0PBcnpt06bA_S00135
lab: 蔡康永和小S了喜的是呢再也看不到其他工作人员了 
rec: 蔡康有和小鸭死了洗的是呢再也看不到其他工作人员了

**Comment by robin1001** [comment]
因为数据集中的英文很少，所以英文的识别率不好。这个是数据的原因，暂时没有好的办法。
