### ISSUE TITLE
Is Efficient Conformer tested  on any English dataset ?

### ISSUE THREAD

**Issue by jayakrishnanmm** [wenet-e2e/wenet#1652]
Hi ,
I have seen Efficient conformer recipes  for Aishell . Can I use this  recipe  for training English data set as well 
( https://github.com/wenet-e2e/wenet/tree/main/examples/aishell/s0/conf )

**Comment by robin1001** [comment]
Yes! Let we know if you have some problem or you have some results on English dataset.

**Comment by jayakrishnanmm** [comment]
Sure !
