### ISSUE TITLE
关于SqueezeformerEncoder的流式模型训练问题

### ISSUE THREAD

**Issue by shizheng12138** [wenet-e2e/wenet#1654]
在wenet/squeezeformer/encoder.py中SqueezeformerEncoder类的forward方法，chunk_masks通过add_optional_chunk_mask函数生成，在self.use_dynamic_chunk时，生成的chunk_masks的shape为(B,T,T)。
后面执行了
xs_lens = chunk_masks.squeeze(1).sum(1)
以及
xs = xs.masked_fill(~chunk_masks[:, 0, :].unsqueeze(-1), 0.0)
前者计算得到的xs_lens并非是xs的真实长度，后者将导致xs中部分位置被错误的置为0。

按照前后逻辑来看，前者需要修改为
xs_lens = mask_pad.squeeze(1).sum(1)

后者需要修改为
xs = xs.masked_fill(~mask_pad[:, 0, :].unsqueeze(-1), 0.0)

**Comment by robin1001** [comment]
@yygle, please follow the issue.

**Comment by yygle** [comment]
ok, thanks for the issue. I'll check it later.

**Comment by yygle** [comment]
Done.
https://github.com/wenet-e2e/wenet/pull/1664
