### ISSUE TITLE
No final reco result for long audio in non-streaming usage

### ISSUE THREAD

**Issue by wukun2015** [wenet-e2e/wenet#1657]
Hello WeNet team, 

Following https://github.com/wenet-e2e/wenet/blob/main/runtime/binding/python/README.md#non-streaming-usage, i tried a 20 minutes long speech audio with continous_decoding enabled like `wenetruntime.Decoder(lang='chs', continuous_decoding=True)`, but only get empty result as below output: 
```
{
  "nbest" : [{
      "sentence" : ""
    }],
  "type" : "final_result"
}
```

Per [wn_1long.log](https://github.com/wenet-e2e/wenet/files/10397368/wn_1long.log), it seems partial results are good but final result is never there. 

Would you please check this issue ? 

Thank you. 

**Desktop **
 - OS: Win11 Pro
 - Python: 3.9

**Comment by robin1001** [comment]
It is a bug, the result is overrided in non-streaming case. You can switch to streaming usage to get the result, and we will fix it for non-streaming case.

**Comment by robin1001** [comment]
@Mddct do you have time to fix it?

**Comment by xingchensong** [comment]
@wukun2015 hi, seems that the end of wav triggered the endpoint and such endpoint will clear all results, thus the final result is empty.
![image](https://user-images.githubusercontent.com/13466943/220238304-a2e621c2-cc33-4f43-a6ac-fc7854b0c72e.png)

**Comment by wukun2015** [comment]
Hello Xingchen,

When will this bug be fixed please ?

Thank you.
________________________________
