### ISSUE TITLE
forward_chunk_by_chunk slow

### ISSUE THREAD

**Issue by zelabean** [wenet-e2e/wenet#1663]
Thanks for providing nice code!

I want to do evaluation in python with streaming fasion.

However, it seems that the forward_chunk_by_chunk function does not support batch.

Even if the batch size is set to 1, it seems that the forward_chunk_by_chunk function runs slower than the forward function.

can someone help?

**Comment by robin1001** [comment]
Yes, forward_chunk_by_chunk is used to simulated the streaming decoding of speech recognition. Absolutely, it's much slower than foward since forward is just called once for each utterance and forward_chunk is called several times for each utterance.
