### ISSUE TITLE
Support for multilingual model

### ISSUE THREAD

**Issue by HenryYuen128** [wenet-e2e/wenet#1665]
**Is your feature request related to a problem? Please describe.**
Is it possible to train a model which can recognize words in English stead of characters? The vocab file seems to only contain characters.

**Describe the solution you'd like**
Fine-tune a model that can recognize English words and Chinese.

**Comment by robin1001** [comment]
Typically char or BPE is used as modeling unit for English. If the vocab is limited(less than 20000), you can try to use words, otherwise it's too big to train.
