### ISSUE TITLE
ImportError: DLL load failed while importing _wenet: 找不到指定的模块。

### ISSUE THREAD

**Issue by MistEO** [wenet-e2e/wenet#1667]
**Describe the bug**

```python
(voice) PS E:\XXXX> python src/main.py
Traceback (most recent call last):
  File "src/main.py", line 3, in <module>
    import wenetruntime as wenet
  File "E:\ENV\anaconda\envs\voice\lib\site-packages\wenetruntime\__init__.py", line 1, in <module>
    from .decoder import Decoder  # noqa
  File "E:\ENV\anaconda\envs\voice\lib\site-packages\wenetruntime\decoder.py", line 17, in <module>
    import _wenet
ImportError: DLL load failed while importing _wenet: 找不到指定的模块。
>>>
```

**To Reproduce**

```bash
conda create -n voice python=3.8
conda activate voice
python -m pip install wenetruntime
python
>>> import wenetruntime
```

I tried this on Windows 10 and Windows 11 and got the same error. I tried uninstalling and reinstalling wenetruntime with pip, still doesn't work.

**Screenshots**

In order to take a screenshot, I recreated a virtual environment called voice2, the result is as follows

![image](https://user-images.githubusercontent.com/18511905/214692470-855dec4d-0418-49b3-946a-e25e13ca0691.png)

**Desktop (please complete the following information):**

 - Win10 x64 and Win11 x64, same error

**Additional context**
https://github.com/wenet-e2e/wenet/issues/1180 I found a similar question and tried to follow his way out, but it didn't work.

![image](https://user-images.githubusercontent.com/18511905/214693544-bfe15b3f-f41a-4ed8-a3d4-f789412ec719.png)
![image](https://user-images.githubusercontent.com/18511905/214693699-f4554411-c480-47f8-b941-8c768ee64118.png)

**Comment by MistEO** [comment]
问题解决，除了 wenetruntime, 还需要再装一个 wenet （但是文档上没写，最好可以补充一下

```bash
python -m pip install wenet
```

**Comment by LRY8686** [comment]
it didn't work too

**Comment by KongKanShan** [comment]
> ```shell
> wenet
> ```

where did you found this package? I cant find it in pip

**Comment by czy20000902** [comment]
> > ```shell
> > wenet
> > ```
> 
> where did you found this package? I cant find it in pip

https://pypi.tuna.tsinghua.edu.cn/packages/18/90/e2677c94896a1fcb96011e4c57b0607e0b9d34cc6797724583e5be6fb52e/wenet-1.0.6-cp39-cp39-win_amd64.whl
