### ISSUE TITLE
Run rnnt recipe get shape error.

### ISSUE THREAD

**Issue by zxcd** [wenet-e2e/wenet#1668]
**Describe the bug**
我在使用examples/librispeech/rnnt进行推理时，运行step[-1-3]生成字典后，加载Readme中的avg_10.pt时，出现了shape error。
![图片](https://user-images.githubusercontent.com/9251256/215238080-c174100c-b269-4afb-9591-b8e5a59f792e.png)

**Comment by robin1001** [comment]
@Mddct @yuekaizhang please follow the issue.

**Comment by zxcd** [comment]
The same problem still occurs after replacing the dictionary.
