### ISSUE TITLE
LibTorch get Chinese garbled characters

### ISSUE THREAD

**Issue by DaobinZhu** [wenet-e2e/wenet#1672]
Hello, when I used LibTorch to decode (decoder_main), I encountered the problem of Chinese garbled characters. I use the data set is Aishell-1, and unit_table is **/wenet/examples/Aishell s0/ data/dict/lang_char.txt**. I generated final.zip after stage 6 of run.sh, using the same dictionary **/wenet/examples/Aishell s0/ data/dict/lang_char.txt**.

However, the error log is as follows:

I0130 20:15:18.808750 186759 asr_decoder.cc:104] Required 67 get 67
I0130 20:15:18.869403 186759 asr_decoder.cc:200] Partial CTC result <is>妒甫喻侠徇螳淳甫茵脂匀娠铃</is>
I0130 20:15:18.869508 186759 asr_decoder.cc:104] Required 64 get 64
I0130 20:15:18.928126 186759 asr_decoder.cc:200] Partial CTC result <is>妒甫喻侠徇螳淳甫茵脂匀娠铃涝糙幻嗽貌殃燊瞻涤铃草喽读</is>
I0130 20:15:18.928225 186759 asr_decoder.cc:104] Required 64 get 64
I0130 20:15:18.983222 186759 asr_decoder.cc:200] Partial CTC result <is>妒甫喻侠徇螳淳甫茵脂匀娠铃涝糙幻嗽貌殃燊瞻涤铃草喽读矩轩寨季咎岂乙疤舛烂览兹烂丑泔</is>
I0130 20:15:18.983327 186759 asr_decoder.cc:104] Required 64 get 64
I0130 20:15:19.044641 186759 asr_decoder.cc:200] Partial CTC result <is>妒甫喻侠徇螳淳甫茵脂匀娠铃涝糙幻嗽貌殃燊瞻涤铃草喽读矩轩寨季咎岂乙疤舛烂览兹烂丑泔秽掩列聘惨妃喽泌推钛殃骋伯屯递褒</is>
I0130 20:15:19.044744 186759 asr_decoder.cc:104] Required 64 get 64
I0130 20:15:19.111181 186759 asr_decoder.cc:200] Partial CTC result <is>妒甫喻侠徇螳淳甫茵脂匀娠铃涝糙幻嗽貌殃燊瞻涤铃草喽读矩轩寨季咎岂乙疤舛烂览兹烂丑泔秽掩列聘惨妃喽泌推钛殃骋伯屯递褒溧喇畜酌咎岂螺鄙忑鄙弓雍矣茵</is>
I0130 20:15:19.111260 186759 asr_decoder.cc:104] Required 64 get 25
I0130 20:15:19.147778 186759 asr_decoder.cc:200] Partial CTC result <is>妒甫喻侠徇螳淳甫茵脂匀娠铃涝糙幻嗽貌殃燊瞻涤铃草喽读矩轩寨季咎岂乙疤舛烂览兹烂丑泔秽掩列聘惨妃喽泌推钛殃骋伯屯递褒溧喇畜酌咎岂螺鄙忑鄙弓雍矣镑惠</is>

**Comment by xingchensong** [comment]
python recognize.py的结果正常吗？

**Comment by DaobinZhu** [comment]
> python recognize.py的结果正常吗？

utt: BAC009S0916W0494
WER: 0.00 % N=11 C=11 S=0 D=0 I=0
lab: 存 在 无 法 如 期 还 贷 的 风 险 
rec: 存 在 无 法 如 期 还 贷 的 风 险 


utt: BAC009S0916W0495
WER: 15.38 % N=13 C=11 S=2 D=0 I=0
lab: 这 令 被 贷 款 的 员 工 们 寝 食 难 安 
rec: 这 令 被 贷 款 的 员 工 们 请 时 难 安 

===========================================================================

Overall -> 4.89 % N=104765 C=99736 S=4807 D=222 I=97
Mandarin -> 4.89 % N=104762 C=99736 S=4804 D=222 I=97
Other -> 100.00 % N=3 C=0 S=3 D=0 I=0

===========================================================================
在生成的文件里看是正常的

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/wenet/blob/main/docs/pretrained_models.en.md 试一下这里下载的aishell模型

**Comment by DaobinZhu** [comment]
> https://github.com/wenet-e2e/wenet/blob/main/docs/pretrained_models.en.md 试一下这里下载的aishell模型

预训练模型可以正常显示

**Comment by xingchensong** [comment]
先别直接用下载的zip，先下载预训练的ckpt，用你的本地代码导出这个ckpt对应的zip，然后试试？（确保本地代码是正确的）

**Comment by DaobinZhu** [comment]
> 先别直接用下载的zip，先下载预训练的ckpt，用你的本地代码导出这个ckpt对应的zip，然后试试？（确保本地代码是正确的）

导出后结果却是是正常的

**Comment by xingchensong** [comment]
那这个确实比较奇怪了，我也没啥想法了

**Comment by DaobinZhu** [comment]
我测试了我自己的final.pt也是正常的，看来问题出自平均模型这部分，谢谢大佬

**Comment by DaobinZhu** [comment]
平均模型后可以用python接口求cer，但是部署以后就不能用了

**Comment by DaobinZhu** [comment]
似乎和train.yaml有关系，我这个代码是之前跑的，train.yaml有71行，而下载的预训练模型里的yaml有78行，我用之前的版本重新编译一下

**Comment by DaobinZhu** [comment]
找到错误的原因了，我这个模型是2021年的远古版本，但是我编译是用的最新的代码，我拿之前的模型放到新代码这里进行导出zip格式的模型就会中文乱码，我在远古代码那里导出然后用新代码解码就正常了

**Comment by code1edoc** [comment]
> 找到错误的原因了，我这个模型是2021年的远古版本，但是我编译是用的最新的代码，我拿之前的模型放到新代码这里进行导出zip格式的模型就会中文乱码，我在远古代码那里导出然后用新代码解码就正常了

我也遇到了相同问题，我将预训练的aishell,  @aishell2的checkpoint使用export_jit.py去解码之后，用得到的final.zip去识别都得到中文乱码；我自己也使用aishell的数据集从头使用提供的run.sh脚本来训练了一个模型，导出后识别结果与预训练的aishell checkpoint一样都是乱码。而wenetspeech的checkpoint导出之后有正常的识别结果。是aishell, aishell2的训练脚本run.sh中哪里出现问题了吗？ @DaobinZhu 我想要在预训练模型的基础上再训练，但是不知道aishell的run.sh脚本哪里出现了问题？
