### ISSUE TITLE
runtime decoding 32bit wave error 

### ISSUE THREAD

**Issue by duj12** [wenet-e2e/wenet#1674]
**Describe the bug**
When I use runtime code to decoding a 32bit wave, the tokens are almost missing, but when i convert these waves into 16bit waves, the decoding results make sense.

**To Reproduce**
run:
 `decoder_main --wav_path ./TEST_MEETING_T0000000000_S00000.16bit.wav --model_path exp/conformer_wavaug/final.zip --unit_path data/dict_bpe/lang_char.txt
`

we can get the normal result,
`
test 咱们的第八层是属于租的人家的
`

The wave is 
[TEST_MEETING_T0000000000_S00000.16bit.wav.zip](https://github.com/wenet-e2e/wenet/files/10544565/TEST_MEETING_T0000000000_S00000.16bit.wav.zip)

Then we decode the 32bit wave 
[TEST_MEETING_T0000000000_S00000.32bit.wav.zip](https://github.com/wenet-e2e/wenet/files/10544577/TEST_MEETING_T0000000000_S00000.32bit.wav.zip)

` decoder_main --wav_path ./TEST_MEETING_T0000000000_S00000.32bit.wav --model_path exp/conformer_wavaug/final.zip --unit_path data/dict_bpe/lang_char.txt
`

We get:
`
test 醉
` 

You can use your own model(WenetSpeech Pretrained model is OK) to verify these result. 
I'm not sure if there are some bugs in https://github.com/wenet-e2e/wenet/blob/main/runtime/core/frontend/wav.h

**Comment by robin1001** [comment]
Only 16 bits is supported in WeNet.
