### ISSUE TITLE
Illegal value of gflags define options

### ISSUE THREAD

**Issue by FionaZZ92** [wenet-e2e/wenet#1675]
**Describe the bug**
ERROR: illegal value '0.99 ' specified for double flag 'blank_skip_thresh'
ERROR: illegal value '16 ' specified for int32 flag 'chunk_size'
ERROR: illegal value '40 ' specified for int32 flag 'thread_num'

**To Reproduce**
Build project on Ubuntu 20.04 or 18.04
gflags 2.2.2

**Screenshots**
<img width="825" alt="Untitled" src="https://user-images.githubusercontent.com/44352144/216003622-646bd927-0b68-4fdb-a714-1ad2aae30026.png">

**Comment by robin1001** [comment]
You should quote decoder_main and it's parameters with '', otherwise they are regarded as the parameter of numactl.

**Comment by FionaZZ92** [comment]
> You should quote decoder_main and it's parameters with '', otherwise they are regarded as the parameter of numactl.

It's not about quotation marks, if remove the numactl and directly to call decoder_main, same issue. And I found this probably only on my Ubuntu machine, not on CentOS.

**Comment by FionaZZ92** [comment]
Should be caused by gflags ,I tried to reinstall system gflags, then the problem disappeared.
