### ISSUE TITLE
使用jit导出模型后效果变得很差

### ISSUE THREAD

**Issue by DaobinZhu** [wenet-e2e/wenet#1676]
通过export_jit导出模型为.zip格式后，使用label_checker测出的CER非常大，

Overall -> 27.58 % N=104765 C=82012 S=20634 D=2119 I=6146
Mandarin -> 27.58 % N=104762 C=82012 S=20633 D=2117 I=6146
Other -> 100.00 % N=3 C=0 S=1 D=2 I=0

但是checkpoint测出来只有四点多，请问这是怎么回事？

**Comment by robin1001** [comment]
label checker 不是用来做解码的，请使用 decoder_main

**Comment by DaobinZhu** [comment]
好的，谢谢彬哥



---原始邮件---
发件人: "Binbin ***@***.***&gt;
发送时间: 2023年2月8日(周三) 中午11:21
收件人: ***@***.***&gt;;
抄送: "Daobin ***@***.******@***.***&gt;;
主题: Re: [wenet-e2e/wenet] 使用jit导出模型后效果变得很差 (Issue #1676)




 
label checker 不是用来做解码的，请使用 decoder_main

**Comment by DaobinZhu** [comment]
彬哥这个label checker作用是什么呀？



---原始邮件---
发件人: "Binbin ***@***.***&gt;
发送时间: 2023年2月8日(周三) 中午11:21
收件人: ***@***.***&gt;;
抄送: "Daobin ***@***.******@***.***&gt;;
主题: Re: [wenet-e2e/wenet] 使用jit导出模型后效果变得很差 (Issue #1676)




 
Closed #1676 as completed.

**Comment by robin1001** [comment]
做标注错误检测的，详见 WenetSpeech 的论文。

**Comment by DaobinZhu** [comment]
明白了，谢谢彬哥



---原始邮件---
发件人: "Binbin ***@***.***&gt;
发送时间: 2023年2月8日(周三) 下午2:14
收件人: ***@***.***&gt;;
抄送: "Daobin ***@***.******@***.***&gt;;
主题: Re: [wenet-e2e/wenet] 使用jit导出模型后效果变得很差 (Issue #1676)




 
做标注错误检测的，详见 WenetSpeech 的论文。

**Comment by code1edoc** [comment]
> 通过export_jit导出模型为.zip格式后，使用label_checker测出的CER非常大，
> 
> Overall -> 27.58 % N=104765 C=82012 S=20634 D=2119 I=6146 Mandarin -> 27.58 % N=104762 C=82012 S=20633 D=2117 I=6146 Other -> 100.00 % N=3 C=0 S=1 D=2 I=0
> 
> 但是checkpoint测出来只有四点多，请问这是怎么回事？

请问解决了导出后的.zip模型识别效果极差的问题吗？我也遇到了相似问题，跟着tutorial_aishell进行到第六步export_jit的时，导出的.zip模型识别效果很差(几乎乱识别)的情况吗？(但是avg_30.pt在第五步wer能达到4.6%)
