### ISSUE TITLE
cuda out of memory

### ISSUE THREAD

**Issue by alongwithyou** [wenet-e2e/wenet#1678]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.81 GiB (GPU 1; 39.59 GiB total capacity; 34.83 GiB already allocated; 1.69 GiB free; 35.63 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by alongwithyou** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.81 GiB (GPU 1; 39.59 GiB total capacity; 36.30 GiB already allocated; 1004.19 MiB free; 36.33 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by alongwithyou** [comment]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.81 GiB (GPU 1; 39.59 GiB total capacity; 34.83 GiB already allocated; 1.69 GiB free; 35.63 GiB reserved in total by PyTorch) 
If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by DaobinZhu** [comment]
调小batch size
