### ISSUE TITLE
building TLG

### ISSUE THREAD

**Issue by jayakrishnanmm** [wenet-e2e/wenet#1680]
I want to use an external LM (G.fst) to gigaspeech pre-trained model.  I am looking at librispeech example for this.
(https://wenet.org.cn/wenet/tutorial_librispeech.html) . However  , for the L (lexicon) part, I see that it still  uses  the  Hybrid model lexicon file. (words -> phonemes)  See below 
  echo "build lexicon..."
  tools/fst/prepare_dict.py $unit_file ${lm}/librispeech-lexicon.txt \
    $lexicon $bpemodel.model
  echo "lexicon saved as '$lexicon'"
This is confusing. Does  it mean, I should have lexicon (word-> phoneme), if I want to use  wenet e2e  with an LM ?
If yes, where can  I get gigaspeech lexicon ?

**Comment by robin1001** [comment]
`word -> phoneme` is not requreid. tools/fst/prepare_dict.py will separate the word into word pieces according to BPE model.

**Comment by LRY1994** [comment]
where can I get the words list ?  I want to know too
