### ISSUE TITLE
how to create force alignment file

### ISSUE THREAD

**Issue by zyjcsf** [wenet-e2e/wenet#1681]
Hi，I do some experiments about trimtail recently，and I found the wenet has offered  latency metrics scripts in tools. Thank you very much. And I have a question about how to create the char-level force alignment file by using kaldi model ( I do force alignment using kaldi only get the word-level)?  What is the format of the alignment file？Thank you very much.

**Comment by xingchensong** [comment]
[字体.AIshell对齐.使用脚本.zip](https://github.com/wenet-e2e/wenet/files/10681093/AIshell.zip)

**Comment by zyjcsf** [comment]
> [字体.AIshell对齐.使用脚本.zip](https://github.com/wenet-e2e/wenet/files/10681093/AIshell.zip)

Great! Thank you very much. By the way, if I want to get the alignment file of my own dataset, how can I do? Thank you.

**Comment by xingchensong** [comment]
![image](https://user-images.githubusercontent.com/13466943/217705927-bd7881ff-03f7-4dc4-bbe6-8c2e5d803b69.png)

you can try this

**Comment by zyjcsf** [comment]
Thank you very much.
