### ISSUE TITLE
Request for U2++ Conformer RNNT model download link in the aishell/rnnt and aishell2/rnnt example

### ISSUE THREAD

**Issue by cyaaronk** [wenet-e2e/wenet#1682]
Hi there,

There are results for U2++ Conformer RNNT in the aishell/rnnt and aishell2/rnnt example.
However, there is no download link to download and test the models.

May I have a copy of the model so we can test it for our ASR system?

Thank you for your support.

**Comment by robin1001** [comment]
@yuekaizhang @Mddct do you have public RNN-T models of aishell?

**Comment by yuekaizhang** [comment]
I only have librispeech models. Here https://huggingface.co/yuekai/wenet-asr-librispeech-conformer-transducer-mtl/tree/main
