### ISSUE TITLE
How to use the model you have trained and use a paragraph for reasoning and prediction

### ISSUE THREAD

**Issue by sun-rabbit** [wenet-e2e/wenet#1684]
I have trained my own model, but I don't know where to find the relevant tutorial for me to reason and predict. I just started to contact wenet. Can you give me some relevant instructions for my own reasoning and prediction。thanks

**Comment by robin1001** [comment]
If you just want to do prediction offline to verify your model, follow the test stage in examples.
If you want to do it in pure python but with simplified pipeline, just use our python binding https://github.com/wenet-e2e/wenet/tree/main/runtime/binding/python
If you want to deploy it in production, please see https://github.com/wenet-e2e/wenet/tree/main/runtime/. We support various  platforms and OS such as android, ios, x86.

**Comment by sun-rabbit** [comment]
hello，ios demo, [link](https://github.com/wenet-e2e/wenet/blob/main/runtime/TODO)。What should I do when I click in and 404 appears

**Comment by sun-rabbit** [comment]
hello，Is test stage in examples the fifth step of run.sh？I can't find where this test is
