### ISSUE TITLE
/encoder/encoders.0/self_attn/Add_2: right operand cannot broadcast on dim 3 LeftShape: {1,8,5426,5426}, RightShape: {1,8,5426,5000}

### ISSUE THREAD

**Issue by YaboSun** [wenet-e2e/wenet#1686]
**Describe the bug**
I used the export_onnx_gpu.py script to convert the model to onnx type and successfully deployed it using the Triton Server, but there was a bug when I call the grpc port

**To Reproduce**
I follow this [README](https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/README.md) and pruduce in step3 

**Screenshots**
![image](https://user-images.githubusercontent.com/16696936/217735692-80eee18a-b861-48aa-be85-de937edd0789.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Additional context**
Wenet model dim is 512 and I use the offline model_repo

**Comment by YaboSun** [comment]
torch==1.13.0  python==3.7.10 
triton server image:nvcr.io/nvidia/tritonserver:22.12-py3

**Comment by goreng2** [comment]
I got the same error.

In my case,
```
2023-02-20 05:09:19.021330918 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running Add node. Name:'Add_154' Status Message: Add_154: right operand cannot broadcast on dim 3 LeftShape: {1,8,6544,6544}, RightShape: {1,8,6544,5000}
```

**Comment by yuekaizhang** [comment]
> I got the same error.
> 
> In my case,
> 
> ```
> 2023-02-20 05:09:19.021330918 [E:onnxruntime:, sequential_executor.cc:369 Execute] Non-zero status code returned while running Add node. Name:'Add_154' Status Message: Add_154: right operand cannot broadcast on dim 3 LeftShape: {1,8,6544,6544}, RightShape: {1,8,6544,5000}
> ```

What's the audio length in your test case? Using audio less than 20s should be okay.

**Comment by goreng2** [comment]
@yuekaizhang Thanks for your answer.
 
You're right.
When I used audio file over 20s, The Error raise. The opposite is not

Well.. so.. wenet's gpu runtime can't ASR for audiofile over 20s?

I should split my test audio file into under 20s?

**Comment by yuekaizhang** [comment]
> @yuekaizhang Thanks for your answer.
> 
> You're right. When I used audio file over 20s, The Error raise. The opposite is not
> 
> Well.. so.. wenet's gpu runtime can't ASR for audiofile over 20s?
> 
> I should split my test audio file into under 20s?

Yes. For long audios, you should split it using VAD module or other methods.
