### ISSUE TITLE
Customize TLG decoding for phoneme-level Lip Reading task

### ISSUE THREAD

**Issue by xiabingquan** [wenet-e2e/wenet#1687]
**Is your feature request related to a problem? Please describe.**
Wenet supports TLG decoding, but users have to use the whole wenet framework to train models and the framework only supports ASR. In my case, I trained a phoneme-level Lip Reading (pretty similar with ASR. The only difference is that the input is a sequence of lip images instead of fbank features or raw waves) model with my own codebase, and I want to use the TLG decoding framework to convert the decoded phonemes into words. The decoding of phonemes relies on CTC prefix beam search.
**Describe the solution you'd like**
I read the source code of the recipe of LibriSpeech, and found that the HLG decoding is directly integrated within libtorch runtime since it relies on `decoder_main` as shown in the code snippet below. It seems that it's impossible to directly use the HLG decoding framework in my case except for modifying the C++ source code. Is there any other solutions in went? Thanks!
https://github.com/wenet-e2e/wenet/blob/0c46d4d91547336931f2d39006f2a3fdd7bd9bb4/tools/decode.sh#L65-L77

**Comment by robin1001** [comment]
There are two ways to do it in WeNet.
1. python training + TLG building + `c++ runtime(decode_main)`, as your description above.
2. pure python with k2,  here is an example https://github.com/wenet-e2e/wenet/blob/main/examples/aishell/s0/run.sh#L242.

If production deploy is not required, the second way is recommended.
