### ISSUE TITLE
HTTP方式部署，语音文件过大无法解析

### ISSUE THREAD

**Issue by qq1728720837** [wenet-e2e/wenet#1689]
可以添加一个可配置参数来设置可接受的文件大小的最大值吗。

**Comment by robin1001** [comment]
Typically, we limit the audio in 5 hours. please see https://www.xfyun.cn/doc/asr/lfasr/API.html#%E6%8E%A5%E5%8F%A3%E8%AF%B4%E6%98%8E.

![image](https://user-images.githubusercontent.com/6036624/218235013-caf53cf9-ec86-4341-b4a2-ee3c70ce9afd.png)
