### ISSUE TITLE
Training a word based Mandarin model

### ISSUE THREAD

**Issue by serendipity24** [wenet-e2e/wenet#1692]
Hi,

We are trying to develop and analyse a word based model for Mandarin language using the wenetspeech/ recipe and data. Can you please let us know what are the changes to be made to the recipe if we want to preserve the word boundaries at the time of training? 

Since the lang_char.txt created for the same text file with and without boundaries turns out to be the same, we are not sure where exactly the information regarding word boundaries is saved. Please provide pointers on how we can proceed.

Thank You.

**Comment by xingchensong** [comment]
u can also refer to this: https://github.com/pengzhendong/welm/blob/master/run.sh#L66-L73

**Comment by robin1001** [comment]
You can split the label into words with space, and add `split_with_space: true` in your training config.

please refer timit recipe in which phone is used as model unit and the label is splited into phones with space.  https://github.com/wenet-e2e/wenet/blob/main/examples/timit/conf/train_conformer.yaml#L38

**Comment by serendipity24** [comment]
Thank You. We will train with split_with_space: true setting in the train config and update regarding the performance.
