### ISSUE TITLE
gigaspeech  LM  notworking with gigaspeech U2PP model

### ISSUE THREAD

**Issue by jayakrishnanmm** [wenet-e2e/wenet#1695]
I am using pre-trained/gigaspeech/20210728_u2pp_conformer_libtorch as  acoustic model  and  want to use gigaspeech LM from https://huggingface.co/wgb14/gigaspeech_lm while decoding. I built TLG.fst using  the instructions from https://github.com/wenet-e2e/wenet/blob/main/docs/tutorial_librispeech.md (Stage 7)  I have used  the  lexicon from the same source  and  using a bpe model to split it. 

./build/bin/decoder_main \
        --chunk_size -1 \
        --wav_path $wav_path    \
        --model_path $model     \
        --unit_path $units      \
        --rescoring_weight $rescoring_weight \
        --ctc_weight $ctc_weight \
        --reverse_weight $reverse_weight \
        $wfst_decode_opts \
        --result  $result/youtube.txt   &> $result/out.log

Howver, I am getting  a  totally wrong  junk text, onlly  few words  are meaningful.   When I decode the model  without LM, it is ok. What is happening here ?

**Comment by robin1001** [comment]
Did you get the right output when LM is not used?

**Comment by jayakrishnanmm** [comment]
Yes.

**Comment by robin1001** [comment]
There must be some error when you building the FST. please make sure the modeling units of gigaspeech model(the model you download) is used for building the FST.

**Comment by xingchensong** [comment]
This may help you https://github.com/wenet-e2e/wenet/issues/1673

**Comment by jayakrishnanmm** [comment]
Thanks. Now  working

**Comment by naomibb** [comment]
May I ask how did you work in the end? and must use the bpe model. where can i get the bpe model? thanks

**Comment by jayakrishnanmm** [comment]
The  bpe  model  is  trained  using the train text. You refer  the  run.sh  under  examples/gigaspeech/s0
