### ISSUE TITLE
python wenetruntime  构建服务端api

### ISSUE THREAD

**Issue by hzfei** [wenet-e2e/wenet#1696]
想在服务器上用python wenetruntime +sanic部署个http接口，如果是用streaming方式解码，看到decode有一个参数last。可是在多用户请求的时候，怎么知道是哪个用户的last?

**Comment by robin1001** [comment]
1. 多用户，不同用户的请求是独立管理的。
2. 用户发的最后一包语音时， last 就是 true。

**Comment by hzfei** [comment]
服务端只能实例一个decoder对象。面对不同用户的请求，A用户发了(wav_a_1,False) ；B用户发了（wav_b_2,True）。这时候decoder分得清A，B吗？

**Comment by xingchensong** [comment]
建议使用c++ runtime搭服务，天然支持多线程和线程隔离（用户隔离）

**Comment by hzfei** [comment]
多谢
