### ISSUE TITLE
Feature Request: Expose acoustic_scale and length_penalty in python bindings

### ISSUE THREAD

**Issue by Jacob-Bishop** [wenet-e2e/wenet#1697]
**Is your feature request related to a problem? Please describe.**
I'm using wenet via the python bindings, and just experimented with adding a LM. As other issues have noted, I've run into problems with increased deletions. Other issues suggest the solution is adjustments to acoustic_scale and length_penalty parameters. Unfortunately, neither of these appear to be available via the python bindings.

**Describe the solution you'd like**
Add python bindings for acoustic_scale and length_penalty parameters in decoder.

**Comment by robin1001** [comment]
Yes, a lot of parameters are required to be exposed when we want to do tuning work in details. @Mddct is working on this job.

**Comment by xingchensong** [comment]
we should also take this into account https://github.com/wenet-e2e/wenet/issues/1482
