### ISSUE TITLE
May I ask how to construct the lexicon.txt of LM?

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#1698]
Hi, I see that aishell is built with the built-in lexicon.txt, and aishell2 is built with DaCiDian. What principles should be built on in practical applications?

**Comment by robin1001** [comment]
We just use the lexicon.txt to get all the words involved in LM.

You can build your lexicon:
* Chinese: just split Chinese words into chars.
* English: split English words to word pieces according to your BPE model.

Here are some examples:

```
中国梦 中 国 梦
apple _app le
```

**Comment by xingchensong** [comment]
Hi, both pre-built lexicon.txt (aishell-1) and DaCiDian (aishell-2) are maps used for mapping words to **phonemes**, i.e., 

```
中国梦 ZHONG_1 GUO_2 MENG_4
```

However, to construct LM, we need to map words to **chars**, i.e., 

```
中国梦 中 国 梦
```

thus we are not actually using pre-built lexicon.txt  or DaCiDian, instead, we just extract words (first row in those files) and split words as @robin1001 mentioned:

see https://github.com/wenet-e2e/wenet/blob/main/tools/fst/prepare_dict.py

and line34 https://github.com/wenet-e2e/wenet/blob/main/tools/fst/prepare_dict.py#L34

**Comment by srdfjy** [comment]
@robin1001 @xingchensong thanks.

**Comment by srdfjy** [comment]
Hi

May I ask why the apple here is split into _app and le? My understanding is that apple is a word and should not be split, such as the following example:

`apple _apple`
`redapple _red apple`
`minicooper _mini cooper`

**Comment by srdfjy** [comment]
@pengzhendong THX!
