### ISSUE TITLE
some requests about WenetSpeech

### ISSUE THREAD

**Issue by 1633347510** [wenet-e2e/wenet#1703]
Thank you for providing such a good architecture in dealing with ASR problems. 

i have some questions related to the WenetSpeech dataset:
 
1: Could you provide me with the config files of Wenet with the transformer-encoder in the examples of WenetSpeech? 

2: Would you public the pre-trained model based on transformer-encoder of WenetSpeech in the future?

**Comment by xingchensong** [comment]
1. you may refer to https://github.com/wenet-e2e/wenet/blob/main/examples/aishell/s0/conf/train_u2%2B%2B_transformer.yaml
2. no plan
