### ISSUE TITLE
The web runtime in Windows Runtime will report an error

### ISSUE THREAD

**Issue by llleohk** [wenet-e2e/wenet#1704]
![微信图片_20230223120052](https://user-images.githubusercontent.com/99810710/220818619-d1a431c1-21eb-4e6c-8d87-893c381a1752.png)

**Comment by cdliang11** [comment]
Hi, for Windows and Linux, wenetruntime depends on torch. Please install and import the same version torch as wenetruntime.

**Comment by llleohk** [comment]
> 

Thank you for your answer. I will reinstall it

**Comment by llleohk** [comment]
> Hi, for Windows and Linux, wenetruntime depends on torch. Please install and import the same version torch as wenetruntime.

I have reinstalled the same version, but there is still this error

**Comment by cdliang11** [comment]
Fixed. see https://github.com/wenet-e2e/wenet/pull/1705.

**Comment by llleohk** [comment]
> Fixed. see #1705.

Really solved, thank you very much
