### ISSUE TITLE
How to output character level timestamp in windows environment？I need this information. Thanks

### ISSUE THREAD

**Issue by 1311004771** [wenet-e2e/wenet#1706]
![image](https://user-images.githubusercontent.com/93832987/221109913-e04d47cd-6a67-4996-9c08-d5cf95a51a2f.png)

E:\wenet-main\runtime\libtorch\build\bin\Debug>decoder_main.exe   --chunk_size -1 --wav_path E:/test-wav/BAC009S0723W0476.wav --model_path E:/audio_editor/20220506_u2pp_conformer_libtorch/final.zip --unit_path E:/audio_editor/20220506_u2pp_conformer_libtorch/units.txt
test 蒋高明的弘毅生态农场在官网上的简介

Only the final result is returned.

**Comment by xingchensong** [comment]
I think only websocket_server returns timestamps, right ? @pengzhendong

**Comment by 1311004771** [comment]
Thank you,
You mean to add r.word_pieces in buffer can realize the corresponding time stamp of output characters under windows environment? @pengzhendong 

https://github.com/wenet-e2e/wenet/blob/main/runtime/core/bin/decoder_main.cc#L118
