### ISSUE TITLE
Check failed: start_state != fst::kNoStateId

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#1707]
Hi, when I tried to decode with tlg, an error occurred. I checked the Issue list and found no similar problems. What is the possible reason for this error?

cmd
---
/wenet/runtime/libtorch/build/bin/decoder_main \
  --model_path final_quant.zip \
  --unit_path lang_char.txt \
  --wav_scp test.scp \
  --sample_rate 8000 \
  --thread_num 8 \
  --num_threads 8 \
  --lowercase \
  --chunk_size -1 \
  --num_left_chunks -1 \
  --ctc_weight 0.3 \
  --reverse_weight 0.3 \
  --result result.txt \
  --beam 15 \
  --fst_path lang_test/TLG.fst \
  --dict_path lang_test/words.txt \
  --lattice_beam 7.5 \
  --max_active 7000 \
  --min_active 200 \
  --acoustic_scale 1.0 \
  --blank_skip_thresh 0.98 \
  --length_penalty 0.0 \
  --rescoring_weight 1.0

err
---
F0224 10:32:04.923169 150268 lattice-faster-decoder.cc:74] Check failed: start_state != fst::kNoStateId 
*** Check failure stack trace: ***
    @     0x7fcc07eb06ec  google::LogMessage::Fail()
    @     0x7fcc07eb0634  google::LogMessage::SendToLog()
    @     0x7fcc07eaff75  google::LogMessage::Flush()
    @     0x7fcc07eb3794  google::LogMessageFatal::~LogMessageFatal()
    @     0x55a77e2b4bbe  kaldi::LatticeFasterDecoderTpl<>::InitDecoding()
    @     0x55a77e24ba94  wenet::CtcWfstBeamSearch::Reset()
    @     0x55a77e24b92b  wenet::CtcWfstBeamSearch::CtcWfstBeamSearch()
    @     0x55a77e16276d  wenet::AsrDecoder::AsrDecoder()
    @     0x55a77e140d13  decode()
    @     0x55a77e16217d  std::__invoke_impl<>()
    @     0x55a77e161f1a  std::__invoke<>()
    @     0x55a77e161c21  _ZNSt5_BindIFPFvSt4pairISsSsEES1_EE6__callIvJEJLm0EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @     0x55a77e1616cd  std::_Bind<>::operator()<>()
    @     0x55a77e160f8f  std::__invoke_impl<>()
    @     0x55a77e160acf  std::__invoke<>()
    @     0x55a77e15fa35  _ZZNSt13__future_base11_Task_stateISt5_BindIFPFvSt4pairISsSsEES3_EESaIiEFvvEE6_M_runEvENKUlvE_clEv
    @     0x55a77e16179c  _ZNKSt13__future_base12_Task_setterISt10unique_ptrINS_7_ResultIvEENS_12_Result_base8_DeleterEEZNS_11_Task_stateISt5_BindIFPFvSt4pairISsSsEESA_EESaIiEFvvEE6_M_runEvEUlvE_vEclEv
    @     0x55a77e161040  _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_EZNS1_11_Task_stateISt5_BindIFPFvSt4pairISsSsEESD_EESaIiEFvvEE6_M_runEvEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @     0x55a77e14b09c  std::function<>::operator()()
    @     0x55a77e14781e  std::__future_base::_State_baseV2::_M_do_set()
    @     0x55a77e153833  std::__invoke_impl<>()
    @     0x55a77e14fc98  std::__invoke<>()
    @     0x55a77e14abe8  _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENKUlvE_clEv
    @     0x55a77e14ac53  _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv
    @     0x55a77e14ac64  _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv
    @     0x7fcbf1b67827  __pthread_once_slow
    @     0x55a77e13fa4a  __gthread_once()
    @     0x55a77e14ad1d  std::call_once<>()
    @     0x55a77e1473c0  std::__future_base::_State_baseV2::_M_set_result()
    @     0x55a77e15faa3  std::__future_base::_Task_state<>::_M_run()
    @     0x55a77e151625  std::packaged_task<>::operator()()
    @     0x55a77e14c3db  _ZZN10ThreadPool7enqueueIRFvSt4pairISsSsEEJRS2_EEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOS8_DpOS9_ENKUlvE_clEv

**Comment by xingchensong** [comment]
please rebuilt your TLG.

by the way, which recipe did you follow to make TLG.fst ? Aishell-1 or Librispeech ？

**Comment by srdfjy** [comment]
Hi

1，I am built based on the Aishell-2 recipe, and my end-to-end dictionary, lang_char.txt, contains a few English words and "<noise>". The lexicon.txt file for LM does not include these words or "<noise>", and the training samples for LM and e2e are different.

2，The wenet version used is 2.0.1, and both ngram-count and kaldi are compiled with the latest official versions. The version of fst used in kaldi is 1.7.2.

**Comment by xingchensong** [comment]
Okay, @pengzhendong is much more familiar with TLG, could you do him a favor?

**Comment by xingchensong** [comment]
@srdfjy， Hi,  could you share what you did to solve this problem for others who also encounter this problem? THX!

**Comment by srdfjy** [comment]
Hi @xingchensong 

This is caused by a mistake of mine. Composition failed because arpa2fst was not configured. Thank you for your enthusiastic help!
