### ISSUE TITLE
runtime/libtorch 编译的GPU 版进行wfst beam search解码，设置thread_num=10，GPU利用率为0

### ISSUE THREAD

**Issue by YYGXjpg** [wenet-e2e/wenet#1713]
如题，解码速度很慢。看起来CPU很高，GPU利用率为0
![image](https://user-images.githubusercontent.com/33392507/222330836-7b39433f-04cc-4f0e-9658-50c89f76c438.png)
代码是
`CUDA_VISIBLE_DEVICES=1 ./build/bin/decoder_main \
        --chunk_size -1 \
        --wav_scp ${testdir}/${set}/${set}.wav.scp \
        --model_path $model_dir/final.zip \
        -thread_num 10  -warmup 10 \
        -ctc_weight 0.3 -reverse_weight 0.5 -rescoring_weight 0.0 \
	-language_type 1 -lowercase false \
        --unit_path ${unit_path} \
        -dict_path $fst_dir/words.txt \
        -fst_path $fst_dir/TLG.fst \
        -length_penalty -3.0 \
        -beam 10 \
        -result ${tgt_dir}/${set}/log `
        
log中显示：`decoder_main.cc:105] Decoded 14222ms audio taken 52918ms`。请问是否正常？
请问应如何加快解码速度？多谢啦

**Comment by DaobinZhu** [comment]
如果CPU占用很高GPU没有利用的话，说明你采用的是CPU的编译方式，使用GPU编译可以通过`mkdir build && cd build && cmake -DGPU=ON .. && cmake --build .`的方式，另外你这个解码速度确实比较慢，可以设置参数warmup=10或者更高，https://github.com/wenet-e2e/wenet/blob/main/runtime/core/bin/decoder_main.cc#L34

**Comment by YYGXjpg** [comment]
您好，我这边确认了下，编译是没问题的，解码也是有用到GPU的。

使用prefix beam search的时候也很快，GPU利用率也有30%以上。

问题在于，加了TLG之后，会非常慢（使用的TLG大小是870M），且GPU利用率长期为0（偶尔会瞬间变成9%）。
打印出了一些中间log如下：

I0307 08:30:37.921689  4976 ctc_wfst_beam_search.cc:122] 44.1748 45.279
I0307 08:30:37.921811  4976 asr_decoder.cc:119] forward takes 55 ms, search takes 47477 ms
I0307 08:30:37.922067  4976 asr_decoder.cc:200] Partial CTC result 还 要 考 虑 预 防 主 义 的 需 要 你 将 来 还 会 不 会 再 实 施 犯 罪 这 个 试 用 期 限 是 最 重 要 的 那 职 业 禁 止 呢 是 从 刑 罚 执 行 完 毕 之 日 起 计 算
I0307 08:30:37.965334  4967 lattice-faster-decoder.cc:967] ProcessNonemitting 224 320
I0307 08:30:37.974196  4967 lattice-faster-decoder.cc:967] ProcessNonemitting 229 346
I0307 08:30:37.982820  4967 lattice-faster-decoder.cc:967] ProcessNonemitting 224 339
I0307 08:30:37.983292  4975 lattice-faster-decoder.cc:967] ProcessNonemitting 68947 158037
...
I0307 08:30:38.293226  4968 lattice-faster-decoder.cc:967] ProcessNonemitting 201 210
I0307 08:30:38.300642  4968 lattice-faster-decoder.cc:967] ProcessNonemitting 201 209
I0307 08:30:38.303037  4976 asr_decoder.cc:200] Partial CTC result 还 要 考 虑 预 防 主 义 的 需 要 你 将 来 还 会 不 会 再 实 施 犯 罪 这 个 试 用 期 限 是 最 重 要 的 那 职 业 禁 止 呢 是 从 刑 罚 执 行 完 毕 之 日 起 计 算
I0307 08:30:38.303089  4976 asr_decoder.cc:84] Rescoring cost latency: 380ms.
I0307 08:30:38.303100  4976 decoder_main.cc:72] Partial result: 还 要 考 虑 预 防 主 义 的 需 要 你 将 来 还 会 不 会 再 实 施 犯 罪 这 个 试 用 期 限 是 最 重 要 的 那 职 业 禁 止 呢 是 从 刑 罚 执 行 完 毕 之 日 起 计 算
I0307 08:30:38.303107  4976 decoder_main.cc:104] BL_mKtLdBK0_0090 Final result: 还 要 考 虑 预 防 主 义 的 需 要 你 将 来 还 会 不 会 再 实 施 犯 罪 这 个 试 用 期 限 是 最 重 要 的 那 职 业 禁 止 呢 是 从 刑 罚 执 行 完 毕 之 日 起 计 算
I0307 08:30:38.303115  4976 decoder_main.cc:105] Decoded 12320ms audio taken 47914ms.

看起来是CtcWfstBeamSearch耗时很久，（search takes 47477 ms），请问这个是正常的吗？如何加速呢？
