### ISSUE TITLE
训练时间变长了

### ISSUE THREAD

**Issue by DaobinZhu** [wenet-e2e/wenet#1714]
以前四张P100，240个epoch需要耗时一天半左右，但是现在更新了最新代码不知道怎么变成了一个小时两个epoch

**Comment by xingchensong** [comment]
torch版本和cuda版本和以前一样吗？第一反应这个应该和torch cuda有关

**Comment by DaobinZhu** [comment]
貌似是不一样，我上次因为所有进程都分配到了第一张卡，所以我删掉了所有conda环境，我再试一下以前的版本，谢谢星辰大佬



---原始邮件---
发件人: "Xingchen ***@***.***&gt;
发送时间: 2023年3月2日(周四) 晚上6:09
收件人: ***@***.***&gt;;
抄送: "Daobin ***@***.******@***.***&gt;;
主题: Re: [wenet-e2e/wenet] 训练时间变长了 (Issue #1714)




 
torch版本和cuda版本和以前一样吗？第一反应这个应该和torch cuda有关

**Comment by DaobinZhu** [comment]
> torch版本和cuda版本和以前一样吗？第一反应这个应该和torch cuda有关

我还原了pytorch到1.9.1但是速度依然很慢。。CUDA一直都是10.2的版本

**Comment by xingchensong** [comment]
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.enabled = True

这两个参数的true和false排列组合试一下

**Comment by DaobinZhu** [comment]
好的，我尝试一下



---原始邮件---
发件人: "Xingchen ***@***.***&gt;
发送时间: 2023年3月2日(周四) 晚上8:26
收件人: ***@***.***&gt;;
抄送: "Daobin ***@***.******@***.***&gt;;
主题: Re: [wenet-e2e/wenet] 训练时间变长了 (Issue #1714)




 
torch.backends.cudnn.benchmark = True
 torch.backends.cudnn.enabled = True
 
这两个参数的true和false排列组合试一下

**Comment by DaobinZhu** [comment]
> cudnn.enabled

这个是单独加在run.sh吗？

**Comment by xingchensong** [comment]
记在wenet/bin/train.py里

**Comment by DaobinZhu** [comment]
> torch.backends.cudnn.benchmark = True
> torch.backends.cudnn.enabled = True

全部调节成True速度似乎没有提升很明显，我不知道是不是跟CPU有关系，我使用nvtop后结果如下：
现在从运行bash run.sh到成功跑完第一个batch size跑完打印日志，差不多需要十多分钟，这好像很不正常
![image](https://user-images.githubusercontent.com/37605608/222435171-906be1d1-15d5-4a0d-ae88-8c292937625f.png)

**Comment by xingchensong** [comment]
试试 True False, False False, False True, 排列组合一下

**Comment by DaobinZhu** [comment]
> 试试 True False, False False, False True, 排列组合一下

好的，我再试试

**Comment by DaobinZhu** [comment]
> 

已经尝试了四种方法，False， True会快一点，但是还是不如以前的速度快，我又换了一个版本的Pytorch=1.10.1，还是不行。。

**Comment by lzy473** [comment]
你好  我想问一下  我自己训练的语言模型该怎么用呢，怎么实现转文字
