### ISSUE TITLE
Failed to import k2 and icefall.

### ISSUE THREAD

**Issue by kartily** [wenet-e2e/wenet#1715]
我在运行librispeech中的rnnt代码时，到了训练步骤，运行时提示Failed to import k2 and icefall.。而且到计算错误率阶段，得到的错误率为100%，识别结果全是<unk>。
![image](https://user-images.githubusercontent.com/89307688/222364385-c27373af-7e95-4519-b6bb-6f2ea73374be.png)

**Comment by DaobinZhu** [comment]
你使用hlg_onebest和hlg_rescore作为解码方式了吗？如果不是的话，这个提示可以忽略，错误应该不是出在这个上面。
