### ISSUE TITLE
why did it run 10 times in `api_main.cc`?

### ISSUE THREAD

**Issue by ferb2015** [wenet-e2e/wenet#1717]
**Describe the bug**
why did it run 10 times in `api_main.cc`?

**To Reproduce**
1. Go to 'https://github.com/wenet-e2e/wenet/blob/main/runtime/core/bin/api_main.cc'
3. Scroll down to 'line 37'
4. See confusion

Thank you very much!!!

**Comment by robin1001** [comment]
It's just a test.
