### ISSUE TITLE
correct  usage of context  biasing

### ISSUE THREAD

**Issue by jayakrishnanmm** [wenet-e2e/wenet#1721]
Hi,

What  is the  correct  way to use  the  context biasing ? Can you  give an  example ? I followed  the  below link, but could not make it successful, as  WER  remain the same . I provided  a sentence (containing the context word) at each line  , but  the transcription accuracy does not improve.
https://wenet.org.cn/wenet/context.html

**Comment by robin1001** [comment]
You should provide the context word at each line in `context_path` file, and you can use bigger `context_score` if you so you will get better recall of the context words.
