### ISSUE TITLE
Is there a reason why attention is reimplemented "manually" ?

### ISSUE THREAD

**Issue by jprobichaud** [wenet-e2e/wenet#1735]
Pytorch now has good attention implementation and I'm wondering why we have MultiHeadedAttention implemented manually in the codebase?

Ultimately, what I'm looking to do is to see if I can integrate https://github.com/HazyResearch/flash-attention into WeNet, but the current setup makes that not trivial.

**Comment by xingchensong** [comment]
Hello, this is a historical legacy issue. Pytorch did not have a well-optimized MHA implementation when we were implementing MHA, so we chose to implement it ourselves.

BTW, we welcome any PR that integrates Pytorch MultiHeadedAttention or flash-attention ~

**Comment by jprobichaud** [comment]
Thanks!  I need to wrap my head around this topic properly before I can hope to submit a PR :)
