### ISSUE TITLE
android 手机运行时没有发音有时也自动出字，重复的字  ，这个如何改善

### ISSUE THREAD

**Issue by wchuan163** [wenet-e2e/wenet#1737]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xingchensong** [comment]
可以考虑自行加一个额外的vad模块屏蔽掉这些语音段

**Comment by wchuan163** [comment]
好的，谢谢
