### ISSUE TITLE
NST能否提供utter_time.json生成的脚本

### ISSUE THREAD

**Issue by DaobinZhu** [wenet-e2e/wenet#1741]
NST使用LM filter需要utter_time.json文件，那么这个文件的格式是什么？有没有生成的脚本可供使用呢？

**Comment by xingchensong** [comment]
@wd929 @NevermoreCY 可以帮忙回答一下这个问题吗？谢谢！

**Comment by NevermoreCY** [comment]
这个文件存储了utterance id 以及起对应数据的时长，时间的单位是秒，存贮单位是float，以下是一个简单的例子，希望对你有所帮助~
{
    "data_id_0": 4.32,
    "data_id_1": 1.28,
}

**Comment by DaobinZhu** [comment]
> 这个文件存储了utterance id 以及起对应数据的时长，时间的单位是秒，存贮单位是float，以下是一个简单的例子，希望对你有所帮助~ { "data_id_0": 4.32, "data_id_1": 1.28, }

感谢回复，请问论文中所说的随机抽取WenetSpeech一千小时，这个有没有根据语音时长进行筛选呀？

**Comment by NevermoreCY** [comment]
一千小时的数据是随机抽取的，但是在NST的流程中可以按语音时长来筛选pseudo-label。

**Comment by DaobinZhu** [comment]
> 一千小时的数据是随机抽取的，但是在NST的流程中可以按语音时长来筛选pseudo-label。

谢谢
