### ISSUE TITLE
lower WER with onnxruntime than libtorch

### ISSUE THREAD

**Issue by jayakrishnanmm** [wenet-e2e/wenet#1742]
Hi 
I have observed  that with  onnxruntime, there is a performance  drop (in terms  of  WER) compared to libtorch. Is this  normal ?
(Gigaspeech model, onnxruntime gives 24.33  on a  test set  while libtorch  is  better  with 22.88) . I have  tried  setting SetGraphOptimizationLevel  to ORT_DISABLE_ALL  , but this  didn't help.

**Comment by xingchensong** [comment]
1. onnx cpu OR onnx gpu ？
2. chunksize ？ left chunks？

**Comment by jayakrishnanmm** [comment]
onnx cpu. chunk size =-1 (full chuck)  ( the model is  conformer bi-decoder)
what is left chunks ?

**Comment by xingchensong** [comment]
Did you change this flag to -1 ? https://github.com/wenet-e2e/wenet/blob/main/runtime/core/decoder/params.h#L69

**Comment by jayakrishnanmm** [comment]
nope. what is the  default value ?

**Comment by xingchensong** [comment]
default = 16

**Comment by jayakrishnanmm** [comment]
OK, with num_left_chunks=-1   , WER  drops  to 22.16  with ONNX. thank you  very much !
