### ISSUE TITLE
Squeezeformer纯CTC与Hybrid结果对比

### ISSUE THREAD

**Issue by Johnson-NLP** [wenet-e2e/wenet#1745]
论文中Squeezeformer-SM只用CTC loss训练就可在Librispeech达到2.79/6.89的WER，这个结果用NeMo的代码确实是可复现的；
Wenet使用Hybrid CTC/Attention loss训练Squeezeformer，结果却连attention rescoring都比论文中差（除Bi-decoder版本），这个是什么原因呢？
求大佬解答下，感谢。

**Comment by ziyu123** [comment]
同上，我最近也在实验wenet的Squeezeformer(参数量有少许差别)，用Conformer和Squeezeformer，loss 采用 CTC + Attention loss，在aishell1上用attention rescoring解码， 结果   conformer 4.60% ,  Squeezeformer 5.17%,  也有一定的差距，不清楚哪里的原因？

**Comment by xingchensong** [comment]
@yygle Hi, 可以帮忙解答一下吗？ 谢谢！

**Comment by yygle** [comment]
论文中Squeezeformer-SM用了2kbatch size + 1000epoch，我目前搭的这个baseline用了120个epoch。aishell上目前不建议用当前版本的squeezeformer，我自己实验的版本是需要把MFCF调整回1/2 * FMCF会好一些，另外bn同步的代码和现在的框架有点不兼容，加上去效果会再好一些

**Comment by Johnson-NLP** [comment]
> 论文中Squeezeformer-SM用了2kbatch size + 1000epoch，我目前搭的这个baseline用了120个epoch。aishell上目前不建议用当前版本的squeezeformer，我自己实验的版本是需要把MFCF调整回1/2 * FMCF会好一些，另外bn同步的代码和现在的框架有点不兼容，加上去效果会再好一些

多谢解答。关于batch_size和epoch的不一致我这边也做过一些实验，发现结果还是有差距；另外Wenet的Hybrid架构用的是5000Unigram建模vocab，Squeezeformer论文中用的是128BPE，这个有影响吗？

**Comment by yygle** [comment]
建模这个部分应该也是有影响的，我之前的实验结论看来，区别不会特别大，另一个比较大的影响是RPE会在英文上有一定提升，目前这个版本为了兼容之前的流式模型，没有支持标准的RPE。

**Comment by ziyu123** [comment]
> 

好的，谢谢，我尝试下调整MFCF和bn，看看效果。
