### ISSUE TITLE
domain adaptation

### ISSUE THREAD

**Issue by suuuuju** [wenet-e2e/wenet#1746]
请问关于无监督域适应（MMD）的部分还会更新进来吗

**Comment by Mddct** [comment]
这里有较新的bestrq的pr https://github.com/wenet-e2e/wenet/pull/1750  可以试用一下 但是目前还没有benchmark

**Comment by suuuuju** [comment]
> 这里有较新的bestrq的pr #1750 可以试用一下 但是目前还没有基准

感谢😃

**Comment by kobenaxie** [comment]
> 这里有较新的bestrq的pr #1750 可以试用一下 但是目前还没有benchmark

请问，多语言是怎么设计词表的呢？是所有语言的建模单元放在同一个词表内？还是说每个语言各自有一个词表，但是所有语言的词表大小都一样？

**Comment by Mddct** [comment]
一般是一个词表 比如各种语言的字或者subword
