### ISSUE TITLE
运行runtime/gpu的readme案例时，出现unexpected keyword argument 'model_name'问题

### ISSUE THREAD

**Issue by lvchigo** [wenet-e2e/wenet#1753]
# 一、Bug描述
- 使用[wenet/tree/main/runtime/gpu进行readme的案例](https://github.com/wenet-e2e/wenet/tree/main/runtime/gpu)运行时，server开启正常，client开启容器正常，但运行client案例时（python3 client.py --audio_file=/ws/test_data/mid.wav --url=0.0.0.0:8001），发生以下问题（unexpected keyword argument 'model_name'）：
- client提示：  
![image](https://user-images.githubusercontent.com/8186051/225495698-36e88f0c-45c0-4127-9f7b-42600a413db1.png)  
- server提示：  
![image](https://user-images.githubusercontent.com/8186051/225495971-52e2cafb-4f89-4f58-83bb-a0d8c2a95760.png)  
- 初步定位到（/ws/model_repo/scoring/1/model.py(246)）：  
![image](https://user-images.githubusercontent.com/8186051/225495843-830d2c83-a114-4c26-9f96-cd1841df245e.png)

# 二、环境验证
## 2.1、server端
- server端开启正常：  
![image](https://user-images.githubusercontent.com/8186051/225493368-0aef80dc-41d5-451c-bd7b-980542b42389.png)   
- server端环境配置：  
![image](https://user-images.githubusercontent.com/8186051/225496101-ab6034a6-0777-4e92-af2a-7360005ee300.png)  
- server端容器环境:  
    - nvcr.io/nvidia/tritonserver:21.04-py3：
    - cuda环境：  
![image](https://user-images.githubusercontent.com/8186051/225497473-725dee4a-e24f-40b9-93cb-9251790e442f.png)  
- server端容器python环境:  
![image](https://user-images.githubusercontent.com/8186051/225497187-d6b1d1bf-698a-4cf8-842e-96495de5e43d.png)
## 2.2、client端
- 镜像：nvcr.io/nvidia/tritonserver:21.04-py3-sdk

**Comment by yuekaizhang** [comment]
请问是什么原因使用21.04呢？没有这个Model_name可能是那个时候的triton确实没有，试试 22.12 或者更新的23.0x吧

**Comment by lvchigo** [comment]
> 请问是什么原因使用21.04呢？没有这个Model_name可能是那个时候的triton确实没有，试试 22.12 或者更新的23.0x吧

使用21.04主要是对应cuda11.3；
线下已与@yuekaizhang大佬沟通，如果需要使用cuda11.3，建议拉取大佬个人打包的镜像docker pull soar97/triton-wenet:22.12；

**Comment by yuekaizhang** [comment]
补充一下：tritonserver 官方镜像 22.xx系列都是支持 cuda 11.3的， soar97/triton-wenet:22.12 是基于 tritonserver 22.12编译的
