### ISSUE TITLE
运行bash tools/fst/make_tlg.sh报错

### ISSUE THREAD

**Issue by wwfcnu** [wenet-e2e/wenet#1779]
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0327 21:27:11.741288 4070603 fst.cc:93] FstHeader::Read: Bad FST header: standard input
Checking how stochastic G is (the first of these numbers should be small):
fstisstochastic /home/wangweifei/data/lang_new/G.fst
0 0
fstdeterminizestar --use-log=true
fstminimizeencoded
fsttablecompose /home/wangweifei/data/lang_new/L.fst /home/wangweifei/data/lang_new/G.fst
fsttablecompose /home/wangweifei/data/lang_new/T.fst /home/wangweifei/data/lang_new/LG.fst
Composing decoding graph TLG.fst succeeded

**Comment by robin1001** [comment]
runtime 编译了吗？
