### ISSUE TITLE
On Multi Machine Parallel Training

### ISSUE THREAD

**Issue by rookie0607** [wenet-e2e/wenet#1780]
我使用wenet进行多机多卡训练（双机8卡），机器1为主节点 显卡p40 （显存22G），batch size设置为22，机器2显卡2080（显存11G） batch size设置为8；现在出现机器1跑完等待机器2的情况，请问改如何避免这种情况？每台机器显卡显存要保持一致、batch size要一致吗？

**Comment by robin1001** [comment]
wenet 中用的是分布式同步训练方案，多卡时建议用同等配置的卡。

**Comment by lemondy** [comment]
> wenet 中用的是分布式同步训练方案，多卡时建议用同等配置的卡。

请问当前有多机多卡训练的代码example示例吗？
