### ISSUE TITLE
我想用自己的数据集训练出来的模型与web交互，需要怎么实现呢？

### ISSUE THREAD

**Issue by lzy473** [wenet-e2e/wenet#1782]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lzy473** [comment]
![image](https://user-images.githubusercontent.com/127758069/227834988-0dac2e81-92fe-47e4-8e66-d571d28ba9d4.png)
我替换了词典和final.zip报了下边的错

**Comment by robin1001** [comment]
please see https://github.com/wenet-e2e/wenet/tree/main/runtime/web.

**Comment by robin1001** [comment]
please see https://github.com/wenet-e2e/wenet/tree/main/runtime/web.
