### ISSUE TITLE
web报错

### ISSUE THREAD

**Issue by lzy473** [wenet-e2e/wenet#1785]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/127758069/228000749-e952855f-675f-4be5-a064-00ad35deb107.png)
我运行之后怎么是错误的

**Comment by robin1001** [comment]
@cdliang11 , please help to figure out the problem.

**Comment by lzy473** [comment]
To create a public link, set `share=True` in `launch()`
这个怎么实现呢

**Comment by lzy473** [comment]
![image](https://user-images.githubusercontent.com/127758069/228181797-15924c86-744a-475d-a728-3fb25d02ea95.png)
报这个错

**Comment by cdliang11** [comment]
我猜测是机器环境存在一些问题，换个机器尝试一下 :)
