### ISSUE TITLE
热词和语言模型同时使用时，置信度得分会出现大于0的情况

### ISSUE THREAD

**Issue by WangGewu** [wenet-e2e/wenet#1794]
https://github.com/wenet-e2e/wenet/blob/main/runtime/core/decoder/ctc_wfst_beam_search.cc#L122
eg：weight.Value1()和weight.Value2()分别为：-140.096，38.2868

**Comment by robin1001** [comment]
最终热词识别率正常吗？

**Comment by WangGewu** [comment]
识别率是正常的
