### ISSUE TITLE
How to compile wenet executables on an ARM-based ubuntu machine?

### ISSUE THREAD

**Issue by Beluooo-H** [wenet-e2e/wenet#1798]
Problem description:

/usr/bin/ld: ../fc_base/libtorch-src/lib/libtorch.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/ctc_prefix_beam_search_test.dir/build.make:99: ctc_prefix_beam_search_test] Error 1
make[2]: Leaving directory '/home/taishan/test/wenet/runtime/server/x86/build'
make[1]: *** [CMakeFiles/Makefile2:400: CMakeFiles/ctc_prefix_beam_search_test.dir/all] Error 2
make[1]: Leaving directory '/home/taishan/test/wenet/runtime/server/x86/build'
make: *** [Makefile:155: all] Error 2

A version problem with libtorch seems to be causing the problem.

set(PYTORCH_VERSION "1.6.0")
......
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    set(LIBTORCH_URL "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip")
    set(URL_HASH "SHA256=c6c0d3a87039338f7812a1ae343b9e48198536f20d1415b0e5a9a15ba7b90b3f")

The CMakeLists file at runtime specifies the path to the libtorch download and the URL_HASH. How do I change the default values here to download the arm version of libtorch.

Looking forward to receiving your reply!

**Comment by Kaisa-H** [comment]
`~/test/wenet/runtime/server/x86/fc_base/libtorch-src/lib$ file libtorch.so
libtorch.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0c8cb78054367df4779d343b1308c477078f7750, not stripped
`

The default URL of the CMakeList file to download libtorch is x86 architecture. I would like to know how to modify the set(LIBTORCH_URL xxx) and set(URL_HASH) to obtain the arm architecture libtorch.

**Comment by Gmgge** [comment]
你可以在[这里](https://github.com/wenet-e2e/wenet/blob/212efb0755caa6bc36d9544f71bea3c7aae484bc/runtime/core/cmake/libtorch.cmake#L1)看到，定义torch下载的url

**Comment by Kaisa-H** [comment]
> 你可以在[这里](https://github.com/wenet-e2e/wenet/blob/212efb0755caa6bc36d9544f71bea3c7aae484bc/runtime/core/cmake/libtorch.cmake#L1)看到，定义了LIBTORCH_URL 下载的url


The link from the official website is to download x86 libtorch, but I don't know a URL to download aarch64 libtorch

**Comment by Gmgge** [comment]
我想你是在寻找这个[问题](https://github.com/wenet-e2e/wenet/issues/1443)，其中提出了https://github.com/KumaTea/pytorch-aarch64/releases，可以下载相关内容

**Comment by wwh131** [comment]
我也有这个问题
