### ISSUE TITLE
Transformer models

### ISSUE THREAD

**Issue by flozi00** [wenet-e2e/wenet#180]
**Is your feature request related to a problem? Please describe.**
Low ressource languages and deep domain use cases need more efficient models

**Describe the solution you'd like**
Huggingface is working in their transformers library integrating ASR models like wave2vec 2 and speech transformer

**Describe alternatives you've considered**
The fairseq implementation of wave2vec has more dependencies and is more complex to use and less readable.

**Additional context**
Integrating huggingface models makes have you pretrained models from modelhub, multiple models support with less code.

**Comment by robin1001** [comment]
Thanks, we will investigate on that

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/wenet/issues/1683 OnGoing
