### ISSUE TITLE
words  joined  at chunk boundaries

### ISSUE THREAD

**Issue by jayakrishnanmm** [wenet-e2e/wenet#1801]
When  decoding large files  with continuous _decoding  option  , two words  are  joined  at chunk boundaries. (in the asr output text)  Cannot  observe this  with  small file  and  chunk_size  set to -1.  (English model)

**Comment by robin1001** [comment]
please give some examples.

**Comment by jayakrishnanmm** [comment]
Sorry  for  the  late follow  up. Since I fixed  it by  a work around, I forgot to take it up again. 
Pls see  the below  decoding result 
./build/bin/decoder_main \
    --chunk_size 16 \
    --num_left_chunks -1 \
    --wav_path $1 \
    --onnx_dir $onnx_dir \
    --continuous_decoding \
    --num_threads 2 \
    --unit_path $units \
    --result $2  2>&1 | tee log.txt


we're gathered at this sacred placein this solemn hour engage in most fundamental of undertakings the right of remembranceremember those who gave their all in the service of america and the service of freedomservice of justice remember their sacrifice their valor and their graceremember their smiles their lovesafter therepotential vibrant and transcendent humanityfor while we stand amid monuments of stonenever forget that each of these markers for those known and unknown here at arlington and far beyondthat a precious life a son a daughter a mother a spouse brother a sister of friend a neighborthose who mourna loved one todayyou and i have some idea how you're feelingour losses are not the samebut that black coal you feel in your chest as if it's going to suck you into itwe geti know the incredible pride you felt senior loved one wear the uniform of our countrypride they felt wearing itour son bose service the dela robbery national guard unit the year is spent deployed in iraqone of the things that he was most proud of in lifeyesterday mark the anniversary of his deathand it's a hard timehard time of year for meand our familylike it is for so many of youit can hurt to remember butis how we feel and how we healalways feel both close to me at memorial day i know exactly where i need to behere honoring our fallen heroesgo through pain and anguish of his loss i remember the pride on his face that penned those bars on his shouldersall of you who are fighting with the fresh pain of losshard it is to believe i promise you thisah day will comeimage of your loved one will bring a smile to your lips before it brings a tear to your eyesbible teaches blessed are they that mourn for they shall be comfortedcomfort that reassurance can be a long time in coming but it will come i promise youum prayer for all of you is that they that that day will come sooner rather than laterwe're all known memorials day origins lying the wake of the civil warfor for the freedom of allfor unionfor for libertyah preservation of the constitutionin calling for such today general john logan commander of the grand army of the republic issued general order number elevenhe directed the nation set aside a day to honor and i quote those who died in defense of their country during the late rebellion and whose bodies now lie in almost every city village and hamlet churchyard throughout the landand so we haveso we do again today in our timewhere the childrenum sacrifice made by a long line of american service members each a link in that chain of honorwe live by the light of the flame of libertyah kept bernie we're free because theyhere on these gentle rolling green hills and across america and around the globe lie buried the heroes of the greatest experiment the world has ever known ever seenbears the noble name the united states of americawomen and menthose we honor todaytheir lives for their countrybut they live forever in our hearts forever proud forever honorable forever americanthey are they are the sentinels of liberty defenders of the downtrodg liberators of nationsand still todayis stand watch around the worldtheir great personal perilwar and conflict death and lossnot relics of our american historypart of american storyhere in arlington why heroes who gave a president lincoln called the last full measure of devotionit did not only die at gettysburg or in flanders field or in the beaches of normantyah mountains of afghanistan the deserts of iraqtwenty yearssex and sixty when i walk through it reminds me of the cost of warhundreds of graves hundreds of graves are here from recent conflictshundreds of patriots gave their alleach of the maybe behind the familywhat their pain and their absence every single dayi want to assure each of those families we will never forgetwhat you gave to our countrywe will never fail to honoryour sacrificeeach dayanyone i was vice president united statescarry in my pocket a number of troops killed during the warsafghanistan and iraqan approximation not rounded off numbersthe eastly behind the entire community and familytoday that number is seven thousand and thirty sixthousand and thirty six fallen angelslost their livesconflictsthis memorial dayand their legacy and their sacrificehonor countrythey lived for it they died for itand we as a nation are eternally grateful<s>so america has been forged in the baz and the fires of warah freedom and the freedom of innumerable others has been secured by young men and women who answered the call of history and gave everything the service of an ideathe idea of americait's the greatest idea in the long history of humankind an ideawe're all created equal in the image of almighty godall entitled to dignity as my father would say and respectdecency and honorneighbor they're not empty wordsbut the vital beating heart of our nationand that democracy must be defended at all costs where democracy makes all this possible democracythat's the soul of americaand i believe it's a soul worth fighting for and so to you a soul worth dying forheroes who lie in eternal peace this beautiful place this sacred place they believe that tooall of america is animatedby the perennial battle betweenah worst instincts which we've seen of late and our better angelsbetween me first andbe the peoplebetween greed and generosity cruelty and kindnessactivity and freedomthe americans of lexington and concord of new orleans gettysburg the argon io g and normandy korean vietnam afghanistan and iraq and thousands of places in betweenthese americans weren't fighting for dictators they were fighting for democracythey weren't fighting to exclude or to enslave they were fighting to build and broaden and liberatethey weren't fighting for self they were fighting for the soul of the nationfor liberty and simple fair playfull fair play and decencydays remember their sacrificeremind ourselves of our duty to their memory to the future they fought forwe owe the honored dead debt we can never fully repay we owe them our whole souls we owe them our full best efforts to perfect the union for which they diedwe owe them the work of our hands and our heartsmake grill the promise of a nation founded on the proposition that all of us all of us all of uscreated equal and deserved to treat it that way throughout our livesdemocracy is more than a form of government its way of being it's a way of seeing the worlddemocracy means the rule of the peoplerule of the peoplenot the rule of monarchsthe role of the moneyed not the rule of the mighty literally the rule of the peoplethe lives of billions from antiquity to our own hourshape by the battle between aspirations of the many and the greed of the few between people right to self determination and the self seeking of the dictator between dreams of democracy and appetites for autocracy which were seen around the worldum who fought this battle on fields around the world but also theof our timeand the mission falls to each of us each and every daysee itselfpair of here at home and around the worldwhat we do nowdo now how we honor the memory of the fallendetermine whether or not democracy will long endurewe all take you for granted we think we learn in school you have that every generation has to fight for itlookit's the biggest question whether a system that prizes the individual that bends towards libertyeverybody a chance of prosperity whether that system can and willah against powerful forces that wish it harmthat we do in our common life as a nation is part of that struggleah go for democracy is taking place around the world democracy and autocracy<z>for decency and dignitysimple decencystruggle for posterity prosperity and progress and yesstruggle for the soul of americaitselffolksyou all know it democracy thrives when the infrastructure democracy is strongum people have the right to votereally and fairly and conveniently when a free and independent press pursues the truth founded on facts not propaganda on the rule of law applies equally and fairly to every citizen and regardless of where they come from what they look likeexcuse mewherever americans are therethere is democracysynagogues and mosquesand coffee shops and dinersleeiters and kids baseball or soccer gameand parksdemocracy begins to grow in the open heart and the impetus to come together for a common causeand i might know parenthetically thank you taps that's what you doand that's where we'll be preservedfor empathy is the fuel democracy let me say that again empathy empathy is the fuel ofdemocracy are willing to see each othernot as enemy as neighbors even we disagreed to understandbut the other's going throughstate the obviousracies imper it always has been but americans have all backgrounds races creeds gender identities sexual orientations have long spillled their blood to defend our democracy the diversity of our country and our arm and of our armed services is inhas been an incredible strengthand generation after generation of american heroes have signed up to be part of the fight because they understand the truth that lives in every american heartliberationopportunity justice are far more likely to come to pass in a democracy than an autocracyif every person is sacred and every person writes our sacredindividual dignity individual worth individualsanctityright to life liberty the pursuit of happiness we say those words so often but think of itthe right to voteright to rise in a world as far as utalu can take you unlimited by unfair barriers of privilege and powersuch are the principles of democracyso how would you put these noble principles into practice how do we do thatmake the idea real or as close to real as we can make it this nation was built on an idea the only nation in the world built an idea every other nation is built on ethnicity geography religionetc we were built on an idea the idea of libertyan opportunity for allnever fully realized that aspiration of our founding but every generation has opened the door a little widerevery generation is open to wider and wider to be more inclusive include those who've been excluded beforeit's a mission handed down generation to generation the work of perfecting our unionthirtywhen we're a young nationdisunionists put their sexual interest ahead of the common gooda great senator daniel websterand the capital to defend the unionwe're not just a collection of competing forces but a coherent wholehis cry firstah just across the potomac in the capitol resonates even nowstood in the floor and he said liberty and union now and forever one and inseparable liberty and union<b> more than one hundred and forty two years laterfirst came to the united states senate at a time when our country was so deeply divided over vietnam the struggle of civil rights the fight of our women's rights inotion that my first task as i stood to make my first speech on the floor of the senate that all of a sudden hit me i'm standing where daniel weptridge stood his desk was next to minei was struck by the weight of history as cornies it soundslegacy the work were charged to carry forward liberty and unionnow and forevernow is thenunity is essential to life liberty and the pursuit of happinessand so remember those who gave their all the cause of unity and the cause of a nation that endures because of themhonor their sacrificegaining the best of america while honestly confronting all that we must do to make our nation fuller freer and more justrememberwe may find the light in the wisdom and yes the courage to move forward in the words of that great hymnfight as they nobly thought of oldwhen remembrance lies not just our history but our hopenot just our solemn remembrance but our renewed purpose not just our solace but our strengththis memorial daybut not all of us are called to make the ultimate sacrificewe all are calm by god and by history andconscienceto make our nation free and fair just and strong noble and wholethis battlemay we now dedicate our souls that our work may prove worthy of the blood of our fallen for this work the work of democracy is the work of our time and for all timeand if we do our duty then age is still to come we'll look back on us and say that we too kept the faiththere's nothing more importantmore sacred nothing more american than keeping the faithand god bless the united states of americaand may the light perpetually shine upon the fallah bring comfort to their familiesum god protect our troopstoday andgod bless you all<z>um
