### ISSUE TITLE
Using RNN-T for training and reasoning on aishell, stage 5 has no output of results

### ISSUE THREAD

**Issue by llleohk** [wenet-e2e/wenet#1806]
I am trying to use the transformer_ The training model of RNNT performs a wer test on the AIShell using the command bash run.sh -- stage 5-- stop stage 5, but there is no result output
![image](https://user-images.githubusercontent.com/99810710/229984035-6fa83d5b-13c4-43bb-b1a1-44cf7a4676a8.png)

**Comment by Mddct** [comment]
could you check ctc branch decoding

**Comment by llleohk** [comment]
> could you check ctc branch decoding

My experiment removed the addition of ctc and only used att+rnnt. Will this issue be related to this? In addition, I only trained 50 epochs, which will also cause this issue ?

**Comment by Mddct** [comment]
I have no idea。 May be it crash in early stage

**Comment by llleohk** [comment]
> I have no idea。 May be it crash in early stage

Thank you very much for your reply. I will try training multiple epochs before testing.

**Comment by SevenTailCat** [comment]
> > I have no idea。 May be it crash in early stage
> 
> Thank you very much for your reply. I will try training multiple epochs before testing.

Hi, does  training multiple epochs solve this question?
