### ISSUE TITLE
ImportError: cannot import name 'Union' from 'torch.nn.modules.conv' (/data/lby/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/conv.py)

### ISSUE THREAD

**Issue by LBY-bamboo** [wenet-e2e/wenet#1807]
Hello, wenet reported the following errors in the training process , how should I solve
ImportError: cannot import name 'Union' from 'torch.nn.modules.conv' (/data/lby/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/nn/modules/conv.py)
![image](https://user-images.githubusercontent.com/94619869/230075531-4b1fa7db-6941-4d9f-b9a1-18ff4c592f74.png)

**Comment by robin1001** [comment]
what's your torch version?

**Comment by zth-1024** [comment]
have you solved the problem?
