### ISSUE TITLE
How to train the model using phonemes as text modeling units?

### ISSUE THREAD

**Issue by zds-potato** [wenet-e2e/wenet#1808]
The use of phonemes for training will help the training of multilingual speech recognition models, which will benefit low-resource speech recognition.

**Comment by robin1001** [comment]
specify `split_with_space: true` in your training yaml configure.

please refer https://github.com/wenet-e2e/wenet/blob/main/examples/timit/conf/train_conformer.yaml#L38.

**Comment by zds-potato** [comment]
Thanks very much.

**Comment by liziru** [comment]
> specify `split_with_space: true` in your training yaml configure.
> 
> please refer https://github.com/wenet-e2e/wenet/blob/main/examples/timit/conf/train_conformer.yaml#L38.
请问我想训练中文识别模型，考虑用作语音转换中的ppg,  @也是这种操作方式吗，有没有推荐的recipes用来修改？感谢！
