### ISSUE TITLE
make_tlg.sh报错

### ISSUE THREAD

**Issue by wwfcnu** [wenet-e2e/wenet#1809]
运行make_tlg.sh报错，猜测是不是与lm.arpa太大有关，lm.arpa大小31G
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/109075309/230297091-a08f7e2b-a675-494b-a0cc-96f50ea4d8c5.png">

**Comment by xingchensong** [comment]
请问参考的哪个recipe来make tlg的？以及代码是最新的吗

**Comment by wwfcnu** [comment]
> 请问参考的哪个recipe来make tlg的？以及代码是最新的吗

[wenet](https://github.com/wenet-e2e/wenet)/[tools](https://github.com/wenet-e2e/wenet/tree/main/tools)/fst/nake_tlg.sh

**Comment by wwfcnu** [comment]
之前同样的脚本处理了一个小一点的arpa，换了更大的lm.arpa就报错了，内存也是够用的
