### ISSUE TITLE
compile hlg error using k2 icefall

### ISSUE THREAD

**Issue by iPwnXX** [wenet-e2e/wenet#1811]
I'm running aishell s0 run.sh with the baseline model,  all stages from 0 to 7 have been executed sucessfully with expected wer testing results. Problems occured when running 8.1 build decoding HLG, after i installed required packages. `compile_hlg.py` didn't generate `HLG.pt`,  logging error showing all the string read from `G_3_gram.fst.txt` is not a valid Fsa:
```
ValueError: The following is not a valid Fsa in the openFst format (with num_aux_labels=1): 
2 123662 2 2 4.71531       
....
```
the `G_3_gram.fst.txt` was generated  by `kaldilm` with default param in `8.2 preprare G ` in `make_hlg.sh`, nothing has been modified, and i don't know what to check next.    

cases i noticed in `G_3_gram.fst.txt`:
most rows are 5 column line;  some rows are 4 column with 0 endding:
`532412 9745 123661 0`    

some rows are 2 column:
`543411 1.31772`

**Comment by robin1001** [comment]
@csukuangfj @aluminumbox any idea？

**Comment by csukuangfj** [comment]
I suggest that you use the latest k2.

**Comment by jyp0716** [comment]
I'm running aishell s0 run.sh with lfmmi in stage 4，problems occured 
![图片](https://user-images.githubusercontent.com/22422669/232745814-25fc9c94-fdb5-4c9b-bf8f-7d9ec540928e.png)
 
I install k2 by pre-built cuda wheel:
![图片](https://user-images.githubusercontent.com/22422669/232746314-21d79cc0-5bcd-4aed-a558-d6f54bbc86f1.png)
it build ok ,no error occured

**Comment by csukuangfj** [comment]
Please post the complete error logs.

**Comment by jyp0716** [comment]
![图片](https://user-images.githubusercontent.com/22422669/232755292-d5b67b64-30a3-4745-9b55-ac15fae7dba1.png)
![图片](https://user-images.githubusercontent.com/22422669/232755404-1822bec0-e25c-4152-9c4a-d91d46b92fbf.png)
![图片](https://user-images.githubusercontent.com/22422669/232755466-874b0b2d-68f8-4632-9661-a65647085a81.png)

**Comment by csukuangfj** [comment]
> ![图片](https://user-images.githubusercontent.com/22422669/232755292-d5b67b64-30a3-4745-9b55-ac15fae7dba1.png) ![图片](https://user-images.githubusercontent.com/22422669/232755404-1822bec0-e25c-4152-9c4a-d91d46b92fbf.png) ![图片](https://user-images.githubusercontent.com/22422669/232755466-874b0b2d-68f8-4632-9661-a65647085a81.png)

Anwered offline. 

Operations from k2 do.not.support torchscript. The fix is to not use k2 during model export.
After exporting the model to torchscript, you can use k2 C++ APIs to run the exported model with libtorch using C++.

**Comment by iPwnXX** [comment]
> I suggest that you use the latest k2.

newer version of k2 fixed the 'comple hlg' problem.

**Comment by jyp0716** [comment]
> > ![图片](https://user-images.githubusercontent.com/22422669/232755292-d5b67b64-30a3-4745-9b55-ac15fae7dba1.png) ![图片](https://user-images.githubusercontent.com/22422669/232755404-1822bec0-e25c-4152-9c4a-d91d46b92fbf.png) ![图片](https://user-images.githubusercontent.com/22422669/232755466-874b0b2d-68f8-4632-9661-a65647085a81.png)
> 
> Anwered offline.
> 
> Operations from k2 do.not.support torchscript. The fix is to not use k2 during model export. After exporting the model to torchscript, you can use k2 C++ APIs to run the exported model with libtorch using C++.

thanks，problem fixed
