### ISSUE TITLE
我在使用tlg解码时候出现一下错误

### ISSUE THREAD

**Issue by lzy473** [wenet-e2e/wenet#1812]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iPwnXX** [comment]
check exp/decoder/lm_with_runtime/split1/1.log to give a more detailed error description.

**Comment by lzy473** [comment]
![image](https://user-images.githubusercontent.com/127758069/231131290-48b5f3c8-b703-4546-94bb-c2677126cfb7.png)

**Comment by SevenTailCat** [comment]
你看看那个cannot open的文件是否存在，line 10

**Comment by lzy473** [comment]
他是存在并且能够打开的

**Comment by lzy473** [comment]
存在并能够打开

**Comment by lzy473** [comment]
![image](https://user-images.githubusercontent.com/127758069/231368765-efdb65c3-3391-4330-a6dd-c0f268cb6a62.png)

**Comment by yangyyt** [comment]
> 语言模型还需要指定词典的路径：https://github.com/wenet-e2e/wenet/blob/main/runtime/core/decoder/params.h#L94

请问这种是什么情况呀，同样报core dumped, [aishell例子中tlg解码正常]
./tools/decode.sh: line 65: 226378 Aborted                 (core dumped) decoder_main --rescoring_weight $rescoring_weight --ctc_weight $ctc_weight --reverse_weight $reverse_weight --chunk_size $chunk_size --wav_scp ${dir}/split${nj}/wav.${n}.scp --model_path $model_file --unit_path $unit_file $wfst_decode_opts --result ${dir}/split${nj}/${n}.text &> ${dir}/split${nj}/${n}.log
awk: cmd. line:1: fatal: division by zero attempted

![image](https://github.com/wenet-e2e/wenet/assets/26132147/d7988c4a-d8d1-4552-bc98-d382cbc7815f)

**Comment by turinaf** [comment]
@yangyyt were you able to solve this issue? 

I'm also facing `awk: cmd. line:1: fatal: division by zero attempted` error.
