### ISSUE TITLE
ssl/bestrq recipe?

### ISSUE THREAD

**Issue by yuseungwoo** [wenet-e2e/wenet#1815]
Hello I'm  Seung Woo 

First of all, Thank you for your good work "ssl/bestrq". I came to train this model and compare my implementation 

For these reason.. Is there any example using the model in librispeech or aishell ?

Thanks for in advance. 

Seung Woo.

**Comment by rookie0607** [comment]
anticipating

**Comment by Mddct** [comment]
training is unstable and always crash now 。 I am working on it

**Comment by Mddct** [comment]
you can try new : https://github.com/wenet-e2e/wenet/pull/1824, recepie will in later pr

**Comment by rookie0607** [comment]
> @yuseungwoo @rookie0607 你可以尝试新的：#1824， recepie 将在以后的 pr
cool！

**Comment by yuseungwoo** [comment]
I hope the recipe will come soon.

**Comment by lizongyao123** [comment]
@yuseungwoo Hi, what's your final reproduction result? Do you have any good reproduction suggestions? My results on librispeech data are completely unable to do the results in the paper.
