### ISSUE TITLE
Reading FLAC files from file-like objects is broken? Shard issue

### ISSUE THREAD

**Issue by dipeshhoncho07** [wenet-e2e/wenet#1818]
Hi, Calling torchaudio.load with a file-like object as argument to load FLAC-encoded files sometimes returns incomplete tensors. It seems to happen with non-trivial tensors after a certain length.

It has a solution by changing the backend from sox to FFMPEG. However, this change needs to be done throughout the codebase. Therefore I request the owners of the repository to update the repo with the fix. Otherwise, it will keep on causing issue if people will try to use flac-files as shardd.

**Comment by robin1001** [comment]
Could you help on that? and what's the solution in torchaudio 2.0?

**Comment by Slyne** [comment]
@dipeshhoncho07   I submitted a small pr (one line of code) which may be relevant to your issue. https://github.com/wenet-e2e/wenet/pull/1842

**Comment by dipeshhoncho07** [comment]
@Slyne, it's working now.
