### ISSUE TITLE
How to generate an alignment file?

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#1822]
Hi，In the latency_metrics.py file, there is an alignment parameter. How can I generate the file? I looked at the alignment file generated by wenet/bin/alignment.py and it doesn't seem to be applicable.

**Comment by robin1001** [comment]
it's ./tools/latency_metrics.py, @xingchensong , please follow the issue.

**Comment by xingchensong** [comment]
It is generated using kaldi, you can find aishell alignments here https://github.com/wenet-e2e/wenet/issues/1681

**Comment by srdfjy** [comment]
thanks.
