### ISSUE TITLE
efficient conformer非流式模型的chunk16和18有什么含义吗

### ISSUE THREAD

**Issue by wenzhengchang** [wenet-e2e/wenet#1825]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zwglory** [comment]
和Conformer的chunk一样，作为一个参考，真正流式用因果卷积，在相同chunksize下和非流式相比效果会差一些（自有场景数据作为参考，流式chunk=18 CER=9.30%，非流式chunk=18 CER=8.76%）。在数值选择方面，16是Conformer runtime默认的chunksize，选择18是因为Attention groupsize=3，来比较是否整除效果会更好。
