### ISSUE TITLE
mandrian conformer model alignment missing the first word

### ISSUE THREAD

**Issue by chenyang399** [wenet-e2e/wenet#1826]
**Describe the bug**
i use the examples/aishell/s0 example to train a conformer model, then i use the wenet/bin/alignment.py to align the aishell data

but the first word of the sentence is not aligned

the result is like

0.00 0.04  甚
0.04 0.88 至
0.88 0.16  出

the first interval has no word
and the second interval has two word in the audio interval

**Comment by robin1001** [comment]
The alignment is not accuate.

**Comment by robin1001** [comment]
@whiteshirt0429 @Mddct any solution to refine it?
