### ISSUE TITLE
onnx export problem

### ISSUE THREAD

**Issue by fclearner** [wenet-e2e/wenet#1827]
**Describe the bug**
onnx export succeded but check failed?
anyone can help, thanks

'''
Stage-3.3: check onnx_decoder and torch_decoder
Traceback (most recent call last):
  File "wenet/bin/export_onnx_cpu.py", line 411, in <module>
    main()
  File "wenet/bin/export_onnx_cpu.py", line 407, in main
    export_decoder(model, arguments)
  File "wenet/bin/export_onnx_cpu.py", line 349, in export_decoder
    np.testing.assert_allclose(to_numpy(torch_score), onnx_output[0],
  File "/data1/fangcheng1050/miniconda3/envs/wenet/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/data1/fangcheng1050/miniconda3/envs/wenet/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatched elements: 1 / 1059600 (9.44e-05%)
Max absolute difference: 0.00576973
Max relative difference: 0.0011973
 x: array([[[ -9.281936,  -7.970399,  -9.281937, ...,  -9.205927,
          -9.42669 ,  -4.096967],
        [ -9.316809, -13.452858,  -9.316811, ..., -10.137756,...
 y: array([[[ -9.281973,  -7.970314,  -9.281975, ...,  -9.205969,
          -9.426718,  -4.096983],
        [ -9.31679 , -13.452774,  -9.31679 , ..., -10.137754,...
'''

**Comment by fclearner** [comment]
I used another 5 pts to generate avg model, it exported successfully, it seems one of the pts has some problems. I checked the loss, it's normal

**Comment by Slyne** [comment]
> I used another 5 pts to generate avg model, it exported successfully, it seems one of the pts has some problems. I checked the loss, it's normal

It does happen sometimes. As long as the final accuracy of the test set does not drop, it should be ok.

**Comment by fclearner** [comment]
> > I used another 5 pts to generate avg model, it exported successfully, it seems one of the pts has some problems. I checked the loss, it's normal
> 
> It does happen sometimes. As long as the final accuracy of the test set does not drop, it should be ok.

Thanks, what may cause the problem

**Comment by Yymax-max** [comment]
i also meeting this problem.


Traceback (most recent call last):
  File "/code/wenet/wenet/bin/export_onnx_cpu.py", line 411, in <module>
    main()
  File "/code/wenet/wenet/bin/export_onnx_cpu.py", line 405, in main
    export_encoder(model, arguments)
  File "/code/wenet/wenet/bin/export_onnx_cpu.py", line 242, in export_encoder
    rtol=1e-03, atol=1e-05)
  File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatched elements: 31 / 81920 (0.0378%)
Max absolute difference: 6.1534345e-05
Max relative difference: 1.7221433
 x: array([[[ 0.143052, -0.392932, -0.089075, ...,  0.014161,  0.588814,
          0.328658],
        [-0.105244,  0.072099,  0.071646, ..., -0.004309,  0.073117,...
 y: array([[[ 0.143052, -0.392932, -0.089075, ...,  0.014162,  0.588814,
          0.328658],
        [-0.105244,  0.072099,  0.071646, ..., -0.004309,  0.073117,...

how can i do

**Comment by Yymax-max** [comment]
> > i also meeting this problem.
> > Traceback (most recent call last): File "/code/wenet/wenet/bin/export_onnx_cpu.py", line 411, in main() File "/code/wenet/wenet/bin/export_onnx_cpu.py", line 405, in main export_encoder(model, arguments) File "/code/wenet/wenet/bin/export_onnx_cpu.py", line 242, in export_encoder rtol=1e-03, atol=1e-05) File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 1531, in assert_allclose verbose=verbose, header=header, equal_nan=equal_nan) File "/opt/conda/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare raise AssertionError(msg) AssertionError: Not equal to tolerance rtol=0.001, atol=1e-05
> > Mismatched elements: 31 / 81920 (0.0378%) Max absolute difference: 6.1534345e-05 Max relative difference: 1.7221433 x: array([[[ 0.143052, -0.392932, -0.089075, ..., 0.014161, 0.588814, 0.328658], [-0.105244, 0.072099, 0.071646, ..., -0.004309, 0.073117,... y: array([[[ 0.143052, -0.392932, -0.089075, ..., 0.014162, 0.588814, 0.328658], [-0.105244, 0.072099, 0.071646, ..., -0.004309, 0.073117,...
> > how can i do
> 
> try another pt file maybe help

i try more than one pt , it meet same problem.and then i shut down  export_onnx_cpu.py -> export_encoder() -> np.testing.assert_allclose ,it is ok.and  the final accuracy of the test set does not drop more. can i do like this ?
