### ISSUE TITLE
lfmmi fails to run and cannot train！

### ISSUE THREAD

**Issue by thsxbw** [wenet-e2e/wenet#1828]
Hello, I try to reproduce lfmmi in aishell/s0 （The latest version of wenet）,but run.sh did not run successfullys，

“Run LF-MMI training from stage 4, with below new args --lfmmi_dir data/local/lfmmi”, error after running：

    "RuntimeError:
       General Union types are not currently supported. Only Unin[T, NoneType]（i.e. Optional[T]） is suppoted".

If I comment out “script_model=torch.jit.script(model)” and “script_model.save(os.path.join(args.model_dir,'init.zip'))”，this problem will not occur，but will appear

 “Warning: NaN or Inf found in input tensor. TRAIN Batch 0/0 loss inf loss_att 66.303215 loss_ctc inf lr 0.00000008 rand 0”

 and it cannot be iterated.

 Can you tell me how to correct it?

**Comment by robin1001** [comment]
@aluminumbox any solution?

**Comment by Ryuk17** [comment]
I solved by updating torch to 1.12.

**Comment by thsxbw** [comment]
> I solved by updating torch to 1.12.

my torch version is 2.0.0+cu117,but error in torch.jit.script(model)
