### ISSUE TITLE
Experiment Environment

### ISSUE THREAD

**Issue by 2choonghyeon** [wenet-e2e/wenet#1829]
Thank you for your awesome work!

Could you inform me of what type of GPUs you used in this experiment and how it took to train rnnt until 60 epochs?

I performed this experiment using 4 V100 gpus but it was too slow.

![image](https://user-images.githubusercontent.com/60165597/233586102-60ffe23c-1b4f-4e3c-b3f8-205833aaad91.png)

**Comment by robin1001** [comment]
@yuekaizhang it was on 8GPU V100?
