### ISSUE TITLE
How to modify files in Raspberry_Pi_runtime to achieve real-time speech recognition

### ISSUE THREAD

**Issue by Jong-cx** [wenet-e2e/wenet#1831]
Thanks for your excellent work，I have already implemented voice recognition from a file on Raspberry Pi, but I wonder how to modify this file to read data from a voice sensor (serial port) and perform real-time recognition. I can read voice data through a serial port and decode the voice signal,I would be very appreciate if you could give me any advice.

**Comment by robin1001** [comment]
You can you `portaudio`, please refer our implementation in `wekws`,  see https://github.com/wenet-e2e/wekws/blob/main/runtime/core/bin/stream_kws_main.cc#L65-L103 for details.

**Comment by Jong-cx** [comment]
Thank you very much for your suggestion. I will try it as soon as possible.&nbsp;
Thank you again for your suggestion



---Original---
From: ***@***.***&gt;
Date: Sat, Apr 22, 2023 17:45 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wenet-e2e/wenet] How to modify files in Raspberry_Pi_runtime toachieve real-time speech recognition (Issue #1831)




 
Or you can refer this pull request: https://github.com/wenet-e2e/wenet/pull/1157/files
