### ISSUE TITLE
tools/decode.sh

### ISSUE THREAD

**Issue by wwfcnu** [wenet-e2e/wenet#1832]
./tools/decode.sh: line 65: 24089 Aborted                 decoder_main --rescoring_weight $rescoring_weight --ctc_weight $ctc_weight --reverse_weight $r
everse_weight --chunk_size $chunk_size --wav_scp ${dir}/split${nj}/wav.${n}.scp --model_path $model_file --unit_path $unit_file $wfst_decode_opts --resu
lt ${dir}/split${nj}/${n}.text &> ${dir}/split${nj}/${n}.log

**Comment by qipotianMFXT** [comment]
Hello, may I ask if you have solved this problem?
