### ISSUE TITLE
我在libtorch里使用自己训练的final.zip运行时出现一下错误

### ISSUE THREAD

**Issue by lzy473** [wenet-e2e/wenet#1833]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lzy473** [comment]
![image](https://user-images.githubusercontent.com/127758069/233775425-41886aaa-9289-40e8-b282-886bc6216afc.png)

**Comment by robin1001** [comment]
查看一下 pytorch 和 libtorch 的版本。

**Comment by lzy473** [comment]
这是pytorch的版本
![image](https://user-images.githubusercontent.com/127758069/233921862-e9af453e-91cd-4314-8264-0bb610d19995.png)
这是liborch的版本
![Uploading image.png…]()

**Comment by lzy473** [comment]
我使用这个他是可以运行的，替换了词典和.zip和train.yaml就使用不了   是不是需要修改什么东西才能使用
![image](https://user-images.githubusercontent.com/127758069/233947626-ec34a165-e400-43c9-8e27-ed8106e1ed71.png)

**Comment by DaobinZhu** [comment]
你的模型必须和yaml配置文件，还有字典匹配，要不然就会报错

**Comment by lzy473** [comment]
是匹配的  但是还是报错
