### ISSUE TITLE
Saving Model Checkpoint after some fixed steps rather than after every epoch

### ISSUE THREAD

**Issue by dipeshhoncho07** [wenet-e2e/wenet#1839]
Hello!

Is it possible to save checkpoints during training at regular intervals instead of just at the end of each epoch. This can be useful for large scale training where it is risky to wait until the end of an epoch to save a checkpoint.

By saving checkpoints after a fixed number of steps, you can minimize the amount of progress lost in case the training process is interrupted or fails.

To implement this, you can modify the code that saves checkpoints to include a check for the number of steps taken since the last checkpoint. Once the number of steps exceeds a pre-determined value, the checkpoint can be saved and the step count reset.

By doing this, you can control the frequency of checkpoints and minimize the amount of progress that is lost in case of failure.

I am requesting repository owners to kindly update the codebase for the same or if it is already there then please let me know how to use?

**Comment by xingchensong** [comment]
could you help to make a PR for this feature？
