### ISSUE TITLE
python multithreading streaming decoder

### ISSUE THREAD

**Issue by eschmidbauer** [wenet-e2e/wenet#1843]
When I initialize a decoder and share it between threads, the results contain data from different threads.

```python
class ASR():
    def __init__(self):
        self.decoder = wenet.Decoder(
            lang='en', nbest=1, enable_timestamp=False, continuous_decoding=False)

    async def handler(self, data):
        while True:
            d = await data.recv()
            result: str = self.decode(d, False)
```

I would expect the decoder to not share result data between threads. Is there a way to solve this other than initializing separate decoders for each thread?

**Comment by Mddct** [comment]
Decoder needs to implement clone and get rid of gil lock

**Comment by eschmidbauer** [comment]
thanks for the feedback, happy to contribute but this seems a bit over my head. If you can point me to some documentation or code, I will give it a try

**Comment by Mddct** [comment]
Wenet runtime is depreciated now
,plz use wenet cli, thx
