### ISSUE TITLE
AED模型和RNNT模型的CTC部分输出结果差距过大

### ISSUE THREAD

**Issue by DaobinZhu** [wenet-e2e/wenet#1847]
我做了一个知识蒸馏的操作，将CTC-AED预训练模型作为教师模型，RNNT模型作为学生模型，但是当我发现这两种模型的CTC输出结果ys_hat差距很大，KL损失也很大，并且并不会随着训练明显变小，相比于解码器部分这个损失很大：
ys_hat的KL损失：
![image](https://user-images.githubusercontent.com/37605608/236663439-6a4e1835-0231-4d91-a71c-6434dc668a01.png)
decoder的KL损失：
![image](https://user-images.githubusercontent.com/37605608/236663476-9325369a-1c38-4599-9efc-f5c2dc2d7d4e.png)
我又将两个ys_hat的值保存到了一个文件里进行比较，发现值的差距很大：

RNN-T的ys_hat:
tensor([[-8.5914, -9.0425, -7.7584,  ..., -8.7676, -7.4026, -8.2635],
        [-8.8213, -8.6570, -8.2492,  ..., -8.7954, -8.8066, -8.1021],
        [-8.9251, -8.7901, -8.1005,  ..., -8.6092, -8.8321, -8.6746],
        [-8.4846, -9.9141, -8.1765,  ..., -8.2617, -8.7680, -8.1899],
        [-9.2111, -9.0205, -8.3390,  ..., -9.1331, -8.5224, -7.6538]],
       device='cuda:0', grad_fn=<UnbindBackward0>)
CTC-AED的ys_hat:
tensor([[-8.5830e-06, -2.8463e+01, -1.6019e+01,  ..., -2.4002e+01,
         -2.6245e+01, -2.8287e+01],
        [-7.1525e-06, -2.8625e+01, -1.6042e+01,  ..., -2.4216e+01,
         -2.6434e+01, -2.8483e+01],
        [-7.3909e-06, -2.8566e+01, -1.6154e+01,  ..., -2.4186e+01,
         -2.6406e+01, -2.8397e+01],
        [-8.4638e-06, -2.8427e+01, -1.5925e+01,  ..., -2.3511e+01,
         -2.6370e+01, -2.8248e+01],
        [-1.4186e-05, -2.7974e+01, -1.5711e+01,  ..., -2.3213e+01,
         -2.6014e+01, -2.7814e+01]], device='cuda:0')

我查看了源码，发现这两个模型的CTC部分都是调用的https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/ctc.py，为什么ys_hat的差距会这么大呢？求指教

**Comment by robin1001** [comment]
是在已有训好的模型基础上做蒸馏还是从头开始训练？

**Comment by DaobinZhu** [comment]
学生模型是从头开始训练的，教师模型用的wenet提供的预训练模型



---原始邮件---
发件人: "Binbin ***@***.***&gt;
发送时间: 2023年5月8日(周一) 上午9:06
收件人: ***@***.***&gt;;
抄送: "Daobin ***@***.******@***.***&gt;;
主题: Re: [wenet-e2e/wenet] AED模型和RNNT模型的CTC部分输出结果差距过大 (Issue #1847)




 
是在已有训好的模型基础上做蒸馏还是从头开始训练？
