### ISSUE TITLE
识别时没有声音也会得到重复的字，训练集是自己从电视剧里面截的

### ISSUE THREAD

**Issue by segu-L** [wenet-e2e/wenet#1848]
![image](https://user-images.githubusercontent.com/61747149/236853113-9f93b8af-dd6e-4787-8c5a-925f10eb4a96.png)

训练时的配置文件是train_u2++_efficonformer_v2.yaml

chunk_size设置为-1的时候，非流式识别效果正常。chunk_size设置为16，流式识别时，没有声音也会出重复的字。

**Comment by robin1001** [comment]
你自己训练的模型？

**Comment by segu-L** [comment]
是的
