### ISSUE TITLE
question on wenetruntime

### ISSUE THREAD

**Issue by kelvinqin** [wenet-e2e/wenet#1851]
When we use decode_main to do decoding, we can apply several parameters likes:
    --beam 
    --lattice_beam
    --max_active
    --blank_skip_thresh
    --ctc_weight
    --rescoring_weight
    --reverse_weight
    --chunk_size
    --acoustic_scale

My question is whether wenetruntime support those parameters? if not, what is the purpose please?

**Comment by Mddct** [comment]
weneruntime is depreciated plz
 use wenet cli, thx
