### ISSUE TITLE
paraformer结果无法复现

### ISSUE THREAD

**Issue by hungker** [wenet-e2e/wenet#1852]
我尝试一下跑了aishell中的paraformer,  按照run.sh中的步骤进行训练，测试结果为：greedy_search: cer = 6.03 %,  beam_search: cer=5.84%, 和README中的结果差距较大，请问README中的结果是否是这套代码跑出来的结果。另外，我发现直接使用这套代码推理会有问题，更改了部分代码。具体更改在：paraformer.py的calc_predictor函数中注释掉encoder_mask操作：
` def calc_predictor(self, encoder_out, encoder_mask):

        #encoder_mask = (~make_pad_mask(
            encoder_mask, max_len=encoder_out.size(1))[:, None, :]).to(
                encoder_out.device)
        pre_acoustic_embeds, pre_token_length, alphas, pre_peak_index = \
            self.predictor(
                encoder_out, None,
                encoder_mask,
                ignore_id=self.ignore_id)
        return pre_acoustic_embeds, pre_token_length, alphas, pre_peak_index`
另外，在paraformer_greedy_search和paraformer_greedy_search函数中将self.cal_decoder_with_predictor的第二个参数改为encoder_mask。
`decoder_outs = self.cal_decoder_with_predictor(encoder_out,
                                                       encoder_mask,
                                                       pre_acoustic_embeds,
                                                       pre_token_length)`

**Comment by JucyCherry** [comment]
我也遇到了一样的问题，推理时会报楼主的错误

**Comment by robin1001** [comment]
@MrSupW @Mddct could you please help to figure out the problem?

**Comment by Mddct** [comment]
请使用最新的实现 之前的已经废弃掉了
