### ISSUE TITLE
ipex runtime problem.

### ISSUE THREAD

**Issue by NathanJHLee** [wenet-e2e/wenet#1856]
Hi my name is Nathan. 
I am trying to implement ipex according to 'wenet/tree/main/runtime/ipex/
README.md'

I use a docker container and conda environment and finished env setting.
But i got error 

First, decoder_main dependencies.
**(base) [asr@aa026e4b97df bin]$ ldd decoder_main**
        linux-vdso.so.1 =>  (0x00007ffc3e7fb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f4c132f6000)
        libtorch.so => /ws/stt/Models/JHLEE/wenet-main_20230516_ipex/runtime/ipex/fc_base/libtorch-src/lib/libtorch.so (0x00007f4c1370d000)
        libtorch_cpu.so => /ws/stt/Models/JHLEE/wenet-main_20230516_ipex/runtime/ipex/fc_base/libtorch-src/lib/libtorch_cpu.so (0x00007f4bf8f96000)
        libc10.so => /ws/stt/Models/JHLEE/wenet-main_20230516_ipex/runtime/ipex/fc_base/libtorch-src/lib/libc10.so (0x00007f4c13656000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f4bf8d7a000)
        libintel-ext-pt-cpu.so => /ws/stt/Models/JHLEE/wenet-main_20230516_ipex/runtime/ipex/fc_base/libtorch-src/lib/libintel-ext-pt-cpu.so (0x00007f4bf24c9000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f4bf21c1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f4bf1ebf000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f4bf1ca9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f4bf18db000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4c134fa000)
        libgomp-a34b3233.so.1 => /ws/stt/Models/JHLEE/wenet-main_20230516_ipex/runtime/ipex/fc_base/libtorch-src/lib/libgomp-a34b3233.so.1 (0x00007f4bf16b1000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f4bf14a9000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f4bf1293000)

   I trained a model in torch1.10.0 version and converted it to a ipex model. 

When I run binary file.
(base) [asr@aa026e4b97df bin]$ export GLOG_logtostderr=1
(base) [asr@aa026e4b97df bin]$ export GLOG_v=2
(base) [asr@aa026e4b97df bin]$ ipexrun --no_python \
> ./decoder_main --chunk_size -1 --sample_rate 8000 --thread_num 10 warmup 1 \
> --wav_scp /ws/stt/Models/JHLEE/wenet-main/examples/aishell/s0/data_kspon969/test_clean_kspon/wav_ipex.scp \
> --model_path /ws/stt/Models/JHLEE/wenet-main/examples/aishell/s0/exp/conformer_kspon_with_space/final_quant_ipex.zip \
> --unit_path /ws/stt/Models/JHLEE/wenet-main/examples/aishell/s0/data_kspon969/dict/lang_char.txt

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "/home/asr/miniconda3/bin/ipexrun", line 8, in <module>
    sys.exit(main())
  File "/home/asr/miniconda3/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 881, in main
    launcher.launch(args)
  File "/home/asr/miniconda3/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 448, in launch
    numactl_available = self.is_numactl_available()
  File "/home/asr/miniconda3/lib/python3.9/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 263, in is_numactl_available
    r = subprocess.run(cmd, env=os.environ, stdout=subprocess.DEVNULL)
  File "/home/asr/miniconda3/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/asr/miniconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/asr/miniconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'numactl'

Please check my problem. Thank you.

my env is below
**(base) [asr@aa026e4b97df bin]$ python --version**
Python 3.9.12

**(base) [asr@aa026e4b97df bin]$ rpm -qa | grep gperftools**
gperftools-libs-2.6.1-1.el7.x86_64
gperftools-2.6.1-1.el7.x86_64
gperftools-devel-2.6.1-1.el7.x86_64

**(base) [asr@aa026e4b97df bin]$ pip list**
Package                     Version
--------------------------- ------------
absl-py                     1.1.0
attrs                       21.4.0
boltons                     23.0.0
brotlipy                    0.7.0
cachetools                  5.2.0
certifi                     2023.5.7
cffi                        1.15.1
charset-normalizer          2.0.4
conda                       23.3.1
conda-package-handling      2.0.2
conda_package_streaming     0.7.0
cryptography                39.0.1
flake8                      3.8.2
flake8-bugbear              22.6.22
flake8-comprehensions       3.10.0
flake8-executable           2.1.1
flake8-pyi                  20.5.0
google-auth                 2.8.0
google-auth-oauthlib        0.4.6
grpcio                      1.47.0
idna                        3.4
importlib-metadata          4.12.0
iniconfig                   1.1.1
**intel-extension-for-pytorch 1.13.100+cpu**
**intel-openmp                2023.1.0**           #<---it's installed by a whl file.
jsonpatch                   1.32
jsonpointer                 2.1
Markdown                    3.3.7
mccabe                      0.6.1
mkl-fft                     1.3.1
mkl-random                  1.2.2
mkl-service                 2.4.0
numpy                       1.24.3
oauthlib                    3.2.0
packaging                   23.0
Pillow                      9.4.0
pip                         23.0.1
pluggy                      1.0.0
protobuf                    3.19.4
psutil                      5.9.1
py                          1.11.0
pyasn1                      0.4.8
pyasn1-modules              0.2.8
pycodestyle                 2.6.0
pycosat                     0.6.4
pycparser                   2.21
pyflakes                    2.2.0
pyOpenSSL                   23.0.0
pyparsing                   3.0.9
PySocks                     1.7.1
pytest                      7.1.2
PyYAML                      6.0
requests                    2.29.0
requests-oauthlib           1.3.1
rsa                         4.8
ruamel.yaml                 0.17.21
ruamel.yaml.clib            0.2.6
sentencepiece               0.1.96
setuptools                  66.0.0
six                         1.16.0
tensorboard                 2.9.1
tensorboard-data-server     0.6.1
tensorboard-plugin-wit      1.8.1
tensorboardX                2.5.1
TextGrid                    1.5
tomli                       2.0.1
toolz                       0.12.0
torch                       1.13.0
torchaudio                  0.13.0
torchvision                 0.14.0
tqdm                        4.65.0
typeguard                   2.13.3
typing_extensions           4.5.0
urllib3                     1.26.15
Werkzeug                    2.1.2
wheel                       0.38.4
zipp                        3.8.0
zstandard                   0.19.0

**Comment by NathanJHLee** [comment]
I found a reason.
My env does not have numactl packages.
so I install rpm and it works.

Centos 7 env
numactl-2.0.12-5.el7.x86_64.rpm
numactl-libs-2.0.12-5.el7.x86_64.rpm

Thank you.

**Comment by xingchensong** [comment]
@ZailiWang Hi, could u do us a favor?

**Comment by ZailiWang** [comment]
Hi Nathan,

By saying "But when i run decoder_main, first few inference is fine, after then it seems hang up."

what is the exact command? It's a bit confusing since initially you reported a "No such file or directory: 'numactl'" error, not a hang up. Would you please clarify this?

**Comment by NathanJHLee** [comment]
Hi ZailiWang.
As you mentioned, I try to run without 'ipexrun', But it not working.

So I changed other options to check work properly.
I found some problem that sometime doesn't work depending on 'thread_num'.(please check it later)
only "thread_num=1" works properly.
So, I change --thread-num to '1'.
Then both of decoding works fine.
run "**ipexrun --no_python ./decoder_main** --chunk_size -1 --sample_rate 8000 **--thread_num 1** warmup 1 
         --wav_scp wav_ipex.scp --model_path final_quant_ipex.zip --unit_path lang_char.txt " 
run "**./decoder_main** --chunk_size -1 --sample_rate 8000 **--thread_num 1** warmup 1 
         --wav_scp wav_ipex.scp --model_path final_quant_ipex.zip --unit_path lang_char.txt " 

But warmup time takes too long than i expected. in this case, it needs 3min.

And, Please check my log especially "numactl " below.
numactl doesn't work fine in a log.
Thank you so much.

(base) [asr@aa026e4b97df bin]$ **ipexrun --no_python ./decoder_main** --chunk_size -1 --sample_rate 8000 --thread_num 1 warmup 1 --wav_scp /ws/stt/Models/JHLEE/wenet-main/examples/aishell/s0/data_kspon969/test_clean_kspon/wav_ipex.scp --model_path /ws/stt/Models/JHLEE/wenet-main/examples/aishell/s0/exp/conformer_kspon_with_space/final_quant_ipex.zip --unit_path /ws/stt/Models/JHLEE/wenet-main/examples/aishell/s0/data_kspon969/dict/lang_char.txt


No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
set_mempolicy: Operation not permitted
setting membind: Operation not permitted
**2023-05-22 11:04:22,146 - intel_extension_for_pytorch.cpu.launch - WARNING - Core binding with numactl is not available. Disabling numactl and using taskset instead. This may affect performance in multi-socket system; please use numactl if memory binding is needed.**
2023-05-22 11:04:22,147 - intel_extension_for_pytorch.cpu.launch - INFO - Use TCMalloc memory allocator
2023-05-22 11:04:22,147 - intel_extension_for_pytorch.cpu.launch - INFO - OMP_NUM_THREADS=40
2023-05-22 11:04:22,147 - intel_extension_for_pytorch.cpu.launch - INFO - Using Intel OpenMP
2023-05-22 11:04:22,147 - intel_extension_for_pytorch.cpu.launch - INFO - KMP_AFFINITY=granularity=fine,compact,1,0
2023-05-22 11:04:22,147 - intel_extension_for_pytorch.cpu.launch - INFO - KMP_BLOCKTIME=1
2023-05-22 11:04:22,147 - intel_extension_for_pytorch.cpu.launch - INFO - LD_PRELOAD=/home/asr1/miniconda3/lib/libiomp5.so:/usr/lib64/libtcmalloc.so
2023-05-22 11:04:22,147 - intel_extension_for_pytorch.cpu.launch - INFO - taskset -c 0-39 ./decoder_main --chunk_size -1 --sample_rate 8000 --thread_num 1 warmup 1 --wav_scp /ws/stt/Models/JHLEE/wenet-main/examples/aishell/s0/data_kspon969/test_clean_kspon/wav_ipex.scp --model_path /ws/stt/Models/JHLEE/wenet-main/examples/aishell/s0/exp/conformer_kspon_with_space/final_quant_ipex.zip --unit_path /ws/stt/Models/JHLEE/wenet-main/examples/aishell/s0/data_kspon969/dict/lang_char.txt
I0522 11:04:22.539285 11166 params.h:155] Reading torch model /ws/stt/Models/JHLEE/wenet-main/examples/aishell/s0/exp/conformer_kspon_with_space/final_quant_ipex.zip
I0522 11:04:23.312954 11166 torch_asr_model.cc:35] Num intra-op threads: 1
I0522 11:04:24.597815 11166 torch_asr_model.cc:73] Torch Model Info:
I0522 11:04:24.597837 11166 torch_asr_model.cc:74]      subsampling_rate 4
I0522 11:04:24.597842 11166 torch_asr_model.cc:75]      right context 6
I0522 11:04:24.597846 11166 torch_asr_model.cc:76]      sos 2166
I0522 11:04:24.597848 11166 torch_asr_model.cc:77]      eos 2166
I0522 11:04:24.597853 11166 torch_asr_model.cc:78]      is bidirectional decoder 1

**Comment by ZailiWang** [comment]
Hi Nathan, I failed to re-produce the issue you met, would you please run the script for env collection
https://github.com/pytorch/pytorch/blob/main/torch/utils/collect_env.py
and paste the output for me so that I can try to set up an identical env and re-produce the issue first.

**Comment by ZailiWang** [comment]
I'd also ask if you have tried to export & use your model with stock libTorch (without ipex)? Does it work fine? This is to confirm if the issue is ipex specific.

**Comment by ZailiWang** [comment]
seems good, congrats, enjoy using ipex :-)

**Comment by ZailiWang** [comment]
Hi Nathan,
No problem, thanks for using IPEX. Would you please tell your mailbox so we can discuss more about IPEX?
We are trying to expand IPEX influence and also collect user experience feedbacks/requirements for next step development.

**Comment by NathanJHLee** [comment]
Sorry for belated reply. I was on vacation. 
Of course. Thank you for suggesting me to expand ipex.
My email address junghan4242@naver.com
Please send me a e-mail. Thank you.
