### ISSUE TITLE
config文件不支持mfcc特征提取方法，如果我想使用mfcc，我该如何配置相关参数？

### ISSUE THREAD

**Issue by newuserforstudy** [wenet-e2e/wenet#1857]
mfcc_conf ？

**Comment by xingchensong** [comment]
是的，mfcc_conf。

https://github.com/wenet-e2e/wenet/blob/main/wenet/dataset/dataset.py#L165-L166

**Comment by newuserforstudy** [comment]
> 是的，mfcc_conf。
> 
> https://github.com/wenet-e2e/wenet/blob/main/wenet/dataset/dataset.py#L165-L166
代码里面是有用到mfcc_conf，但是在yaml文件中mfcc_conf参数是没有配置的。请问mfcc_conf参数是怎样的？我查看mfcc和fbank是不一样的，但是我想用mfcc。

**Comment by cdliang11** [comment]
> > 是的，mfcc_conf。
> > https://github.com/wenet-e2e/wenet/blob/main/wenet/dataset/dataset.py#L165-L166
> > 代码里面是有用到mfcc_conf，但是在yaml文件中mfcc_conf参数是没有配置的。请问mfcc_conf参数是怎样的？我查看mfcc和fbank是不一样的，但是我想用mfcc。

需要自己改一下yaml文件，将fbank_conf替换掉，具体内容参考：https://github.com/wenet-e2e/wenet/blob/e657753d4d197dbf8481159e5870c6e4aae6a6ea/wenet/dataset/processor.py#L285

**Comment by newuserforstudy** [comment]
我觉得问题并没有解决！！！
首先，yaml文件中并没有关于mfcc_conf的选项(尽管代码中有写但是并没有真正执行到该行，因为用的是fbank特征)；
其次，fbank特征和mfcc特征并相同，使用的参数也是不相同的，我查看了torchaudio和librosa关于fbank和mfcc的API，但是我还是不知道什么的参数合适u2++模型，代码中的关于mfcc的默认值参数似乎是不合理的，所以我在wenet的提问没有得到似乎正确的回到。
最后，我经过查询似乎mfcc特征相比fbank在语音识别中应该是更优的选择，为什么wenet中使用fbank且毫不关心mfcc？难道是作者在精度和速度的折中选择？望回复！

**Comment by cdliang11** [comment]
> 我觉得问题并没有解决！！！ 首先，yaml文件中并没有关于mfcc_conf的选项(尽管代码中有写但是并没有真正执行到该行，因为用的是fbank特征)； 其次，fbank特征和mfcc特征并相同，使用的参数也是不相同的，我查看了torchaudio和librosa关于fbank和mfcc的API，但是我还是不知道什么的参数合适u2++模型，代码中的关于mfcc的默认值参数似乎是不合理的，所以我在wenet的提问没有得到似乎正确的回到。 最后，我经过查询似乎mfcc特征相比fbank在语音识别中应该是更优的选择，为什么wenet中使用fbank且毫不关心mfcc？难道是作者在精度和速度的折中选择？望回复！

fbank特征更多是希望符合声音信号的本质，拟合人耳的接收特性。
DCT是线性变换，会丢失语音信号中原本的一些高度非线性成分。在深度学习之前，受限于算法，mfcc配GMMs-HMMs是ASR的主流做法。当深度学习方法出来之后，由于神经网络对高度相关的信息不敏感，mfcc不是最优选择，经过实际验证，其在神经网络中的表现也明显不如fbank。（ref：https://zhuanlan.zhihu.com/p/130926693）
MFCC引入的DCT去相关更多的是为了后面的GMM建模，而且DCT运算量更大。（ref：http://fancyerii.github.io/books/mfcc/）

因此wenet中采用fbank特征 😊
