### ISSUE TITLE
wenet/bin/recognize.py load模型bug

### ISSUE THREAD

**Issue by CodeMonkZy** [wenet-e2e/wenet#1858]
第291行代码，load_checkpoint(model, args.checkpoint)
函数没有返回 model，在load_checkpoint函数内部将checkpoint的权重load进来，recognize.py里之后的model都是没有load的吧。

**Comment by cdliang11** [comment]
哈喽，load_checkpoint函数内部load了权重，对应recognition里model权重已经改变了，这是python中函数值传递问题，请参考这个链接：https://zhuanlan.zhihu.com/p/69746955?utm_source=wechat_session
