### ISSUE TITLE
any one had success  in  fine tuning ?

### ISSUE THREAD

**Issue by jayakrishnanmm** [wenet-e2e/wenet#1859]
.
I have been following  up  #1397 quite recently. It looks  no one had  success in fine tuning with about 50  or 100 hour of out of domain data .
1. Performance on the  original in-domain test  set drops if  we  use use only out of domain data to fine tune. So the suggested  alternative is to sample (5% or 10%)  the original data set  used  for  training  and  use  it with  out of domain train set  to  fine tune. This  assume  that  the  original units.txt  is  un touched. But again the problem could be like,  we  are  not  considering the new words in the out of domain data. Because it cannot be  recognized by the model (Unless  BPE  cannot  make it from existing sub words  in the  units.txt)
2. So that  comes to  expanding the  units.txt. But if we  do this, then input model  shape  error comes, since  the  base model  input shape[0] is different  from the expanded units.txt size . How to  resolve this ?

**Comment by robin1001** [comment]
why BPE can not make the new words? New language?

**Comment by jayakrishnanmm** [comment]
Since  the  BPE  model  is  trained  using  the  training text, (in this  case  the  original in-domain)  it is likely that adapted  text (out of  domain) may contain words  that  cannot  be made up  by the  sub words from original units.txt

**Comment by SevenTailCat** [comment]
I tried adding new tokens, changing embed and output_layer, and ctc_lo. The result was a problem where the training loss dropped, but no results were identified.
