### ISSUE TITLE
need a parallel inference program

### ISSUE THREAD

**Issue by boji123** [wenet-e2e/wenet#186]
it would be great if wenet have a parallel inference program to speed up the decoding procedure

**Comment by robin1001** [comment]
If gpu is used for decoding, it is fast enough. For cpu, it maybe quite slow.

**Comment by boji123** [comment]
i mean multi thread or multi process，like espnet or kaldi

**Comment by robin1001** [comment]
Yes, if you want to be faster, just use GPU for decoding. I think it's fast enough. And there is no plan to support multiple thread decoding on CPU in the near future. Sorry about that.

**Comment by boji123** [comment]
solved, GPU is fast enough

**Comment by zhxiqing** [comment]
> solved, GPU is fast enough


Do you mind describing in detail how to use GPU for decoding in RUNTIME?

**Comment by travisCxy** [comment]
@boji123 hello, can u share your method about how to use GPU for decoding

**Comment by Mddct** [comment]
decoder_main support multi_thread to decode utterance,  plz see: https://github.com/wenet-e2e/wenet/pull/1198
