### ISSUE TITLE
Question :: Torch Num Threads

### ISSUE THREAD

**Issue by madkote** [wenet-e2e/wenet#1861]
Hi, I have two question:

(1) By default `Torch Num Threads` is equal 1. in which cases, the value should increased and which influence it will have on performance?
(2) number of torch threads is for each recognizer or for each loaded model?

Use case:
- web service
- load the model
- create multiple recognizers / channels in parallel

So far I have tested, increasing torch threads does not bring any performance gains. Sometime, recognizer become even slower with many torch threads.

Thanks!

**Comment by robin1001** [comment]
1. `num threads` is for GEMM for neural network inference.
2. Yes, it's for each recongizer.


Increasing the num threads when test offline. you can get better real time factor.
Limit the num threads in web service, you can get more concurrency.
