### ISSUE TITLE
Decoding problem in NST recipe

### ISSUE THREAD

**Issue by ZihanLiao** [wenet-e2e/wenet#1862]
When doing `decode.sh `in aishell/NST/run_nst.sh, the following error occurred. Seems like when adding the param --fst_path, we have to give full information for the fst options which means we should specify our --dict_path.
Please let me know if I understand this correctly
![image](https://github.com/wenet-e2e/wenet/assets/54339989/c159dedd-b2e8-43a1-9b6d-b5cf7b83b4ba)

![image](https://github.com/wenet-e2e/wenet/assets/54339989/c568a318-f19b-4ef4-9876-5300961a6f50)

**Comment by robin1001** [comment]
Yes, --dict_path should be specified for decoding with FST. would you please help to fix the bug?

**Comment by ZihanLiao** [comment]
> Yes, --dict_path should be specified for decoding with FST. would you please help to fix the bug?

Thanks for the quick reply. When I'm validating the result after fixing the glitch, I met the problem same with [https://github.com/wenet-e2e/wenet/issues/1838].
![image](https://github.com/wenet-e2e/wenet/assets/54339989/e3de22ff-cd3f-4953-90ba-3b25df323cd7)

My ingredients are as follows:
Acoustic Model: wenetspeech pre-trained model (20220506_u2pp_conformer_exp)
Language Model(TLG): 3-gram language model trained using aishell
![image](https://github.com/wenet-e2e/wenet/assets/54339989/a4f58f94-6a3e-46b8-ad3c-24225900429c)

**Comment by ZihanLiao** [comment]
After some code reading, I think the problem might be `chunk_size` setting in the `asr_decoder.cc`.
If we set chunk_size=-1(by default) at the shell level, we would run into this branch which set `num_required_frames = std::numeric_limits<int>::max();`
![image](https://github.com/wenet-e2e/wenet/assets/54339989/94c06bd3-0c7c-4724-8938-1ab0b8623121)

![image](https://github.com/wenet-e2e/wenet/assets/54339989/7048786f-d487-41cb-a47d-523ebf5deacb)
Please let me know if I understand this thing right.

**Comment by ZihanLiao** [comment]
> Yes, --dict_path should be specified for decoding with FST. would you please help to fix the bug?

https://github.com/wenet-e2e/wenet/pull/1863
