### ISSUE TITLE
加入新的token后，微调模型时出现无法识别的问题

### ISSUE THREAD

**Issue by SevenTailCat** [wenet-e2e/wenet#1865]
以20210815_unified_conformer_exp中的final.pt为预训练模型，改变decode.embed中的Embedding的长度，加入两个新token的256维参数。然后修改units.txt、output_layer和ctc_lo为对应长度。
以wenetspeech中抽取的大概10个小时数据作为训练集，无法正常识别。
第一轮训练如下：
![c02f81d0d95358f35f07c4a2c0c10e2](https://github.com/wenet-e2e/wenet/assets/16370705/875da0e0-32a8-4dec-8345-0c7cbb97df80)
第三轮训练结果如下：
![1ec1c64e851e0dc1ef99f0535298bd8](https://github.com/wenet-e2e/wenet/assets/16370705/f06255b2-3eb6-43f5-81c1-bdedb7d02857)
从第三轮之后，一直没有结果了。loss正常下降。
在训练过程中，我从forward内冻结了encode，decode.decoders，仅仅保留ctc.ctc_lo、decode.output_layer, decode.embed参与训练。

**Comment by xingchensong** [comment]
可能10h数据太少了，你看看cvloss的变化趋势

**Comment by SevenTailCat** [comment]
> 可能10h数据太少了，你看cvloss的变化趋势

cv_loss下降到一定程度，开始缓慢上升。。。

**Comment by xingchensong** [comment]
> > 可能10h数据太少了，你看cvloss的变化趋势
> 
> cv_loss下降到一定程度，开始缓慢上升。。。

那就是模型没训好了，10h数据比较少的原因

**Comment by SevenTailCat** [comment]
我增加了一些数据，然后目前loss如下：
![5a6305330a1705f7d6be1344f057f56](https://github.com/wenet-e2e/wenet/assets/16370705/0d510c56-3b49-499d-a9a2-f284c74a38e2)
感觉不太对。。。

**Comment by fclearner** [comment]
> 我增加了一些数据，然后目前loss如下： ![5a6305330a1705f7d6be1344f057f56](https://user-images.githubusercontent.com/16370705/241662888-0d510c56-3b49-499d-a9a2-f284c74a38e2.png) ![image](https://user-images.githubusercontent.com/16370705/241665768-32dc8772-9084-48fe-820a-8d747342229e.png) 感觉不太对。。。

我感觉你这个更像是数据处理或者模型配置出问题了，一般10小时finetune也不会导致通用效果变得这么差啊，模型训练配置里面的输出节点改了吗，冻结参数的时候只需要修改wenet/utils/checkpoint.py中的load_trained_modules模块，然后在调用的时候添加相应的配置，不需要在其他位置再去修改参数，调整完后在训练log文件中查看模型结构是不是符合预期。希望能帮到你

**Comment by SevenTailCat** [comment]
> 

我把embed中的第一层的Embdding改了，因为有三个我这边非常需要的汉字在原始的units文件里面没有。这个算是改了模型配置吗？
然后因为改了units.txt，所以ctc层中的ctc_lo也需要修改。我增加了3个token。

**Comment by SevenTailCat** [comment]
> > 我增加了一些数据，然后目前loss如下：感觉不太对。。。![5a6305330a1705f7d6be1344f057f56](https://user-images.githubusercontent.com/16370705/241662888-0d510c56-3b49-499d-a9a2-f284c74a38e2.png) ![图像](https://user-images.githubusercontent.com/16370705/241665768-32dc8772-9084-48fe-820a-8d747342229e.png)
> 
> 我感觉你这个更像是数据处理或者模型配置出问题了，一般10小时finetune也不会导向通效变得这么差啊，模型训练配置里面的输出点改了吗，冻结结束的时候只需要修改wenet/utils/checkpoint.py中的load_trained_modules模块，然后在调使用的时候添加相应的配置，不需要在其他位置再去修改参数，调完后在训练日志件中查看模型结构不是符合预期。希望能帮到你

我把embed中的第一层的Embding改了，因为有三个我这边非常需要的汉字在原来的单位文件里面没有。这个算改了模型配置吗？然后为改了units.txt，所以ctc
层中的ctc_lo也需要修改。我加了3个token。
在不增加token的情况下确实效果不会变差。

**Comment by fclearner** [comment]
> > > 我增加了一些数据，然后目前loss如下：感觉不太对。。。![5a6305330a1705f7d6be1344f057f56](https://user-images.githubusercontent.com/16370705/241662888-0d510c56-3b49-499d-a9a2-f284c74a38e2.png) ![图像](https://user-images.githubusercontent.com/16370705/241665768-32dc8772-9084-48fe-820a-8d747342229e.png)
> > 
> > 
> > 我感觉你这个更像是数据处理或者模型配置出问题了，一般10小时finetune也不会导向通效变得这么差啊，模型训练配置里面的输出点改了吗，冻结结束的时候只需要修改wenet/utils/checkpoint.py中的load_trained_modules模块，然后在调使用的时候添加相应的配置，不需要在其他位置再去修改参数，调完后在训练日志件中查看模型结构不是符合预期。希望能帮到你
> 
> 我把embed中的第一层的Embding改了，因为有三个我这边非常需要的汉字在原来的单位文件里面没有。这个算改了模型配置吗？然后为改了units.txt，所以ctc 层中的ctc_lo也需要修改。我加了3个token。 在不增加token的情况下确实效果不会变差。

你怎么该的embeding维度，在哪改的

**Comment by SevenTailCat** [comment]
> > > > 我增加了一些数据，然后目前loss如下：感觉不太对。。。![5a6305330a1705f7d6be1344f057f56](https://user-images.githubusercontent.com/16370705/241662888-0d510c56-3b49-499d-a9a2-f284c74a38e2.png) ![图像](https://user-images.githubusercontent.com/16370705/241665768-32dc8772-9084-48fe-820a-8d747342229e.png)
> > > 
> > > 
> > > 我感觉你这个更像是数据处理或者模型配置出问题了，一般10小时finetune也不会导向通效变得这么差啊，模型训练配置里面的输出点改了吗，冻结结束的时候只需要修改wenet/utils/checkpoint.py中的load_trained_modules模块，然后在调使用的时候添加相应的配置，不需要在其他位置再去修改参数，调完后在训练日志件中查看模型结构不是符合预期。希望能帮到你
> > 
> > 
> > 我把embed中的第一层的Embding改了，因为有三个我这边非常需要的汉字在原来的单位文件里面没有。这个算改了模型配置吗？然后为改了units.txt，所以ctc 层中的ctc_lo也需要修改。我加了3个token。 在不增加token的情况下确实效果不会变差。
> 
> 你怎么该的embeding维度，在哪改的

我我直接修改了model.decoder.embed[0]，把它增大了3个维度，原本token对应的维度信息不变，直接从以前的copy过来。

**Comment by SevenTailCat** [comment]
> 

相当于把embedding, ctc, deceode.output这三个部分全部重新训练吗？
我想请问一个细节，这个新加入的字符应该在sos/eos之前吗？我现在是放在了之后。
我用一个100h的数据集重新训练了三轮加入新token的情况，但是结果依然相似。而在不加入token的模型上则一直可以得到正常的结果（没有空识别，可以读通的句子），这是否意味着只要加入token，就训练难度增大许多，就算把之前embedding的信息放进去，也要重新训练整个embedding和ctc。

**Comment by fclearner** [comment]
> > > > > > > 我增加了一些数据，然后目前loss如下：感觉不太对。。。![5a6305330a1705f7d6be1344f057f56](https://user-images.githubusercontent.com/16370705/241662888-0d510c56-3b49-499d-a9a2-f284c74a38e2.png) ![图像](https://user-images.githubusercontent.com/16370705/241665768-32dc8772-9084-48fe-820a-8d747342229e.png)
> > > > > > 
> > > > > > 
> > > > > > 我感觉你这个更像是数据处理或者模型配置出问题了，一般10小时finetune也不会导向通效变得这么差啊，模型训练配置里面的输出点改了吗，冻结结束的时候只需要修改wenet/utils/checkpoint.py中的load_trained_modules模块，然后在调使用的时候添加相应的配置，不需要在其他位置再去修改参数，调完后在训练日志件中查看模型结构不是符合预期。希望能帮到你
> > > > > 
> > > > > 
> > > > > 我把embed中的第一层的Embding改了，因为有三个我这边非常需要的汉字在原来的单位文件里面没有。这个算改了模型配置吗？然后为改了units.txt，所以ctc 层中的ctc_lo也需要修改。我加了3个token。 在不增加token的情况下确实效果不会变差。
> > > > 
> > > > 
> > > > 你怎么该的embeding维度，在哪改的
> > > 
> > > 
> > > 我我直接修改了model.decoder.embed[0]，把它增大了3个维度，原本token对应的维度信息不变，直接从以前的copy过来。
> > 
> > 
> > 不需要手动改的，训练配置文件改下输出节点数，字典新增字符，他会自动生成新的模型，冻结参数的时候会选择加载预训练模型，把原来的参数加载进来，strict改成false
> 
> 相当于把embedding, ctc, deceode.output这三个部分全部重新训练吗？ 我想请问一个细节，这个新加入的字符应该在sos/eos之前吗？我现在是放在了之后。 我用一个100h的数据集重新训练了三轮加入新token的情况，但是结果依然相似。而在不加入token的模型上则一直可以得到正常的结果（没有空识别，可以读通的句子），这是否意味着只要加入token，就训练难度增大许多，就算把之前embedding的信息放进去，也要重新训练整个embedding和ctc。

理论上token在字典里的位置是不影响的，要看wenet代码有没有做限制，建议按照规范来(把sos/eos放在最后)，可读性也好，100h数据效果异常你应该反思下自己的实验配置了，100h数据正常训练模型同分布测试集cer也有30%左右，新增字符的话建议是重新训练输出层和embedding，只要在finetune的时候加一些预训练模型的原始训练数据，模型遗忘不会很严重的

**Comment by SevenTailCat** [comment]
> > > > > > 我增加了一些数据，然后目前loss如下：感觉不太对。。。![5a6305330a1705f7d6be1344f057f56](https://user-images.githubusercontent.com/16370705/241662888-0d510c56-3b49-499d-a9a2-f284c74a38e2.png) ![图像](https://user-images.githubusercontent.com/16370705/241665768-32dc8772-9084-48fe-820a-8d747342229e.png)
> > > > > 
> > > > > 
> > > > > 我感觉你这个更像是数据处理或者模型配置出问题了，一般10小时finetune也不会导向通效变得这么差啊，模型训练配置里面的输出点改了吗，冻结结束的时候只需要修改wenet/utils/checkpoint.py中的load_trained_modules模块，然后在调使用的时候添加相应的配置，不需要在其他位置再去修改参数，调完后在训练日志件中查看模型结构不是符合预期。希望能帮到你
> > > > 
> > > > 
> > > > 我把embed中的第一层的Embding改了，因为有三个我这边非常需要的汉字在原来的单位文件里面没有。这个算改了模型配置吗？然后为改了units.txt，所以ctc 层中的ctc_lo也需要修改。我加了3个token。 在不增加token的情况下确实效果不会变差。
> > > 
> > > 
> > > 你怎么该的embeding维度，在哪改的
> > 
> > 
> > 我我直接修改了model.decoder.embed[0]，把它增大了3个维度，原本token对应的维度信息不变，直接从以前的copy过来。
> 
> 不需要手动改的，训练配置文件改下输出节点数，字典新增字符，他会自动生成新的模型，冻结参数的时候会选择加载预训练模型，把原来的参数加载进来，strict改成false

我用的wenet预训练模型的实验配置，但是把学习率减少到原本的1/10。但是我只跑了三轮，也许在新加token的情况下我应该跑更多轮才能得到可以读的通的结果？
