### ISSUE TITLE
Question about U2++ config

### ISSUE THREAD

**Issue by cyaaronk** [wenet-e2e/wenet#1866]
Dear Sir/Madam:

I see from wenet/examples/aishell/rnnt that Conformer Result "ctc prefix beam + rnnt&attn rescore" can reach CER 4.45, which is better than the "attention rescoring" result of CER 4.61 in wenet/examples/aishell/s0.

I want to use a similar config to train a u2++ model, and hopefully its "ctc prefix beam + rnnt&attn rescore" result will also beat the "attention rescoring" u2++ conformer result in wenet/examples/aishell/s0.

However, I see sometimes the config to train a u2++ model is a lot different from a non-u2++ model. May I ask for your suggestion as to what is likely to be a better config for u2++?
1. Should I just train u2++ by using the non-u2++ conformer model config?
2. Otherwise what should I change that may lead to better result? Maybe increase epoch? Change transducer weight? Use dither 1.0?

Please advise.

Thank you so much!

Best regards,
Aaron

**Comment by robin1001** [comment]
please show us the two files you compared.

**Comment by cyaaronk** [comment]
Dear Sir,

Please see the 2 files:
https://github.com/wenet-e2e/wenet/blob/main/examples/librispeech/s0/conf/train_conformer.yaml
https://github.com/wenet-e2e/wenet/blob/main/examples/librispeech/s0/conf/train_u2%2B%2B_conformer.yaml

I found that the below parameters are very different (left non-u2++ vs right u2++):
1. filter_conf.max_length: 2000 vs 40960
2. filter_conf.min_length: 50 vs 0
3. fbank_conf.dither: 0.0 vs 1.0
4. max_epoch: 70 vs 120
5. lr: 0.004 vs 0.001

Now I want to use the train.yaml file from aishell/rnnt's 2nd conformer rnnt model which uses transducer weight 0.4 (https://wenet-1256283475.cos.ap-shanghai.myqcloud.com/models/aishell/20220728_conformer_rnnt_exp.tar.gz) as a starting point to train a aishell u2++ conformer rnnt model, to see if it can beat the u2++ conformer model from aishell/s0. 

As the original train.yaml is used for non-u2++ conformer rnnt model. How should I modify the parameters to train a u2++ conformer rnnt model so it will likely work for u2++ models, as again I see the config for u2++ vs non-u2++ config are quite different?

**Comment by cyaaronk** [comment]
Another confusion is that in aishell/rnnt, the 2nd conformer rnnt result uses lr 0.001, however the train.yaml in the pretrained model provided uses lr 0.002!

https://github.com/wenet-e2e/wenet/tree/main/examples/aishell/rnnt:
Conformer Result
Feature info: using fbank feature, dither, cmvn, online speed perturb
Training info: lr 0.001, batch size 20, 8 gpu, acc_grad 1, 140 epochs, dither 0.1
Training weight info: transducer_weight 0.4, ctc_weight 0.2, attention_weight 0.4, average_num 10
Predictor type: lstm
Model link: https://wenet-1256283475.cos.ap-shanghai.myqcloud.com/models/aishell/20220728_conformer_rnnt_exp.tar.gz

**Comment by robin1001** [comment]
@Mddct any idea?

**Comment by robin1001** [comment]
> Dear Sir,
> 
> Please see the 2 files: https://github.com/wenet-e2e/wenet/blob/main/examples/librispeech/s0/conf/train_conformer.yaml https://github.com/wenet-e2e/wenet/blob/main/examples/librispeech/s0/conf/train_u2%2B%2B_conformer.yaml
> 
> I found that the below parameters are very different (left non-u2++ vs right u2++):
> 
> 1. filter_conf.max_length: 2000 vs 40960
> 2. filter_conf.min_length: 50 vs 0
> 3. fbank_conf.dither: 0.0 vs 1.0
> 4. max_epoch: 70 vs 120
> 5. lr: 0.004 vs 0.001
> 
> Now I want to use the train.yaml file from aishell/rnnt's 2nd conformer rnnt model which uses transducer weight 0.4 (https://wenet-1256283475.cos.ap-shanghai.myqcloud.com/models/aishell/20220728_conformer_rnnt_exp.tar.gz) as a starting point to train a aishell u2++ conformer rnnt model, to see if it can beat the u2++ conformer model from aishell/s0.
> 
> As the original train.yaml is used for non-u2++ conformer rnnt model. How should I modify the parameters to train a u2++ conformer rnnt model so it will likely work for u2++ models, as again I see the config for u2++ vs non-u2++ config are quite different?

please follow https://github.com/wenet-e2e/wenet/blob/main/examples/aishell/rnnt/conf/conformer_u2pp_rnnt.yaml

**Comment by cyaaronk** [comment]
@robin1001 Thank you for you reply. 

The config you pointed out uses: 
transducer_weight: 0.75
ctc_weight: 0.1
attention_weight: 0.15

However, if you check https://github.com/wenet-e2e/wenet/tree/main/examples/aishell/rnnt, there are 2 conformer rnnt results, and the one using transducer_weight=0.4 gives far better result.

So I am thinking of following the config of transducer_weight=0.4. The only problem is that there are no config for this setup. So I am asking for your help to see how I can safely modify a conformer rnnt config to use transducer_weight=0.4 and enable u2++ training.

**Comment by Mddct** [comment]
> @robin1001 Thank you for you reply. 
> 
> The config you pointed out uses: 
> transducer_weight: 0.75
> ctc_weight: 0.1
> attention_weight: 0.15
> 
> However, if you check https://github.com/wenet-e2e/wenet/tree/main/examples/aishell/rnnt, there are 2 conformer rnnt results, and the one using transducer_weight=0.4 gives far better result.
> 
> So I am thinking of following the config of transducer_weight=0.4. The only problem is that there are no config for this setup. So I am asking for your help to see how I can safely modify a conformer rnnt config to use transducer_weight=0.4 and enable u2++ training.

you can refer other u2++ recipe using rnnt model conf

**Comment by cyaaronk** [comment]
Thank you
