### ISSUE TITLE
HLG Decoding doesn't have full results

### ISSUE THREAD

**Issue by nguyendothanhtruc** [wenet-e2e/wenet#1868]
I have trained squeezeformer in Vietnamese audios and run the decoding method in python script (recognize.py) using HLG decoding of k2-icefall but the output results are so weird:
![image](https://github.com/wenet-e2e/wenet/assets/63278931/ef6b48f4-6f5e-46d1-ad1e-f09764db6fd2)

However, the results are still fine when I try CTC greedy decoding. 
Therefore, I doubt it's a mistake when builiding the HLG graph and ngram LM.
I have tried 2 versions for 3gram LM, using the train script by SRILM (in example/aishell):
- LM with word tokenizer
- LM with spm tokenizer

But their behaviors are nearly the same, it just output some tokens not full sentence.

When debug the hlg rescoring method with full audio chunk, the hypothesises for utterance contain few tokens in each path that why the result of later process (choose best path and decode) gives worst result?
[Code link](https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/asr_model.py#L711)
![image](https://github.com/wenet-e2e/wenet/assets/63278931/ec674c45-90b3-499c-90d0-fb038233087d)
 
Can you please help to figure out the underlying reason for this bug?

**Comment by robin1001** [comment]
@aluminumbox , any idea?

**Comment by smehrabikia** [comment]
I encountered the same problem for the Persian language.
The output of the model without the language model is good, but after adding the language model, the output is not irrelevant except for a few words.
Thank you for your guidance.

I1010 13:07:47.599594 57527 params.h:155] Reading torch model exp/unified_conformer/final.zip
I1010 13:07:47.600919 57527 torch_asr_model.cc:35] Num intra-op threads: 1
I1010 13:07:48.796988 57527 torch_asr_model.cc:73] Torch Model Info:
I1010 13:07:48.796998 57527 torch_asr_model.cc:74] 	subsampling_rate 4
I1010 13:07:48.797000 57527 torch_asr_model.cc:75] 	right context 6
I1010 13:07:48.797001 57527 torch_asr_model.cc:76] 	sos 5025
I1010 13:07:48.797003 57527 torch_asr_model.cc:77] 	eos 5025
I1010 13:07:48.797004 57527 torch_asr_model.cc:78] 	is bidirectional decoder 0
I1010 13:07:48.797008 57527 params.h:197] Reading unit table welm/exp/lang/units.txt
I1010 13:07:48.811363 57527 params.h:205] Reading fst welm/exp/lang/TLG.fst
I1010 13:07:48.811384 57527 fst.h:799] FstImpl::ReadHeader: source: welm/exp/lang/TLG.fst, fst_type: vector, arc_type: standard, version: 2, flags: 0
I1010 13:08:06.386134 57527 params.h:211] Reading symbol table welm/exp/lang/words.txt
I1010 13:08:06.520176 57637 decoder_main.cc:54] num frames 344
I1010 13:08:06.520457 57637 asr_decoder.cc:104] Required 2147483647 get 344
I1010 13:08:06.833223 57637 asr_decoder.cc:200] Partial CTC result سگ
I1010 13:08:06.837100 57637 queue.h:570] AutoQueue: using top-order discipline
I1010 13:08:06.837770 57637 asr_decoder.cc:200] Partial CTC result سگ
I1010 13:08:06.921747 57637 asr_decoder.cc:84] Rescoring cost latency: 88ms.
I1010 13:08:06.921768 57637 decoder_main.cc:104] 0007-m_0036 Final result: 
I1010 13:08:06.921773 57637 decoder_main.cc:105] Decoded 3456ms audio taken 401ms.
I1010 13:08:06.928592 57637 decoder_main.cc:54] num frames 123
I1010 13:08:06.928719 57637 asr_decoder.cc:104] Required 2147483647 get 123
I1010 13:08:09.942358 57637 queue.h:535] AutoQueue: using state-order discipline
I1010 13:08:10.626091 57637 asr_decoder.cc:84] Rescoring cost latency: 683ms.
I1010 13:08:10.626111 57637 decoder_main.cc:104] 0429-m_0199 Final result: 
I1010 13:08:10.626116 57637 decoder_main.cc:105] Decoded 1248ms audio taken 3697ms.
I1010 13:08:10.639844 57637 decoder_main.cc:54] num frames 369
I1010 13:08:10.639951 57637 asr_decoder.cc:104] Required 2147483647 get 369
I1010 13:08:13.459914 57637 queue.h:570] AutoQueue: using top-order discipline
I1010 13:08:13.789427 57637 asr_decoder.cc:84] Rescoring cost latency: 336ms.
I1010 13:08:13.789448 57637 decoder_main.cc:104] 0935-m_0035 Final result: 
I1010 13:08:13.789453 57637 decoder_main.cc:105] Decoded 3712ms audio taken 3149ms.
I1010 13:08:13.796512 57637 decoder_main.cc:54] num frames 185
I1010 13:08:13.796602 57637 asr_decoder.cc:104] Required 2147483647 get 185
I1010 13:08:22.201333 57637 queue.h:570] AutoQueue: using top-order discipline
I1010 13:08:24.385641 57637 asr_decoder.cc:84] Rescoring cost latency: 2188ms.
I1010 13:08:24.385661 57637 decoder_main.cc:104] 1613-m_0013 Final result:
