### ISSUE TITLE
runtime GPU， server docker 启动报错，找不到swig_decoder

### ISSUE THREAD

**Issue by hmylk** [wenet-e2e/wenet#1872]
E0602 02:21:56.364861 139 model_repository_manager.cc:487] Invalid argument: ensemble 'streaming_wenet' depends on 'wenet' which has no loaded version. Model 'wenet' loading failed with error: version 1 is at UNAVAILABLE state: Internal: ModuleNotFoundError: No module named 'swig_decoders'

![image](https://github.com/wenet-e2e/wenet/assets/26154355/a520b10d-9f80-43c7-a428-0916d46a8259)

**Comment by yuekaizhang** [comment]
> E0602 02:21:56.364861 139 model_repository_manager.cc:487] Invalid argument: ensemble 'streaming_wenet' depends on 'wenet' which has no loaded version. Model 'wenet' loading failed with error: version 1 is at UNAVAILABLE state: Internal: ModuleNotFoundError: No module named 'swig_decoders'
> 
> ![image](https://user-images.githubusercontent.com/26154355/242768853-a520b10d-9f80-43c7-a428-0916d46a8259.png)
Thanks, I will investigate this issue. There are 2 WAR for you:
1. Would you mind trying this container first ， docker pull soar97/triton-wenet:22.12
2. You may install swig decoder manually in the container https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/Dockerfile/Dockerfile.server#L10.

**Comment by hmylk** [comment]
> > E0602 02:21:56.364861 139 model_repository_manager.cc:487] Invalid argument: ensemble 'streaming_wenet' depends on 'wenet' which has no loaded version. Model 'wenet' loading failed with error: version 1 is at UNAVAILABLE state: Internal: ModuleNotFoundError: No module named 'swig_decoders'
> > ![image](https://user-images.githubusercontent.com/26154355/242768853-a520b10d-9f80-43c7-a428-0916d46a8259.png)
> 
> @hmylk Thanks, I will investigate this issue. There are 3 WAR may work for you:
> 
> 1. Would you mind trying this container first ， docker pull soar97/triton-wenet:22.12
> 2. You may install swig decoder manually in the container https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/Dockerfile/Dockerfile.server#L10.
> 3. export PYTHONPATH=$PYTHONPATH:/path/to/swig_decoders

@yuekaizhang   thanks for your reply，OK， I  ever tried  2 ,  also not work.
i just tried 3,  error occur like 
![image](https://github.com/wenet-e2e/wenet/assets/26154355/0c5a19a7-3220-48d3-8c9a-f9f88412ca33)

i am now tring the 1 .
hope to get your advice,thks very much.

**Comment by hmylk** [comment]
![image](https://github.com/wenet-e2e/wenet/assets/26154355/a4b4ea8f-80f5-4aeb-af35-ef33335101d1)

**Comment by iron-js** [comment]
@hmylk swig_decoder installed in /root/.local/lib/python3.8, you should  setting PYTHONPATH ：
export PYTHONPATH=/root/.local/lib/python3.8/site-packages:/root/.local/lib/python3.8/site-packages/swig_decoders-1.1-py3.8-linux-x86_64.egg:$PYTHONPATH

**Comment by hmylk** [comment]
> 

thankyou very much， now， docker server can run  successful。 But , when  i run  docker triton client :
cmd like ：
AUDIO_DATA=<path to client test wavs>
docker run -ti --net host --name wenet_client -v $PWD/client:/ws/client -v $AUDIO_DATA:/ws/test_data wenet_client:latest
cd /ws/client
python3 client.py --audio_file=/ws/test_data/mid.wav --url=localhost:8001

Error occur ：
![1685934952212](https://github.com/wenet-e2e/wenet/assets/26154355/0dc1e482-d130-411f-9014-15585d9974bd)

this error perpelx me  for a several days， hope to get your advices，thank you.

**Comment by hmylk** [comment]
> @hmylk swig_decoder installed in /root/.local/lib/python3.8, you should setting PYTHONPATH ： export PYTHONPATH=/root/.local/lib/python3.8/site-packages:/root/.local/lib/python3.8/site-packages/swig_decoders-1.1-py3.8-linux-x86_64.egg:$PYTHONPATH

@iron-js   thank you very much， now， docker server can run successfully。 But , when i run docker triton client :
cmd like ：
AUDIO_DATA=path to client test  wavs
docker run -ti --net host --name wenet_client -v $PWD/client:/ws/client -v $AUDIO_DATA:/ws/test_data wenet_client:latest
cd /ws/client
python3 client.py --audio_file=/ws/test_data/mid.wav --url=localhost:9001

Error occur ：
![image](https://github.com/wenet-e2e/wenet/assets/26154355/4896acac-515f-4321-8134-9b5f3a1b059d)

This error perplex me  for serveral days，hope to get advices ，thank you very much

**Comment by yuekaizhang** [comment]
> > @hmylk swig_decoder installed in /root/.local/lib/python3.8, you should setting PYTHONPATH ： export PYTHONPATH=/root/.local/lib/python3.8/site-packages:/root/.local/lib/python3.8/site-packages/swig_decoders-1.1-py3.8-linux-x86_64.egg:$PYTHONPATH
> 
> @iron-js thank you very much， now， docker server can run successfully。 But , when i run docker triton client : cmd like ： AUDIO_DATA=path to client test wavs docker run -ti --net host --name wenet_client -v $PWD/client:/ws/client -v $AUDIO_DATA:/ws/test_data wenet_client:latest cd /ws/client python3 client.py --audio_file=/ws/test_data/mid.wav --url=localhost:9001
> 
> Error occur ： ![image](https://user-images.githubusercontent.com/26154355/243243803-4896acac-515f-4321-8134-9b5f3a1b059d.png)
> 
> This error perplex me for serveral days，hope to get advices ，thank you very much

1. Would you mind changing client.py by yourself to remove the multi-threads related parts? The error you showed is caused by multi-thread call rather than the root cause.
2. Could you try this client? https://github.com/yuekaizhang/Triton-ASR-Client/blob/main/client.py#L37-L43. You may check the project readme.md first and test it with single wav.

**Comment by hmylk** [comment]
> > > @hmylk swig_decoder installed in /root/.local/lib/python3.8, you should setting PYTHONPATH ： export PYTHONPATH=/root/.local/lib/python3.8/site-packages:/root/.local/lib/python3.8/site-packages/swig_decoders-1.1-py3.8-linux-x86_64.egg:$PYTHONPATH
> > 
> > 
> > @iron-js thank you very much， now， docker server can run successfully。 But , when i run docker triton client : cmd like ： AUDIO_DATA=path to client test wavs docker run -ti --net host --name wenet_client -v $PWD/client:/ws/client -v $AUDIO_DATA:/ws/test_data wenet_client:latest cd /ws/client python3 client.py --audio_file=/ws/test_data/mid.wav --url=localhost:9001
> > Error occur ： ![image](https://user-images.githubusercontent.com/26154355/243243803-4896acac-515f-4321-8134-9b5f3a1b059d.png)
> > This error perplex me for serveral days，hope to get advices ，thank you very much
> 
> 1. Would you mind changing client.py by yourself to remove the multi-threads related parts? The error you showed is caused by multi-thread call rather than the root cause.
> 2. Could you try this client? https://github.com/yuekaizhang/Triton-ASR-Client/blob/main/client.py#L37-L43. You may check the project readme.md first and test it with single wav --audio-path.

@yuekaizhang thank you for your reply。 I tried remove the multi-threads related code，this error doesn't occur .
But，another error :
![image](https://github.com/wenet-e2e/wenet/assets/26154355/4702d177-4fda-4622-a3be-a7dd7e198ee2)

**Comment by yuekaizhang** [comment]
> ds related code，this error doesn't occur .

Could you paste your code about the server launch and client launch? Make sure your client and server could communicate first.

**Comment by hmylk** [comment]
> > ds related code，this error doesn't occur .
> 
> Could you paste your code about the server launch and client launch? Make sure your client and server could communicate first.

Server:
1.sudo docker run --gpus '"device=0"' -it -v $PWD/model_repo_stateful:/ws/model_repo -v $onnx_model_dir:/ws/onnx_model -p 9000:9000 -p 9001:9001 -p 9002:9002 --shm-size=1g --ulimit memlock=-1  wenet_server_new:latest
2. export PYTHON path ： export PYTHONPATH=/root/.local/lib/python3.8/site-packages:/root/.local/lib/python3.8/site-packages/swig_decoders-1.1-py3.8-linux-x86_64.egg:$PYTHONPATH
3. /workspace/scripts/convert_start_server.sh

Client：
1. docker run -ti --net host --name wenet_client -v $PWD/client:/ws/client -v $AUDIO_DATA:/ws/test_data wenet_client_new:latest
2. cd /ws/client
3. python3 client.py --wavscp=/ws/test_data/wav.scp --data_dir=/ws/test_data/ --trans=/ws/test_data/trans.txt --model_name=streaming_wenet --streaming

One situation needs to be explained：
Becase the default port of 8000 is used by others ，so when i launch server docker， i just change ports parameters of docker run command。  
BUT NOW  ,   I tried chang the server port from 9000 to 8000，  can **run successfully**


Thank you very much @iron-js @yuekaizhang .

**Comment by Slyne** [comment]
> > > ds related code，this error doesn't occur .
> > 
> > 
> > Could you paste your code about the server launch and client launch? Make sure your client and server could communicate first.
> 
> Server: 1.sudo docker run --gpus '"device=0"' -it -v $PWD/model_repo_stateful:/ws/model_repo -v $onnx_model_dir:/ws/onnx_model -p 9000:9000 -p 9001:9001 -p 9002:9002 --shm-size=1g --ulimit memlock=-1 wenet_server_new:latest 2. export PYTHON path ： export PYTHONPATH=/root/.local/lib/python3.8/site-packages:/root/.local/lib/python3.8/site-packages/swig_decoders-1.1-py3.8-linux-x86_64.egg:$PYTHONPATH 3. /workspace/scripts/convert_start_server.sh
> 
> Client：
> 
> 1. docker run -ti --net host --name wenet_client -v $PWD/client:/ws/client -v $AUDIO_DATA:/ws/test_data wenet_client_new:latest
> 2. cd /ws/client
> 3. python3 client.py --wavscp=/ws/test_data/wav.scp --data_dir=/ws/test_data/ --trans=/ws/test_data/trans.txt --model_name=streaming_wenet --streaming
> 
> One situation needs to be explained： Becase the default port of 8000 is used by others ，so when i launch server docker， i just change ports parameters of docker run command。 BUT NOW , I tried chang the server port from 9000 to 8000， can **run successfully**
> 
> Thank you very much @iron-js @yuekaizhang .

You can use the port as:
```
-p 9000:8000 -p 9001:8001
```
You need to make sure the right port(inside the docker) should alway be 8000, 8001 if you didn't change the port when starting triton server.  For the left port (your local server port), you may use any port number that is not occupied by others.

**Comment by hmylk** [comment]
> > > > ds related code，this error doesn't occur .
> > > 
> > > 
> > > Could you paste your code about the server launch and client launch? Make sure your client and server could communicate first.
> > 
> > 
> > Server: 1.sudo docker run --gpus '"device=0"' -it -v $PWD/model_repo_stateful:/ws/model_repo -v $onnx_model_dir:/ws/onnx_model -p 9000:9000 -p 9001:9001 -p 9002:9002 --shm-size=1g --ulimit memlock=-1 wenet_server_new:latest 2. export PYTHON path ： export PYTHONPATH=/root/.local/lib/python3.8/site-packages:/root/.local/lib/python3.8/site-packages/swig_decoders-1.1-py3.8-linux-x86_64.egg:$PYTHONPATH 3. /workspace/scripts/convert_start_server.sh
> > Client：
> > 
> > 1. docker run -ti --net host --name wenet_client -v $PWD/client:/ws/client -v $AUDIO_DATA:/ws/test_data wenet_client_new:latest
> > 2. cd /ws/client
> > 3. python3 client.py --wavscp=/ws/test_data/wav.scp --data_dir=/ws/test_data/ --trans=/ws/test_data/trans.txt --model_name=streaming_wenet --streaming
> > 
> > One situation needs to be explained： Becase the default port of 8000 is used by others ，so when i launch server docker， i just change ports parameters of docker run command。 BUT NOW , I tried chang the server port from 9000 to 8000， can **run successfully**
> > Thank you very much @iron-js @yuekaizhang .
> 
> You can use the port as:
> 
> ```
> -p 9000:8000 -p 9001:8001
> ```
> 
> @hmylk You need to make sure the right port(inside the docker) should alway be 8000, 8001 if you didn't change the port when starting triton server. For the left port (your local server port), you may use any port number that is not occupied by others.

oh,  so it is. Thanks  very much for your advices @Slyne 
I want to  confirm that  the right port(inside the docker ) only be 8000,80001?

**Comment by FieldsMedal** [comment]
> > > > > ds related code，this error doesn't occur .
> > > > 
> > > > 
> > > > Could you paste your code about the server launch and client launch? Make sure your client and server could communicate first.
> > > 
> > > 
> > > Server: 1.sudo docker run --gpus '"device=0"' -it -v $PWD/model_repo_stateful:/ws/model_repo -v $onnx_model_dir:/ws/onnx_model -p 9000:9000 -p 9001:9001 -p 9002:9002 --shm-size=1g --ulimit memlock=-1 wenet_server_new:latest 2. export PYTHON path ： export PYTHONPATH=/root/.local/lib/python3.8/site-packages:/root/.local/lib/python3.8/site-packages/swig_decoders-1.1-py3.8-linux-x86_64.egg:$PYTHONPATH 3. /workspace/scripts/convert_start_server.sh
> > > Client：
> > > 
> > > 1. docker run -ti --net host --name wenet_client -v $PWD/client:/ws/client -v $AUDIO_DATA:/ws/test_data wenet_client_new:latest
> > > 2. cd /ws/client
> > > 3. python3 client.py --wavscp=/ws/test_data/wav.scp --data_dir=/ws/test_data/ --trans=/ws/test_data/trans.txt --model_name=streaming_wenet --streaming
> > > 
> > > One situation needs to be explained： Becase the default port of 8000 is used by others ，so when i launch server docker， i just change ports parameters of docker run command。 BUT NOW , I tried chang the server port from 9000 to 8000， can **run successfully**
> > > Thank you very much @iron-js @yuekaizhang .
> > 
> > 
> > You can use the port as:
> > ```
> > -p 9000:8000 -p 9001:8001
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @hmylk You need to make sure the right port(inside the docker) should alway be 8000, 8001 if you didn't change the port when starting triton server. For the left port (your local server port), you may use any port number that is not occupied by others.
> 
> oh, so it is. Thanks very much for your advices @Slyne I want to confirm that the right port(inside the docker ) only be 8000,80001?

if you want to use other port in start tritonserver,  add --grpc-port=9990 --http-port=9991 --metrics-port=9992.
https://github.com/wenet-e2e/wenet/blob/6b0dcd24f4f75fb4724a5185ff3bc9b985119262/runtime/gpu/scripts/convert_start_server.sh#LL26C1-L26C130
`tritonserver --model-repository=${model_repo} --pinned-memory-pool-byte-size=1024000000 --cuda-memory-pool-byte-size=0:1024000000 --grpc-port=9990 --http-port=9991 --metrics-port=9992`

**Comment by hmylk** [comment]
> > > > > > ds related code，this error doesn't occur .
> > > > > 
> > > > > 
> > > > > Could you paste your code about the server launch and client launch? Make sure your client and server could communicate first.
> > > > 
> > > > 
> > > > Server: 1.sudo docker run --gpus '"device=0"' -it -v $PWD/model_repo_stateful:/ws/model_repo -v $onnx_model_dir:/ws/onnx_model -p 9000:9000 -p 9001:9001 -p 9002:9002 --shm-size=1g --ulimit memlock=-1 wenet_server_new:latest 2. export PYTHON path ： export PYTHONPATH=/root/.local/lib/python3.8/site-packages:/root/.local/lib/python3.8/site-packages/swig_decoders-1.1-py3.8-linux-x86_64.egg:$PYTHONPATH 3. /workspace/scripts/convert_start_server.sh
> > > > Client：
> > > > 
> > > > 1. docker run -ti --net host --name wenet_client -v $PWD/client:/ws/client -v $AUDIO_DATA:/ws/test_data wenet_client_new:latest
> > > > 2. cd /ws/client
> > > > 3. python3 client.py --wavscp=/ws/test_data/wav.scp --data_dir=/ws/test_data/ --trans=/ws/test_data/trans.txt --model_name=streaming_wenet --streaming
> > > > 
> > > > One situation needs to be explained： Becase the default port of 8000 is used by others ，so when i launch server docker， i just change ports parameters of docker run command。 BUT NOW , I tried chang the server port from 9000 to 8000， can **run successfully**
> > > > Thank you very much @iron-js @yuekaizhang .
> > > 
> > > 
> > > You can use the port as:
> > > ```
> > > -p 9000:8000 -p 9001:8001
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @hmylk You need to make sure the right port(inside the docker) should alway be 8000, 8001 if you didn't change the port when starting triton server. For the left port (your local server port), you may use any port number that is not occupied by others.
> > 
> > 
> > oh, so it is. Thanks very much for your advices @Slyne I want to confirm that the right port(inside the docker ) only be 8000,80001?
> 
> if you want to use other port in start tritonserver, add --grpc-port=9990 --http-port=9991 --metrics-port=9992. https://github.com/wenet-e2e/wenet/blob/6b0dcd24f4f75fb4724a5185ff3bc9b985119262/runtime/gpu/scripts/convert_start_server.sh#LL26C1-L26C130 `tritonserver --model-repository=${model_repo} --pinned-memory-pool-byte-size=1024000000 --cuda-memory-pool-byte-size=0:1024000000 --grpc-port=9990 --http-port=9991 --metrics-port=9992`

ok， thank you very much.

**Comment by carryzhang123** [comment]
Can I specify the installation location of swig I want to install in conda environment

**Comment by yuekaizhang** [comment]
> Can I specify the installation location of swig I want to install in conda environment

You may try `conda install -c anaconda swig`
