### ISSUE TITLE
加了TLG后识别为空的原因是什么？

### ISSUE THREAD

**Issue by SevenTailCat** [wenet-e2e/wenet#1873]
> i have used `--acoustic_scale 1.2`. Should i try higher values and what can be these values?

yes, please try higher acoustic_scale

_Originally posted by @xingchensong in https://github.com/wenet-e2e/wenet/issues/1545#issuecomment-1437836863_

为什么加入语言模型后，即使用平滑算法，依然会出现识别是空的情况。但是如果不加语言模型直接用神经网络识别或者在神经网络上加入context bias都可以？
我的理解是，如果用ctc搜索相当于所有的token之间有互相联系，但是用WFTS就只能在语言文本中有关系的词之间跳转。
但是在生成语言模型的过程中如果使用了平滑算法，那么“不在文本中出现前后关系的词之间也会有极小概率的联系”。我这样理解对吗？
但是实际上识别确是空？

PS：当我将aishell1语料库和我自己的语料库合并后，识别不为空。但是启动了平滑算法为什么还是会出现这个问题呢？

**Comment by robin1001** [comment]
先试试标准的 recipe 有没有问题，没有问题的话，看看自己 build 的 TLG 有没有问题。
