### ISSUE TITLE
我的在使用attention解码时，有部分会输出空

### ISSUE THREAD

**Issue by speechless-z** [wenet-e2e/wenet#1877]
当我利用attention进行解码时，会有很多如下情况产生，我的输出并不完整。
senls01-zang_24_10 ས <space>
但是我使用test_attention_rescoring时，输出合理且正确，并且不会有空或者不完整的情况，我想知道这是什么原因呢？
senls01-zang_24_10 ས <space> ཁ ུ ལ <space> ཁ ག <space> ད ང <space> ས ྡ ེ <space> ཁ ག <space> ཁ ག <space> ག ི ས <space> ཀ ྲ ུ ང <space> ད བ ྱ ང <space> ག ི <space> ག ཅ ི ག <space> འ ག ྱ ུ ར <space> བ ཀ ོ ད <space> ས ྒ ྲ ི ག <space> ད ང <space> ག ན ད <space> ད ོ ན <space> ཐ ག <space> ག ཅ ོ ད <space> བ ྱ ེ ད <space> ད ག ོ ས

**Comment by robin1001** [comment]
attention 是自回归解码，对 unseen data 和语音长度更敏感一些。 attention_rescoring 是先做 CTC，后基于 CTC nbest 做 rescoring。

**Comment by speechless-z** [comment]
好的我明白了 非常感谢
