### ISSUE TITLE
测试自己的wav文件出错

### ISSUE THREAD

**Issue by fh520** [wenet-e2e/wenet#1884]
错误提示：
I0613 21:07:11.584242 643286 fst.h:799] FstImpl::ReadHeader: source: data/lang_test/TLG.fst, fst_type: vector, arc_type: standard, version: 2, flags: 0
I0613 21:07:12.173897 643286 params.h:211] Reading symbol table data/lang_test/words.txt
F0613 21:07:12.396431 644314 decoder_main.cc:48] Check failed: wav_reader.sample_rate() == FLAGS_sample_rate (8000 vs. 16000)
*** Check failure stack trace: ***

**Comment by hmylk** [comment]
> 

检查下你的wav文件的采样率是不是16K的吧？

**Comment by Mddct** [comment]
可以重新开启这个issues 如果还有问题的吗
Kěyǐ chóngxīn kāiqǐ zhège issues rúguǒ hái yǒu wèntí de ma

you  can reopen this issue if there are still problems
