### ISSUE TITLE
DDP training problem

### ISSUE THREAD

**Issue by Macsim2** [wenet-e2e/wenet#1885]
**Describe the bug**
Hi, I'm trying to multiple-gpu training with nccl but,
when execute `model = torch.nn.parallel.DistributedDataParallel()` in wenet/bin/train.py, memory used by one gpu and then process is terminated.
It looks like a problem of mis-occupation that more process are using one gpu, 
whatever I select 2 or 4 gpu, first gpu are used..
Although I check the ddp.rank, and world_size(number_gpu) twice, I didn't why it is

If anyone who like me or know the same problem, please give me a hint

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 20.04

**Comment by xingchensong** [comment]
which recipe could reproduce your issue?

**Comment by Macsim2** [comment]
My git hash is dbf8037 
and I'm trying u2++ squeezeformer and u2++ conformer 
Regardless of recipe, I think because of my specific environments this problem is occurring

In addition, I had used NCCL_P2P_DISABLE=1 but not now. I made P2P operation enable without the Flag.
In my opinion, perhaps we curious of system setting or something rather than source
thank you @xingchensong

**Comment by foemre** [comment]
@Macsim2 have you updated your driver since? Having to use `NCCL_P2P_DISABLE=1` on driver version 525 was a known issue, did the new driver solve this issue?

**Comment by Macsim2** [comment]
@foemre 
No, I'm trying to train on 510.108.03 driver. and `NCCL_P2P_DISABLE=1` is not using 
should I upgrade nvidia-driver version and then test again..?

**Comment by Macsim2** [comment]
This problem was solved by reinstalling torch or something else
It is probably used in confusion of python package
thank for all. @xingchensong @foemre
