### ISSUE TITLE
多机多卡训练报错

### ISSUE THREAD

**Issue by kli017** [wenet-e2e/wenet#1891]
torch 1.9.0+cu111
cuda version 11.1

启动后得到如下报错，求指导

`voicec105:90736:90736 [0] misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
voicec105:90736:90736 [0] NCCL INFO NET/Socket : Using [0]eno1:172.16.20.105<0>
voicec105:90736:90736 [0] NCCL INFO Using network Socket
voicec105:90735:91654 [0] NCCL INFO Channel 00/02 :    0   1   2   3
voicec105:90735:91654 [0] NCCL INFO Channel 01/02 :    0   1   2   3
voicec105:90735:91654 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
voicec105:90735:91654 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1|-1->0->1/-1/-1 [1] 1/-1/-1->0->3|3->0->1/-1/-1
voicec105:90735:91654 [0] NCCL INFO Setting affinity for GPU 4 to ffff,fff00000,00ffffff,f0000000
voicec105:90736:91655 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
voicec105:90736:91655 [0] NCCL INFO Trees [0] 2/-1/-1->1->0|0->1->2/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1
voicec105:90736:91655 [0] NCCL INFO Setting affinity for GPU 5 to ffff,fff00000,00ffffff,f0000000
voicec105:90735:91654 [0] NCCL INFO Channel 00 : 3[b2000] -> 0[88000] [receive] via NET/Socket/0
voicec105:90735:91654 [0] NCCL INFO Channel 00 : 0[88000] -> 1[89000] via P2P/IPC
voicec105:90736:91655 [0] NCCL INFO Channel 00 : 1[89000] -> 2[b1000] [send] via NET/Socket/0

voicec105:90736:91655 [0] include/socket.h:403 NCCL WARN Connect to fe80::c4eb:49ff:fe04:e32d%6<57335> failed : Network is unreachable
voicec105:90736:91655 [0] NCCL INFO transport/net_socket.cc:313 -> 2
voicec105:90736:91655 [0] NCCL INFO include/net.h:21 -> 2
voicec105:90736:91655 [0] NCCL INFO transport/net.cc:161 -> 2
voicec105:90736:91655 [0] NCCL INFO transport.cc:68 -> 2
voicec105:90736:91655 [0] NCCL INFO init.cc:766 -> 2
voicec105:90736:91655 [0] NCCL INFO init.cc:840 -> 2
voicec105:90736:91655 [0] NCCL INFO group.cc:73 -> 2 [Async thread]
Traceback (most recent call last):
  File "wenet/bin/train.py", line 319, in <module>
    main()
  File "wenet/bin/train.py", line 248, in main
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/likai/miniconda3/envs/wenet_k/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 496, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying
voicec105:90735:91654 [0] NCCL INFO Call to connect returned Connection refused, retrying

voicec105:90735:91654 [0] include/socket.h:403 NCCL WARN Connect to 172.16.20.105<54011> failed : Connection refused
voicec105:90735:91654 [0] NCCL INFO bootstrap.cc:95 -> 2
voicec105:90735:91654 [0] NCCL INFO bootstrap.cc:363 -> 2
voicec105:90735:91654 [0] NCCL INFO transport.cc:50 -> 2
voicec105:90735:91654 [0] NCCL INFO init.cc:767 -> 2
voicec105:90735:91654 [0] NCCL INFO init.cc:840 -> 2
voicec105:90735:91654 [0] NCCL INFO group.cc:73 -> 2 [Async thread]
Traceback (most recent call last):
  File "wenet/bin/train.py", line 319, in <module>
    main()
  File "wenet/bin/train.py", line 248, in main
    model = torch.nn.parallel.DistributedDataParallel(
  File "/home/likai/miniconda3/envs/wenet_k/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 496, in __init__
    dist._verify_model_across_ranks(self.process_group, parameters)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:911, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
`

**Comment by xingchensong** [comment]
可以的话请贴一下解决方案方便别人遇到相同问题吗？谢谢！

**Comment by kli017** [comment]
需要在每个node指定网卡，设置NCCL_SOCKET_IFNAME后可正常训练
