### ISSUE TITLE
libwenet.so crash with  signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by Havelet** [wenet-e2e/wenet#1892]
**Describe the bug**
I integrated the latest project into my project as an aar for android, but met crash with libwenet.so and the log is attached.

**To Reproduce**
I just modified the build.gradle and remove the UI related code and build out an aar then put it into my application.
In the application , I wrappered the Recognize class to a handler to process the initialization and recognizing. It works fine 
at fisrt, but lately the crash happened occasionally, now it's inevitable, the crash will happened once the Recognizer initialized.

**Expected behavior**
the wenet asr work fine

**Screenshots**
crash log is attached in  "Additional context" part

**Desktop (please complete the following information):**
 - Not available

**Smartphone (please complete the following information):**
 - Device: Redmi Note 8
 - OS: [Android 10]
  - Version info：xiaomi/ginkgo/ginkgo:10/QKQ1.200114.002/V12.0.3.0.QCOCNXM:user/release-keys
  
**Additional context**
crash log
06-28 11:03:53.449 I/chatty  (10564): uid=10253(com.test.sampleapp) expire 2 lines
06-28 11:03:53.451 I//system/bin/tombstoned( 1140): received crash request for pid 10532
06-28 11:03:52.365 I/chatty  ( 1539): uid=1000(system) Binder:1539_8 identical 2 lines
06-28 11:03:52.367 E/WifiService( 1539): Permission violation - getScanResults not allowed for uid=10253, packageName=com.test.sampleapp, reason=java.lang.SecurityException: Location mode is disabled for the device
06-28 11:03:53.457 E/WifiService( 1539): Permission violation - getScanResults not allowed for uid=10253, packageName=com.test.sampleapp, reason=java.lang.SecurityException: Location mode is disabled for the device
06-28 11:03:53.458 I/CNSS    ( 3263): Failed to send nl message
06-28 11:03:53.474 I/chatty  (10262): uid=10253(com.test.sampleapp) expire 7 lines
06-28 11:03:53.475 I/chatty  (10262): uid=10253(com.test.sampleapp) expire 73 lines
06-28 11:03:53.490 F/DEBUG   (10564): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-28 11:03:53.490 F/DEBUG   (10564): Build fingerprint: 'xiaomi/ginkgo/ginkgo:10/QKQ1.200114.002/V12.0.3.0.QCOCNXM:user/release-keys'
06-28 11:03:53.490 F/DEBUG   (10564): Revision: '0'
06-28 11:03:53.490 F/DEBUG   (10564): ABI: 'arm64'
06-28 11:03:53.490 F/DEBUG   (10564): Timestamp: 2023-06-28 11:03:53+0800
06-28 11:03:53.490 F/DEBUG   (10564): pid: 10262, tid: 10532, name: test.sampleapp  >>> com.test.sampleapp <<<
06-28 11:03:53.490 F/DEBUG   (10564): uid: 10253
06-28 11:03:53.490 F/DEBUG   (10564): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
06-28 11:03:53.490 F/DEBUG   (10564): Cause: null pointer dereference
06-28 11:03:53.490 F/DEBUG   (10564):     x0  0000007246ec12a0  x1  0000000000001fb5  x2  0000000000000018  x3  0000000000000000
06-28 11:03:53.490 F/DEBUG   (10564):     x4  000000728e08b8d8  x5  000000728e08b8d8  x6  0000000000000000  x7  0000000000000000
06-28 11:03:53.490 F/DEBUG   (10564):     x8  0000000000000000  x9  0000000000000000  x10 0000000000000004  x11 0000000000000000
06-28 11:03:53.490 F/DEBUG   (10564):     x12 000000728e08b8b8  x13 0000000000000000  x14 0000007258790d50  x15 0000007258790d60
06-28 11:03:53.490 F/DEBUG   (10564):     x16 000000727bf19038  x17 000000727b9cbb6c  x18 000000727c9ab3f8  x19 000000728e08bd50
06-28 11:03:53.490 F/DEBUG   (10564):     x20 00000073a89cc9ec  x21 000000728e08bd50  x22 000000728e08c060  x23 000000728e08bdd8
06-28 11:03:53.490 F/DEBUG   (10564):     x24 000000728e08bd50  x25 000000728e08bd50  x26 000000728e08c020  x27 00000073ac69d020
06-28 11:03:53.490 F/DEBUG   (10564):     x28 0000007ff256e380  x29 000000728e08b930
06-28 11:03:53.490 F/DEBUG   (10564):     sp  000000728e08b620  lr  000000727b9caccc  pc  000000727b9cacd4
06-28 11:03:53.495 I/chatty  (10262): uid=10253(com.test.sampleapp) expire 1 line
06-28 11:03:53.496 F/DEBUG   (10564): 
06-28 11:03:53.496 F/DEBUG   (10564): backtrace:
06-28 11:03:53.496 F/DEBUG   (10564):       #00 pc 0000000000566cd4  /data/app/com.test.sampleapp-0NtRAAgA9BQSQyIl5GK8QQ==/lib/arm64/libwenet.so (wenet::AsrDecoder::UpdateResult(bool)+584) (BuildId: 49c7da940f5206af8b3cfe7c730a7642e556c012)
06-28 11:03:53.496 F/DEBUG   (10564):       #01 pc 00000000005662d4  /data/app/com.test.sampleapp-0NtRAAgA9BQSQyIl5GK8QQ==/lib/arm64/libwenet.so (wenet::AsrDecoder::AdvanceDecoding(bool)+1524) (BuildId: 49c7da940f5206af8b3cfe7c730a7642e556c012)
06-28 11:03:53.496 F/DEBUG   (10564):       #02 pc 0000000000565cd0  /data/app/com.test.sampleapp-0NtRAAgA9BQSQyIl5GK8QQ==/lib/arm64/libwenet.so (wenet::AsrDecoder::Decode(bool)+40) (BuildId: 49c7da940f5206af8b3cfe7c730a7642e556c012)
06-28 11:03:53.496 F/DEBUG   (10564):       #03 pc 0000000000522b38  /data/app/com.test.sampleapp-0NtRAAgA9BQSQyIl5GK8QQ==/lib/arm64/libwenet.so (wenet::decode_thread_func()+44) (BuildId: 49c7da940f5206af8b3cfe7c730a7642e556c012)
06-28 11:03:53.496 F/DEBUG   (10564):       #04 pc 000000000053d524  /data/app/com.test.sampleapp-0NtRAAgA9BQSQyIl5GK8QQ==/lib/arm64/libwenet.so (BuildId: 49c7da940f5206af8b3cfe7c730a7642e556c012)
06-28 11:03:53.496 F/DEBUG   (10564):       #05 pc 000000000053d480  /data/app/com.test.sampleapp-0NtRAAgA9BQSQyIl5GK8QQ==/lib/arm64/libwenet.so (BuildId: 49c7da940f5206af8b3cfe7c730a7642e556c012)
06-28 11:03:53.496 F/DEBUG   (10564):       #06 pc 000000000053cdf4  /data/app/com.test.sampleapp-0NtRAAgA9BQSQyIl5GK8QQ==/lib/arm64/libwenet.so (_ZNSt6__ndk114__thread_proxyINS_5tupleIJNS_10unique_ptrINS_15__thread_structENS_14default_deleteIS3_EEEEPFvvEEEEEEPvSA_+128) (BuildId: 49c7da940f5206af8b3cfe7c730a7642e556c012)
06-28 11:03:53.496 F/DEBUG   (10564):       #07 pc 00000000000e6a10  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 85ab2bc1ae7f4dbc4ee5d68f94085e8b)
06-28 11:03:53.496 F/DEBUG   (10564):       #08 pc 0000000000084c6c  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 85ab2bc1ae7f4dbc4ee5d68f94085e8b)

**Comment by robin1001** [comment]
Have you fixed the problem?

**Comment by al4fun** [comment]
met the same problem.

**Comment by Mddct** [comment]
reopen this issue if there are still problems

**Comment by zqyp** [comment]
How to fix it? please

**Comment by zqyp** [comment]
> How to fix it? please
fixed it，the reason is the units.txt file have be changed unexpectedly，it's ok when I've repleced it with the original units.txt file

**Comment by zqyp** [comment]
> How to fix it? please

fixed it，the reason is the units.txt file have be changed unexpectedly，it's ok when I've repleced it with the original units.txt file
