### ISSUE TITLE
iOS Problem:I want to Compile the wenet into. a, but I can't 

### ISSUE THREAD

**Issue by smartxiaosiyu** [wenet-e2e/wenet#1899]
I can use CMake to run an iOS project without any problems. Now, I want to compile these C++/C files into a framework so that I can use this framework in my app. However, I'm facing issues and the compilation is not successful. The errors I encountered include "'istream' file not found" and "xxx file not found".

Here's what I did: I used CMake to compile all the ".a" files, and I found the header files in the files. I copied them into my project, but I kept getting errors during the build process.

I would like to know if my approach is correct, and if you have been able to compile successfully.

**Comment by robin1001** [comment]
@Ma-Dan, any idea?

**Comment by Ma-Dan** [comment]
Your approach is correct. Have you modified header search paths setting before compiling?
<img width="758" alt="image" src="https://github.com/wenet-e2e/wenet/assets/38337958/3c4b7fc2-d121-43cf-9d97-199dd3803b48">
