### ISSUE TITLE
paraformer训练第七步无attention rescore

### ISSUE THREAD

**Issue by daihuangyu** [wenet-e2e/wenet#1908]
跑aishell的paraformer，第七步中最后一小步不输出，后发现其没有attention rescore，想问问paraformer这套代码本身就没有这个模块吧，原论文应该是没有这个模块的。

**Comment by robin1001** [comment]
对，paraformer 没有 attention rescore，另外 paraformer 这块的实现不完善，有坑，有兴趣可以踩坑提修改。

**Comment by Mddct** [comment]
请看下最新代码 最新代码兼容阿里实现
