### ISSUE TITLE
在centos7上面运行python setup.py install 出现 不知道如何在系统中定义32位整数的问题

### ISSUE THREAD

**Issue by newday1255** [wenet-e2e/wenet#1910]
运行环境：
系统：centos7 64位
glibc: 2.17 
cmake: 3.15.3
glibc-devel: glibc-devel-2.17-326.el7_9.x86_64

运行日志如下：
/home/platform2/miniconda3/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/home/platform2/miniconda3/lib/python3.9/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing wenetruntime.egg-info/PKG-INFO
writing dependency_links to wenetruntime.egg-info/dependency_links.txt
writing requirements to wenetruntime.egg-info/requires.txt
writing top-level names to wenetruntime.egg-info/top_level.txt
reading manifest file 'wenetruntime.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wenetruntime.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
Setting PYTHON_EXECUTABLE to /home/platform2/miniconda3/bin/python
-- Populating libtorch
-- Configuring done
-- Generating done
-- Build files have been written to: /home/platform2/wenet/runtime/binding/python/fc_base/libtorch-subbuild
[100%] Built target libtorch-populate
-- Populating gflags
-- Configuring done
-- Generating done
-- Build files have been written to: /home/platform2/wenet/runtime/binding/python/fc_base/gflags-subbuild
[100%] Built target gflags-populate
CMake Error at fc_base/gflags-src/CMakeLists.txt:287 (message):
  Do not know how to define a 32-bit integer quantity on your system! Neither
  uint32_t, u_int32_t, nor __int32 seem to be available.  Set
  [GFLAGS_]INTTYPES_FORMAT to either C99, BSD, or VC7 and try again.

**Comment by kli017** [comment]
#1061
