### ISSUE TITLE
wenet在openvino--windows端编译的一些错误

### ISSUE THREAD

**Issue by lvchigo** [wenet-e2e/wenet#1913]
# 问题描述
- 请问目前wenet（20230710），能不能支持openvino的windows端--流式语音识别？？现在onnxruntime方案验证没问题，openvino在VS2022上编译，出现一堆错误：  
![26a8c5cd7904a79835857d5e1dd77ab](https://github.com/wenet-e2e/wenet/assets/8186051/41fdab51-8232-42c9-938a-e3a46a99daac)

# 编译步骤
- wenet代码设置：下载wenet主分支源码包（20230710），且拷贝wenet/runtime/core/下相关文件夹至wenet/runtime/openvino/（如api/bin/decoder等）；
- CMake编译：开启PC端CMake，并设置待编译路径，并配置configure为Visual studio 2022/X64环境；CMake流程正常，依次点击Configure/Generate：    
![image](https://github.com/wenet-e2e/wenet/assets/8186051/1b6d02e4-5b21-4f2b-a953-7dd3fab3549c)    
- 开启Visual studio 2022：或进入runtime\openvino\build目录，找到wenet.sln，双击开启Visual studio 2022；
- 编译wenet库：开启Visual studio后，选定Release与X64环境，并使用“生成”--“生成解决方案”即开始编译：    
![image](https://github.com/wenet-e2e/wenet/assets/8186051/e812a6c8-ae6c-4623-adee-9b201e8a25f0)  
- 解决方案资源管理器加载如下：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/1bad356d-480a-4a11-bedf-3b82682f4c0a)  
- 编译过程中产生错误如下：  
![26a8c5cd7904a79835857d5e1dd77ab](https://github.com/wenet-e2e/wenet/assets/8186051/41fdab51-8232-42c9-938a-e3a46a99daac)

# 环境说明
- windows 10 X64；
- Visual studio 2022；
- CMake 3.27.0-rc3

# 联系方式
- 176032216@qq.com；

**Comment by lvchigo** [comment]
- 通过linux端wenet支持openvino，发现以下几个问题：
    - 1、openvino依赖库需重编译：wenet/runtime/core/cmake/openvino.cmake中，默认下载openvino官方已编译版本；但该版本基于c++11编译，如需应用于wenet，需使用c++14进行openvino源码重编译；
    - 2、指定openvino自编译版本：需调整wenet/runtime/openvino/ov/CMakeLists.txt、wenet/runtime/core/cmake/openvino.cmake等文件，用于支持指定openvino自编译版本；
    - 3、wenet暂不支持openvino-int8：openvino进行int8量化时，官方提供POT与NNCF方案，均需进行数据加载，目前wenet暂未适配；对openvino-int8量化感兴趣，可参考https://docs.openvino.ai/cn/2022.1/openvino_docs_model_optimization_guide.html#doxid-openvino-docs-model-optimization-guide；
    - 4、推理耗时：与onnx-int8版本推理耗时对比，openvino耗时较长；
    - 5、以下为自用推理耗时对比，仅做参考，backbone为u2++conformer：

| 版本  | 说明               |  RTF   | 
| :-------:  |:-------------: |  :-----:  | 
| onnx-int8 | onnx-int8量化版本  | 0.1807 | 
| openvino | openvino未量化版本  | 0.318 | 
| openvino-fp16 | openvino-fp16版本  | 0.314 | 
| openvino-int8 | openvino-int8版本  | wenet暂不支持 | 

- 推理案例：以下为自用版本、基于openvino2023.0.1的wenet流式ASR推理案例：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/52970000-7ea9-40ce-8c60-3fd8b2cd44de)
- 回到本issue，基于windows端编译，建议针对openvino进行源码重编译；

**Comment by Yymax-max** [comment]
最后能不能支持openvino的windows端？
