### ISSUE TITLE
openvino推理速度不如onnxruntime

### ISSUE THREAD

**Issue by WangGewu** [wenet-e2e/wenet#1917]
@FionaZZ92， 在实时流模式下，openvino的RTF高于onnxruntime，这个现象正常吗？
openvino：0.06088
onnxruntime：0.04626
注：
openvino版本：2022.03
onnxruntime版本：0.12.1
cpu：Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz

**Comment by Fred-cell** [comment]
现在IPEX性能比onnxruntime要好， 建议你使用ipex的方式先，就导出模型需要特殊处理一下，剩下的和pytorch的脚本几乎一样，参考runtime/ipex的代码。

**Comment by WangGewu** [comment]
请问有具体的性能对比数据吗？IPEX能快多少。

**Comment by Fred-cell** [comment]
在第四代至强上可以快50%，在以往型号上快6%，后续还有进一步优化，到时更新IPEX版本就行了。

**Comment by WolfKingAlex** [comment]
@Fred-cell 按照readme配置了IPEX的运行时环境，跑起来比onnxrt 要慢四五倍，请问有什么设置开关readme当中没有提到吗

**Comment by Fred-cell** [comment]
@WolfKingAlex 提供一下你的硬件配置信息

**Comment by WolfKingAlex** [comment]
@Fred-cell  Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz 128GBMem， 2xV100(GPU信息应该无关吧)，运行时CPU无其他任何负载。

**Comment by Fred-cell** [comment]
你怎么安装的ipex环境，就是原始的libtorch也不会慢4到5倍

**Comment by WolfKingAlex** [comment]
![image](https://github.com/wenet-e2e/wenet/assets/8457652/69e89f4d-8403-4847-b82e-db8edf9b16e9)
install via source compilation

**Comment by Fred-cell** [comment]
这个是python环境，只限于转换模型，推理不是用的c++代码吗？

**Comment by WolfKingAlex** [comment]
OK，暂时没有自己写代码，推理用的就是wenet/runtime/ipex路径下提供的流程。
![image](https://github.com/wenet-e2e/wenet/assets/8457652/18cfa762-d6c3-4dfa-a3ac-519c8800cd5b)

**Comment by WolfKingAlex** [comment]
我相信您说的是对的，我这里可能存在误操作，但是可以麻烦帮忙看下吗？这两者运行的输出
![img_v2_e33d764f-90cb-46fe-93ef-e0361c9f83fg](https://github.com/wenet-e2e/wenet/assets/8457652/8ee57638-cdc0-47f4-88f1-ed3c2abc30d2)
![img_v2_d2145651-4b54-45cc-aadd-416a9572c70g](https://github.com/wenet-e2e/wenet/assets/8457652/d7340851-d818-430e-a020-65e24d9c5037)

**Comment by WolfKingAlex** [comment]
TCMalloc等选项我尝试了，有5%性能提升，不过没有影响到先在数量级落后的情况。

**Comment by Fred-cell** [comment]
输出怎么是空的？

**Comment by WolfKingAlex** [comment]
@Fred-cell 输出就是这句，and that the one to get the out of shop and soi'm of course, 因为是用的内部的其他数据和下载下来模型在推理，结果暂时没有那么精确，但俩结果在onnxrt和ipex上一致

**Comment by Fred-cell** [comment]
ipex有个warmup的过程，多测试点数据，不要只测试1条。

**Comment by WolfKingAlex** [comment]
也就是说wenet在ipex上需要warmup才会达到相当于onnxrt或者超过onnxrt的性能？

**Comment by Fred-cell** [comment]
也就前面1条语音，服务启动的时候，只warmup一次，后面的都是快的

**Comment by WolfKingAlex** [comment]
我这里非流式的按顺序去推理批量数据，这样也算服务启动吗？

**Comment by Fred-cell** [comment]
非流式上GPU呗，你要的是大吞吐还是大并发，根据自己的需求来。

**Comment by WolfKingAlex** [comment]
好的，不过这里是初步测试下ipex和onnxrt性能对比，可以麻烦您帮忙看下前面信息判断下是不是ipex的配置使用有误导致单次推理性能很差吗？
