### ISSUE TITLE
efficient conformer is not supported in onnxruntime yet？

### ISSUE THREAD

**Issue by wbjnpu** [wenet-e2e/wenet#1918]
I CAN transfer efficient conformer from torch model to onnx model correctly. But it does not work in onnxruntime build project.

**Comment by zwglory** [comment]
If you export the **streaming model** using `export_onnx_gpu.py`, it will work properly when using https://github.com/wenet-e2e/wenet/tree/main/runtime/gpu/model_repo_stateful .

However, when you want to deploy **non-streaming model**, you can replace https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/model_repo/feature_extractor/1/model.py with https://huggingface.co/58AILab/wenet_efficient_conformer_aishell_v1/blob/main/model_repo_feature_extractor/model.py

Or, you can add the following code after https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/model_repo/feature_extractor/1/model.py#L127
```
            feat_len = ((expect_feat_len-1)//2 - 1) // 2
            print(f"before: expect_feat_len={expect_feat_len}, feat_len={feat_len}")
            if feat_len % 3 > 0:
                expect_feat_len = expect_feat_len + (feat_len % 3 - 1) * 4
            print(f"after: expect_feat_len={expect_feat_len}, feat_len={((expect_feat_len-1)//2 - 1) // 2}")
```

**Comment by wbjnpu** [comment]
how about export with export-onnx-cpu.py and inference using runtime/onnxtuntime compiled project, with streaming model.

**Comment by zwglory** [comment]
Unfortunately, we have not yet tested the Streaming EfficientConformer ONNX model on CPU, 

But you are welcome to explore its implementation by referring to the provided code below.

- https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_onnx_gpu.py#L433
- https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_onnx_gpu.py#L854

We will also test it when we have time.

**Comment by wbjnpu** [comment]
> Unfortunately, we have not yet tested the Streaming EfficientConformer ONNX model on CPU, 
> 
> But you are welcome to explore its implementation by referring to the provided code below.
> 
> - https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_onnx_gpu.py#L433
> - https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_onnx_gpu.py#L854
> 
> We will also test it when we have time.

I test it in cpu and it work. But limit to the same parameters, and under the same subsampling factor, efficientformer is slower about 1/3 than conformer.  So it looks like has no visibly perference.

**Comment by zwglory** [comment]
Our CPU test is based on the JIT model, and the inference speed has been improved to a certain extent. If we have time, we will also test on the onnx.

**Comment by senbukai0203** [comment]
Hi Guys! any update on it?

**Comment by bourne979** [comment]
Same question- any updates on onnx-cpu export for models with efficient conformer or squeezeformer encoders?

**Comment by senbukai0203** [comment]
Hi..it is been a while no communication in this thread. Any update/support on Onnxruntime CPU export for efficient conformer?

**Comment by wbjnpu** [comment]
> Hi..it is been a while no communication in this thread. Any update/support on Onnxruntime CPU export for efficient conformer? Thanks

NO，the same as what conformer export do

**Comment by senbukai0203** [comment]
Managed to export efficient conformer in onnx format and tried decoding with decoder_main, but it crashed with "segmentation fault". Does current decoder_main support efficient conformer or there is some issue while exporting the econformer ONNX model. Thanks!
