### ISSUE TITLE
对于杂音敏感且产生很多错误输出

### ISSUE THREAD

**Issue by mukang98** [wenet-e2e/wenet#1925]
通过网页版 websocket 客户端实时识别语音时，由于没有额外假如VAD，系统对于杂音会产生很多错误输出。
1.对于非常细微的杂音也会有输出，想先通过设置声音的输入阈值的方式减少一些杂音的输入，请问哪里可以设置？
2.有人自己加过VAD吗？效果如何？有推荐的VAD资源吗？

**Comment by robin1001** [comment]
1. 可以试试提供的 wenetspeech 的模型。
2. VAD @pengzhendong 麻烦推荐个好用的 VAD。

**Comment by pengzhendong** [comment]
1. Silero-VAD: https://github.com/snakers4/silero-vad
2. FSMN-Monophone VAD: https://modelscope.cn/models/damo/speech_fsmn_vad_zh-cn-16k-common-pytorch/summary

**Comment by mukang98** [comment]
@robin1001 @pengzhendong 已经试过了wenetspeech模型，会好一些。多谢分享！
