### ISSUE TITLE
TypeError: spec_aug() got an unexpected keyword argument 'warp_for_time’

### ISSUE THREAD

**Issue by yangb05** [wenet-e2e/wenet#1926]
I tried to train a streaming model according to [the tutorial](https://wenet.org.cn/wenet/tutorial_librispeech.html) by replacing the config file with 'train_u2++_conformer.yaml' without changing any configuration. However, the training process is teminated by the error:

> TypeError: spec_aug() got an unexpected keyword argument 'warp_for_time’

I checked 'train_u2++_conformer.yaml', there's indeed an item named 'warp_for_time’ under 'spec_aug_conf', and the default value is 'true'. So I just commented out it and the training seems alright for now. 

I take it as a bug since it happens under default setting. I also want to know what 'warp_for_time’ means and the effect it does for traning.

**Comment by robin1001** [comment]
Yes, it's a bug, fixed, please see https://github.com/wenet-e2e/wenet/pull/1927.
