### ISSUE TITLE
"illegal instruction" happens when cross-complied with aarch64-rockchip-linux-gnu

### ISSUE THREAD

**Issue by locasxe** [wenet-e2e/wenet#1934]
I tried to test wenet with aarch64-rockchip-linux-gnu platform.
Following the pipeline of [onnxruntime] and [raspberrypi], I used the toolchain aarch64-rockchip-linux-gnu to build the ‘decoder_main’ executable file. It was done.
But, the error "illegal instruction" occurred when running ‘decoder_main’.

Is there any idea to fix it?

**Comment by xingchensong** [comment]
could you try compile runtime on-board（on your rockchip） ？

**Comment by locasxe** [comment]
> could you try compile runtime on-board（on your rockchip） ？
thx for your reply
We had tried to complie it directly on device, however, it didn't work. 
We also tried something else (other modules,) to make sure the toolchain is fine. It seems the error only occurs when running 'decoder_main'
