### ISSUE TITLE
Doesn't wenet support torch 1.12.1 version ?

### ISSUE THREAD

**Issue by Sang-Hoon-Pakr** [wenet-e2e/wenet#1938]
when i install wenet with torch i saw this issue

**"wenetruntime 1.12.0 requires torch==1.12.0, but you have torch 1.12.1+cu113 which is incompatible."**

i have to install torch=1.12.1 bacause my cuda version 11.3 

how can i overcome this issue? 
thank you

**Comment by robin1001** [comment]
wenet do support torch 1.12.1, we do not upgrade the dependency to the latest, so just update it.
