### ISSUE TITLE
在运行时出现一个问题

### ISSUE THREAD

**Issue by beetter** [wenet-e2e/wenet#1939]
./build/bin/websocket_server_main: error while loading shared libraries: libonnxruntime.so.1.12.0: cannot open shared object file: No such file or directory 缺少一个so文件，我添加进去了并创建了软连接也没有用。

**Comment by robin1001** [comment]
检查库的路径，添加合适的路径。

**Comment by wwfcnu** [comment]
pip install onnxruntime之后没找到这个libonnxruntime.so.1.12.0文件
