### ISSUE TITLE
在arm架构运行onnxruntime进行测试的时候出现报错

### ISSUE THREAD

**Issue by cplzl** [wenet-e2e/wenet#1950]
运行如下指令进行测试，出现报错，怎么解决？？
export GLOG_logtostderr=1
export GLOG_v=2
wav_path=/media/c1-633/tf/asrdata/data_aishell/wav/test/s0764/BAC009S0764W0122.wav
onnx_dir=/media/c1-633/tf/wenet1/onnx
units=/media/c1-633/tf/xunlian/aishell_u2pp_conformer_exp/units.txt  # Change it to your model units path
# Make sure that the `chunk_size` and `num_left_chunks` variables are set to the corresponding values used when exporting the ONNX models.
./build/bin/decoder_main \
    --chunk_size 16 \
    --num_left_chunks -1 \
    --wav_path $wav_path \
    --onnx_dir $onnx_dir \
    --unit_path $units 2>&1 | tee log.txt
报错信息：
I0817 16:38:01.740577 57015 params.h:145] Reading onnx model 
I0817 16:38:02.549082 57015 onnx_asr_model.cc:128] Onnx Model Info:
I0817 16:38:02.549158 57015 onnx_asr_model.cc:129]      encoder_output_size 256
I0817 16:38:02.549167 57015 onnx_asr_model.cc:130]      num_blocks 12
I0817 16:38:02.549171 57015 onnx_asr_model.cc:131]      head 4
I0817 16:38:02.549175 57015 onnx_asr_model.cc:132]      cnn_module_kernel 15
I0817 16:38:02.549178 57015 onnx_asr_model.cc:133]      subsampling_rate 4
I0817 16:38:02.549182 57015 onnx_asr_model.cc:134]      right_context 6
I0817 16:38:02.549185 57015 onnx_asr_model.cc:135]      sos 4232
I0817 16:38:02.549188 57015 onnx_asr_model.cc:136]      eos 4232
I0817 16:38:02.549191 57015 onnx_asr_model.cc:137]      is bidirectional decoder 0
I0817 16:38:02.549203 57015 onnx_asr_model.cc:138]      chunk_size 16
I0817 16:38:02.549207 57015 onnx_asr_model.cc:139]      num_left_chunks -1
I0817 16:38:02.549211 57015 onnx_asr_model.cc:142] Onnx Encoder:
I0817 16:38:02.549250 57015 onnx_asr_model.cc:53]       Input 0 : name=chunk type=1 dims=1 -1 80 
I0817 16:38:02.549265 57015 onnx_asr_model.cc:53]       Input 1 : name=offset type=7 dims=
I0817 16:38:02.549278 57015 onnx_asr_model.cc:53]       Input 2 : name=att_cache type=1 dims=12 4 -1 128 
I0817 16:38:02.549291 57015 onnx_asr_model.cc:71]       Output 0 : name=output type=1 dims=-1 -1 -1 
I0817 16:38:02.549302 57015 onnx_asr_model.cc:71]       Output 1 : name=r_att_cache type=1 dims=12 4 -1 128 
I0817 16:38:02.549310 57015 onnx_asr_model.cc:71]       Output 2 : name=r_cnn_cache type=1 dims=12 0 0 0 
I0817 16:38:02.549315 57015 onnx_asr_model.cc:144] Onnx CTC:
I0817 16:38:02.549325 57015 onnx_asr_model.cc:53]       Input 0 : name=hidden type=1 dims=1 -1 256 
I0817 16:38:02.549338 57015 onnx_asr_model.cc:71]       Output 0 : name=probs type=1 dims=1 -1 4233 
I0817 16:38:02.549343 57015 onnx_asr_model.cc:146] Onnx Rescore:
I0817 16:38:02.549355 57015 onnx_asr_model.cc:53]       Input 0 : name=hyps type=7 dims=-1 -1 
I0817 16:38:02.549365 57015 onnx_asr_model.cc:53]       Input 1 : name=hyps_lens type=7 dims=-1 
I0817 16:38:02.549376 57015 onnx_asr_model.cc:53]       Input 2 : name=encoder_out type=1 dims=1 -1 256 
I0817 16:38:02.549384 57015 onnx_asr_model.cc:71]       Output 0 : name=score type=1 dims=-1 -1 4233 
I0817 16:38:02.549391 57015 onnx_asr_model.cc:71]       Output 1 : name=r_score type=1 dims=
I0817 16:38:02.549404 57015 params.h:197] Reading unit table /media/c1-633/tf/xunlian/aishell_u2pp_conformer_exp/units.txt
W0817 16:38:02.555260 57021 wav.h:67] Error in read /media/c1-633/tf/asrdata/data_aishell/wav/test/s0764/BAC009S0764W0122.wav
F0817 16:38:02.555336 57021 decoder_main.cc:48] Check failed: wav_reader.sample_rate() == FLAGS_sample_rate (91 vs. 16000) 
*** Check failure stack trace: ***
    @     0xaaaac19e6094  google::LogMessage::Fail()
    @     0xaaaac19e5f98  google::LogMessage::SendToLog()
    @     0xaaaac19e58b4  google::LogMessage::Flush()
    @     0xaaaac19e8eb4  google::LogMessageFatal::~LogMessageFatal()
    @     0xaaaac16b8bb0  decode()
    @     0xaaaac16d67f8  std::__invoke_impl<>()
    @     0xaaaac16d64ec  std::__invoke<>()
    @     0xaaaac16d60f8  _ZNSt5_BindIFPFvSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES6_EbES7_bEE6__callIvJEJLm0ELm1EEEET_OSt5tupleIJDpT0_EESt12_Index_tupleIJXspT1_EEE
    @     0xaaaac16d5b24  std::_Bind<>::operator()<>()
    @     0xaaaac16d527c  std::__invoke_impl<>()
    @     0xaaaac16d4d84  std::__invoke<>()
    @     0xaaaac16d3b04  _ZZNSt13__future_base11_Task_stateISt5_BindIFPFvSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_EbES9_bEESaIiEFvvEE6_M_runEvENKUlvE_clEv
    @     0xaaaac16d5c04  _ZNKSt13__future_base12_Task_setterISt10unique_ptrINS_7_ResultIvEENS_12_Result_base8_DeleterEEZNS_11_Task_stateISt5_BindIFPFvSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESF_EbESG_bEESaIiEFvvEE6_M_runEvEUlvE_vEclEv
    @     0xaaaac16d5364  _ZNSt17_Function_handlerIFSt10unique_ptrINSt13__future_base12_Result_baseENS2_8_DeleterEEvENS1_12_Task_setterIS0_INS1_7_ResultIvEES3_EZNS1_11_Task_stateISt5_BindIFPFvSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESI_EbESJ_bEESaIiEFvvEE6_M_runEvEUlvE_vEEE9_M_invokeERKSt9_Any_data
    @     0xaaaac16bf90c  std::function<>::operator()()
    @     0xaaaac16bd3a4  std::__future_base::_State_baseV2::_M_do_set()
    @     0xaaaac16c633c  std::__invoke_impl<>()
    @     0xaaaac16c3118  std::__invoke<>()
    @     0xaaaac16bf4c0  _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENKUlvE_clEv
    @     0xaaaac16bf500  _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENKUlvE0_clEv
    @     0xaaaac16bf51c  _ZZSt9call_onceIMNSt13__future_base13_State_baseV2EFvPSt8functionIFSt10unique_ptrINS0_12_Result_baseENS4_8_DeleterEEvEEPbEJPS1_S9_SA_EEvRSt9once_flagOT_DpOT0_ENUlvE0_4_FUNEv
    @     0xffff89fd83b8  __pthread_once_slow
    @     0xaaaac16bae64  __gthread_once()
    @     0xaaaac16bf5f0  std::call_once<>()
    @     0xaaaac16bceb8  std::__future_base::_State_baseV2::_M_set_result()
    @     0xaaaac16d3b78  std::__future_base::_Task_state<>::_M_run()
    @     0xaaaac16c50d4  std::packaged_task<>::operator()()
    @     0xaaaac16c0ecc  _ZZN10ThreadPool7enqueueIRFvSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_EbEJRS8_bEEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOSE_DpOSF_ENKUlvE_clEv
    @     0xaaaac16cf900  _ZNSt17_Function_handlerIFvvEZN10ThreadPool7enqueueIRFvSt4pairINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_EbEJRSA_bEEESt6futureINSt9result_ofIFT_DpT0_EE4typeEEOSG_DpOSH_EUlvE_E9_M_invokeERKSt9_Any_data
    @     0xaaaac16bff94  std::function<>::operator()()
    @     0xaaaac16bd704  _ZZN10ThreadPoolC4EmENKUlvE_clEv
    @     0xaaaac16d63fc  _ZSt13__invoke_implIvZN10ThreadPoolC4EmEUlvE_JEET_St14__invoke_otherOT0_DpOT1_

**Comment by robin1001** [comment]
看起来是 wav 文件格式有问题，检查一下 wav 文件。

**Comment by cplzl** [comment]
![image](https://github.com/wenet-e2e/wenet/assets/132201414/51ccaff8-f41c-4ef9-bcd1-053947e5acfa)
您好 wav文件没有问题啊 试了好多不同的文件都是这样的情况 右键属性采样率都是16000 不知道是什么问题？

**Comment by pengzhendong** [comment]
``` bash
soxi /media/c1-633/tf/asrdata/data_aishell/wav/test/s0764/BAC009S0764W0122.wav
```

**Comment by cplzl** [comment]
> ```shell
> soxi /media/c1-633/tf/asrdata/data_aishell/wav/test/s0764/BAC009S0764W0122.wav
> ```

您好 我输入了这个指令 结果如下
![image](https://github.com/wenet-e2e/wenet/assets/132201414/8d26b435-b6c7-491f-8fa7-5b802929a95b)

**Comment by yudefu** [comment]
> > ```shell
> > soxi /media/c1-633/tf/asrdata/data_aishell/wav/test/s0764/BAC009S0764W0122.wav
> > ```
> 
> 您好 我输入了这个指令 结果如下 ![image](https://user-images.githubusercontent.com/132201414/263037491-8d26b435-b6c7-491f-8fa7-5b802929a95b.png)

你好：可以请教一个问题吗？我在利用bin目录下的脚本export_jit.py导出torchscript模式的模型时，发现用netron打不开（采用的是checkpoints模型），你知道为什么吗
