### ISSUE TITLE
About rnnt loss

### ISSUE THREAD

**Issue by Lingeng56** [wenet-e2e/wenet#1951]
有一个东西真的很困惑我，我自己实现的conformer-rnnt，模型参数的名字完全对齐了大佬们提供的examples的代码训练出来的参数，并且我自己实现的模型直接加载用wenet训练的参数可以正确的做预测，但是训练的loss的刻度差别真的好大，我的都是几百，但是wenet跑的时候loss是两位数甚至个位数，请问log出来的loss是做过什么处理吗

**Comment by robin1001** [comment]
可以对一下细节，看看 loss 有没有做归一化等。

**Comment by Mddct** [comment]
<img width="502" alt="Screenshot 2023-08-29 at 22 26 16" src="https://github.com/wenet-e2e/wenet/assets/4906435/b035d287-da11-4907-b40e-35808ac9b3ab">

是用的torchaudio 的rnnt loss吗， 请注意下使用的那种reduction

**Comment by Mddct** [comment]
如果还有疑问的话 可以reopen这个issue
