### ISSUE TITLE
使用CtcWfstBeamSearch解码FinalizeSearch后得分降很多

### ISSUE THREAD

**Issue by Ryuk17** [wenet-e2e/wenet#1958]
我用CtcWfstBeamSearch进行解码，Partial result top 1得分是-13.8233，但是经过FinalizeSearch后，top 1得分降到了-31.7852，有时候top1因为得分降太多被其他超过了。请问这是语言模型的问题还是声学模型的问题？
https://github.com/wenet-e2e/wenet/blob/f393be9bc816fef57c6dc8ce85134ef40a4ce1e4/runtime/core/decoder/ctc_wfst_beam_search.cc#L125

**Comment by robin1001** [comment]
FinalizeSearch 会再加上 Rescoring 的得分，详见：https://github.com/wenet-e2e/wenet/blob/main/runtime/core/decoder/asr_decoder.cc#L239

**Comment by Ryuk17** [comment]
我的意思是再加上 Rescoring 的得分之前FinalizeSearch的得分已经掉了
![image](https://github.com/wenet-e2e/wenet/assets/22525811/0d6d41f3-32cb-4a91-8fb7-62b1957a897d)

**Comment by robin1001** [comment]
在 FinalizeSearch 的时候会加一个 Final() 的得分，也就是以该词该状态结束的得分。

**Comment by Ryuk17** [comment]
能请教下为什么以该词该状态结束的得分会突然降低呢

**Comment by robin1001** [comment]
以该状态、该字结束的语言模型的概率不高。你可以提供一下你具体的 case。

**Comment by Ryuk17** [comment]
感谢回答，因为不是语音识别任务不好提供case。
