### ISSUE TITLE
基于onnxruntime的模型加载内存泄漏

### ISSUE THREAD

**Issue by lvchigo** [wenet-e2e/wenet#1964]
**Describe the bug**
- 使用[wenet/runtime/onnxruntime](https://github.com/wenet-e2e/wenet/tree/main/runtime/onnxruntime)流程，编译流式wenet库，并参考wenet_api接口（wenet/runtime/core/api/wenet_api.h）与demo（wenet/runtime/core/bin/api_main.cc），同时使用valgrind进行内存泄漏检测，发现在onnxruntime的模型加载时（wenet::OnnxAsrModel::Read），出现以下内存泄漏：    
![image](https://github.com/wenet-e2e/wenet/assets/8186051/463d275d-2ea2-4af2-a9e6-cb83e6942154)    
- 且泄漏接口包含三处接口：Ort::ModelMetadata::LookupCustomMetadataMap、Ort::Session::GetInputName、Ort::Session::GetOutputName：
![image](https://github.com/wenet-e2e/wenet/assets/8186051/428c1b64-70f8-4ec2-8da6-e295a364f1f5)  
- 但，除去模型初始化时内存泄漏问题，整体WER验证c++端与python端一致，推理过程中无内存泄漏情况发生；
- 同时，查看onnxruntime v1.12.0源码，发现LookupCustomMetadataMap接口，有提示内存泄漏风险：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/4767036f-b98c-4ce5-88ab-7c19f6598b53)  
- 推荐解决方案：使用LookupCustomMetadataMapAllocated、GetInputNameAllocated、GetOutputNameAllocated替换原有接口即可（LookupCustomMetadataMap、GetInputName、GetOutputName）：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/a97bee30-8662-43df-985c-17b19779ca64)  

**编译环境**
- GCC：7.5.0；
- onnxruntime：1.12.0、CPU版；

**联系方式:**
 - 176032216@qq.com

**Comment by xingchensong** [comment]
谢谢，可以直接提个PR修复嘛，非常感谢！

**Comment by xingchensong** [comment]
Update: 尝试了更换三个接口，程序无法运行成功（如下图所示），原因可能是session->run函数需要传入节点的name，这些name是const char*，在替换了接口后，这些pointer在出了初始化函数后被释放了。

![image](https://github.com/wenet-e2e/wenet/assets/13466943/624a4bb8-ef00-4e79-9d6d-7c6027420b56)

![image](https://github.com/wenet-e2e/wenet/assets/13466943/ee27a12a-5ab1-4f8f-b052-d22b6dffa843)

**Comment by xingchensong** [comment]
https://bbs.huaweicloud.com/blogs/357047    @lvchigo 或许这篇blog的方法可以借鉴下

**Comment by lvchigo** [comment]
- 参考上述blog方案，进行内存泄漏复现，同时加入try-catch捕获异常，发现ASR推理时，仍提示指针被提前释放；
- 修改源码如下：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/0c349cf1-d4d2-40c1-8bb5-7a6bad22a4bf)  
- wenet-onnx源码编译通过，ASR模型加载通过，但在ASR推理时，提示指针被提前释放（与GetInputNameAllocated替换GetInputName方案问题一致）；即GetInputName与GetOutputName内存泄漏问题修复，但ASR推理异常：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/8b4eb42e-f636-4ca6-b2d6-ce00dbb027cf)  
- ASR推理异常问题点：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/21a33723-0fda-4aa3-89f1-4de63a5ccac0)

**Comment by lvchigo** [comment]
- 已参考上述blog进行“string标准库”方案复现，然而仅解决接口（GetInputName与GetOutputName）内存泄漏问题，ASR推理时，encoder_session_->Run提示encoder_out_names_错误（即指针被提前释放）：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/e8cfdfec-3e45-4914-9315-0b2e5335ebdb)  
- 同时，参考onnxruntime的修复方案（https://github.com/microsoft/onnxruntime/issues/10490），编写OnnxAsrModel的析构函数，用于释放资源（如encoder_in_names_、encoder_out_names_、ctc_in_names_、ctc_out_names_、rescore_in_names_、rescore_out_names_）；
- 然而，接口（GetInputName与GetOutputName）内存泄漏问题，仍然存在，具体析构函数代码如下参考：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/0da4863f-9c1f-4f63-ac9a-76d8b2257517)  
- @xingchensong GetInputName与GetOutputName内存泄漏问题，还需要大佬帮忙看看。。

**Comment by xingchensong** [comment]
@lvchigo onnxruntime最新版应该在API上有不少改动，可以试试最新版的onnxruntime 在run这个api上是否还需要以来const char*的输入？

**Comment by zhuanaa** [comment]
Anybody come across this？

**Comment by xingchensong** [comment]
> @lvchigo 参照此可解决：[microsoft/onnxruntime#14157](https://github.com/microsoft/onnxruntime/issues/14157) onnxruntime ：1.13.1

可以提个pr吗
