### ISSUE TITLE
英文语料中<unk>被错误tokenize为<, U, N, K, >

### ISSUE THREAD

**Issue by jianganbai** [wenet-e2e/wenet#1969]
**bug描述**

若输入英文语料库中含有`<unk>`等特殊token，则tokenize后会被拆分识别为`<, U, N, K, >`。

原因在于，输入的英文转录，首先会全部转为大写，详见wenet/dataset/processor.py的332行。

![image](https://github.com/wenet-e2e/wenet/assets/50263321/82ffb955-c8c3-4b5a-a87e-8987066fecf8)

此时`<unk>`会被转为`<UNK>`，导致无法被正确切分。

**Comment by xingchensong** [comment]
good catch，可以提个PR吗

**Comment by robin1001** [comment]
在训练时 train.py 带个 --non_lang_syms 的参数就可以，把 <unk> 放进这个文件中，如果除了这个标签还有其他特殊标签的话，也一并放进去。详见 https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/train.py#L103C28-L103C41。
