### ISSUE TITLE
Chinese Characters  repeated 

### ISSUE THREAD

**Issue by jayakrishnanmm** [wenet-e2e/wenet#1971]
I have  trained  a  Chinese  Model from Aishell corpus. Converted to ONNX.
With chunk_size=-1  and  left_chunk_size=-1,  I tried to decode  a ~1 min audio, it  is  fine. (See results below)
多年来跑步都是以年轻男性为主的一个活动然后这次反而吸引到很多比较年长的女性也是出乎我们的意料的当然我们有跟他们聊一聊当时他们第一次发
现跑酷他们的第一次的那个一印象是怎样的他们刚开始是觉得蛮蛮可怕的不过他们也是充满了一些好奇心觉得很好玩然后毕竟这些年长者偶尔他们也是见过>那种工人跑步还是健身房的运动对他们来说他们是想尝试新的活动学习一些新的技巧尤其是可能对他们来说年长年长年长者需要学习如何叠导如何强化身体>是一个非常重要的一件事所以他们学习跑酷的时候其实有如孩童一般在邻里玩耍的一种感觉就恢复儿时的那种天真玩耍的那种状态其实他们都非常享受的很>多的学员都是大概六十岁到七十岁左右尤其是疫情期间我们也见到了一些好一些六十多岁的年长者来加入大部分的年长者学员都是女性我们发现到

With  chunk_size=16  and  left_chunk_size=-1 , some  characters  are repeated. See  below  output 
 多年来来跑步不都是以年年轻难男性为主组的一个活我懂啊然后这次反反呢信领到很多多比比较年长的米女性也是出出乎我们的意料你当然当然我们有
跟了他们聊了一聊啊当当时他们跟第一次发发现跑酷他们的呃啊呃第一一次的那个一个一定说像是怎样的他们刚刚开始是觉得蛮蛮可怕他的包过说他他们也>是是充满了没一些好奇心觉得他好玩然后毕竟进这些这年讲者不果他们也是建过那种工人跑跑步还是建身房的运懂对他们他们来说他们是想尝试是新的活我>懂其习一些这性的技巧尤其是是可能对他们他们来说年长嗯年长嗯那年长者学需要学习如和别导如或强化生身体是一个非以常重要要的一件事所以他们他学>习跑包括的时候其实是有如啊还从一般在零里玩书所的种感感觉就就会恢复不呃俄时就的那种天跟增玩耍的那种涨上态其实他们都说非常享受的呃很多或的>学员都是是大概六就是隧到其车也是岁左用呃用尤其是疫情之这呃钱其间我们我们也见到了一些好跑一些六十多多岁的本年长当者来加入大部分嗯的年长者>学员都说是女性我们发现到嗯

The  repeating character is  different  when  chunk_size =32

The same  is true for continuous_decoding option also. (chunk_size=16  or  32)

Is there  any problem  with  segmentation.  I am using  the latest runtime  code. I have  verified  that English  model  has  no such problem  with the  same runtime

**Comment by jayakrishnanmm** [comment]
1. ONNX  is  CPU
2. Will  try this. But  for  English  model , normally I set chunk_size=-1  during ONNX conversion,  and have no  problem using chunk_size=16  with decoder_main

**Comment by jayakrishnanmm** [comment]
I did  convert to  ONNX  with  chunk_size=16  and  used  the same  with decoder_main.  The  result  still  have the same problem
test 多年来来跑步不都是以年年轻难男性为主组的一个活我懂啊然后这次反反呢信领到很多多比比较年长的米女性也是出出乎我们的意料你当然当然我们有
跟了他们聊了一聊啊当当时他们跟第一次发发现跑酷他们的呃啊呃第一一次的那个一个一定说像是怎样的他们刚刚开始是觉得蛮蛮可怕他的包过说他他们也>是是充满了没一些好奇心觉得他好玩然后毕竟进这些这年讲者不果他们也是建过那种工人跑跑步还是建身房的运懂对他们他们来说他们是想尝试是新的活我>懂其习一些这性的技巧尤其是是可能对他们他们来说年长嗯年长嗯那年长者学需要学习如和别导如或强化生身体是一个非以常重要要的一件事所以他们他学>习跑包括的时候其实是有如啊还从一般在零里玩书所的种感感觉就就会恢复不呃俄时就的那种天跟增玩耍的那种涨上态其实他们都说非常享受的呃很多或的>学员都是是大概六就是隧到其车也是岁左用呃用尤其是疫情之这呃钱其间我们我们也见到了一些好跑一些六十多多岁的本年长当者来加入大部分嗯的年长者>学员都说是女性我们发现到嗯

**Comment by xingchensong** [comment]
could you share your audio files？

**Comment by jayakrishnanmm** [comment]
I found it. The model  is  not  u2pp. That's why  chunk_size=16 could not   work.  Thanks.
