### ISSUE TITLE
ImportError: libtorch.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by danliangsky** [wenet-e2e/wenet#1972]
新的虚拟环境，然后运行 pip3 install wenetruntime

代码中只有一行代码 import wenetruntime

报错: ImportError: libtorch.so: cannot open shared object file: No such file or directory

**Comment by danliangsky** [comment]
是需要自己安装 pytorch 吗

**Comment by robin1001** [comment]
是的。
