### ISSUE TITLE
请问 websocket 支持并发吗？

### ISSUE THREAD

**Issue by MarsMeng1994** [wenet-e2e/wenet#1973]
您好
我正在使用 runtime/libtorch的websocket_server_main搭建服务器，但看代码感觉是1对1的交互过程，请问是否支持并发呢？

**Comment by robin1001** [comment]
支持，使用线程支持的，来一个请求，会创建一个新线程以支持并发，详见 https://github.com/wenet-e2e/wenet/blob/main/runtime/core/websocket/websocket_server.cc#L259
