### ISSUE TITLE
运行runtime的DEMO报错import _wenet ImportError: DLL load failed: 找不到指定的模块。

### ISSUE THREAD

**Issue by 50ZAIofficial** [wenet-e2e/wenet#1974]
**Describe the bug**
我使用runtime界面上的简易demo测试wenet的可用性，环境配置为anaconda python3.7：
`import sys`
`import wenetruntime as wenet`
`audio_file = sys.argv[1]  # support wav, mp3, flac, etc`
`decoder = wenet.Decoder(lang='chs')`
`ans = decoder.decode("XX.wav")`
`print(ans)`

但是我在pycharm中得到这个

`Traceback (most recent call last):`
  `File "D:\XX\main.py", line 2, in <module>`
   ` import wenetruntime as wenet`
 ` File "C:\ProgramData\anaconda3\envs\wn\lib\site-packages\wenetruntime\__init__.py", line 1, in <module>`
 `   from .decoder import Decoder  # noqa`
`  File "C:\ProgramData\anaconda3\envs\wn\lib\site-packages\wenetruntime\decoder.py", line 17, in <module>`
 `   import _wenet`
`ImportError: DLL load failed: 找不到指定的模块。`
小白第一次尝试使用，希望大佬们指教/(ㄒoㄒ)/~~

**Comment by cdliang11** [comment]
可能需要导入torch包，试下

```
import torch
import wenetruntime as wenet
```

**Comment by Mddct** [comment]
> 可能需要导入torch包，试下
> 
> ```
> import torch
> import wenetruntime as wenet
> ```

@50ZAIofficial  你可以试下这个

**Comment by Mddct** [comment]
pip install wenetruntime==1.0.13 --upgrade 或者使用下这个版本， 
当前wheel release 版本有bug https://github.com/wenet-e2e/wenet/issues/1976

**Comment by yuyun2000** [comment]
都会报错的哥哥

**Comment by yuyun2000** [comment]
pip install wenetruntime==1.13.0

**Comment by 50ZAIofficial** [comment]
> pip install wenetruntime--upgrade 或者使用下最新版本， 当前wheel release 版本有bug #1976 fix #1977

已经解决了，非常感谢
