### ISSUE TITLE
不能使用 GPU推理吗？

### ISSUE THREAD

**Issue by danliangsky** [wenet-e2e/wenet#1975]
import torch
import wenetruntime as wenet

gpu_id = 7
torch.cuda.set_device(gpu_id)

decoder = wenet.Decoder(lang='chs')
ans = decoder.decode_wav('output.wav')
print(ans)

好像 gpu 并没有动静啊 ，我装的 torch 是 gpu 版本

**Comment by robin1001** [comment]
目前还不支持 GPU。@Mddct 确实可以考虑下支持 GPU。

**Comment by danliangsky** [comment]
> 目前还不支持 GPU。@Mddct 确实可以考虑下支持 GPU。

啊这。。。CPU推理速度有点感人。。。

**Comment by robin1001** [comment]
安装最新的 wenetruntime 试试

**Comment by Mddct** [comment]
> > 目前还不支持 GPU。@Mddct 确实可以考虑下支持 GPU。
> 
> 啊这。。。CPU推理速度有点感人。。。

你可以多推两条看看 可能有wanmup 前几条快

**Comment by robin1001** [comment]
慢的主要原因以前默认是流式推理，最近改默认非流推理了，又快效果又好。
