### ISSUE TITLE
利用预训练模型进行模型转化时：ModuleNotFoundError: No module named 'wenet'

### ISSUE THREAD

**Issue by yudefu** [wenet-e2e/wenet#1984]
你好作者：我按照doc里面的安装步骤安装了必要的环境，利用你们提供的预训练模型时发现提供的是断点模型，想把模型通过wenet/wenet/wenet/bin下面的脚本转化为对应的onnx或者jit时，报如下错误：
Traceback (most recent call last):
  File "export_jit.py", line 23, in <module>
    from wenet.utils.checkpoint import load_checkpoint
ModuleNotFoundError: No module named 'wenet'

执行指令：python3 export_jit.py --config ../../../../triton/20220506_u2pp_conformer_exp/train.yaml --checkpoint ../../../../triton/20220506_u2pp_conformer_exp/final.pt --output_file torch_jit_model

辛苦帮忙看看啦

**Comment by robin1001** [comment]
在 wenet 同级目录下执行，即 python wenet/bin/export_jit.py ...

**Comment by yudefu** [comment]
> 在 wenet 同级目录下执行，即 python wenet/bin/export_jit.py ...

好像还是不太行，我试了不同的目录层级下执行，都报上面的错误；会不会是环境没有安装好？
![image](https://github.com/wenet-e2e/wenet/assets/39699204/735360da-eb7f-4fb9-a191-d4fdb60bcf9c)

**Comment by yudefu** [comment]
通过这种方式可以解决上述的问题：

import sys
sys.path.insert(0, '/home/wenet_code/wenet')

**Comment by Mddct** [comment]
或者 export PYTHONPATH=/home/wenet_code/wenet
