### ISSUE TITLE
利用bin目录下的export脚本导出的转换模型无法用netron打开

### ISSUE THREAD

**Issue by yudefu** [wenet-e2e/wenet#1987]
你好作者：我这边利用export_jit.py这个脚本，把20220506_u2pp_conformer_exp里面的断点模型final.pt转换为torch.jit.script成功了，输出新的jit格式的模型，但是我在利用netron查看模型结构时打不开，想问一下是不是正常现象呢
执行：python3 ./wenet/bin/export_jit.py --config ./20220506_u2pp_conformer_exp/train.yaml --checkpoint ./20220506_u2pp_conformer_exp/final.pt

**Comment by pengzhendong** [comment]
> Netron has `experimental` support for PyTorch, `TorchScript`, TensorFlow, OpenVINO, RKNN, MediaPipe, ML.NET and scikit-learn.

**Comment by yudefu** [comment]
> > Netron has `experimental` support for PyTorch, `TorchScript`, TensorFlow, OpenVINO, RKNN, MediaPipe, ML.NET and scikit-learn.

非常感谢你的回复！netron支持的模型类型我之前了解过，不过利用咱们代码export_jit.py转换后的torchscript模型用netron打不开，无法确认模型的输入信息。我们这边自己的推理框架需要知道模型的具体输入信息维度这些
