### ISSUE TITLE
WENet支持张量并行吗？

### ISSUE THREAD

**Issue by coreeey** [wenet-e2e/wenet#1989]
在使用wenet时，默认使用了数据并行，但是修改模型后，模型一直出现显存不够的现象，请问wenet有在哪里提供了张量并行的接口吗？

**Comment by Mddct** [comment]
目前还不支持 ， wenet 支持deepspeed的stage系列， 你可以试下
参考：  https://mp.weixin.qq.com/s/mn47BK9IFYwq70ofbyv6FQ

**Comment by Mddct** [comment]
还有，你提到了“修改模型后”才oom， 请看下是否修改的有问题

**Comment by coreeey** [comment]
我这里级联了一个较大的模型，所以句子较长时出现OOM是正常的。
感谢回复，我再这里去尝试一下别的方法。
