### ISSUE TITLE
多机训练时两台机器卡数量不一致要怎样设置

### ISSUE THREAD

**Issue by kli017** [wenet-e2e/wenet#1994]
训练时node0有8张卡node1有4张卡，请问需要怎么设置节点信息？num_nodes设置为2主机export 8卡后就自动显示16个了。。

**Comment by yudefu** [comment]
这种情况下好像不行，最好两边gpu的数量保存一致，因为你多机多卡的几个必要参数是保持两边gpu数量一致的；当然你可以实验一下，以前我做过实验是不行的

**Comment by kli017** [comment]
感谢！试了下可以跑起来但是模型收敛不太正常。。
