### ISSUE TITLE
RNNT模型训练的时候不收敛，损失一直是50-60

### ISSUE THREAD

**Issue by DaobinZhu** [wenet-e2e/wenet#1996]
训练一直不收敛，在解码的时候发现所有语音只输出一个结果

**Comment by DaobinZhu** [comment]
![image](https://github.com/wenet-e2e/wenet/assets/37605608/25206725-fad7-4a4a-afa0-09fdc669a604)

**Comment by DaobinZhu** [comment]
![image](https://github.com/wenet-e2e/wenet/assets/37605608/9814f412-2971-4d5a-a7ae-8f2106948ea8)

**Comment by Mddct** [comment]
检查下数据处理流程，看着标注都一样？

**Comment by DaobinZhu** [comment]
数据处理检查了一下貌似没有问题，我重新删了项目再下载一下试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 上午10:52
收件人: ***@***.***&gt;;
抄送: "Daobin ***@***.******@***.***&gt;;
主题: Re: [wenet-e2e/wenet] RNNT模型训练的时候不收敛，损失一直是50-60 (Issue #1996)




 
检查下数据处理流程，看着标注都一样？

**Comment by DaobinZhu** [comment]
重新把项目删了再下载，还是报错

**Comment by Mddct** [comment]
稍等下 我跑一下看下 你是按那个配置跑的呢？

**Comment by DaobinZhu** [comment]
默认配置



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月7日(周四) 下午2:55
收件人: ***@***.***&gt;;
抄送: "Daobin ***@***.******@***.***&gt;;
主题: Re: [wenet-e2e/wenet] RNNT模型训练的时候不收敛，损失一直是50-60 (Issue #1996)




 
稍等下 我跑一下看下 你是按那个配置跑的呢？
