### ISSUE TITLE
Crash in iOS 

### ISSUE THREAD

**Issue by summerHearts** [wenet-e2e/wenet#1998]
**Describe the bug**
 Using the model, it crashes after running for a period of time without any other operations in between
**To Reproduce**
1. Go to 'iOS Demo'
2. setting model and lib 
3. run it 
4. crash

**Expected behavior**
  Using the model, it crashes after running for a period of time without any other operations in between

**Screenshots**
![20230906-165312](https://github.com/wenet-e2e/wenet/assets/10678821/625a1eec-4353-46a3-9837-8d6ba21fb719)

**Smartphone (please complete the following information):**
 - OS: iOS
 - Version: OS  15.6

**Comment by robin1001** [comment]
@Ma-Dan，any idea?

**Comment by Ma-Dan** [comment]
请问一下，发生这个问题的现场，accessor是什么shape？看起来像是访问越界。

**Comment by Lumoas** [comment]
> accesso
![image](https://github.com/wenet-e2e/wenet/assets/15683503/43bca438-8340-4684-a84a-4b3fde9fec95)
Model：use "Multi-CN" pretrained model
Scene that appears： it crashes after running for a period of time without any other operations in between

**Comment by summerHearts** [comment]
> 请问一下，发生这个问题的现场，accessor是什么shape？看起来像是访问越界。
Same as the comment below。 Model：use "Multi-CN" pretrained model

**Comment by Ma-Dan** [comment]
请问下你用的哪个版本的代码测试的？我用了主线最新代码测试，连续播放了半小时让它一直识别也没有出现。最新代码在执行计算之前已经用CHECK_EQ对输出的probs的两个维度的长度进行了检查，如果要出这个错，原则上CHECK_EQ这步就会出错。

**Comment by summerHearts** [comment]
使用的是主分支代码

**Comment by Ma-Dan** [comment]
![image](https://github.com/wenet-e2e/wenet/assets/38337958/9a813035-90a5-4110-977e-832cd41c24d8)
发生问题的现场，可以把prob，hyp和accessor详情展开看下么？
