### ISSUE TITLE
直接使用wenet推理出错

### ISSUE THREAD

**Issue by Taraus20** [wenet-e2e/wenet#2002]
运行该条命令
![image](https://github.com/wenet-e2e/wenet/assets/74604314/1c81902c-9aaf-400b-af9a-854f4842dfda)
出现DLL load failed while importing _wenet: 找不到指定的程序  错误

**Comment by robin1001** [comment]
@Mddct windows 是不是一直有问题？

**Comment by Mddct** [comment]
更新下最新版本 上次fix版本后 我这边试过没问题

**Comment by Mddct** [comment]
> 运行该条命令
> ![image](https://github.com/wenet-e2e/wenet/assets/74604314/1c81902c-9aaf-400b-af9a-854f4842dfda)
> 出现DLL load failed while importing _wenet: 找不到指定的程序  错误

用的是哪个版本
