### ISSUE TITLE
High RTF

### ISSUE THREAD

**Issue by heibaidaolx123** [wenet-e2e/wenet#2003]
Hi, 
I tested decoder_main built with onnx. 
The RTF for float32 is 0.1544 and for int8 it's 0.1632.
The RTFs are both higher than those claimed in the paper and got by others like in this [issue](https://github.com/wenet-e2e/wenet/issues/1669). And it's odd to me that the int8 version is slower.
Any idea?

For decoder_main, 
testset: 100 normal short waves 
model: 20220506_u2pp_conformer_exp
CPU: AMD EPYC 7742 64-Core Processor
env: docker ubuntu22.04
thread_num: 1
chunk_size: -1
warmup: 10
other args: default

The command to export onnx model, 
```
python -m wenet.bin.export_onnx_cpu \
  --config $pt_dir/train.yaml \
  --checkpoint $pt_dir/final.pt \
  --chunk_size -1 \
  --output_dir $onnx_dir \
  --num_decoding_left_chunks -1
```

**Comment by robin1001** [comment]
Compared to the paper, you tested on different machine, so there is difference of the RTF. I think it's a reasonable result.

Typically, int8 gets better RTF than float32 on ARM architecture.

**Comment by heibaidaolx123** [comment]
Thanks @robin1001
