### ISSUE TITLE
用v100单机多卡训练，都跑到同一张卡上了

### ISSUE THREAD

**Issue by dahu1** [wenet-e2e/wenet#2010]
<img width="1508" alt="image" src="https://github.com/wenet-e2e/wenet/assets/22560013/37aac485-d6f9-42cb-8800-0eab9c2f3c1b">
<img width="567" alt="image" src="https://github.com/wenet-e2e/wenet/assets/22560013/4e40280d-6025-429e-be4a-509b6e85ea55">

使用v100来多卡训练，发现分配gpu都分配到同一张卡了，这个要如何处理，之前使用2080和3090训练，都没遇到过这种情况。

机器信息：
镜像 nvidia/cuda:11.7.1-devel-ubuntu20.04
python3.8
torch==1.13.0+cu117
torchaudio==0.13.0

**Comment by robin1001** [comment]
@yuekaizhang 碰到过吗？

**Comment by dahu1** [comment]
![image](https://github.com/wenet-e2e/wenet/assets/22560013/4e2865e3-e62d-4905-aea6-e5b2b6a31205)
<img width="1260" alt="image" src="https://github.com/wenet-e2e/wenet/assets/22560013/b5e6f5c5-6e7c-4b55-894b-e51ea17a490f">


补充一下git commit  :  98048215e92bcb03b651e98b5c1891630ff17cdb

**Comment by MrSupW** [comment]
@dahu1 你好，请问这个问题有解决方式吗？我今天也遇到这个情况了。

**Comment by ziyu123** [comment]
在 `model.cuda()` 之前 添加 `torch.cuda.set_device(args.rank)`，我的已经解决了

**Comment by MrSupW** [comment]
@ziyu123 感谢！我这里也正常了

**Comment by dahu1** [comment]
> 在 `model.cuda()` 之前 添加 `torch.cuda.set_device(args.rank)`，我的已经解决了

感谢

**Comment by robin1001** [comment]
或者可以拉最新的代码，使用 torchrun 跑并行训练，见 https://github.com/wenet-e2e/wenet/pull/2020。
