### ISSUE TITLE
libtorch gpu decoder_main error: torch::jit::ErrorReport

### ISSUE THREAD

**Issue by maowandong** [wenet-e2e/wenet#2011]
After build decoder_main with GPU， run decoder_main with following error: 
decoder_main     --model_path $model_dir/20.final.zip     --unit_path $model_dir/units.txt     --ctc_weight 0.3     --reverse_weight 0.5     --rescoring_weight 1.0     --acoustic_scale 1.2     --length_penalty -3.0     --output_nbest True     --nbest 30     --beam 7.5 --lattice_beam 10.0 --max_active 7000     --chunk_size -1     --wav_path ./audio/test.wav

terminate called after throwing an instance of 'torch::jit::ErrorReport'
terminate called recursively
已放弃 (核心已转储)

ENV：
gcc: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
torch: 1.13
libtorch.so:  
![image](https://github.com/wenet-e2e/wenet/assets/5255096/03a5b529-1fd2-47fb-b034-157aae9865a7)

1) decoder_main build command:    mkdir build && cd build && cmake -DGPU=ON -DGRAPH_TOOLS=ON .. && cmake --build .
2) runtime model export command:  . ./path.sh && python wenet/bin/export_jit.py --config exp/u2cpp_0904/train.yaml --checkpoint exp/u2cpp_0904/21.pt --output_file exp/u2cpp_0904/21.final.zip

**If build with cpu, it works fine.**

![image](https://github.com/wenet-e2e/wenet/assets/5255096/f1d3a94f-a847-46f3-b110-8ded54096ede)

**Comment by maowandong** [comment]
pinpoint the cause：dismatch between torch(1.13) and libtorch GPU version (1.11) https://download.pytorch.org/libtorch/cu113/libtorch-shared-with-deps-1.11.0%2Bcu113.zip  from https://github.com/wenet-e2e/wenet/blob/main/runtime/core/cmake/libtorch.cmake 

After modify cmake file, it works fine:

 34            set(LIBTORCH_URL "https://download.pytorch.org/libtorch/cu116/libtorch-shared-with-deps-1.13.0%2Bcu116.zip")
 35           set(URL_HASH "SHA256=d0e254012b6eaa9966bf8a9e9a8dfac15d78abb21f373f63f5b01fefb1670f72")

**Comment by xingchensong** [comment]
PR is welcome ~~
