### ISSUE TITLE
cannot install wenetruntime on mac m1  python 3.18.18

### ISSUE THREAD

**Issue by dyustc** [wenet-e2e/wenet#2016]
**Describe the bug**
cannot install wenetruntime on mac m1  python 3.18.18,  it said no matching distribution, is this package currently available?

**To Reproduce**
pip install wenetruntime 
or
pip3 install wenetruntime

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [mac osx Ventura 13.3.1]

**Additional context**

**Comment by Mddct** [comment]
You may try to use python >=3.6

**Comment by dyustc** [comment]
> You may try to use python >=3.6

谢谢，可以在python == 3.6.13上安装成功，不过我试跑了一下，会报73988 illegal hardware instruction  wenetruntime的错误， 在reading torch model的时候， 我的机器是macbook M1 Pro
--------------------

不过没事，我目前主要在跑c++的 demo，python 我倒不是真那么需要，只是发现了这个 bug，可能没有把torch相关的库兼容。

**Comment by dyustc** [comment]
wenetruntime用的pip在python3.6下装的， 跑非流式的python demo报illegal hardware instruction， 跑流式的demo报segmentation fault， demo代码就是[readme](https://github.com/wenet-e2e/wenet/tree/main/runtime/binding/python)里面的

然后自己用python setup.py install的话，install 成功，但是跑起来会提示某个 symbol 在libtorch_cpu.so里面找不到...

**Comment by Mddct** [comment]
贴一下 这个symnol

**Comment by dyustc** [comment]
> 贴一下 这个symnol
pip 装的是wenetruntime的版本号 1.14.0， 我自己本地装的 wenet repo的版本号是v2.2.1， 对应出来的wenetruntime的版本号是 1.0.12

symbol名称 ： __ZN2at4_ops3cat4callERKN3c108IListRefINS_6TensorEEEx
![截屏2023-09-28 10 37 11](https://github.com/wenet-e2e/wenet/assets/14801111/0d0a946b-4ae4-4a7c-a0ec-3a3e96482aae)

**Comment by xingchensong** [comment]
请使用cli，wenetruntime已废弃
