### ISSUE TITLE
Contextual Biasing is used for post ranking.

### ISSUE THREAD

**Issue by lomizandtyd** [wenet-e2e/wenet#2019]
Hi Wenet team,

Contextual biasing is used for second pruning in Wenet. (First is CTC Topk score pruning).

Have you considered the combination of contextual biasing score and CTC score for first pruning?

The scenario of contextual biasing is to improve tokens with low CTC score. If we already pruned with CTC score, it's hard to get biased candidates we want.

**Comment by xingchensong** [comment]
PR is welcomed ~
