### ISSUE TITLE
examples with torchrun ?

### ISSUE THREAD

**Issue by kobenaxie** [wenet-e2e/wenet#2023]
https://github.com/wenet-e2e/wenet/blob/336e774fe88732b1a0cde942671a175b2b85c0a3/examples/aishell/rnnt/run.sh#L119-L120
#2021 `torchrun` needs not `python` command ?

**Comment by pengzhendong** [comment]
Both `torchrun` and `python -m torchrun` are fine.

**Comment by robin1001** [comment]
Good catch, fixed, please see https://github.com/wenet-e2e/wenet/pull/2024.
