### ISSUE TITLE
添加热词之后，会出现识别中断的情况

### ISSUE THREAD

**Issue by newday1255** [wenet-e2e/wenet#2027]
代码版本：v2.0.1
使用的runtime/binding/python
添加的热词有['一证通查'，‘飞享套餐’]
context_score=2

识别结果：
![image](https://github.com/wenet-e2e/wenet/assets/46987480/fd349c53-71be-4782-bb1d-a50991c3fb50)
其中飞享套餐热词正确且<content></content>标签完整，但是后面的  “<content>一”  热词错误多次且标签不完整，最后导致的是输入的wav音频信息没有识别完成就结束了识别，请问这种情况该如何解决？

**Comment by robin1001** [comment]
热词标签不完整是正常的，这个标签仅仅是辅助人进行查看的，可以认为去掉不成对的 <context> </context> 标签，即为识别结果。

**Comment by robin1001** [comment]
wav 音频没有识别结束应该另有它因。
