### ISSUE TITLE
Setup.py fatal error: 'processor/wetext_processor.h' file not found

### ISSUE THREAD

**Issue by Runtrons** [wenet-e2e/wenet#2032]
### **Hi, I haven't had any success running this so far. I have gotten this error every time I try to run anything using the wenetruntime python package:**

libc++abi: terminating due to uncaught exception of type c10::Error: Type c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > could not be converted to any of the known types.
Exception raised from operator() at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/jit_type.h:1756 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>) + 98 (0x11fa8c992 in libc10.dylib)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 106 (0x11fa8b0aa in libc10.dylib)
frame #2: c10::detail::getTypePtr_<c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>>>::call()::'lambda'()::operator()() const + 275 (0x15581e233 in libtorch_cpu.dylib)
frame #3: c10::Type::SingletonOrSharedTypePtr<c10::Type> c10::getFakeTypePtrCopy<c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>>>() + 25 (0x15581dfc9 in libtorch_cpu.dylib)
frame #4: c10::detail::infer_schema::(anonymous namespace)::createArgumentVector(c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) + 188 (0x15509197c in libtorch_cpu.dylib)
frame #5: c10::detail::infer_schema::make_function_schema(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) + 123 (0x15509174b in libtorch_cpu.dylib)
frame #6: c10::detail::infer_schema::make_function_schema(c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef>) + 76 (0x155091d6c in libtorch_cpu.dylib)
frame #7: std::__1::unique_ptr<c10::FunctionSchema, std::__1::default_delete<c10::FunctionSchema>> c10::detail::inferFunctionSchemaFromFunctor<at::Tensor (*)(at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>> const&, double, long long)>() + 180 (0x15587ade4 in libtorch_cpu.dylib)

**And the error goes on and on. I decided to run from source so I tried:

1. git clone https://github.com/wenet-e2e/wenet.git
2. cd wenet/runtime/binding/python
3. python setup.py install

And when I do so it fails after countless warnings with this fatal error:**

[ 69%] Built target kaldi-decoder **#Was working**
[ 74%] Built target frontend **#Was working**
[ 76%] Building CXX object post_processor/CMakeFiles/post_processor.dir/post_processor.cc.o#Was working
In file included from /Users/ronangrant/Safe/wenet2/wenet/runtime/binding/python/post_processor/post_processor.cc:16: **#Error**
/Users/ronangrant/Safe/wenet2/wenet/runtime/binding/python/post_processor/post_processor.h:22:10: fatal error: 'processor/wetext_processor.h' file not found
#include "processor/wetext_processor.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[3]: *** [post_processor/CMakeFiles/post_processor.dir/post_processor.cc.o] Error 1
make[2]: *** [post_processor/CMakeFiles/post_processor.dir/all] Error 2
make[1]: *** [CMakeFiles/_wenet.dir/rule] Error 2
make: *** [_wenet] Error 2

......

  File "setup.py", line 38, in build_extension
    raise Exception(
Exception: 
Build wenet failed. Please check the error message.
You can ask for help by creating an issue on GitHub.

**I am using MacOs on an intel Mac. I have tried on python 3.10. 3.9 and 3.8. The error above was python 3.8.

If you could help I would really appreciate it**

<img width="1326" alt="Screenshot 2023-09-28 at 3 06 49 PM" src="https://github.com/wenet-e2e/wenet/assets/67560747/fe88a6c3-eb1e-4733-b2c1-4e60edc3c7cb">

**Comment by Runtrons** [comment]
I do not see **`/runtime/libtorch/fc_base/wetextprocessing-src/runtime/processor`** directory in the repo. The only fc_base directory I found was in `wenet/runtime/binding/python/fc_base.` am I missing something? Thank you so much for your help.

**Comment by kuruvachankgeorge** [comment]
> @kuruvachankgeorge I do not see **`/runtime/libtorch/fc_base/wetextprocessing-src/runtime/processor`** directory in the repo. The only fc_base directory I found was in `wenet/runtime/binding/python/fc_base.` am I missing something? Thank you so much for your help.

I was expecting your `pwd` to be `wenet/runtime/binding/python`, if not please run `cd wenet/runtime/binding/python` . Then try `ln -s ../../../runtime/libtorch/fc_base/wetextprocessing-src/runtime/processor`.

**Comment by Runtrons** [comment]
@kuruvachankgeorge  Thanks so much for helping me it means a lot. There still isn't a directory `fc_base` that I see inside of libtorch as you can see here:
<img width="440" alt="image" src="https://github.com/wenet-e2e/wenet/assets/67560747/9d256ffb-0d85-4f60-84a1-7fb554251d12">

Could that be the problem? Am I doing something wrong? Thanks

**Comment by kuruvachankgeorge** [comment]
I guess you didn't build the runtime in libtorch. SO you can follow these steps:

1. git clone https://github.com/wenet-e2e/wenet.git
2. cd runtime/libtorch
3. mkdir build && cd build && cmake -DGRAPH_TOOLS=ON .. && cmake --build .
4. cd wenet/runtime/binding/python
5. ln -s ../../../runtime/libtorch/fc_base/wetextprocessing-src/runtime/processor
6. python setup.py install

Note: runtime build requires cmake 3.14 or above (conda install -c anaconda cmake)

**Comment by xingchensong** [comment]
thank u for pointing it out. this is partly caused by the intergration of itn(wetextprocessing) runtime in pr
 #2001, where we only change the cmakelist for runtime/libtorch, but forget to modify cmakelist for runtime/bingding/python accordingly. u can just do similar modifications in binding/python, once u succesed, whelcom to submit a PR.

**Comment by Runtrons** [comment]
@kuruvachankgeorge That worked! I experienced another error though with python setup.py install:

<img width="1637" alt="Screenshot 2023-09-28 at 10 13 18 PM" src="https://github.com/wenet-e2e/wenet/assets/67560747/163a17f8-f0d6-4be1-9552-b90842f8f062">

Undefined symbols for architecture x86_64:
  "wetext::Processor::Normalize(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      wenet::PostProcessor::Process(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, bool) in libpost_processor.a(post_processor.cc.o)
  "wetext::Processor::Processor(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)", referenced from:
      wenet::PostProcessor::InitITNResource(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) in libpost_processor.a(post_processor.cc.o)
**ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)**
make[3]: *** [api/libwenet_api.dylib] Error 1
make[2]: *** [api/CMakeFiles/wenet_api.dir/all] Error 2
make[1]: *** [CMakeFiles/_wenet.dir/rule] Error 2
make: *** [_wenet] Error 2
Traceback (most recent call last):
  File "setup.py", line 65, in <module>
........

  File "setup.py", line 38, in build_extension
    raise Exception(
Exception: 
Build wenet failed. Please check the error message.
You can ask for help by creating an issue on GitHub.


It appears `clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Would you mind helping me with this as well? I could not have done this without you thank you so much!

**Comment by kuruvachankgeorge** [comment]
> @kuruvachankgeorge That worked! I experienced another error though with python setup.py install:
> 
> <img alt="Screenshot 2023-09-28 at 10 13 18 PM" width="1637" src="https://user-images.githubusercontent.com/67560747/271470080-163a17f8-f0d6-4be1-9552-b90842f8f062.png">
> Undefined symbols for architecture x86_64: "wetext::Processor::Normalize(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator> const&)", referenced from: wenet::PostProcessor::Process(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator> const&, bool) in libpost_processor.a(post_processor.cc.o) "wetext::Processor::Processor(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator> const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator> const&)", referenced from: wenet::PostProcessor::InitITNResource(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator> const&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator> const&) in libpost_processor.a(post_processor.cc.o) **ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation)** make[3]: *** [api/libwenet_api.dylib] Error 1 make[2]: *** [api/CMakeFiles/wenet_api.dir/all] Error 2 make[1]: *** [CMakeFiles/_wenet.dir/rule] Error 2 make: *** [_wenet] Error 2 Traceback (most recent call last): File "setup.py", line 65, in ........
> 
> File "setup.py", line 38, in build_extension raise Exception( Exception: Build wenet failed. Please check the error message. You can ask for help by creating an issue on GitHub.
> 
> It appears `clang: error: linker command failed with exit code 1 (use -v to see invocation)`
> 
> Would you mind helping me with this as well? I could not have done this without you thank you so much!

Can you check the build instructions for iOS [https://github.com/wenet-e2e/wenet/tree/main/runtime/ios](url)

**Comment by 20070951** [comment]
> I guess you didn't build the runtime in libtorch. So you can follow these steps:
> 
> 1. git clone https://github.com/wenet-e2e/wenet.git
> 2. cd runtime/libtorch
> 3. mkdir build && cd build && cmake -DGRAPH_TOOLS=ON .. && cmake --build .
> 4. cd wenet/runtime/binding/python
> 5. ln -s ../../../runtime/libtorch/fc_base/wetextprocessing-src/runtime/processor
> 6. python setup.py install
> 
> Note: runtime build requires cmake 3.14 or above (conda install -c anaconda cmake)

Worked! Thank you for your advice.

**Comment by xingchensong** [comment]
@kuruvachankgeorge @20070951 ,could u try this fix ? https://github.com/wenet-e2e/wenet/pull/2042
