### ISSUE TITLE
bestrq复现

### ISSUE THREAD

**Issue by lizongyao123** [wenet-e2e/wenet#2037]
**Describe the bug**
我们使用wenet中实现的bestrq代码，试图复现预训练模型的结果，但是效果不好，完全达不到论文中的WER结果。

**To Reproduce**
1. 我们使用librispeech 960h数据进行预训练模型训练，使用10h和100h的数据进行微调。
2. 我们仿照wav2vec2的实验设置，预训练模型接CTC，而不是bestrq论文中的rnnt。

**Expected behavior**
bestrq这个模块，你们在librispeech数据上有没有做过尝试，如果有，你们的效果如何？如果没有，推荐的预训练模型的数据量是多少？

**Comment by Mddct** [comment]
bestrq训练特别依赖调参，当前还没有提供对应的超参。过一段时间我们会release超参和模型

**Comment by lizongyao123** [comment]
@Mddct 谢谢你的回复，我了解了。

**Comment by rookie0607** [comment]
> bestrq训练特别依赖调参，当前还没有提供对应的超参。过一段时间我们会release超参和模型

周哥，我们等的的花都谢了

**Comment by Liujingxiu23** [comment]
请问有 超参和模型 了吗？
