### ISSUE TITLE
基于onnxruntime-gpu的encoder推理耗时问题

### ISSUE THREAD

**Issue by lvchigo** [wenet-e2e/wenet#2038]
**Describe the bug**
- 基于wenet的onnxruntime-gpu模型转换与推理源码，打印每次推理耗时，发现encoder解码的耗时极不稳定，每条音频总长不超过10秒，具体问题如下：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/988c4c8e-716a-4c87-822e-7de127896cb1)    
- 而使用相同数据进行推理时，问题消失：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/a5295898-f2bd-4d57-866f-dcdc3bcd0815)

**To Reproduce**
1. 离线解码+attention_rescoring模式，模型转换：https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_onnx_gpu.py
2. 模型推理：https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/recognize_onnx_gpu.py
3. 模型推理中增加每次推理耗时统计代码，参考如下：  
![image](https://github.com/wenet-e2e/wenet/assets/8186051/52c2e859-017c-4f28-b6e2-49958cbbfeaa)  
4. 打印每次推理耗时，发现encoder解码的耗时极不稳定，每条音频总长不超过10秒，具体见上图；

**Desktop (please complete the following information):**
 - OS: centos7
 - onnxruntime-gpu：1.12.0/1.13.1/1.16.0
 - cuda：11.3/11.4
 - python：3.8

**尝试解决方案**
- 1、onnxruntime更新至最新版本（1.16.0）：问题未解决；
- 2、cuda驱动更新：查阅onnxruntime的git-issue，发现类似问题（https://github.com/microsoft/onnxruntime/issues/14016），但更新cuda驱动后，问题仍未解决；

**Comment by yuekaizhang** [comment]
可以试试把音频都pad到相同的长度，Onnxruntime-gpu 有些算子可能需要预热
