### ISSUE TITLE
Error when running python package 

### ISSUE THREAD

**Issue by Runtrons** [wenet-e2e/wenet#2040]
### Hi, I haven't had any success running this so far. I have gotten this error every time I try to run anything using the wenetruntime python package:

libc++abi: terminating due to uncaught exception of type c10::Error: Type c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2> > > could not be converted to any of the known types.
Exception raised from operator() at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/core/jit_type.h:1756 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator>) + 98 (0x11fa8c992 in libc10.dylib)
frame https://github.com/wenet-e2e/wenet/pull/1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__1::basic_string<char, std::__1::char_traits, std::_1::allocator> const&) + 106 (0x11fa8b0aa in libc10.dylib)
frame https://github.com/wenet-e2e/wenet/pull/2: c10::detail::getTypePtr<c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>>>::call()::'lambda'()::operator()() const + 275 (0x15581e233 in libtorch_cpu.dylib)
frame https://github.com/wenet-e2e/wenet/pull/3: c10::Type::SingletonOrSharedTypePtrc10::Type c10::getFakeTypePtrCopy<c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>>>() + 25 (0x15581dfc9 in libtorch_cpu.dylib)
frame https://github.com/wenet-e2e/wenet/pull/4: c10::detail::infer_schema::(anonymous namespace)::createArgumentVector(c10::ArrayRefc10::detail::infer_schema::ArgumentDef) + 188 (0x15509197c in libtorch_cpu.dylib)
frame https://github.com/wenet-e2e/wenet/pull/5: c10::detail::infer_schema::make_function_schema(std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator>&&, std::__1::basic_string<char, std::__1::char_traits, std::__1::allocator>&&, c10::ArrayRefc10::detail::infer_schema::ArgumentDef, c10::ArrayRefc10::detail::infer_schema::ArgumentDef) + 123 (0x15509174b in libtorch_cpu.dylib)
frame https://github.com/wenet-e2e/wenet/pull/6: c10::detail::infer_schema::make_function_schema(c10::ArrayRefc10::detail::infer_schema::ArgumentDef, c10::ArrayRefc10::detail::infer_schema::ArgumentDef) + 76 (0x155091d6c in libtorch_cpu.dylib)
frame https://github.com/wenet-e2e/wenet/pull/7: std::__1::unique_ptr<c10::FunctionSchema, std::__1::default_deletec10::FunctionSchema> c10::detail::inferFunctionSchemaFromFunctor<at::Tensor (*)(at::Tensor, c10::intrusive_ptr<ConvPackedParamsBase<2>, c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>> const&, double, long long)>() + 180 (0x15587ade4 in libtorch_cpu.dylib)

.....

****And the error goes on and on. It is pretty long, here is a screenshot:**
<img width="1132" alt="Screenshot 2023-10-09 at 5 47 53 PM" src="https://github.com/wenet-e2e/wenet/assets/67560747/31565aeb-b15d-4e2b-8b62-9b3df90cdb21">

I was EXPECTING it to stream audio from the demo code found in the python bindings streaming in the documentation. I have even tried transcribing a wav file. If I do anything with the package gives this error. I have tried several python versions and it doesn't seem to work. I really want to get this working, I have been trying for almost 2 weeks now. The package does not install when I use python 3.10 so I am using 3.8 for this setup. 

I tried installing it from source, but it always gives a fatal error and can never get it installed. I posted an issue about it but never got a response: https://github.com/wenet-e2e/wenet/issues/2033

**I am using MacOs on an intel Mac. I have tried on python 3.10. 3.9 and 3.8. The error above was python 3.8.

**Comment by xingchensong** [comment]
sorry for late response. we are on vacation last week~. could u try https://github.com/wenet-e2e/wenet/pull/2042

**Comment by xingchensong** [comment]
I can build from source successfully using that fix

![image](https://github.com/wenet-e2e/wenet/assets/13466943/20f57b01-62db-45d0-9a39-7f308580b1ad)
