### ISSUE TITLE
[rnnt] 重构rnnt

### ISSUE THREAD

**Issue by Mddct** [wenet-e2e/wenet#2064]
- [ ] 分离k2 loss
- [ ] model decode： https://github.com/wenet-e2e/wenet/blob/26f7deb2d62e71c12ab1f4f2ad8a9409b0620942/wenet/bin/recognize.py#L240
- [ ] rnnt batch greedy seaarch
- [ ] rnnt batch beam search
- [ ] rnnt modified beam search （限制一帧一token or blank）
- [ ] https://arxiv.org/abs/2305.11571 （也许是一个可以降低先存的方法 但是cif目前是for实现， 其实有parallel实现 https://github.com/George0828Zhang/torch_cif）
- [ ] rnnt trick 验证
- [ ] predictor 重构
- [ ] batch specaug mask on gpu

**Comment by robin1001** [comment]
Look forward to the new RNN-T system and SOTA result.
