### ISSUE TITLE
迷你项目：python cli(command line interface) and api(application programming interface)

### ISSUE THREAD

**Issue by robin1001** [wenet-e2e/wenet#2069]
## 目的

* 为开发者提供开箱即用更方便、更稳定的 python cli 和 api，功能、易用性能对标 whisper。 
* 基于 python 快速的开发和迭代。

其背景是现有的基于 c++ 的 python binding 扩展、开发、维护成本都比较高，大家普遍反馈环境问题也比较多。

## 功能

- [x] 基本 attention rescoring 支持 @robin1001 , 见 https://github.com/wenet-e2e/wenet/pull/2075
- [x] 时间戳支持 @robin1001 , 见 https://github.com/wenet-e2e/wenet/pull/2082
- [x] 置信度支持 @robin1001, 见 https://github.com/wenet-e2e/wenet/pull/2083
- [x] 对齐支持 @robin1001
- [x] GPU 支持，依赖 pytorch 进行原生支持，@yuekaizhang
- [x] paraformer 支持，目前 paraformer 是行业里效果最好的开源中文模型。@Mddct https://github.com/wenet-e2e/wenet/pull/2067
- [ ] 长音频支持？
- [x] 热词支持 @cdliang11 https://github.com/wenet-e2e/wenet/pull/2128
- [ ] VAD 支持 ?
- [ ] 说话人日志 speaker diarization 支持？@cdliang11 
- [x] #2089
- [ ] 其他 feature

欢迎大家提需求。

**Comment by xingchensong** [comment]
提一个：wenet.cpp, paraformer.cpp, ... etc (int4量化+多平台支持)

**Comment by Mddct** [comment]
现在paraformer 可以导出jit， 之后会支持onnx
不仅是cli ， runtime 也可以比较容易继
而且cif的对齐是比较准确的 后边是否考虑对齐用cif

**Comment by xingchensong** [comment]
> 现在paraformer 可以导出jit， 之后会支持onnx 不仅是cli ， runtime 也可以比较容易继 而且cif的对齐是比较准确的 后边是否考虑对齐用cif
> 
> 其次 whisper 也可以考虑拿过来， espnet已经有reproduce whisper的pr了 [espnet/espnet#5478](https://github.com/espnet/espnet/pull/5478) （@xingchensong 提供）

目前在完善deepspeed的易用性，下一步就是reproduce whisper了

**Comment by Mddct** [comment]
cli-paraformer    推理基本功能完成
TODO ：

- ［ ］TP-align
- ［ ］timestamp
- ［ ］自动化转conf等资源

**Comment by Mddct** [comment]
新需求： 端到端输出产生字幕
