### ISSUE TITLE
runtime 编译 websocket_server_main服务，存在内存占用问题

### ISSUE THREAD

**Issue by Yymax-max** [wenet-e2e/wenet#2071]
运行过程
1、采用ov runtime运行
运行参数：
./build/bin/websocket_server_main \
--core_number 8 \
--port 8382 \
--ctc_weight 0.7 \
--rescoring_weight 1.0  \
--reverse_weight 0.3 \
--chunk_size -1 \
--context_path context.txt \
--context_score 1.5 \
--nbest 10

2、调用(每台机器的数据是207条/248条/208条，音频平均时长5-15s)
方法一：采用3台不同机器串行调用该接口，每台机器20个并发调用
<img width="660" alt="image" src="https://github.com/wenet-e2e/wenet/assets/39081569/ee404295-f7bc-4779-aaef-e1832bc2da9c">

方法二：采用3台不同机器同时调用该接口，每台机器20个并发调用
<img width="789" alt="image" src="https://github.com/wenet-e2e/wenet/assets/39081569/ec8fd249-772e-4828-8286-d07df818a973">

问题：
1、看起来是并发数高，内存占用相应高，最后会稳定在一个值，但是起的并发数高，内存占用相应高，是不是存在内存泄露，这会是在websocke并发调用产生的还是解码器内部产生，如何有效定位？感谢
2、websocket_server.cc中，每次OnSpeechStart都会decoder_ = std::make_shared<AsrDecoder>(feature_pipeline_, decode_resource_,*decode_config_)，是否存在释放问题？

另外这个内存无论是ov还是libtorch都存在的

望大佬解答疑惑或者提供排查思路，感谢～～～～

**Comment by robin1001** [comment]
@chwma0，有经验吗？

**Comment by chwma0** [comment]
之前没遇到过，后面有空我跟进下





来自阿里邮箱Android客户端------------------------------------------------------------------
发件人：Binbin ***@***.***>
日　期：2023年10月27日 15:35:29
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [wenet-e2e/wenet] runtime 编译 websocket_server_main服务，存在内存占用问题 (Issue #2071)

@chwma0，有经验吗？
