### ISSUE TITLE
How to create alignments with Triton Inference

### ISSUE THREAD

**Issue by Macsim2** [wenet-e2e/wenet#2074]
First of all, thanks to Wenet guidelines, I did Triton Inferecne with u2pp model.
and I've got a alignments(timestamp) in wenet using u2pp model
I want to get decoding result including sentence and alignments at the same time using Triton server
How can I make it..?
Thank you.

**Comment by robin1001** [comment]
Timestamp is not avaliable in Triton server. @yuekaizhang any idea?

**Comment by Macsim2** [comment]
I'm trying to change output number of triton server last output.
So that I think that I need a changing onnx model which additionally output ctc_prob at encoder output.
This approach is right you think ..?

**Comment by yuekaizhang** [comment]
> I'm trying to change output number of triton server last output. So that I think that I need a changing onnx model which additionally output ctc_prob at encoder output. This approach is right you think ..?

Yeah, for CTC aligment, you need pass the CTC_Prob into the scoring/model.py, which should come from encoder.onnx.
