### ISSUE TITLE
Load model error in Android

### ISSUE THREAD

**Issue by TicooLiu** [wenet-e2e/wenet#2077]
## Environment
- Ubuntu 20.04 based on WSL2
- python 3.8
- dataset: aishell-1
- config: train_u2++_conformer.yaml

  **modify:  for more fast to get model**
  + `max_epoch: 360` to `max_epoch: 3`
- bash script: examples/aishell/s0/run.sh

  **modify: for more fast to get model**
  + `train_config=conf/train_u2++_conformer.yaml`
  + `dir=exp/u2pp_conformer`
  + `average_num=2`
  
## Status
After run `bash run.sh --stage 0 --stop-stage 5`,
get normal WER test report in `exp/u2pp_conformer/attention/`,
`exp/u2pp_conformer/attention_rescoring/`,
`exp/u2pp_conformer/ctc_greedy_search/`
and `exp/u2pp_conformer/ctc_prefix_beam_search/`.
Then to run `base run.sh --stage 6 --stop-stage 6` to export model,
get final.zip and final_quant.zip normally too.

when test runtime of Android with pretrained model of wenet,
APP can load pretrained model normaly,
but when remove APP from Android device, 
then replace pretrained model with trained model above `final.zip`,
reinstall APP get error as below:
```
terminating with uncaught exception of type c10::Error: isTuple()INTERNAL ASSERT FAILED at "../../../../src/main/cpp/libtorch_include/arm64-v8a/ATen/core/ivalue_inl.h":1400, please report a bug to PyTorch. Expected Tuple but got String
                                                                                                    Exception raised from toTuple at ../../../../src/main/cpp/libtorch_include/arm64-v8a/ATen/core/ivalue_inl.h:1400 (most recent call first):
                                                                                                    (no backtrace available)
```

It maybe is issue of export model?
Any advice?

**Comment by TicooLiu** [comment]
Thanks, have resolved this issue.

**Comment by khanld** [comment]
@TicooLiu can you share the solution, i have faced the same issue when running on Android. Thank you in advance!

**Comment by TicooLiu** [comment]
> @TicooLiu can you share the solution, i have faced the same issue when running on Android. Thank you in advance!

@khanld 
You should check your python environment which used to train your model firstly, like blow:
```
$pip list
...
torch                    1.13.1
...
```
You will get the torch version for trainning and exporting model.
Then you should check your Android project, where  include unified torch version in `build.gradle` as below:
```
dependencies {
    ...
    implementation 'org.pytorch:pytorch_android:1.13.1'
    extractForNativeBuild 'org.pytorch:pytorch_android:1.13.1'
    ...
}
```
**Note:** You may need copy and rename `data/dict/lang_char.txt` from trainning environment to your Android projiect's `assets` folder as `units.txt`, because generated dict file name is different with used in Android.
Good luck!

**Comment by khanld** [comment]
Thank you @TicooLiu, it works!
