### ISSUE TITLE
一个shuffle size 数据 跑完，下一个 shuffle size 的时候需要等待挺长时间的 

### ISSUE THREAD

**Issue by hackerxiaobai** [wenet-e2e/wenet#2095]
如标题，这个是合理的吗？
shuffle_size：3000
sort_size：500

**Comment by robin1001** [comment]
可以，有量化的等待时间吗？这个和训练时的 num_workers 也有关系。

**Comment by xingchensong** [comment]
这个怎么改，可以提个pr吗

**Comment by kobenaxie** [comment]
和这个issue类似？shuffle size变大，训练变慢 #https://github.com/wenet-e2e/wenet/issues/2052

**Comment by xingchensong** [comment]
@Mddct 周哥有啥想法

**Comment by Mddct** [comment]
> @Mddct 周哥有啥想法

初步想法是：
可以在 tar_file_and_group 最一开始io的地方 维护一个2*shuffle size的buffer， 然后用multiprocess pool 并发去读（下载），每次只yield 1 个shuffler size的wav

**Comment by xingchensong** [comment]
num_workers开大一点能不能解决这个问题呢？ @hackerxiaobai @kobenaxie @Mddct

**Comment by Mddct** [comment]
可以的 但是num worker依赖的共享内存一直有bug
