### ISSUE TITLE
请问libtorch的推理代码有过什么加速吗？

### ISSUE THREAD

**Issue by sunnymoon155** [wenet-e2e/wenet#2102]
几个月前测试rtf在gpu上0.04左右，最近从新拉了一下代码，在同样的环境下rtf在0.024左右，很奇怪，我看只加了一个itn没有别的变化呀

**Comment by robin1001** [comment]
可能是前后测试的机器负载影响，所以有波动。

**Comment by sunnymoon155** [comment]
> 可能是前后测试的机器负载影响，所以有波动。

我重新测试了一下，发现是测试集不同导致的，使用了相同测试集，新版和旧版代码差距为0.02799：0.02511，还是有10%左右的速度差异，而且是多次测试得出的结论
