### ISSUE TITLE
Failed to import k2 and icefall.         Notice that they are necessary for         hlg_onebest/hlg_rescore decoding and LF-MMI training

### ISSUE THREAD

**Issue by weru88097** [wenet-e2e/wenet#2105]
I keep getting an error about not being able to import k2 and icefall when running s0 in aishell dataset, but I already have k2 installed. please answer.

**Comment by robin1001** [comment]
Just ignore it if you do not use hlg_onebest/hlg_rescore decoding ro LF-MMI training
