### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by XinchenK** [wenet-e2e/wenet#2112]
**Describe the bug**
Error when running aishell project:
<img width="764" alt="772b83779b21fb824a079ccc44647c9" src="https://github.com/wenet-e2e/wenet/assets/93128436/c44bbee9-d176-4746-a134-749aeafa2f5f">

The version is wenet-2.0.0, the cuda version is 10.2, and the torch is 1.10.0.
The specific configuration is as follows:
<img width="468" alt="8352795f89b813de613b399d61feded" src="https://github.com/wenet-e2e/wenet/assets/93128436/a17b32e2-a7e2-4fd2-bfd6-787e0f48ab25">
Currently nvidia-smi cannot be used.
<img width="508" alt="18868b74bb2b228c5772c9df633fb0b" src="https://github.com/wenet-e2e/wenet/assets/93128436/bec754b6-fca3-4b1f-8667-bd63e887901e">
<img width="505" alt="b189f9016eb354329a922c97a1ce2e7" src="https://github.com/wenet-e2e/wenet/assets/93128436/75ec0195-5447-43bf-9d08-34e59c8130ff">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by robin1001** [comment]
用最新的代码试试呢？

**Comment by XinchenK** [comment]
试了个遍，可能是显卡不兼容，同样的版本换了机器就正常了
