### ISSUE TITLE
RNN-T在stage 5推理的时候没有报错，也没有解码

### ISSUE THREAD

**Issue by DaobinZhu** [wenet-e2e/wenet#2114]
在训练30epoch后，进行stage5进行解码的时候，没有任何输出结果，也没有报错，直接停掉了，改小bs也没有解决，请问如何解决？

日志如下:

/rnnt$ bash run.sh --stage 5 --stop-stage 5
do model average and final checkpoint is exp/conformer_rnnt/avg_3.pt
Namespace(dst_model='exp/conformer_rnnt/avg_3.pt', max_epoch=65536, min_epoch=0, num=3, src_path='exp/conformer_rnnt', val_best=True)
best val scores = [4.8622159 4.9295922 4.9345009]
selected epochs = [28 27 29]
['exp/conformer_rnnt/28.pt', 'exp/conformer_rnnt/27.pt', 'exp/conformer_rnnt/29.pt']
Processing exp/conformer_rnnt/28.pt
Processing exp/conformer_rnnt/27.pt
Processing exp/conformer_rnnt/29.pt
Saving to exp/conformer_rnnt/avg_3.pt
Warning: Failed to import k2 & icefall, which are for LF-MMI/hlg
/home/lsj/.conda/envs/wenet/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
Warning: Failed to import k2 which is requried for k2 rnnt train
Namespace(attn_weight=0.5, batch_size=16, beam_size=10, bpe_model=None, checkpoint='exp/conformer_rnnt/avg_3.pt', config='exp/conformer_rnnt/train.yaml', connect_symbol='', context_bias_mode='', context_graph_score=0.0, context_list_path='', ctc_weight=0.5, data_type='raw', decoder_scale=0.0, decoding_chunk_size=-1, dict='data/dict/lang_char.txt', gpu=0, hlg='', lm_scale=0.0, modes=['rnnt_beam_search'], non_lang_syms=None, num_decoding_left_chunks=-1, override_config=[], penalty=0.0, r_decoder_scale=0.0, result_dir='exp/conformer_rnnt', reverse_weight=0.0, search_ctc_weight=0.3, search_transducer_weight=0.7, simulate_streaming=False, test_data='data/test/data.list', transducer_weight=0.5, word='')
2023-11-06 10:56:23,113 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/avg_3.pt
{'accum_grad': 1, 'cmvn_file': 'exp/conformer_rnnt/global_cmvn', 'dataset_conf': {'batch_conf': {'batch_size': 6, 'batch_type': 'static'}, 'fbank_conf': {'dither': 0.1, 'frame_length': 25, 'frame_shift': 10, 'num_mel_bins': 80}, 'filter_conf': {'max_length': 40960, 'min_length': 10, 'token_max_length': 200, 'token_min_length': 1}, 'resample_conf': {'resample_rate': 16000}, 'shuffle': True, 'shuffle_conf': {'shuffle_size': 1500}, 'sort': True, 'sort_conf': {'sort_size': 500}, 'spec_aug': True, 'spec_aug_conf': {'max_f': 10, 'max_t': 50, 'num_f_mask': 2, 'num_t_mask': 2}, 'speed_perturb': True}, 'decoder': 'bitransformer', 'decoder_conf': {'attention_heads': 4, 'dropout_rate': 0.1, 'linear_units': 2048, 'num_blocks': 3, 'positional_dropout_rate': 0.1, 'r_num_blocks': 3, 'self_attention_dropout_rate': 0.1, 'src_attention_dropout_rate': 0.1}, 'dtype': 'fp32', 'encoder': 'conformer', 'encoder_conf': {'activation_type': 'swish', 'attention_dropout_rate': 0.1, 'attention_heads': 4, 'causal': True, 'cnn_module_kernel': 8, 'cnn_module_norm': 'layer_norm', 'dropout_rate': 0.1, 'input_layer': 'conv2d', 'linear_units': 2048, 'normalize_before': True, 'num_blocks': 12, 'output_size': 256, 'pos_enc_layer_type': 'rel_pos', 'positional_dropout_rate': 0.1, 'selfattention_layer_type': 'rel_selfattn', 'use_cnn_module': True, 'use_dynamic_chunk': True, 'use_dynamic_left_chunk': False}, 'grad_clip': 4, 'input_dim': 80, 'is_json_cmvn': True, 'joint_conf': {'activation': 'tanh', 'join_dim': 512, 'joint_mode': 'add', 'postjoin_linear': False, 'prejoin_linear': True, 'enc_output_size': 256, 'pred_output_size': 256}, 'lfmmi_dir': '', 'log_interval': 100, 'max_epoch': 130, 'model_conf': {'attention_weight': 0.15, 'ctc_weight': 0.1, 'length_normalized_loss': False, 'lsm_weight': 0.1, 'reverse_weight': 0.3, 'transducer_weight': 0.75}, 'model_dir': 'exp/conformer_rnnt', 'optim': 'adam', 'optim_conf': {'lr': 0.001}, 'output_dim': 4233, 'predictor': 'rnn', 'predictor_conf': {'bias': True, 'dropout': 0.1, 'embed_dropout': 0.1, 'embed_size': 256, 'hidden_size': 256, 'num_layers': 2, 'output_size': 256, 'rnn_type': 'lstm'}, 'save_states': 'model_only', 'scheduler': 'warmuplr', 'scheduler_conf': {'warmup_steps': 25000}, 'train_engine': 'torch_ddp', 'use_amp': False, 'init_infos': {}}
2023-11-06 10:56:23,315 INFO Checkpoint: loading from checkpoint exp/conformer_rnnt/avg_3.pt

**Comment by Mddct** [comment]
新代码在重构， 目前rnnt还没有完成

**Comment by DaobinZhu** [comment]
好的，谢谢周佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月6日(周一) 中午11:10
收件人: ***@***.***&gt;;
抄送: "Daobin ***@***.******@***.***&gt;;
主题: Re: [wenet-e2e/wenet] RNN-T在stage 5推理的时候没有报错，也没有解码 (Issue #2114)




 
新代码在重构， 目前rnnt还没有完成
