### ISSUE TITLE
make_shard_list.py 的重采样的逻辑错误

### ISSUE THREAD

**Issue by gengxuelong** [wenet-e2e/wenet#2125]
audio, sample_rate = sox.load(wav, normalize=False)   ------------------> 得到audio是int16
                if sample_rate != resample:
                    audio = torchaudio.transforms.Resample(
                        sample_rate, resample)(audio)   --------------------------> 要求输入是float, 类型不正确会报错
                read_time += (time.time() - ts)

建议改为:
audio, sample_rate = sox.load(wav, normalize=False)
                if sample_rate != resample:
                    audio = torchaudio.transforms.Resample(
                        sample_rate, resample)(audio.float())
                    audio = audio.to(torch.int16)

**Comment by cdliang11** [comment]
欢迎提个pr

**Comment by gengxuelong** [comment]
好的， 我会尽快提出修复pr

**Comment by cdliang11** [comment]
https://github.com/wenet-e2e/wenet/pull/2134
