### ISSUE TITLE
Build for deployment：CMake Error

### ISSUE THREAD

**Issue by sister-tong** [wenet-e2e/wenet#2151]
CMake Error at gflags-subbuild/gflags-populate-prefix/src/gflags-populate-stamp/download-gflags-populate.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/gflags/gflags/archive/v2.2.2.zip' failed
          status_code: 92
          status_string: "Stream error in the HTTP/2 framing layer"
          log:
          --- LOG BEGIN ---
            Trying 20.205.243.166:443...

  Connected to github.com (20.205.243.166) port 443 (#0)

  ALPN: offers h2

  ALPN: offers http/1.1

  [CONN-0-0][CF-SSL] TLSv1.0 (OUT), TLS header, Certificate Status (22):

  [5 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Certificate Status (22):

  [5 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Server hello (2):

  [122 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Finished (20):

  [5 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):

  [19 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Certificate (11):

  [2459 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, CERT verify (15):

  [79 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.2 (IN), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.3 (IN), TLS handshake, Finished (20):

  [36 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Finished (20):

  [5 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS change cipher, Change cipher spec
  (1):

  [1 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.3 (OUT), TLS handshake, Finished (20):

  [36 bytes data]

  SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256

  ALPN: server accepted h2

  Server certificate:

   subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=github.com
   start date: Feb 14 00:00:00 2023 GMT
   expire date: Mar 14 23:59:59 2024 GMT
   subjectAltName: host "github.com" matched cert's "github.com"
   issuer: C=US; O=DigiCert Inc; CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
   SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.

  Using HTTP2, server supports multiplexing

  Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
  len=0

  [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  h2h3 [:method: GET]

  h2h3 [:path: /gflags/gflags/archive/v2.2.2.zip]

  h2h3 [:scheme: https]

  h2h3 [:authority: github.com]

  h2h3 [user-agent: curl/7.87.0]

  h2h3 [accept: */*]

  Using Stream ID: 1 (easy handle 0x2d6a580)

  [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  GET /gflags/gflags/archive/v2.2.2.zip HTTP/2

  Host: github.com

  user-agent: curl/7.87.0

  accept: */*

  

  HTTP/2 stream 1 was not closed cleanly before end of the underlying stream

  [CONN-0-0][CF-SSL] TLSv1.2 (OUT), TLS header, Supplemental data (23):

  [5 bytes data]

  [1 bytes data]

  Connection #0 to host github.com left intact

          --- LOG END ---
          
    

make[2]: *** [CMakeFiles/gflags-populate.dir/build.make:100: gflags-populate-prefix/src/gflags-populate-stamp/gflags-populate-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/gflags-populate.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
CMake Error at /root/miniconda3/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/FetchContent.cmake:1622 (message):
  Build step for gflags failed: 2
Call Stack (most recent call first):
  /root/miniconda3/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/FetchContent.cmake:1762:EVAL:2 (__FetchContent_directPopulate)
  /root/miniconda3/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/FetchContent.cmake:1762 (cmake_language)
  /root/miniconda3/lib/python3.8/site-packages/cmake/data/share/cmake-3.26/Modules/FetchContent.cmake:1976 (FetchContent_Populate)
  cmake/gflags.cmake:5 (FetchContent_MakeAvailable)
  cmake/openfst.cmake:2 (include)
  CMakeLists.txt:45 (include)

-- Configuring incomplete, errors occurred!
在runtime/libtorch运行mkdir build && cd build && cmake -DGRAPH_TOOLS=ON .. && cmake --build .报错

**Comment by Mddct** [comment]
网络问题
