### ISSUE TITLE
decode speed depends on chunk size

### ISSUE THREAD

**Issue by Sang-Hoon-Pakr** [wenet-e2e/wenet#2163]
Dear wenet members. 

I used the script written below
the difference is only --chunk_size (16, -1)
-----
./build/bin/decoder_main \
    --chunk_size 16 \ <-> -1
    --thread_num 5 \
    --wav_scp $wav_path \
    --model_path $model_dir/final.zip \
    --unit_path $model_dir/units.txt 2>&1 | tee log.txt
-----

i saw some wire results when i use chunk size 16 

the results written below 
------------
I1124 08:28:39.623006  1356 decoder_main.cc:105] Decoded 3275ms audio taken 28637ms.
I1124 08:28:39.728370  1360 decoder_main.cc:105] Decoded 5210ms audio taken 28731ms.
I1124 08:28:39.781566  1359 decoder_main.cc:105] Decoded 5810ms audio taken 28763ms.
I1124 08:28:41.332217  1358 decoder_main.cc:105] Decoded 5215ms audio taken 30348ms.
I1124 08:28:41.367691  1356 decoder_main.cc:105] Decoded 6730ms audio taken 1725ms.
I1124 08:28:49.478484  1358 decoder_main.cc:105] Decoded 6625ms audio taken 8130ms.
I1124 08:28:49.526084  1359 decoder_main.cc:105] Decoded 9635ms audio taken 9719ms.
I1124 08:28:49.529465  1356 decoder_main.cc:105] Decoded 10575ms audio taken 8132ms.
I1124 08:28:49.727684  1357 decoder_main.cc:105] Decoded 13895ms audio taken 38702ms.
I1124 08:28:49.780489  1360 decoder_main.cc:105] Decoded 15720ms audio taken 10012ms.
I1124 08:28:50.161931  1360 decoder_main.cc:105] Decoded 2710ms audio taken 372ms.
I1124 08:28:50.318866  1358 decoder_main.cc:105] Decoded 6610ms audio taken 821ms.
I1124 08:28:50.445773  1357 decoder_main.cc:105] Decoded 5815ms audio taken 700ms.
I1124 08:28:50.729379  1360 decoder_main.cc:105] Decoded 4405ms audio taken 554ms.
I1124 08:28:50.811239  1357 decoder_main.cc:105] Decoded 2715ms audio taken 358ms.
I1124 08:28:50.968897  1359 decoder_main.cc:105] Decoded 10555ms audio taken 1415ms.
I1124 08:28:51.098784  1356 decoder_main.cc:105] Decoded 11175ms audio taken 1536ms.
I1124 08:28:51.158071  1357 decoder_main.cc:105] Decoded 2680ms audio taken 339ms.
I1124 08:28:51.264426  1360 decoder_main.cc:105] Decoded 4090ms audio taken 522ms.
I1124 08:28:51.608510  1357 decoder_main.cc:105] Decoded 3445ms audio taken 441ms.
I1124 08:28:51.883816  1360 decoder_main.cc:105] Decoded 4670ms audio taken 608ms.
I1124 08:28:52.240777  1358 decoder_main.cc:105] Decoded 13275ms audio taken 1888ms.
I1124 08:28:52.455902  1359 decoder_main.cc:105] Decoded 10435ms audio taken 1458ms.
I1124 08:28:52.956656  1360 decoder_main.cc:105] Decoded 7915ms audio taken 1051ms.
I1124 08:28:53.217851  1357 decoder_main.cc:105] Decoded 11640ms audio taken 1580ms.
I1124 08:28:53.306288  1358 decoder_main.cc:105] Decoded 7830ms audio taken 1044ms.
I1124 08:28:53.392740  1360 decoder_main.cc:105] Decoded 3330ms audio taken 427ms.
I1124 08:28:53.689960  1356 decoder_main.cc:105] Decoded 16790ms audio taken 2544ms.
I1124 08:28:54.134187  1359 decoder_main.cc:105] Decoded 11655ms audio taken 1647ms.
I1124 08:28:54.182366  1358 decoder_main.cc:105] Decoded 6550ms audio taken 859ms.
I1124 08:28:54.231544  1356 decoder_main.cc:105] Decoded 4275ms audio taken 529ms.
I1124 08:28:54.538321  1356 decoder_main.cc:105] Decoded 2225ms audio taken 300ms.
I1124 08:28:54.580708  1358 decoder_main.cc:105] Decoded 3250ms audio taken 389ms.
I1124 08:28:54.604974  1360 decoder_main.cc:105] Decoded 8870ms audio taken 1189ms.
I1124 08:28:55.002360  1359 decoder_main.cc:105] Decoded 6615ms audio taken 848ms.
I1124 08:28:55.029304  1357 decoder_main.cc:105] Decoded 12445ms audio taken 1779ms.
I1124 08:28:55.045656  1358 decoder_main.cc:105] Decoded 3540ms audio taken 455ms.
I1124 08:28:55.091445  1356 decoder_main.cc:105] Decoded 4010ms audio taken 541ms.
------------

when i start decoding, i need long time for decode
but it is getting faster and faster.. 

On the other hand, chunk size -1 
the decoding speed is constant 

-----------------
I1124 08:27:42.871932  1286 decoder_main.cc:105] Decoded 3275ms audio taken 941ms.
I1124 08:27:42.900110  1287 decoder_main.cc:105] Decoded 5215ms audio taken 967ms.
I1124 08:27:42.911448  1285 decoder_main.cc:105] Decoded 5810ms audio taken 971ms.
I1124 08:27:42.916059  1289 decoder_main.cc:105] Decoded 5210ms audio taken 952ms.
I1124 08:27:43.868875  1288 decoder_main.cc:105] Decoded 13895ms audio taken 1883ms.
I1124 08:27:45.274590  1286 decoder_main.cc:105] Decoded 6730ms audio taken 2389ms.
I1124 08:27:46.902217  1286 decoder_main.cc:105] Decoded 6610ms audio taken 1615ms.
I1124 08:27:46.943917  1289 decoder_main.cc:105] Decoded 6625ms audio taken 4015ms.
I1124 08:27:47.029280  1285 decoder_main.cc:105] Decoded 9635ms audio taken 4099ms.
I1124 08:27:47.037636  1288 decoder_main.cc:105] Decoded 10575ms audio taken 3149ms.
I1124 08:27:47.253921  1287 decoder_main.cc:105] Decoded 15720ms audio taken 4325ms.
I1124 08:27:47.294570  1288 decoder_main.cc:105] Decoded 2710ms audio taken 251ms.
I1124 08:27:47.544210  1285 decoder_main.cc:105] Decoded 5815ms audio taken 503ms.
I1124 08:27:47.642027  1287 decoder_main.cc:105] Decoded 4405ms audio taken 379ms.
I1124 08:27:47.783713  1285 decoder_main.cc:105] Decoded 2715ms audio taken 234ms.
I1124 08:27:47.815616  1286 decoder_main.cc:105] Decoded 10555ms audio taken 893ms.
I1124 08:27:48.001384  1287 decoder_main.cc:105] Decoded 4090ms audio taken 351ms.
I1124 08:27:48.018872  1289 decoder_main.cc:105] Decoded 11175ms audio taken 1054ms.
I1124 08:27:48.026834  1285 decoder_main.cc:105] Decoded 2680ms audio taken 237ms.
I1124 08:27:48.317885  1289 decoder_main.cc:105] Decoded 3445ms audio taken 292ms.
I1124 08:27:48.432368  1285 decoder_main.cc:105] Decoded 4670ms audio taken 396ms.
I1124 08:27:48.594731  1288 decoder_main.cc:105] Decoded 13275ms audio taken 1275ms.
I1124 08:27:48.821668  1286 decoder_main.cc:105] Decoded 10435ms audio taken 986ms.
I1124 08:27:49.142170  1285 decoder_main.cc:105] Decoded 7915ms audio taken 695ms.
I1124 08:27:49.278682  1288 decoder_main.cc:105] Decoded 7830ms audio taken 669ms.
I1124 08:27:49.421458  1289 decoder_main.cc:105] Decoded 11640ms audio taken 1081ms.
I1124 08:27:49.432744  1285 decoder_main.cc:105] Decoded 3330ms audio taken 284ms.
I1124 08:27:49.793706  1287 decoder_main.cc:105] Decoded 16790ms audio taken 1761ms.
I1124 08:27:49.886099  1286 decoder_main.cc:105] Decoded 11655ms audio taken 1042ms.
I1124 08:27:50.011909  1289 decoder_main.cc:105] Decoded 6550ms audio taken 577ms.
I1124 08:27:50.153266  1287 decoder_main.cc:105] Decoded 4275ms audio taken 351ms.
I1124 08:27:50.247462  1285 decoder_main.cc:105] Decoded 8870ms audio taken 798ms.
I1124 08:27:50.295675  1289 decoder_main.cc:105] Decoded 3250ms audio taken 277ms.
I1124 08:27:50.363186  1287 decoder_main.cc:105] Decoded 2225ms audio taken 205ms.
I1124 08:27:50.438823  1286 decoder_main.cc:105] Decoded 6615ms audio taken 540ms.
I1124 08:27:50.509759  1288 decoder_main.cc:105] Decoded 12445ms audio taken 1207ms.
I1124 08:27:50.625085  1285 decoder_main.cc:105] Decoded 4010ms audio taken 369ms.
I1124 08:27:50.629228  1289 decoder_main.cc:105] Decoded 3540ms audio taken 326ms.
-----------------

How can i fix this situation ..?

**Comment by xingchensong** [comment]
It's a common issue about warmup, please see:
- https://github.com/wenet-e2e/wenet/issues/1425
- https://github.com/wenet-e2e/wenet/issues/1669
- https://github.com/wenet-e2e/wenet/issues/1661
