### ISSUE TITLE
[cli]  No module named 'whisper'

### ISSUE THREAD

**Issue by Mddct** [wenet-e2e/wenet#2166]
we need fix in cli 
<img width="832" alt="Screenshot 2023-11-26 at 00 49 25" src="https://github.com/wenet-e2e/wenet/assets/4906435/4fb15ff7-d5ef-4906-a701-923bb802cbae">

**Comment by Mddct** [comment]
TODO:
- [ ] cli test unit

**Comment by robin1001** [comment]
@xingchensong please follow the issue.

**Comment by xingchensong** [comment]
get
