### ISSUE TITLE
[bug/whisper] known bug  of emb length when enable speed_perturb

### ISSUE THREAD

**Issue by xingchensong** [wenet-e2e/wenet#2171]
whisper的encoder和decoder均采用固定长度emb（encoder 30s， decoder 448字符），因此当开启speed_perturb，变速1.1时 30s的audio可能会造成assertion error

- https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/embedding.py#L96-L103

**Comment by Mddct** [comment]
这里可能有一个，还没仔细看。（bf16下text embedding可能会碰撞）
https://www.51cto.com/article/764120.html

**Comment by Mddct** [comment]
还有个 时间戳， speed 之后 时间戳的数据的label可能也有变化
