### ISSUE TITLE
examples/aishell/s0 run.sh  bug in stage 5

### ISSUE THREAD

**Issue by tianqiong123** [wenet-e2e/wenet#2181]
**Describe the bug**
When I run 'bash run.sh --stage 5 --stop_stage 5', it comes a bug and the run.sh doesn't run any more. 

**To Reproduce**
1. Edit '$CUDA_VISIBLE_DEVICES' to '0', '$num_workers' to 1, '$average_num' to 1.
2. Run 'bash run.sh --stage -1 --stop_stage 4'.
3. When train.py finishes epoch 3 training, press 'Ctrl+C' to stop.  
4. Run 'bash run.sh --stage 5 --stop_stage 5'.
5. See the bug.

**Additional context**
The output message:
'''
$ bash run.sh --stage 5 --stop_stage 5
do model average and final checkpoint is exp/conformer/avg_1.pt
Namespace(dst_model='exp/conformer/avg_1.pt', max_epoch=65536, min_epoch=0, num=1, src_path='exp/conformer', val_best=True)
best val scores = [13.99669639]
selected epochs = [3]
['exp/conformer/3.pt']
Processing exp/conformer/3.pt
Saving to exp/conformer/avg_1.pt
/home/tian/miniconda3/envs/myenv/lib/python3.8/site-packages/torch/_jit_internal.py:726: FutureWarning: ignore(True) has been deprecated. TorchScript will now drop the function call on compilation. Use torch.jit.unused now. {}
  warnings.warn(
Namespace(attn_weight=0.0, batch_size=32, beam_size=10, bpe_model=None, checkpoint='exp/conformer/avg_1.pt', config='exp/conformer/train.yaml', connect_symbol='', context_bias_mode='', context_graph_score=0.0, context_list_path='', ctc_weight=0.3, data_type='raw', decoder_scale=0.0, decoding_chunk_size=-1, dict='data/dict/lang_char.txt', gpu=0, hlg='', lm_scale=0.0, modes=['ctc_greedy_search', 'ctc_prefix_beam_search', 'attention', 'attention_rescoring'], non_lang_syms=None, num_decoding_left_chunks=-1, override_config=[], penalty=0.0, r_decoder_scale=0.0, result_dir='exp/conformer', reverse_weight=0.5, search_ctc_weight=1.0, search_transducer_weight=0.0, simulate_streaming=False, test_data='data/test/data.list', transducer_weight=0.0, word='')
2023-11-30 15:02:43,902 INFO Checkpoint: loading from checkpoint exp/conformer/avg_1.pt
{'accum_grad': 4, 'cmvn_file': 'exp/conformer/global_cmvn', 'ctc_conf': {'ctc_blank_id': 0}, 'dataset_conf': {'batch_conf': {'batch_size': 16, 'batch_type': 'static'}, 'fbank_conf': {'dither': 0.1, 'frame_length': 25, 'frame_shift': 10, 'num_mel_bins': 80}, 'filter_conf': {'max_length': 40960, 'min_length': 0, 'token_max_length': 200, 'token_min_length': 1}, 'resample_conf': {'resample_rate': 16000}, 'shuffle': True, 'shuffle_conf': {'shuffle_size': 1500}, 'sort': True, 'sort_conf': {'sort_size': 500}, 'spec_aug': True, 'spec_aug_conf': {'max_f': 10, 'max_t': 50, 'num_f_mask': 2, 'num_t_mask': 2}, 'speed_perturb': True}, 'decoder': 'transformer', 'decoder_conf': {'attention_heads': 4, 'dropout_rate': 0.1, 'linear_units': 2048, 'num_blocks': 6, 'positional_dropout_rate': 0.1, 'self_attention_dropout_rate': 0.0, 'src_attention_dropout_rate': 0.0}, 'dtype': 'fp32', 'encoder': 'conformer', 'encoder_conf': {'activation_type': 'swish', 'attention_dropout_rate': 0.0, 'attention_heads': 4, 'cnn_module_kernel': 15, 'dropout_rate': 0.1, 'input_layer': 'conv2d', 'linear_units': 2048, 'normalize_before': True, 'num_blocks': 12, 'output_size': 256, 'pos_enc_layer_type': 'rel_pos', 'positional_dropout_rate': 0.1, 'selfattention_layer_type': 'rel_selfattn', 'use_cnn_module': True}, 'grad_clip': 5, 'input_dim': 80, 'is_json_cmvn': True, 'lfmmi_dir': '', 'log_interval': 100, 'max_epoch': 240, 'model_conf': {'ctc_weight': 0.3, 'length_normalized_loss': False, 'lsm_weight': 0.1}, 'model_dir': 'exp/conformer', 'optim': 'adam', 'optim_conf': {'lr': 0.002}, 'output_dim': 4233, 'save_states': 'model_only', 'scheduler': 'warmuplr', 'scheduler_conf': {'warmup_steps': 25000}, 'train_engine': 'torch_ddp', 'use_amp': False, 'vocab_size': 4233, 'init_infos': {}}
Traceback (most recent call last):
  File "wenet/bin/recognize.py", line 271, in <module>
    main()
  File "wenet/bin/recognize.py", line 248, in main
    results = model.decode(
  File "/home/tian/master_graduation_project/wenet/wenet/transformer/asr_model.py", line 248, in decode
    results['attention_rescoring'] = attention_rescoring(
  File "/home/tian/master_graduation_project/wenet/wenet/transformer/search.py", line 382, in attention_rescoring
    s = r_decoder_out[i][len(hyp) - j - 1][w]
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number
'''

**Desktop (please complete the following information):**
 - OS: Ubuntu in WSL2
 - Browser : Vscode
 - Version: 22.04 LTS

**Comment by xingchensong** [comment]
在`wenet/transformer/search.py` 文件下 372行加一个hyp = hyp[0] 代码, 试一试，成功解码且数值无误可以提个PR修复下

**Comment by xingchensong** [comment]
s = r_decoder_out[i][len(hyp) - j - 1][w].item() 呢

**Comment by David-tianqiong** [comment]
还是报错：
Traceback (most recent call last):
  File "wenet/bin/recognize.py", line 271, in <module>
    main()
  File "wenet/bin/recognize.py", line 248, in main
    results = model.decode(
  File "/home/tian/master_graduation_project/wenet/wenet/transformer/asr_model.py", line 248, in decode
    results['attention_rescoring'] = attention_rescoring(
  File "/home/tian/master_graduation_project/wenet/wenet/transformer/search.py", line 382, in attention_rescoring
    s = r_decoder_out[i][len(hyp) - j - 1][w].item()
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python or `tensor.item<T>()` in C++ to convert a 0-dim tensor to a number

**Comment by xingchensong** [comment]
我用的是u2pp_conformer, 你这个看起来是conformer，我再试一下这个
