### ISSUE TITLE
RelPositionMultiHeadedAttention 可以支持Flash attention吗？

### ISSUE THREAD

**Issue by shushanxingzhe** [wenet-e2e/wenet#2187]
RelPositionMultiHeadedAttention 可以支持Flash attention吗？
https://github.com/wenet-e2e/wenet/blob/main/wenet/transformer/attention.py#L190

**Comment by xingchensong** [comment]
需要改flash attention的代码来适配

**Comment by Mddct** [comment]
RelPositionMultiHeadedAttention pos主要作用到了q k上， flash att支持也相对简单
可以参考：https://github.com/QwenLM/Qwen-Audio/blob/main/modeling_qwen.py#L180

**Comment by shushanxingzhe** [comment]
> RelPositionMultiHeadedAttention pos主要作用到了q k上， flash att支持也相对简单 可以参考：https://github.com/QwenLM/Qwen-Audio/blob/main/modeling_qwen.py#L180

我看了一下Qwen-Audio的代码，但是还是不知道要怎么改，请问有计划近期改一下RelPositionMultiHeadedAttention以支持 flash att吗？在某个分支上支持了也行

**Comment by Mddct** [comment]
https://github.com/wenet-e2e/wenet/pull/2360

均已支持
