### ISSUE TITLE
关于contrastive_loss的疑问

### ISSUE THREAD

**Issue by Janeliao-C** [wenet-e2e/wenet#2190]
wenet/ssl/wav2vec2/wav2vec2_model.py文件中的_compute_contrastive_loss函数计算的是对比loss的分母，也就是拿预测feature和政府样本同时计算相似度，不需要用feature和正样本计算相似度作为分子再得到最后的对比loss吗？

**Comment by Mddct** [comment]
分母分子都有了 第一个就是分子 其他分母，
