### ISSUE TITLE
[tokenizer] 希望将tokenizer_type等写入yaml，从而可以在yaml中配置相关字段

### ISSUE THREAD

**Issue by xingchensong** [wenet-e2e/wenet#2204]
现在的tokenizer初始化方式是通过判断bpe_model是否为空来执行的，未来引入更多类型的tokenizer时已显得不适用

**Comment by Mddct** [comment]
https://github.com/wenet-e2e/wenet/pull/2205#issue-2032081131 这个pr已经写入了conf

<img width="623" alt="Screenshot 2023-12-13 at 14 24 12" src="https://github.com/wenet-e2e/wenet/assets/4906435/763b6169-b0ce-4603-90cd-2a0baebd0308">

**Comment by Mddct** [comment]
TODO： @Mddct M
-  校验special_tokens 是否和词表里边一致
