### ISSUE TITLE
No module named 'wenet.text'

### ISSUE THREAD

**Issue by unrea1-sama** [wenet-e2e/wenet#2239]
**Describe the bug**

Install wenet using:
```
pip install git+https://github.com/wenet-e2e/wenet.git
```
and run
```python
import wenet
model = wenet.load_model('chinese')
result = model.transcribe('audio.wav')
print(result['text'])
```
will report `ModuleNotFoundError: No module named 'wenet.text'`.
The commit id of insatlled code is: `d39af5805cf187831303068711f0c8bb8a9ca4fe`

**Comment by xingchensong** [comment]
可能是这个 https://github.com/wenet-e2e/wenet/tree/main/wenet/text 目录下缺个__init__.py, 快提个PR修一下
