### ISSUE TITLE
MOE支持多语种识别的问题

### ISSUE THREAD

**Issue by fclearner** [wenet-e2e/wenet#2250]
参考这篇谷歌的论文:https://arxiv.org/pdf/2305.15663.pdf
看起来只是改了一层conformer的fc层，加了个MOE模块
<img width="394" alt="1702889588453" src="https://github.com/wenet-e2e/wenet/assets/19747891/ad9026d6-41e1-4b61-83d2-a9a413d51a69">

@Mddct 周神有啥看法
详细的训练策略有待研究(是否需要冻结参数？)，论文看的我有点懵，如果有大佬指导下就更好了(respect)

加个知乎文章: https://zhuanlan.zhihu.com/p/671873012

**Comment by shanguanma** [comment]
I just read this article, its mixture-of-experts is to replace the ffn in each conformer block, because each ffn has two linear layers, if the first linear layer is replaced, it is recorded as MoE -Start, when the second linear layer is replaced, it is marked as MoE-End, and when both are replaced, it is marked as MoE-Both. The mixture-of-experts layer here should be 8 linear layers, that is, 8 experts. In the end, the actual each time you select only the top2 experts, the following code snippet can be easily understood:
```
class MoE(nn.Module):
    def __init__(self) -> None:
        super().__init__()
        self.gate = nn.Linear(n_embd, n_expert, bias=False)
        self.experts = nn.ModuleList(nn.Linear() for _ in range(n_expert))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        B, T, C = x.size()  # batch size, sequence length, embedding dimensionality (n_embd)
        x = x.view(-1, C)  # (B*T, C)
        router = self.gate(x)  # (B*T, n_expert)
        probs, indices = torch.topk(router, n_expert_per_token)
        probs = probs.softmax(dim=1, dtype=torch.float).to(dtype=x.dtype)  # (B*T, n_expert_per_token)
        y = torch.zeros_like(x)  # (B*T, C)
        for i, expert in enumerate(self.experts):
            mask = indices == i
            batch_idx, ith_expert = torch.where(mask)
            y[batch_idx] += probs[batch_idx, ith_expert, None] * expert(x[batch_idx])
        return y.view(B, T, C)
```

**Comment by fclearner** [comment]
> I just read this article, its mixture-of-experts is to replace the ffn in each conformer block, because each ffn has two linear layers, if the first linear layer is replaced, it is recorded as MoE -Start, when the second linear layer is replaced, it is marked as MoE-End, and when both are replaced, it is marked as MoE-Both. The mixture-of-experts layer here should be 8 linear layers, that is, 8 experts. In the end, the actual each time you select only the top2 experts, the following code snippet can be easily understood:
> 
> ```
> class MoE(nn.Module):
>     def __init__(self) -> None:
>         super().__init__()
>         self.gate = nn.Linear(n_embd, n_expert, bias=False)
>         self.experts = nn.ModuleList(nn.Linear() for _ in range(n_expert))
> 
>     def forward(self, x: torch.Tensor) -> torch.Tensor:
>         B, T, C = x.size()  # batch size, sequence length, embedding dimensionality (n_embd)
>         x = x.view(-1, C)  # (B*T, C)
>         router = self.gate(x)  # (B*T, n_expert)
>         probs, indices = torch.topk(router, n_expert_per_token)
>         probs = probs.softmax(dim=1, dtype=torch.float).to(dtype=x.dtype)  # (B*T, n_expert_per_token)
>         y = torch.zeros_like(x)  # (B*T, C)
>         for i, expert in enumerate(self.experts):
>             mask = indices == i
>             batch_idx, ith_expert = torch.where(mask)
>             y[batch_idx] += probs[batch_idx, ith_expert, None] * expert(x[batch_idx])
>         return y.view(B, T, C)
> ```

Thanks for sharing this insightful explanation of the MoE net. The code snippet provided helps in understanding the implementation of the MoE module. Great work! Additionally, I'm curious about the model's ability to learn to switch between different tasks using the MoE module and whether there's a need to consider parameter freezing for expert-task training

**Comment by Mddct** [comment]
感谢！！ make pr？

**Comment by shanguanma** [comment]
@Mddct，I can add a class if you feel it's necessary. @fclearner , from this google paper,He did not explore this area(parameter freezing or finetune), However, latest Mistral AI release Mixtral 8x7B LLM model. It can be seen in its related interpretation [that](https://mp.weixin.qq.com/s/knFuzD7IkJ73lvrRu-hdiQ) expert may reuse the model weights that have been trained before.

**Comment by fclearner** [comment]
> @Mddct，I can add a class if you feel it's necessary. @fclearner , from this google paper,He did not explore this area(parameter freezing or finetune), However, latest Mistral AI release Mixtral 8x7B LLM model. It can be seen in its related interpretation [that](https://mp.weixin.qq.com/s/knFuzD7IkJ73lvrRu-hdiQ) expert may reuse the model weights that have been trained before.

thanks, I think we can start by conducting some experiments to validate the effectiveness of MoE and the training strategies used
