### ISSUE TITLE
decoder_main.cc 中线程warmup的bug

### ISSUE THREAD

**Issue by HalFTeen** [wenet-e2e/wenet#2257]
![image](https://github.com/wenet-e2e/wenet/assets/38465161/a07489cb-57a9-405d-acbe-588d6b706471)
另外，这里 FLAGS_warmup 跟 FLAGS_thread_num 数值上有必然的关系吗？必须相等（每个线程都先解码一次）还是怎样的？ 期待大佬的解答，谢谢

**Comment by xingchensong** [comment]
warmup的目标对象是libtorch.so or libonnx,不是某个具体线程
