### ISSUE TITLE
语言模型结果异常

### ISSUE THREAD

**Issue by wpchenit** [wenet-e2e/wenet#2258]
**Describe the bug**
使用合并giga和wenetspeech实例中units.txt形成新的units.txt生成TLG.fst识别结果异常。

**To Reproduce**
生成TLG.fst步骤参考aishell实例中的步骤
1. tools/fst/prepare_dict.py $unit_file data/lm/lexicon.txt data/local/dict/lexicon.txt
2. 使用lexicon.txt生成分词词典，参考kaldi aishellv2方式严格按照词典分词：jieba.cut(parts[1], HMM=False)
3. local/aishell_train_lms.sh
4. tools/fst/compile_lexicon_token_fst.sh data/local/dict data/local/tmp data/local/lang
5. tools/fst/make_tlg.sh data/local/lm data/local/lang data/lang_test
6. 使用decoder_main解码，命令为:
  export GLOG_logtostderr=1
  export GLOG_v=2
  wav_path=warmup.wav
  onnx_dir=model
  units=units.txt  # Change it to your model units path
   ./decoder_main \
    --chunk_size 16 \
    --num_left_chunks -1 \
    --beam 9.0 \
    --lattice_beam 6.0 \
    --max_active 5000 \
    --warmup 2 \
    --acoustic_scale 3 \
    --blank_skip_thresh 0.98 \
    --wav_path $wav_path \
    --dict_path ${onnx_dir}/words.txt \
    --fst_path ${onnx_dir}/TLG.fst \
    --onnx_dir $onnx_dir \
    --unit_path ${onnx_dir}/$units 2>&1 | tee log.txt

**use TLG.fst result**
![0c2ca7b20b3cde4d03f4fc80460769c](https://github.com/wenet-e2e/wenet/assets/64248379/b2ada935-7c13-4b86-9932-e9ff66a181c4)

**unuse TLG.fst result**
![8d1fcb32ba7c8f65dfbc5b5e88c4c3b](https://github.com/wenet-e2e/wenet/assets/64248379/7d4233b8-e04a-4de8-8420-fdc5559e5dd9)

**Additional context**
使用同样的文本，使用wenetspeech里面的units.txt识别结果如图
![image](https://github.com/wenet-e2e/wenet/assets/64248379/eff7c5a1-26f9-478f-a8f4-3c35491dde0c)

异常的units.txt如附件
[units.txt](https://github.com/wenet-e2e/wenet/files/13764401/units.txt)

**Comment by wpchenit** [comment]
模型链接：
链接：https://pan.baidu.com/s/17rI-KzoqTrD9CWAnWZG3MQ 
提取码：zwod

**Comment by xingchensong** [comment]
1. 检查字典，sos是2还是4232
2. 检查是否构图时存在这里的问题 https://github.com/wenet-e2e/wenet/issues/2254

**Comment by wpchenit** [comment]
已收到您的邮件。

**Comment by wpchenit** [comment]
> 1. 查字典，sos是2还是4232
> 2. 检查构图时是否存在这里的问题[运行aishell示例加阶段7的LM报错问题](https://github.com/wenet-e2e/wenet/issues/2254)[ #2254](https://github.com/wenet-e2e/wenet/issues/2254)[](https://github.com/wenet-e2e/wenet/issues/2254)

1. units.txt内sos是10504  <sos/eos> 10504
2. 字典构图未遇到问题。且因为同样的步骤，同样的文本语料使用wenetspeech预训练模型的units.txt是没问题的。
