### ISSUE TITLE
Wrong arguments in ./examples/timit/s0/run.sh stage 5 when runing recognize.py

### ISSUE THREAD

**Issue by Pooookeman** [wenet-e2e/wenet#2260]
**Describe the bug**
"--result_file" should be "--result_dir" for current version, and the "--connect_symbol" is missing for this phoneme recognition task.
**To Reproduce**
1. Go to './examples/timit/s0'
2. Run 'run.sh'

**Expected behavior**
The output phonemes are not seperated without "--connect_symbol"
![image](https://github.com/wenet-e2e/wenet/assets/44428159/3672a824-3274-4e0e-9760-6171b011015e)

**Screenshots**
![image](https://github.com/wenet-e2e/wenet/assets/44428159/a47a6937-3f6b-4875-b6fb-d8c03587aeb5)

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by xingchensong** [comment]
try latest code

**Comment by Pooookeman** [comment]
> try latest code

I just downloaded and tried on this repo, would you mind providing the link to the latest code?

**Comment by xingchensong** [comment]
add `connect_symbol: ' '` in yaml, and try again

https://github.com/wenet-e2e/wenet/blob/main/examples/timit/s0/conf/train_conformer.yaml#L34

**Comment by Pooookeman** [comment]
> add `connect_symbol: ' '` in yaml, and try again
> 
> https://github.com/wenet-e2e/wenet/blob/main/examples/timit/s0/conf/train_conformer.yaml#L34

It works! Thank you

**Comment by xingchensong** [comment]
@Pooookeman could u make a PR to fix this issue?

**Comment by Pooookeman** [comment]
> @Pooookeman could u make a PR to fix this issue?

Sure yes, but I'm afraid the way I'm modifying can be potentially harmful to the project by passing connect_symbol to tokenizer, especially other datasets with 'split_with_space'==FALSE.

>     elif tokenizer_type == "char":
        tokenizer = CharTokenizer(
            configs['tokenizer_conf']['symbol_table_path'],
            configs['tokenizer_conf']['non_lang_syms_path'],
            split_with_space=configs['tokenizer_conf'].get(
                'split_with_space', False),
            connect_symbol=configs['tokenizer_conf'].get(
                'split_with_space', ''))
If no further problems, I will submit a PR

**Comment by xingchensong** [comment]
if u set it to the default value (''), then it's ok

```py
connect_symbol=configs['tokenizer_conf'].get(
            'connect_symbol', '')
```

**Comment by Pooookeman** [comment]
> if u set it to the default value (''), then it's ok
> 
> ```python
> connect_symbol=configs['tokenizer_conf'].get(
>             'connect_symbol', '')
> ```

Oh sry for the typo, will submit the PR soon
