### ISSUE TITLE
ASRModel类中的apply_non_blank_embedding的作用是什么？

### ISSUE THREAD

**Issue by segu-L** [wenet-e2e/wenet#2267]
# asr_model.py line105
# 2b. Attention-decoder branch
        # use non blank (token level) embedding for decoder
        if self.apply_non_blank_embedding:
            assert self.ctc_weight != 0
            encoder_out, encoder_mask = self.filter_blank_embedding(
                ctc_probs, encoder_out)
        if self.ctc_weight != 1.0:
            loss_att, acc_att = self._calc_att_loss(encoder_out, encoder_mask,
                                                    text, text_lengths)
        else:
            loss_att = None
            acc_att = None

在解码之前会判断self.apply_non_blank_embedding，做过滤。self.filter_blank_embedding()函数的作用是什么呢

**Comment by kobenaxie** [comment]
跳帧的，过滤掉出blank的语音帧，加快解码的
