### ISSUE TITLE
/example/aishell/s0训练到stage4时卡住，使用的数据集是aishell+少量其他数据。参数就是train_conformer.yaml的原始参数。

### ISSUE THREAD

**Issue by alanshaoTT** [wenet-e2e/wenet#2294]
**Describe the bug**
/example/aishell/s0训练到stage4时卡住

**To Reproduce**
将data换成了aishell+少量其他数据，训练/example/aishell/s0的conformer模型，参数按照train_conformer.yaml，在8卡2080ti训练stage4时卡住

**Screenshots**
![image](https://github.com/wenet-e2e/wenet/assets/101975339/23d7bc9e-b969-45b0-b3e4-5af6665b06f5)

**Comment by alanshaoTT** [comment]
改小了batch_size也不行

**Comment by alanshaoTT** [comment]
pdb调试发现是train.py中145行executor.train(model, optimizer, scheduler, train_data_loader,
                       cv_data_loader, writer, configs, scaler, group_join)出错，在executor.train中执行到53行
with model_context():
->         for batch_idx, batch_dict in enumerate(train_data_loader):
                info_dict["tag"] = "TRAIN"
                info_dict["step"] = self.step
                info_dict["batch_idx"] = batch_idx
                if wenet_join(group_join, info_dict):出错

**Comment by xingchensong** [comment]
拉最新代码，https://github.com/wenet-e2e/wenet/pull/2286 至少要是合入了这个pr的代码

**Comment by alanshaoTT** [comment]
可以正常训练了，谢谢！！

**Comment by alanshaoTT** [comment]
你好 最近在使用最新wenet代码之后又出现了相同的问题  在本issue下相同的数据和yaml下训练卡在了
![image](https://github.com/wenet-e2e/wenet/assets/101975339/1e1e072e-f4f9-497c-8521-10c8674b544e)

**Comment by Mddct** [comment]
拉今天的代码看下
