### ISSUE TITLE
转ONNX推理结果前后不一致

### ISSUE THREAD

**Issue by hotbaby** [wenet-e2e/wenet#2304]
转ONNX之前识别结果是：
`HIS NAME IS A SHOP HIS NAME IS A SHOP`

转ONNX之后识别结果是：
`HIS NAME IS A SHEF HIS NAME IS A SHEF`

**Comment by LRY1994** [comment]
怎么解决呢？

**Comment by hotbaby** [comment]
> 怎么解决呢？

我的case是因为训练和推理参数不一致，训练的用了cmvn normalization，推理的时候没有用cmvn，所以导致了这个问题。
