### ISSUE TITLE
FAST-U2++ reproducible code or config support

### ISSUE THREAD

**Issue by lzl-mt** [wenet-e2e/wenet#2306]
**Is your feature request related to a problem? Please describe.**
Reduce the last word's emit delay

**Describe the solution you'd like**
Hi, I saw your excellent work: *FAST-U2++* https://arxiv.org/abs/2211.00941, do you have plans to open source reproducible code and configuration in Wenet? Thanks a lot.

**Comment by cdliang11** [comment]
This is the code for the paper [fast-u2pp](https://github.com/cdliang11/fast-u2pp). This is implemented on the basis of early wenet code.

**Comment by lzl-mt** [comment]
> This is the code for the paper [fast-u2pp](https://github.com/cdliang11/fast-u2pp). This is implemented on the basis of early wenet code.

thx!
