### ISSUE TITLE
torch 2.2 新特性

### ISSUE THREAD

**Issue by Mddct** [wenet-e2e/wenet#2335]
1 torch log
2 fsdp （TP DP zero3）

其他参考链接 https://mp.weixin.qq.com/s/sxryOerYdDWh3m9UlnMTU

https://github.com/pytorch/pytorch/releases/tag/v2.2.0

**Comment by DaobinZhu** [comment]
大佬请问现在最新的代码需要CUDA 12以上吗？我目前CUDA版本10.2，torchaudio导入失败，而且torch的GPU不可用

**Comment by Mddct** [comment]
严格按照readme里安装来，基本没有问题 最好是conda环境, 你可以贴一下env

**Comment by DaobinZhu** [comment]
谢谢周佬，问题解决了，就是CUDA的版本太低了，我重新安装了12.2的版本就可以正常运行了，还有一个问题想请教，您在训练RNNT模型的时候是八张V100进行的吗？我现在只有四张12G的P100是不是够呛能收敛呀

**Comment by Mddct** [comment]
可以用k2的loss，checkpoint activatiom 打开 也可以训的bs大点的

**Comment by DaobinZhu** [comment]
谢谢周佬，我试一下，之前稍微调大一点bs就爆显存了



---原始邮件---
发件人: "Dinahao ***@***.***&gt;
发送时间: 2024年2月2日(周五) 中午11:01
收件人: ***@***.***&gt;;
抄送: "Daobin ***@***.******@***.***&gt;;
主题: Re: [wenet-e2e/wenet] torch 2.2 新特性 (Issue #2335)




 
可以用k2的loss，checkpoint activatiom 打开 也可以训的bs大点的
