### ISSUE TITLE
新IO多数据训练卡死

### ISSUE THREAD

**Issue by kobenaxie** [wenet-e2e/wenet#2338]
**Describe the bug**

```
torch==2.1.2+cu118
```

您好，我在单机8卡上使用新IO在更多的数据集上(AISHELL2+LIbrispeech+CSTAL)实验的时候出现了训练卡死的情况，其中一张卡的利用率为0，其余卡利用率100%，看着像是数据不平衡导致的梯度同步的问题？单在AISHELL上用新IO是没有问题的，请问有什么debug的建议吗？

**Comment by Mddct** [comment]
截个卡住的gpu图看看

**Comment by kobenaxie** [comment]
@Mddct 我找到问题了，我没有直接使用wenet的master分支的代码，现在的代码是基于wenet之前版本修改来的(tar格式可以正常训练)，出现卡死的情况主要有两点原因；

1. 因为存储空间的限制，我之前把shard格式数据打包成bz2格式了，不过bz2解压很慢；
2. `decode_wav`还是按照旧的IO中直接使用
```
with stream.extractfile(tar_info) as file_obj:
    waveform, sample_rate = torchaudio.load(file_obj)
```
如果按照新的IO中改成
```
with stream.extractfile(tar_info) as file_obj:
    waveform, sample_rate = torchaudio.load(io.BytesIO(file_obj.read()))
```
之后训练就正常了（仅限于bz2格式的数据）
在最新的master分支充分验证代码正确性之前还是不能乱改啊

**Comment by Mddct** [comment]
<img width="647" alt="Screenshot 2024-02-04 at 16 17 13" src="https://github.com/wenet-e2e/wenet/assets/4906435/574f2336-2646-478e-bf76-ef1a6a1213f8">

master 里decode_wav 接受两种 一种是bytes， 一种路径， 你decode_wav 用的是

**Comment by kobenaxie** [comment]
是的，master是没问题的，我自己的问题，decode_wav那里改的不对

**Comment by kobenaxie** [comment]
> <img alt="Screenshot 2024-02-04 at 16 17 13" width="647" src="https://private-user-images.githubusercontent.com/4906435/302087769-574f2336-2646-478e-bf76-ef1a6a1213f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMzUxNTQsIm5iZiI6MTcwNzAzNDg1NCwicGF0aCI6Ii80OTA2NDM1LzMwMjA4Nzc2OS01NzRmMjMzNi0yNjQ2LTQ3OGUtYmY3Ni1lZjFhNmExMjEzZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDRUMDgyMDU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM5MWM4MDk5ZGYwZDI4MzU1YzM2ODY2ODQyNzFmNDM5MWYyZjRjNjkwOWEyOWUyNmYyODZkYzRjYzA2NDRlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JXFAi3rF85spUxsOcJ-AuAsEX9P5ehl2LJahgctBCF0">
> master 里decode_wav 接受两种 一种是bytes， 一种路径，这里是没问题的 （从tar出来的是bytes）
> 
> 等io完成差不多了， 完善下文档 TODO
> 
> * [ ]  新dataset 文档

这里好像有个小bug，
```
sample['wav'] = waveform
sample['sample_rate'] = sample_rate
```
应该在`if...else...` 的外边，现在是在`else`内的

**Comment by Mddct** [comment]
提个pr， segment的这种一直没有跑过
