### ISSUE TITLE
Citing Wenet lib in another CMake project

### ISSUE THREAD

**Issue by YimengZhu** [wenet-e2e/wenet#2348]
Hi,

I'm trying to use wenet to do SR in a [ROS](https://www.ros.org/) package. To do that, I need to use wenet as a lib in the C++ code. I noticed there is a libdecoder.a after building the runtime. Is there any header file I could include for this lib?

Also, is there any official doc about how to use wenet in other CMake project? w

Appreciate if anyone could help on this!

Thanks,
Yimeng

**Comment by xingchensong** [comment]
u may refer to this https://github.com/wenet-e2e/wenet/blob/main/runtime/core/bin/decoder_main.cc#L19-L25

**Comment by YimengZhu** [comment]
do I have to include all the header file in wenet? What is the corresponding lib in the build?

**Comment by xingchensong** [comment]
just include what is included in decoder_main.cc

**Comment by YimengZhu** [comment]
BTW, for the sake of simplicity in the future, I prefer to use it as dynamic lib than static...

**Comment by csukuangfj** [comment]
> BTW, for the sake of simplicity in the future, I prefer to use it as dynamic lib than static...

@YimengZhu 可以参考下
https://k2-fsa.github.io/sherpa/onnx/c-api/index.html
或者
https://k2-fsa.github.io/sherpa/ncnn/c-api/index.html

只需要在你项目里，包含一个 c 语言头文件, 及所需的若干库文件（静态库.a，或者动态库 .so）。
