### ISSUE TITLE
Should check enc_init instead of checkpoint at line 166 in init_model.py

### ISSUE THREAD

**Issue by shaominFei** [wenet-e2e/wenet#2350]
**Describe the bug**
There might be a typo at line 166 in init_model.py. The check should be on enc_init, but now it's on checkpoint

**To Reproduce**
1. Go to wenet/utils/init_model.py
2. Scroll to line 166
3. The check should be on enc_init, not on checkpoint
![image](https://github.com/wenet-e2e/wenet/assets/90332261/520f4b5c-da7d-4c9e-9886-669524c8a045)

**Comment by robin1001** [comment]
Good catch!

**Comment by robin1001** [comment]
Fixed, see https://github.com/wenet-e2e/wenet/pull/2354
