### ISSUE TITLE
最新版代码，LibriSpeech复现不成功，run.sh，stage1，RuntimeError: Error loading audio file: failed to open file

### ISSUE THREAD

**Issue by jinleihu** [wenet-e2e/wenet#2352]
stage 1: Feature Generation
tools/compute_cmvn_stats.py:15: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this func               tion is no-op. You can remove the function call.
  torchaudio.set_audio_backend("sox_io")
using resample and new sample rate is 16000
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement               ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi               ng implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
Traceback (most recent call last):
  File "tools/compute_cmvn_stats.py", line 125, in <module>
    for i, batch in enumerate(data_loader):
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "tools/compute_cmvn_stats.py", line 35, in __call__
    sample_rate = torchaudio.backend.sox_io_backend.info(
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torchaudio/backend/_sox_io_backend.py", line 32, in info
    sinfo = torch.ops.torchaudio.sox_io_get_info(filepath, format)
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Error loading audio file: failed to open file /home/hujinlei/hjl/LibriSpeech/train-clean-360/1054/143005/1054-143005-0084.fl                                         ac 

查看了/home/hujinlei/hjl/LibriSpeech/train-clean-360/1054/143005/1054-143005-0084.flac 文件是存在的

**Comment by jinleihu** [comment]
RuntimeError: Error loading audio file: failed to open file /home/hujinlei/hjl/LibriSpeech/train-clean-360/1054/143005/1054-143005-0084.fl            ac 
发现报错中的路径最后 flac中多了很多空格

**Comment by jinleihu** [comment]
> 重新制作一下数据集试试

您好，我尝试重新跑stage 0，重新跑stage 1，

还是出现类似的错误
RuntimeError: Error loading audio file: failed to open file /home/hujinlei/hjl/LibriSpeech/train-other-500/1595/132753/1595-132753-0011.flac


完整流程如下
/home/hujinlei/hjl/wenet/examples/librispeech/s0# bash run_try.sh

CUDA_VISIBLE_DEVICES is 0,1,2,3,4,5,6,7
stage 1: Feature Generation
tools/compute_cmvn_stats.py:15: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("sox_io")
using resample and new sample rate is 16000
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlying implementation directly.
  sample_rate = torchaudio.backend.sox_io_backend.info(
Traceback (most recent call last):
  File "tools/compute_cmvn_stats.py", line 125, in <module>
    for i, batch in enumerate(data_loader):
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "tools/compute_cmvn_stats.py", line 35, in __call__
    sample_rate = torchaudio.backend.sox_io_backend.info(
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torchaudio/backend/_sox_io_backend.py", line 32, in info
    sinfo = torch.ops.torchaudio.sox_io_get_info(filepath, format)
  File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Error loading audio file: failed to open file /home/hujinlei/hjl/LibriSpeech/train-other-500/1595/132753/1595-132753-0011.flac

**Comment by xingchensong** [comment]
/home/hujinlei/hjl/LibriSpeech/train-other-500/1595/132753/1595-132753-0011.flac 检查这个文件，如果有问题，从stage -1 开始重新跑

**Comment by jinleihu** [comment]
> /home/hujinlei/hjl/LibriSpeech/train-other-500/1595/132753/1595-132753-0011.flac 检查这个文件，如果有问题，从stage -1 开始重新跑

您好，我按照路径去检查了这个文件，文件是正常的，
![11](https://github.com/wenet-e2e/wenet/assets/92070079/b54063ee-07b4-4d93-bdaa-ffbdc5a14012)

**Comment by jinleihu** [comment]
您好，我参照同学的上个版本的wenet环境，使用torch==1.13.0和torchaudio==0.13.0替代了最新的torch版本之后该问题解决了，可能还是由于版本问题导致的

**Comment by jinleihu** [comment]
> 您好，我参照同学的上个版本的wenet环境，使用torch==1.13.0和torchaudio==0.13.0替代了最新的torch版本之后该问题解决了，可能还是由于版本问题导致的

但替代之后 stage 4 报了新错误 ModuleNotFoundError: No module named 'torch.utils.data.datapipes.iter.sharding'
换回原来的环境就好了...

**Comment by Mddct** [comment]
用readme里边建议的安装一下，这个torch.utils.data.datapipes.iter.sharding， torch 2.0之后才有的

**Comment by jinleihu** [comment]
> 用readme里边建议的安装一下，这个torch.utils.data.datapipes.iter.sharding， torch 2.0之后才有的

是的，用最新版的requirements.txt  stage4 是可以跑的，但最新版的环境stage 1 会报错......

用老版的环境stage 1 就不报错了，但stage 4 会卡住 就是应该因为torch版本的问题。目前主要还是没找到为啥最新环境stage 1会报错，我尝试用aishell数据集的话就没问题

**Comment by xingchensong** [comment]
librispeech 原始数据是flac格式的，aishell是wav，可能处理flac有点问题

**Comment by lsrami** [comment]
> stage 1: Feature Generation tools/compute_cmvn_stats.py:15: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this func tion is no-op. You can remove the function call. torchaudio.set_audio_backend("sox_io") using resample and new sample rate is 16000 tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( tools/compute_cmvn_stats.py:35: UserWarning: Torchaudio's I/O functions now support par-call bakcend dispatch. Importing backend implement ation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the udnerlyi ng implementation directly. sample_rate = torchaudio.backend.sox_io_backend.info( Traceback (most recent call last): File "tools/compute_cmvn_stats.py", line 125, in for i, batch in enumerate(data_loader): File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in **next** data = self._next_data() File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data return self._process_data(data) File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data data.reraise() File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise raise exception RuntimeError: Caught RuntimeError in DataLoader worker process 0. Original Traceback (most recent call last): File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop data = fetcher.fetch(index) File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch return self.collate_fn(data) File "tools/compute_cmvn_stats.py", line 35, in **call** sample_rate = torchaudio.backend.sox_io_backend.info( File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torchaudio/backend/_sox_io_backend.py", line 32, in info sinfo = torch.ops.torchaudio.sox_io_get_info(filepath, format) File "/root/anaconda3/envs/wenet/lib/python3.8/site-packages/torch/_ops.py", line 692, in **call** return self._op(*args, **kwargs or {}) RuntimeError: Error loading audio file: failed to open file /home/hujinlei/hjl/LibriSpeech/train-clean-360/1054/143005/1054-143005-0084.fl ac
> 
> 查看了/home/hujinlei/hjl/LibriSpeech/train-clean-360/1054/143005/1054-143005-0084.flac 文件是存在的


这是由于在torchaudio更新到2.0以后启用了[dispatcher 机制](https://pytorch.org/audio/main/torchaudio.html)；因此需要更新 [compute_cmvn_stats.py](https://github.com/wenet-e2e/wenet/blob/main/tools/compute_cmvn_stats.py#L35) ，将torchaudio.backend.sox_io_backend.info改成torchaudio.info

**Comment by xingchensong** [comment]
@lsrami 可以提个pr修复吗

**Comment by turinaf** [comment]
Hi, I'm facing this issue when running stage 1 on custom dataset.
First, I thought it was about audio path issue, so I changed wav_path to absolute path, but still the error persisted 

stage 1: Feature Generation
using resample and new sample rate is 16000
Traceback (most recent call last):
  File "/home/turi/experiment/oasr/wenet/examples/librispeech/s0/tools/compute_cmvn_stats.py", line 122, in <module>
    for i, batch in enumerate(data_loader):
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/_utils.py", line 722, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/experiment/oasr/wenet/examples/librispeech/s0/tools/compute_cmvn_stats.py", line 33, in __call__
    sample_rate = torchaudio.info(wav_path).sample_rate
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torchaudio/_backend/utils.py", line 99, in info
    return backend.info(uri, format, buffer_size)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torchaudio/_backend/sox.py", line 22, in info
    sinfo = sox_ext.get_info(uri, format)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/turi/anaconda3/envs/torch_env/lib/python3.11/site-packages/torch/_ops.py", line 755, in __call__
    return self._op(*args, **(kwargs or {}))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error loading audio file: failed to open file /home/turi/experiment/oasr/data/train/sagalee_SPKRF109_130.flac

**Comment by turinaf** [comment]
@xingchensong FYI, I converted my custom data into `.wav` format and still getting same error
