### ISSUE TITLE
sdpa about

### ISSUE THREAD

**Issue by Macsim2** [wenet-e2e/wenet#2361]
I'm curious about performance of flash attention.
And I saw the 5dfc9dcbd4f6fa050baa297b9d0fe2e38a4aaa0b (commit id), We can use a sdpa for conformer now.
Is it only available cpu-mode?
If it works no matter which mode, 

```python 
with torch.backends.cuda.sdp_kernel(enable_math=False):
F.scaled_dot_product_attention(query,key,value)
```
Does gpu-mode still work without this code or something?

**Comment by Mddct** [comment]
Pytorch natively supports flash attention through sdpa, we do not need this line ‘with torch.backends.cuda.sdp_kernel(enable_math=False):’, pytorch will automatically select flash attention or memory efficenet attention 
you can check  https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html
and https://github.com/wenet-e2e/wenet/pull/2351

**Comment by Mddct** [comment]
Wenet's previous code implemented the attention calculation process by itself. This parameter is compatible with the previous one. When it is false, the previous implementation is used. When it is true, F.scaled_dot_product_attention is used.

Wenet's previous code implemented the attention calculation process by itself. This parameter is compatible with the previous one. When it is false, the previous implementation is used. When it is true, F.scaled_dot_product_attention is used.  btw This function currently cannot be converted to onnx, but it can be converted to jit

**Comment by Macsim2** [comment]
Thank you very much @Mddct 
I understand your answer
