### ISSUE TITLE
Reproduce CHiME4 results

### ISSUE THREAD

**Issue by lcoppieters** [wenet-e2e/wenet#2364]
**Describe the bug**
I tried to reproduce the baseline results obtained on the CHiME4 dataset, but the results are not similar to the ones in the README file. Do you have any clue about the reason where this performance difference is coming from?

**To Reproduce**
I used the complete dataset and the baseline files in wenet/examples/chime4/s0 

**Expected behavior**
|      decoding mode     | dt05_real_1ch | dt05_simu_1ch | et05_real_1ch | et05_simu_1ch |
|:----------------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| ctc_prefix_beam_search |   19.06%      |   21.17%      |   28.39%      |    29.16%     |
|  attention_rescoring   |   17.92%      |   20.22%      |   27.40%      |    28.25%     |

**My results**
|      decoding mode     | dt05_real_1ch | dt05_simu_1ch | et05_real_1ch | et05_simu_1ch |
|:----------------------:|:-------------:|:-------------:|:-------------:|:-------------:|
| ctc_prefix_beam_search |   22.71 %     |   24.28 %      |   32.66 %      |    55.11 %     |
|  attention_rescoring   |  21.51 %    |   23.28 %      |   31.54 %     |    54.55 %     |

**Comment by rookie0607** [comment]
> **描述我尝试重现在CHiME4数据集上获得的基线结果的错误** ，但结果与README文件中的结果不相似。您知道这种性能差异的原因吗？
> 
> **为了覆盖，** 我使用了 wenet/examples/chime4/s0 中的完整数据集和基线文件
> 
> **预期行为**
> 
> 解码方式	dt05_real_1ch	dt05_simu_1ch	et05_real_1ch	et05_simu_1ch
> ctc_prefix_beam_search	19.06%	21.17%	28.39%	29.16%
> 注意力重新评分	17.92%	20.22%	27.40%	28.25%
> **我的结果**
> 
> 解码方式	dt05_real_1ch	dt05_simu_1ch	et05_real_1ch	et05_simu_1ch
> ctc_prefix_beam_search	22.71%	24.28%	32.66%	55.11%
> 注意力重新评分	21.51%	23.28%	31.54%	54.55%

大佬，能求一份chme4数据吗
