### ISSUE TITLE
Unified 及 U2++中 attention rescoring 并不是严格streaming的吗？

### ISSUE THREAD

**Issue by FnoY0723** [wenet-e2e/wenet#2372]
查看attention rescoring的代码时发现，尽管选择decode chunk size不为full（即streaming mode），encoder的输出还是会全部输入decoder，在decoder的src_att中会用到所有的context，这样就并不是严格streaming的。

不知道我的理解是否正确？如果有误还望指出

**Comment by xingchensong** [comment]
rescore是非流的
