### ISSUE TITLE
Whisper训练

### ISSUE THREAD

**Issue by zhangron013** [wenet-e2e/wenet#2382]
我是一个刚接触语音方向的小白，想问一下Whisper的训练是需要先remove conv1d2 and init ctc，然后将处理后的权重作为初始权重加载进去训练吗？另外我在conf/finetune_whisper_largev3.yaml没有找到哪里是加载词典路径的参数？训练步骤可否详细些？

**Comment by xingchensong** [comment]
可以不remove，用这个配置 https://github.com/wenet-e2e/wenet/blob/main/examples/aishell/whisper/conf/finetune_whisper_largev3_onlyattn.yaml

whisper自带词典，不需要显示配置

**Comment by aaaaamilk** [comment]
您好，我想问一下，微调之后还能支持英文的吗？
