### ISSUE TITLE
aishell paraformer复现的cer对不上

### ISSUE THREAD

**Issue by RyanFlying** [wenet-e2e/wenet#2386]
![img_v3_028m_f334122d-ce60-4b5b-86e5-61a91f75e0ag](https://github.com/wenet-e2e/wenet/assets/71589850/14122493-a1cc-456f-88d6-7038166e9aa6)
![tG8lHGCSsY](https://github.com/wenet-e2e/wenet/assets/71589850/321b8046-aed1-4c7c-88aa-b51a2037b910)
跑aishell中paraformer的识别，识别出结果如上。与官方cer相差甚远！
所采用的模型为https://www.modelscope.cn/models/iic/speech_paraformer_asr_nat-zh-cn-16k-common-vocab8404-online/summary。
通过官方的转换脚本转换后，直接跑run.sh中第2步中的识别，结果如上。

**Comment by Mddct** [comment]
如何操作的 请简单写一下

**Comment by RyanFlying** [comment]
我就是拿上述转换后的pt，即exp/paraformer/large/wenet_paraformer.pt，进行测试的。

**Comment by Mddct** [comment]
新泡的 我这边可以复现

<img width="1326" alt="截屏2024-03-06 13 02 46" src="https://github.com/wenet-e2e/wenet/assets/4906435/a297e703-4a09-49f9-8504-4a8736719d75">

**Comment by RyanFlying** [comment]
方便加个微信吗？我的15811168806

**Comment by RyanFlying** [comment]
![Oxyl6O77AC](https://github.com/wenet-e2e/wenet/assets/71589850/a2a4343c-d279-487d-bd88-5dca1391b17a)

我是将这里面的--checkpoint参数指定为exp/paraformer/large/wenet_paraformer.pt，其他参数没改动。跑出的上述结果。
