### ISSUE TITLE
whisper使用tiny权重

### ISSUE THREAD

**Issue by zhangron013** [wenet-e2e/wenet#2391]
我想请教一下，我想加载whisper的tiny权重finetune，但是我看到代码中是没有公布tiny对应的配置yaml的，我使用large-v3.yaml训练报错：
`RuntimeError: Error(s) in loading state_dict for Whisper:
  	size mismatch for ctc.ctc_lo.weight: copying a param with shape torch.Size([51865, 384]) from checkpoint, the shape in current model is torch.Size([51866, 1280])`
然后我在配置文件中改了第一层的输出为384后，报错：
` File "/data/zhangluotao/project/wenet_new/wenet-main/wenet/transformer/attention.py", line 47, in __init__
      assert n_feat % n_head == 0
  AssertionError
`
我把它注释掉之后报错：
`  RuntimeError: Error(s) in loading state_dict for Whisper:
  	size mismatch for ctc.ctc_lo.weight: copying a param with shape torch.Size([51865, 384]) from checkpoint, the shape in current model is torch.Size([51866, 384])`
请问我如果想使用tiny作为预训练权重，应该怎么修改？

**Comment by xingchensong** [comment]
convert.....py 会自动生成一个对应tiny的train.yaml，自己改下batchsize，lr之类的东西
