### ISSUE TITLE
cli中的confidence实例， 可以支持batch推理吗

### ISSUE THREAD

**Issue by yangyyt** [wenet-e2e/wenet#2400]
**Is your feature request related to a problem? Please describe.**
希望加速模型推理，能够输出置信度和对齐的时间信息。

**Describe the solution you'd like**
batch推理。

**Describe alternatives you've considered**
数据太多了的情况下，调用https://github.com/wenet-e2e/wenet/pull/2083这个推理接口，发现处理时间太长。

**Additional context**

**Comment by Mddct** [comment]
可以自己改一下 decode接口本身是支持batch的

**Comment by yangyyt** [comment]
> 可以自己改一下 decode接口本身是支持batch的

今天在用这个工具打印置信度的时候遇到了一个新的问题，处理大于3min的音频的时候，位置编码过长导致报错，请问cli中的实例应该怎么修改呢
![image](https://github.com/wenet-e2e/wenet/assets/26132147/9e2919db-0f7f-4718-94ac-762538dfa66c)

**Comment by Mddct** [comment]
不支持这么长的 该位置编码的max len可以 但是效果会变差
