### ISSUE TITLE
Converting Hugging Face's Whisper model to Wenet

### ISSUE THREAD

**Issue by lsrami** [wenet-e2e/wenet#2408]
I have been fine-tuning the Whisper model provided by OpenAI on Hugging Face and have achieved some results. Now, I would like to continue fine-tuning this model using the Wenet framework.

I would like to know if there is an existing method to convert the Whisper model from Hugging Face to Wenet? If not, is it possible to develop a new tool to perform this conversion?

I understand that this might involve considerations about the compatibility of the model structures and weights. I would appreciate any advice on how to approach these issues.

**Comment by boxpkaka** [comment]
You can first convert the huggingface model to openai format, and then convert from openai format to wenet

**Comment by lsrami** [comment]
> You can first convert the huggingface model to openai format, and then convert from openai format to wenet

I only found the conversion script from openai to hugging face in the transformers library, not the hugging face to openai script

**Comment by boxpkaka** [comment]
> > You can first convert the huggingface model to openai format, and then convert from openai format to wenet
> 
> I only found the conversion script from openai to hugging face in the transformers library, not the hugging face to openai script

https://github.com/zuazo-forks/transformers/blob/convert_hf_to_openai/src/transformers/models/whisper/convert_hf_to_openai.py
try this.

**Comment by lsrami** [comment]
> > > You can first convert the huggingface model to openai format, and then convert from openai format to wenet
> > 
> > 
> > I only found the conversion script from openai to hugging face in the transformers library, not the hugging face to openai script
> 
> https://github.com/zuazo-forks/transformers/blob/convert_hf_to_openai/src/transformers/models/whisper/convert_hf_to_openai.py try this.

thanks
