### ISSUE TITLE
context bias for each websocket request

### ISSUE THREAD

**Issue by anjul1008** [wenet-e2e/wenet#2423]
Hi All,

I'm trying to implement context biasing for each websocket request with user provided words.
i have made a few changes in `wesocket_server.cc` file to accept user context strings and score to build graph.
And graph bulding is perfomed in `OnSpeechStart()` method.

But looks graph is not updated with newly build graph, it remains same which is build while loading model from `params.h`.

here are the screenshots of code change:
![Screenshot from 2024-03-19 14-56-25](https://github.com/wenet-e2e/wenet/assets/25085268/64a13b26-b6b6-4d3e-89d9-29d063bd1025)
![Screenshot from 2024-03-19 14-54-53](https://github.com/wenet-e2e/wenet/assets/25085268/11f65cd1-d27c-48bf-9b60-0bd75f240a7a)

Can anyone help me to resolve it, any help would be appreciated.

**Comment by anjul1008** [comment]
graph build successfully and memory location got updated.
![Screenshot from 2024-03-19 15-12-55](https://github.com/wenet-e2e/wenet/assets/25085268/599fac4c-9435-46f2-854e-cfa6024130dd)

**Comment by anjul1008** [comment]
Hi @pengzhendong 
 
i have tried the other approach to, i have added a new method `void ContextGraph::UpdateContextGraph(std::string on_request_context_words_, float on_request_context_score_, const std::shared_ptr<fst::SymbolTable>& unit_table)` in  
 `context_graph.h` header file, which can be called from `OnSpeechGraph()` method in `wesocket_server.cc`.
 
 but it leads to following compilation error:
 
![Screenshot from 2024-03-19 17-05-11](https://github.com/wenet-e2e/wenet/assets/25085268/be75c5ef-88ad-4e97-98f3-c891d0dd69c7)

Can you please suggest me the where i'm making mistake or better approach to handle request level context graph creation.

**Comment by anjul1008** [comment]
i have define it in cc file, now it's working as expected.
thanks

**Comment by Mddct** [comment]
plz make a pr to enhance ？

**Comment by anjul1008** [comment]
Hi @Mddct,
i made changes as described above but the context graph is updated which is shared across active connections.
i'll working on it and need to make major changes with shared context resources to non shared websocket connection.

your guidance would be very helpful if you have time.

thank you.

**Comment by Mddct** [comment]
@pengzhendong  plz make some advice

**Comment by pengzhendong** [comment]
> need to make major changes with shared context resources to non shared

LGTM
