### ISSUE TITLE
After building a LM according to the document, the wer is close to 100%

### ISSUE THREAD

**Issue by Deleter-D** [wenet-e2e/wenet#2425]
**Describe the bug**
I built the TLG language model on aishell according to [LM for WeNet](https://wenet.org.cn/wenet/lm.html#how-to-use). Then use runtime for inference, and the performance is very poor on the test set of aishell.

**Screenshots**
![image](https://github.com/wenet-e2e/wenet/assets/56388518/c5207334-586b-47d7-acab-08acbc4e9c36)

Did I do something wrong? I didn't make any critical changes to the official shell scripts.

**Comment by maiphong0411** [comment]
I think it depends on your language model to build WFST.
