### ISSUE TITLE
train model with train_unified_conformer_ctl.yaml erros

### ISSUE THREAD

**Issue by junshipeng** [wenet-e2e/wenet#2430]
@YYTtyy  
File "***/wenet/utils/executor.py", line 136, in cv
    ) if _dict['th_accuracy'] is not None else 0.0)
KeyError: 'th_accuracy

主要是asr_model_ctl.py文件中forward函数返回的loss_dict中没有"th_accuracy": acc_att，导致executor.py中执行错误
total_acc.append(_dict['th_accuracy'].item(
                ) if _dict['th_accuracy'] is not None else 0.0)

**Comment by xingchensong** [comment]
可以直接提个PR修复

**Comment by YYTtyy** [comment]
ok 我这两天看看哈～
