### ISSUE TITLE
请问为什么测试模型的result是空白的

### ISSUE THREAD

**Issue by ccyniubi** [wenet-e2e/wenet#2435]
![image](https://github.com/wenet-e2e/wenet/assets/79295265/ee8d2a9a-4893-477b-8281-9ccdefe5d553)
![image](https://github.com/wenet-e2e/wenet/assets/79295265/d896c78b-3568-454e-8208-e3fae6aea350)

**Comment by MarStarck** [comment]
我也遇到这个问题了

**Comment by Mddct** [comment]
把flac 转成wav试下

**Comment by caiyuxi** [comment]
我也遇到类似的问题。

```
import torchaudio
import wenet
waveform, sample_rate = torchaudio.load("examples_1995-1836-0002.flac")
torchaudio.save(
    "sound2.wav", waveform, sample_rate,
    encoding="PCM_S")
model = wenet.load_model("english")
result = model.transcribe("sound2.wav")
print(result)
```
stdout为 `{'text': '▁UM', 'confidence': 0.6211525614053677}`
音频文件来自https://huggingface.co/spaces/wenet/wenet_demo/tree/main/examples
除了`wenet.load_model("english")`，其他的预训练模型也有类似的问题。

```
@pytest.mark.parametrize("model", [
    "gigaspeech_u2pp_conformer_libtorch.tar.gz",
    "librispeech_u2pp_conformer_libtorch.tar.gz",
])
def test_model(model):
    dest = model.split('.')[0]  # aishell_u2pp_conformer_libtorch
    dataset = model.split('_')[0]  # aishell
    if not os.path.exists(dest):
        os.makedirs(dest)
    response = requests.get(
        "https://modelscope.cn/api/v1/datasets/wenet/wenet_pretrained_models/oss/tree"  # noqa
    )
    model_info = next(data for data in response.json()["Data"]
                      if data["Key"] == model)
    model_url = model_info['Url']
    download(model_url, dest=dest, only_child=True)
    model = Model(dest, gpu=-1, beam=5, resample_rate=16000)
    assert dataset in ['gigaspeech', 'librispeech']
    audio_file = "sound2.wav"
    result = model.transcribe(audio_file)
    print(result)
```

gigaspeech_u2pp_conformer_libtorch.tar.gz": `{'confidence': 0.6211525614053677, 'text': '▁UM'}`
"librispeech_u2pp_conformer_libtorch.tar.gz": `{'confidence': 0.5829262466384643, 'text': ''}`

**Comment by tianqiong123** [comment]
我也遇到类似问题，我用的是aishell数据集，使用wenet预训练的模型识别wav文件，代码如下：
`import wenet
from pathlib import Path




if __name__=='__main__':
    recognize_net=wenet.load_model(language='chinese',gpu=0)
    
    soundfile_dir=Path('/home/tian/datasets/data_aishell/wav/test')
    total=0
    reg=0
    for soundfile in soundfile_dir.rglob(r'*.wav'):
        result=recognize_net.transcribe(soundfile.as_posix())
        if result['text']=='':
            total+=1
            continue
        print(soundfile.stem, result['text'])
        reg+=1
        total+=1
    
    print(f'{reg}/{total}')`
结果如下：
`10/7176`
即7176条音频只有10个识别出文字，其他均为空字符串，请问这种情况该如何处理？
