### ISSUE TITLE
RuntimeError: missing value in ASRModel forward()

### ISSUE THREAD

**Issue by dayfinihzy** [wenet-e2e/wenet#2441]
**Issue Description**:
I encountered a RuntimeError while trying to perform inference using a  wenet ASR model trained by my friend loaded with torch.jit.load(). The error message suggests that the argument 'speech_lengths' is missing in the forward() method of ASRModel. When I provide the argument 'speech_lengths', it then prompts me that the argument 'text' is missing. I'm not clear on the meaning of 'Text' and 'text_lengths' in this context.

**Steps to Reproduce**:
Load an audio file using torchaudio and perform necessary pre-processing steps.
Load the wenet ASR model using torch.jit.load() with the provided JIT file path.
Call the model with the pre-processed audio as the input.

**Code** :
```
import torch
import torchaudio

audio_origin = '/root/data/wav/exa.wav' # example wav

def read_audio(path: str, sampling_rate: int = 16000):
    wav, sr = torchaudio.load(path)

    if wav.size(0) > 1:
        wav = wav.mean(dim=0, keepdim=True)

    if sr != sampling_rate:
        transform = torchaudio.transforms.Resample(orig_freq=sr, new_freq=sampling_rate)
        wav = transform(wav)
        sr = sampling_rate

    assert sr == sampling_rate
    return wav.squeeze(0)


wav = read_audio(audio_origin) # read wav
jit_file_path = '/root/data/final.zip'  # the path of jit file
model = torch.jit.load(jit_file_path)
model.eval()
model(wav)
```

**Error**:
The code raises a RuntimeError with the message "missing values for arguments in ASRModel forward()".
```
Traceback (most recent call last):
  File "/root/data/asr_jit.py", line 28, in <module>
    model(wav)
  File "/opt/anaconda3/envs/ASR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/anaconda3/envs/ASR/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
RuntimeError: forward() is missing value for argument 'speech_lengths'. Declaration: forward(__torch__.wenet.transformer.asr_model.ASRModel self, Tensor speech, Tensor speech_lengths, Tensor text, Tensor text_lengths) -> Dict(str, Tensor?)
```

**Environment**:

PyTorch version: 2.2.1
torchaudio version: 2.2.1
CUDA Version: 12.2 
Operating System: CentOS 7

**Additional Information:**
The code for exporting the model is as described in your documentation:
```
script_model = torch.jit.script(model)
script_model.save(os.path.join(args.model_dir, 'final.zip'))
```

I have verified that the audio waveform and the JIT model file exist in the specified paths.I would like to know the meaning of the parameters 'speech_lengths', 'text', and 'text_lengths', as well as whether I am using the method incorrectly. I would appreciate any guidance or suggestions to resolve this issue. Thank you!

**Comment by Mddct** [comment]
plz see: https://github.com/wenet-e2e/wenet/blob/main/wenet/cli/model.py#L82-L86

**Comment by dayfinihzy** [comment]
> plz see: https://github.com/wenet-e2e/wenet/blob/main/wenet/cli/model.py#L82-L86

Thanks for your reply. This link solved my problem. Thanks again!
