### ISSUE TITLE
预训练模型下载不了

### ISSUE THREAD

**Issue by didi222-lqq** [wenet-e2e/wenet#2443]
![image](https://github.com/wenet-e2e/wenet/assets/84363031/677e030e-50a5-4d63-ab34-c717c2912987)
我想下载aishell的两种预训练模型，但是网页打不开

**Comment by didi222-lqq** [comment]
![image](https://github.com/wenet-e2e/wenet/assets/84363031/15196c63-500d-4615-8bb7-7b89b0ee32b9)

**Comment by Mddct** [comment]
<img width="1511" alt="截屏2024-04-07 10 37 44" src="https://github.com/wenet-e2e/wenet/assets/4906435/bf788d03-0f8f-4d4a-9e2c-889c89e8dd34">
<img width="1017" alt="截屏2024-04-07 10 38 06" src="https://github.com/wenet-e2e/wenet/assets/4906435/c336c0d3-0831-42cd-86a5-be6bbe97794b">


可以的

**Comment by didi222-lqq** [comment]
想下载aishell的
![image](https://github.com/wenet-e2e/wenet/assets/84363031/2d264516-3239-4e6b-9bfd-78e1dac4c35d)
还是进不去

**Comment by Mddct** [comment]
先从这里下载吧
https://modelscope.cn/datasets/wenet/wenet_pretrained_models/files

**Comment by didi222-lqq** [comment]
好的，谢谢

**Comment by didi222-lqq** [comment]
请问有微调的程序吗
