### ISSUE TITLE
wenet-whisper-finetune中attention与ctc解码差异很大

### ISSUE THREAD

**Issue by yangsuxia** [wenet-e2e/wenet#2451]
![image](https://github.com/wenet-e2e/wenet/assets/34536059/b3cf370d-cc60-40f3-948f-e9e80c0799b5)
1、使用medium的模型进行finetune，attention的结果和ctc的结果差异这么大正常么？
2、ctc的结果中为什么会出现”�“？我看之前问题中说使用hybridtokenizer解决，这个具体是怎么解决啊？

**Comment by fclearner** [comment]
参考这个：https://github.com/wenet-e2e/wenet/issues/2308

**Comment by yangsuxia** [comment]
嗯嗯，之前就看到这个了，说是正常现象，说是hybrid tokenizer解决，我不太明白这个是什么意思，具体怎么做

**Comment by fclearner** [comment]
说白了，就是因为你的微调数据量少了，ctc训练不充分，所以星辰大佬的意思是ctc另外搞一个词表，因为本质上ctc和attention_decoder是两个不同的loss，可以不使用同一份词表，loss计算的时候再加权就好了，不过看issue，代码改动量有点大，所以这个方案其实是没搞完的，需要自己diy

**Comment by yangsuxia** [comment]
哦哦，好的，明白了，谢谢哈
