### ISSUE TITLE
Support for training on single accelerator?

### ISSUE THREAD

**Issue by MengqingCao** [wenet-e2e/wenet#2454]
请问wenet是否有支持单卡训练的计划？现在的版本似乎只支持多卡分布式训练

**Comment by Mddct** [comment]
分布式可以为单卡

**Comment by MengqingCao** [comment]
> 分布式可以为单卡

OK 感谢回复，因为我在单卡直接跑 aishell/s0 的 run.sh 脚本时候碰到了 `torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 1250419) of binary: /home/root/miniconda
3/envs/wenet/bin/python` 的报错，误以为不支持单卡。

**Comment by Mddct** [comment]
gpu nums 改为1， prefetch和numbworker 改小些试试

**Comment by MengqingCao** [comment]
> gpu nums 改为1， prefetch和numbworker 改小些试试

赞，有效解决问题:）
