### ISSUE TITLE
paraformer-8k模型的问题

### ISSUE THREAD

**Issue by dospeech** [wenet-e2e/wenet#2461]
paraformer模型可以下载16k的模型，如果下载8k的“speech_paraformer_asr_nat-zh-cn-8k-common-vocab8358-tensorflow1”模型
 ，只改下面的模型名称好像不支持吧（改成8k名称后，链接打不开）？
 
url = "https://www.modelscope.cn/api/v1/"\
        "models/iic/"\
        "speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-pytorch"\
        "/repo?Revision={}&FilePath=".format(version) + name

**Comment by Mddct** [comment]
直接去modelscope里边下载就行
