### ISSUE TITLE
paraformer模型推理报错

### ISSUE THREAD

**Issue by wanghanyang123** [wenet-e2e/wenet#2465]
**Describe the bug**

执行
`python transcribe.py  -l chinese ../../../faster-whisper/1.wav --paraformer`
结果正常

但执行
`python transcribe.py  -l chinese ../../../faster-whisper/1.wav --paraformer -t`
结果报错

具体过程如图，增加 -t 导致报错了
![image](https://github.com/wenet-e2e/wenet/assets/32231771/fd8e6e4e-f5a7-4e1a-958c-4df52c5e5bca)

**Comment by Mddct** [comment]
这个音频发便给一下吗 这边debug下

**Comment by wanghanyang123** [comment]
@Mddct 
[1.zip](https://github.com/wenet-e2e/wenet/files/14940534/1.zip)

**Comment by wanghanyang123** [comment]
同时部署发现如果使用paraformer的模型，热词 “--context_path” 也无效；如果使用默认的模型，时间戳和热词使用都是正常的。

**Comment by Mddct** [comment]
热词还没有支持paraformer， 热词是支持ctc测的
