### ISSUE TITLE
meet a question when running android to compute rtf

### ISSUE THREAD

**Issue by tianmala** [wenet-e2e/wenet#2468]
I run the commands according to readme.md about android
Step 2, ./gradlew build

but I don't find the directory app/.cxx/cmake/release in Step 3.  I don't know how to solve it

Step 3, push your binary and the dynamic library to /data/local/tmp as follows:
adb push app/.cxx/cmake/release/arm64-v8a/decoder_main /data/local/tmp

**Comment by pengzhendong** [comment]
Please try:
``` bash
./gradlew assembleRelease
```
