### ISSUE TITLE
有没有能部署在android的Runtime Model支持中英文混合识别的模型呀，现在只有中文或者英文的

### ISSUE THREAD

**Issue by adi-hld** [wenet-e2e/wenet#2487]
https://github.com/wenet-e2e/wenet/blob/main/docs/pretrained_models.md 这个预训练模型只有中文或英文的
有没有能部署在android的Runtime Model支持中英文混合识别的模型呀

**Comment by csukuangfj** [comment]
可以试试下面这个 APK

https://github.com/k2-fsa/sherpa-onnx/releases/download/v1.9.19/sherpa-onnx-1.9.19-arm64-v8a-bilingual-en-zh.apk
