### ISSUE TITLE
Convert Whisper-wenet to  ONNX

### ISSUE THREAD

**Issue by signal1234** [wenet-e2e/wenet#2500]
I am converting the  wenet converted  whisper model to ONNX, using the below command, but  it cannot proceed.
exp=./wenet/whisper/whisper-wenet
model=wenet_whisper.pt
onnx_dir=onnx-whisper-model
python -m wenet.bin.export_onnx_cpu \
  --config $exp/train.yaml \
  --checkpoint $exp/$model \
  --chunk_size -1 \
  --output_dir $onnx_dir \
  --num_decoding_left_chunks -1

2024-04-23 08:39:05,440 INFO [Rank 0] Checkpoint: loading from checkpoint ./wenet/whisper/whisper-wenet/wenet_whisper.pt
2024-04-23 08:39:11,105 INFO missing tensor: decoder.output_layer.weight
2024-04-23 08:39:11,105 INFO missing tensor: decoder.output_layer.bias
2024-04-23 08:39:11,105 INFO missing tensor: ctc.ctc_lo.weight
2024-04-23 08:39:11,105 INFO missing tensor: ctc.ctc_lo.bias
{'accum_grad': 4, 'cmvn': None, 'cmvn_conf': {'cmvn_file': None, 'is_json_cmvn': None}, 'ctc_conf': {'ctc_blank_id': 50363}, 'dataset': 'asr', 'dataset_conf': {'batch_conf': {'batch_size': 26, 'batch_type': 'dynamic', 'max_frames_in_batch': 12000}, 'feats_type': 'log_mel_spectrogram', 'filter_conf': {'max_length': 3000, 'min_length': 0, 'token_max_length': 448, 'token_min_length': 1}, 'language_conf': {'limited_langs': ['zh']}, 'log_mel_spectrogram_conf': {'hop_length': 160, 'n_fft': 400, 'num_mel_bins': 128, 'padding': 0}, 'resample_conf': {'resample_rate': 16000}, 'shuffle': True, 'shuffle_conf': {'shuffle_size': 1500}, 'sort': True, 'sort_conf': {'sort_size': 500}, 'spec_aug': True, 'spec_aug_conf': {'max_f': 10, 'max_t': 50, 'num_f_mask': 2, 'num_t_mask': 2}, 'spec_sub': True, 'spec_sub_conf': {'max_t': 30, 'num_t_sub': 3}, 'spec_trim': False, 'speed_perturb': False}, 'decoder': 'transformer', 'decoder_conf': {'activation_type': 'gelu', 'attention_heads': 20, 'dropout_rate': 0.1, 'gradient_checkpointing': True, 'input_layer': 'embed_learnable_pe', 'key_bias': False, 'linear_units': 5120, 'normalize_before': True, 'num_blocks': 32, 'positional_dropout_rate': 0.1, 'self_attention_dropout_rate': 0.0, 'src_attention': True, 'src_attention_dropout_rate': 0.0, 'tie_word_embedding': True, 'use_output_layer': True}, 'encoder': 'transformer', 'encoder_conf': {'activation_type': 'gelu', 'attention_dropout_rate': 0.0, 'attention_heads': 20, 'dropout_rate': 0.1, 'gradient_checkpointing': True, 'input_layer': 'conv1d2', 'key_bias': False, 'linear_units': 5120, 'normalize_before': True, 'num_blocks': 32, 'output_size': 1280, 'pos_enc_layer_type': 'abs_pos_whisper', 'positional_dropout_rate': 0.1, 'static_chunk_size': -1, 'use_dynamic_chunk': False, 'use_dynamic_left_chunk': False}, 'grad_clip': 5, 'input_dim': 128, 'log_interval': 100, 'max_epoch': 100, 'model': 'whisper', 'model_conf': {'ctc_weight': 0.3, 'length_normalized_loss': False, 'lsm_weight': 0.1}, 'optim': 'adam', 'optim_conf': {'lr': 0.0005}, 'output_dim': 51866, 'scheduler': 'warmuplr', 'scheduler_conf': {'warmup_steps': 12000}, 'tokenizer': 'whisper', 'tokenizer_conf': {'bpe_path': None, 'is_multilingual': True, 'non_lang_syms_path': None, 'num_languages': 100, 'special_tokens': {'eot': 50257, 'no_speech': 50363, 'no_timestamps': 50364, 'sot': 50258, 'sot_prev': 50362, 'timestamp_begin': 50365, 'transcribe': 50360, 'translate': 50359}, 'split_with_space': False, 'symbol_table_path': None}, 'init_infos': {}}
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/work/projects/WENET/wenet/wenet/bin/export_onnx_cpu.py", line 470, in <module>
    main()
  File "/home/ubuntu/work/projects/WENET/wenet/wenet/bin/export_onnx_cpu.py", line 426, in main
    model, configs = init_model(args, configs)
  File "/home/ubuntu/work/projects/WENET/wenet/wenet/utils/init_model.py", line 189, in init_model
    model.decoder.tie_or_clone_weights(jit_mode=args.jit)
AttributeError: 'Namespace' object has no attribute 'jit'

Wenet ver:  Latest  github version
PyTorch ver:
2.2.0+cpu

**Comment by xingchensong** [comment]
try this https://github.com/wenet-e2e/wenet/pull/2501
