### ISSUE TITLE
K2 hlg 解码问题请教

### ISSUE THREAD

**Issue by mahuichao** [wenet-e2e/wenet#2502]
请问目前wenet-main中，对于k2 的hlg解码，也就是aishell/s0/run.sh中的第8阶段是否支持了呢。

我查看源码（以tranformer模型为例子），在init_model.py中，在选取类的时候，并没有走k2_model，而是走的asr_model（从yaml中读取而来），如下：
![image](https://github.com/wenet-e2e/wenet/assets/12440741/910e93b5-fa1f-478c-a431-72a3c9d3eb58)
且在对应的recognize.py中，有三个TODO，有一个对应K2的解码，所以这里很是疑惑，求解一下。
![image](https://github.com/wenet-e2e/wenet/assets/12440741/f33b483d-1318-4dd2-b2dd-c3b097b5b8ff)

**Comment by Mddct** [comment]
需要自己改下，初始化model为k2 并且 model.decode 直接调用 model.hlgxxx
