### ISSUE TITLE
Can paraformer be inferenced with gpu and runtime ?

### ISSUE THREAD

**Issue by shatealaboxiaowang** [wenet-e2e/wenet#2527]
Hi,

    When will gpu export of paraformer be supported and inference can be done using the runtime ?
    Looking forward for your replay.
thx!

**Comment by Mddct** [comment]
Sorry, we don’t have enough time to support the runtime paraformer
now, and we look forward to the community’s PR.


github-actions[bot] ***@***.***> 于2024年7月22日周一 09:35写道：
