### ISSUE TITLE
How can I set beam_size in Android runtime?

### ISSUE THREAD

**Issue by Dan1chu** [wenet-e2e/wenet#2533]
Now I'm testing u2++ conformer model in mobile phone, with wenet android runtime.

In c++ runtime, I can simply change the decoding option "--beam <beam_size>" 

But in android runtime, there is no option for custom beam_size.

could you give me an idea?

thank you.

**Comment by robin1001** [comment]
please see https://github.com/wenet-e2e/wenet/blob/main/runtime/android/app/src/main/cpp/wenet.cc#L59.

You can add it by 

```
  decode_config->ctc_wfst_search_opts.nbest = FLAGS_nbest;
  decode_config->ctc_prefix_search_opts.first_beam_size = FLAGS_nbest;
  decode_config->ctc_prefix_search_opts.second_beam_size = FLAGS_nbest;
```

**Comment by Dan1chu** [comment]
Thank you!
