### ISSUE TITLE
训练的模型后验为空的问题

### ISSUE THREAD

**Issue by yangsuxia** [wenet-e2e/wenet#2537]
单独使用6000w条基础数据训练模型没有问题，单独使用1200w条新增数据训练模型没有问题，但是将这些数据合在一起之后训练的模型loss值很高，看音频后验，全部都是空的，可能会是什么问题呢？

**Comment by Dan1chu** [comment]
Try reducing learning rate to 1/2, or increasing accum_grad to twice from current configuration.
