### ISSUE TITLE
paraformer模型训练报错

### ISSUE THREAD

**Issue by didi222-lqq** [wenet-e2e/wenet#2542]
在执行完以下命令后
![image](https://github.com/wenet-e2e/wenet/assets/84363031/1c81e7b3-543c-41b4-939b-264e56c49bc1)
把词典替换成自己的，在训练配置文件里修改参数对应自己的词典
![image](https://github.com/wenet-e2e/wenet/assets/84363031/135b3702-64e2-4b5d-813b-a184789c2807)

执行run.sh第0步报错
[rank5]: Traceback (most recent call last):
[rank5]:   File "/data/run01/scz0arv/lindaodi/wenet2/wenet/examples/aishell/paraformer/wenet/bin/train.py", line 178, in <module>
[rank5]:     main()
[rank5]:   File "/HOME/scz0arv/.conda/envs/wenet2/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
[rank5]:     return f(*args, **kwargs)
[rank5]:   File "/data/run01/scz0arv/lindaodi/wenet2/wenet/examples/aishell/paraformer/wenet/bin/train.py", line 94, in main
[rank5]:     model, configs = init_model(args, configs)
[rank5]:   File "/data/run01/scz0arv/lindaodi/wenet2/wenet/wenet/utils/init_model.py", line 174, in init_model
[rank5]:     infos = load_checkpoint(model, args.checkpoint)
[rank5]:   File "/data/run01/scz0arv/lindaodi/wenet2/wenet/wenet/utils/checkpoint.py", line 31, in load_checkpoint
[rank5]:     missing_keys, unexpected_keys = model.load_state_dict(checkpoint,
[rank5]:   File "/HOME/scz0arv/.conda/envs/wenet2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
[rank5]:     raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
[rank5]: RuntimeError: Error(s) in loading state_dict for Paraformer:
[rank5]: 	size mismatch for decoder.output_layer.weight: copying a param with shape torch.Size([8404, 512]) from checkpoint, the shape in current model is torch.Size([5077, 512]).
[rank5]: 	size mismatch for decoder.output_layer.bias: copying a param with shape torch.Size([8404]) from checkpoint, the shape in current model is torch.Size([5077]).
[rank5]: 	size mismatch for ctc.ctc_lo.weight: copying a param with shape torch.Size([8404, 512]) from checkpoint, the shape in current model is torch.Size([5077, 512]).
[rank5]: 	size mismatch for embed.weight: copying a param with shape torch.Size([8404, 512]) from checkpoint, the shape in current model is torch.Size([5077, 512]).

是还有地方没改到吗

**Comment by Mddct** [comment]
词典需要和模型维度保持一致

didi222-lqq ***@***.***> 于2024年5月29日周三 11:57写道：
