### ISSUE TITLE
Does the wenetruntime package still exist?

### ISSUE THREAD

**Issue by songjie1121** [wenet-e2e/wenet#2543]
Can I ask the author if the wenetruntime package is removed now? I keep getting an error when I install wenetruntime on pip3 and I can't search for the package on pypi

**Comment by Mddct** [comment]
wenetruntime is deprecated， plz use wenet cli

songjie1121 ***@***.***> 于2024年5月29日周三 10:23写道：

**Comment by songjie1121** [comment]
OK，thank you very much
