### ISSUE TITLE
Rank 1 failed to pass monitoredBarrier in 1200000 ms

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#2552]
Hi

When training with DeepSpeed, an error occurred: "Rank 1 failed to pass monitoredBarrier in 30000 ms." When I changed the timeout to 1200s, the same timeout error was reported. What could be causing this?

I am using NCCL, but it's reporting a GLOO timeout here.

err
---
2024/06/05 12:08:28 [/opt/conda/conda-bld/pytorch_1702400366987/work/third_party/gloo/gloo/transport/tcp/unbound_buffer.cc:81] Timed out waiting 30000ms for recv operation to complete

cfg
---
num_works=2
prefetch=100
shards data，http read

**Comment by xingchensong** [comment]
http might not working correctly，you should first debug http connection

**Comment by srdfjy** [comment]
I used two machines (each with a single V100) for training and executed wget shards_000000000.tar on both machines; the HTTP download was normal.

download logs
---
![image](https://github.com/wenet-e2e/wenet/assets/66103286/532aeb8c-668d-4f2b-ad6c-314c37a2f16e)

train logs
---
![image](https://github.com/wenet-e2e/wenet/assets/66103286/30667b02-e554-45de-b3b3-04ee8d3c2f49)

**Comment by xingchensong** [comment]
Could u try torch_ddp?

**Comment by srdfjy** [comment]
The troch_ddp training is normal.

Is it because the log mentions that it is caused by load imbalance? but I see that the code in deepspeed has already handled this situation through wenet_join.

logs
-
"2024/06/06 12:28:05 2024-06-06 12:28:05,934 INFO Detected uneven workload distribution: [Rank 0]: Rank 1 failed to pass monitoredBarrier in 30000 ms",

**Comment by srdfjy** [comment]
hi @xingchensong 

Based on your response here, this should be normal for me, but I don't know why this error would occur.

https://github.com/wenet-e2e/wenet/issues/2266#issuecomment-1886436064

**Comment by xingchensong** [comment]
how many tars in your dataset? For small dataset, say only 2 tars, it is normal, timeout means you reach the end of epoch

**Comment by srdfjy** [comment]
> how many tars in your dataset? For small dataset, say only 2 tars, it is normal, timeout means you reach the end of epoch

I have used 34 Tars for fine-tuning, and currently, the entire training can proceed normally. If this is normal, then I will ignore this log for now.

**Comment by xingchensong** [comment]
you dataset is small, this is normal

**Comment by srdfjy** [comment]
> you dataset is small, this is normal

THX!
