### ISSUE TITLE
现在是否有多语种wenet模型？

### ISSUE THREAD

**Issue by ykk648** [wenet-e2e/wenet#2555]

**Comment by Mddct** [comment]
木有开源的

**Comment by ykk648** [comment]
> 木有开源的

如果我用1000h英文数据finetune multi-cn这个wenet模型，是否就是多语种模型？ 因为我是TTS训练0基础，想评估一下这里面的工作量。

**Comment by Mddct** [comment]
multi-cn 这个模型的建模单元不太合适， 需要自己改一下， 并且训练数据较少

**Comment by srdfjy** [comment]
> 木有开源的

如果想训练一个多语种的是不是最好加个语种loss，要不把所有的数据混合在一起训感觉效果不会太好。
