### ISSUE TITLE
wenet --language chinese audio.wav

### ISSUE THREAD

**Issue by icestoneking** [wenet-e2e/wenet#2559]
TypeError: integer argument expected, got float

**Comment by azraelkuan** [comment]
@Mddct https://github.com/wenet-e2e/wenet/blob/dec409bf9c6fd6280fb04abc02ea7470ff6114b7/wenet/cli/model.py#L172
there is a parameters error in this line

**Comment by XiHenSuper** [comment]
@Mddct @azraelkuan 
 我也碰到这个问题，请问怎么解决？
```model = wenet.load_model('chinese')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wenet/wenet/cli/model.py", line 172, in load_model
    model = Model(model_dir, beam, context_path, context_score)
  File "wenet/wenet/cli/model.py", line 54, in __init__
    self.context_graph = ContextGraph(context_path,
  File "wenet/wenet/utils/context_graph.py", line 130, in __init__
    self.context_list = tokenize(context_list_path, symbol_table,
  File "wenet/wenet/utils/context_graph.py", line 35, in tokenize
    with open(context_list_path, "r") as fin:
TypeError: expected str, bytes or os.PathLike object, not float```

**Comment by icestoneking** [comment]
> @Mddct @azraelkuan 我也碰到这个问题，请问怎么解决？ context_list_path这个文件是什么文件？有示例吗？
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "wenet/wenet/cli/model.py", line 172, in load_model
>     model = Model(model_dir, beam, context_path, context_score)
>   File "wenet/wenet/cli/model.py", line 54, in __init__
>     self.context_graph = ContextGraph(context_path,
>   File "wenet/wenet/utils/context_graph.py", line 130, in __init__
>     self.context_list = tokenize(context_list_path, symbol_table,
>   File "wenet/wenet/utils/context_graph.py", line 35, in tokenize
>     with open(context_list_path, "r") as fin:
> TypeError: expected str, bytes or os.PathLike object, not float
> ```

楼上的解决方案是对的，参数没对齐。model = Model(model_dir, beam, context_path, context_score)

**Comment by Mddct** [comment]
plz see https://github.com/wenet-e2e/wenet/pull/2563
