### ISSUE TITLE
Android compile Error

### ISSUE THREAD

**Issue by wgfi110** [wenet-e2e/wenet#2560]
**Describe the bug**
[CXX1306] D:\workspace\wenet\runtime\android\app\src\main\cpp\CMakeLists.txt debug|arm64-v8a : CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FBJNI_LIBRARY
    linked by target "decoder" in directory D:/workspace/wenet/runtime/android/app/src/main/cpp/decoder
PYTORCH_LIBRARY
    linked by target "decoder" in directory D:/workspace/wenet/runtime/android/app/src/main/cpp/decoder

**To Reproduce**
1. Environment:
Android Studio Hedgehog | 2023.1.1 Patch 2
Build #AI-231.9392.1.2311.11330709, built on January 19, 2024
Runtime version: 17.0.7+0-b2043.56-10550314 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 20
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false

Android SDK Build-Tools: 30.0.3
NDK: 22.0.7026061
Android SDK Command-line Tools: 4.0.0
CMake: 3.10.2.4988404
Android Emulator
Android SDK Platform-tool

Operation:Win10
Wenet: newest master

**Comment by robin1001** [comment]
@pengzhendong would you please help on the problem?

**Comment by zqyp** [comment]
![image](https://github.com/user-attachments/assets/33a00912-3f9c-4ca4-b179-7d2c177362ff)
试着在 buid.gradle 中加 nameapace

**Comment by zqyp** [comment]
![image](https://github.com/user-attachments/assets/ed8cbc71-2b39-4dc8-96ba-fac4e7480431)
试着在build.gradle 中加上 namespace

**Comment by jprobichaud** [comment]
I'm getting the same issue. It is also reported in #2615

```
./gradlew --version

------------------------------------------------------------
Gradle 7.5
------------------------------------------------------------

Build time:   2022-07-14 12:48:15 UTC
Revision:     c7db7b958189ad2b0c1472b6fe663e6d654a5103

Kotlin:       1.6.21
Groovy:       3.0.10
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.24 (Ubuntu 11.0.24+8-post-Ubuntu-1ubuntu322.04)
OS:           Linux 6.9.3-76060903-generic amd64
```

**Comment by ospeech** [comment]
windows下的编译可以这么解：
把pytorch_android-1.13.0.aar解压后，把jnit放在src/main下，并把headers放要jni里面，然后在更改decoder/CMakeLists.txt如下：
`
if(ANDROID)
  set(JNI_LIBS_DIR "D:/wenet/runtime/android/app/src/main/jniLibs")
  #拼接当前架构的库路径（如 arm64-v8a）
  set(TORCH_LIB_DIR "${JNI_LIBS_DIR}/${ANDROID_ABI}")

  #强制指定库文件路径（避免 find_library 查找失败）
  set(PYTORCH_LIBRARY "${TORCH_LIB_DIR}/libpytorch_jni.so")
  set(FBJNI_LIBRARY "${TORCH_LIB_DIR}/libfbjni.so")

  #检查库是否存在
  if(NOT EXISTS ${PYTORCH_LIBRARY})
    message(FATAL_ERROR "libpytorch_jni.so 未找到！路径: ${PYTORCH_LIBRARY}")
  endif()
  if(NOT EXISTS ${FBJNI_LIBRARY})
    message(FATAL_ERROR "libfbjni.so 未找到！路径: ${FBJNI_LIBRARY}")
  endif()

  target_include_directories(utils PUBLIC ${JNI_LIBS_DIR}/headers)
  target_include_directories(utils PUBLIC ${JNI_LIBS_DIR}/headers/torch/csrc/api/include)
  #链接库
  target_link_libraries(decoder PUBLIC ${PYTORCH_LIBRARY} ${FBJNI_LIBRARY})
`
openfst也是同样的思路。代码比较老了，又没有维护，遇到问题问AI吧，最终都能解。
下面是我编译出的最终的呈现：

![Image](https://github.com/user-attachments/assets/81c9f669-0f7a-469d-a168-788eb467d342)
