### ISSUE TITLE
libtorch decoder latency differs in official docker image and locally build

### ISSUE THREAD

**Issue by anjul1008** [wenet-e2e/wenet#2564]
I have tested last year build websocket [docker image](https://hub.docker.com/r/wenetorg/wenet-mini) decoder and locally compiled latest decoder. i used same docker container by replacing newly compiled websocket binary.
I found 35-40% higher latency with latest compiled decoder.

It can be due to some addition parameter passed while compiling, but didn't find any specify parameter in cmake file which can lead to higher latency.

thank you in advance, any help would be appreciated.

**Comment by xingchensong** [comment]
there might be a warmup issue

**Comment by xingchensong** [comment]
https://github.com/wenet-e2e/wenet/issues/2163#issuecomment-1829688878

**Comment by anjul1008** [comment]
the model warmup properly, it's the same after more than 1000 iterations.

**Comment by xingchensong** [comment]
its strange ，i have no idea

**Comment by xingchensong** [comment]
cc @robin1001

**Comment by anjul1008** [comment]
@robin1001 am i missing any addition parameter ?
