### ISSUE TITLE
ios pod install error

### ISSUE THREAD

**Issue by hanboys87** [wenet-e2e/wenet#2567]
I encounter an error during pod install when setting up an iOS app. Initially, I faced issues with the latest CMake version, so I reverted to version 3.14, and the following command executed successfully:

cd runtime/ios/build
cmake .. -G Xcode -DTORCH=ON -DONNX=OFF -DIOS=ON -DGRAPH_TOOLS=OFF -DBUILD_TESTING=OFF -DCMAKE_TOOLCHAIN_FILE=../toolchains/ios.toolchain.cmake -DPLATFORM=OS64 -DENABLE_BITCODE=FALSE

**However, when I run pod install afterwards, I encounter the following error:**

Could not automatically select an Xcode workspace. Specify one in your Podfile like so:
 workspace 'path/to/Workspace.xcworkspace'

I'm wondering if I need to modify the Podfile. I performed this in the directory wenet/runtime/ios/build. Additionally, after running pod install, should I open the project file located at wenet/runtime/ios/WenetDemo/WenetDemo.xcodeproj?

**Comment by robin1001** [comment]
@Ma-Dan，any idea?
