### ISSUE TITLE
export wenet_paraformer.pt to onnx fail

### ISSUE THREAD

**Issue by 946166920** [wenet-e2e/wenet#2568]
基于wenet-main，
<img width="575" alt="image" src="https://github.com/wenet-e2e/wenet/assets/49601492/c83ec5eb-3a9f-4530-8b94-78a39fee046e">
使用wenet.bin.export_onnx_cpu转换
<img width="964" alt="image" src="https://github.com/wenet-e2e/wenet/assets/49601492/bf10f508-5a14-4e75-93e1-12302587c442">
报了如图所示的shape错误，请问怎么处理？

**Comment by Mddct** [comment]
目前还不支持导出onnx

**Comment by rainskyfyy** [comment]
> 目前还不支持导出onnx

有支持paraformer导出onnx的计划吗，或者说一下需要如何实现
