### ISSUE TITLE
NPU Error

### ISSUE THREAD

**Issue by yushanyong** [wenet-e2e/wenet#2570]
Conformer模型使用Paraformer的tokenizer，会导致grad_norm NaN，进而NPU会报Inner Error，但使用GPU训练一切正常
![image](https://github.com/wenet-e2e/wenet/assets/30676802/df29c1dd-2a7c-42ac-ac4f-c4dfc69bce76)

### 复现方式
- 拉最新代码
- 修改wenet/examples/aishell/s0/run_npu.sh 下面 conf/train_conformer.yaml，将tokenizer改成paraformer
```
tokenizer: paraformer
tokenizer_conf:
  seg_dict_path: exp/paraformer/large/seg_dict
  special_tokens:
    <blank>: 0
    <eos>: 2
    <sos>: 1
    <unk>: 8403
  symbol_table_path: exp/paraformer/large/units.txt
```
- 直接运行run_npu.sh

**Comment by robin1001** [comment]
@MengqingCao, 麻烦帮忙看一下

**Comment by MengqingCao** [comment]
@yushanyong hello 我没有复现出这个问题，从当前的log不能定位具体哪个算子引起的，如果确认输入数据没问题，可以尝试升级下cann toolkit和kernels包版本

我的环境：
**CANN toolkit/kernels**：8.0.RC2.alpha003
**torch/torch-npu**: 2.2.0
**Python**: 3.10

**Comment by yushanyong** [comment]
我的环境是这个，必现：
CANN toolkit/kernels：8.0.RC1
torch/torch-npu: 2.1.0
Python: 3.10

我升级试一下

**Comment by MengqingCao** [comment]
> 我的环境是这个，必现： CANN toolkit/kernels：8.0.RC1 torch/torch-npu: 2.1.0 Python: 3.10
> 
> 我升级试一下

请问问题解决了吗

**Comment by yushanyong** [comment]
> > 我的环境是这个，必现： CANN toolkit/kernels：8.0.RC1 torch/torch-npu: 2.1.0 Python: 3.10
> > 我升级试一下
> 
> 请问问题解决了吗

还没有试，等有时间了试一下
