### ISSUE TITLE
微调模型  build apk 闪退 报错 

### ISSUE THREAD

**Issue by LiSongRan** [wenet-e2e/wenet#2573]

**Comment by zqyp** [comment]
![20240716-120359](https://github.com/user-attachments/assets/237842eb-82f9-437f-9c83-4664c51eb695)
我尝试用微调前的模型 wenetspeech_u2pp_conformer_libtorch_quant，app 也会出现闪退，类似的错误

**Comment by zqyp** [comment]
![image](https://github.com/user-attachments/assets/8e0689d5-b241-4e52-b59c-a4492253be5d)
我也遇到了类似的问题，使用的是微调前的模型 wenetspeech_u2pp_conformer_libtorch_quant

**Comment by LiSongRan** [comment]
@zqyp 有解决吗 是不是torch版本有问题？

**Comment by zqyp** [comment]
感觉是torch 版本的问题，升级到2.1.0后，会有一些奇怪的编译错误，不知道怎么解决

**Comment by zqyp** [comment]
> 感觉是torch 版本的问题，升级到2.1.0后，会有一些奇怪的编译错误，不知道怎么解决

@LiSongRan 多次编译模型不能覆盖，需要卸载上一次的apk 重新编译，在这个基础上测试了几个模型，通过 whisper转成 final.zip 的模型都会有这个错，只有官方的 wenetspeech_u2pp_conformer_libtorch_quant 模型可以正常运行，不知道是模型转换出错，还是android 没有适配其他模型

**Comment by zqyp** [comment]
> > 感觉是torch 版本的问题，升级到2.1.0后，会有一些奇怪的编译错误，不知道怎么解决
> 
> @LiSongRan 多次编译模型不能覆盖，需要卸载上一次的apk 重新编译，在这个基础上测试了几个模型，通过 whisper转成 final.zip 的模型都会有这个错，只有官方的 wenetspeech_u2pp_conformer_libtorch_quant 模型可以正常运行，不知道是模型转换出错，还是android 没有适配其他模型

@xingchensong 你好！我通过convert_whisper_to_wenet_config_and_ckpt.py、export_jit.py这两个脚本将whisper 模型转成final.zip, 在android 端会出现torch 算子不支持的情况，请问这个该怎么解决呢？

**Comment by LiSongRan** [comment]
@zqyp  有解决吗 @megazone87 @placebokkk @veelion

**Comment by LiSongRan** [comment]
已经解决

**Comment by PineJuneYang** [comment]
> 已经解决
你好 我安卓工程中升级libtorch到2.1.0之后，加载wenet.so又有新的问题，请问怎么解决的呢？
 Process: com.mobvoi.wenet, PID: 9244
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN5torch3jit4loadERKNSt6__ndk112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEN3c108optionalINSA_6DeviceEEE" referenced by "/data/app/~~EpdC9vdajl2qVh_uGxRYCg==/com.mobvoi.wenet-BGm4nZS9GLD8ZVTlWmi4AA==/lib/arm64/libwenet.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
        at java.lang.System.loadLibrary(System.java:1661)
        at com.mobvoi.wenet.Recognize.<clinit>(Recognize.java:6)
        at com.mobvoi.wenet.MainActivity.onCreate(MainActivity.java:94)

![image](https://github.com/user-attachments/assets/ea8e55a1-ecf3-4668-82a9-99912a381e8a)
