### ISSUE TITLE
pip install 遗漏了一些包

### ISSUE THREAD

**Issue by selaselah** [wenet-e2e/wenet#2581]
**Describe the bug**
pip install 安装后丢失了一些包。
应该是这些包没有 __init__.py 导致的

**To Reproduce**
import init_model 就能复现
```text
  File "xxx.py", line 17, in init_model
    from wenet.utils.init_model import init_model
  File "xxx/lib/python3.10/site-packages/wenet/utils/init_model.py", line 18, in <module>
    from wenet.finetune.lora.utils import mark_only_lora_as_trainable
ModuleNotFoundError: No module named 'wenet.finetune'
```

**Desktop (please complete the following information):**
 - OS: Linux

**Comment by Mddct** [comment]
欢迎题pr

**Comment by fclearner** [comment]
加init.py就能解决吗，我这边没遇到这个问题

**Comment by selaselah** [comment]
原因是在 `setup.py` 里
```python
    packages=find_packages(),
```
这个 `find_packages()` 是通过检查 `__init__.py` 来定位包的，所以没有 `__init__.py` 就不会加入到 packages 里，安装时就会丢失。
有的人使用正常的原因，我猜测是通过类似 `pip install -e .`  的命令安装的。这时候整个文件夹会软链过去，所以不会出问题。
---
我不提pr的原因是丢失的文件太多的，我检查代码发现有的文件夹里有 py 文件，但是没有使用。并不知道这些文件的存在意图，所以还是维护者确认下比较好。

**Comment by fclearner** [comment]
了解了，后面补一个

**Comment by Ying9712** [comment]
那请问这个问题怎么解决呀？

**Comment by fclearner** [comment]
> 那请问这个问题怎么解决呀？

你还有碰到类似的问题吗，最新的代码我已经加了__init__.py了

**Comment by Ying9712** [comment]
谢谢您的回复，问题解决啦。
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Sep 2, 2024 01:54 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [wenet-e2e/wenet] pip install 遗漏了一些包 (Issue #2581)

&nbsp;



  
那请问这个问题怎么解决呀？
  
你还有碰到类似的问题吗，最新的代码我已经加了__init__.py了

**Comment by Mddct** [comment]
最新的代码 应该是可以的
