### ISSUE TITLE
请问大佬，如果想拿wenet encoder的结果去做下游任务，怎么做呢？

### ISSUE THREAD

**Issue by anliyuan** [wenet-e2e/wenet#2601]
请问大佬，如果想拿wenet encoder的结果去做下游任务，怎么做呢？

**Comment by lordlxh** [comment]
同问

**Comment by Mddct** [comment]
直接forward拿embeding

**Comment by lordlxh** [comment]
> 直接forward拿embeding

感谢你的回答，请问可以具体展开讲一下嘛，我这边用model.forward_encoder_chunk(feats, 0, -1)得到的encoder_out最后一个维度是512，但是我看encoder的output_size是256，感觉得到的encoder_out最后一个维度应该是256，我是不是搞错了一个函数拿embeding？
