### ISSUE TITLE
【提问】需要一个char+bpe联合建模时tokenizer的yaml配置

### ISSUE THREAD

**Issue by xIaott-s** [wenet-e2e/wenet#2613]
我按照multi_cn中的步骤构建了lang_char.txt，但是训练那一步的--symbol_table和--bpe_model跟最新的代码已经不兼容了

**Comment by Mddct** [comment]
参考 aishell 里边的配置， 目前吧这些放到yaml里边的tokenizer的path里了

**Comment by xIaott-s** [comment]
类似下面这样么
tokenizer: bpe
tokenizer_conf:
  symbol_table_path: xxx
  split_with_space: false
  bpe_path: xxx

**Comment by Mddct** [comment]
是 顺便提个pr 修一下

**Comment by xIaott-s** [comment]
ok，thks.
