### ISSUE TITLE
在github中使用action 编译runtime报错

### ISSUE THREAD

**Issue by Sail-Ocean** [wenet-e2e/wenet#2615]
将wenet fork到我自己的仓库中，点击github中的action， 然后点击Build Windows Runtime, run workflow , 报错“Process completed with exit code 1.” 请问这是什么问题，如何解决呢

**Comment by robin1001** [comment]
因人力问题，Windows 的 Runtime 现在基本处于不维护的状态了，推荐使用 linux Runtime。

**Comment by baixf-tk** [comment]
Build Android APK & Binary 在build with gradle时也报错
`FAILURE: Build failed with an exception.
* What went wrong:
> Task :app:configureCMakeRelWithDebInfo[arm64-v8a] FAILED
Execution failed for task ':app:configureCMakeRelWithDebInfo[arm64-v8a]'.
C/C++: CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> [CXX1429] error when building with cmake using /home/runner/work/wenet/wenet/runtime/android/app/src/main/cpp/CMakeLists.txt: -- Detecting CXX compiler ABI info
C/C++: Please set them or make sure they are set and tested correctly in the CMake files:
C/C++: FBJNI_LIBRARY
C/C++:     linked by target "decoder" in directory /home/runner/work/wenet/wenet/runtime/android/app/src/main/cpp/decoder
C/C++: PYTORCH_LIBRARY
C/C++:     linked by target "decoder" in directory /home/runner/work/wenet/wenet/runtime/android/app/src/main/cpp/decoder
C/C++: CMake Generate step failed.  Build files cannot be regenerated correctly.
> Task :app:processReleaseManifestForPackage
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.5/userguide/command_line_interface.html#sec:command_line_warnings
13 actionable tasks: 13 executed
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/local/lib/android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/local/lib/android/sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Configuring done
  -- Generating done
  
  C++ build system [configure] failed while executing:
      /usr/local/lib/android/sdk/cmake/3.18.1/bin/cmake \
        -H/home/runner/work/wenet/wenet/runtime/android/app/src/main/cpp \
        -DCMAKE_SYSTEM_NAME=Android \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DCMAKE_SYSTEM_VERSION=21 \
        -DANDROID_PLATFORM=android-21 \
        -DANDROID_ABI=arm64-v8a \
        -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
        -DANDROID_NDK=/usr/local/lib/android/sdk/ndk/21.1.6352462 \
        -DCMAKE_ANDROID_NDK=/usr/local/lib/android/sdk/ndk/21.1.6352462 \
        -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake \
        -DCMAKE_MAKE_PROGRAM=/usr/local/lib/android/sdk/cmake/3.18.1/bin/ninja \
        "-DCMAKE_CXX_FLAGS=-std=c++14 -DC10_USE_GLOG -DC10_USE_MINIMAL_GLOG -DANDROID -Wno-c++11-narrowing -fexceptions" \
        -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/runner/work/wenet/wenet/runtime/android/app/build/intermediates/cxx/RelWithDebInfo/94u3d5yd/obj/arm64-v8a \
        -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/home/runner/work/wenet/wenet/runtime/android/app/build/intermediates/cxx/RelWithDebInfo/94u3d5yd/obj/arm64-v8a \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        -B/home/runner/work/wenet/wenet/runtime/android/app/.cxx/RelWithDebInfo/94u3d5yd/arm64-v8a \
        -GNinja
    from /home/runner/work/wenet/wenet/runtime/android/app
  CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  FBJNI_LIBRARY
      linked by target "decoder" in directory /home/runner/work/wenet/wenet/runtime/android/app/src/main/cpp/decoder
  PYTORCH_LIBRARY
      linked by target "decoder" in directory /home/runner/work/wenet/wenet/runtime/android/app/src/main/cpp/decoder
  
  CMake Generate step failed.  Build files cannot be regenerated correctly.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
* Get more help at https://help.gradle.org/
BUILD FAILED in 2m
Error: Process completed with exit code 1.`

**Comment by Sail-Ocean** [comment]
> 因人力问题，Windows 的 Runtime 现在基本处于不维护的状态了，推荐使用 linux Runtime。

求教 Linux Runtime如何使用, 能给一些参考资料吗？

还有我按照视频中的步骤安装VS 2022 之后， cmake --build build的时候，会报错，错误信息是you need c++17 to compile Pytorch，请问这个问题如何解决，能提供些思路吗

**Comment by xingchensong** [comment]
> > 因人力问题，Windows 的 Runtime 现在基本处于不维护的状态了，推荐使用 linux Runtime。
> 
> 求教 Linux Runtime如何使用, 能给一些参考资料吗？
> 
> 还有我按照视频中的步骤安装VS 2022 之后， cmake --build build的时候，会报错，错误信息是you need c++17 to compile Pytorch，请问这个问题如何解决，能提供些思路吗

升级一下gcc

**Comment by Sail-Ocean** [comment]
> > > 因人力问题，Windows 的 Runtime 现在基本处于不维护的状态了，推荐使用 linux Runtime。
> > 
> > 
> > 求教 Linux Runtime如何使用, 能给一些参考资料吗？
> > 还有我按照视频中的步骤安装VS 2022 之后， cmake --build build的时候，会报错，错误信息是you need c++17 to compile Pytorch，请问这个问题如何解决，能提供些思路吗
> 
> 升级一下gcc

我是在windows系统，用的Visual Studio 2022，不是在Linux下呀
