### ISSUE TITLE
【Help needed】训练迭代一定step后开始频繁出现loss = nan的情况

### ISSUE THREAD

**Issue by xIaott-s** [wenet-e2e/wenet#2616]
使用了deepspeed stage2，fp16模式，训练了差不多1w steps后开始频繁出现loss为nan的情况。有人遇到过类似的问题么。

**Comment by Mddct** [comment]
fp16 相当不稳定， 如果支持bf16 最好用bf16

**Comment by xIaott-s** [comment]
v100，支持不了，这种情况下是不是最优解就是fp32了

**Comment by Mddct** [comment]
是 可以先fp32训练会 然后切fp16

**Comment by xIaott-s** [comment]
好的，感谢指导。

**Comment by fclearner** [comment]
> fp16 相当不稳定， 如果支持bf16 最好用bf16

周神，fp16不稳定是不是因为layernorm或者rmsnorm，如果用最新的那个dyt会不会就稳定了，很好奇
