### ISSUE TITLE
在不能联网环境下编译onnxruntime，如何离线下载WeTextProcessing

### ISSUE THREAD

**Issue by xiaodiandian1234** [wenet-e2e/wenet#2617]
**Describe the bug**
在不能联网环境下编译wenet onnxruntime时，总是会联网git clone https://github.com/wenet-e2e/WeTextProcessing.git 。想请教下如何像其它工具包那样可以提前离线下载？ 谢谢。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
Linux centos

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xingchensong** [comment]
手动下载解压
