### ISSUE TITLE
aishell2_u2pp_conformer_exp预训练权重转换成onnx后不出识别结果

### ISSUE THREAD

**Issue by angenge** [wenet-e2e/wenet#2624]
使用[aishell2_u2pp_conformer_exp.tar.gz]里的训练权重进行onnx格式模型转换，可以转换成功，但是解码时没有结果，同样转成libtorch模型也不行。

wenet版本：v3.1.0

python版本：3.10

转换命令：
`exp=/home/ubuntu/wenet/exp/aishell2_u2pp_conformer_exp
onnx_dir=models/onnx
python -m wenet.bin.export_onnx_cpu \
  --config $exp/train.yaml \
  --checkpoint $exp/final.pt \
  --chunk_size 16 \
  --output_dir $onnx_dir \
  --num_decoding_left_chunks -1`

`exp=/home/ubuntu/wenet/exp/aishell2_u2pp_conformer_exp
jit_dir=models/jit
python -m wenet.bin.export_jit \
  --config $exp/train.yaml \
  --checkpoint $exp/final.pt \
  --output_file $jit_dir/final.zip \
  --output_quant_file $jit_dir/final_quant.zip
`

**Comment by xingchensong** [comment]
看一下字典里sos是2还是其他的

**Comment by xingchensong** [comment]
另外看一下音频是不是双声道的，要先转单声道
