### ISSUE TITLE
whisper script does not work

### ISSUE THREAD

**Issue by 200987299** [wenet-e2e/wenet#2626]
loss_dict = executor.cv(model, cv_data_loader, configs)
  File "/datasets_hdd/dxu/wenet/wenet/utils/executor.py", line 161, in cv
    loss_dict["acc"] = sum(total_acc) / len(total_acc)
ZeroDivisionError: division by zero
return f(*args, **kwargs)
  File "/datasets_hdd/dxu/wenet/examples/common_voice_yue_t2/whisper/wenet/bin/train.py", line 162, in main
    loss_dict = executor.cv(model, cv_data_loader, configs)
  File "/datasets_hdd/dxu/wenet/wenet/utils/executor.py", line 161, in cv
    loss_dict["acc"] = sum(total_acc) / len(total_acc)
ZeroDivisionError: division by zero

That is the error I got, I tried two datasets but they all gives me the same error. BTW, the "input_dim" parameter is missing from the default config file.

Please let me know what I did wrong or maybe there is a bug somewhere?

bests

**Comment by turinaf** [comment]
I'm also facing this error

**Comment by turinaf** [comment]
@200987299 were you able to solve?
