### ISSUE TITLE
请问为什么调用模型的model.forward_encoder_chunk(feats, 0, -1)函数生成结果维度与encoder的output_size不匹配

### ISSUE THREAD

**Issue by lordlxh** [wenet-e2e/wenet#2627]
在使用模型进行推理的时候
def _decode(self,
                audio_file: str,
                tokens_info: bool = False,
                label: str = None) -> dict:
        feats = self.compute_feats(audio_file)
        print("feats:",feats.size())
        encoder_out, _, _ = self.model.forward_encoder_chunk(feats, 0, -1)
        print("encoder_out:",encoder_out.size())
其输出最后一个维度是512
![image](https://github.com/user-attachments/assets/4f6525ff-652c-4393-8dd4-a6fd82c8afc1)
但是在encoder中他的output_size应该是256，请问为什么最后的输出维度不是[1,chunks,256]?

**Comment by xingchensong** [comment]
因为有1/4subsample
