### ISSUE TITLE
efficonformer是否支持runtime解码？

### ISSUE THREAD

**Issue by Yong2Fern** [wenet-e2e/wenet#2628]
训练数据：librispeech960
模型结构：u2pp_efficonformer_v2_stream.yaml，使用因果卷积causal=true;
测试集：test_other
torch原型，recognize.py解码，解码方式：ctc_prefix_beam_search，beam=10
libtorch模型，decoder_main解码，纯声学解码（不加载fst）

问题1：原型和引擎效果对齐问题：chunk_size=18, 效果不一致 （why ????????????????????????????）
ps：原型和引擎解码num_left_chunks均为default=-1。
chunk_size=-1，效果一致
chunk_size=12，效果一致
chunk_size=16，效果不一致（分析认为是 efficient conformer 组注意力groups=3，导致流式推理时pad0问题）
chunk_size=18, 效果不一致 （why ????????????????????????????）

问题2：u2pp_efficonformer_v2_stream.yaml runtime解码支持fst吗？

**Comment by xingchensong** [comment]
应该是不支持efficientconformer的
