### ISSUE TITLE
train u2++ conformer :  AssertionError  assert offset + size <= self.max_len

### ISSUE THREAD

**Issue by turinaf** [wenet-e2e/wenet#2629]
When training u2++ conformer on custom dataset, I'm encountering this error, it stops after training a while. The `train_conformer.yaml` worked fine. 
```
/wenet/wenet/transformer/embedding.py", line 102, in position_encoding
      assert offset + size <= self.max_len
  AssertionError
```
**To Reproduce**
1. create custom dataset following librispeech example (uising wav files, instead of flac)
2. change config file to `train_u2++_conformer.yaml` in `run.sh`, the only thing I changed in yaml file is batch size
3. run stage 4

**Expected behavior**
Finish training normally

**Comment by Mddct** [comment]
训练数据太长了 ， 超过emb的最长长度

Turi Abu ***@***.***> 于2024年9月10日周二 11:16写道：

**Comment by Mddct** [comment]
需要把每一条训练数据限制在30s以内， 或者该打max len

Turi Abu ***@***.***> 于2024年9月10日周二 13:33写道：
