### ISSUE TITLE
link not work

### ISSUE THREAD

**Issue by aa671** [wenet-e2e/wenet#2631]
Hi,
the [link](http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/aishell2/20210618_u2pp_conformer_exp.tar.gz) do not work in the [file]( https://github.com/wenet-e2e/wenet/blob/main/runtime/gpu/tensorrt/run_streaming_small_model.sh) 
cannot download 20210618_u2pp_conformer_exp.tar.gz, please cheak.

![图片](https://github.com/user-attachments/assets/743726ca-2e47-4e30-9ed6-65fe7485e536)

**Comment by pengzhendong** [comment]
All models are moved to `modelscope`, please see: https://github.com/wenet-e2e/wenet/blob/main/docs/pretrained_models.md
