### ISSUE TITLE
problem with compute-wer.py

### ISSUE THREAD

**Issue by dsplabbee** [wenet-e2e/wenet#2634]
I'm running a speech recognition experiment where text is in UTF-8 format, containing also non-Latin characters. When I run the compute-wer.py to calculate the WER, there are problems with the alignment between reference text and recognized text. In each word which contains a non-Latin character, script inserts a space before the non-Latin character, which results in two words instead of one.

To reproduce the problem:

1.) Reference text file:
A_0001 ABCČDÖF

2.) Recognized text file:
A_0001 ABCČDÖX

3.) compute-wer.py command:
python3 tools/compute-wer.py --char=1 --v=1 --cs=0 reference-text recognized-text

4.) Output from compute-wer.py:

utt: A_0001
WER: 33.33 % N=3 C=2 S=1 D=0 I=0
lab: ABC ČD ÖF 
rec: ABC ČD ÖX 

5.) Correct result:
The recording A_0001 contains only one word, where the recognition error is in the last character (X recognized instead of F in reference). Thus, the correct WER should be 100%.

As it can be seen instead of only one word, compute-wer.py inserts space before each non-Latin character, producing three words, and then calculates the wrong WER of 33%. 

This is just a small artificial example of my problem, generated for debugging. I can always reproduce it on a 1000 hours real dataset. I'm running Wenet on a Linux Ubuntu system using basically the Librispeech recipe from examples.

Please help me to find out, if I'm doing anything wrong or this presents a bug.

**Comment by Sakura-Cloud28** [comment]
Your text contains chars like "Č" and "Ö". In this case, you can set "--char=0" in command "python3 tools/compute-wer.py --char=1 --v=1 --cs=0 reference-text recognized-text".
For details,  check the "characterize()" function in computer-wer.py.
