### ISSUE TITLE
关于Paraformer模型：使用wenet中的Paraformer转换代码转换后无法在安卓runtime使用

### ISSUE THREAD

**Issue by Furtherking** [wenet-e2e/wenet#2644]
您好！我使用了wenet中[convert_paraformer_to_wenet_config_and_ckpt.py]将Paraformer模型转成了wenet的格式，并导出成了final.zip并适配了units.txt。但是在安卓runtime中似乎并不能直接使用，使用转换后的模型会导致app闪退，请问使用wenet的安卓runtime运行转换后的Paraformer模型是可行的吗？

**Comment by xingchensong** [comment]
官方没有验证过
