### ISSUE TITLE
MoE onnx 导出

### ISSUE THREAD

**Issue by xIaott-s** [wenet-e2e/wenet#2646]
我看到历史issue中有提到如果使用了moe模块的话，无法导出onnx。但是我使用wenet/bin/export_onnx_gpu.py是可以正常导出encoder.onnx 和 decoder.onnx的，而且cer跟torch checkpoint是对齐的。想请教下是有什么坑我没注意到么？还是目前已经支持moe的onnx导出了？

**Comment by xingchensong** [comment]
所谓“不支持”是指没有经过验证，如果你验证没问题的话那就太好了

**Comment by computervisionlearner** [comment]
> 所谓“不支持”是指没有经过验证，如果你验证没问题的话那就太好了

你说的“没有经过验证”，是指在验证torch和onnx推理结果误差判断的时候，失败了对吧？
