### ISSUE TITLE
How to train recipe wenetspeech dataset

### ISSUE THREAD

**Issue by liziru** [wenet-e2e/wenet#2647]
**Describe the bug**
I want to train the recipe of wenetspeech dataset(examples/wenetspeech/s0), but torchaudio failed to load opus format file after wenetspeech dataset is downloaded. 
I also use '[process_opus.py](https://github.com/wenet-e2e/wenet/blob/main/examples/wenetspeech/s0/local/process_opus.py)' to process 'train_l' subset of wenetspeech, and change step2 as following, but still got an error '*_seg0004 not in key dict'

![image](https://github.com/user-attachments/assets/b221dd66-eb47-4739-8adf-7695229ca7b7)

I cannot find any docs on the internet. Any advice to solve this problem? I will appreciate it very much.

**To Reproduce**
1. download wenetspeech dataset
2. python process_opus.py data/train_l/wav.scp data/train_l/segment data/train_l/out_wav.scp 
3. change wenetspeech path in run.sh , bash examples/wenetspeech/s0/run.sh
4.  error file *_seg0004 not in key dict'

**Screenshots**
I will put it later

**Desktop (please complete the following information):**
 - OS:  ubuntu20

**Comment by xingchensong** [comment]
算cmvn可以不用全部数据集，采样一点数据就行，没有的key可以忽略
