### ISSUE TITLE
paraformer streaming inference

### ISSUE THREAD

**Issue by AITDASR** [wenet-e2e/wenet#2651]
请问还会支持流式paraformer推理吗？我看代码中列了TODO，有后续计划吗？或者能讲一下思路吗？感谢

**Comment by Mddct** [comment]
runtime 不会支持， 训练的话 目前是直接动态chunk训练的 也就是支持的streaming

**Comment by AITDASR** [comment]
> runtime 不会支持， 训练的话 目前是直接动态chunk训练的 也就是支持的streaming

动态chunk 在实际流式使用(chunk by chunk)的时候 fsmn 的pading  会对结果产生很大影响。
