### ISSUE TITLE
wenet检查点保存和加载

### ISSUE THREAD

**Issue by llh666521** [wenet-e2e/wenet#2658]
请问wenet在保存和加载checkpoint的时候有考虑save和load optimizer和scheduler的逻辑吗？

**Comment by xingchensong** [comment]
有schedule没有optimizer

**Comment by llh666521** [comment]
> 有schedule没有optimizer

请问这个对训练效果影响大吗？谢谢！

**Comment by Mddct** [comment]
不大 ， 你可以自己修改下 纯opt

llh666521 ***@***.***> 于2024年11月24日周日 19:20写道：
