### ISSUE TITLE
bug: feature_pipeline doesn't have support for pitch

### ISSUE THREAD

**Issue by jprobichaud** [wenet-e2e/wenet#296]
Hi,

When training a model using librispeech recipe, we use `steps/make_fbank_pitch.sh` to generate features.  This will create than just the 80 fbank coeficients.  Because of that, using the streaming mode in the runtime will fail because starting from audio signal, we can only extract the 80 fbanks, but not the picth-related features.

Is it possible to add support for that easily?

Thanks

**Comment by robin1001** [comment]
Please use librispeech/s0 recipe which use fbank feature to retrain your model. There is no plan to support pitch feature in runtime.

**Comment by jprobichaud** [comment]
Thanks for the information.  Was it determined that using pitch is not useful or harmful?  I know that for diarization, it is often a useful set of features to consider.

**Comment by whiteshirt0429** [comment]
we indeed tried both fbank and fbank+pitch on aishell-1 dataset, fbank perhaps better than fbank with pitch.
