### ISSUE TITLE
fatal error: 'fst/log.h' file not found when building android binary

### ISSUE THREAD

**Issue by sungitly** [wenet-e2e/wenet#307]
Hi,

I was trying to build the android binary and apk following the instruction here [WeNet On-device ASR Android Demo](https://github.com/mobvoi/wenet/tree/e86e5c15f44137efb8abdf4496238771ddcb4aaa/runtime/device/android/wenet).

When I executed the following scripts, 

```Shell
cd runtime/device/android/wenet
./gradlew build
```

 I got the missing fst/log.h errors as follows.

![fst_error](https://user-images.githubusercontent.com/5569844/114530324-6a1c0b80-9c7d-11eb-9dfb-1dc8d3cf150d.jpg)

Can someone help on this?

**Comment by yh8899** [comment]
I have the same problem.

**Comment by wangbq18** [comment]
I have the same problem too.

**Comment by sungitly** [comment]
@yh8899 @wangbq18 The issue has been fixed in branch zhendong-android-openfst. I have tested it and it works well.

**Comment by yh8899** [comment]
> @yh8899 @wangbq18 The issue has been fixed in branch zhendong-android-openfst. I have tested it and it works well.

Thanks.
