### ISSUE TITLE
runtime memory leak

### ISSUE THREAD

**Issue by Mddct** [wenet-e2e/wenet#352]
libtorch model cause memory growth for courrent  call.

**Comment by robin1001** [comment]
Is there any solution to fix it?

**Comment by Mddct** [comment]
I tried some environment variables but none of them worked.  Maybe need to recompile libtorch without mkl

**Comment by lvzhiqiang** [comment]
Has the problem benn solved? @Mddct

**Comment by Mddct** [comment]
@lvzhiqiang 
sorry，I've been busy recently, and haven't tried to solve it yet。

**Comment by Mddct** [comment]
> Is there any solution to fix it?
Maybe related issues:
https://github.com/pytorch/pytorch/issues/27971#issuecomment-543067718

**Comment by xingchensong** [comment]
Will hold this PR for anyone else who has encountered and interested in the same question.

**Comment by xingchensong** [comment]
Please note that memory leak has been fixed by jemalloc in PR #1011
