### ISSUE TITLE
a simulate forward chunk by chunk bug

### ISSUE THREAD

**Issue by boji123** [wenet-e2e/wenet#388]
https://github.com/mobvoi/wenet/blob/1eebda820c24ea26d2fba62219da60c033fcb41a/wenet/transformer/encoder.py#L218

**Comment by boji123** [comment]
is xs is short enough， next_cache_start will be a negative number

**Comment by boji123** [comment]
should replace by
`next_cache_start = max(xs.size(1) - required_cache_size, 0)`

**Comment by robin1001** [comment]
make it a PR?

**Comment by boji123** [comment]
submitted

**Comment by robin1001** [comment]
merged, thanks
