### ISSUE TITLE
Streaming a long file with decoder_main yield an exception in embedding.py

### ISSUE THREAD

**Issue by jprobichaud** [wenet-e2e/wenet#389]
Running `decoder_main` on a "long" file (5 minutes) with `--simulate-streaming` and `--num_left_chunks 15` end up throwing an exception inside embedding.py:
```
I0518 12:28:59.294829  3894 torch_asr_decoder.cc:100] Required 64 get 64
terminate called after throwing an instance of 'torch::jit::JITException'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/wenet/transformer/embedding.py", line 17, in forward_encoder_chunk
      pass
    else:
      ops.prim.RaiseException("Exception")
      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _1 = torch.to(self.pe, ops.prim.device(x), None, False, False)
    self.pe = _1

Traceback of TorchScript, original code (most recent call last):
  File "/workspaces/wenet/transformer/embedding.py", line 107, in forward_encoder_chunk
            torch.Tensor: Positional embedding tensor (1, time, `*`).
        """
        assert offset + x.size(1) < self.max_len
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        self.pe = self.pe.to(x.device)
        x = x * self.xscale
RuntimeError: Exception

```

**Expected behavior**
I would expect that in streaming mode, we can transcribe very long audio.
 - OS: Ubuntu 16, pytorch 1.6.0, python 3.8.8, gcc 5.4,

**Comment by pengzhendong** [comment]
—simulate-streaming is used to test the cpu usage. It will sleep to simulate the real speaking scene.
You should use the websocket with —continuous_decoding

**Comment by jprobichaud** [comment]
hum, ok.  I'm getting a different exception when I try with the websocket approach.  I'm still a little puzzle as why setting a left context > -1 does not limit how many characters are considered by the network.  I'll do a bit more digging and I'll report here.

Just to be sure, you are saying that it should be technically possible to perform recognition on a very long audio by using `--continuous_decoding` and a positive num_left_chunk parameter, right?

**Comment by pengzhendong** [comment]
The left context only limits the chunks num of decoding. Rescoring will consider the total sentence.
Set `--continuous_decoding` to true, a negative num_left_chunk works too (so do not care it).

**Comment by jprobichaud** [comment]
>  Rescoring will consider the total sentence.
Can't we limit rescoring to a certain window?  I mean, if we want streaming capabilities, it sort of implies (in my head actually), to not bound the length of the audio to transcribe to a certain length.  Am I misunderstanding what WeNet considers "streaming" to be?

**Comment by pengzhendong** [comment]
`--continuous_decoding` will detect the endpoint. Once the endpoint is detected, wenet will do the rescoring and reset the decoding state.

**Comment by pcbua** [comment]
Unfortunately, this assert still fires on ~6min recordings.
Any chance on fix?

Here is how I run it:
```
./build/decoder_main \
    --chunk_size -1 \
    --wav_path $f \
    --model_path $model_dir/final.zip \
    --dict_path $model_dir/words.txt

```

Here is error message:
```
I1005 01:53:16.203866 98472 torch_asr_decoder.cc:111] Required 2147483647 get 36389
terminate called after throwing an instance of 'torch::jit::JITException'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/wenet/transformer/embedding.py", line 17, in forward_encoder_chunk
      pass
    else:
      ops.prim.RaiseException("Exception")
      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _1 = torch.to(self.pe, ops.prim.device(x), None, False, False)
    self.pe = _1

Traceback of TorchScript, original code (most recent call last):
  File "/data/users/diwu/github/reverse/wenet/examples/gigaspeech/s0/wenet/transformer/embedding.py", line 107, in forward_encoder_chunk
            torch.Tensor: Positional embedding tensor (1, time, `*`).
        """
        assert offset + x.size(1) < self.max_len
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        self.pe = self.pe.to(x.device)
        x = x * self.xscale
RuntimeError: Exception

```

**Comment by crazysunsir** [comment]
Same error.
So is the error solved now?
