### ISSUE TITLE
Multi-cn Unified Conformer  Pretrained model

### ISSUE THREAD

**Issue by h0ngwen** [wenet-e2e/wenet#399]
Will you provide the Unified Conformer pretrained model in multi-cn example?

**Comment by pengzhendong** [comment]
Just in the plan.

**Comment by XiaoYee** [comment]
May you release the model recently？ Thank you.

**Comment by pengzhendong** [comment]
In the next  few days~

**Comment by double22a** [comment]
[Unified Conformer pretrained model in multi-cn example](https://pan.baidu.com/s/1v6QooKCrKCldKiWROB-AEQ) password: i3kq

[Unified Conformer results in multi-cn example](https://github.com/wenet-e2e/wenet/commit/aa8f03d24f1498f6128bc0c5db3f6c64ca558035#diff-41c6bae6cc7176e9579f198299f121d97c6aae97719d9e70892422a9ef2c86e2)

**Comment by temp1096** [comment]
Thanks for sharing that model @double22a !

There is another multi-cn unified conformer in the results table, trained also on AISHELL-2 and TAL-ASR. Are you planning to release this model as well?

**Comment by double22a** [comment]
> ring that model @double22a !
> 
> There is another multi-cn unified conformer in the results table, trained also on AISHELL-2 and TAL-ASR. Are you planning to release this model as well?

Sorry, no, we don't have AISHELL-2. Mobvoi has this plan. @pengzhendong

**Comment by pengzhendong** [comment]
@h0ngwen @XiaoYee @temp1096 @double22a https://github.com/wenet-e2e/wenet/pull/568
The pre-trained multi_cn model train on:
| Dataset    | Duration (Hours) |
|------------|------------------|
| Aidatatang | 140              |
| Aishell    | 151              |
| MagicData  | 712              |
| Primewords | 99               |
| ST-CMDS    | 110              |
| THCHS-30   | 26               |
| TAL-ASR    | 587              |
| AISHELL2   | 1000             |

**Comment by Mddct** [comment]
awesome。  great job

彭震东 ***@***.***> 于 2021年8月16日周一 上午7:51写道：

**Comment by Jackiexiao** [comment]
for those who want to [inference using docker]((https://github.com/wenet-e2e/wenet/tree/main/runtime/server/x86#wenet-server-x86-asr-demo)
), I have exported the model using [export_jit](https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_jit.py) 

Download link
[20210815_unified_conformer_server.tar.gz](https://pan.baidu.com/s/12oy3D1H_pU_AqEO4WMPLig) password / 提取码：f0hn

**Comment by robin1001** [comment]
> for those who want to [inference using docker](https://github.com/wenet-e2e/wenet/tree/main/runtime/server/x86#wenet-server-x86-asr-demo), I have exported the model using [export_jit](https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_jit.py)
> 
> Download link
> [20210815_unified_conformer_server.tar.gz](https://pan.baidu.com/s/12oy3D1H_pU_AqEO4WMPLig) password / 提取码：f0hn

Thanks, it is also available on WeNet runtime, please see  https://github.com/wenet-e2e/wenet/tree/main/runtime/server/x86 for details

**Comment by Jackiexiao** [comment]
> > for those who want to [inference using docker](https://github.com/wenet-e2e/wenet/tree/main/runtime/server/x86#wenet-server-x86-asr-demo), I have exported the model using [export_jit](https://github.com/wenet-e2e/wenet/blob/main/wenet/bin/export_jit.py)
> > Download link
> > [20210815_unified_conformer_server.tar.gz](https://pan.baidu.com/s/12oy3D1H_pU_AqEO4WMPLig) password / 提取码：f0hn
> 
> Thanks, it is also available on WeNet runtime, please see https://github.com/wenet-e2e/wenet/tree/main/runtime/server/x86 for details

great!

Could you provide LibriSpeech GigaSpeech model for docker inference ?  Thx!

![image](https://user-images.githubusercontent.com/18050469/130204674-17b24acf-df8e-4106-9f6f-069981b19bcc.png)
