### ISSUE TITLE
Gigaspeech model broken link

### ISSUE THREAD

**Issue by temp1096** [wenet-e2e/wenet#407]
The pretrained conformer model link provided for the Gigaspeech example doesn't work, says "file not exist"

Model link: http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/gigaspeech/20210115_conformer_exp.tar.gz

**Comment by pengzhendong** [comment]
try http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/gigaspeech/20210520_conformer_exp.tar.gz

**Comment by temp1096** [comment]
This works, thank you! Would you like to also push that updated link to the repo?

**Comment by temp1096** [comment]
@pengzhendong I'm trying to load the model from that link, just calling "torch.load(<path>)" and giving it the path to the final.pt file, but I get errors - I've attached the stack trace below. Is there an issue with this model file, or is there another way I should be calling it? Thanks!

```
  File "wenet/bin/export_jit.py", line 43, in <module>
    load_checkpoint(model, args.checkpoint)
  File "/Users/ark/Documents/projects/wenet/wenet/utils/checkpoint.py", line 18, in load_checkpoint
    checkpoint = torch.load(path, map_location='cpu')
  File "/opt/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/serialization.py", line 577, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/opt/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/serialization.py", line 241, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory
```

**Comment by pengzhendong** [comment]
It has been updated.
Please change your pytorch version to 1.6.

**Comment by temp1096** [comment]
Got it, thanks! For anybody who stumbles upon this in the future, I was actually using torch 1.6, but on a machine without a GPU - with a GPU it worked fine, even on torch 1.8.

**Comment by temp1096** [comment]
Hello again! I just have another question trying to get the model working. The steps I followed were: 

- Download and untar the file provided at the download link
- Export the model, with: `python wenet/bin/export_jit.py --config 20210520_conformer_exp/train.yaml --checkpoint 20210520_conformer_exp/final.pt --output_file final.zip`, this runs successfully
- Try to recognize on the librispeech test-clean test set (since I don't have access to download gigaspeech yet): 
```
python wenet/bin/recognize.py --gpu 0 --mode attention_rescoring --config 20210520_conformer_exp/train.yaml --checkpoint 20210520_conformer_exp/final.pt --test_data examples/librispeech/s0/data/test_clean/format.data --beam_size 20 --batch_size 1 --penalty 0.0 --dict 20210520_conformer_exp/words.txt
```
This fails, I believe because words.txt contains log probabilities of the tokens instead of the indices. I tried replacing the log probabilities with indices, but it seems like the words need to be correctly sorted, and use the correct special tokens as well. I'm able to decode if I use integer indices in words.txt, but the results are nonsensical, presumably because the indices don't correspond correctly to the proper tokens.

Is there another words.txt file that I should be using instead? Thanks again for the help!

**Comment by temp1096** [comment]
Hello again @pengzhendong - just wanted to ask the above question again, if you have a chance to take a look.

**Comment by rohithkodali** [comment]
The same issue for me as well,  there are log probabilities instead of integer indices and I tried to convert them into indices but the output is worse.

**Comment by temp1096** [comment]
Update for others - the same link now seems to point to an updated word list, that I was able to get running this time.
