### ISSUE TITLE
add acknowledgement  to EESEN

### ISSUE THREAD

**Issue by YingChenlu** [wenet-e2e/wenet#417]
The work of TLG is proposed as early as in 2015 by Yajie Miao, whose death in 2016 was really a pity. Please give an acknowledgement  and respect to him.
paper: [EESEN: End-to-End Speech Recognition using Deep RNN Models and WFST-based Decoding](https://arxiv.org/abs/1507.08240)
github: [https://github.com/srvk/eesen](https://github.com/srvk/eesen)

**Comment by robin1001** [comment]
Thanks, please see https://github.com/wenet-e2e/wenet/pull/418.
