### ISSUE TITLE
Training a non-streaming model

### ISSUE THREAD

**Issue by martinkoling** [wenet-e2e/wenet#431]
Hi!

I would like to train a non-streaming model, similar to the one called M1 in the WeNet paper, for comparison purposes. Can you please provide information on where I can specify to train the model with (static) full attention? 

My expectation is that this model would perform better on full decoding than a model trained with dynamic chunk attention, as you are describing in table 1 in the WeNet paper. Out of curiosity, I would also like to conduct experiments on what happens when you try to decode the non-streaming model on 16/8/4/1 decoding sizes. 

Thank you so much for any advice!

**Comment by robin1001** [comment]
Just use conf/train_conformer.yaml for your experiment. please see https://github.com/wenet-e2e/wenet/blob/main/examples/aishell/s0/run.sh for demo.

![image](https://user-images.githubusercontent.com/6036624/120575910-78540000-c454-11eb-8337-56e0eff47f0b.png)

And the only configure difference of none-streaming model and streaming model is  the "use_dynamic_chunk"  option in configure yaml.

**Comment by martinkoling** [comment]
Thank you for your response.

Indeed, that is what I tried but I was surprised by the results. I am using Librispeech 100 hours to train the models for 100 epochs. The first table is with the train_unified_conformer and the second is with train_conformer, both using the same hyperparameters in the config file. I would expect results as in your paper where the non-streaming is slightly better on full attention decoding. However, as you can see this is not the case.

![Screenshot 2021-06-03 at 10 59 11](https://user-images.githubusercontent.com/32307597/120619689-81e16600-c45c-11eb-9735-8e8720032a9b.png)

![Screenshot 2021-06-03 at 11 06 17](https://user-images.githubusercontent.com/32307597/120619755-96256300-c45c-11eb-8312-762f6c360ed8.png)

I would like to ask for your opinion if you think that these are reasonable results given the dataset I use, or if I am not actually training with full attention for the non-streaming model. Also a bit curious on why the results are the same for the different chunk sizes in the non-streaming model, if you would like to comment that :) 

Sorry for the long question, I really appreciate the time you are taking to answer this.

**Comment by robin1001** [comment]
The result is weird, I think maybe the result are both from non-streaming conformer tested with chunk 16. In theory, you can't test the non-streaming model with fixed chunk, the result degrades a lot compared to the full chunk.

![image](https://user-images.githubusercontent.com/6036624/121982269-cad0dd00-cdc1-11eb-951d-3a3aa0e710bd.png)

**Comment by Mddct** [comment]
closed  due to not activating for long time
