### ISSUE TITLE
Relative position encoding

### ISSUE THREAD

**Issue by yjiangling** [wenet-e2e/wenet#435]
There is a note described below the code like this:

# Remove rel_shift since it is useless in speech recognition,
# and it requires special attention for streaming.
# matrix_bd = self.rel_shift(matrix_bd)

So, we totally don't need to use it in ASR task, right? And when we use relative position encoding (don't use rel_shift), we can stil achieve Streaming function, right?

**Comment by robin1001** [comment]
Yes. we don't use it in ASR and it's still streaming without it.

**Comment by yjiangling** [comment]
> Yes. we don't use it in ASR and it's still streaming without it.

OK， thanks

**Comment by heibaidaolx123** [comment]
@robin1001 
Hi, binbin,
why is rel_shift uesless in asr?
And what did you mean by 'it requires special attention for streaming'?
Thanks.
