### ISSUE TITLE
Error while building runtime lib x86

### ISSUE THREAD

**Issue by Durgesh92** [wenet-e2e/wenet#437]
I am building the runtime lib on ubuntu 20.04 with grpc and getting following issue

~/wenet_android/runtime/server/x86/bin/grpc_server_main.cc:40:32: error: no matching function for call to ‘wenet::GrpcServer::GrpcServer(std::shared_ptr<wenet::FeaturePipelineConfig>&, std::shared_ptr<wenet::DecodeOptions>&, std::shared_ptr<fst::SymbolTable>&, std::shared_ptr<wenet::TorchAsrModel>&, std::shared_ptr<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > >&)’

**Comment by robin1001** [comment]
It's a bug, it gets fixed now, please pull the latest code.
