### ISSUE TITLE
Error during ./decoder_main

### ISSUE THREAD

**Issue by Durgesh92** [wenet-e2e/wenet#438]
I have trained Librespeech Recipe and when tried to decode with ./decoder_main am getting an error

I0604 23:29:12.050468 89918 torch_asr_model.cc:42] torch model info subsampling_rate 4 right context 6 sos 5030 eos 5030 is bidirectional decoder 0
I0604 23:29:12.075227 89918 decoder_main.cc:67] num frames 600
I0604 23:29:12.075562 89918 torch_asr_decoder.cc:120] Required 2147483647 get 600
terminate called after throwing an instance of 'std::runtime_error'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/wenet/transformer/asr_model.py", line 105, in forward_encoder_chunk
    elayers_output_cache: Optional[List[Tensor]]=None,
    conformer_cnn_cache: Optional[List[Tensor]]=None) -> Tuple[Tensor, Tensor, List[Tensor], List[Tensor]]:
    _20 = (self.encoder).forward_chunk(xs, offset, required_cache_size, subsampling_cache, elayers_output_cache, conformer_cnn_cache, )
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return _20
  def right_context(self: __torch__.wenet.transformer.asr_model.ASRModel) -> int:
  File "code/__torch__/wenet/transformer/encoder.py", line 84, in forward_chunk
    tmp_masks = torch.ones([1, _40], dtype=11, layout=None, device=_41, pin_memory=None)
    tmp_masks0 = torch.unsqueeze(tmp_masks, 1)
    xs15 = (self.global_cmvn).forward(xs, )
            ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _42 = (self.embed).forward(xs15, tmp_masks0, offset, )
    xs16, pos_emb, _43, = _42
  File "code/__torch__/wenet/transformer/cmvn.py", line 11, in forward
  def forward(self: __torch__.wenet.transformer.cmvn.GlobalCMVN,
    x: Tensor) -> Tensor:
    x0 = torch.sub(x, self.mean, alpha=1)
         ~~~~~~~~~ <--- HERE
    if self.norm_var:
      x1 = torch.mul(x0, self.istd)

Traceback of TorchScript, original code (most recent call last):
  File "/home/ubuntu/wenet/examples/durgesh/wenet/transformer/cmvn.py", line 44, in forward
            (torch.Tensor): normalized feature
        """
        x = x - self.mean
            ~~~~~~~~~~~~~ <--- HERE
        if self.norm_var:
            x = x * self.istd
RuntimeError: The size of tensor a (80) must match the size of tensor b (83) at non-singleton dimension 2

**Comment by Durgesh92** [comment]
maybe because I have used Kaldi style feature extractors with pitch (steps/make_fbank_pitch.sh)?

**Comment by Mddct** [comment]
Runtime only support fbank

Durgesh ***@***.***> 于 2021年6月5日周六 上午3:22写道：
