### ISSUE TITLE
Error while building runtime lib x86 add_subdirectory given source "kaldi" which is not an existing directory.

### ISSUE THREAD

**Issue by mingo-doer** [wenet-e2e/wenet#443]
(wenet) [root@localhost build]# build && cd build && cmake -DINTTYPES_FORMAT:STRING=C99 .. && cmake --build .
-bash: build: command not found
(wenet) [root@localhost build]# cd ..
(wenet) [root@localhost x86]# rm -rf build
(wenet) [root@localhost x86]# mdir build && cd build && cmake -DINTTYPES_FORMAT:STRING=C99 .. && cmake --build .
-bash: mdir: command not found
(wenet) [root@localhost x86]# mkdir build && cd build && cmake -DINTTYPES_FORMAT:STRING=C99 .. && cmake --build .
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Populating gflags
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/ASRT/wenet-main/runtime/server/x86/fc_base/gflags-subbuild
[100%] Built target gflags-populate
CMake Warning (dev) at fc_base/gflags-src/CMakeLists.txt:94 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Looking for C++ include unistd.h
-- Looking for C++ include unistd.h - not found
-- Looking for C++ include stdint.h
-- Looking for C++ include stdint.h - not found
-- Looking for C++ include inttypes.h
-- Looking for C++ include inttypes.h - not found
-- Looking for C++ include sys/types.h
-- Looking for C++ include sys/types.h - not found
-- Looking for C++ include sys/stat.h
-- Looking for C++ include sys/stat.h - not found
-- Looking for C++ include fnmatch.h
-- Looking for C++ include fnmatch.h - not found
-- Looking for strtoll
-- Looking for strtoll - not found
-- Looking for strtoq
-- Looking for strtoq - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for C++ include stddef.h
-- Looking for C++ include stddef.h - not found
-- Check size of pthread_rwlock_t
-- Check size of pthread_rwlock_t - failed
-- Populating glog
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/ASRT/wenet-main/runtime/server/x86/fc_base/glog-subbuild
[100%] Built target glog-populate
CMake Warning at fc_base/glog-src/CMakeLists.txt:51 (find_package):
  By not providing "Findgflags.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gflags", but
  CMake did not find one.

  Could not find a package configuration file provided by "gflags" (requested
  version 2.2.0) with any of the following names:

    gflagsConfig.cmake
    gflags-config.cmake

  Add the installation prefix of "gflags" to CMAKE_PREFIX_PATH or set
  "gflags_DIR" to a directory containing one of the above files.  If "gflags"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for execinfo.h
-- Looking for execinfo.h - found
-- Looking for glob.h
-- Looking for glob.h - found
-- Looking for libunwind.h
-- Looking for libunwind.h - not found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for pwd.h
-- Looking for pwd.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for sys/syscall.h
-- Looking for sys/syscall.h - found
-- Looking for sys/time.h
-- Looking for sys/time.h - found
-- Looking for sys/utsname.h
-- Looking for sys/utsname.h - found
-- Looking for syscall.h
-- Looking for syscall.h - found
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Looking for ucontext.h
-- Looking for ucontext.h - found
-- Looking for unwind.h
-- Looking for unwind.h - found
-- Looking for C++ include ext/hash_map
-- Looking for C++ include ext/hash_map - not found
-- Looking for C++ include ext/hash_set
-- Looking for C++ include ext/hash_set - not found
-- Looking for C++ include ext/slist
-- Looking for C++ include ext/slist - not found
-- Looking for C++ include tr1/unordered_map
-- Looking for C++ include tr1/unordered_map - not found
-- Looking for C++ include tr1/unordered_set
-- Looking for C++ include tr1/unordered_set - not found
-- Looking for C++ include unordered_map
-- Looking for C++ include unordered_map - not found
-- Looking for C++ include unordered_set
-- Looking for C++ include unordered_set - not found
-- Check size of unsigned __int16
-- Check size of unsigned __int16 - failed
-- Check size of u_int16_t
-- Check size of u_int16_t - failed
-- Check size of uint16_t
-- Check size of uint16_t - failed
-- Looking for dladdr
-- Looking for dladdr - not found
-- Looking for fcntl
-- Looking for fcntl - found
-- Looking for pread
-- Looking for pread - found
-- Looking for pwrite
-- Looking for pwrite - found
-- Looking for sigaction
-- Looking for sigaction - found
-- Looking for sigaltstack
-- Looking for sigaltstack - found
-- Performing Test HAVE_NO_DEPRECATED
-- Performing Test HAVE_NO_DEPRECATED - Failed
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS
-- Performing Test HAVE_NO_UNNAMED_TYPE_TEMPLATE_ARGS - Failed
-- Looking for snprintf
-- Looking for snprintf - found
-- Looking for get_static_proc_name in unwind
-- Looking for get_static_proc_name in unwind - not found
-- Looking for UnDecorateSymbolName in dbghelp
-- Looking for UnDecorateSymbolName in dbghelp - not found
-- Performing Test HAVE___ATTRIBUTE__
-- Performing Test HAVE___ATTRIBUTE__ - Success
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_DEFAULT
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_DEFAULT - Success
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_HIDDEN
-- Performing Test HAVE___ATTRIBUTE__VISIBILITY_HIDDEN - Success
-- Performing Test HAVE___BUILTIN_EXPECT
-- Performing Test HAVE___BUILTIN_EXPECT - Success
-- Performing Test HAVE___SYNC_VAL_COMPARE_AND_SWAP
-- Performing Test HAVE___SYNC_VAL_COMPARE_AND_SWAP - Success
-- Performing Test HAVE___DECLSPEC
-- Performing Test HAVE___DECLSPEC - Failed
-- Performing Test STL_NO_NAMESPACE
-- Performing Test STL_NO_NAMESPACE - Failed
-- Performing Test STL_STD_NAMESPACE
-- Performing Test STL_STD_NAMESPACE - Failed
-- Performing Test HAVE_USING_OPERATOR
-- Performing Test HAVE_USING_OPERATOR - Failed
-- Performing Test HAVE_NAMESPACES
-- Performing Test HAVE_NAMESPACES - Failed
-- Performing Test HAVE_GCC_TLS
-- Performing Test HAVE_GCC_TLS - Failed
-- Performing Test HAVE_MSVC_TLS
-- Performing Test HAVE_MSVC_TLS - Failed
-- Performing Test HAVE_CXX11_TLS
-- Performing Test HAVE_CXX11_TLS - Failed
-- Performing Test HAVE_ALIGNED_STORAGE
-- Performing Test HAVE_ALIGNED_STORAGE - Failed
-- Performing Test HAVE_LOCALTIME_R
-- Performing Test HAVE_LOCALTIME_R - Failed
-- Populating googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/ASRT/wenet-main/runtime/server/x86/fc_base/googletest-subbuild
[100%] Built target googletest-populate
-- Found PythonInterp: /root/anaconda3/envs/wenet/bin/python (found version "3.8.10") 
-- Populating boost
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/ASRT/wenet-main/runtime/server/x86/fc_base/boost-subbuild
[100%] Built target boost-populate
-- Populating libtorch
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/ASRT/wenet-main/runtime/server/x86/fc_base/libtorch-subbuild
[100%] Built target libtorch-populate
-- Found Torch: /mnt/ASRT/wenet-main/runtime/server/x86/fc_base/libtorch-src/lib/libtorch.so  
CMake Error at CMakeLists.txt:127 (add_subdirectory):
  add_subdirectory given source "kaldi" which is not an existing directory.

-- Configuring incomplete, errors occurred!
See also "/mnt/ASRT/wenet-main/runtime/server/x86/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/ASRT/wenet-main/runtime/server/x86/build/CMakeFiles/CMakeError.log".

**Comment by pengzhendong** [comment]
Windows does not support symlink by default.
这篇公众号推送末尾有相关解决方法：https://mp.weixin.qq.com/s/owUZAguxqV3ZcfxhU6XFxg

**Comment by magiczixiao** [comment]
same error, have you soved?

**Comment by pengzhendong** [comment]
kaldi is a symbol link instead of directory. Windows does not support symbol link by default.
1. copy the kaldi folder from the core folder
2. change the default settings of Windows

**Comment by magiczixiao** [comment]
> kaldi is a symbol link instead of directory. Windows does not support symbol link by default.
> 
> 1. copy the kaldi folder from the core folder, or
> 2. change the default settings of Windows

Thanks! But I compiled it under linux, and the project was also directly cloned in linux by git clone?

**Comment by magiczixiao** [comment]
> > kaldi is a symbol link instead of directory. Windows does not support symbol link by default.
> > 
> > 1. copy the kaldi folder from the core folder, or
> > 2. change the default settings of Windows
> 
> Thanks! But I compiled it under linux, and the project was also directly cloned in linux by git clone?

Solved! It is because I cloned the project under windows and then copied it into linux. Directly clone the projrct in linux can avoid this issue. Thanks again.
