### ISSUE TITLE
Error with cmake build

### ISSUE THREAD

**Issue by Durgesh92** [wenet-e2e/wenet#452]
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/gflags/gflags-nonamespace-targets.cmake:37 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: gflags_static;gflags_nothreads_static

  Targets not yet defined: gflags_shared;gflags_nothreads_shared

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/gflags/gflags-config.cmake:17 (include)
  fc_base/glog-src/CMakeLists.txt:51 (find_package)

Below is the error log

Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /home/durgesh/iamplus/wenet-latest/runtime/server/x86/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_d0900/fast && /usr/bin/make -f CMakeFiles/cmTC_d0900.dir/build.make CMakeFiles/cmTC_d0900.dir/build
make[1]: Entering directory '/media/durgesh/linux-external/iamplus/wenet-latest/runtime/server/x86/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_d0900.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_d0900.dir/src.c.o   -c /home/durgesh/iamplus/wenet-latest/runtime/server/x86/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_d0900
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_d0900.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    -rdynamic CMakeFiles/cmTC_d0900.dir/src.c.o  -o cmTC_d0900 
/usr/bin/ld: CMakeFiles/cmTC_d0900.dir/src.c.o: in function `main':
src.c:(.text+0x46): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x52): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x63): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_d0900.dir/build.make:87: cmTC_d0900] Error 1
make[1]: Leaving directory '/media/durgesh/linux-external/iamplus/wenet-latest/runtime/server/x86/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_d0900/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/durgesh/iamplus/wenet-latest/runtime/server/x86/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_c6455/fast && /usr/bin/make -f CMakeFiles/cmTC_c6455.dir/build.make CMakeFiles/cmTC_c6455.dir/build
make[1]: Entering directory '/media/durgesh/linux-external/iamplus/wenet-latest/runtime/server/x86/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c6455.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_c6455.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.16/Modules/CheckFunctionExists.c
Linking C executable cmTC_c6455
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c6455.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_c6455.dir/CheckFunctionExists.c.o  -o cmTC_c6455  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
make[1]: *** [CMakeFiles/cmTC_c6455.dir/build.make:87: cmTC_c6455] Error 1
make[1]: Leaving directory '/media/durgesh/linux-external/iamplus/wenet-latest/runtime/server/x86/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_c6455/fast] Error 2

**Comment by robin1001** [comment]
Please try to build with docker.

**Comment by LeonWlw** [comment]
Still build err with docker.
Sending build context to Docker daemon  15.36kB
Step 1/11 : FROM ubuntu:latest
 ---> 4c108a37151f
Step 2/11 : MAINTAINER <zhendong.peng@mobvoi.com>
 ---> Using cache
 ---> 9adefcb64fd1
Step 3/11 : ENV DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> ae61fbfb6685
Step 4/11 : RUN sed -i s@/archive.ubuntu.com/@/mirrors.tuna.tsinghua.edu.cn/@g /etc/apt/sources.list
 ---> Using cache
 ---> 16dce2c3d25e
Step 5/11 : RUN apt-get update && apt-get install -y git cmake wget build-essential
 ---> Using cache
 ---> 78160a6d58e7
Step 6/11 : RUN git clone https://github.com/mobvoi/wenet.git /home/wenet
 ---> Using cache
 ---> b8193a7bc802
Step 7/11 : ARG model=20210602_unified_transformer_server.tar.gz
 ---> Using cache
 ---> 300505bac228
Step 8/11 : RUN wget -P /home http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/aishell2/$model
 ---> Using cache
 ---> 6de74bd8ecc9
Step 9/11 : RUN tar -xzf /home/$model -C /home
 ---> Using cache
 ---> c91e6fbbdd64
Step 10/11 : ARG build=/home/wenet/runtime/server/x86/build
 ---> Using cache
 ---> 382f88b8eb83
Step 11/11 : RUN mkdir $build && cd $build && cmake .. && cmake --build .
 ---> Running in b5cd1a09d4e4
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.14 or higher is required.  You are running version 3.10.2


-- Configuring incomplete, errors occurred!
The command '/bin/sh -c mkdir $build && cd $build && cmake .. && cmake --build .' returned a non-zero code: 1

**Comment by pengzhendong** [comment]
@LeonWlw Use the image from docker-hub directly.

mobvoiwenet/wenet:latest

**Comment by jldeng3** [comment]
it means you install libgflags-dev,so Targets Defined: gflags_static;gflags_nothreads_static,Targets not yet defined: gflags_shared;gflags_nothreads_shared,solution:sudo apt autoremove libgflags-dev
