### ISSUE TITLE
x86 server   model broken link

### ISSUE THREAD

**Issue by python-linming** [wenet-e2e/wenet#457]
I am loading the x86 server pre-training model, but the file does not exist:
http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/aishell2/20210602_unified_transformer_exp_server.tar.gz
http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/aishell/20210602_unified_transformer_server.tar.gz
Thank you

**Comment by robin1001** [comment]
@whiteshirt0429 , please fix it.

**Comment by pengzhendong** [comment]
http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/aishell2/20210602_unified_transformer_server.tar.gz
http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/aishell/20210601_unified_transformer_server.tar.gz
