### ISSUE TITLE
The Position Encoding for U2++ model with BiTransformerDecoder

### ISSUE THREAD

**Issue by yjiangling** [wenet-e2e/wenet#460]
I see that the inputs are reversed as the input of the right decoder, but the position encodings are not. The left decoder inputs and the right decoder inputs use the same position encoding, is it OK?

I'm looking forward to your answer. Thanks a lot.

**Comment by robin1001** [comment]
It's not, the forward and backward decoder have their own encoding and embedding. 
please see wenet/transformer/decoder.py:BiTransformerDecoder, which consists of two separate decoders.

**Comment by yjiangling** [comment]
> It's not, the forward and backward decoder have their own encoding and embedding.
> please see wenet/transformer/decoder.py:BiTransformerDecoder, which consists of two separate decoders.

Oh, thanks, I see. The two decoders have different embedding, but the position encoding are all triangle function, that is to say, the positional encoding added to the two decoders are same? For example, if the inputs of the two decoders are like this: 
[<sos>, c1,  c2, c3, c4, c5] and [<sos>, c5, c4, c3, c2, c1], and the positional encoding added to the two decoders are [p0, p1, p2, p3, p4], they are same, right?

**Comment by robin1001** [comment]
exactly.

**Comment by yjiangling** [comment]
> exactly.

Ok, thanks a lot for the reply~
