### ISSUE TITLE
how to calculate the cached_feature_size in torch_asr_decoder.cc

### ISSUE THREAD

**Issue by godjealous** [wenet-e2e/wenet#461]
const int cached_feature_size = 1 + right_context - subsampling_rate; +97 torch_asr_decoder.cc
why the feat cached size is calculated like this ?
What about the left context ?

**Comment by robin1001** [comment]
please see https://wenet-e2e.github.io/wenet/runtime.html.

![image](https://user-images.githubusercontent.com/6036624/122493261-f817c800-d019-11eb-898a-5671e67d2c04.png)

**Comment by Slyne** [comment]
@godjealous In the above [link](https://wenet-e2e.github.io/wenet/runtime.html) mentioned, right_context=6, subsample_rate=4
You may refer to codes [here](https://github.com/wenet-e2e/wenet/blob/7f00996e018839f0e2bb8835ef2452896d74ef1e/wenet/transformer/subsampling.py#L93)
