### ISSUE TITLE
question about example of aishell

### ISSUE THREAD

**Issue by Jefferyoung96** [wenet-e2e/wenet#476]
**Describe the bug**
 when i run the command "bash run.sh --stage 1 --stop-stage 1"
 it shows 
_**Traceback (most recent call last):
  File "tools/compute_cmvn_stats.py", line 10, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'**_

but I have already install pytorch

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MomentOfTime** [comment]
i meet the same error as fellow:
`(wenet) lyl@lyl-To-be-filled-by-O-E-M:~/pubsrc/wenet/examples/aishell/s0$ sudo bash run.sh --stage 1 --stop-stage 1
Traceback (most recent call last):
  File "tools/compute_cmvn_stats.py", line 10, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
(wenet) lyl@lyl-To-be-filled-by-O-E-M:~/pubsrc/wenet/examples/aishell/s0$ python
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
>>> 
`
these  Installation calls of readne tutorial have been run succcessfully
`conda create -n wenet python=3.8
conda activate wenet
pip install -r requirements.txt
conda install pytorch=1.10.0 torchvision torchaudio=0.10.0 cudatoolkit=11.1 -c pytorch -c conda-forge`

**Comment by MomentOfTime** [comment]
> i meet the same error as fellow:
> 
> ```
> (wenet) lyl@lyl-To-be-filled-by-O-E-M:~/pubsrc/wenet/examples/aishell/s0$ sudo bash run.sh --stage 1 --stop-stage 1
> Traceback (most recent call last):
>   File "tools/compute_cmvn_stats.py", line 10, in <module>
>     import torch
> ModuleNotFoundError: No module named 'torch'
> (wenet) lyl@lyl-To-be-filled-by-O-E-M:~/pubsrc/wenet/examples/aishell/s0$ python
> Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
> [GCC 7.5.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import torch
> >>> torch.cuda.is_available()
> True
> ```
> 
> these Installation calls of readne tutorial have been run succcessfully
> 
> ```
> conda create -n wenet python=3.8
> conda activate wenet
> pip install -r requirements.txt
> conda install pytorch=1.10.0 torchvision torchaudio=0.10.0 cudatoolkit=11.1 -c pytorch -c conda-forge
> ```

by dirctly running `tools/compute_cmvn_stats.py --num_workers 8 --train_config $train_config \
    --in_scp data/${train_set}/wav.scp \
    --out_cmvn data/$train_set/global_cmvn`  in command line, it can skip this error.
`lyl@lyl-To-be-filled-by-O-E-M:~/pubsrc/wenet/examples/aishell/s0$ tools/compute_cmvn_stats.py --num_workers 8 --train_config conf/train_conformer.yaml --in_scp data/train/wav.scp --out_cmvn data/train/global_cmvn
using resample and new sample rate is 16000
/home/lyl/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
processed 1000 wavs, 453470 frames
processed 2000 wavs, 908369 frames
processed 3000 wavs, 1353136 frames
processed 4000 wavs, 1797996 frames
`
maybe there exist some context enviornment problems

**Comment by MomentOfTime** [comment]
> > i meet the same error as fellow:
> > ```
> > (wenet) lyl@lyl-To-be-filled-by-O-E-M:~/pubsrc/wenet/examples/aishell/s0$ sudo bash run.sh --stage 1 --stop-stage 1
> > Traceback (most recent call last):
> >   File "tools/compute_cmvn_stats.py", line 10, in <module>
> >     import torch
> > ModuleNotFoundError: No module named 'torch'
> > (wenet) lyl@lyl-To-be-filled-by-O-E-M:~/pubsrc/wenet/examples/aishell/s0$ python
> > Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
> > [GCC 7.5.0] :: Anaconda, Inc. on linux
> > Type "help", "copyright", "credits" or "license" for more information.
> > >>> import torch
> > >>> torch.cuda.is_available()
> > True
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > these Installation calls of readne tutorial have been run succcessfully
> > ```
> > conda create -n wenet python=3.8
> > conda activate wenet
> > pip install -r requirements.txt
> > conda install pytorch=1.10.0 torchvision torchaudio=0.10.0 cudatoolkit=11.1 -c pytorch -c conda-forge
> > ```
> 
> by dirctly running the command as fellow in command line, it can skip this error of `no named module torch`.
> 
> ```
> tools/compute_cmvn_stats.py --num_workers 8 --train_config $train_config \
>     --in_scp data/${train_set}/wav.scp \
>     --out_cmvn data/$train_set/global_cmvn 
> ```
> 
> ```
> lyl@lyl-To-be-filled-by-O-E-M:~/pubsrc/wenet/examples/aishell/s0$ tools/compute_cmvn_stats.py --num_workers 8 --train_config conf/train_conformer.yaml --in_scp data/train/wav.scp --out_cmvn data/train/global_cmvn
> using resample and new sample rate is 16000
> /home/lyl/miniconda3/envs/wenet/lib/python3.8/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
>   warnings.warn(_create_warning_msg(
> processed 1000 wavs, 453470 frames
> processed 2000 wavs, 908369 frames
> processed 3000 wavs, 1353136 frames
> processed 4000 wavs, 1797996 frames
> ```
> 
> maybe there exist some context enviornment problems

i just know the reason of `no module named torch`,
we can run the run.sh from stage -1 to avoid the error. i firstly directly run the stage 1 so that i find there no python enviornment.
```
cd example/aishell/s0
bash run.sh --stage -1 --stop-stage -1
bash run.sh --stage 0 --stop-stage 0
bash run.sh --stage 1 --stop-stage 1
bash run.sh --stage 2 --stop-stage 2
bash run.sh --stage 3 --stop-stage 3
bash run.sh --stage 4 --stop-stage 4
bash run.sh --stage 5 --stop-stage 5
bash run.sh --stage 6 --stop-stage 6
```
