### ISSUE TITLE
终端编译报错

### ISSUE THREAD

**Issue by wangbq18** [wenet-e2e/wenet#482]
**Describe the bug**
您好，我拉了最新的code, 然后按照README.md, 在wenet/runtime/device/android/wenet目录下执行
./gradlew build
报错，错误信息如下，请问怎么解决呢？

运行系统ubuntu16.04

-   ninja: Entering directory `/wenet/runtime/device/android/wenet/app/.cxx/cmake/debug/arm64-v8a'
-   [1/29] Building CXX object CMakeFiles/decoder.dir/decoder/torch_asr_model.cc.o
-   [2/29] Building CXX object CMakeFiles/decoder.dir/decoder/ctc_endpoint.cc.o
-   [3/29] Building CXX object CMakeFiles/decoder.dir/decoder/ctc_prefix_beam_search.cc.o
-   [4/29] Building CXX object CMakeFiles/frontend.dir/frontend/fft.cc.o
-   [5/29] Building CXX object CMakeFiles/utils.dir/utils/utils.cc.o
-   [6/29] Linking CXX static library libutils.a
-   [7/29] Building CXX object CMakeFiles/frontend.dir/frontend/feature_pipeline.cc.o
-   [8/29] Linking CXX static library libfrontend.a
-   [9/29] Building CXX object kaldi/CMakeFiles/kaldi-util.dir/util/kaldi-io.cc.o
-   [10/29] Building CXX object kaldi/CMakeFiles/kaldi-util.dir/util/parse-options.cc.o
-   [11/29] Building CXX object kaldi/CMakeFiles/kaldi-util.dir/util/simple-io-funcs.cc.o
-   [12/29] Building CXX object kaldi/CMakeFiles/kaldi-base.dir/base/kaldi-error.cc.o
-   [13/29] Building CXX object kaldi/CMakeFiles/kaldi-util.dir/util/text-utils.cc.o
-   [14/29] Building CXX object CMakeFiles/decoder_main.dir/bin/decoder_main.cc.o
-   [15/29] Building CXX object kaldi/CMakeFiles/kaldi-base.dir/base/kaldi-math.cc.o
-   [16/29] Linking CXX static library kaldi/libkaldi-base.a
-   [17/29] Linking CXX static library kaldi/libkaldi-util.a
-   [18/29] Building CXX object CMakeFiles/decoder.dir/decoder/torch_asr_decoder.cc.o
-   [19/29] Building CXX object CMakeFiles/decoder.dir/decoder/ctc_wfst_beam_search.cc.o
-   [20/29] Building CXX object kaldi/CMakeFiles/kaldi-lat.dir/lat/lattice-functions.cc.o
-   [21/29] Building CXX object kaldi/CMakeFiles/kaldi-lat.dir/lat/determinize-lattice-pruned.cc.o
-   [22/29] Linking CXX static library kaldi/libkaldi-lat.a
-   [23/29] Building CXX object CMakeFiles/wenet.dir/wenet.cc.o
-   [24/29] Building CXX object kaldi/CMakeFiles/kaldi-decoder.dir/decoder/lattice-faster-online-decoder.cc.o
-   [25/29] Building CXX object kaldi/CMakeFiles/kaldi-decoder.dir/decoder/lattice-faster-decoder.cc.o
-   [26/29] Linking CXX static library kaldi/libkaldi-decoder.a
-   [27/29] Linking CXX static library libdecoder.a
-   [28/29] Linking CXX executable decoder_main
-   FAILED: decoder_main 

  : && /usr/local/android-home/android-sdk-linux/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --gcc-toolchain=/usr/local/android-home/android-sdk-linux/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/usr/local/android-home/android-sdk-linux/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/sysroot  -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -std=c++14 -DC10_USE_GLOG -DC10_USE_MINIMAL_GLOG -DANDROID -Wno-c++11-narrowing -fexceptions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections CMakeFiles/decoder_main.dir/bin/decoder_main.cc.o  -o decoder_main -L/wang/ASR/wenet/runtime/device/android/wenet/app/src/main/cpp/../../../build/wenet-openfst-android-1.0.0.aar/jni/arm64-v8a -llog -lgflags_nothreads -lglog -lfst libutils.a libfrontend.a libdecoder.a -landroid -lc++_shared kaldi/libkaldi-decoder.a kaldi/libkaldi-lat.a kaldi/libkaldi-util.a kaldi/libkaldi-base.a libutils.a -llog -lgflags_nothreads -lglog -lfst /wang/ASR/wenet/runtime/device/android/wenet/app/build/pytorch_android-1.6.0.aar/jni/arm64-v8a/libpytorch_jni.so /wang/ASR/wenet/runtime/device/android/wenet/app/build/pytorch_android-1.6.0.aar/jni/arm64-v8a/libfbjni.so -latomic -lm && :
  /usr/local/android-home/android-sdk-linux/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: decoder_main: hidden symbol `_Unwind_Resume' in /usr/local/android-home/android-sdk-linux/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/libgcc_real.a(unwind-dw2.o) is referenced by DSO
  /usr/local/android-home/android-sdk-linux/ndk/21.1.6352462/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: final link failed: Bad value
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  [29/29] Linking CXX shared library /wang/ASR/wenet/runtime/device/android/wenet/app/build/intermediates/cmake/debug/obj/arm64-v8a/libwenet.so
  ninja: build stopped: subcommand failed.

**Comment by pengzhendong** [comment]
Try #485
