### ISSUE TITLE
中文预训练模型的识别结果和ground truth差异很大

### ISSUE THREAD

**Issue by xiabingquan** [wenet-e2e/wenet#486]
我按照下图所示的文档编译运行时程序
![image](https://user-images.githubusercontent.com/53991699/123984483-3d170380-d9f7-11eb-8f40-56abd255f0bc.png)
![image](https://user-images.githubusercontent.com/53991699/123984516-4607d500-d9f7-11eb-92b5-1d4de8b35f51.png)

 然后测试了一段一分钟左右的音频，但是识别结果非常奇怪，请问问题出在哪里？谢谢
![image](https://user-images.githubusercontent.com/53991699/123984612-5a4bd200-d9f7-11eb-8702-d113a2f38c77.png)

**Comment by robin1001** [comment]
Sorry, we don't know, the details are not given.

**Comment by EnHuiPug** [comment]
FYI：输入的音频文件需要是单声道的，立体声的话结果就会很奇怪。
