### ISSUE TITLE
Using GigaSpeech model in WeNet Server (x86) ASR Demo

### ISSUE THREAD

**Issue by ReubenLim0202** [wenet-e2e/wenet#495]
Hi. I would like to test out the GigaSpeech model. I wanted to test ASR for English. Is there a way to test this model using the steps from "WeNet Server (x86) ASR Demo". I tried using the pre-built docker but the model doesn't seems suitable for this demo.

**Comment by robin1001** [comment]
Yes, it's just a non-streaming model now, and the docker only supports streaming model by default setting.
You can just wait for our streaming model, it should be ready in a few days.

**Comment by robin1001** [comment]
Or you can just to set --chunk-size=-1 to use the non-streaming model.

**Comment by ReubenLim0202** [comment]
Alright, thank you so much.

**Comment by Jackiexiao** [comment]
> Yes, it's just a non-streaming model now, and the docker only supports streaming model by default setting.
> You can just wait for our streaming model, it should be ready in a few days.

hi,  thx for your work, has this streaming model been released yet? @robin1001
