### ISSUE TITLE
problems when build grpc version

### ISSUE THREAD

**Issue by Dsqds** [wenet-e2e/wenet#500]
due to internet problem,i munually git clone grpc to the /wenet/runtime/server/x86/fc_base/grpc-src and install it.
i can pass grpc test and wenet-websocket build respectively,so i think the single grpc and single wenet-websocket are right
but when build wenet-grpc , some strange errors occurred
in /wenet/runtime/server/x86/build,
cmake -DGRPC=ON .. 
cmake --build .
the error are as follows:

[ 53%] Building CXX object CMakeFiles/grpc_server_main.dir/bin/grpc_server_main.cc.o
/usr/bin/c++   -I/home/wenet/runtime/server/x86 -I/home/wenet/runtime/server/x86/kaldi -I/home/wenet/runtime/server/x86/fc_base/gflags-build/include -I/home/wenet/runtime/server/x86/fc_base/glog-src/src -I/home/wenet/runtime/server/x86/fc_base/glog-build -I/home/wenet/runtime/server/x86/fc_base/boost-src -I/home/wenet/runtime/server/x86/fc_base/openfst-subbuild/openfst-populate-prefix/include -I/home/wenet/runtime/server/x86/grpc -isystem /home/wenet/runtime/server/x86/fc_base/libtorch-src/include -isystem /home/wenet/runtime/server/x86/fc_base/libtorch-src/include/torch/csrc/api/include  -std=c++14 -pthread -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -DC10_USE_GLOG   -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++14 -o CMakeFiles/grpc_server_main.dir/bin/grpc_server_main.cc.o -c /home/wenet/runtime/server/x86/bin/grpc_server_main.cc
/home/wenet/runtime/server/x86/bin/grpc_server_main.cc: In function 'int main(int, char**)':
/home/wenet/runtime/server/x86/bin/grpc_server_main.cc:40:32: error: no matching function for call to 'wenet::GrpcServer::GrpcServer(std::shared_ptr<wenet::FeaturePipelineConfig>&, std::shared_ptr<wenet::DecodeOptions>&, std::shared_ptr<fst::SymbolTable>&, std::shared_ptr<wenet::TorchAsrModel>&, std::shared_ptr<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > >&)'
   40 |                             fst);
      |                                ^
In file included from /home/wenet/runtime/server/x86/fc_base/openfst-subbuild/openfst-populate-prefix/include/fst/fst.h:21,
                 from /home/wenet/runtime/server/x86/fc_base/openfst-subbuild/openfst-populate-prefix/include/fst/expanded-fst.h:16,
                 from /home/wenet/runtime/server/x86/fc_base/openfst-subbuild/openfst-populate-prefix/include/fst/fstlib.h:28,
                 from /home/wenet/runtime/server/x86/decoder/torch_asr_decoder.h:13,
                 from /home/wenet/runtime/server/x86/decoder/params.h:10,
                 from /home/wenet/runtime/server/x86/bin/grpc_server_main.cc:19:
/home/wenet/runtime/server/x86/grpc/grpc_server.h:104:28: note: candidate: 'wenet::GrpcServer::GrpcServer(const wenet::GrpcServer&)'
  104 |   DISALLOW_COPY_AND_ASSIGN(GrpcServer);
      |                            ^~~~~~~~~~
/home/wenet/runtime/server/x86/fc_base/openfst-subbuild/openfst-populate-prefix/include/fst/compat.h:29:3: note: in definition of macro 'DISALLOW_COPY_AND_ASSIGN'
   29 |   type(const type&);                      \
      |   ^~~~
/home/wenet/runtime/server/x86/grpc/grpc_server.h:104:28: note:   candidate expects 1 argument, 5 provided
  104 |   DISALLOW_COPY_AND_ASSIGN(GrpcServer);
      |                            ^~~~~~~~~~
/home/wenet/runtime/server/x86/fc_base/openfst-subbuild/openfst-populate-prefix/include/fst/compat.h:29:3: note: in definition of macro 'DISALLOW_COPY_AND_ASSIGN'
   29 |   type(const type&);                      \
      |   ^~~~
In file included from /home/wenet/runtime/server/x86/bin/grpc_server_main.cc:20:
/home/wenet/runtime/server/x86/grpc/grpc_server.h:85:3: note: candidate: 'wenet::GrpcServer::GrpcServer(std::shared_ptr<wenet::FeaturePipelineConfig>, std::shared_ptr<wenet::DecodeOptions>, std::shared_ptr<fst::SymbolTable>, std::shared_ptr<wenet::TorchAsrModel>, std::shared_ptr<fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> > > >)'
   85 |   GrpcServer(std::shared_ptr<FeaturePipelineConfig> feature_config,
      |   ^~~~~~~~~~
/home/wenet/runtime/server/x86/grpc/grpc_server.h:89:49: note:   no known conversion for argument 5 from 'shared_ptr<fst::Fst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >>' to 'shared_ptr<fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >>'
   89 |              std::shared_ptr<fst::StdVectorFst> fst)
      |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
make[2]: *** [CMakeFiles/grpc_server_main.dir/build.make:66: CMakeFiles/grpc_server_main.dir/bin/grpc_server_main.cc.o] Error 1
make[2]: Leaving directory '/home/wenet/runtime/server/x86/build'
make[1]: *** [CMakeFiles/Makefile2:361: CMakeFiles/grpc_server_main.dir/all] Error 2
make[1]: Leaving directory '/home/wenet/runtime/server/x86/build'
make: *** [Makefile:155: all] Error 2

**Comment by robin1001** [comment]
please first try the version without gRPC, if it works then try gRPC version to avoid some env or setting problems.
