### ISSUE TITLE
TAL Corpus

### ISSUE THREAD

**Issue by temp1096** [wenet-e2e/wenet#514]
Hello! In the multi-cn recipe, there is reference made to the 600 hour TAL corpus. I looked around a bit online for more information about this corpus and wasn't able to find any.

Could you please share details to a homepage, download link, paper, anything?

**Comment by double22a** [comment]
> e multi-cn recipe, there is reference made to the 600 hour TAL corpus. I looked around a bit online for more information about this corpus and wasn't able to find any.

[TAL_ASR, TAL_CSASR](https://ai.100tal.com/dataset)

**Comment by temp1096** [comment]
Great, thank you for sharing.
