### ISSUE TITLE
How to find why TLG decoding is harmful for testset cer

### ISSUE THREAD

**Issue by LeonWlw** [wenet-e2e/wenet#516]
With a 1.3G TLG.fst for decoding, I got a relative 15% rising on cer than only attention rescoring by full chunk size. Is there anyone can help me figure out what is the issue? I found @pengzhendong said issue about LM weight. I can't find which param than he pointed out.Is it the rescoring_weight? But turning it is useless for me.

**Comment by double22a** [comment]
@LeonWlw Hi，How to solve this problem?
