### ISSUE TITLE
Worse result using runtime than recognize.py

### ISSUE THREAD

**Issue by DrBlueberry** [wenet-e2e/wenet#519]
Hi, I follow the Librispeech example to train an 8k English unified conformer model.
The WER using recognize.py is about 12%, and the result looks fine. But when I use decoder_main to decode, the WER is 23%.
I am not sure if this is related to [#356](https://github.com/wenet-e2e/wenet/issues/356#issue-874838867). But I have checked python and runtime both use the same dict, set dither=0. The code is also updated.
Here I attach both commands I used. I add an option in decoder.sh to pass the sample_rate to decoder_main
```
  python wenet/bin/recognize.py --gpu $gpu_id \
      --mode $mode \
      --config $dir/train.yaml \
      --test_data data/$test/format.data \
      --checkpoint $decode_checkpoint \
      --beam_size 10 \
      --batch_size 1 \
      --penalty 0.0 \
      --dict $dict \
      --result_file $test_dir/text_bpe \
      --ctc_weight $ctc_weight \
      ${decoding_chunk_size:+--decoding_chunk_size $decoding_chunk_size}
      tools/spm_decode --model=${bpemodel}.model --input_format=piece < $test_dir/text_bpe | sed -e "s/▁/ /g" >$test_dir/text
```
```
./tools/decode.sh --nj 1 \
    --ctc_weight 0.5 --rescoring_weight 1.0 \
    --sample_rate 8000 \
    --chunk_size $decoding_chunk_size \
    data/$test/wav.scp data/$test/text $dir/final.zip \
    $dict \
    $dir/runtime_${test}
tail $dir/runtime_${test}/wer
```
I also checked the results, for most utterances, the results from runtime look good.
But In some other cases, the result looks extremely weird and has a lot of deletion errors
Here are two examples:
```
python:  ADDED BANKER ACCOUNT
runtime: UM
```
```
python: I WANT TO CONTINUE
runtime:  I
```
The following is the log of the second utterance.
```
I0720 15:35:02.428913 77100 torch_asr_model.cc:41] torch model info subsampling_rate 4 right context 6 sos 5197 eos 5197 is bidirectional decoder 0
I0720 15:35:02.445143 77100 decoder_main.cc:67] num frames 232
I0720 15:35:02.445442 77100 torch_asr_decoder.cc:120] Required 2147483647 get 232
I0720 15:35:03.492915 77100 torch_asr_decoder.cc:295] Partial CTC result ill
I0720 15:35:03.493304 77100 torch_asr_decoder.cc:295] Partial CTC result ill
I0720 15:35:03.994511 77100 torch_asr_decoder.cc:90] Rescoring cost latency: 501ms.
I0720 15:35:03.994554 77100 decoder_main.cc:84] Partial result: i
I0720 15:35:03.994558 77100 decoder_main.cc:107] 148-4-0044701-0044935 Final result: i
I0720 15:35:03.994566 77100 decoder_main.cc:108] Decoded 2340ms audio taken 1549ms.
```
Any help would be greatly appreciated.

**Comment by robin1001** [comment]
I have no idea, have you figured it out?

**Comment by DrBlueberry** [comment]
Sorry for the late reply. The problem is still unsolved.

**Comment by DrBlueberry** [comment]
I figured it out. It is because some audios have 2 channels. The recognize.py directly uses the fbank extracted by Kaldi, which extracted the left channel by default.  However, the wenet runtime has to extract the fbank itself again, and this causes the issue.

**Comment by nocoolsandwich** [comment]
> I figured it out. It is because some audios have 2 channels. The recognize.py directly uses the fbank extracted by Kaldi, which extracted the left channel by default. However, the wenet runtime has to extract the fbank itself again, and this causes the issue.

How to handle this in runtime mode?Preprocessing it to 1 channel before inference?
