### ISSUE TITLE
1分钟DEMO开始识别后报错websocket连接失败

### ISSUE THREAD

**Issue by insistenceofgream** [wenet-e2e/wenet#528]
> Desktop ():**
>  - OS: [AWS Ubuntu LINUX]
>  - Browser [chrome]
> ![image](https://user-images.githubusercontent.com/23382208/126453180-6d5a9e4f-95f9-4459-88c9-b248506b2c84.png)
> 
> 

### 按照说明在AWS上部署好服务以后，点击开始识别，js会报错连接失败
![image](https://user-images.githubusercontent.com/23382208/126454096-51f7d90c-6658-4354-a491-a72bd140c22c.png)
### 服务器上端口监听情况
![image](https://user-images.githubusercontent.com/23382208/126454216-e76682ab-309e-4abd-ae70-980ae9c92ab6.png)

**Comment by pengzhendong** [comment]
127.0.0.0 => 127.0.0.1

**Comment by insistenceofgream** [comment]
127.0.0.1和localhost都不行

![image](https://user-images.githubusercontent.com/23382208/126580902-1047b0f5-e99f-469b-a680-8ea7e56ee35e.png)
![image](https://user-images.githubusercontent.com/23382208/126580947-2caddd3f-29d7-4f14-89b2-0ad2b49dd2de.png)

**Comment by pengzhendong** [comment]
You should input the IP of the AWS.
And check that the firewall is enabled.

**Comment by insistenceofgream** [comment]
AWS IP doesn't work also... And the firewall is enabled.

Is calling port 10086 of my server via 'ws://' the correct direction? If yes, then I will close my ticket and figure it out by myself.
