### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by frankenliu** [wenet-e2e/wenet#530]
there is a bug in tools/compute_cmvn_stats.py.

torchaudio.backend.sox_io_backend.load(
                    filepath=wav_path,
                    num_frames=end_frame - start_frame,
                    offset=start_frame)
shoule be:
torchaudio.backend.sox_io_backend.load(
                    filepath=wav_path,
                    num_frames=end_frame - start_frame,
                    frame_offset=start_frame)

docs in torchaudio:
torchaudio.backend.sox_io_backend.load(filepath: str, frame_offset: int = 0, num_frames: int = -1, normalize: bool = True, channels_first: bool = True, format: Optional[str] = None) → Tuple[torch.Tensor, int]

**Comment by whiteshirt0429** [comment]
maybe you can commit a pr directly

**Comment by robin1001** [comment]
fixed.
