### ISSUE TITLE
Question of batch-decode in wenet/bin/recognize.py

### ISSUE THREAD

**Issue by xiaolling** [wenet-e2e/wenet#531]
Hi,
    When I use "wenet/bin/recognize.py" to test my model,  In the "ctc greedy search" decode_mode, I change the batch-size : (1, 2, 5,10)， the WER is different:(1.38%, 1.59%, 1.71%, 1.73%). The trained model is nostreaming AED-Conformer and followed the aishell/s0 & "train_conformer.yaml", and I don't change the train and recognize param expect "decode batch-size", train & test data is my own dataset.
    This doesn't seem to be a scripting problem on my part. I'm not sure that's a bug? mask problem? 
    At last, thanks for you work, is cool !

**Comment by robin1001** [comment]
Yes, there may be some bugs when you decode Conformer with batch decoding mode. It is related to mask. So batch decoding is not suggested in wenet, and batch decoding is not supported in `ctc_prefix_search` and `attention_rescoding` mode.
