### ISSUE TITLE
[runtime]cmake error

### ISSUE THREAD

**Issue by neneluo** [wenet-e2e/wenet#535]
Hi, I met the following error during "cmake --build ." when building the runtime, and I didn't find solution from former issues. Please help check. Thanks.

gcc: 7.3.1
cmake: 3.17.5
system: CentOS Linux release 7.6.1810

error message:
libtool: link: g++ -std=c++11 -o .libs/fstcompose fstcompose.o fstcompose-main.o  -L/absolute/path/streaming/wenet/runtime/server/x86/fc_base/gflags-build -L/absolute/path/streaming/wenet/runtime/
server/x86/fc_base/glog-build ../script/.libs/libfstscript.so ../lib/.libs/libfst.so -lm -ldl -lgflags_nothreads -lglog -lpthread -Wl,-rpath -Wl,/absolute/path/streaming/wenet/runtime/server/x86/fc_b$
se/openfst-subbuild/openfst-populate-prefix/lib
../lib/.libs/libfst.so: undefined reference to `__cxa_throw_bad_array_new_length'
../lib/.libs/libfst.so: undefined reference to `operator delete(void*, unsigned long)'
../lib/.libs/libfst.so: undefined reference to `__cxa_throw_bad_array_new_length'
../lib/.libs/libfst.so: undefined reference to `operator delete(void*, unsigned long)'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
make[3]: *** [fstarcsort] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [fstclosure] Error 1
../lib/.libs/libfst.so: undefined reference to `__cxa_throw_bad_array_new_length'
../lib/.libs/libfst.so: undefined reference to `operator delete(void*, unsigned long)'
collect2: error: ld returned 1 exit status
make[3]: *** [fstcompile] Error 1
../lib/.libs/libfst.so: undefined reference to `__cxa_throw_bad_array_new_length'
../lib/.libs/libfst.so: undefined reference to `operator delete(void*, unsigned long)'
collect2: error: ld returned 1 exit status
make[3]: *** [fstcompose] Error 1
make[3]: Leaving directory `/absolute/path/streaming/wenet/runtime/server/x86/fc_base/openfst-build/src/bin'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/absolute/path/streaming/wenet/runtime/server/x86/fc_base/openfst-build/src'

**Comment by robin1001** [comment]
Please first try build with docker, then compare the environment with your local build to find the problem.
Typically, local build is not recommended.

**Comment by neneluo** [comment]
> Please first try build with docker, then compare the environment with your local build to find the problem.
> Typically, local build is not recommended.

Thanks for your reply!
I use the docker and the runtime is now up and running. But I get two more questions, (1) How to run the offline ASR demo in runtime with GPU? The program now runs completely on the CPU. (2) What’s the rtf should be when decoding with chunk 16 (model trained using aishell/s1/conf/train_unified_conformer.yaml). My result is 0.18. Is this a normal result?

**Comment by robin1001** [comment]
1) You have to modify the runtime code if you want to support GPU.
2) It depends on your model size and machine. 0.18 is a reasonable number for chunk 16.
