### ISSUE TITLE
x86 cmake error, the error relates with openfst, could anyone give a solution?

### ISSUE THREAD

**Issue by echoaimaomao** [wenet-e2e/wenet#537]
![Screenshot from 2021-07-26 21-59-32](https://user-images.githubusercontent.com/8649753/127001746-0a634887-9467-4b65-b5a9-a778e8df7c49.png)

**Comment by robin1001** [comment]
There is a blank in your path, please change it and retry.

**Comment by echoaimaomao** [comment]
It works! Thank you very much.
