### ISSUE TITLE
Are the pre-trained models available somewhere?

### ISSUE THREAD

**Issue by QuantScientist** [wenet-e2e/wenet#54]
Many thanks!

**Comment by robin1001** [comment]
It's on developing now, will provide it once it is ready.

**Comment by whiteshirt0429** [comment]
we have uploaded some pre-trained models, the details can be seen in s0/README

**Comment by QuantScientist** [comment]
Thanks,
Here https://github.com/mobvoi/wenet/blob/main/examples/librispeech/s0/README.md? 
I don't see anything there.

**Comment by mikelei** [comment]
There are pre-trained models for AIShell in:
https://github.com/mobvoi/wenet/tree/main/examples/aishell/s0/README.md

Librispeech models need to be uploaded. @whiteshirt0429

**Comment by whiteshirt0429** [comment]
I have uploaded a librispeech u2 model，the model link is "http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/librispeech/20210122_unified_conformer_exp.tar.gz" and you can use git hash "1ea7515e4722f4e05a5985f587120c994a93694a" to load it and decode

**Comment by whiteshirt0429** [comment]
The more details can be found in  https://github.com/mobvoi/wenet/tree/main/examples/librispeech/s0/README.md

**Comment by whiteshirt0429** [comment]
I have uploaded a librispeech u2 model，the model link is "http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/librispeech/20210122_unified_conformer_exp.tar.gz" and you can use git hash "1ea7515e4722f4e05a5985f587120c994a93694a" to load it and decode.
The more details can be found in https://github.com/mobvoi/wenet/tree/main/examples/librispeech/s0/README.md.

**Comment by whiteshirt0429** [comment]
I have uploaded a librispeech u2 model，the model link is "http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/librispeech/20210122_unified_conformer_exp.tar.gz" and you can use git hash "1ea7515e4722f4e05a5985f587120c994a93694a" to load it and decode.

**Comment by whiteshirt0429** [comment]
I have uploaded a librispeech u2 model，the model link is "http://mobvoi-speech-public.ufile.ucloud.cn/public/wenet/librispeech/20210122_unified_conformer_exp.tar.gz" and you can use git hash "1ea7515e4722f4e05a5985f587120c994a93694a" to load it.

**Comment by mikelei** [comment]
It seems oss is not accessible from outside China. Maybe put in some other places, such as dropbox?

**Comment by jprobichaud** [comment]
Thanks a lot for providing this!  I see that in the pretrained model archives, the bpe models aren't available.  If one wants to try these models on different audio files, we would need this file.  Otherwise, we have to download all the training data and rebuild to bpe model.

**Comment by arkadyark** [comment]
Hey @jprobichaud - I was stuck on the same thing. After I looked a bit more, I was able to find a file (for instance in 20210215_unified_conformer_exp.tar.gz) called "train_960_unigram5000.model" which is the BPE model. This should work for you!
