### ISSUE TITLE
利用docker解码出错

### ISSUE THREAD

**Issue by fivenick** [wenet-e2e/wenet#543]
运行命令：
./build/decoder_main \
    --chunk_size -1 \
    --wav_path $wav_path \
    --model_path $model_dir/final.zip \
    --dict_path $model_dir/words.txt 2>&1 | tee log.txt

报错：
I0727 10:59:35.462808    15 params.h:83] Reading model docker_resource/model/final.zip
terminate called after throwing an instance of 'c10::Error'
  what():  Method 'is_bidirectional_decoder' is not defined.
Exception raised from get_method at /home/wenet/runtime/server/x86/fc_base/libtorch-src/include/torch/csrc/jit/api/object.h:91 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f1f2f3bceb9 in /home/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libc10.so)
frame #1: <unknown function> + 0x6d39a (0x7f1f3f86039a in ./build/decoder_main)
frame #2: <unknown function> + 0x7ab59 (0x7f1f3f86db59 in ./build/decoder_main)
frame #3: <unknown function> + 0x79ec7 (0x7f1f3f86cec7 in ./build/decoder_main)
frame #4: <unknown function> + 0x461b5 (0x7f1f3f8391b5 in ./build/decoder_main)
frame #5: <unknown function> + 0x46821 (0x7f1f3f839821 in ./build/decoder_main)
frame #6: __libc_start_main + 0xf3 (0x7f1f2e60e0b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #7: <unknown function> + 0x45dde (0x7f1f3f838dde in ./build/decoder_main)

说明：
模型final.zip是我用wenet训练导出的，没有做任何改动，现在一脸懵，不知道该怎么处理这个错误。

**Comment by robin1001** [comment]
You have trained and exported the model with the old code, but tested with the lasted docker build. Just export your model with the lasted code then do the test, it should work.

**Comment by fivenick** [comment]
> You have trained and exported the model with the old code, but tested with the lasted docker build. Just export your model with the lasted code then do the test, it should work.

it works!!!!!!  thks
