### ISSUE TITLE
docker中导入模型失败

### ISSUE THREAD

**Issue by fivenick** [wenet-e2e/wenet#549]
在docker中执行脚本，导入模型时报错，错误代码如下所示。
之前也出现过类似错误，当时提问了，说是版本问题，后来我更想了最新的版本，生成模型后可以导入成功。
这次无意间将docker镜像又更新到最新，发现之前的模型再次无法导入，所以又重新将wenet升到最新版本，再次生成模型，结果发现还是导入不成功。。。。。。

错误信息：
(base) [yangxingya@sge_node_210 docker]$ docker run --rm -v /nfs/user/yangxingya/raid0/company_task/task32_wenet/wenet:/home/wenet_self -it wenet bash
root@0b3b18feac63:/# cd /home/wenet/runtime/server/x86
root@0b3b18feac63:/home/wenet/runtime/server/x86# export GLOG_logtostderr=1
root@0b3b18feac63:/home/wenet/runtime/server/x86# export GLOG_v=2
root@0b3b18feac63:/home/wenet/runtime/server/x86# wav_path=docker_resource/test.wav
root@0b3b18feac63:/home/wenet/runtime/server/x86# model_dir=docker_resource/model
root@0b3b18feac63:/home/wenet/runtime/server/x86# ./build/decoder_main \
>     --chunk_size -1 \
>     --wav_path $wav_path \
>     --model_path $model_dir/final.zip \
>     --dict_path $model_dir/words.txt 2>&1 | tee log.txt
I0730 02:36:32.943698    13 params.h:83] Reading model docker_resource/model/final.zip
terminate called after throwing an instance of 'c10::Error'
  what():  open file failed, file path: docker_resource/model/final.zip
Exception raised from FileAdapter at ../caffe2/serialize/file_adapter.cc:11 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f550131eeb9 in /home/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libc10.so)
frame #1: caffe2::serialize::FileAdapter::FileAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x2f5 (0x7f55038137a5 in /home/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #2: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x40 (0x7f5504c16320 in /home/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x79972 (0x7f55117ce972 in ./build/decoder_main)
frame #4: <unknown function> + 0x461b5 (0x7f551179b1b5 in ./build/decoder_main)
frame #5: <unknown function> + 0x46821 (0x7f551179b821 in ./build/decoder_main)
frame #6: __libc_start_main + 0xf3 (0x7f55005700b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #7: <unknown function> + 0x45dde (0x7f551179adde in ./build/decoder_main)

**Comment by pengzhendong** [comment]
Check whether `docker_resource/model/final.zip` exists.
