### ISSUE TITLE
runtime server Cmake Error

### ISSUE THREAD

**Issue by kli017** [wenet-e2e/wenet#551]
environment:
Ubuntu 18.04
gcc 7.5.0
cmake 3.14.0

command:
cd runtime/server/x86
mkdir build && cd build && cmake .. && cmake --build .

After camke .. 
got following error:

-- Populating glog
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kli/wenet/runtime/server/x86/fc_base/glog-subbuild
[100%] Built target glog-populate
-- Populating googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kli/wenet/runtime/server/x86/fc_base/googletest-subbuild
[100%] Built target googletest-populate
-- Populating boost
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kli/wenet/runtime/server/x86/fc_base/boost-subbuild
[100%] Built target boost-populate
-- Populating libtorch
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kli/wenet/runtime/server/x86/fc_base/libtorch-subbuild
[100%] Built target libtorch-populate
-- Configuring done
CMake Error: install(EXPORT "glog-targets" ...) includes target "glog" which requires target "gflags_nothreads_static" that is not in the export set.
-- Generating done
-- Build files have been written to: /home/kli/wenet/runtime/server/x86/build

**Comment by robin1001** [comment]
Please first try docker build, then compare the docker environment to your local to find the problem.

**Comment by dragen1860** [comment]
@kli017 Hi, i get the same erro as yours:
```
-- Build files have been written to: /media/sdf/long/audio/wav2vec_proj/wenet/runtime/server/x86/fc_base/glog-subbuild
/usr/games/cmake-3.18.0-rc1-Linux-x86_64/bin/cmake -S/media/sdf/long/audio/wav2vec_proj/wenet/runtime/server/x86/fc_base/glog-subbuild -B/media/sdf/long/audio/wav2vec_proj/wenet/runtime/server/x86/fc_base/glog-subbuild --check-build-system CMakeFiles/Makefile.cmake 0
/usr/games/cmake-3.18.0-rc1-Linux-x86_64/bin/cmake -E cmake_progress_start /media/sdf/long/audio/wav2vec_proj/wenet/runtime/server/x86/fc_base/glog-subbuild/CMakeFiles /media/sdf/long/audio/wav2vec_proj/wenet/runtime/server/x86/fc_base/glog-subbuild//CMakeFiles/progress.marks
/usr/bin/make -s -f CMakeFiles/Makefile2 all
[100%] Built target glog-populate
/usr/games/cmake-3.18.0-rc1-Linux-x86_64/bin/cmake -E cmake_progress_start /media/sdf/long/audio/wav2vec_proj/wenet/runtime/server/x86/fc_base/glog-subbuild/CMakeFiles 0
CMake Error at /usr/local/lib/cmake/gflags/gflags-nonamespace-targets.cmake:34 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: gflags_nothreads_static

  Targets not yet defined: gflags_static

Call Stack (most recent call first):
  /usr/local/lib/cmake/gflags/gflags-config.cmake:17 (include)
  fc_base/glog-src/CMakeLists.txt:51 (find_package)


-- Configuring incomplete, errors occurred!
See also "/media/sdf/long/audio/wav2vec_proj/wenet/runtime/server/x86/build/CMakeFiles/CMakeOutput.log".
```

anyy tips? thank you.

**Comment by kli017** [comment]
@dragen1860 hello, my build file actually has been successfully made even there is a cmake error. I just ignore the error and continue to build.
