### ISSUE TITLE
searcher_ -> Search(ctc_log_probs)函数出错

### ISSUE THREAD

**Issue by fivenick** [wenet-e2e/wenet#553]
调用torch_asr_decoder.cc文件中的函数searcher_ -> Search(ctc_log_probs)函数时,sometime it runs correct, but sometimes is runs error。
the error is ：
terminate called after throwing an instance of 'c10::Error'
  what():  selected index k out of range
Exception raised from topk_out_cpu at ../aten/src/ATen/native/Sorting.cpp:197 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f509c62aeb9 in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libc10.so)
frame #1: at::native::topk_out_cpu(at::Tensor&, at::Tensor&, at::Tensor const&, long, long, bool, bool) + 0x26f (0x7f509d6f8b2f in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0x11bbdd9 (0x7f509da13dd9 in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x11d781e (0x7f509da2f81e in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #4: at::topk_out(at::Tensor&, at::Tensor&, at::Tensor const&, long, long, bool, bool) + 0x189 (0x7f509da72149 in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #5: at::native::topk(at::Tensor const&, long, long, bool, bool) + 0x10d (0x7f509d6f86bd in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #6: <unknown function> + 0x11bbe25 (0x7f509da13e25 in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x11d9cd4 (0x7f509da31cd4 in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #8: at::topk(at::Tensor const&, long, long, bool, bool) + 0x130 (0x7f509dac0e70 in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x2ec0f51 (0x7f509f718f51 in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x11d9cd4 (0x7f509da31cd4 in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #11: at::Tensor::topk(long, long, bool, bool) const + 0x127 (0x7f509dc68f27 in /home/wenet_self/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so)
frame #12: <unknown function> + 0x76bfd (0x55f985a10bfd in ./decoder_main)
frame #13: <unknown function> + 0x5f1b6 (0x55f9859f91b6 in ./decoder_main)
frame #14: <unknown function> + 0x5e21c (0x55f9859f821c in ./decoder_main)
frame #15: <unknown function> + 0x50bdc (0x55f9859eabdc in ./decoder_main)
frame #16: <unknown function> + 0x473ec (0x55f9859e13ec in ./decoder_main)
frame #17: __libc_start_main + 0xf3 (0x7f509b87c0b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #18: <unknown function> + 0x46dde (0x55f9859e0dde in ./decoder_main)

**Comment by robin1001** [comment]
What is your dataset? public or private?
