### ISSUE TITLE
report out of range error on the debug version

### ISSUE THREAD

**Issue by flytair** [wenet-e2e/wenet#557]
https://github.com/wenet-e2e/wenet/blob/fbec55613f630f6a1e030e9cfe2c0508d0b5fd0f/runtime/core/decoder/ctc_wfst_beam_search.cc#L168

the error is gone, when changing the condition from:
cur - 1 < alignment.size()
to
cur + 1 < alignment.size()

**Comment by robin1001** [comment]
Great catch, Thanks
