### ISSUE TITLE
How to recognize one piece of audio with trained model?

### ISSUE THREAD

**Issue by Aiden1997** [wenet-e2e/wenet#559]
Excuse me,

I am a newbie, is there any friendly instruction for me to recognize one piece of audio with trained model?

I have downloaded wenet-1.0.0.zip and 20210204_conformer_exp.tar.gz, I tried to  recognize audio by /wenet/bin/recognize.py. But failed.

Could you give me some advice?

Thanks a lot!

Regards

**Comment by robin1001** [comment]
please follow https://wenet-e2e.github.io/wenet/tutorial.html

**Comment by Aiden1997** [comment]
> please follow https://wenet-e2e.github.io/wenet/tutorial.html

Thanks for your reply!

Do you mean the only way to recognize audio is to train the model on my own, and there is no trained model to use?

If so, where can I download the aishell-1 data?

Thank you!

Regards

**Comment by Aiden1997** [comment]
Thanks for your friendly reply!

By the way, I am following the instruction to Run with Local Build:
[https://github.com/wenet-e2e/wenet/tree/main/runtime/server/x86](url)

When I am running
`mkdir build && cd build && cmake .. && cmake --build .`

This error occurred:

[100%] Completed 'libtorch-populate'
[100%] Built target libtorch-populate
-- Found Torch: /home/mingzhe.liu/ASR/wenet-main/runtime/server/x86/fc_base/libtorch-src/lib/libtorch.so  
CMake Error at CMakeLists.txt:136 (add_subdirectory):
  add_subdirectory given source "kaldi" which is not an existing directory.


-- Configuring incomplete, errors occurred!
See also "/home/mingzhe.liu/ASR/wenet-main/runtime/server/x86/build/CMakeFiles/CMakeOutput.log".
See also "/home/mingzhe.liu/ASR/wenet-main/runtime/server/x86/build/CMakeFiles/CMakeError.log".


What should I do? Need your help!

Thank you!

Aiden

**Comment by robin1001** [comment]
Please follow the runtime README, first try to build with docker, then do local build to find the problem.
