### ISSUE TITLE
Flask starts the webscoket service and cannot record

### ISSUE THREAD

**Issue by koin-sj** [wenet-e2e/wenet#570]
Hello ,I have a question about the Web version of the WebSocket client。
I directly open the file web/templates/index.html and enter the address in the WebSocket URL, which can be used for recording recognition。

However, I started the service through Flask, opened the web page, and clicked to start recognition after entering the address in the WebSocket URL, but there was no response. I also set https.
may I know what is the reason?

**Comment by robin1001** [comment]
The record requires HTTPS for network service, and it is not required for local file.

**Comment by koin-sj** [comment]
> The record requires HTTPS for network service, and it is not required for local file.

Thanks for your reply, but I've already set HTTPS, I started the service through Flask(app.py), opened the web page, and clicked to start recognition after entering the address in the WebSocket URL, but there was no response.

**Comment by pengzhendong** [comment]
Just open the index.html file with the browser.
