### ISSUE TITLE
accelerate current wenet

### ISSUE THREAD

**Issue by Dsqds** [wenet-e2e/wenet#571]
When using current wenet, I feel the flow is a bit slow.

I want to try some method like tensorRt to accelerate it but I'm not sure the feasibility.

Could you please tell me some methods you have tried to accelerate wenet and their effect?

Thank a lot.

**Comment by robin1001** [comment]
We haven't try tensorRT. Some else have tried ONNX, about 20% speedup compared with Libtorch.

**Comment by Dsqds** [comment]
could you please give me github-link or other contact-way of the one who successfully tried onnx acceleration if you have?
I want to ask him about some details

**Comment by robin1001** [comment]
There is a Chinese blog here.  please see
https://mp.weixin.qq.com/s?src=11&timestamp=1629690837&ver=3269&signature=xZqnYAS*DfR8I-fCIxbSv4QdzdKHMPC3Ck7tdV49gkfpy6tnbLojZtnlSvs8ySMEflzuk434SS7fXL*03ZKVuesPNBs8YX9LTbmcAA0EDHgLH9ddb1NYSHHAW*XP89ci&new=1

**Comment by Mddct** [comment]
link expired
