### ISSUE TITLE
Calling for volunteers to support more datasets in WeNet.

### ISSUE THREAD

**Issue by robin1001** [wenet-e2e/wenet#575]
We are calling for volunteers to support more datasets in WeNet including but not limited to the following table. Please note the `Assign` column: 
* Done: already one.
* @sb: taken by the volunteer.
* empty: it is free to take.

Let we know if you are interest in, feel free to support the dataset not listed in the table, thanks!

|  Datasets       |  Languages |  Assign       |  Test Sets                  |  Metric(CER/WER) |
|-----------------|------------|---------------|-----------------------------|------------------|
|  aishell        |  CN        |  Done         |  test                       |  4.36            |
|  aishell2       |  CN        |  Done         |  test_IOS                   |  5.35            |
|  ami            |  EN        |               |                             |                  |
|  chime4         |  EN        |  @funcwj      |                             |                  |
|  commonvoice/en |  EN        |               |                             |                  |
|  commonvoice/pt |  PT        |   @Xiaoxiao_77           |                             |                  |
|  csj            |  JP        |               |                             |                  |
|  gigaspeech     |  EN        |  Done         |  dev/test                   |  10.7/10.6       |
|  hkust          |  CN        |  @fanlu      |                             |                  |
|  librispeech    |  EN        |  Done         |  test_clean/test_other      |  2.65/5.98       |
|  magicdata       |  CN        |   @Xiaoxiao_77       |       |         |
|  multi_cn       |  CN        |  Done         |  test_aishell/test_aishell2 |  1.23/5.25       |
|  swbd           |  EN        |  @pengchengguo |                             |                  |
|  tedlium3       |  EN        |  @YuekaizhanG    |                             |                  |
| timit       |  EN        |     |                             |                  |
|  wsj            |  EN        |  @pengchengguo |                             |                  |

**Comment by tuocheng0824** [comment]
求aishell2和wsj数据集

**Comment by kunnnnnn** [comment]
需求aishell2和hkust数据集，谢谢了。

**Comment by chen1399** [comment]
需求aishell2和wsj数据集

**Comment by jasonyong** [comment]
需求aishell2数据集，谢谢

**Comment by robin1001** [comment]
*Please do not apply for data here, try to use English if you are willing to contribute a public dataset, which is friendly for non-Chinese users.*

**Comment by robin1001** [comment]
We moved it to Github Discussions https://github.com/wenet-e2e/wenet/discussions/587
