### ISSUE TITLE
errs in make when using libtorch1.9

### ISSUE THREAD

**Issue by Dsqds** [wenet-e2e/wenet#595]
the code i use is the latest wenet code;
the libraries like fst,glog etc. are the same as previous version (the previous code and libraries can run rightly);
I only chg the libtorch to cxx-1.9-cpu downloaded by my self from official-website;
now, when I make, it report errs like below.
I think maybe you have met the err before.
If you have some knowledge about the err, please give me some suggestions.
Thank a lot.
----------
/home/fc_base/glog-build/libglog.a(logging.cc.o): In function `google::(anonymous namespace)::LogFileObject::Write(bool, long, char const*, int)':
logging.cc:(.text+0x1443): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
logging.cc:(.text+0x1a0c): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
/home/fc_base/glog-build/libglog.a(logging.cc.o): In function `google::CheckstrcmptrueImpl[abi:cxx11](char const*, char const*, char const*)':
logging.cc:(.text+0x5f07): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
/home/fc_base/glog-build/libglog.a(logging.cc.o): In function `google::CheckstrcmpfalseImpl[abi:cxx11](char const*, char const*, char const*)':
logging.cc:(.text+0x60f3): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
/home/fc_base/glog-build/libglog.a(logging.cc.o): In function `google::CheckstrcasecmptrueImpl[abi:cxx11](char const*, char const*, char const*)':
logging.cc:(.text+0x62e0): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
/home/fc_base/glog-build/libglog.a(logging.cc.o):logging.cc:(.text+0x64cc): more undefined references to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()' follow
/home/fc_base/openfst-subbuild/openfst-populate-prefix/lib/libfst.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()@GLIBCXX_3.4.26'
collect2: error: ld returned 1 exit status
CMakeFiles/decoder.dir/build.make:306: recipe for target 'decoder' failed
make[2]: *** [decoder] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/decoder.dir/all' failed
make[1]: *** [CMakeFiles/decoder.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by robin1001** [comment]
please refer https://github.com/wenet-e2e/wenet/issues/188
