### ISSUE TITLE
use the model of 16k data to fine tune 8K data ？

### ISSUE THREAD

**Issue by unkwner** [wenet-e2e/wenet#602]
Hi!

I would like to train a model with 8k audio,  but the training is time-consuming, can i use the model of 16k data to fine tune 8K data ？

I'd appreciate any suggestion from you!

**Comment by robin1001** [comment]
just upsampling 8k data to 16k and bootstrap from 16k pretrained model.

**Comment by unkwner** [comment]
> just upsampling 8k data to 16k and bootstrap from 16k pretrained model.

Thank you very much for your answer, but I also use 8K data when I apply it, so I want to know whether I can directly use 16K model to fine tune 8K data. 

In addition, I will try your suggestions .

**Comment by robin1001** [comment]
Just try. Both of them should work.
