### ISSUE TITLE
maker failure when using docker environment

### ISSUE THREAD

**Issue by GZJAS** [wenet-e2e/wenet#629]
When I compile the server/x86 using docker environment：
`cd docker`
`docker build --no-cache -t wenet:latest .`

I meet the following errors：
204.1 g++: fatal error: Killed signal terminated program cc1plus
204.1 compilation terminated.
204.2 make[6]: *** [Makefile:518: determinize.lo] Error 1
204.2 make[6]: *** Waiting for unfinished jobs....
229.1 make[6]: Leaving directory '/home/wenet/runtime/server/x86/fc_base/openfst-build/src/script'
229.1 make[5]: *** [Makefile:358: all-recursive] Error 1
229.1 make[5]: Leaving directory '/home/wenet/runtime/server/x86/fc_base/openfst-build/src'
229.1 make[4]: *** [Makefile:414: all-recursive] Error 1
229.2 make[4]: Leaving directory '/home/wenet/runtime/server/x86/fc_base/openfst-build'
229.2 make[3]: *** [Makefile:337: all] Error 2
229.2 make[3]: Leaving directory '/home/wenet/runtime/server/x86/fc_base/openfst-build'
229.2 make[2]: *** [CMakeFiles/openfst.dir/build.make:119: openfst-prefix/src/openfst-stamp/openfst-build] Error 2
229.2 make[2]: Leaving directory '/home/wenet/runtime/server/x86/build'
229.2 make[1]: *** [CMakeFiles/Makefile2:350: CMakeFiles/openfst.dir/all] Error 2
229.2 make[1]: Leaving directory '/home/wenet/runtime/server/x86/build'
229.2 make: *** [Makefile:155: all] Error 2

**Comment by heichang12138** [comment]
I meet the same problem, may i ask how do you solve it?

**Comment by GZJAS** [comment]
> I meet the same problem, may i ask how do you solve it?

expand the docker memory size, such as 5G or 6G at least

**Comment by heichang12138** [comment]
it works for me! thanks a lot

**Comment by heichang12138** [comment]
> > I meet the same problem, may i ask how do you solve it?
> 
> expand the docker memory size, such as 5G or 6G at least

it works for me! thanks a lot

**Comment by GZJAS** [comment]
> > > I meet the same problem, may i ask how do you solve it?
> > 
> > 
> > expand the docker memory size, such as 5G or 6G at least
> 
> it works for me! thanks a lot

：）

**Comment by hscspring** [comment]
why is this image 
so large.....
