### ISSUE TITLE
如何使用cpu训练模型？

### ISSUE THREAD

**Issue by godzilla-123** [wenet-e2e/wenet#661]
我正在尝试跑aishell s0的run.sh，发现第四步模型训练必须要使用gpu。我希望可以在不用gpu的情况下把模型跑起来看一下运行结果，不知道wenet是否支持？

**Comment by pengzhendong** [comment]
自己改脚本呗

**Comment by waiter1** [comment]
您好，请问您改成功了吗

**Comment by pengzhendong** [comment]
> 您好，请问您改成功了吗

不建议用 cpu，跑到何年何月。
