### ISSUE TITLE
make runtime  error:   c++: 错误：unrecognized command line option ‘-std=c++14’

### ISSUE THREAD

**Issue by dancinghui** [wenet-e2e/wenet#663]
**build the runtime server x86 encountered error :c++: 错误：unrecognized command line option ‘-std=c++14’**

> /usr/local/bin/cmake -E cmake_progress_start /mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/build/CMakeFiles /mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/build/CMakeFiles/progress.marks
/usr/bin/gmake -f CMakeFiles/Makefile2 all
gmake[1]: 进入目录“/mnt/sdb2/user_home/li.hui/wenet/runtime/server/x86/build”
/usr/bin/gmake -f ../fc_base/glog-build/CMakeFiles/glog.dir/build.make ../fc_base/glog-build/CMakeFiles/glog.dir/depend
gmake[2]: 进入目录“/mnt/sdb2/user_home/li.hui/wenet/runtime/server/x86/build”
cd /mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/build && /usr/local/bin/cmake -E cmake_depends "Unix Makefiles" /mnt/sdb/user_home/li.hui/wenet/runtime/server/x86 /mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/fc_base/glog-src /mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/build /mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/fc_base/glog-build /mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/fc_base/glog-build/CMakeFiles/glog.dir/DependInfo.cmake --color=
Scanning dependencies of target glog
gmake[2]: 离开目录“/mnt/sdb2/user_home/li.hui/wenet/runtime/server/x86/build”
/usr/bin/gmake -f ../fc_base/glog-build/CMakeFiles/glog.dir/build.make ../fc_base/glog-build/CMakeFiles/glog.dir/build
gmake[2]: 进入目录“/mnt/sdb2/user_home/li.hui/wenet/runtime/server/x86/build”
[  1%] Building CXX object ../fc_base/glog-build/CMakeFiles/glog.dir/src/demangle.cc.o
cd /mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/fc_base/glog-build && /usr/bin/c++  -DGOOGLE_GLOG_DLL_DECL="" -I/mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/fc_base/glog-src/src -I/mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/fc_base/glog-build -I/mnt/sdb/user_home/li.hui/wenet/runtime/server/x86 -I/mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/kaldi -I/mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/fc_base/gflags-build/include  -std=c++14 -pthread -fPIC -fPIC -fvisibility=default -fvisibility-inlines-hidden   -o CMakeFiles/glog.dir/src/demangle.cc.o -c /mnt/sdb/user_home/li.hui/wenet/runtime/server/x86/fc_base/glog-src/src/demangle.cc
c++: 错误：unrecognized command line option ‘-std=c++14’
gmake[2]: *** [../fc_base/glog-build/CMakeFiles/glog.dir/src/demangle.cc.o] 错误 1
gmake[2]: 离开目录“/mnt/sdb2/user_home/li.hui/wenet/runtime/server/x86/build”
gmake[1]: *** [../fc_base/glog-build/CMakeFiles/glog.dir/all] 错误 2
gmake[1]: 离开目录“/mnt/sdb2/user_home/li.hui/wenet/runtime/server/x86/build”
gmake: *** [all] 错误 2

**To Reproduce**
1. Go to 'wenet/runtime/server/x86'
2. run:   'mkdir build && cd build && cmake -DINTTYPES_FORMAT:STRING=C99 .. && cmake --build .'

**Desktop :**
 - OS: CentOS Linux release 7.6.1810 (Core) 
 -cmake: 3.16.0-rc2

**Comment by pengzhendong** [comment]
Maybe you need to update the version of g++.

**Comment by MMingabc** [comment]
> Maybe you need to update the version of g++.

What version of g++ do you use?

**Comment by dancinghui** [comment]
> > Maybe you need to update the version of g++.
> 
> What version of g++ do you use?

4.8.5

**Comment by xianglan010** [comment]
@dancinghui Hi, I also come across this problem, have you solved it now, please tell me, thanks!

**Comment by dancinghui** [comment]
> 

sorry, not solved

**Comment by pengzhendong** [comment]
gcc version >= 5.0.0 supports c++14
