### ISSUE TITLE
windows make error

### ISSUE THREAD

**Issue by qwerrrrrt** [wenet-e2e/wenet#666]
when I try this command:mkdir build && cd build && cmake .. && cmake --build . .There is still an error.
![image](https://user-images.githubusercontent.com/91374065/136656165-e9ebc1d0-86e9-4331-9612-467737a9bdcd.png)
and the cmakeerror.log file shows that
![image](https://user-images.githubusercontent.com/91374065/136656196-d651a395-7015-4532-974a-1fb4e17af3a0.png)
which I think it may be the link question,but I am not sure. I post this question once ,it is still there. But I can make the project on the Linux platform.
I just git clone the project and then do the "make" step,  I tried several times, which seems the same error.

**Comment by qwerrrrrt** [comment]
I installed some packages and some error disappear. But it still has some, I can't solve this error. 
![image](https://user-images.githubusercontent.com/91374065/136657682-73ee607c-202d-4f30-bff8-fc7026549e12.png)

**Comment by robin1001** [comment]
Linux is preferred for building wenet. We do not do test on windows.
