### ISSUE TITLE
Is it possible to finetune pretrained model?

### ISSUE THREAD

**Issue by Freddy-pp** [wenet-e2e/wenet#751]
With a new training (adaptation) set? I didn't find any out-of-the-box transfer learning options in wenet code. Could I do this "resuming" new training from a checkpoint, and setting checkpoint path to pretrained model? Or it's possible to somehow change init.pt and start from it? Thanks in advance.

**Comment by Freddy-pp** [comment]
Thank you. I'll try.

**Comment by blacklj** [comment]
> Both Resuming from checkpoint and changing init.pt could work for fine-tuning.

How to handle outputs mismatch？

**Comment by StuartIanNaylor** [comment]
Dunno if this is of any use and the methods it describes
https://arxiv.org/html/2409.09506v1
