### ISSUE TITLE
Compile libtorch for Android

### ISSUE THREAD

**Issue by lyj157175** [wenet-e2e/wenet#756]
![image](https://user-images.githubusercontent.com/49610133/139841943-9e2c45b2-125e-44dd-b3bb-334fd946eef2.png)
你好！想问下安卓里的CMakelist.txt里的这个.so文件是那里来的呀，是需要自己先编译好用于安卓的libtorch动态库嘛？

**Comment by pengzhendong** [comment]
从 Android NDK 里来的，不需要自己编译 libtorch 动态库（会自动下载预编译的库）
