### ISSUE TITLE
Does wenet natively support multiple machines and multiple cards?

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#757]
HI，Does wenet natively support multiple machines and multiple cards? I think there is no relevant configuration in the configuration.

**Comment by cnrpman** [comment]
https://github.com/wenet-e2e/wenet/blob/70f35735e3fe7e19113b47d1992aa3c0927d1dbe/examples/aishell/s0/run.sh#L123

**Comment by robin1001** [comment]
Yes, multiple machines and multiple cards are built-in, and @cnrpman shows the related code.

**Comment by srdfjy** [comment]
thanks @robin1001 @cnrpman
