### ISSUE TITLE
Train with shard mode break after every epoch

### ISSUE THREAD

**Issue by carclodefly** [wenet-e2e/wenet#759]
**Describe the bug**
While I'm trying to train my model with shard data mode using gloo, I got an error after every epoch and my task stoped .like this :
/opt/conda/envs/wenet/lib/python3.8/multiprocessing/process.py:108: ResourceWarning: unclosed file <_io.BufferedReader name='/data/wenet_aishell2_shards/train/shards_000005738.tar'>
  self._target(*self._args, **self._kwargs)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "wenet/bin/train.py", line 262, in <module>
    main()
  File "wenet/bin/train.py", line 235, in main
    executor.train(model, optimizer, scheduler, train_data_loader, device,
  File "/workspace/wenet/examples/aishell2/s0/wenet/utils/executor.py", line 71, in train
    loss.backward()
  File "/opt/conda/envs/wenet/lib/python3.8/site-packages/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/envs/wenet/lib/python3.8/site-packages/torch/autograd/__init__.py", line 147, in backward
    Variable._execution_engine.run_backward(

**To Reproduce**
1. train model with shard mode by set --data_type "shard"
2. wait for at least one epoch complete,you my get it.

**Expected behavior**
train with shard mode successfully all the time

**Screenshots**
![图片](https://user-images.githubusercontent.com/17400780/140242758-c840c39b-22b9-48df-bde5-477a88755992.png)

**Desktop (please complete the following information):**
 - OS: [LINUX x86_64]
 - Version [commit f972951275261ed14f3ba10f1b70716970f758ec (HEAD -> main)]

**Comment by carclodefly** [comment]
![图片](https://user-images.githubusercontent.com/17400780/140243299-8460327f-9e45-43c3-bbfd-1c8b1daa28f2.png)

**Comment by robin1001** [comment]
Is it the latest code? 
It should be close by https://github.com/wenet-e2e/wenet/blob/main/wenet/dataset/processor.py#L109.

**Comment by xingchensong** [comment]
fiexd, close this issue
