### ISSUE TITLE
terminate called after throwing an instance of 'torch::jit::ErrorReport'

### ISSUE THREAD

**Issue by pythonLiNM** [wenet-e2e/wenet#762]
wenetspeech model ,Finished package, run model error:terminate called after throwing an instance of 'torch::jit::ErrorReport'
![1636089561](https://user-images.githubusercontent.com/50547107/140462418-4af7f085-7608-475d-90df-aefc658f7723.jpg)

**Comment by robin1001** [comment]
what's you pytorch version and libtorch version?

**Comment by robin1001** [comment]
We update both the pytorch and libtorch to 1.10.0, please pull the latest code  and retry.

**Comment by python-linming** [comment]
thanks, v0.5.0 was used for the project deployment code and  the model is v1.0.0 ;I don't know if it's possible?
pytorch ==1.8.0,
