### ISSUE TITLE
BUG IN data filter

### ISSUE THREAD

**Issue by peggyxpxu** [wenet-e2e/wenet#766]
In old tools/remove_longshortdata.py, the feature length is in seconds, min_output_input_ratio is 0.05 and max_output_input_ratio in 10 as default.
In new uio code, we have 100 frames every second, so min_output_input_ratio should be 0.0005 and max_output_input_ratio should be 0.1，but it is 1 in the wenet/dataset/processor.py as default, which is unable to filter data effectively.

**Comment by robin1001** [comment]
We do not use the same value in the UIO. Typically, the default parameter do not filter the data unless we setting it explicitly.

**Comment by peggyxpxu** [comment]
It is recommended to expose these parameters rather than hide them in the code, which can lead to training errors .

> We do not use the same value in the UIO. Typically, the default parameter do not filter the data unless we setting it explicitly.

**Comment by robin1001** [comment]
You could set it in the yaml config file or in command line, please see https://github.com/wenet-e2e/wenet/pull/709

**Comment by robin1001** [comment]
@qmpzzpmq, it's time to give a document, could you help on that?

**Comment by qmpzzpmq** [comment]
Any idea?

**Comment by xingchensong** [comment]
Now it is set to 0.0005 and 0.1 for librispeech : https://github.com/wenet-e2e/wenet/blob/main/examples/librispeech/s0/conf/train_conformer_bidecoder_large.yaml#L47-L48
