### ISSUE TITLE
wenet的长音频识别除了模拟流式的方式来实现还有其他方式吗？

### ISSUE THREAD

**Issue by smil4ever** [wenet-e2e/wenet#768]
wenet的长音频识别我看了全是除了模拟流式的方式来实现。无论是websocket还是grpc还是直接decoder，都是要通过time sleep的方式来模拟流式发送音频数据，想问一下整个架构都是必须得用这种流式音频的输入方式吗？

**Comment by robin1001** [comment]
This is just a reference solution for real time transcription. For long audio offline transcription, you should make your own system design according to your product and scenario requirements.
