### ISSUE TITLE
报错：run.sh: line 57: tools/parse_options.sh: Not a directory

### ISSUE THREAD

**Issue by smil4ever** [wenet-e2e/wenet#769]
cd /examples/aishell/s0
 bash run.sh --stage -1

run.sh: line 57: tools/parse_options.sh: Not a directory

**Comment by robin1001** [comment]
check the soft link and your environment.

**Comment by seekFire** [comment]
@smil4ever I met the same problem with you, did you solved it ?

**Comment by seekFire** [comment]
@robin1001 Do you confirm that we need to create any soft link under examples/aishell/s0?

**Comment by wei-chan2022** [comment]
> 
I also met the same problem with you, did you solved it now?

**Comment by wei-chan2022** [comment]
> @smil4ever I met the same problem with you, did you solved it ?

I also met the same problem with you, did you solved it now?

**Comment by wei-chan2022** [comment]
> @smil4ever I met the same problem with you, did you solved it ?

@smil4ever I also met the same problem with you, did you solved it now?

**Comment by wei-chan2022** [comment]
> @smil4ever I met the same problem with you, did you solved it ?

@seekFire I also met the same problem with you, did you solved it now?
