### ISSUE TITLE
Not used wav.segment.scp in the gigaspeech/run.sh

### ISSUE THREAD

**Issue by RuslanSel** [wenet-e2e/wenet#770]
gigaspeech/run.sh stage 1:
python tools/segment.py --segments $data/$x/segments \
      --input $data/$x/wav.scp \
      --output $data/$x/wav.segment.scp
But then in stage 3 we don't use wav.segment.scp:
tools/make_shard_list.py --resample 16000 --num_utts_per_shard 1000 \
      --num_threads 32 --segments data/$x/segments \
      data/$x/wav.scp data/$x/text \
      $(realpath $dst) data/$x/data.list

**Comment by robin1001** [comment]
Acctually, we can use the segmented audio or the full audio to estimate CMVN., both should work fine.

**Comment by robin1001** [comment]
And the problem is it takes too long time to compute CMVN since the data is very big. We should sample some of the data to reduce the time.

please refer https://github.com/wenet-e2e/wenet/blob/main/examples/wenetspeech/s0/run.sh#L78-L92, could you help to fix that?
