### ISSUE TITLE
Centos 编译runtime/x86出现错误

### ISSUE THREAD

**Issue by ziyu123** [wenet-e2e/wenet#771]
在Linux 系统 CentOS Linux release 7.7.1908版本上，进行runtime/x86 进行编译，出现错误如下： 
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘operator delete(void*, std::align_val_t)@CXXABI_1.3.11’未定义的引用
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘__cxa_init_primary_exception@CXXABI_1.3.11’未定义的引用
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11’未定义的引用
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘powf@GLIBC_2.27’未定义的引用
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘log2f@GLIBC_2.27’未定义的引用
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘lgammaf@GLIBC_2.23’未定义的引用
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘expf@GLIBC_2.27’未定义的引用
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘exp2f@GLIBC_2.27’未定义的引用
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘operator new(unsigned long, std::align_val_t)@CXXABI_1.3.11’未定义的引用
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘lgamma@GLIBC_2.23’未定义的引用
wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so：对‘logf@GLIBC_2.27’未定义的引用    

看log是Glibc版本的问题，但是目前没有系统root权限，没法升级Glibc版本，有遇到这样问题的没？这个问题怎么解决呢？

**Comment by robin1001** [comment]
Just try to build with docker, then compare and fix the environment problems.
