### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by peggyxpxu** [wenet-e2e/wenet#773]
I trained with raw data,  but memory usage rose from 60% to 70%+ in the first epoch, and it keeps going up .
Whatsmore,I found that the training speed of the new code decreased a lot, may I ask why ?

**Comment by robin1001** [comment]
it's not memory leak, the new IO also caches and prefetchs data  by design.
The speed should be comparable to the old IO.

**Comment by peggyxpxu** [comment]
> it's not memory leak, the new IO also caches and prefetchs data by design. The speed should be comparable to the old IO.
When training data more than 2W hours（data type is raw）,  memory usage continues to rise during training.
It feels like an iterative read without releasing the previous data.

**Comment by peggyxpxu** [comment]
> it's not memory leak, the new IO also caches and prefetchs data by design. The speed should be comparable to the old IO.

When training data more than 2W hours（data type is raw）, memory usage continues to rise during training.
It feels like an iterative read without releasing the previous data.

**Comment by SWHL** [comment]
- I meet the same problem.
- When trainning data more than 6 epoches, memory usage continues to rise.
