### ISSUE TITLE
make_shard_list.py doesn't work with long files

### ISSUE THREAD

**Issue by RuslanSel** [wenet-e2e/wenet#777]
gigaspeech has files with length like 16 hours.
And make_shard_list.py can't create shard_xx.tar from them. It just hangs some time and that's all.

**Comment by robin1001** [comment]
Did you specify --segments ?

**Comment by RuslanSel** [comment]
Yes.

**Comment by robin1001** [comment]
You mean there is a semgent which length is longer than 16 hours?

**Comment by robin1001** [comment]
Could you help to fix the problem? I'm afraid that I don't have the bandwidth to fix it recently.

**Comment by RuslanSel** [comment]
Seems like sox.load() crashes with files longer then 1 hour 15 minutes.

**Comment by robin1001** [comment]
It works fine in my environment in WenetSpeech for long audios.

**Comment by RuslanSel** [comment]
Replacing 
import torchaudio.backend.sox_io_backend as sox
with
import torchaudio.backend.soundfile_backend as sox
helped me.

**Comment by keshawnhsieh** [comment]
Met the same problem. Process will crash without any message output while loading AUD0000000035.opus.
Replacing with torchaudio.backend.soundfile_backend doesn't help.

**Comment by JeffC0628** [comment]
the same problem, have any solution?

**Comment by agreatbush** [comment]
I got the same problem  without any message output but some *.tar file is not readable
