### ISSUE TITLE
C++ runtime slower than Python CPU version

### ISSUE THREAD

**Issue by peterdarkdarkgogo** [wenet-e2e/wenet#787]
May i ask why the C++ wenet is kind of slower than the Python CPU version? Especially in the encoder part, which is obvious slower than the Python CPU version.

**Comment by robin1001** [comment]
any number? both benchmarked on CPU? Libtorch should be faster than python.

**Comment by peterdarkdarkgogo** [comment]
I test a wav with 14 second duration both in Python CPU version and CPP version on the same server. The Python average inference time is 2 second, while the CPP version average inference time is 3.8 second, which kind of weird.

**Comment by xingchensong** [comment]
calling the c++ runtime for the first time will be slower because some context required by libtorch needs to be started, the 
 subsequent calls will be much faster.

**Comment by peterdarkdarkgogo** [comment]
Oh i get it. It seems reasonable. Thanks.
