### ISSUE TITLE
runtime decoder

### ISSUE THREAD

**Issue by Innocence-0712** [wenet-e2e/wenet#788]
Hi all:
       I use the runtime-decode (decode_main) to get the ASR result, which follow the Librispeech recipe, but have no any results.  The log always stops at " Reading symbol table data/lang_test/words.txt".  The log of pre-process have no any errors.  
      Anybody can help me? Thank you in advance.

**Comment by xingchensong** [comment]
this may help u : https://github.com/wenet-e2e/wenet/issues/563

**Comment by Innocence-0712** [comment]
Yeah, sovle it , thank you very much !
