### ISSUE TITLE
How can I add a c++ interface

### ISSUE THREAD

**Issue by qwerrrrrt** [wenet-e2e/wenet#792]
I want to write more C + + interfaces in ASR_ In model.py, @ torch.jit.export is used to construct a new function, and then the model is trained through export_ JIT is exported to final.zip, but the newly written function is not found in Android programming, which is similar to (get_method ("forward_encoder_chunk"). Please tell me how to solve this problem. Thank you！
Is the Android terminal calling model - > torch_ model() ->get_ Method is extracted from final.zip, because I regenerate the new final.zip, but still can't find the function interface I wrote，thanks a lot!!!!!

**Comment by robin1001** [comment]
It should work. You can refer our implementation or the documentation of LibTorch for more details.
