### ISSUE TITLE
ModuleNotFoundError in stage 4

### ISSUE THREAD

**Issue by Karuizawa7** [wenet-e2e/wenet#793]
When I try to run train.py in stage 4 in the tutorial, an error occurs:

(wenet) yifeng@clx03:~/wenet/examples/aishell/s0$ bash run.sh --stage 4 --stop-stage 4
run.sh: init method is file:///home/yifeng/wenet/examples/aishell/s0/exp/conformer/ddp_init
total gpus is: 8
Traceback (most recent call last):
Traceback (most recent call last):
File "wenet/bin/train.py", line 29, in <module>
File "wenet/bin/train.py", line 29, in <module>
from wenet.dataset.dataset import Dataset
from wenet.dataset.dataset import Dataset
ModuleNotFoundError: No module named 'wenet'
ModuleNotFoundError: No module named 'wenet'

I found the wenet folder in the correct path I think:
(wenet) yifeng@clx03:~/wenet/examples/aishell/s0$ ls -la
total 52
drwxrwxr-x 6 yifeng yifeng 4096 11月 16 15:33 .
drwxrwxr-x 5 yifeng yifeng 4096 11月 16 10:55 ..
drwxrwxr-x 2 yifeng yifeng 4096 11月 16 10:55 conf
drwxrwxr-x 7 yifeng yifeng 4096 11月 16 14:06 data
drwxrwxr-x 3 yifeng yifeng 4096 11月 16 14:09 exp
drwxrwxr-x 2 yifeng yifeng 4096 11月 16 11:07 local
-rw-rw-r-- 1 yifeng yifeng  409 11月 16 10:55 path.sh
-rw-rw-r-- 1 yifeng yifeng 5473 11月 16 10:55 README.md
-rw-rw-r-- 1 yifeng yifeng 8271 11月 16 15:33 run.sh
lrwxrwxrwx 1 yifeng yifeng   15 11月 16 10:55 tools -> ../../../tools/
-rw-rw-r-- 1 yifeng yifeng  153 11月 16 10:55 UIO_RESULT.md
lrwxrwxrwx 1 yifeng yifeng   15 11月 16 10:55 wenet -> ../../../wenet/

I wonder how I can fix the problem.
Thank you.

**Comment by Karuizawa7** [comment]
I setup the environment by following the instruction, so the python version is 3.8.11.

**Comment by robin1001** [comment]
`bash` should be the default shell. please check and retry.

**Comment by Karuizawa7** [comment]
Thanks for your reply. But what do you mean by the default shell?

**Comment by Karuizawa7** [comment]
(wenet) yifeng@clx03:~/wenet/examples/aishell/s0$ echo $SHELL
/bin/bash

I think the default shell is bash? Do you mean this?

**Comment by pengzhendong** [comment]
Try to set the PYTHONPATH: `export PYTHONPATH=/path/to/wenet`

**Comment by robin1001** [comment]
We fix the PYTHONPATH in the latest code. please pull the latest code.
