### ISSUE TITLE
 Failed while writing sample data to (null)

### ISSUE THREAD

**Issue by LBY-bamboo** [wenet-e2e/wenet#805]
Why does entering "--stage 0 --stop-stage 0" in HKUST will display" Failed while writing sample data to (null)";"/usr/bin/sox WARN trim: End position is after expected end of audio.";"/usr/bin/sox WARN trim: Last 1 position(s) not reached."?

**Comment by robin1001** [comment]
@hicliff

**Comment by LBY-bamboo** [comment]
您好，我在HKUST数据集下运行"--stage 0 --stop-stage 0" ，出现
"/usr/bin/sox WARN trim: End position is after expected end of audio."
"/usr/bin/sox WARN trim: Last 1 position(s) not reached."
会对后续需处理步骤产生影响么？如果会产生影响，我需要怎么解决？


***@***.***
 
From: Binbin Zhang
Date: 2021-11-19 19:43
To: wenet-e2e/wenet
CC: LBY-bamboo; Author
Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805)
@hicliff
―
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LBY-bamboo** [comment]
Hello, I run "-- stage 0 -- stop stage 0" under the HKUST dataset, and an error appears
"/usr/bin/sox WARN trim: End position is after expected end of audio."
"/usr/bin/sox WARN trim: Last 1 position(s) not reached."
Will it affect the subsequent processing steps？If it will have an impact, how do I need to solve it？


***@***.***
 
From: Binbin Zhang
Date: 2021-11-19 19:43
To: wenet-e2e/wenet
CC: LBY-bamboo; Author
Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805)
@hicliff
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hicliff** [comment]
> Hello, I run "-- stage 0 -- stop stage 0" under the HKUST dataset, and an error appears "/usr/bin/sox WARN trim: End position is after expected end of audio." "/usr/bin/sox WARN trim: Last 1 position(s) not reached." Will it affect the subsequent processing steps？If it will have an impact, how do I need to solve it？ ***@***.*** From: Binbin Zhang Date: 2021-11-19 19:43 To: wenet-e2e/wenet CC: LBY-bamboo; Author Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) @hicliff — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Hello, 
As far as I know, the reason for this warning is the little difference between the segment info. of .sph file and the actual audio length(e.g. the segment file shows the last segment of one sph file continues from 12.1 to 19.81s. however, the actua audio length is 19.8s). I will not affect the subsequent processing steps. If you find any problems during train or decode, please let me know.

**Comment by LBY-bamboo** [comment]
您好，我发现wenet对输入语音长度有限制，超过70s的语音不能读取，这个是在什么地方有设置么？放不方便告知一下。麻烦了，谢谢！

***@***.***
 
From: Yi Peng
Date: 2021-12-01 17:03
To: wenet-e2e/wenet
CC: LBY-bamboo; State change
Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805)
Hello, I run "-- stage 0 -- stop stage 0" under the HKUST dataset, and an error appears "/usr/bin/sox WARN trim: End position is after expected end of audio." "/usr/bin/sox WARN trim: Last 1 position(s) not reached." Will it affect the subsequent processing steps？If it will have an impact, how do I need to solve it？ @.*** From: Binbin Zhang Date: 2021-11-19 19:43 To: wenet-e2e/wenet CC: LBY-bamboo; Author Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) @hicliff ― You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
Hello,
As far as I know, the reason for this warning is the little difference between the segment info. of .sph file and the actual audio length(e.g. the segment file shows the last segment of one sph file continues from 12.1 to 19.81s. however, the actua audio length is 19.8s). I will not affect the subsequent processing steps. If you find any problems during train or decode, please let me know.
―
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hicliff** [comment]
> 您好，我发现wenet对输入语音长度有限制，超过70s的语音不能读取，这个是在什么地方有设置么？放不方便告知一下。麻烦了，谢谢！ ***@***.*** From: Yi Peng Date: 2021-12-01 17:03 To: wenet-e2e/wenet CC: LBY-bamboo; State change Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) Hello, I run "-- stage 0 -- stop stage 0" under the HKUST dataset, and an error appears "/usr/bin/sox WARN trim: End position is after expected end of audio." "/usr/bin/sox WARN trim: Last 1 position(s) not reached." Will it affect the subsequent processing steps？If it will have an impact, how do I need to solve it？ @.*** From: Binbin Zhang Date: 2021-11-19 19:43 To: wenet-e2e/wenet CC: LBY-bamboo; Author Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) @hicliff ― You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. Hello, As far as I know, the reason for this warning is the little difference between the segment info. of .sph file and the actual audio length(e.g. the segment file shows the last segment of one sph file continues from 12.1 to 19.81s. however, the actua audio length is 19.8s). I will not affect the subsequent processing steps. If you find any problems during train or decode, please let me know. ― You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

你好，你说的问题是在训练时还是解码时呢？训练的话，配置文件中有max_length选项，控制处理的音频最大长度，可以尝试修改参数值。解码的时候，也可以看下这个参数值是否有限制。或者在模型训练时用no_positional_encoding的选项，理论上是可以解码无限长的音频

**Comment by LBY-bamboo** [comment]
您好，还想请问一下，我网络训练好，在解码过程中遇见报错如下，请问怎么解决？


***@***.***
 
From: Yi Peng
Date: 2021-12-14 17:07
To: wenet-e2e/wenet
CC: LBY-bamboo; State change
Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805)
您好，我发现wenet对输入语音长度有限制，超过70s的语音不能读取，这个是在什么地方有设置么？放不方便告知一下。麻烦了，谢谢！ @.*** From: Yi Peng Date: 2021-12-01 17:03 To: wenet-e2e/wenet CC: LBY-bamboo; State change Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) Hello, I run "-- stage 0 -- stop stage 0" under the HKUST dataset, and an error appears "/usr/bin/sox WARN trim: End position is after expected end of audio." "/usr/bin/sox WARN trim: Last 1 position(s) not reached." Will it affect the subsequent processing steps？If it will have an impact, how do I need to solve it？ @.*** From: Binbin Zhang Date: 2021-11-19 19:43 To: wenet-e2e/wenet CC: LBY-bamboo; Author Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) @hicliff D You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. Hello, As far as I know, the reason for this warning is the little difference between the segment info. of .sph file and the actual audio length(e.g. the segment file shows the last segment of one sph file continues from 12.1 to 19.81s. however, the actua audio length is 19.8s). I will not affect the subsequent processing steps. If you find any problems during train or decode, please let me know. D You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
你好，你说的问题是在训练时还是解码时呢？训练的话，配置文件中有max_length选项，控制处理的音频最大长度，可以尝试修改参数值。解码的时候，也可以看下这个参数值是否有限制。或者在模型训练时用no_positional_encoding的选项，理论上是可以解码无限长的音频
―
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hicliff** [comment]
> 您好，还想请问一下，我网络训练好，在解码过程中遇见报错如下，请问怎么解决？ ***@***.*** From: Yi Peng Date: 2021-12-14 17:07 To: wenet-e2e/wenet CC: LBY-bamboo; State change Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) 您好，我发现wenet对输入语音长度有限制，超过70s的语音不能读取，这个是在什么地方有设置么？放不方便告知一下。麻烦了，谢谢！ @.*** From: Yi Peng Date: 2021-12-01 17:03 To: wenet-e2e/wenet CC: LBY-bamboo; State change Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) Hello, I run "-- stage 0 -- stop stage 0" under the HKUST dataset, and an error appears "/usr/bin/sox WARN trim: End position is after expected end of audio." "/usr/bin/sox WARN trim: Last 1 position(s) not reached." Will it affect the subsequent processing steps？If it will have an impact, how do I need to solve it？ @.*** From: Binbin Zhang Date: 2021-11-19 19:43 To: wenet-e2e/wenet CC: LBY-bamboo; Author Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) @hicliff D You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. Hello, As far as I know, the reason for this warning is the little difference between the segment info. of .sph file and the actual audio length(e.g. the segment file shows the last segment of one sph file continues from 12.1 to 19.81s. however, the actua audio length is 19.8s). I will not affect the subsequent processing steps. If you find any problems during train or decode, please let me know. D You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你好，你说的问题是在训练时还是解码时呢？训练的话，配置文件中有max_length选项，控制处理的音频最大长度，可以尝试修改参数值。解码的时候，也可以看下这个参数值是否有限制。或者在模型训练时用no_positional_encoding的选项，理论上是可以解码无限长的音频 ― You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

没看到报错信息，能重新发一下吗？

**Comment by LBY-bamboo** [comment]
您好，您这面方便共享一下chime4数据集么？想从wenet上跑一下chime4数据集。麻烦了，谢谢！


***@***.***
 
From: Yi Peng
Date: 2021-12-29 15:34
To: wenet-e2e/wenet
CC: LBY-bamboo; State change
Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805)
您好，还想请问一下，我网络训练好，在解码过程中遇见报错如下，请问怎么解决？ @.*** From: Yi Peng Date: 2021-12-14 17:07 To: wenet-e2e/wenet CC: LBY-bamboo; State change Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) 您好，我发现wenet对输入语音长度有限制，超过70s的语音不能读取，这个是在什么地方有设置么？放不方便告知一下。麻烦了，谢谢！ @.*** From: Yi Peng Date: 2021-12-01 17:03 To: wenet-e2e/wenet CC: LBY-bamboo; State change Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) Hello, I run "-- stage 0 -- stop stage 0" under the HKUST dataset, and an error appears "/usr/bin/sox WARN trim: End position is after expected end of audio." "/usr/bin/sox WARN trim: Last 1 position(s) not reached." Will it affect the subsequent processing steps？If it will have an impact, how do I need to solve it？ @.*** From: Binbin Zhang Date: 2021-11-19 19:43 To: wenet-e2e/wenet CC: LBY-bamboo; Author Subject: Re: [wenet-e2e/wenet] Failed while writing sample data to (null) (Issue #805) @hicliff D You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. Hello, As far as I know, the reason for this warning is the little difference between the segment info. of .sph file and the actual audio length(e.g. the segment file shows the last segment of one sph file continues from 12.1 to 19.81s. however, the actua audio length is 19.8s). I will not affect the subsequent processing steps. If you find any problems during train or decode, please let me know. D You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 你好，你说的问题是在训练时还是解码时呢？训练的话，配置文件中有max_length选项，控制处理的音频最大长度，可以尝试修改参数值。解码的时候，也可以看下这个参数值是否有限制。或者在模型训练时用no_positional_encoding的选项，理论上是可以解码无限长的音频 D You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
没看到报错信息，能重新发一下吗？
―
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by LBY-bamboo** [comment]
![image](https://user-images.githubusercontent.com/94619869/159399755-b8229d94-c71d-4672-b3b4-71b78aad203e.png)

2022-03-22 10:40:24,635 INFO 20041028_124231_A013309_B013310-B-058899-059281 呃我觉得挺好的
2022-03-22 10:40:24,792 INFO 20041028_124231_A013309_B013310-B-059611-059928 巴塞罗纳我一开始我就不喜欢巴西
Traceback (most recent call last):
File "tools/compute-cer.py", line 414, in
default_cluster_name = default_cluster(word)
File "tools/compute-cer.py", line 231, in default_cluster
unicode_names = [unicodedata.name(char) for char in word]
File "tools/compute-cer.py", line 231, in
unicode_names = [unicodedata.name(char) for char in word]
ValueError: no such name
![image](https://user-images.githubusercontent.com/94619869/159399821-b39b0a87-b016-4927-aee0-5aeef6071e9f.png)
![image](https://user-images.githubusercontent.com/94619869/159399891-2932c453-c6a1-427b-8b75-0287ed05f9b6.png)

How should I solve this mistake?

**Comment by xingchensong** [comment]
> ![image](https://user-images.githubusercontent.com/94619869/159399755-b8229d94-c71d-4672-b3b4-71b78aad203e.png)
> 
> 2022-03-22 10:40:24,635 INFO 20041028_124231_A013309_B013310-B-058899-059281 呃我觉得挺好的 2022-03-22 10:40:24,792 INFO 20041028_124231_A013309_B013310-B-059611-059928 巴塞罗纳我一开始我就不喜欢巴西 Traceback (most recent call last): File "tools/compute-cer.py", line 414, in default_cluster_name = default_cluster(word) File "tools/compute-cer.py", line 231, in default_cluster unicode_names = [unicodedata.name(char) for char in word] File "tools/compute-cer.py", line 231, in unicode_names = [unicodedata.name(char) for char in word] ValueError: no such name ![image](https://user-images.githubusercontent.com/94619869/159399821-b39b0a87-b016-4927-aee0-5aeef6071e9f.png) ![image](https://user-images.githubusercontent.com/94619869/159399891-2932c453-c6a1-427b-8b75-0287ed05f9b6.png)
> 
> How should I solve this mistake?

可能您的text中包含非unicode字符，请clean一下
