### ISSUE TITLE
F1124 15:38:16.049290   109 websocket_server.cc:58] Check failed: feature_pipeline_ != nullptr 

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#813]
Hi，When I send an invalid websocket request, websocket_server will stop. Is there a way to avoid this on the server side?

--------------------------------------------------------------------------

root@53aa8a6383eb:/home# sh run.sh 
I1124 15:44:08.632865   112 params.h:100] Reading model /home/assets/final.zip
I1124 15:44:09.313627   112 torch_asr_model.cc:38] torch model info subsampling_rate 4 right context 6 sos 5536 eos 5536 is bidirectional decoder 0 num threads 1
I1124 15:44:09.313686   112 params.h:113] Reading symbol table /home/assets/words.txt
I1124 15:44:09.318467   112 params.h:125] Use symbol table as unit table
I1124 15:44:09.318496   112 websocket_server_main.cc:31] Listening at port 8080
I1124 15:44:20.789677   152 websocket_server.cc:57] Recieved speech end signal
F1124 15:44:20.789736   152 websocket_server.cc:58] Check failed: feature_pipeline_ != nullptr 
*** Check failure stack trace: ***
    @     0x7feb4fdffb82  google::LogMessage::Fail()
    @     0x7feb4fdffabd  google::LogMessage::SendToLog()
    @     0x7feb4fdff3ee  google::LogMessage::Flush()
    @     0x7feb4fe02e68  google::LogMessageFatal::~LogMessageFatal()
    @     0x56534622cad0  wenet::ConnectionHandler::OnSpeechEnd()
    @     0x56534622ed03  wenet::ConnectionHandler::operator()()
    @     0x5653462d97fb  std::__invoke_impl<>()
    @     0x5653462d90ef  std::__invoke<>()
    @     0x5653462d83ae  _ZNSt6thread8_InvokerISt5tupleIJN5wenet17ConnectionHandlerEEEE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE
    @     0x5653462d6f8d  std::thread::_Invoker<>::operator()()
    @     0x5653462d5482  std::thread::_State_impl<>::_M_run()
    @     0x7feb4f7b4de4  (unknown)
    @     0x7feb4ff8a609  start_thread
    @     0x7feb4f4a4293  clone
    @              (nil)  (unknown)
Aborted (core dumped)
root@53aa8a6383eb:/home# ps -ef | grep run.sh
root       154     8  0 15:44 pts/0    00:00:00 grep --color=auto run.sh
root@53aa8a6383eb:/home# ps -ef | grep websocket_server
root       156     8  0 15:45 pts/0    00:00:00 grep --color=auto websocket_server

**Comment by robin1001** [comment]
It's a reference implementation now, so we did less work on checking the invalid protocal and error processing.
Could you help on this based on your case?

**Comment by teinhonglo** [comment]
Hi all,
I have the same issue too.

Server:
export GLOG_logtostderr=1
export GLOG_v=2
./build/websocket_server_main --port 6789 --chunk_size 16 --model_path models/20210815_unified_conformer_server/final.zip --dict_path models/20210815_unified_conformer_server/words.txt

Client:
https://github.com/wenet-e2e/wenet/blob/main/runtime/server/x86/web/templates/index.html
I typed "wss://IP_ADDRESS:6789" to textarea of index.html
