### ISSUE TITLE
一个潜在的重采样问题

### ISSUE THREAD

**Issue by boji123** [wenet-e2e/wenet#822]
https://github.com/wenet-e2e/wenet/blob/5a0afe155961a8ff3f9709281ad90ff077cd49cf/examples/wenetspeech/s0/local/process_opus.py#L69

这里使用的库，pydub的AudioSegment其重采样算法可能过于简单，是否考虑换一个更好的重采样算法？

函数库源码
https://github.com/jiaaro/pydub/blob/7b0d27a4eb7246324601ff1a120397eeddfa3ee5/pydub/audio_segment.py#L441

重采样算法源码
https://github.com/jiaaro/pydub/blob/7b0d27a4eb7246324601ff1a120397eeddfa3ee5/pydub/pyaudioop.py#L498-L519

**Comment by robin1001** [comment]
the script is not used in the pipeline now.
