### ISSUE TITLE
terminate called after throwing an instance of 'c10::Error'

### ISSUE THREAD

**Issue by NUAAerJC** [wenet-e2e/wenet#823]
I use Docker Toolbox to run your project and when I run the code below:
`docker run --rm -it -p 10086:10086 -v $model_dir:/home/wenet/model mobvoiwenet/wenet:mini bash /home/run.sh`
I get 
`terminate called after throwing an instance of 'c10::Error'
  what():  open file failed, file path: /home/wenet/model/final.zip
Exception raised from FileAdapter at ../caffe2/serialize/file_adapter.cc:11 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7fd48639deb9 in /home/wenet/lib/libc10.so)
frame #1: caffe2::serialize::FileAdapter::FileAdapter(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x2f5 (0x7fd4888927a5 in /home/wenet/lib/libtorch_cpu.so)
frame #2: torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::optional<c10::Device>, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >&) + 0x40 (0x7fd489c95320 in /home/wenet/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x1354e8 (0x55bccd4204e8 in /home/wenet/websocket_server_main)
frame #4: <unknown function> + 0x4ca81 (0x55bccd337a81 in /home/wenet/websocket_server_main)
frame #5: <unknown function> + 0x4cf15 (0x55bccd337f15 in /home/wenet/websocket_server_main)
frame #6: __libc_start_main + 0xf3 (0x7fd4855ef0b3 in /lib/x86_64-linux-gnu/libc.so.6)
frame #7: <unknown function> + 0x4c94e (0x55bccd33794e in /home/wenet/websocket_server_main)`
What should I do to solve this problem?

**Comment by NUAAerJC** [comment]
In fact, I run your project on Docker Toolbox for Windows 10.

**Comment by NUAAerJC** [comment]
my pytorch version is 1.8.1+cu101 and my python version is 3.8.6.

**Comment by pengzhendong** [comment]
The version of libtorch in the docker image is too old. You may need to build the image with the Dockerfile manually.

https://github.com/wenet-e2e/wenet/blob/main/runtime/server/x86/docker/Dockerfile
