### ISSUE TITLE
In func tar_file_and_group, torchaudio.load cannnot deal with file_obj when trainning with data_type "shard"

### ISSUE THREAD

**Issue by Kanraaaaa** [wenet-e2e/wenet#826]
When trainning with data_type "shard”，stream extracts txt file and flac file from tar file. But torchaudio.load cannot deal with flac file_obj.

Error Message:

  File "examples/ppg_model/s1_cn_en/wenet/dataset/processor.py", line 92, in tar_file_and_group
    waveform, sample_rate = torchaudio.load(file_obj)
  File "/home/.local/lib/python3.7/site-packages/torchaudio/backend/sox_backend.py", line 35, in load
    raise OSError("{} not found or is a directory".format(filepath))
OSError: <ExFileObject name=''> not found or is a directory

**Comment by robin1001** [comment]
To load MP3, FLAC, OGG/VORBIS, OPUS and other codecs libsox does not handle natively, your installation of torchaudio has to be linked to libsox and corresponding codec libraries such as libmad or libmp3lame etc.

please see https://pytorch.org/audio/stable/backend.html#load
