### ISSUE TITLE
final.zip，modules folder “_is_full_backward_hook : NoneType”error

### ISSUE THREAD

**Issue by qwerrrrrt** [wenet-e2e/wenet#828]
Hello, I want to generate a new torch model, that is, to generate a library for C + +. There is an extra sentence for each function in the final.zip file I output：“_is_full_backward_hook : NoneType”.
![image](https://user-images.githubusercontent.com/91374065/144185149-ba19bc5e-0445-459f-9427-4a139a208333.png)

However, the corresponding function has not been changed in the original project.As a result, an error will be reported in the program.
![image](https://user-images.githubusercontent.com/91374065/144184433-d1a690f7-1ca9-4322-8eb4-240d4e3757e9.png)
On the left is the pre trained downloaded model, and on the right is the model generated by myself. Moreover, there are differences in the functions in some files. For example, there will be several more functions, but I haven't changed the codes of these parts. How should I adjust them.These files are in the final.zip, torch->nn->modules,like activation.py,conv.py etc.
![image](https://user-images.githubusercontent.com/91374065/144184891-b36c2fdd-4b41-43a5-8f19-0cce2af77558.png)
Thanks a lot!

**Comment by CharlesSL** [comment]
I solved this problem by downgrading pytorch and libtorch version to 1.7, you may try it :)

**Comment by xingchensong** [comment]
pull latest code and retry
