### ISSUE TITLE
export model error

### ISSUE THREAD

**Issue by qwerrrrrt** [wenet-e2e/wenet#831]
According to the tutorial on aishell training model, I also pulled the latest code again, and then ran from step 0 to step 4. Then I ran step 6 to generated my own pretrained model as the C + + interface and generated final.zip. After that, I found an error when I put the final.zip into the Android terminal for reading.
![image](https://user-images.githubusercontent.com/91374065/144438401-f0a7a4e6-8326-49da-8a1c-edcdd6ce9db1.png)
The code was not changed, and the experiment was conducted according to the document. The pulled code was on December 2. Compared with the released pre training model, it was found that there was no such line in the released model you put on the net.
![image](https://user-images.githubusercontent.com/91374065/144438892-95ce979c-8ad3-4f12-adb2-db7a94b31ade.png)
The last question was also raised by me. In that question, I changed part of the model. I think it may be the problem of the model or not using the latest code, but I pulled the latest code again and installed a new environment today. This problem still arises, so there may be some problems, but I read JIT in wenet, There shouldn't be a big problem, but it's strange that this nonetype error is in torch. What can I do to solve the problem? If the pre training model published on the Internet was trained the same way, why is there no such line? Thank you for your answer!
I would really really appreciate it if you could answer my tiny question!!!!

**Comment by xingchensong** [comment]
pull latest code and retry
