### ISSUE TITLE
为什么librispeech的recipe里面没有使用bpe

### ISSUE THREAD

**Issue by godzilla-123** [wenet-e2e/wenet#838]
如题，我尝试跑了librispeech s0的recipe，跑训练(stage 4)的时候发现只把bpe的dict(train_960_unigram5000_units.txt)传进去了，但是没有传--bpe这个参数，结果在dataset tokenize的时候因为没有接收到bpe_model，会导致把label当成一个一个的字母。想问一下为什么要这样设计？

**Comment by robin1001** [comment]
Good catch. It's a bug, now we get it fixed. see https://github.com/wenet-e2e/wenet/pull/847
