### ISSUE TITLE
20211025_conformer_bidecoder_exp 预训练模型

### ISSUE THREAD

**Issue by haojiepan1** [wenet-e2e/wenet#841]
20211025_conformer_bidecoder_exp 没有 global_cmvn 文件，因为wenetspeech过大，自己机器的硬件问题，无法通过运行bash run.sh --stage -1 --stop-stage -1
bash run.sh --stage 0 --stop-stage 0
bash run.sh --stage 1 --stop-stage 1
bash run.sh --stage 2 --stop-stage 2
步骤来生成global_cmvn文件

**Comment by robin1001** [comment]
Sorry about that, we missed it. However you can download the cmvn from https://github.com/wenet-e2e/wenet/tree/main/examples/wenetspeech/s0#conformer.
