### ISSUE TITLE
现在processor.py中bpe的使用方法是不是有问题？

### ISSUE THREAD

**Issue by godzilla-123** [wenet-e2e/wenet#845]
对于用空格分开的语言(比如英语)，bpe encode的时候应该调用的是[这个](https://github.com/google/sentencepiece/blob/master/python/README.md#segmentation)函数把整句句子给encode起来，而不是先按照空格分开再做encode_as_pieces吧？

**Comment by robin1001** [comment]
Good catch! fixed, please see  https://github.com/wenet-e2e/wenet/pull/849/

**Comment by xingchensong** [comment]
hello，从逻辑上看确实应该以句子为单位进行encode，但是实际上无论以句子为单位还是以单词为单位，结果都是一样的。这是因为我们在librispeech recipe中使用了 unigram作为建模单元，如下所示([link](https://github.com/wenet-e2e/wenet/blob/main/examples/librispeech/s0/run.sh#L36-L38))：
```sh
# bpemode (unigram or bpe)
nbpe=5000
bpemode=unigram
```
而在sentencepiece底层源码中，unigram模型的训练（见[代码](https://github.com/google/sentencepiece/blob/master/src/unigram_model_trainer.cc#L466-L526)），在开始前就会先按照空格分词（line485-line487）:
```cpp
if (trainer_spec_.split_by_whitespace()) {
    SplitSentencesByWhitespace();
}
```
`SplitSentencesByWhitespace()`的作用在[这里](https://github.com/google/sentencepiece/blob/master/src/trainer_interface.h#L120-L125)有体现，也即：
```cpp
// Splits all sentencecs by whitespaces and
// replace the |sentences_| with tokenized string.
// e.g.,
//  [ ["hello world ", 1], ["hi world]" ] =>
//  [ ["hello", 1], ["hi", 1], ["world", 2] ]
void SplitSentencesByWhitespace();
```

因此，在inference阶段（encode阶段），以句子为单位和以单词为单位，所得的结果相同。
