### ISSUE TITLE
When is context_graph used?

### ISSUE THREAD

**Issue by dwjdw** [wenet-e2e/wenet#853]
The original code is in https://github.com/wenet-e2e/wenet/blob/main/runtime/core/decoder/params.h#L130. But context_graph isn't set in any of example scripts. When is context graph used and what does it mean?

**Comment by jinsongpan** [comment]
just ref this doc: https://github.com/wenet-e2e/wenet/blob/main/docs/context.md

**Comment by dwjdw** [comment]
Is there any code example for it? Like building a toy grammar consisting of proper nouns in librispeech and aishell, then compose it with TLG using context graph?

**Comment by jinsongpan** [comment]
> 

until now, it 's only used in runtime part.
