### ISSUE TITLE
bash run.sh --stage -1 --stop-stage -1

### ISSUE THREAD

**Issue by zhangyifei1** [wenet-e2e/wenet#854]
bash run.sh --stage -1 --stop-stage -1
stage -1: Data Download
local/download_and_untar.sh: no such directory /export/data/asr-data/OpenSLR/33/
local/download_and_untar.sh: no such directory /export/data/asr-data/OpenSLR/33/

**Comment by jinsongpan** [comment]
> bash run.sh --stage -1 --stop-stage -1 stage -1: Data Download local/download_and_untar.sh: no such directory /export/data/asr-data/OpenSLR/33/ local/download_and_untar.sh: no such directory /export/data/asr-data/OpenSLR/33/

you should create the folder mentioned in the log first.

**Comment by BillKerman** [comment]
May I ask where should I create this directory? I've tried under s0/, s0/local/ , still didn't work ;(
