### ISSUE TITLE
不显示rtf

### ISSUE THREAD

**Issue by BrandnewA** [wenet-e2e/wenet#855]
**Describe the bug**
x86，测试没有出bug，但是不显示rtf

测试命令：
export GLOG_logtostderr=1
export GLOG_v=2
wav_path=your_test_wav_path
model_dir=your_model_dir
./build/decoder_main \
    --chunk_size -1 \
    --wav_path $wav_path \
    --model_path $model_dir/final.zip \
    --dict_path $model_dir/words.txt 2>&1 | tee log.txt

**Comment by robin1001** [comment]
please see https://github.com/wenet-e2e/wenet/blob/main/runtime/core/bin/decoder_main.cc#L134
