### ISSUE TITLE
how to change decoding methods if using c++ example - decoder_main ?

### ISSUE THREAD

**Issue by garymmi** [wenet-e2e/wenet#857]
which decoding method that decoder_main used ?
how to change decoding methods in decoder_main ?

decoidng methods :
    ctc_greedy_search / ctc_prefix_beam_search / attention / attention_rescoring

Thanks

**Comment by robin1001** [comment]
We only support ctc_prefix_beam_search/attention_rescoring in our runtime.

please see https://github.com/wenet-e2e/wenet/blob/main/runtime/core/decoder/params.h#L36.

If the `rescoring_weight` is zero, it's ctc_prefix_beam_search, otherwise it's attention_rescoring.
