### ISSUE TITLE
how can i prepare TLG data for BPE based dataset, like multi_cn

### ISSUE THREAD

**Issue by hellomotor** [wenet-e2e/wenet#862]
I'd like to use WFST based decoder for multi_cn dataset, but when i going to generate TLG for wfst decoder, 
i cannot figure out how to preprare lexicon files, do you have a docs or tutorial for that?

**Comment by robin1001** [comment]
please refer https://github.com/wenet-e2e/wenet/blob/main/examples/librispeech/s0/run.sh#L260
