### ISSUE TITLE
the context biasing that has not yet the end boundary does not subtract the previous offset score.

### ISSUE THREAD

**Issue by luchuanze** [wenet-e2e/wenet#864]
**Describe the issue**

At the end of the ctc prefix search, the context that has not yet the end boundary does not subtract the previous offset score.

**To Reproduce**

My test context is "千玺机器人" ，context_score= 3.0, and my test pronouncing is "qianxi" .  The recognition results are as follows：

![image](https://user-images.githubusercontent.com/32317033/146340351-3e2e73d4-de88-4057-9b4a-301d5c8576a3.png)

When the ctc search was over,  a relatively low score for "迁徙" because the context state of "千玺" was not set to the start state with negative score.

**Expected behavior**

By overwritting 'CtcPrefixBeamSearch.FinalizeSearch()' to fix it ?

**Comment by robin1001** [comment]
@pengzhendong , what do you think?

**Comment by pengzhendong** [comment]
@luchuanze We've talked about this before. You could commit a pr, thanks!

**Comment by luchuanze** [comment]
> @luchuanze我们以前讨论过这个。你可以提交一个公关，谢谢！

**Comment by luchuanze** [comment]
> @luchuanze We've talked about this before. You could commit a pr, thanks!

OK,
