### ISSUE TITLE
Request for supporting BPE in runtime

### ISSUE THREAD

**Issue by iou2much** [wenet-e2e/wenet#865]
It seems the cpp runtime doesn't support BPE feature now?  
Is there any plan to do it recently? 
Or is there any project that I can refer to ? I might help to add this feature to wenet

**Comment by robin1001** [comment]
It's already supported. BPE units are used as the symbol table in decoding. All  we need to do is postprocessing in BPE case. Please see https://github.com/wenet-e2e/wenet/blob/main/runtime/core/post_processor/post_processor.cc#L24

**Comment by iou2much** [comment]
Oh, I see. Thanks a lot.
I searched BPE as keyword in runtime folder, and didn't find any result. So I thought it was not supported yet.
