### ISSUE TITLE
 [CMakeFiles/ctc_prefix_beam_search_test.dir/all] Error 2

### ISSUE THREAD

**Issue by caoshuirong** [wenet-e2e/wenet#866]
**Describe the bug**

collect2: error: ld returned 1 exit status
CMakeFiles/ctc_prefix_beam_search_test.dir/build.make:113: recipe for target '
make[2]: *** [ctc_prefix_beam_search_test] Error 1
make[2]: Leaving directory '/home/student2020/srcao/wenet-main/runtime/server/
CMakeFiles/Makefile2:397: recipe for target 'CMakeFiles/ctc_prefix_beam_search
make[1]: *** [CMakeFiles/ctc_prefix_beam_search_test.dir/all] Error 2
make[1]: Leaving directory '/home/student2020/srcao/wenet-main/runtime/server/
Makefile:158: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by caoshuirong** [comment]
my environment：gcc 5.4.0 + glibc 2.23 can‘t work.

**Comment by pengzhendong** [comment]
log 信息太少了，建议使用 docker 试试
