### ISSUE TITLE
GigaSpeech run.sh stage 1 is painfully slow

### ISSUE THREAD

**Issue by dwjdw** [wenet-e2e/wenet#867]
The problem lies in reading opus file using pytorch + sox backend(https://github.com/wenet-e2e/wenet/blob/main/tools/compute_cmvn_stats.py#L42), it's the bottleneck to the whole thing and sometimes it takes 9 mins when start_frame is large. Is there anything I can do to make it faster?

**Comment by robin1001** [comment]
Yes, it's painful since the corpus is very large. Here is a wav to solve the problem.

![image](https://user-images.githubusercontent.com/6036624/147308190-71c02017-e2f5-435d-b8de-53ce30011e31.png)
