### ISSUE TITLE
windows本地编译，识别结果乱码

### ISSUE THREAD

**Issue by xdqf2128** [wenet-e2e/wenet#882]
Windows本地编译，虽然编译过程有报错
![image](https://user-images.githubusercontent.com/50766766/147315418-2a945ef0-5c20-40b6-b6b0-7878b20232bc.png)
但是decoder_main并没有错误，而且能够正常运行。
但是识别结果会乱码：
![image](https://user-images.githubusercontent.com/50766766/147315457-dc8c82bf-71fb-4c51-a3ce-153026512a67.png)
同样的模型docker编译的识别结果正常：
![image](https://user-images.githubusercontent.com/50766766/147315481-1a977013-832d-47bb-956a-25c5a991e6f9.png)

**Comment by pengzhendong** [comment]
报错的不是  decoder_main，编出来的可执行文件应该没问题，可以检查一下字典和环境啥的

**Comment by xdqf2128** [comment]
> 

是的，执行文件应该没错。字典用的是同一个，这感觉像是编码的问题，这就有点糟糕了。。。。

**Comment by Engineering-Course** [comment]
> > 
> 
> 是的，执行文件应该没错。字典用的是同一个，这感觉像是编码的问题，这就有点糟糕了。。。。

@xdqf2128 请问乱码问题最终怎么解决的呢？

**Comment by xdqf2128** [comment]
> > > 
> > 
> > 
> > 是的，执行文件应该没错。字典用的是同一个，这感觉像是编码的问题，这就有点糟糕了。。。。
> 
> @xdqf2128 请问乱码问题最终怎么解决的呢？

后来发现问题其实挺简单的，不是编译的问题，是在windows上执行的时候，cmd.exe默认编码是GBK，但是程序输出是UTF-8，格式不匹配导致的，只需要先执行`chcp 65001`，把cmd.exe的编码改成UTF-8，再执行程序，打印就正常了

**Comment by pengzhendong** [comment]
![image](https://user-images.githubusercontent.com/10704539/163786043-92970614-2060-4b1f-bcef-2239598082a0.png)

设置后重启电脑即可

**Comment by pengzhendong** [comment]
> Windows本地编译，虽然编译过程有报错 ![image](https://user-images.githubusercontent.com/50766766/147315418-2a945ef0-5c20-40b6-b6b0-7878b20232bc.png) 但是decoder_main并没有错误，而且能够正常运行。 但是识别结果会乱码： ![image](https://user-images.githubusercontent.com/50766766/147315457-dc8c82bf-71fb-4c51-a3ce-153026512a67.png) 同样的模型docker编译的识别结果正常： ![image](https://user-images.githubusercontent.com/50766766/147315481-1a977013-832d-47bb-956a-25c5a991e6f9.png)

上述问题均已解决，提示换行符是因为里面有中文，已经在 CMakeLists.txt 里面支持了。
websocket_client_main 报错可能是因为 gflags 定义的 host 变量冲突了，已经改成了 hostname。

**Comment by xdqf2128** [comment]
> > Windows本地编译，虽然编译过程有报错 ![image](https://user-images.githubusercontent.com/50766766/147315418-2a945ef0-5c20-40b6-b6b0-7878b20232bc.png) 但是decoder_main并没有错误，而且能够正常运行。 但是识别结果会乱码： ![image](https://user-images.githubusercontent.com/50766766/147315457-dc8c82bf-71fb-4c51-a3ce-153026512a67.png) 同样的模型docker编译的识别结果正常： ![image](https://user-images.githubusercontent.com/50766766/147315481-1a977013-832d-47bb-956a-25c5a991e6f9.png)
> 
> 上述问题均已解决，提示换行符是因为里面有中文，已经在 CMakeLists.txt 里面支持了。 websocket_client_main 报错可能是因为 gflags 定义的 host 变量冲突了，已经改成了 hostname。

好的，感谢

**Comment by xzwworkplace** [comment]
你好，我在linux上测试成功了，想在window上测试一下，没有windows下使用的经验，请问在windows上怎么运行decoder_main这个工具呀

**Comment by pengzhendong** [comment]
> 你好，我在linux上测试成功了，想在window上测试一下，没有windows下使用的经验，请问在windows上怎么运行decoder_main这个工具呀

https://github.com/wenet-e2e/wenet/blob/main/.github/workflows/windows.yml
