### ISSUE TITLE
fstaddselfloops: 未找到命令

### ISSUE THREAD

**Issue by pythonLiNM** [wenet-e2e/wenet#885]
tools/fst/compile_lexicon_token_fst.sh: 行 83: fstaddselfloops: 未找到命令
ERROR: FstHeader::Read: Bad FST header: standard input

在调试librispeech的语言模型时,报以上错误,请问是还要安装什么吗?百度说是安装kaldi相关环境

**Comment by pengzhendong** [comment]
这个是 kaldi 的工具 ，wenet  已经复制过来了，需要到 runtime/server/x86 里编译一下

**Comment by python-linming** [comment]
谢谢,明了了,还有个问题请教 一下,代码中有下载语言模型,好像在后期没用?
![image](https://user-images.githubusercontent.com/50547107/147344585-1bf59672-ee21-405d-8b9a-2beec34bf1ca.png)

**Comment by LRY1994** [comment]
想问怎们编译，已经运行成功了
cmake -DINTTYPES_FORMAT:STRING=C99 -DGRAPH_TOOLS=ON ..
cmake -DCMAKE_CXX_COMPILER=/usr/local/gcc/bin/g++ .

还是会出现tools/fst/compile_lexicon_token_fst.sh: 行 83: fstaddselfloops: 未找到命令
ERROR: FstHeader::Read: Bad FST header: standard input

**Comment by zth-1024** [comment]
我也是这个错误，有没有解决方案啊
