### ISSUE TITLE
feature_pipeline.cc ReadOne 并发逻辑不正确

### ISSUE THREAD

**Issue by panpan-wu** [wenet-e2e/wenet#893]
```c++
bool FeaturePipeline::ReadOne(std::vector<float>* feat) {
  if (!feature_queue_.Empty()) {
    *feat = std::move(feature_queue_.Pop());
    return true;
  } else {
    std::unique_lock<std::mutex> lock(mutex_);
    while (!input_finished_) {
      // This will release the lock and wait for notify_one()
      // from AcceptWaveform() or set_input_finished()
      finish_condition_.wait(lock);
      if (!feature_queue_.Empty()) {
        *feat = std::move(feature_queue_.Pop());
        return true;
      }
    }
    CHECK(input_finished_);
    CHECK(feature_queue_.Empty());
    return false;
  }
}
```

假如时序如下逻辑会有问题：
1. 读线程判断 feature_queue_.Empty() 为 true，代码准备执行 else
2. 写线程执行 AcceptWaveform 并且设置 input_finished_
3. 读线程开始执行 else 部分，input_finished_ 为 true，所以不执行 while 循环体，CHECK(feature_queue_.Empty()) 会失败

**Comment by robin1001** [comment]
Any test case?

Here read/write is controlled by mutex and lock.

**Comment by panpan-wu** [comment]
C++ is hard to test, so I use python to reproduce it.

```python
from queue import Queue
from threading import Condition, Lock
import threading
import time


class FeaturePipeline:

    def __init__(self):
        self._que = Queue()
        self._lock = Lock()
        self._cond = Condition(self._lock)
        self._input_finished = False

    def set_input_finished(self) -> None:
        assert self._input_finished is False
        with self._lock:
            self._input_finished = True

    def accept_waveform(self, num: int) -> None:
        self._que.put(num)
        with self._cond:
            self._cond.notify(1)

    def read_one(self) -> int:
        if not self._que.empty():
            return self._que.get()
        time.sleep(2). # 加上这句更容易让问题复现
        with self._cond:
            while not self._input_finished:
                self._cond.wait()
                if not self._que.empty():
                    return self._que.get()
        assert self._input_finished
        assert self._que.empty()


def write(feature_pipeline):
    for i in range(10):
        feature_pipeline.accept_waveform(i)
        print("write:", i)
        time.sleep(0.1)
    feature_pipeline.set_input_finished()


def read(feature_pipeline):
    while True:
        res = feature_pipeline.read_one()
        print("read:", res)
        if res is None:
            break


def main():
    feature_pipeline = FeaturePipeline()
    write_thread = threading.Thread(target=write, args=(feature_pipeline,))
    read_thread = threading.Thread(target=read, args=(feature_pipeline,))
    write_thread.start()
    read_thread.start()


if __name__ == "__main__":
    main()
```

**Comment by robin1001** [comment]
So any idea how should we refine it?

**Comment by panpan-wu** [comment]
我英语不好，能看懂部分英文，但说不明白，所以直接用汉语了。

python 的话，可以输入完成时放个 None 当作标志，类似下面这样：

```python
q = queue.Queue()

def producer(num_workers):
    for _ in range(num_workers):
        q.put(None)

def consumer():
    while True:
        task = q.get()
        if task is None:
            break
```

但 c++ 是静态类型的，要实现上述效果可能会很复杂。一种替代方案是不用并发，即 feature_pipeline 就用普通的 queue，然后 AcceptWaveform 和 Decode 放在一个线程执行，不过要多加一个 state 来表明是数据不足返回的，类似下面这样：

```c++
feature_pipeline->AcceptWaveform(wav);
auto state = decoder->Decode();
if (state == kWaitMoreData) {
  continue;
} 
```

**Comment by robin1001** [comment]
It's necsssary to put AcceptWaveform and Decode in two threads.

**Comment by xingchensong** [comment]
How about this:

```cpp
bool FeaturePipeline::ReadOne(std::vector<float>* feat) {
  if (!feature_queue_.Empty()) {
    *feat = std::move(feature_queue_.Pop());
    return true;
  } else {
    std::unique_lock<std::mutex> lock(mutex_);
    while (!input_finished_) {
      // This will release the lock and wait for notify_one()
      // from AcceptWaveform() or set_input_finished()
      finish_condition_.wait(lock);
      if (!feature_queue_.Empty()) {
        *feat = std::move(feature_queue_.Pop());
        return true;
      }
    }
    CHECK(input_finished_);
    // CHECK(feature_queue_.Empty());
    // double check feature_queue_.Empty()
    if (!feature_queue_.Empty()) {
      *feat = std::move(feature_queue_.Pop());
      return true;
    } else {
      return false;
    }
  }
}
```
special case:
- 触发上面special case的前提条件有两个，一是之前queue是空的，二是input_finished_=True，这说明这个special case实际上只会发生在最后一个chunk（input_finish=true），且在这个chunk前的所有数据都已经被server成功读出（queue为空），因此只需要while-loop后面进行double check即可，此时走第一个分支取走该chunk并返回true，接着decode线程继续向feature_pipeline索要新chunk，但是因为已经处理完最后一个chunk，所以decode线程再次访问readone函数的时候queue必然为空，会走else分支，while-loop必然不执行因为input_finish=True，最后double check也一定会走return false的分支

common case:
- 上面说了该错误只会出现在最后一个chunk，那么common case就对应之前的chunk，假设之前某个时间queue也是空的（这个实际上也是很难出现，这要求model infer速度大于等于接收wav速度），导致又进了while-loop，因为我们知道这个chunk肯定不是最后一个chunk，所以while-loop中的逻辑一定会执行且返回true

**Comment by robin1001** [comment]
Sounds Great. @panpan-wu You can try this in your python code to verify if it could work.

**Comment by panpan-wu** [comment]
测试没问题，不过这样逻辑太复杂了，有一种简化版方案：首先我们给 queue 加个 Close 方法，类似下面这样：

utils/blocking_queue.h

```c++
class QueueClosedError: public std::exception {
    public:
        explicit QueueClosedError(const std::string& msg):msg_(msg){}
        virtual const char* what() const throw() {return msg_.c_str();}
    private:
        const std::string msg_;
};

template <typename T>
class BlockingQueue {
  T Pop1() {
    std::unique_lock<std::mutex> lock(mutex_);
    while (queue_.empty() && !closed_) {
      not_empty_condition_.wait(lock);
    }
    if (queue_.empty() && closed_) {
      throw QueueClosedError("queue closed");
    }
    T t(std::move(queue_.front()));
    queue_.pop();
    not_full_condition_.notify_one();
    return t;
  }

  void Close() {
    std::unique_lock<std::mutex> lock(mutex_);
    if (!closed_) {
      closed_ = true;
      not_empty_condition_.notify_all();
      not_full_condition_.notify_all();
    }
  }
  private:
    bool closed_;
};
```

然后 feature_pipeline.cc 的代码可以简化成下面这样（不再需要锁和 finish_condition_ 了）：

```c++
void FeaturePipeline::set_input_finished() {
  CHECK(!input_finished_);
  feature_queue_.Close();
}

bool FeaturePipeline::ReadOne(std::vector<float>* feat) {
  try {
    *feat = std::move(feature_queue_.Pop1());
    return true;
  } catch (QueueClosedError& e) {
    return false;
  }
}
```

上面这些代码只是一些想法，并没有经过测试，还需要进一步验证。

https://github.com/intuited/CloseableQueue 这是个 Python 版的具有 Close 方法的 Queue，可以参考一下。

**Comment by robin1001** [comment]
> 测试没问题，不过这样逻辑太复杂了，有一种简化版方案：首先我们给 queue 加个 Close 方法，类似下面这样：
> 
> utils/blocking_queue.h
> 
> ```c++
> class QueueClosedError: public std::exception {
>     public:
>         explicit QueueClosedError(const std::string& msg):msg_(msg){}
>         virtual const char* what() const throw() {return msg_.c_str();}
>     private:
>         const std::string msg_;
> };
> 
> template <typename T>
> class BlockingQueue {
>   T Pop1() {
>     std::unique_lock<std::mutex> lock(mutex_);
>     while (queue_.empty() && !closed_) {
>       not_empty_condition_.wait(lock);
>     }
>     if (queue_.empty() && closed_) {
>       throw QueueClosedError("queue closed");
>     }
>     T t(std::move(queue_.front()));
>     queue_.pop();
>     not_full_condition_.notify_one();
>     return t;
>   }
> 
>   void Close() {
>     std::unique_lock<std::mutex> lock(mutex_);
>     if (!closed_) {
>       closed_ = true;
>       not_empty_condition_.notify_all();
>       not_full_condition_.notify_all();
>     }
>   }
>   private:
>     bool closed_;
> };
> ```
> 
> 然后 feature_pipeline.cc 的代码可以简化成下面这样（不再需要锁和 finish_condition_ 了）：
> 
> ```c++
> void FeaturePipeline::set_input_finished() {
>   CHECK(!input_finished_);
>   feature_queue_.Close();
> }
> 
> bool FeaturePipeline::ReadOne(std::vector<float>* feat) {
>   try {
>     *feat = std::move(feature_queue_.Pop1());
>     return true;
>   } catch (QueueClosedError& e) {
>     return false;
>   }
> }
> ```
> 
> 上面这些代码只是一些想法，并没有经过测试，还需要进一步验证。
> 
> https://github.com/intuited/CloseableQueue 这是个 Python 版的具有 Close 方法的 Queue，可以参考一下。

这个最后还有验证和后续吗？

**Comment by panpan-wu** [comment]
没有验证。最终是把 FeaturePipeline 的 queue 换成了普通版本的（非线程安全），然后在上层（用 go）做并发控制，c++ 这边不再有并发的逻辑，所以就不需要线程安全的 queue 了，解码部分的伪代码：
