### ISSUE TITLE
terminate called after throwing an instance of 'torch::jit::JITException'

### ISSUE THREAD

**Issue by pythonLiNM** [wenet-e2e/wenet#895]
您好，我在使用decoder_main离线转写4分钟以上wav文件时报错
![1640923237(1)](https://user-images.githubusercontent.com/50547107/147802550-991f73af-4ae3-4e8e-bbe5-5315318b20f3.jpg)

**Comment by robin1001** [comment]
add option --continuous_decoding=true.
