### ISSUE TITLE
Adding language model error rate increases rapidly

### ISSUE THREAD

**Issue by kaiAksenov** [wenet-e2e/wenet#900]
I used about 30 hours of data to train a model, and the error rate of the model was normal, about 30%(wer), without language model.When I added the language model and decoded it, the error rate was 127% . 
I thought if I added the language model it would reduce the error rate, but it's not going to reduce it by that much.

The error rate is as high as 120% whether the training data is used to generate a 3-Ngram model or to train a larger language model with additional data.
May I ask what is the possible cause of this, thank you

**Comment by robin1001** [comment]
It's weird. please check:
1. words.txt: for decoding with LM, you should use the words.txt which is generated by LM tools. Do not use the words.txt which is used for training.
2. check your lexicon
3. check your LM.

**Comment by kaiAksenov** [comment]
> It's weird. please check:
> 
> 1. words.txt: for decoding with LM, you should use the words.txt which is generated by LM tools. Do not use the words.txt which is used for training.
> 2. check your lexicon
> 3. check your LM.

I use the words.txt which is generated by LM tools.there are about 50000 words in words.txt. Language models are also generated by training texts.My data set is on OpenSLR, LM and  lexicon should be normal.Have you tested it on a small amount of data ?

**Comment by robin1001** [comment]
We only test it on 200+ hours dataset. However, I think it must be something wrong in your pipeline, the WER is greater than 100%.

**Comment by nocoolsandwich** [comment]
This could be happen when you use runtime decode.The decode_main has a function to detect human voice first,i guess.

**Comment by xingchensong** [comment]
u can refer to this: https://github.com/wenet-e2e/wenet/issues/1673

**Comment by xingchensong** [comment]
and this : https://github.com/wenet-e2e/wenet/issues/1545
