### ISSUE TITLE
onnx runtime error 2: not enough space: expected 318080, got 314240

### ISSUE THREAD

**Issue by piekey1994** [wenet-e2e/wenet#906]
**Describe the bug**
这个bug或许是tritonserver的问题，在使用代码中提供的gpu生产服务（triton server）部署后。直接测试encoder模块时，我需要直接发送fbank的特征到服务器上，此时假如我有三个线程并发的请求，每个线程请求的的step是随机的，也就是fbank的时间步是不一样长的，此时转写的速度会比较慢，但不会报错。这里猜测是由于每个请求的step不一样长，所以没办法组成batch，服务器端的dynamic_batching等待组batch等待耗时较长。于是添加参数max_queue_delay_microseconds等于70000，也就是70ms后就不要等待batch了直接预测，此时客户端就会有一定概率出现异常，异常如下：
Traceback (most recent call last):
  File "debug_encoder.py", line 30, in input_numpy
    response = triton_client.infer("encoder",
  File "/opt/conda/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 1156, in infer
    raise_error_grpc(rpc_error)
  File "/opt/conda/lib/python3.8/site-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] onnx runtime error 2: not enough space: expected 318080, got 314240
此时我请求的三个fbank特征的step是482, 497, 485，dims是80，batch_size是1，318080刚好是497*80*8，也就是模型在预测497那个请求时，莫名遇到空间不足的问题。而且在多次并发请求中，这种错是偶发的，出现后继续请求也有可能成功。如果不并发请求，而是一个个请求的话，则不会报错，如果并发请求的尺寸是固定的也不会报错，只有在并发请求不固定长度的时候，且max_queue_delay_microseconds比较小时会报错。

**Desktop (please complete the following information):**
 - triton server：21.11
 - 服务器 内存16G 显存16G T4显卡，应该不可能是显存或者内存不足

**Comment by Slyne** [comment]
尺寸不同的fbank特征triton中是不会打batch的

另外，在单独测试encoder的时候(不添加feature extractor情况下)，除了fbank特征以外，还需要提供长度信息即speech_lengths，这个数值可以检查一下不要填错。

如果可以的话，提供一个client.py的代码可以复现这个问题最好了，谢谢！

**Comment by piekey1994** [comment]
> 

本地直接用recognize_onnx.py测试是正常的，我的测试脚本如下：
```
import time
import tritonclient.grpc as grpcclient
from tritonclient.utils import np_to_triton_dtype
import numpy as np
import random
import traceback
import asyncio

with grpcclient.InferenceServerClient(url="127.0.0.1:8082") as triton_client_1:

    def input_numpy(feats,feats_lengths):
        triton_client = grpcclient.InferenceServerClient(url="127.0.0.1:8082")
        inputs = [
                grpcclient.InferInput("speech", feats.shape,
                                                np_to_triton_dtype(feats.dtype)),
                grpcclient.InferInput("speech_lengths", feats_lengths.shape,
                                                np_to_triton_dtype(feats_lengths.dtype))
            ]
        inputs[0].set_data_from_numpy(feats)
        inputs[1].set_data_from_numpy(feats_lengths)
        outputs = [
            grpcclient.InferRequestedOutput("encoder_out_lens"),
            grpcclient.InferRequestedOutput("beam_log_probs"),
            grpcclient.InferRequestedOutput("beam_log_probs_idx")
        ]
        # response = triton_client.infer("get_ctc",
        #                 inputs,
        #                 outputs=outputs)
        try:
            response = triton_client.infer("encoder",
                            inputs,
                            outputs=outputs)
        except Exception as err:
            print(traceback.format_exc(),feats_lengths)

    async def task(feat_len):
        # feat_len = (feat_len-400)//160+1
        loop = asyncio.get_event_loop()
        feats = np.random.randn(1,feat_len,80).astype(np.float32)
        feats_lengths = np.array([[feat_len]],dtype=np.int32)
        # time.sleep(random.randint(0,2))
        await loop.run_in_executor(None,input_numpy,feats,feats_lengths)
            
    async def main():
        for _ in range(100):
            max_len = random.randint(5*16000,9*16000)
            min_len = random.randint(1*16000,5*16000)
            num = random.randint(3,10)
            lens = [(random.randint(min_len,max_len)-400)//160+1 for _ in range(num)]
            print(lens)
            tasks=[]
            for feat_len in lens:
                tasks.append(task(feat_len))
            await asyncio.gather(*tasks)
    
    asyncio.get_event_loop().run_until_complete(main())
```
我的encoder的配置如下：
```
name: "encoder"
backend: "onnxruntime"
default_model_filename: "encoder.onnx"

max_batch_size: 32
input [
  {
    name: "speech"
    data_type: TYPE_FP32
    dims: [-1, 80]
  },
  {
    name: "speech_lengths"
    data_type: TYPE_INT32
    dims: [1]
    reshape: { shape: [ ] }
  }
]

output [
  {
    name: "encoder_out_lens"
    data_type: TYPE_INT32
    dims: [1]
    reshape: { shape: [ ] }
  },
  {
    name: "beam_log_probs"
    data_type: TYPE_FP32
    dims: [-1, 10]
  },
  {
    name: "beam_log_probs_idx"
    data_type: TYPE_INT64
    dims: [-1, 10]
  }
]

dynamic_batching {
    max_queue_delay_microseconds: 70000
}


instance_group [
    {
      count: 1
      kind: KIND_GPU
    }
]
```
最后我把bug也提给了nvidia：
https://github.com/triton-inference-server/server/issues/3776

最后的最后，我最近吧onnx换成jit在triton里面部署，就没有这个问题了，但是吞吐没有onnx好，谢谢大佬

**Comment by Slyne** [comment]
@piekey1994  JIT的config.pbtxt里面看看有没有设置下面这两个参数:
```
parameters: {
key: "INFERENCE_MODE"
    value: {
    string_value:"true"
    }
}
parameters: {
key: "DISABLE_OPTIMIZED_EXECUTION"
    value: {
    string_value:"true"
    }
}
```

onnx这个稍微等等  我研究一下

**Comment by piekey1994** [comment]
这两个参数会让jit的预热时间变为0，且结果变稳定

**Comment by piekey1994** [comment]
换成jit后，速度没有onnx快，而且gpu的利用率上不去，不知道是怎么回事

**Comment by FredZhaoI** [comment]
@piekey1994 你做的是online的还是offline的模型？选择triton，速度比onnxruntime会快一些吗？

**Comment by piekey1994** [comment]
> @piekey1994 你做的是online的还是offline的模型？选择triton，速度比onnxruntime会快一些吗？

我做的是一句话转写的接口，用triton比较方便，不用自己写构造batch的轮子，试过比server-streamer+onnx快

**Comment by Slyne** [comment]
@piekey1994 看起来更像是triton的onnxruntime backend的问题。
Wenet这边我们用的配置是:
```
dynamic_batching {
    preferred_batch_size: [ 16, 32 ]
  }
```
只要设置了preferred batch size 都会开启打batch的功能。

**Comment by piekey1994** [comment]
> @piekey1994 看起来更像是triton的onnxruntime backend的问题。 Wenet这边我们用的配置是:
> 
> ```
> dynamic_batching {
>     preferred_batch_size: [ 16, 32 ]
>   }
> ```
> 
> 只要设置了preferred batch size 都会开启打batch的功能。

就是我本意是想写一个支持不等长input的服务，我就在onnx前加了个python模块，并且开启允许不等长的配置，然后在python里面吧一组input pad到一样长再送往onnx。onnx如果不配置max_queue_delay_microseconds就会特别慢，除非我输入的音频始终是一样长的，一旦长短不一就会特别慢，但是一旦配了max_queue_delay_microseconds就会有一定概率报错。不过这些问题在换成pytorch backend后都解决了

**Comment by Slyne** [comment]
你的python backend + onnx 是ensemble的 还是 BLS调用的？
另一个是我感觉你需要在triton那个issue里贴一下会出问题的 model_repo的链接，给个one drvie或者网盘的链接，不然他们可能一直拖着不解决。
既然这个issue跟wenet没啥关系，我就先close了啊..  有问题你再开。。

**Comment by TonyUSTC** [comment]
你好，我现在也遇到了这个问题。用onnxruntime部署服务，单线程的时候，不会报"not enough space"
这个问题，当线程数增多之后，就会出现。监控内存，也没有溢出。初步定位应该是音频长度变化导致的，但是模型转onnx的时候，特征长度设置的是动态维度。
请问这个问题，后续有解决吗？

**Comment by piekey1994** [comment]
> 你好，我现在也遇到了这个问题。用onnxruntime部署服务，单线程的时候，不会报"not enough space" 这个问题，当线程数增多之后，就会出现。监控内存，也没有溢出。初步定位应该是音频长度变化导致的，但是模型转onnx的时候，特征长度设置的是动态维度。 请问这个问题，后续有解决吗？

triton上有人也有这个问题，但是官方没有给出回应，我现在都改成triton+jit部署了

**Comment by Slyne** [comment]
@TonyUSTC   你也是这个shape的问题吗 还是单纯的OOM ？

@piekey1994 你们要不要参加一个比赛 测一下Tensorrt会不会出问题 
https://tianchi.aliyun.com/specials/promotion/NvidiaHackathon2022?spm=5176.14154004.J_1916026360.2.31fe5699TbaHIX

**Comment by TonyUSTC** [comment]
> @TonyUSTC 你也是这个shape的问题吗 还是单纯的OOM ？
> 
> @piekey1994 你们要不要参加一个比赛 测一下Tensorrt会不会出问题 https://tianchi.aliyun.com/specials/promotion/NvidiaHackathon2022?spm=5176.14154004.J_1916026360.2.31fe5699TbaHIX

shape的问题，不是内存问题，尝试把onnxruntime输入，语音帧数设置固定长度，就没事。

**Comment by TonyUSTC** [comment]
> tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] onnx runtime error 2: not enough space: expected 318080, got 314240
定位到原因了，多线程情况下，多个线程会同时修改你输入的特征长度，比如当前线程输入是497帧，onnxruntime在申请空间的时候，其他线程又修改了特征长度，导致申请空间对不上。

**Comment by piekey1994** [comment]
> 

那最后这个问题该如何解决
