### ISSUE TITLE
libtorch升级至1.10后RTF变慢

### ISSUE THREAD

**Issue by onair1314** [wenet-e2e/wenet#908]
wenet论文中提到的RTF benchmark如下：
![image](https://user-images.githubusercontent.com/40174566/148911738-38ca96f9-789b-429e-938d-23538957abe3.png)

wenet v1.0.0版本默认pytorch版本为1.6，故runtime中对应的libtorch版本也为1.6，针对dockerfile中提供的默认模型20210602_unified_transformer_server.tar.gz，采用runtime中decoder_main对自有测试集（200条16k的wav）进行测试，chunk_size设置为-1，其他参数均为默认配置，得到RTF约为0.06，与论文中基本一致；

目前（2022-01-11）wenet main分支代码中，默认pytorch版本为1.10，对应libtorch也为1.10，针对wenetspeech中提供的官方模型20211025_conformer_exp.tar.gz，采用runtime中decoder_main针对上述同一测试集进行测试，RTF约为0.2，与论文中相差甚远；

由于pytorch向下兼容，因此采用libtorch1.10版本测试pytorch1.6版本训练出来的模型20210602_unified_transformer_server.tar.gz，RTF仍为0.2，与论文中相差甚远；

上述结果分别在三台不同ubuntu物理机中测试，测试时CPU均为空闲状态，测试结果完全一致

当测试集为1000条音频时，最终的RTF降至0.085，但decode前200条音频的RTF仍为0.2
不知道是本人配置出现问题导致RTF变慢还是其他什么问题，请各位大神解惑答疑

**Comment by robin1001** [comment]
论文中的模型是 aishell 的模型小一些，100 多M。
wenetspeech 的模型很大，400 多M。

**Comment by onair1314** [comment]
> 论文中的模型是 aishell 的模型小一些，100 多M。 wenetspeech 的模型很大，400 多M。

但我使用libtorch1.10测试aishell的100多M的小模型，RTF仍然很高，为0.2

**Comment by pengzhendong** [comment]
不少人都遇到了 libtorch 1.10.0 比较慢的问题
1. 可以换成 1.10.1 试试，如果问题解决的话希望提一个 pr
2. 实在不行就用回老版本

**Comment by FredZhaoI** [comment]
我也遇到了同样的问题

**Comment by onair1314** [comment]
回退到老版本速度正常

**Comment by cliffchen123** [comment]
I meet #744 when backing to v1.9.0.
Is there any better way to solve both problems at the same time?

**Comment by pengzhendong** [comment]
@cliffchen123 Could you try v1.10.1?

**Comment by cliffchen123** [comment]
@pengzhendong I try the v1.10.1. There is also the speed problem  in this version.
This problem seems to be more serious when the chunk size is smaller
