### ISSUE TITLE
empty vector check needed in decoder_main

### ISSUE THREAD

**Issue by 1215thebqtic** [wenet-e2e/wenet#910]
When I use the runtime binary to decode an audio with long silence at beginning, the program is exited with segmentation fault. And I checked the code,
In decoder_main.cc, line 90: 
```
     if (state == wenet::DecodeState::kEndpoint) {
        decoder.Rescoring();
        final_result.append(decoder.result()[0].sentence);
        decoder.ResetContinuousDecoding();
      }
```
when rule1 of ctc end point detection (the audio starts with silence longer than 5000ms) is triggered, nothing is decoded, then decoder.result() is empty, resulting in segmentation fault. I think a check like this is needed here:
```
      if (state == wenet::DecodeState::kEndpoint) {
        decoder.Rescoring();
        if (!decoder.result().empty()){
        final_result.append(decoder.result()[0].sentence);
        }
        decoder.ResetContinuousDecoding();
      }
```

**Comment by robin1001** [comment]
Good catch, please make a PR.

**Comment by pengzhendong** [comment]
Related to issue https://github.com/wenet-e2e/wenet/issues/912.
