### ISSUE TITLE
Reset() in ctc prefix beam search results in the failure of  equality check in UpdateFinalContext()

### ISSUE THREAD

**Issue by 1215thebqtic** [wenet-e2e/wenet#912]
I use the runtime decoder_main binary to decode using the prefix beam search. Some audios raise the following errors (sorry for the partial error backtrace because I'm not allowed to copy anything from my company's server to the public):
`
ctc_prefix_beam_search.cc:200 Check failed: hypotheses_.size() == cur_hyps_.size() (0 vs. 1)
*** Check failure stack trace: ***
google::LogMessage::Fail()
...
...
wenet::CtcPrefixBeamSearch::UpdateFinalContext()
wenet::CtcPrefixBeamSearch::FinalizeSearch()
wenet::TorchAsrDecoder::AttentionRescoring()
wenet::TorchAsrDecoder::Rescoring()
`

I read the related code, the error is raised under the following condition: 
the decoder is in `kEndpoint` state, after rescoring, the decoder will calll `ResetContinuousDecoding()` in `decoder_main.cc`, and then `searcher_.Reset()` in `torch_asr_decoder.cc`. Then the decoder changes to `kEndFeat` state, the decoder will do rescoring directly, `searcher_` will finally call the `UpdateFinalContext()` function, resulting in check failed error. I think it's because of the Reset() function in ctc prefix beam search: 

original code of Reset() in ctc_prefix_beam_search.cc:
```
cur_hyps_[empty] = prefix_score;
```

I think `hypotheses_` and `likelihood_` should also be initialized to satisfy the equality check, but I'm not sure whether the initialization of these two members will lead to other issues, please let me know if this will result in other issues.
```
cur_hyps_[empty] = prefix_score;
hypotheses_.emplace_back(empty);
likelihood_.emplace_back(prefix_score.total_score());
```

**Comment by robin1001** [comment]
It's better to debug the problem.
@pengzhendong you can also look at the problem.

**Comment by pengzhendong** [comment]
@1215thebqtic No other issues, pr please.

**Comment by pengzhendong** [comment]
Fixed. https://github.com/wenet-e2e/wenet/pull/967
