### ISSUE TITLE
Question :: How word start/end are aligned to audio timestamps? 

### ISSUE THREAD

**Issue by madkote** [wenet-e2e/wenet#926]
**Describe the bug**
I would like to align word start/end to the actual audio stream.
E.g. `Hello World` --> `Hello[0.16:0.20] World[0.31:0.40]`, where e.g. `0.31` is in measurement in seconds.

The actual output is
```
{
      "score" : -2.402725,
      "sentence" : "hello wolrd",
      "words" : [{
          "end" : 600,
          "start" : 0,
          "word" : "▁HELLO"
        }, {
          "end" : 960,
          "start" : 600,
          "word" : "▁WORLD"
        }
    ]
}
```
and this is not aligned to the audio.

More over, when looking at words, the end of the previous word is always the start of the next word independent of the speaker pause between words.

thanks!

**Comment by robin1001** [comment]
Yes, e2e based method could not get the accurate boundary as traditional ASR system. So we just give a reference timestamp.
