### ISSUE TITLE
More deletion error when using TLG decode

### ISSUE THREAD

**Issue by cliffchen123** [wenet-e2e/wenet#929]
When using TLG to decode, I try to rise acoustic_scale. Although it bring better CER, it also caused more deletion error.
Any good method can adjust weight of acoustic and graphic without causing deletion error?

**Comment by robin1001** [comment]
Adding LM always results in more deletion error.

**Comment by Arrivederci** [comment]
> Adding LM always results in more deletion error.
I meet the same problem, Could you explain why LM always leads to more deletion error?
Thanks

**Comment by Arrivederci** [comment]
@cliffchen123 Did you use the code in wenet runtime? I can't find where to add a del penalty

**Comment by cliffchen123** [comment]
@Arrivederci I add deletion penalty to graph_cost of wfst decoding.
@robin1001 Do you think it is necessary to propose a PR?

**Comment by Yymax-max** [comment]
Adding LM always results in more deletion error.
I also meet the same problem.can you give some idea ,thank

**Comment by kangj13** [comment]
> @Arrivederci I add deletion penalty to graph_cost of wfst decoding. @robin1001 Do you think it is necessary to propose a PR?

I met same problem, can you propose a PR?  Thanks

**Comment by Arrivederci** [comment]
> > @Arrivederci I add deletion penalty to graph_cost of wfst decoding. @robin1001 Do you think it is necessary to propose a PR?
> 
> I met same problem, can you propose a PR? Thanks

@cliffchen123 that would be very helpful

**Comment by robin1001** [comment]
> @Arrivederci I add deletion penalty to graph_cost of wfst decoding. @robin1001 Do you think it is necessary to propose a PR?

please make a PR to show how it works.
