### ISSUE TITLE
wav文件识别报错

### ISSUE THREAD

**Issue by ZhengHui-Z** [wenet-e2e/wenet#930]
#### wav文件格式：
General
Complete name                            : output.wav
Format                                   : Wave
File size                                : 7.41 MiB
Duration                                 : 4 min 2 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 256 kb/s
Writing application                      : Lavf59.6.100

Audio
Format                                   : PCM
Format settings                          : Little / Signed
Codec ID                                 : 1
Duration                                 : 4 min 2 s
Bit rate mode                            : Constant
Bit rate                                 : 256 kb/s
Channel(s)                               : 1 channel
Sampling rate                            : 16.0 kHz
Bit depth                                : 16 bits
Stream size                              : 7.41 MiB (100%)

#### 报错信息：

```
I0126 02:51:33.921983   283 params.h:125] Use symbol table as unit table
I0126 02:51:35.632484   283 decoder_main.cc:66] num frames 24286
I0126 02:51:35.645773   283 torch_asr_decoder.cc:111] Required 2147483647 get 24286
terminate called after throwing an instance of 'torch::jit::JITException'
  what():  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/wenet/transformer/embedding.py", line 17, in forward_encoder_chunk
      pass
    else:
      ops.prim.RaiseException("Exception")
      ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _1 = torch.to(self.pe, ops.prim.device(x), None, False, False)
    self.pe = _1

Traceback of TorchScript, original code (most recent call last):
  File "/export/expts6/di.wu/github/del/wenet/examples/aishell/s0/wenet/transformer/embedding.py", line 59, in forward_encoder_chunk
            torch.Tensor: for compatibility to RelPositionalEncoding
        """
        assert offset + x.size(1) < self.max_len
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        self.pe = self.pe.to(x.device)
        pos_emb = self.pe[:, offset:offset + x.size(1)]
RuntimeError: Exception
```
#### 测试指令
cd /home/wenet/runtime/server/x86
export GLOG_logtostderr=1
export GLOG_v=2

./build/decoder_main \
    --chunk_size -1 \
    --wav_path /home/wenet/model/wav/output.wav \
    --model_path /home/wenet/model/final.zip \
    --dict_path $model_dir/words.txt 2>&1 | tee log.txt

#### 问题：
- 预训练模型支持的wav格式有什么要求？

**Comment by day9011** [comment]
音频太长，采用模拟流式测试较好。
