### ISSUE TITLE
undefined reference 

### ISSUE THREAD

**Issue by lucylqe** [wenet-e2e/wenet#931]
我在CentOS7上编译decoder_main二进制       提示编译错误   我定位到下面这一行命令过不去
g++  -std=c++11 -pthread -fPIC  -D_GLIBCXX_USE_CXX11_ABI=0 -DC10_USE_GLOG   CMakeFiles/fsttablecompose.dir/fstbin/fsttablecompose.cc.o  -o fsttablecompose   -L/proj/wenet/runtime/server/x86/fc_base/openfst-subbuild/openfst-populate-prefix/lib  -Wl,-rpath,/proj/wenet/runtime/server/x86/fc_base/openfst-subbuild/openfst-populate-prefix/lib -ldl libkaldi-fstext.a libkaldi-util.a libkaldi-base.a ../libutils.a -lfst -ldl   

请问为啥呢一直提示找不到 为啥呢   我看 libfst.so 也都正常编译出来了
kaldi-fst-io.cc:(.text+0x209): undefined reference to `fst::FstHeader::Read(std::istream&, std::string const&, bool)'
kaldi-fst-io.cc:(.text+0x2d0): undefined reference to `fst::FstReadOptions::FstReadOptions(std::string const&, fst::FstHeader const*, fst::SymbolTable const*, fst::SymbolTable const*)'

**Comment by robin1001** [comment]
编译问题请统一用 docker 编译。
