### ISSUE TITLE
How can I build runtime with Intel OneDNN?

### ISSUE THREAD

**Issue by dahanhan** [wenet-e2e/wenet#932]
I installed latest Intel OneDNN and MKL from its official release 2022.0.2, then run 'source /opt/intel/oneapi/setvars.sh' to let OneDNN and MKL environment settings in effect.
I started to build wenet on local:
_cd runtime/server/x86
mkdir build
cd build
cmake ..
make -j8_

The errors happened in the linking to indicate that all functions 'mkl_xxx' are not defined which is used by libmkl_intel_thread.so. Below are selected from hundreds of lines of Error info:
/usr/bin/ld: /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so: undefined reference to `mkl_spblas_lp64_zzeros'
/usr/bin/ld: /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so: undefined reference to `mkl_lapack_xzpttrs'
/usr/bin/ld: /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so: undefined reference to `mkl_spblas_ccsr1ttlnf__smout_par'
/usr/bin/ld: /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so: undefined reference to `mkl_pds_lp64_fct_cmplx_block'
/usr/bin/ld: /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so: undefined reference to `mkl_spblas_dcsr0ttluc__mmout_par'
/usr/bin/ld: /opt/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so: undefined reference to `mkl_feast_dfeast_scsrev'
......

 I also installed the docker image on my server. Although the inference can be run but I notice there is no MKL and OneDNN is installed. I guess the docker image doesn't utilize OneDNN, right?
My server is an ICL and OS is Ubuntu 20.04.

**Comment by robin1001** [comment]
I think if you want it works, your libtorch should be built with the specific OneDNN and MKL.
