### ISSUE TITLE
Init self.concat_linear only when concat_after = True.

### ISSUE THREAD

**Issue by kobenaxie** [wenet-e2e/wenet#947]
https://github.com/wenet-e2e/wenet/blob/384f9356cc25848175dacda32e08d9c9a6c4ad52/wenet/transformer/encoder_layer.py#L177
default `concat_after = False`, so there is no need init the `self.concat_linear` layer,  need only init this layer when `concat_after = True`,  otherwise leads to a never used `nn.Parameter` in `self.concat_linear`; 
```
if self.concat_after:
    self.concat_linear = nn.Linear(size + size, size) 

 ```

**Comment by robin1001** [comment]
Could you help to make a PR?

**Comment by kobenaxie** [comment]
[fixed](https://github.com/wenet-e2e/wenet/commit/2e9efcfd3118bec0db3a3f9f157a7e59bacde9c0)
