### ISSUE TITLE
nbest option

### ISSUE THREAD

**Issue by RuslanSel** [wenet-e2e/wenet#950]
How to set nbest option?
./tools/decode.sh: invalid option --nbest
Thanks in advance.

**Comment by rookie0607** [comment]
> How to set nbest option? ./tools/decode.sh: invalid option --nbest Thanks in advance.

Have you solved “CV loss oscillates near 140 from start ” problem?

**Comment by RuslanSel** [comment]
For train.py - no.
But train_deprecated.py with unigram 800 doesn't have that problem.

**Comment by robin1001** [comment]
Use --output_nbest in decoder_main, please see https://github.com/wenet-e2e/wenet/blob/main/runtime/core/bin/decoder_main.cc#L19
