### ISSUE TITLE
aishell例子中的语言模型运行失败

### ISSUE THREAD

**Issue by yuzhang112** [wenet-e2e/wenet#955]
我运行run.sh中的第七步，想把语言模型添加进去进行测试。但出现了问题。

file data/local/lm/heldout: 10000 sentences, 89496 words, 0 OOVs
0 zeroprobs, logprob= -272791.2 ppl= 551.7352 ppl1= 1117.077
tools/fst/compile_lexicon_token_fst.sh: line 59: fstcompile: command not found
tools/fst/compile_lexicon_token_fst.sh: line 60: fstarcsort: command not found
Traceback (most recent call last):
  File "tools/fst/ctc_token_fst.py", line 22, in <module>
    print('{} {} {} {}'.format(node, 2, '<eps>', '<eps>'))
BrokenPipeError: [Errno 32] Broken pipe
tools/fst/make_tlg.sh: line 23: arpa2fst: command not found
tools/fst/make_tlg.sh: line 23: fstprint: command not found
tools/fst/make_tlg.sh: line 24: fstcompile: command not found
tools/fst/make_tlg.sh: line 26: fstrmepsilon: command not found
tools/fst/make_tlg.sh: line 26: fstarcsort: command not found
Checking how stochastic G is (the first of these numbers should be small):
tools/fst/make_tlg.sh: line 30: fstisstochastic: command not found
tools/fst/make_tlg.sh: line 33: fsttablecompose: command not found
tools/fst/make_tlg.sh: line 33: fstdeterminizestar: command not found
tools/fst/make_tlg.sh: line 34: fstminimizeencoded: command not found
tools/fst/make_tlg.sh: line 34: fstarcsort: command not found

**Comment by robin1001** [comment]
![image](https://user-images.githubusercontent.com/6036624/155838985-d689c30c-92aa-429b-9c0e-6e8ca997160a.png)

**Comment by xpanp** [comment]
这里在跑librispeech例子的时候遇到了一样的问题。编译的时候，这里cmake应该要加上一个参数
cmake -DFST_HAVE_BIN=ON ..
