### ISSUE TITLE
context biasing can't work with LatticeFasterOnlineDecoder::GetBestPath()

### ISSUE THREAD

**Issue by 1215thebqtic** [wenet-e2e/wenet#956]
In order for quick online decoding, our ASR engine calls `LatticeFasterOnlineDecoder::GetBestPath()`, not generating lattice, to get temporary transcripts every 1 second. I'm using ctc wfst beam search with context biasing. It turns out that the best path from the `GetBestPath()` are different from the best path in the lattice and it seems that context biasing does not take any effect in `GetBestPath()`. 

I read the context biasing related code, the `context_score` is only substracted from the `graph_cost` of `ForwardLink` in `Token`, however the `tot_cost` of `Token` does not substract the `context_score`. `GetLattice` uses `ForwardLink` in `Token` to form lattice and get best path from the lattice, however `LatticeFasterOnlineDecoder::GetBestPath()` uses `tot_cost` of `Token` to find the best path.

So I think for consistence, the `context_score` should also be substracted from the `tot_cost` in `Token`. I make some small changes to the context biasing code as follows, mainly changing the order, the results become consistent, but I'm not sure whether there are other potential problems. Can you help me with this? Thanks!

Before:
https://github.com/wenet-e2e/wenet/blob/2d4703e0798e667f81ba54e1a53ed4e61fe17589/runtime/core/kaldi/decoder/lattice-faster-decoder.cc#L818-L845

After:  (same change to ProcessNonemmiting)
```
          BaseFloat ac_cost = cost_offset -
                              decodable->LogLikelihood(frame, arc.ilabel),
                    graph_cost = arc.weight.Value(), cur_cost = tok->tot_cost;
          bool is_start_boundary = false;
          bool is_end_boundary = false;
          float context_score = 0;
          int context_state;
          if (context_graph_) {
            if (arc.olabel == 0) {
              context_state = tok->context_state;
            } else {
              context_state = context_graph_->GetNextState(
                  tok->context_state, arc.olabel, &context_score,
                  &is_start_boundary, &is_end_boundary);
              graph_cost -= context_score;
            }
          }
          BaseFloat tot_cost = cur_cost + ac_cost + graph_cost;          
          if (tot_cost >= next_cutoff)
            continue;
          else if (tot_cost + adaptive_beam < next_cutoff)
            next_cutoff =
                tot_cost + adaptive_beam;  // prune by best current token
          // Note: the frame indexes into active_toks_ are one-based,
          // hence the + 1.
          Elem *e_next =
              FindOrAddToken(arc.nextstate, frame + 1, tot_cost, tok, NULL);
          // NULL: no change indicator needed

          if (context_graph_) {
              e_next->val->context_state = context_state;
          }
```

**Comment by robin1001** [comment]
@pengzhendong please follow the problem.
