### ISSUE TITLE
直接运行android项目报以下错误是什么原因呢？

### ISSUE THREAD

**Issue by yaojunqi** [wenet-e2e/wenet#957]
F:\yidao\wenet-main\runtime\device\android\wenet\app\src\main\cpp\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error at F:\yidao\wenet-main\runtime\device\android\wenet\app\src\main\cpp\CMakeLists.txt:50 (add_subdirectory):
  add_subdirectory given source "kaldi" which is not an existing directory.
  
我是把整个项目下载的，kaldi文件夹也是有的，没有改动任何路径、代码只改了gradle版本；直接运行报以上错误，麻烦大佬指教

**Comment by yeyupiaoling** [comment]
@yaojunqi 请问你是怎么解决的？我的也是类似的问题
```
\runtime\android\app\src\main\cpp\CMakeLists.txt:14 (include):
  include could not find load file:

    libtorch

```
