### ISSUE TITLE
Missing word problem

### ISSUE THREAD

**Issue by Yymax-max** [wenet-e2e/wenet#960]
I trained a conformer model and the model has converged.But I had some problems of missing word when I tested.（Test set is from speech-io，so I think it is no problem.）
For example，
{""uid"":""OQPuDLngojA__3_9_0201"",""score"":-4.0,""ter"":26.67,""cor"":11,""sub"":1,""ins"":0,""del"":3}",
REF "['甜', '美', '的', '性', '格', '很', '适', '合', '他', '的', '一', '个', '女', '孩', '子']",
HYP"['*', '*', '*', '性', '格', '很', '适', '合', '她', '的', '一', '个', '女', '孩', '子']"

And I print the nbest and score .
![截屏2022-03-02 下午4 23 20](https://user-images.githubusercontent.com/39081569/156325150-92357351-5f33-4ed7-8bbc-bc2ddb825014.png)

It showed that ctc results are missing some word.if some wrong of my model ,how can I improve it.

**Comment by rookie0607** [comment]
How do you print scores and N-best in decode_main?

**Comment by tianmala** [comment]
I had the same problem . Did you solve this problem？

**Comment by xingchensong** [comment]
try to pad zero at the front of wav
