### ISSUE TITLE
libtorch 1.10 may cause some error

### ISSUE THREAD

**Issue by Mddct** [wenet-e2e/wenet#961]
mkl link issues: https://github.com/pytorch/pytorch/pull/72806

**Comment by Mddct** [comment]
may be shoud bump version to v1.11.0
<img width="1355" alt="Untitled 3" src="https://user-images.githubusercontent.com/4906435/158300707-e57b2323-e81f-4844-8024-3f98ed51aa55.png">

**Comment by robin1001** [comment]
What's the error case? memory leak or other problems?

**Comment by Mddct** [comment]
slower than older versions and need more wamup in some machine。

**Comment by hm-0714** [comment]
> 1.10 libtorch_cpu.so mkl linking bug causes slower than older versions and requires more wamup on some machines

yes，i had the same problem ，so we export jit model  use 1.9
