### ISSUE TITLE
websocket_server_main failed

### ISSUE THREAD

**Issue by xzdong-2019** [wenet-e2e/wenet#962]
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/websocket_server_main.dir/link.txt --verbose=1
/usr/bin/c++   -std=c++14 -pthread -fPIC -D_GLIBCXX_USE_CXX11_ABI=1 -DC10_USE_GLOG   CMakeFiles/websocket_server_main.dir/bin/websocket_server_main.cc.o  -o websocket_server_main   -L/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/openfst-subbuild/openfst-populate-prefix/lib  -Wl,-rpath,/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/openfst-subbuild/openfst-populate-prefix/lib:/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib libwebsocket.a libdecoder.a ../fc_base/libtorch-src/lib/libtorch.so -Wl,--no-as-needed,"/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so" -Wl,--as-needed ../fc_base/libtorch-src/lib/libc10.so -lpthread -Wl,--no-as-needed,"/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch.so" -Wl,--as-needed ../fc_base/libtorch-src/lib/libc10.so ../fc_base/libtorch-src/lib/libkineto.a kaldi/libkaldi-decoder.a kaldi/libkaldi-lat.a kaldi/libkaldi-util.a kaldi/libkaldi-base.a libpost_processor.a libfrontend.a libutils.a -lfst -ldl 
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `operator delete(void*, std::align_val_t)@CXXABI_1.3.11'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `powf@GLIBC_2.27'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `log2f@GLIBC_2.27'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `expf@GLIBC_2.27'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `exp2f@GLIBC_2.27'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `operator new(unsigned long, std::align_val_t)@CXXABI_1.3.11'
/mnt/dongxz/docker/wenet/runtime/server/x86/fc_base/libtorch-src/lib/libtorch_cpu.so: undefined reference to `logf@GLIBC_2.27'
collect2: error: ld returned 1 exit status

CMakeFiles/websocket_server_main.dir/build.make:99: recipe for target 'websocket_server_main' failed

make[2]: *** [websocket_server_main] Error 1
make[2]: Leaving directory '/mnt/dongxz/docker/wenet/runtime/server/x86/build'
CMakeFiles/Makefile2:325: recipe for target 'CMakeFiles/websocket_server_main.dir/all' failed
make[1]: *** [CMakeFiles/websocket_server_main.dir/all] Error 2
make[1]: Leaving directory '/mnt/dongxz/docker/wenet/runtime/server/x86/build'
Makefile:154: recipe for target 'all' failed
make: *** [all] Error 2

system message:
# uname -a
Linux omnisky 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pengzhendong** [comment]
1. Update your version of ubuntu, or GLIBC.
2. Use docker.

**Comment by DaobinZhu** [comment]
请问解决了吗？我也遇到了一样的错误

**Comment by DaobinZhu** [comment]
谢谢东哥，我试一下



---Original---
From: ***@***.***&gt;
Date: Wed, Feb 1, 2023 10:11 AM
To: ***@***.***&gt;;
Cc: "Daobin ***@***.******@***.***&gt;;
Subject: Re: [wenet-e2e/wenet] websocket_server_main failed (Issue #962)




 
删掉 libtorch 下载链接中的 cxx11-abi-
