### ISSUE TITLE
Random output with WFST decoding

### ISSUE THREAD

**Issue by Teenuu** [wenet-e2e/wenet#977]
**Describe the bug**
Decoding with WFST LM is working fine with pre-trained models. But with my own model getting random output using LM decoding. Sample out is given below. Please tell what might be the possible issues.
uttid  Transcription
010010007 yd y yeh y yew yea y yeo
010010041 yi yea yeh yt zoe
010010064 yd y yeh yi qr yea yea yi qgh yi
010010093 yt yea zoe zoggs yields yn y halts y
010010100 yi yi yeh ypu yi yeh yea zog qr y
010010103 yeh yea yeh y
010010144 y yea zoe zoggs yea yd yi
010010231 y yeh yea yeh yeh y y yea
010010281 qr yeo yea yt yi zp yea yl yea yeo
~                                            
**To Reproduce**
1. Used Librispeech s0 recipe
2. Created my own language model and lexicon and acoustic model

**Comment by robin1001** [comment]
Did you get right result when decoding without LM?

**Comment by Teenuu** [comment]
> Did you get right result when decoding without LM?

Yes I got the correct result without LM. I am only facing issue with my own trained model with LM decoding.

**Comment by robin1001** [comment]
010010007 yd y yeh y yew yea y yeo
010010041 yi yea yeh yt zoe
010010064 yd y yeh yi qr yea yea yi qgh yi
010010093 yt yea zoe zoggs yields yn y halts y
010010100 yi yi yeh ypu yi yeh yea zog qr y
010010103 yeh yea yeh y
010010144 y yea zoe zoggs yea yd yi
010010231 y yeh yea yeh yeh y y yea
010010281 qr yeo yea yt yi zp yea yl yea yeo
The random symbols are your modeling unit?

**Comment by Teenuu** [comment]
> 010010007 yd y yeh y yew yea y yeo 010010041 yi yea yeh yt zoe 010010064 yd y yeh yi qr yea yea yi qgh yi 010010093 yt yea zoe zoggs yields yn y halts y 010010100 yi yi yeh ypu yi yeh yea zog qr y 010010103 yeh yea yeh y 010010144 y yea zoe zoggs yea yd yi 010010231 y yeh yea yeh yeh y y yea 010010281 qr yeo yea yt yi zp yea yl yea yeo The random symbols are your modeling unit?

They are not part of model units. These words are there in my lexicon.

**Comment by NathanJHLee** [comment]
I think it's same problem with it.
https://github.com/wenet-e2e/wenet/issues/1673

**Comment by xingchensong** [comment]
please follow https://github.com/wenet-e2e/wenet/issues/1673
