### ISSUE TITLE
The speed of training u2++ under multi-machine and multi-card is slow

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#978]
Hi, according to the experimental data of wennet, the default value of the accum_grad parameter of u2++_conformer is 1, which will affect the speed of multi-machine and multi-card. Why is it set to 1 instead of 4?

**Comment by robin1001** [comment]
The experiments shows 1 gets slightly better result than 4 for u2++. You can set it to 4 to speedup the training.

**Comment by srdfjy** [comment]
thanks @robin1001
