### ISSUE TITLE
About remove_longshortdata

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#979]
Hi, CUDA out of memory occurs when training with the latest version of wenet, is it because the latest version removes the remove_longshortdata operation?

**Comment by robin1001** [comment]
The lastest code remove long short data on-the-fly, please see https://github.com/wenet-e2e/wenet/blob/main/examples/librispeech/s0/conf/train_conformer.yaml#L40-L41

**Comment by srdfjy** [comment]
@robin1001 thanks
