### ISSUE TITLE
Error occurred during computer-CER in examples/HKUST

### ISSUE THREAD

**Issue by LBY-bamboo** [wenet-e2e/wenet#985]
2022-03-22 10:40:24,635 INFO 20041028_124231_A013309_B013310-B-058899-059281 呃我觉得挺好的
2022-03-22 10:40:24,792 INFO 20041028_124231_A013309_B013310-B-059611-059928 巴塞罗纳我一开始我就不喜欢巴西
Traceback (most recent call last):
  File "tools/compute-cer.py", line 414, in <module>
    default_cluster_name = default_cluster(word)
  File "tools/compute-cer.py", line 231, in default_cluster
    unicode_names = [unicodedata.name(char) for char in word]
  File "tools/compute-cer.py", line 231, in <listcomp>
    unicode_names = [unicodedata.name(char) for char in word]
ValueError: no such name
![image](https://user-images.githubusercontent.com/94619869/159398744-a1226197-236a-4949-9265-72e610988d49.png)
How should I solve this mistake?

**Comment by pengzhendong** [comment]
Maybe some chars have no names in unicodedata. Please provide the hyp.

**Comment by LBY-bamboo** [comment]
What is the hyp?

**Comment by pengzhendong** [comment]
Sorry. The decode result.

**Comment by LBY-bamboo** [comment]
This is my decode result.



***@***.***
 
From: 彭震东
Date: 2022-03-22 11:31
To: wenet-e2e/wenet
CC: LBY-bamboo; Author
Subject: Re: [wenet-e2e/wenet] Error occurred during computer-CER in examples/HKUST (Issue #985)
Sorry. The decode result.

**Comment by pengzhendong** [comment]
Please print the `word` before line 231 `unicode_names = [unicodedata.name(char) for char in word]` in `tools/compute-cer.py`.

**Comment by LBY-bamboo** [comment]
The decode result after print (the word before line 231 unicode_names = [unicodedata.name(char) for char in word] in tools/compute-cer.py)


***@***.***
 
From: 彭震东
Date: 2022-03-22 11:36
To: wenet-e2e/wenet
CC: LBY-bamboo; Author
Subject: Re: [wenet-e2e/wenet] Error occurred during computer-CER in examples/HKUST (Issue #985)
Please print the word before line 231 unicode_names = [unicodedata.name(char) for char in word] in tools/compute-cer.py.

**Comment by LBY-bamboo** [comment]
Hello, I have solved the problem in the morning. At present, I pay attention to the related work of wenet. Can you share the chime4 data set with me? I want to compare our work with wenet by the chime4 data set. thank you！


***@***.***
 
From: 彭震东
Date: 2022-03-22 11:36
To: wenet-e2e/wenet
CC: LBY-bamboo; Author
Subject: Re: [wenet-e2e/wenet] Error occurred during computer-CER in examples/HKUST (Issue #985)
Please print the word before line 231 unicode_names = [unicodedata.name(char) for char in word] in tools/compute-cer.py.

**Comment by pengzhendong** [comment]
Sorry. We do not share any data sets except wenetspeech.
Could you share you solution of this problem and close the issue?
