### ISSUE TITLE
Using uio multi-machine multi-card training, the average utilization of gpu is low

### ISSUE THREAD

**Issue by srdfjy** [wenet-e2e/wenet#988]
Hi，Using uio multi-machine multi-card training，shard-local reads data, and the gpu utilization fluctuates. Trying to change prefetch and num_workers has no effect.

1，CPU utilization is not high
2，the memory utilization is not high
3，gpu memory utilization is full

model=conformer

num_utts_per_shard=1000

num_workers=1
prefetch=200

shuffle_buffer=1500
sort_buffer=500
batch_size=16
accum_grad=4

![image](https://user-images.githubusercontent.com/66103286/159648815-c2c55d66-c44a-4180-82bb-e40cfce0b48f.png)

**Comment by WangGewu** [comment]
请问这个问题是如何解决的？
