### ISSUE TITLE
How can we decrease the latency?

### ISSUE THREAD

**Issue by jhkim1993** [wenet-e2e/wenet#995]
**Describe the bug**
I am learning runtime of wenet. I download pre-trained librispeech confermer u++ model then put it into dirtory (docker_resource/model).
Both server and client works, but when running websocket_client, the total latency of decoding wave file is so long that it takes more than 30 sec.
![image](https://user-images.githubusercontent.com/48937483/160567162-b6c43a66-5374-4540-906e-a24dc98ae7f5.png)

Can I know about server's qualification which runs demo in 'https://github.com/wenet-e2e/wenet/tree/main/runtime/server/x86' ? Otherwise, I want to know how can I solve this issue and decrease the total latency of server.

**Comment by robin1001** [comment]
It is slow for the first time, and it will become faster and faster when you test the second, the third. please try.

**Comment by jhkim1993** [comment]
Thanks for solving problem. It works well. Do you know what's the cause of this issue?

**Comment by pengzhendong** [comment]
It need a “warm up” (do some initialization). You  could  pass some random data to the network firstly.

**Comment by wpchenit** [comment]
What data can ensure a successful initialization?
a 2.4s wav file. first time use 9100ms， second time use 5700ms, Next few times use about 100ms.
then recog a new wav file, 11.33s, first time use 24320ms,second time use 4965ms, Next few times use about 340ms.
