### ISSUE TITLE
android thread error

### ISSUE THREAD

**Issue by jldeng3** [wenet-e2e/wenet#996]
when I run the android ,run it in my demo,put error ,I do not how to deal it
    ***** SIGNAL SIGABRT(6)
    
    *******	STACKDUMP *******
    	stack dump [1]  
    	stack dump [2]  __kernel_rt_sigreturn
    	stack dump [3]  abort
    	stack dump [4]  
    	stack dump [5]  
    	stack dump [6]  
    	stack dump [7]  
    	stack dump [8]  _ZN5wenet15FeaturePipeline18set_input_finishedEv
    	stack dump [9]  _ZN5wenet18set_input_finishedEv
    	stack dump [10]  
    	stack dump [11]  
    	stack dump [12]  _ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc
    	stack dump [13]  _ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE
    	stack dump [14]  _ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE
    	stack dump [15]  MterpInvokeStatic
    	stack dump [16]  
    	stack dump [17]  
    	stack dump [18]  artQuickToInterpreterBridge
    	stack dump [19]  
    	stack dump [20]  
    
    Exiting after fatal event  (FATAL_SIGNAL). Fatal type:  SIGABRT
    Log content flushed sucessfully to sink

    --------- beginning of crash
2022-03-29 16:15:50.032 2944-2950/com.pudutech.voiceinteraction.app A/libc: Fatal signal 6 (SIGABRT), code 0 (SI_USER) in tid 2950 (Jit thread pool), pid 2944 (interaction.app)
2022-03-29 16:15:50.291 2944-2976/com.pudutech.voiceinteraction.app A/libc: FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x73978dfd50)

**Comment by robin1001** [comment]
No clue about it.
